### ISSUE TITLE
Showing the same Date when we add 42 months in two different dates

### ISSUE THREAD

**Issue by MirAamirAli** [briannesbitt/Carbon#1002]
Scenario 1st. from Date `30-Aug-2017` and add 42 months result is `2021-03-02`.

```php
$repayment_date = Carbon::parse('30-Aug-2017');
$repayment_date->addDays(0);
$repayment_date->addMonths(42);
echo $repayment_date;
```

The scenario 2nd from Date `02-Sep-2017` and add 42 months result is `2021-03-02`.

```php
$repayment_date = Carbon::parse('02-Sep-2017');
$repayment_date->addDays(0);
$repayment_date->addMonths(42);
echo $repayment_date;
```

**Comment by Glavic** [comment]
Scenario 1:
Date `30-Aug-2017` + 42 months = `2021-02-30`. And since February doesn't have 30 days it overflows to date `2021-03-02`.

Scenario 2:
Date `02-Sep-2017` + 42 months = `2021-02-30` :)

All normal here.

I closed this issue. Reopen if needed.
