### ISSUE TITLE
createFromFormat('m/Y', $value) return wrong Date

### ISSUE THREAD

**Issue by hgod8** [briannesbitt/Carbon#1003]
Hi Everyone,
i have interesting problem, when i 02/2017 over GET sended, Carbon create wrong date? is createFromFormat not correct or this way not normal? 

 **_Simple Request : index.php?month=02/2017_**

`echo $selected_date = Carbon::createFromFormat('m/Y', $request->get('month'));
`
_**return**_:
`2017-03-02 23:44:44
`

**Comment by Acen** [comment]
Seems to be a weird issue with feb.

```>>> $date = Carbon\Carbon::createFromFormat('m/Y', '01/2012');
=> Carbon\Carbon {#918
     +"date": "2012-01-31 11:44:33.000000",
     +"timezone_type": 3,
     +"timezone": "Pacific/Auckland",
   }
`$date = Carbon\Carbon::createFromFormat('m/Y', '02/2012');`
=> Carbon\Carbon {#907
     +"date": "2012-03-02 11:44:41.000000",
     +"timezone_type": 3,
     +"timezone": "Pacific/Auckland",
   }
>>> $date = Carbon\Carbon::createFromFormat('m/Y', '03/2012');
=> Carbon\Carbon {#908
     +"date": "2012-03-31 11:44:46.000000",
     +"timezone_type": 3,
     +"timezone": "Pacific/Auckland",
   }
```

```>>> $date = Carbon\Carbon::createFromFormat('m#Y', '14/2011');
=> Carbon\Carbon {#908
     +"date": "2012-03-02 11:45:31.000000",
     +"timezone_type": 3,
     +"timezone": "Pacific/Auckland",
   }
>>> $date = Carbon\Carbon::createFromFormat('m#Y', '13/2011');
=> Carbon\Carbon {#918
     +"date": "2012-01-31 11:45:42.000000",
     +"timezone_type": 3,
     +"timezone": "Pacific/Auckland",
   }
>>> $date = Carbon\Carbon::createFromFormat('m#Y', '15/2011');
=> Carbon\Carbon {#907
     +"date": "2012-03-31 11:45:47.000000",
     +"timezone_type": 3,
     +"timezone": "Pacific/Auckland",
   }
```

**Comment by kzorluoglu** [comment]
it's work, when if a 01/2017 or 03/2017  - 04/.. - 12/.. sendet, . Only 02/**** is problem.

**Comment by TobiasJ** [comment]
Got the same Issue:
```php
for ($i = 1; $i < 13; $i++) {
    $m = $i < 10 ? '0' . $i : $i;

    echo $m . ': ' 
            . Carbon\Carbon::createFromFormat('m', $m)->format('m') // format for easier readablitiy
            . PHP_EOL; 
}

/* 
Output:
Expected: Actual
01: 01 
02: 03 
03: 03 
04: 05 
05: 05 
06: 07 
07: 07 
08: 08 
09: 10 
10: 10 
11: 12 
12: 12 
*/
```

**Comment by kusabi-software** [comment]
It looks as though you tested this on the 30th/31st. By not supplying the day, is it possible DateTime is creating the date 31st February, which is not possible and then jumping to the next month?

**Comment by Jeemusu** [comment]
This happens because DateTime will always assume it is the current day when an alternative is not supplied as attribute.

Executed on the **22/10/2017**
```
Carbon\Carbon::createFromFormat('m/Y', 11/2017);
_Output: 2017-11-22_
```

Executed on the **31/10/2017**
```
Carbon\Carbon::createFromFormat('m/Y', 11/2017);
_Output: 2017-12-01_
```
As there is no 31st day in November the date skips to the first day of the next month. 

You can supply the day attribute to always get the expected year/month result.

```
Carbon\Carbon::createFromFormat('d/m/Y', "01/11/2017");
_Output: 2017-11-01_
```

**Comment by kylekatarnls** [comment]
We will not change this behavior. For safe dates add the day.

**Comment by Glavic** [comment]
@Jeemusu: just use `!` format:

```php
Carbon\Carbon::createFromFormat('!m/Y', 11/2017);
```

See here: http://php.net/manual/en/datetime.createfromformat.php#refsect1-datetime.createfromformat-parameters what `!` format is:

> Resets all fields (year, month, day, hour, minute, second, fraction and timezone information) to the Unix Epoch. Without !, all fields will be set to the current date and time.

**Comment by Abu3safeer** [comment]
> @Jeemusu: just use `!` format:
> 
> ```
> Carbon\Carbon::createFromFormat('!m/Y', '11/2017');
> ```
> 
> See here: http://php.net/manual/en/datetime.createfromformat.php#refsect1-datetime.createfromformat-parameters what `!` format is:
> 
> > Resets all fields (year, month, day, hour, minute, second, fraction and timezone information) to the Unix Epoch. Without !, all fields will be set to the current date and time.

Thank you.

**Comment by rodrigo-spb** [comment]
> @Jeemusu: just use `!` format:
> 
> ```
> Carbon\Carbon::createFromFormat('!m/Y', '11/2017');
> ```
> 
> See here: http://php.net/manual/en/datetime.createfromformat.php#refsect1-datetime.createfromformat-parameters what `!` format is:
> 
> > Resets all fields (year, month, day, hour, minute, second, fraction and timezone information) to the Unix Epoch. Without !, all fields will be set to the current date and time.

Thank you man !

**Comment by KangYoosam** [comment]
https://github.com/briannesbitt/Carbon/issues/1003#issuecomment-370336838
this helped me.

thanks, @Glavic !
