### ISSUE TITLE
Human readable comparators ? 

### ISSUE THREAD

**Issue by StyxOfDynamite** [briannesbitt/Carbon#1004]
Hi, quick question before I commit to a PR, it may well be that mathematical comparators are opted for for ease of cross language documentation, but I think the main reason I use Carbon is the human readable element.

```php
var_dump($first->eq($second));                     // bool(false)
var_dump($first->ne($second));                     // bool(true)
var_dump($first->gt($second));                     // bool(false)
var_dump($first->gte($second));                    // bool(false)
var_dump($first->lt($second));                     // bool(true)
var_dump($first->lte($second));                    // bool(true)
```
would be available as
```php
var_dump($first->is($second));                     // bool(false)
var_dump($first->isNot($second));                  // bool(true)
var_dump($first->after($second));                  // bool(false)
var_dump($first->gte($second));                    // bool(false) // Not sure the english here, isOrAfter ?
var_dump($first->before($second));                 // bool(true)
var_dump($first->lte($second));                    // bool(true) // As above isOrBefore ?
```

I'm fairly new to OS development, so not sure this is wanted or warranted but thought I'd check ?

**Comment by sebsel** [comment]
I want this too, especially 'before' and 'after'. I always have to wrap my head around whether a time is greater than or less than if it's before or after.

**Comment by kylekatarnls** [comment]
I think there already are enough aliases for comparisons: http://carbon.nesbot.com/docs/#api-comparison

And I would prefer isBefore rather than isAfter to be more explicit. As for as I'm concerned, I don't even use those methods, I just use the native PHP operators: `$first > $second`

**Comment by imbrish** [comment]
Yeah, after discovering `$first > $second` works you just never go back!

Nevertheless `gte` could be called `notBefore`.

**Comment by StyxOfDynamite** [comment]
I'm closing then as its probably not needed.
