### ISSUE TITLE
Strict date parsing

### ISSUE THREAD

**Issue by sonOfRa** [briannesbitt/Carbon#1009]
This is somewhat related to #879.

I can't seem to find a way to enable strict date parsing, that would fail for dates like "2017/02/31". Currently, that yields a date "2017/03/03". I ran into this when trying to validate whether or not a user-supplied date was valid, and expected there to be a way to make Carbon strictly parse the date, something like

````php
try {
     $date = Carbon::createFromDateStrict(2017, 02, 31);
} catch (InvalidArgumentException $ex) {
    // Date is somehow invalid
}
// Date is valid
````

Other languages, like Java have a setting for this: https://docs.oracle.com/javase/8/docs/api/java/time/format/ResolverStyle.html

It would be convenient to have this in Carbon as well, instead of the hack that I'm currently using:
````php
$date = Carbon::createFromDate($this->year, $this->month, $this->day);
return ($date->year == $this->year && $date->month == $this->month && $date->day == $this->day);
````

**Comment by Glavic** [comment]
Seams legit. If overflow happens, return error|exception.

**Comment by kylekatarnls** [comment]
In fact, it exists but it's not yet documented, it's `createSafe`

**Comment by kylekatarnls** [comment]
See #1147
