### ISSUE TITLE
Carbon diff confusion

### ISSUE THREAD

**Issue by dubcanada** [briannesbitt/Carbon#101]
Hello,

I am using Carbon and trying to do a diff to show something like `this comment was posted 10 minutes ago`. And I have the following `Carbon::parse($date)->diffForHumans(Carbon::now());` but it keeps saying `before` or `after`. I want it to use `ago`. I can't seem to figure out how to use a passed in datetime and now to find a human readable difference that doesn't have `before` or `after in it, but the proper`ago` term?

Any ideas?

**Comment by zaritzki** [comment]
Hi Brian, 

on this example..
Carbon::parse($date)->diffForHumans(null, true);

having diffForHumans(null, true)  will removed ago.. and how about, I want Abbreviate the dates.

minute to min
minutes to mins

hour to hr
hours to hrs

on so..

Thanks!
