### ISSUE TITLE
Windows 10 - Hungarian

### ISSUE THREAD

**Issue by RajcsanyiZ** [briannesbitt/Carbon#1011]
https://github.com/briannesbitt/Carbon/blob/926aee5ab38c2868816aa760f862a85ad01cb61a/src/Carbon/Carbon.php#L1202

Hello

The Hungarian Windows 10 doesn't support UTF-8 language localization so the output of this function is an empty string. The strftime function works correct, but it's output is iso-8859-2 language set.

$formatted = strftime($format, strtotime($this));

This code works only:
```php
  $formatted = iconv('iso-8859-2', 'UTF-8', strftime($format, strtotime($this)));
```
I've tested with the code above:
```php
  {{ setlocale(LC_ALL, 'hu-HU') }}<br>

    {{ iconv('iso-8859-2', 'UTF-8', strftime(" in Finnish is %A,")) }}<br>
    {{ \Carbon\Carbon::now('Europe/Budapest')->format('Y.m.d. H:i:s') }}<br>
    {{ \Carbon\Carbon::now()->formatLocalized('%A %d %B %Y') }}<br>
    {{ \Carbon\Carbon::now()->addYear()->diffForHumans() }}
```
Zoltan

**Comment by kylekatarnls** [comment]
Hi, sorry for the delay. I strongly recommend in such case to install and use an UTF-8 language package (e.g. `hu-HU.UTF8`).

**Comment by RajcsanyiZ** [comment]
This problem may be a Windows 10 specific problem, baceuse windows doesn't support  hu-HU.UTF8 language pack (I don't know how). But it is only my opinion. I tested this problem with Linux and Docker and everithing worked well.
