### ISSUE TITLE
Locale doesn't work

### ISSUE THREAD

**Issue by zhukovsergey** [briannesbitt/Carbon#1012]
When i use 

```
    Carbon::setLocale('ru'); //it matter on diffs like ago, before, and declension of dates
    setlocale(LC_TIME, "ru_RU.utf8");
    Carbon::now()->addYear()->toFormattedDateString() //'Oct 8, 2018'
```
Locale doesn't work on any formated methods

But it works:
```
    setlocale(LC_TIME, "ru_RU.utf8");
    strftime("%A") //'Воскресенье'
```

**Comment by sn0opy** [comment]
You have to use `formatLocalized()` to actually use the set locale. This method then uses `strftime()` internally. Sample:

```php
 setlocale(LC_TIME, 'ru_RU.UTF-8');¬
 echo Carbon::now()->addYear()->formatLocalized('%A');
```

`toFormattedDateString()` is basically nothing less than `format('M j, Y')`

**Comment by briannesbitt** [comment]
Seems this is answered.  Closing this now but let us know if you think there is still an issue.
