### ISSUE TITLE
[Request] Decimals in functions like  $carbon->addDays(0.5)

### ISSUE THREAD

**Issue by n8-sd** [briannesbitt/Carbon#1014]
As title.
Sometimes things like `$carbon->addDays(0.5)` happen.

**Comment by Glavic** [comment]
What about `$carbon->addHours(0.5 * 24)` ?

**Comment by Glavic** [comment]
Problem I see here that `addX()` methods use [`DateTime::modify`](http://php.net/manual/en/datetime.modify.php), which use [supported date and time formats](http://php.net/manual/en/datetime.formats.php), where there are no decimals for no metric. Based on that I would not modify current methods, maybe add new ones? Next problem you have is rounding, for example `->addSeconds()` with `0.4` or `0.6` would add what?
IMHO this is very user specific thing :/
