### ISSUE TITLE
CreateFromDate should allow for single digit months with 0 in them

### ISSUE THREAD

**Issue by eli4d** [briannesbitt/Carbon#1018]
Hi Brian,

Awesome job on Carbon.

I got bit by this issue that's perfectly described here: https://stackoverflow.com/questions/37287295/why-am-i-getting-invalid-numeric-numeral-using-carbon

For single digit months - it may make sense to have CarbonFromDate accept these months with a 0 as in 08 for August rather than just 8.

Thank you for all that you do.

Eli

**Comment by Glavic** [comment]
Please read http://php.net/manual/en/language.types.integer.php
Number `8` (decimal) is not same as `08` (octal). Proof: https://eval.in/954869
Based on that, this is not Carbon specific issue.
