### ISSUE TITLE
Error parsing date on leap year

### ISSUE THREAD

**Issue by stebogit** [briannesbitt/Carbon#1026]
I'm surprised this hasn't been mentioned so far, but I found this quite unexpected, since 2017 is not a leap year:
```php
Carbon::parse('2017-02-29 10:25')->toDateTimeString(); // "2017-03-01 10:25:00"
Carbon::create(2017, 02, 29)->toDateTimeString(); // "2017-03-01"
```
I believe both the above cases should instead throw an Exception.
 
It seems this is a "known" PHP issue due to his [parsing behavior](https://stackoverflow.com/questions/10120643/php-datetime-createfromformat-functionality/10120725#10120725), but I expected `Carbon` was validating the timestamp input.

However, this was mainly for the records, I love `Carbon`!! 👍

**Comment by Glavic** [comment]
Carbon does not validate input. IMHO you should do that yourself before calling parse/create methods.
This is how php parsing works, and people are used of this behaviour.

_I closed this issue. Reopen if needed._

**Comment by kgrosvenor** [comment]
Is there a work around?

**Comment by kylekatarnls** [comment]
Since this issue was posted, `createSafe` has been added:

```php
Carbon::createSafe(2017, 02, 29)
```

throw an exception `"day : 29 is not a valid value."`
