### ISSUE TITLE
setTestNow not being used when a timestring(hh:mm) is parsed by Carbon

### ISSUE THREAD

**Issue by AGTropus** [briannesbitt/Carbon#1027]
I've encountered the following within my test suite,
And I'm wondering if this is intended behaviour or not.
When I've set a specific timestring for testing Carbon ignores the set time-string when I parse a hh:mm time-string. Using the current date instead.
Below is my test

```
    public function testCarbon()
    {
        $now = Carbon::create(2000,12,22);
        Carbon::setTestNow($now);
        // Check if test is set.
        self::assertTrue(Carbon::hasTestNow());
        // Check if Now is accurate: 2000-12-22.
        self::assertEquals('2000-12-22',Carbon::now()->toDateString(),'now does not match 2000-12-22');
        $time = Carbon::parse('12:00');
        // Check if test is still set.
        self::assertTrue(Carbon::hasTestNow());
        // Check result of Parse.
        self::assertEquals('2000-12-22 12:00:00',$time->toDateTimeString(),'12:00 today does not match expected 2000-12-22 12:00:00');
        $time = Carbon::parse('Tomorrow');
        // Check if test is still set.
        self::assertTrue(Carbon::hasTestNow());
        // Check result of Parse.
        self::assertEquals('2000-12-23',$time->toDateString(),'Tomorrow does not match expected 2000-12-23');
    }
```

And this is the current output:
12:00 today does not match expected 2000-12-22 12:00:00
Failed asserting that two strings are equal.
Expected :'2000-12-22 12:00:00'
Actual   :'2017-11-07 12:00:00'

Are time strings not supported with the parse method for a Carbon object, when the setTestNow() is set?

**Comment by kylekatarnls** [comment]
Sorry for the delay.

The problem is the date you use as now can have any time (12h is not the default value, the default value is current time), so you should use: `$now = Carbon::create(2000, 12, 22, 12, 0, 0);`.

If it does not fix your problem please tell and I'll reopen.
