### ISSUE TITLE
Day of week property

### ISSUE THREAD

**Issue by thekingrat** [briannesbitt/Carbon#1030]
Similar to other properties, it would be nice to have an ISO day of week property (format 'N') without having to use the format method.

**Comment by Glavic** [comment]
Sorry for late reply.

Why not :) Are you interested in making PR? `dayOfWeekIso` ? `dayIsoOfWeek` ?

**Comment by kylekatarnls** [comment]
Will be merged in 1.25 via this PR: #1198
