### ISSUE TITLE
Microseconds stripped when using `setTestNow()` and `now()`

### ISSUE THREAD

**Issue by davidstanley01** [briannesbitt/Carbon#1033]
Hello,

First, I love this library. Thanks to all for your hard work. You've certainly made things easier for me.

## Summary
It appears that the microseconds are being stripped off the object when calling the `Carbon::now()` method and using microseconds. 

## Steps to recreate
PHP version on my local machine is 7.1.8

<img width="447" alt="screen shot 2017-11-16 at 4 27 49 pm" src="https://user-images.githubusercontent.com/844070/32919361-2899e4e6-caeb-11e7-9c8b-bbd8cca32336.png">

I placed the following code in a file called `test.php` within the `src` directory.

Then, I executed it via `php test.php` at the terminal.  

```php
use Carbon\Carbon;

require_once __DIR__.'/../vendor/autoload.php';

$now = new Carbon;
echo $now->format('Y-m-d H:i:s.u') . PHP_EOL;

$now->subDay();
echo $now->format('Y-m-d H:i:s.u') . PHP_EOL;

Carbon::setTestNow($now);

echo Carbon::getTestNow()->format('Y-m-d H:i:s.u') . PHP_EOL;
echo Carbon::now()->format('Y-m-d H:i:s.u') . PHP_EOL;

```

## Result

<img width="193" alt="screen shot 2017-11-16 at 4 19 19 pm" src="https://user-images.githubusercontent.com/844070/32918992-ee42cf8e-cae9-11e7-87b0-8f2756ce5298.png">

As you can see, the microseconds are preserved when manipulating the date as well as after initially calling `Carbon::setTestNow($now)`. However, when calling `Carbon::now()` later on, the microseconds are reset to all zeroes.

I believe the issue occurs because of the `$time = $testInstance->toDateTimeString();` on [line 288](https://github.com/briannesbitt/Carbon/blob/master/src/Carbon/Carbon.php#L288) in `src/Carbon.php`. 

When substituting `$time = $testInstance->format('Y-m-d H:i:s.u')`, things work as expected, and all the tests pass.

<img width="203" alt="screen shot 2017-11-16 at 4 24 39 pm" src="https://user-images.githubusercontent.com/844070/32919258-ba6c092c-caea-11e7-8851-5a415838a9f7.png">

I'm happy to submit a PR for this, but would like a little guidance, first. 

A) Is this something that you see as needing to be fixed?
B) What is the preferred way to solve this (if not the method shown above)?

Thank you,
ds

**Comment by Erutan409** [comment]
Seeing the same thing.  Except, I can't seem to reproduce your successful outputting of microseconds.
