### ISSUE TITLE
Dependencies on Symfony components not stated

### ISSUE THREAD

**Issue by samtuke** [briannesbitt/Carbon#1034]
The documented installation procedure implies that Carbon can work as a standalone PHP file ("Download Carbon.php from the repo and save the file into your project path somewhere."). In fact it depends on three Symfony components (fatal errors ensue without it). Please make this clear in the 'Getting started' docs. For projects not using Composer (or manually including the dependencies), Carbon cannot be used.

**Comment by kylekatarnls** [comment]
Fixed via #1125
