### ISSUE TITLE
Carbon::parse giving counter-intuitive results

### ISSUE THREAD

**Issue by dsandber** [briannesbitt/Carbon#1037]
```
>>> Carbon::parse('2018-Jun-8')
=> Carbon\Carbon {#924
     +"date": "2018-06-01 00:00:00.000000",
     +"timezone_type": 1,
     +"timezone": "-08:00",
   }
```

Google Sheets formats dates like "2018-Jun-8" which is a nice format since it's unambiguous as far as mm-dd vs. dd-mm formatting.  However, Carbon is interpreting that as June 1 with -8 timezone which is problematic.

Strangely, this works fine:

```
>>> Carbon::parse('2018-Jun-22')
=> Carbon\Carbon {#927
     +"date": "2018-06-22 00:00:00.000000",
     +"timezone_type": 3,
     +"timezone": "UTC",
   }
```

I'd much prefer if the date was understood as 2018-Jun-8 in the first case, or perhaps an AmbiguousDateException if there is a reason that both formats should be understood.

**Comment by dsandber** [comment]
Full month name has same problem:

```
>>> Carbon::parse('2018-June-8')
=> Carbon\Carbon {#932
     +"date": "2018-06-01 00:00:00.000000",
     +"timezone_type": 1,
     +"timezone": "-08:00",
   }
```

**Comment by Glavic** [comment]
Parser uses your `-8` or `-22` part as timezone. Your date format is not a standard one: http://php.net/manual/en/datetime.formats.date.php 

Based on that, your should use `::createFromFormat()` instead, like:

```php
Carbon::createFromFormat('!Y-M-j', '2018-Jun-8');
```

**Comment by dsandber** [comment]
It's pretty standard for human beings.  And it's pretty counter-intuitive that 2018-Jun-22 works right while 2018-June-22 doesn't.  My point was just that it would be a lot easier to write bug free code (and to debug) if ambiguous dates threw exceptions rather than the interpretation being arbitrarily chosen.

**Comment by Glavic** [comment]
Like I said, your date format cannot be found [here](http://php.net/manual/en/datetime.formats.date.php). If php cannot resolve what format you have, it will try to "decipher"  what your input is, and for your input it decided to be `Y-MO`, see [here](https://eval.in/955501). All I'm saying is, that you cannot throw anything at php `date_parser()` and hope it can read your mind on what format it is (human readable or not). **For non standard dates, please use `createFromFormat()`.**

**Comment by dsandber** [comment]
Hi Glavic.  I was suggesting that rather than following PHP's date_parser idiosyncrasies, perhaps Carbon should throw an error on any ambiguous input strings.  This would probably save user's time in the long-run.

I understand that this might be problematic due to Carbon's existing user base, or perhaps for some other reasons.

Anyway, I'll close the ticket.

**Comment by Glavic** [comment]
@dsandber: ambiguous input string to you maybe valid for other. Based on that, it is hard to make such validation...

**Comment by kylekatarnls** [comment]
Yes, and I would add "June" is an english word. Should we support arabic, chinese, greek, german, etc. to fulfill all possible missing formats in DateTime? I don't think so.

`Carbon::parse('2018-Jun-8')` works because PHP DateTime handle it. It sounds cool but I would not use it in my app. I would prefer an explicit parsing, handling which languages and formats specifically in each app.

So we keep supporting `Carbon::parse('2018-Jun-8')` just because DateTime does and we try to keep Carbon compatible when possible.
