### ISSUE TITLE
Add version to carbon.php

### ISSUE THREAD

**Issue by cfoellmann** [briannesbitt/Carbon#1038]
I know that using composer is the "only" way to use php libraries right but some people do not use it or can not use it.
So when copying in the library manually to a projects version control you lose any way to identify the version of carbon.
Maybe you can add a `DOCBLOCK @version` to Carbon.php to identify the release versions

**Comment by kylekatarnls** [comment]
I propose to improve the manual installation this way: #1150

By attaching to releases stand-alone packages that contains a PHP 5.3 compatible version of symfony/translation and an autoload.php file to include which contains a `@version` comment.
