### ISSUE TITLE
Diff as CarbonInterval

### ISSUE THREAD

**Issue by ownmaster** [briannesbitt/Carbon#1039]
Is it possible to implement something like `diffAsCarbonInterval()` to return `CarbonInterval`? Because `diff()` comes from `DateTime` and returns `DateInterval`, which feels wrong when you try to work with Carbon objects.

**Comment by kylekatarnls** [comment]
It seems legit to me too. It would need to override `diff()`, but if it's done the right way, it could be a nice adding of possibilities.

It also make me think that all diff* methods could allow DateTime|DateTimeInterface rather than Carbon instances the same way we did with methods isSame*.

**Comment by kylekatarnls** [comment]
Hi, DateInterval produced by diff() that blocks has restrictions that prevent to wrap them in a CarbonInterval. I did not find solution. If someone do, please propose a PR.

**Comment by imbrish** [comment]
@kylekatarnls What was the problem exactly?

**Comment by kylekatarnls** [comment]
Just find the solution by trying to explain the problem: https://3v4l.org/KdcYk
Rubber duck debugging always works.

So the main problem is the CarbonInterval constructor is not compatible with the DateInterval one. Wee need first to allow to pass spec string to create new CarbonInterval. Then we need `instance` to calculate the spec from the DateInterval, then recreate a CarbonInterval with this spec.

Would you be interested in helping for that?

**Comment by imbrish** [comment]
Are there any tests that would be broken before, which your solution fixed?

I cannot wrap my head around why can't we use current implementation of `CarbonInterval::instance`, and just ignore the `days` property.

**Comment by kylekatarnls** [comment]
This is what I tried first and `days` cannot be set when the interval is created from diff, that's why we currently have the exception `'Can not instance a DateInterval object created from DateTime::diff().'` in the instance() method, because PHP DateInterval generate an immutable days property (don't know why) when created from diff().

So if we could create it from a spec rather, it could solve this problem. And it would be also relevant to have CarbonInterval __construct compatible with DateInterval __construct. So it seems to me like the right thing to do.

**Comment by imbrish** [comment]
Don't get me wrong, I'm totally in for constructing `CarbonInterval` from a spec string, I just don't see it anyhow relevant to this issue.

Creating a new instance from a spec in case of diffs is equivalent to not throwing exception and removing `$instance->days = $di->days;` line from current `CarbonInterval::instance`. It does exactly the same thing! Namely it returns a new interval, which doesn't have `days` set.

I imagine you may want to know a number of `days` between dates you just diffed, but still this can be achieved in a myriad of different, better ways. For example adding getters for `totalDays`, `totalMonths` etc is one, and for sure superior to completely rejecting intervals created from diffs!

**Comment by kylekatarnls** [comment]
First step here: #1229

Next to come in my plans:
- way to resolve intervals (something like 3820 seconds `->resolve()` become 1 hour, 2 minutes)
- way to set factors (hour per day, day per week/month, etc.)
- way to sum in one unit (as you said: totalDays, totalMonths, etc.)

**Comment by ownmaster** [comment]
There is another thought, about naming: `Carbon` methods like `now()`, `yesterday()`, `tomorrow()` all return `Carbon` objects, so it would be logical for `diff()` to return `CarbonInterval` and some other method should return `DateInterval`, for example `diffAsDateInterval()` or `diffInDateInterval()` (following methods naming like `diffInSeconds()` and others). What do you think about it?

**Comment by kylekatarnls** [comment]
I see your point but as CarbonInterval is not perfectly compatible with DateInterval, it could break some apps. So keeping the DateTime::diff method as is (not overriden) is safer. A new method `diffAsCarbonInterval` allows to get CarbonInterval if you need it without breaking stuff.
