### ISSUE TITLE
Add Pull Request and Issue Template

### ISSUE THREAD

**Issue by armen-gabrielyan** [briannesbitt/Carbon#1046]
I think it will be helpful to have templates for PR and Issue submissions. I would like to work on it.

**Comment by Glavic** [comment]
Still interested? Do you have any suggestions?

**Comment by armen-gabrielyan** [comment]
Yes, I am. I will add pull request.

**Comment by Glavic** [comment]
Ok, will talk more on PR. Closing this for now.
