### ISSUE TITLE
Carbon::setTestNow(..) affects new Carbon(date_as_text);

### ISSUE THREAD

**Issue by dsandber** [briannesbitt/Carbon#1047]
I have regression tests that use Carbon::setTestNow.

For reasons I can't understand, this ends up introducing a time component into the result of "new Carbon('2018-03-27').  

I can introduce Carbon::setTestNow(null) into tearDown to work around the problem, but the root issue seems to be that Carbon::setTestNow is having an affect more widely than one would expect.

Am I missing something that would explain it?

**Comment by kylekatarnls** [comment]
`Carbon::now()` is called as many places (for default values in create, in diff methods mostly) and create and diff methods themselves are called by createFromDate, createFromTime, intervals.

So indeed, `Carbon::setTestNow` has a wild impact. You can consider, it's as if you would change the date and time of your operating system for all Cabon instances.

**Comment by dsandber** [comment]
I'm not understanding -- If you do:

`
>>> new Carbon('Feb 3 2018')
=> Carbon\Carbon @1517616000 {#948
     date: 2018-02-03 00:00:00.0 UTC (+00:00),
`

It returns a date with the time set to midnight.  Why would setTestNow change the time?  This is a very non-obvious side-effect of using setTestNow

**Comment by kylekatarnls** [comment]
This is DateTime behavior, only "now" add current Time, all other string passed in new is at midnight, then if you setTestNow, it replaces now (for test purpose only) Time included.

**Comment by dsandber** [comment]
Ok, so you're saying that setTestNow will change the time-zone used when doing subsequent calls to functions like Carbon::today?  Perhaps this can be documented in Carbon::today and/or in setTestNow?  I don't think anyone would expect that

```
>>> Carbon::today()
=> Carbon\Carbon @1520899200 {#953
     date: 2018-03-13 00:00:00.0 UTC (+00:00),
   }
>>> Carbon::setTestNow('2018-02-03 1:34+8')
=> null
>>> Carbon::today()
=> Carbon\Carbon @1517587200 {#956
     date: 2018-02-03 00:00:00.0 +08:00,
   }
```

**Comment by kylekatarnls** [comment]
Yep, today relatively to real now become today relatively to testing instance.

If you want you can send a PR to the gh-pages branch (where lives the documentation), edit `.src.html` files then you can run `composer update` and `php generate.php` to generate `.html` files. If you get any trouble with generation, just send the `.src.html` modifications, I'll do the generation.
