### ISSUE TITLE
Feature request: fallback text

### ISSUE THREAD

**Issue by mityukov** [briannesbitt/Carbon#1050]
Hi,

It would be great to use Carbon in this manner sometimes:
```php
echo $someDate->format('m/d/Y', 'not available');
```

'not available' would be the fallback text, when the date is empty. I.e., in cases like these:
```
$someDate = Carbon::createFromTimestamp(0);
$someDate = Carbon::parse('');
// etc.
```

**Implementation:** it should probably check year that it's not 1970 or less or, **better**, keep a property filed that it was instantiated with an empty string or zero(s) — depending on the "fabric" used for the instantiation.

For the **backwards compatibility** (there are, for sure, people who rely on that `::parse('')` returns current date and that `::createFromTimestamp(0)` returns Jan 01 1970) I would suggest to preserve current behavior intact if second argument is not passed to `::format()`. Or, it could be a different method, like `::formatOr($format, $fallbackText)`.

**Comment by Glavic** [comment]
Problem I see here is that `1970-01-01` is still a valid date; also years before 1970 are valid (or negative unix timestamp). I think this kind of validation should be used before calling `Carbon::parse()` with empty string, so Carbon should know nothing about this... Just MHO.
