### ISSUE TITLE
A meridian could not be found

### ISSUE THREAD

**Issue by sadalsuud** [briannesbitt/Carbon#1053]
I send by form a time : 9:30 AM then .. 

`Carbon::createFromFormat('g:i A', $request->input('hora_ini'))->format('H:i');`

but throw exception " InvalidArgumentException
A meridian could not be found"

Any idea?? ... thanks

**Comment by Glavic** [comment]
This code works: https://eval.in/949789

You have issues with `$request->input('hora_ini')`; it probably doesn't contain what you think it does.

Add `var_dump($request->input('hora_ini'));` before you `Carbon::createF....` line.
