### ISSUE TITLE
Make translation dependency optional

### ISSUE THREAD

**Issue by bubach** [briannesbitt/Carbon#1062]
I think that forcing the Symfony translator package for such simple translations used by Carbon is pretty absurd.

A small 2 class lib that suddenly requires like 50 extra bloated translation classes - when it could have been using a simple array lookup without all the fancy stuff? Also, what if I already use zend translations for example? 

Perhaps ship it with a (simple) array lookup, but using a custom TranslatorInterface, so you optionally could use other methods such as Symfony or Zend on top of it - if you want to.

**Comment by Glavic** [comment]
Hi @bubach, do you have any idea/example/PR how we should replace Symphony dependency? TY

**Comment by kylekatarnls** [comment]
It's not a simple array lookup, do you look at the arabic or serbian plurals, are you aware 0 and 1.5 are plural in english but not in french and is some languages 2 is even not plural or have 3 plural forms. Symfony translator already deals for us with all that and we're really happy to not have to handle all that. If we code it ourselves, we will have a ton or linguistic errors.

And I'm pretty sure at the end, we will have as much code as symfony/translate if we succeed.

So what would be absurd would be to recode something that works. If you think you can do it with no error in any language. Please send a PR.
