### ISSUE TITLE
composer phpcs errors

### ISSUE THREAD

**Issue by Ovsyanka** [briannesbitt/Carbon#1069]
If you run `composer phpcs` at current master (926aee5ab38c2868816aa760f862a85ad01cb61a) _(Actually I run it after two fixes #1068, #886, because without them you can't run the command on the windows systems)_ then you have a lot of style errors.

In current state style-checking is useless because before run checks onyour own changes you have to fix already existed errors.

And I see the strange situation: If you look at my pull-request all tests is passed inluding style check. But my next pull-request (#1070) which based on previous because it is needful to run the style checks on a windows system - there is plenty of style errors in code I didn't change.

**Comment by Glavic** [comment]
I have changed/fixed all issues in PR https://github.com/briannesbitt/Carbon/pull/1087, so `composer phpcs` should return success now. Closing this for now, since solution is already in PR.
