### ISSUE TITLE
Carbon loses microsecond information

### ISSUE THREAD

**Issue by t-tomek** [briannesbitt/Carbon#1073]
I've found an issue with microseconds (Carbon v1.22.1, PHP v7.0.22):
```
$date = DateTime::createFromFormat('Y-m-d\TH:i:s.uT', '2017-07-29T13:57:27.123456Z');
echo($date->format('Y-m-d H:i:s.u e')); // 2017-07-29 13:57:27.123456 Z

$date = Carbon::createFromFormat('Y-m-d\TH:i:s.uT', '2017-07-29T13:57:27.123456Z');
echo($date->format('Y-m-d H:i:s.u e')); // 2017-07-29 13:57:27.000000 Z
```

**Comment by Glavic** [comment]
On PHP 7.0.22 (Windows x64) and Carbon 1.22.1 I get the identical result.

```php
public function testIssue1073()
{
	$date = \DateTime::createFromFormat('Y-m-d\TH:i:s.uT', '2017-07-29T13:57:27.123456Z');
	$d1 = $date->format('Y-m-d H:i:s.u e');
	
	$date = Carbon::createFromFormat('Y-m-d\TH:i:s.uT', '2017-07-29T13:57:27.123456Z');
	$d2 = $date->format('Y-m-d H:i:s.u e');
	
	$this->assertTrue($d1 === $d2);
}
```

**Comment by t-tomek** [comment]
Just found out why this is not working for me.

It's related with `setlocale('pl-PL.utf8'); as PHP has problem with decimal point :| see [Bug #67127](https://bugs.php.net/bug.php?id=67127)

**Comment by Glavic** [comment]
I didn't know that `setlocale()` has any power over parsing datetimes. Will look into php source code in the near future to see what is happening there :/

I have added `setlocale(LC_ALL, 'pl-PL.utf8');` to my test, and I still cannot reproduce issue on php 7.0.22.

**Comment by t-tomek** [comment]
Sorry, I copied wrong command it should be `setlocale(LC_ALL, 'pl_PL.UTF-8');`

But be aware that you have to have this locale installed on your system, otherwise locale won't be changed.

**Comment by Glavic** [comment]
@t-tomek: I have tested your configuration, and indeed it doesn't. It doesn't work for any locale which has comma for decimal point, even for my `sl_SI`. If you set only `LC_TIME` in `setlocale()` it will work. 
Based that this is php bug I don't see what we can do?

**Comment by kylekatarnls** [comment]
The initial issue says DateTime works for the same input. We should check if we have nothing related to the dot in our code.

**Comment by kylekatarnls** [comment]
Confirmed, we do this wrong: `static::createFromFormat('U.u', sprintf('%F', $timestamp / 1000))`

I will fix it.

**Comment by kylekatarnls** [comment]
This is a PHP problem:

```php
$date = new \DateTime('2017-07-29T13:57:27.123456Z');
echo $date->format('Y-m-d H:i:s.u e')."\n";

setlocale(LC_ALL, 'fr');

$date = new \DateTime('2017-07-29T13:57:27.123456Z');
echo $date->format('Y-m-d H:i:s.u e');
```

Outputs:
```
2017-07-29 13:57:27.123456 Z
2017-07-29 13:57:27.000000 Z
```

This is a big problem, since createFromFormat call `new DateTime` to wrap a Carbon object around the DateTime.

@Glavic @briannesbitt If you have some idea. I don't know how we could work around this.

**Comment by kylekatarnls** [comment]
This is a fix to keep microseconds with coma decimal separator locales and work around https://bugs.php.net/bug.php?id=67127: #1128
