### ISSUE TITLE
Strange behavior with parse() when chaining addHours() and addMinutes()

### ISSUE THREAD

**Issue by toddstoker** [briannesbitt/Carbon#1075]
I'm experiencing some strange behavior. When using Carbon::parse() on an atom formatted string (e.g. '2018-01-23T03:30:45-5:00'), if addHours() and addMinutes() are chained then you will receive an erroneous result.

```
>>> $d = Carbon\Carbon::parse('2018-01-23T03:30:45-5:00')
=> Carbon\Carbon @1516696245 {#1042
     date: 2018-01-23 03:30:45.0 -05:00,
   }
>>> $d->addHours(1)->addMinutes(1)
=> Carbon\Carbon @1516681905 {#1042
     date: 2018-01-22 23:31:45.0 -05:00,
   }
```
Edit: Carbon 1.22.1, PHP 7.1.2

**Comment by Ovsyanka** [comment]
I can't reproduce it (I have php 7.1.11 on the windows though).

Could you write the unit test with date_default_timezone_set() with your current timezone like this? Does it fail?

```php
<?php

namespace Tests\Carbon;

use Carbon\Carbon;
use Tests\AbstractTestCase;

class issue1705Test extends AbstractTestCase
{
    public function testIssue() {
        date_default_timezone_set('America/New_York');
        $d = Carbon::parse('2018-01-23T03:30:45-5:00');
        $d->addHours(1)->addMinutes(1);
        $this->assertEquals('2018-01-23T04:31:45-05:00', $d->format('c'));
    }
}

```

**Comment by toddstoker** [comment]
My default TZ is UTC, but if I change it to America/New_York it functions as expected.

Also I just tried this in another environment, where PHP is at 7.1.7, and I couldn't reproduce the issue.

**Comment by Ovsyanka** [comment]
So, this test failed in your environment?

```php
<?php

namespace Tests\Carbon;

use Carbon\Carbon;
use Tests\AbstractTestCase;

class issue1705Test extends AbstractTestCase
{
    public function testIssue() {
        date_default_timezone_set('UTC');
        $d = Carbon::parse('2018-01-23T03:30:45-5:00');
        $d->addHours(1)->addMinutes(1);
        $this->assertEquals('2018-01-23T04:31:45-05:00', $d->format('c'));
    }
}
```

**Comment by Glavic** [comment]
Default TZ should have no saying here, since you already have TZ info in the string.

See note on `$timezone` parameter (http://php.net/manual/en/datetime.construct.php):
> The $timezone parameter and the current timezone are ignored when the $time parameter either is a UNIX timestamp (e.g. @946684800) or specifies a timezone (e.g. 2010-01-28T15:00:00+02:00).

@toddstoker: this is a very strange bug. Are you sure you are not doing anything else with `$d` object in-between?

**Comment by Ovsyanka** [comment]
It might be because `modify` method (see #883). So I ask this just for sure, that this is not the case. But newermind, seems like @toddstoker not interested in this issue anymore.

**Comment by Glavic** [comment]
We will fix that modify method ASAP.

**Comment by Ovsyanka** [comment]
Btw, I already made pull-request for that a quite time ago: #1070

**Comment by Glavic** [comment]
True, but we must first fix travis and styleci, and then you should rebase, and if all goes well, we shall merge. Bear with us :)
