### ISSUE TITLE
Full list of string formatters?

### ISSUE THREAD

**Issue by websanova** [briannesbitt/Carbon#1076]
Don't see this in the docs.

There is a small section on formatting: http://carbon.nesbot.com/docs/#api-formatting

But would be nice to see a list of all the character options and what they mean.

**Comment by Glavic** [comment]
For start :)

![untitled](https://user-images.githubusercontent.com/2729571/35827908-f9b6cc12-0abd-11e8-8947-1a33a0ff8045.png)

**Comment by websanova** [comment]
Right, but I was looking for the three letter day in lowerase.

For example "wed".

I ended up finding this after looking through the source:

```
strtolower($day->format('D'))
```

Just saying it would be nice to see a full list of codes with an example somewhere. Something similar to the php date docs. 

http://php.net/manual/en/function.date.php
