### ISSUE TITLE
what's the result of compare $data>'2018-02-02 12:00:00'?

### ISSUE THREAD

**Issue by kalsolio** [briannesbitt/Carbon#1079]
$data maybe {"date":"2018-02-02 11:07:43.000000","timezone_type":3,"timezone":"UTC"},
what's the result of compare $data>'2018-02-02 12:00:00'?

**Comment by Glavic** [comment]
If `$data` is Carbon object, then result would be `false`.

```php
var_dump(Carbon::parse('2018-02-02 11:07:43.000000') > '2018-02-02 12:00:00');
```
