### ISSUE TITLE
formatLocalized doesn't work with custom toStringFormat

### ISSUE THREAD

**Issue by stueliueli** [briannesbitt/Carbon#1081]
I used to call `Carbon::setToStringFormat()` in my application.
Because of this, the `$carbon->formatLocalized()` does not work anymore.
This is because `strtotime()` takes a Carbon-Object, which then is converted to a string according to the [Specification](http://php.net/manual/en/function.strtotime.php)

> The function expects to be given a string containing an English date format and will try to parse that format into a Unix timestamp

A successful solution could look like this:
- User calls formatLocalized
- Current toStringFormat is being stored
- Default toStringFormat is set
- strtotime() is called
- Custom toStringFormat is re-set

Or `strtotime` could simply be called with `$carbon->format('Y-m-d H:i:s');`

**Comment by ricardobucho** [comment]
Hey there,

I don't see how this is an issue.

I might be missing something here but the default should be the carbon object and not the string format.  You can just call `formatLocalized` whenever you wish or any other method for that matter.

You could just as easily extend the carbon class or add an helper function somewhere else that does something like` $carbonObject->toDateTimeString()`.

Hope I am not misreading the situation here, best of luck :)

**Comment by stueliueli** [comment]
Yes, yes, you're right. Carbon itself works with carbon objects. But the carbon-method `formatLocalized` calls the PHP date method `strtotime` with `$this` as argument.

Relevant code from Carbon.php lines 1179-1190:

```php
/**
 * Format the instance with the current locale.  You can set the current
 * locale using setlocale() http://php.net/setlocale.
 *
 * @param string $format
 *
 * @return string
 */
 public function formatLocalized($format)
    {
        // Check for Windows to find and replace the %e
        // modifier correctly
        if (strtoupper(substr(PHP_OS, 0, 3)) === 'WIN') {
            $format = preg_replace('#(?<!%)((?:%%)*)%e#', '\1%#d', $format);
        }

        $formatted = strftime($format, strtotime($this));

        return static::$utf8 ? utf8_encode($formatted) : $formatted;
    }
```

The problem here is the line `$formatted = strftime($format, strtotime($this));` or specific the part `strtotime($this)`. 

[strtotime](http://php.net/manual/en/function.strtotime.php) expects the parameter to be a string. So php implicitly parses `$this` to a string. This, using the function `__toString()`. 
This function on a carbon object returns the time formatted according to the format provided by `Carbon::setToStringFormat()`. 
If, using this method, the default toString-format is changed, `strtotime` does not get a format-string it can use, and thus fails.

Steps to reproduce:

```php
$time = Carbon::now();
echo $time->formatLocalized('%A');
//will print the day of the week localized ("Monday" or "Montag" or "Lundi")

Carbon::setToStringFormat(''d. F Y H:i \U\h\r');
//sets the format to output something like "5. May 2018 14:30 Uhr"
//("Uhr" is the german "o'clock")
echo $time->formatLocalized('%A');
//Will always print "Thursday" or "Donnerstag", because strtotime can't parse the input and assumes a timestamp of 0, defaulting to Thursday, 01. January 1970.
```

I hope my issue is now more clear :)

**Comment by briannesbitt** [comment]
PR accepted thanks!
