### ISSUE TITLE
Incorrect weekOfMonth

### ISSUE THREAD

**Issue by kheme** [briannesbitt/Carbon#1086]
I tried getting the weekOfMonth of a particular date and realized that weekOfMonth is calculated differently from weekOfYear, which is more accurate, but relative to the year and not a specific month. 

For instance, consider the following:
```
$dt = Carbon::parse('2017-2-2 00:00:00');
var_dump($dt->weekOfMonth); // returns 1
var_dump($dt->weekOfYear); // returns 5
```
and then consider this:
```
$dt = Carbon::parse('2017-2-6 00:00:00');
var_dump($dt->weekOfMonth); // returns 1
var_dump($dt->weekOfYear); // returns 6
```

Looking at a calendar, we see that February **2nd** and February **6th** fall on different weeks. Hence using weekOfYear, we get weeks 5 and 6 respectively.

However, weekOfMonth returns week 1 for both dates, which is incorrect. This is incorrect because weekOfMonth is calculated by dividing the number of days in a month by 7.

Therefore I am proposing a more accurate weekOfMonth that is calculated with reference to the weekOfYear that a date falls on. I managed to accomplish this with the following modifications to "**Carbon\Carbon.php**":
```
case $name === 'weekOfMonth':
if($this->month == 1){
	return $this->weekOfYear;
}
else{
	$returnWeek = $this->weekOfYear;

	// subtract previous month weeks from weeks in a year
	for($i = 1; $i < $this->month; $i++){
		// we have to check if the last week of the previous month is the same week as the first week of the current month
		$dateOfLastDay = Carbon::parse($this->month($i))->daysInMonth;
		$weekOfLastDay = Carbon::parse($this->day($dateOfLastDay))->weekOfYear;

		// if Yes, then we add 1 to $returnWeek to avoid returning "0" as Week of Month
		if($weekOfLastDay == $this->weekOfYear){
			$returnWeek += 1;
		}
		
		$returnWeek -= ceil(Carbon::parse($this->month($i))->daysInMonth / 7);
	}
	
	// if the first week of the month is same as the last week of the previous month,
	// then $returnWeek will be zero, so we have to add "1" to $returnWeek
	if($returnWeek == 0){
		$returnWeek += 1;
	}
	
	return (int) $returnWeek;
}
//return (int) ceil($this->day / static::DAYS_PER_WEEK);
```

Perhaps this could be improved further and included in the future releases.

Thanks

**Comment by Glavic** [comment]
Don't know why this was implemented, will look it up, but in the meantime: https://en.wikipedia.org/wiki/ISO_week_date#Weeks_per_month

> The ISO standard does not define any association of weeks to months. A date is either expressed with a month and day-of-the-month, or with a week and day-of-the-week, never a mix. 

Based on that, there is no standard for `weekOfMonth`... Some1 decided to make this work like it does, divide current month day with 7, and that is week of the month. This is "wrong", and should be left out of the library, for user to make his own decision. But, since we need to keep backward compatibility, I would not fix this nor remove it from library.

Let's see what others have to say about this.

**Comment by 36864** [comment]
I believe the current implementation makes it easier to define/check dates such as "The second Thursday of November". In the given example, it's easy to see that 2/2/2017 was the first Thursday of the month, and 6/2/2017 was the first Monday of the same month.
This kind of check is useful when, for example, calculating holiday dates or club gathering dates.

As you said, changing this would be a pretty big breaking change for anyone using it for this kind of date, even if the name might be misleading at first.

Another point to consider would be how to handle the first week of the year. 1/1/2017 was a Sunday. 
```
>>> Carbon::parse('2017-01-01')->weekOfYear;
=> 52
>>> Carbon::parse('2017-01-01')->weekOfMonth;
=> 1
>>> Carbon::parse('2017-01-01')->dayOfWeek;
=> 0
```
I don't know if we really want week of month to behave like week of year.

**Comment by Glavic** [comment]
`weekOfYear` is same as `->format('W')` which will return [ISO-8601](https://en.wikipedia.org/wiki/ISO_8601) week number of year. 
Date `2017-01-01` still belongs to last week of the year 2016 (52). That is working correctly.

I would like to have an option that is standard for weekOfMonth, like we have for weekOfYear, but currently I cannot see one :/

**Comment by Glavic** [comment]
Because of the BC and no standard for week in months, I'm closing this.
Will reopen if we get some new info. TY

**Comment by Vendin** [comment]
Yes, i agree,  need to keep backward compatibility, I would not fix this nor remove it from library. But you need to add a new, correct functionality that users need!
https://github.com/briannesbitt/Carbon/pull/1105
