### ISSUE TITLE
Missing getter "weekNumberInMonth

### ISSUE THREAD

**Issue by tobias-boyer** [briannesbitt/Carbon#1122]
The getter `$dt->weekNumberInMonth` is missing in Carbon version 1.22.1 with PHP version 5.6.31 but is listet as available in the documentation.

It results in an "Unknown getter" exception if called.

**Comment by briannesbitt** [comment]
That was just added in the last day and will be in the next 1.23 due out shortly. https://github.com/briannesbitt/Carbon/commit/ff3b26391b122d6df6c9cda165eb753ad034dfc1

**Comment by tobias-boyer** [comment]
Thank you for your effort. The new version solves the issue.
