### ISSUE TITLE
DST bug with day modification

### ISSUE THREAD

**Issue by tscheepers** [briannesbitt/Carbon#1126]
**Version: 1.22.1**

I've found a problem with day modification on the DST boundary.

I would expect if I call `subDay()` that I end up in the day before, not two days before.

```php
<?php
require 'vendor/autoload.php';

use Carbon\Carbon;

// DST on Europe/Amsterdam is 2018-03-25 2:00 == 2018-03-25 3:00

// 2018-03-26 0:30:0
$dstDateTime = new \DateTime('2018-03-26 0:30:00', new \DateTimeZone('Europe/Amsterdam'));
$dstCarbon = Carbon::create(2018, 03, 26, 0, 30, 0, 'Europe/Amsterdam');

// Expected: 2018-03-25 0:30:0
$beforeDstDateTime = $dstDateTime->modify('-1 days');
$beforeDstCarbon = $dstCarbon->subDay();

// Got: 2018-03-25 00:30:00
var_dump($beforeDstDateTime);

// class DateTime#3 (3) {
//   public $date =>
//   string(26) "2018-03-25 00:30:00.000000"
//   public $timezone_type =>
//   int(3)
//   public $timezone =>
//   string(16) "Europe/Amsterdam"
// }

// Got: 2018-03-24 23:30:00
var_dump($beforeDstCarbon);

// class Carbon\Carbon#3 (3) {
//   public $date =>
//   string(26) "2018-03-24 23:30:00.000000"
//   public $timezone_type =>
//   int(3)
//   public $timezone =>
//   string(16) "Europe/Amsterdam"
// }

```

Maybe, this could be due to an error on these lines: 
 https://github.com/briannesbitt/Carbon/blob/10c98d1e9d0d7a78a2d9be1d7b4056718d85de50/src/Carbon/Carbon.php#L3385-L3397

It looks like the lines try to circumvent this bug in PHP: https://bugs.php.net/bug.php?id=65811

Shouldn't the timezone setting and resetting depend on the length of the interval?

**Comment by tscheepers** [comment]
Ooh wait, I see something like this is already being discussed: https://github.com/briannesbitt/Carbon/issues/991

**Comment by kylekatarnls** [comment]
Yes, we're working on that subject. Thanks for you test case, it could help.
