### ISSUE TITLE
Daylight savings always true when using timezone offset

### ISSUE THREAD

**Issue by robmazur** [briannesbitt/Carbon#1127]
I was having an issue with time being off by an hour and tracked the issue down to this line. Looks like daylight savings is always "true" when using the timezone offset. 

My understanding is there is no easy fix for this (Timezone != Offset): https://stackoverflow.com/tags/timezone/info 

https://github.com/briannesbitt/Carbon/blob/ba61af080c8a618ce5ff33ae4cc79229fb1c1fc4/src/Carbon/Carbon.php#L249

**Comment by kylekatarnls** [comment]
Not sure to understand what you're trying to do and what you expect, maybe you should add some of your code and expectation.

But when you set numeric timezone, it does not care of the country, the daylight saving or anything else, it's just GMT+ the number of hours you gave.

When you set string timezone, it take the country into account and the optional daylight saving.
