### ISSUE TITLE
Create some chatting place

### ISSUE THREAD

**Issue by Ovsyanka** [briannesbitt/Carbon#1130]
I suggest you to create some hat to make people discuss things and ask questions in realtime.

It may be Gitter, Discord, Slack, IRC, etc... I personally prefere Discord at this moment, but it could be anything.

What do you think?

We can discuss it here and make some polling about.

**Comment by kylekatarnls** [comment]
Hi, we use Slack internally. I don't known how have a public place in Slack, but it could be interesting.

**Comment by kylekatarnls** [comment]
We'll discuss it internally. For now, people can request an access to our Slack with this temporary form: http://carbon.selfbuild.fr
