### ISSUE TITLE
Version tag is wrong.

### ISSUE THREAD

**Issue by JorgenSolli** [briannesbitt/Carbon#1131]
I just realized I could't get the diffForHumans with "number of parts" parameter, as added in 1.22.0, to work because composer is not giving me the correct version of Carbon.

I can't accurately see what version the tag 1.22.1 points to, because its not specified anywhere. But it's definitely pointing to a way older commit than the actual 1.22.0 version.
Also probably a good idea to start tagging the version name in Carbon.php, I would have caught the "error" way sooner :)

this is the supposedly 1.22.1 tagged version without the parameters for parts
https://github.com/briannesbitt/Carbon/blob/1.22.1/src/Carbon/Carbon.php#L2789

Anyways.. Thought I should report. I'll be using "dev-master" for now :)

**Comment by Glavic** [comment]
I think v1.23 will be release any time soon. @kylekatarnls will have more info on that one :)

**Comment by kylekatarnls** [comment]
Yep @Glavic waiting for your review on https://github.com/briannesbitt/Carbon/pull/1129 to tag it ;)

Tag 1.22.1 is fine, but the doc is a bit ahead. *number of parts* will be available on 1.23.
