### ISSUE TITLE
Issue with AddMonths

### ISSUE THREAD

**Issue by hrtrulz** [briannesbitt/Carbon#1132]
for some reason when using the following It does not return me the correct date

Initially the date is '2018-07-01 09:00:00' then running `$start = $start->addMonths( 1 );` it returns a date `2018-07-31 09:00:00`

These times are using AEST (UTC+10).

**Comment by Glavic** [comment]
I can confirm this:

```php
$start = new Carbon('2018-07-01 09:00:00 Australia/Melbourne');
var_dump($start->format('c I')); // 2018-07-01T09:00:00+10:00 0
$start->addMonths( 1 );
var_dump($start->format('c I')); // 2018-07-31T09:00:00+10:00 0
```

This is because of the `modify()` method in `Carbon` class. PR #1129 will solve this issue.

**Comment by kylekatarnls** [comment]
Confirmed, until +09:00, we get 08-01, then +10, +11 and +12, we get 07-31. Will inspect if it's a bug of DateTime or Carbon.

**Comment by kylekatarnls** [comment]
You can update to 1.23 to fix it. Please tell us if you get any trouble.
