### ISSUE TITLE
Change in method signature in 1.23 error

### ISSUE THREAD

**Issue by jsiebach** [briannesbitt/Carbon#1136]
Hello, not sure if this is really an error with Carbon or with another package, but I wanted to report updating composer to 1.23 caused a breaking change:

Declaration of Jenssegers\Date\Date::diffForHumans(?Carbon\Carbon $since = NULL, $absolute = false, $short = false) should be compatible with Carbon\Carbon::diffForHumans(?Carbon\Carbon $other = NULL, $absolute = false, $short = false, $parts = 1)

It's another fairly popular library so I imagine I wont be the only one with this issue.

For those of you here that had the same problem, I solved it by pegging carbon to 1.22 in composer.json:  `"nesbot/carbon" : "1.22.*"`

**Comment by briannesbitt** [comment]
Ya with the extra parameter, even with a default value, anyone who has a child class the overrides the method will get the error it seems.

**Comment by kylekatarnls** [comment]
Hi, it's jenssegers that need to get compatible, please refer to this issue: https://github.com/jenssegers/date/issues/280
