### ISSUE TITLE
addYears(25) returns 0000:00:00

### ISSUE THREAD

**Issue by SirCumz** [briannesbitt/Carbon#1139]
When i add more then 20 years (in this case 25 years) the result is going to be 0000:00:00 00:00:00

im trying to add 25 years to this timestamp: 

2017-02-09 00:00:00

result:

0000:00:00 00:00:00

expecting:

2042-02-09 00:00:00

**Comment by SirCumz** [comment]
mysql only handles 20 years in the future? :/

**Comment by imbrish** [comment]
@SirCumz use `datetime` column instead of `timestamp` ;)

**Comment by kylekatarnls** [comment]
If the storage is 32bit: '1970-01-01 00:00:01' UTC to '2038-01-19 03:14:07' UTC
 - 32bit OS
 - 32bit PHP program
 - 4 octets database storage (INT, TIMESTAMP, etc.)
If the storage is 64bit: '1000-01-01' to '9999-12-31'
 - Match all other cases
