### ISSUE TITLE
holiday or festive days?

### ISSUE THREAD

**Issue by carlituxman** [briannesbitt/Carbon#116]
it can be possible have some method like isWeekend but isHoliday establishing an array or by location, to know if date is on holiday?

**Comment by rmblstrp** [comment]
I created a PR which adds Carbon extensions that check to see if a given date is a business day. Custom holiday and business schedules can be provided which allow you to properly determine what the date is for next or previous number of business days.

https://github.com/briannesbitt/Carbon/pull/706
