### ISSUE TITLE
Carbon object in methods parameters ?!

### ISSUE THREAD

**Issue by patie** [briannesbitt/Carbon#117]
Hi,

is there reason for using Carbon object as methods parametr ?

For example:
```
   public function diffInDays(Carbon $dt = null, $abs = true)
   {
      $dt = ($dt === null) ? static::now($this->tz) : $dt;

      return intval($this->diff($dt, $abs)->format('%r%a'));
   }
```
first parameter is Carbon, so i cannot put here DateTime, its possible to update this for Interface or must be there Carbon object ?

thx

**Comment by briannesbitt** [comment]
Going to close this for now.  Most of the popular frameworks now use Carbon natively.
