### ISSUE TITLE
Unexpected character since last update (from 1.22.0 to 1.24)

### ISSUE THREAD

**Issue by mobal** [briannesbitt/Carbon#1173]
Hi,

since my last update (from 1.22.0 to 1.24.1) I got the following exception:

`DateTime::__construct(): Failed to parse time string (2018-03-09 15:58:28.-909518) at position 24 (5): Unexpected character`

1.22.0 works perfectly. My timezone is UTC. Could you please help me?

Thanks!

**Comment by austintoddj** [comment]
Looks like it's being worked on [here](https://github.com/briannesbitt/Carbon/pull/1172).

**Comment by Cranavvo** [comment]
This is also happening to me on GMT 😢

Guess there won't be a Friday deploy after all...

**Comment by kylekatarnls** [comment]
No @austintoddj it's not the same issue.

@mobal `-909518` means `microtime(true)` returned a negative value. It seems like a serious bug from your PHP program, which exact PHP version (and build) do you use?

**Comment by mobal** [comment]
@kylekatarnls I have the following PHP installed:

`PHP 5.6.28 (cli) (built: Nov  9 2016 06:40:27)
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies`

**Comment by kylekatarnls** [comment]
Yes, it happened because we prepend the microtime (since 1.24), but we did not expect a microtime to be a negative value. I have to inspect how this could happen.

**Comment by kylekatarnls** [comment]
Hi, could you please test with the last version (set composer `"nesbot/carbon": "dev-master"`) and tell me if it fix your bug? If not I'll re-open.

**Comment by mobal** [comment]
Hi,

I did a quick test and with the latest commit looks okay (`0200f98`)!  :)

**Comment by kylekatarnls** [comment]
I'm still embarrassed not to know why you have negative microtime, but I'm glad it helps.

**Comment by TahseenAlaa** [comment]
Hi,
I got the same problem after update to (1.24.1), 
also i'm using Laravel 5.5.39

**Comment by Glavic** [comment]
@TahseenAlaa & @mobal : did you had this issues on 32bit machine?

**Comment by mobal** [comment]
@TahseenAlaa no. Up to date 64 bit Windows 7.

**Comment by TahseenAlaa** [comment]
@Glavic Windows 10 - 64 bit.

**Comment by TahseenAlaa** [comment]
Solved by rollback to **Carbon 1.22.1** and **Laravel 5.5.38**.

**Comment by mobal** [comment]
@TahseenAlaa de next version, 1.25 will contains the fix. You can use the dev-master now, or 1.23.

**Comment by TahseenAlaa** [comment]
@mobal Great, thanks a lot.

**Comment by kylekatarnls** [comment]
You can quick test with:
```php
<?php
echo PHP_INT_SIZE === 4 ? '32bit' : '64bit';
```

**Comment by mobal** [comment]
@kylekatarnls you mean the php version? :)

For me it is 32 bit.

**Comment by kylekatarnls** [comment]
You're in 32bit if your OS is 32bit (no matter which PHP you use, you cannot have 64bit) or if you installed a 32bit version of PHP. To get PHP_INT_SIZE = 8, you must have both PHP and Windows in 64bit.

**Comment by mobal** [comment]
@kylekatarnls not. I am 100% sure I have 64-bit Windows 7. Just checked in the System panel and I have two Program Files folder. This is the package what I downloaded today morning: **php-5.6.34-Win32-VC11-x64.zip**

**Comment by TahseenAlaa** [comment]
I excuted that code 
`
PHP_INT_SIZE === 4 ? '32bit' : '64bit';
`
and I got the result 32bit ....
so what is the issue in my machine ?
@kylekatarnls

**Comment by kylekatarnls** [comment]
@mobal, @TahseenAlaa Check your `<?php echo PHP_BINARY`, maybe the PHP running program is not the one you think.

What I'm sure is if `PHP_INT_SIZE` is 4, you're not running a 64bit PHP program.

**Comment by mobal** [comment]
For me `PHP_BINARY` points to the right place.

**Comment by kylekatarnls** [comment]
OK, got it. Windows PHP < 7 are not really 64bit, the program is but number are still handled with a 32bit storage. Upgrade to PHP 7! 🆙

**Comment by mobal** [comment]
Maybe this is a bug in PHP 5 in this case?

**Comment by TahseenAlaa** [comment]
`PHP_BINARY` point me to the php.exe path.
And when excute `php -v` in the terminal ... I got the following (you might be interested)
PHP 7.0.22 (cli) (built: Aug  1 2017 14:13:55) ( ZTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies

**Comment by Cranavvo** [comment]
I don't have the issue anymore, but when I did both my production and development servers were both running PHP7, and my production server did not bug-out like this; shot in the dark, could `artisan` affect this?
