### ISSUE TITLE
 Declaration of Illuminate\Support\Carbon::__set_state(array $array) should be compatible with Carbon\Carbon::__set_state($state

### ISSUE THREAD

**Issue by chhedadhaval120386** [briannesbitt/Carbon#1178]
I am getting this issue when I am doing laravel new project_name so please help me

**Comment by andyg1** [comment]
Same here. Just broke my Laravel project. 

I ran composer update and it went from v.1.23.something to 1.24.1

**Comment by zyfcjtc** [comment]
/vendor/laravel/framework/src/Illuminate/Support/Carbon.php : 9
   
 public static function __set_state( $array)
    {
        return static::instance(parent::__set_state($array));
    }

this is only a temporary fix for the development, wait for the update

**Comment by kylekatarnls** [comment]
Dupplicate, fixed
