### ISSUE TITLE
The last release ( 1.24.1)  broke my code. 

### ISSUE THREAD

**Issue by emanuelverardi** [briannesbitt/Carbon#1179]
I'm getting this error today after the new release.

 Declaration of Illuminate\Support\Carbon::__set_state(array $array) should   
  be compatible with Carbon\Carbon::__set_state($state) 

I'm using Laravel 5.5 and php 7.0

Any Sugestions?

**Comment by zyfcjtc** [comment]
Same here

**Comment by zyfcjtc** [comment]
/vendor/laravel/framework/src/Illuminate/Support/Carbon.php : 9

change remove the 'array' type for the temporary fix

    public static function __set_state($array)
    {
        return static::instance(parent::__set_state($array));
    }

**Comment by chhedadhaval120386** [comment]
thanks zyfcjtc for the fix

but I cloned laravel and did composer installed and no issues..strange

**Comment by zyfcjtc** [comment]
Yeah, laravel just update couple minutes ago

**Comment by emanuelverardi** [comment]
I fixed the problem setting the last stable version  (1.20) in my composer.json 
"require": {
"nesbot/carbon": "1.20"
}

Too Bad Luck for a friday ...  Fu%^&^%

**Comment by kylekatarnls** [comment]
Duplicate, fixed.
