### ISSUE TITLE
Carbon::today() does not set microseconds to 0

### ISSUE THREAD

**Issue by rsukonovs** [briannesbitt/Carbon#1200]
``Carbon::today()`` should not be: ``2018-03-14 00:00:00.115167`` This is not start of the day. It breaks all comparison functions.

PHP version: 7.0.28

**Comment by kylekatarnls** [comment]
Fixed in 1.25 by #1197

**Comment by kylekatarnls** [comment]
You can yet test it by setting `"nesbot/carbon": "dev-master"` in your composer.json file and run `composer update`.
