### ISSUE TITLE
setTime() non-zero seconds

### ISSUE THREAD

**Issue by lee-van-oetz** [briannesbitt/Carbon#1206]
`var_dump(Carbon::now()->setTime(0, 0, 0)); // '2018-03-15 00:00:00.000031'`
`var_dump((new DateTime)->setTime(0, 0, 0)); // '2018-03-15 00:00:00.000000'`

The seconds fraction varies between runs.

**Comment by kylekatarnls** [comment]
Will be fixed on 1.25 (#1190)

If you need it urgently, you can temporarily set `"nesbot/carbon": "dev-master"` in your **composer.json**

**Comment by kylekatarnls** [comment]
1.25 released, please refer to http://carbon.nesbot.com/docs/#note-about-microseconds
