### ISSUE TITLE
startOfDay() doesn't set microseconds to '0' in php < 7.1

### ISSUE THREAD

**Issue by JackSW** [briannesbitt/Carbon#1209]
The now() method sets the microseconds to a non-zero value but in PHP<7.1, the startOfDay() method does not set the microseconds to zero.

This causes a bug to occur when comparing dates using gte/lte/equalTo functions, for example
```PHP
$date1 = Carbon::today();
$date2 = Carbon::today();
var_dump( $date1->equalTo($date2) ); // false
```

```PHP
$date1 = Carbon::now()->startOfDay();
$date2 = Carbon::now()->startOfDay();
var_dump( $date1->equalTo($date2) ); // false

var_dump($date1);
/*
object(Carbon\Carbon)#767 (3) {
  ["date"]=>
  string(26) "2018-03-16 00:00:00.793818"
  ["timezone_type"]=>
  int(3)
  ["timezone"]=>
  string(3) "UTC"
}
*/

var_dump($date2);
/*
object(Carbon\Carbon)#769 (3) {
  ["date"]=>
  string(26) "2018-03-16 00:00:00.793879"
  ["timezone_type"]=>
  int(3)
  ["timezone"]=>
  string(3) "UTC"
}
*/
```

**Comment by JackSW** [comment]
I believe this affects PHP < 7.1

**Comment by kylekatarnls** [comment]
today() in next version 1.25 will no longer have microseconds.
and `Carbon::useMicrosecondsFallback(false)` will disable microseconds in now() for PHP < 7.1 also in the next version,

you can yet test it by setting `"nesbot/carbon": "dev-master"` in your **composer.json**.

**Comment by kylekatarnls** [comment]
1.25 released, please refer to http://carbon.nesbot.com/docs/#note-about-microseconds
