### ISSUE TITLE
Document 1.26 version

### ISSUE THREAD

**Issue by kylekatarnls** [briannesbitt/Carbon#1213]
- [x] setTimeFrom()/setDateFrom()
- [x] json_encode/json_decode, serializeUsing()
- [x] jsonSerialize()
- [x] macro()/hasMacro()/mixin()
- [x] propose a list of macros [from issues and pull-requests](https://github.com/briannesbitt/Carbon/issues?utf8=%E2%9C%93&q=label%3A%22maybe+macro+%3F%22+)
- [x] Diff as CarbonInterval
- [x] diffForHumans: new words (just now, yesterday, tomorrow, etc.) #1240

https://github.com/briannesbitt/Carbon/compare/gh-pages...kylekatarnls:gh-pages-1.26

**Comment by tm1000** [comment]
@kylekatarnls  thank you for your work on this!!
