### ISSUE TITLE
Problem with GTE on diferent servers

### ISSUE THREAD

**Issue by mr0bles** [briannesbitt/Carbon#1227]
> Server 1: (localhost) XAMPP
> Server 2: (localhost) Homestead
> Server 3: (GC) Ubuntu 14.04
> 
> date1 = (Carbon object) 2018-03-31 23:59:59
> date2 = (Carbon object) 2018-03-31 23:59:59
> 

Test on Server 1 and Server 2
`$date1 ->gte($date2)`
return true

Test on Server 3
`$date1 ->gte($date2)`
return false

I tested lte and work correctly but gte doesn't work

**Comment by kylekatarnls** [comment]
As explained in the doc:

> Those methods use natural comparisons offered by PHP $date1 == $date2 so all of them will ignore milli/micro-seconds before PHP 7.1, then take them into account starting with 7.1.

I guess you have different versions of PHP on your different servers.

**Comment by mr0bles** [comment]
TEs, is problem of php, with version 7.0 dont work

**Comment by kylekatarnls** [comment]
We can say "does not work". It's just a different behavior. I know it's a bit breaking and unexpected for a minor version of PHP, but it's not a bug if you swap your values you will have the same behavior with lte and gte. You can simply consider than comparisons with timestamps in PHP < 7.1 are done with microtimestamps in PHP >= 7.1.
