### ISSUE TITLE
There is no way to set microseconds to 0 in PHP 7.0

### ISSUE THREAD

**Issue by rsukonovs** [briannesbitt/Carbon#1231]
Version 1.25.0 fixed some issues with microseconds on versions PHP 7.0 and older. But I think it still introduces BC breaks.

For example ``Carbon::now()->startOfDay()`` still results in 2018-03-26 00:00:00.533444. This is not correct, especially if ``Carbon::today()`` is 2018-03-26 00:00:00.000000.

Even if I risked introducing errors in our project, and ``setTime()`` manually I can't do that.

**Comment by Glavic** [comment]
Use `Carbon::useMicrosecondsFallback(false);` ?

**Comment by rsukonovs** [comment]
I have read code now. This idea is kind of nice idea, but it needs fixing. First of all microseconds is set only on constructor level. But it means all time modifications should include this functionality. First of all ``setTime()`` should be overwritten, to emulate PHP 7.1 functionality. Then what about setters? ``$this->modify('00:00:00.000000');`` does not work on 7.0 as you can see in my first post.

And I don't understand why this is not false by default? Nobody till this moment used this functionality in older versions.

**Comment by kylekatarnls** [comment]
> But it means all time modifications should include this functionality.

Simply not possible, microseconds are immutable in PHP 7.0, you can change it only by creating a new object, it's not a Carbon issue, DateTime has this bug. See the example in this section using native DateTime class: http://carbon.nesbot.com/docs/#note-about-microseconds

> `$this->modify('00:00:00.000000')` does not work on 7.0

Works except for the microseconds (it's exactly what we say in the example of doc I mention above).
