### ISSUE TITLE
:Time from now

### ISSUE THREAD

**Issue by flakerimi** [briannesbitt/Carbon#1232]
":time from now" should be " in :time" 

 no one says 5 sec from now, people says in 5 sec, in one day, etc

**Comment by 36864** [comment]
They're equally valid constructs.
I'd like to see where you got the data from to assert "no one says" :time from now

**Comment by kylekatarnls** [comment]
It depends more on the context and language level. But we provide some neutral translations. And it's up to you to change it to contextualize according to your needs.

Check the end of the localization section of the documentation: http://carbon.nesbot.com/docs/#api-localization

It show you how you can edit the wording.
