### ISSUE TITLE
Is it a bug?

### ISSUE THREAD

**Issue by yica00** [briannesbitt/Carbon#1233]
I test the time around 2018-3-29~2018-3-31:
$month = Carbon::now()->subMonth(1);
the result is 3, but it should be 2.why this? Thanks

**Comment by 36864** [comment]
If today is 2018-03-29
SubMonth makes that 2018-02-29
2018 is not a leap year, so DateTime automatically corrects that to 2018-03-01

This is well-documented DateTeim behavior that has existed for a very long time.

**Comment by sasureshkumar** [comment]
To fix this use:
`$month` = Carbon::now()->firstOfMonth()->subMonth();`

**Comment by Glavic** [comment]
Or use `Carbon::useMonthsOverflow(false);`

Read more here: http://carbon.nesbot.com/docs/#api-addsub

**Comment by kylekatarnls** [comment]
Or `$month = Carbon::now()->subMonthWithNoOverflow(1);`
