### ISSUE TITLE
Microsecond Breaking Changes

### ISSUE THREAD

**Issue by CImrie** [briannesbitt/Carbon#1234]
Hey, unfortunately I think there was a breaking change introduced after v1.22.1. I think it's after 1.23.0 but can't verify since Laravel seemed to have a small bug with 1.23.0.

I've been using `$date->endOfMonth()` so that a series of events always take place at the last possible second in a month (it works for a financial model I'm building). This now shows `.99999` for microseconds, where they were not present before.

This results in a very small difference (the `endOfMonth` call has just less than 1 second full of microseconds more than the date I'm expecting). As a result any comparisons of end-of-month dates in my app no longer work (and I happen to use them quite extensively). I've reverted to 1.22.1 and this has fixed the issue.

This may have been introduced in #1140.

I expect this is something that is intended but wanted to post here to warn people who may not have been catering for microseconds before as it will take some thought and careful checking to make sure their results are consistent.

**Comment by Glavic** [comment]
https://github.com/briannesbitt/Carbon/issues/1231
https://github.com/briannesbitt/Carbon/issues/1209

**Comment by kylekatarnls** [comment]
> This now shows .99999 for microseconds, where they were not present before.

This is a feature to get closer to PHP 7.1+ behavior.

To compare without microseconds 2 dates you can do this:
```php
$date1->isSameAs('U', $date2)
```
