### ISSUE TITLE
diffForHumans short format isn't working for other locale

### ISSUE THREAD

**Issue by aso824** [briannesbitt/Carbon#1238]
When I change the locale of Carbon, short format of `diffForHumans` method result stop working correctly - it ignores third parameter. 

    >>> $c1->diffForHumans($c2, true, true, 2)
    => "2h 30m"
    
    >>> \Carbon\Carbon::setLocale('pl')
    => true
    
    >>> $c1->diffForHumans($c2, true, true, 2)
    => "2 godziny 30 minut"

**Comment by Glavic** [comment]
Then translation is not what it should be > https://github.com/briannesbitt/Carbon/blob/master/src/Carbon/Lang/pl.php

If you speak polish, can you fix it please?

**Comment by kylekatarnls** [comment]
@aso824 Short syntax has been added after most of translations, so short syntaxes also need to be translated language by language.
