### ISSUE TITLE
isDayOfWeek() is not defined

### ISSUE THREAD

**Issue by lu3do** [briannesbitt/Carbon#1239]
```
<?php
use Carbon\Carbon;

$dt = Carbon::now();
$dt->isDayOfWeek(Carbon::SATURDAY);
?>
```
results in:
Call to undefined method Carbon\Carbon::isDayOfWeek

**Comment by kylekatarnls** [comment]
Which is your Carbon version? Have you at least 1.24:
https://github.com/briannesbitt/Carbon/releases/tag/1.24.0

**Comment by kylekatarnls** [comment]
I guess it just needed to be updated, I close this issue. Tell us if you still need help.
