### ISSUE TITLE
The timezone could not be found in the database

### ISSUE THREAD

**Issue by shamshashmi** [briannesbitt/Carbon#1241]
Due to the latest changes when calling createFromFormat('Y-m-d H:i:s', '16:00:00') drops me with error "Failed to parse time string (2018-04-13 15:09 PM) at position 17 (P): The timezone could not be found in the database" and my php version is 7.1.15... Why is this?

**Comment by DuckThom** [comment]
@shamshashmi Just fyi, im aloy from IRC

Just wanted to add that the error currently does not match the code snippet in the post above.
I'll add the screenshot that you sent me with the stacktrace: ![](https://i.imgur.com/g6SUIOj.png)

As you can see, the call `Carbon::createFromFormat('Y-m-d H:i:s', '2018-04-04 16:00:00')` seems to convert the '2018-04-04 16:00:00' part to '2018-04-04 16:00 PM' before passing it to the DateTime constructor without changing the format.

**Comment by shamshashmi** [comment]
change in the static function instance in Carbon.php file happening this issue. 

return new static($date->format('Y-m-d H:i A'), $date->getTimezone());
bad move.
it was before 
return new static($date->format('Y-m-d H:i:s.u'), $date->getTimezone());

I dont know why it is changed but wasted my all day....

**Comment by shamshashmi** [comment]
this will reproduce the error 

Carbon::createFromFormat('Y-m-d H:i:s', '2018-04-04 16:00:00') ... please check

**Comment by kylekatarnls** [comment]
Overriding `$date->format('Y-m-d H:i A')` in the `instance` method has no sense, it just break the library. What did you try to do by changing this?

**Comment by shamshashmi** [comment]
Apologize, must be some mistake happened on our side.... Thanks for helping :)

**Comment by kylekatarnls** [comment]
Glad you find out the problem. I close this issue, have a nice week-end.
