### ISSUE TITLE
Add second rounding methods

### ISSUE THREAD

**Issue by spawnia** [briannesbitt/Carbon#1248]
I am happily using Carbon as part of a Laravel project.

However, when comparing dates in unit testing, i run into an issue: I want to test the correct serialization of dates to the database. The format i store in the database only stores second precision, so the rehydrated Carbon instance does not contain microseconds.

My testing code looks like this:
````php
$now = now();

$myModel->some_date_field = $now;
$myModel->save();

$this->assertTrue($now->equalsTo($myModel->some_date_field)

var_dump($now);
var_dump($myModel->some_date_field);
````

The assertion fails and the output looks like this:
````
object(Illuminate\Support\Carbon)#3536 (3) {
  ["date"]=>
  string(26) "2017-04-16 11:36:08.769991"
  ["timezone_type"]=>
  int(3)
  ["timezone"]=>
  string(3) "UTC"
}
object(Illuminate\Support\Carbon)#3547 (3) {
  ["date"]=>
  string(26) "2017-04-16 11:36:08.000000"
  ["timezone_type"]=>
  int(3)
  ["timezone"]=>
  string(3) "UTC"
}
````

Firstly, i think Carbon should round the timestamp to the next higher second.

Secondly, it would be nice to have a way of comparing the equality of those dates in a way that allows to ignore the precision. I see a few ways for doing that:

- Explicitely round the first date like this: `$carbon->roundSeconds()`
- Pass an extra parameters to the equality check, specifying precision: `$carbon->equalsTo($carbon2, Carbon::SECOND)`
- Have a seperate function for comparing equality with different precision `$carbon->equalsSecondsTo($carbon2)`

Which of those would be the most useful? I would happily submit a pull request, but would like to discuss this before getting to work.

I currently worked around it by calling `$carbon->second($carbon->second)` which effectively rounded the date instance.

**Comment by kylekatarnls** [comment]
Hi,

> Firstly, i think Carbon should round the timestamp to the next higher second.

Why? I store microseconds in my DB in my app because I want a precise order of what happened, and I certainly not want to loose this information when comparing two dates. Carbon keep the maximum of precision the PHP version allow to and it's up to the user to do rounding he needs. The library should certainly not take such opinionated decision.

> Secondly, it would be nice to have a way of comparing the equality of those dates in a way that allows to ignore the precision.

There, is you can compare with any format you need:
```php
$date1->isSameAs('U', $date2) // second precision
$date1->isSameAs('Y-m-d H:i', $date2) // minute precision
$date1->isSameAs('Y-m-d H', $date2) // hour precision
...
```

With formatting and comparison tools available, you may not even need rounding explicitly at all.

Neverless if you still need it, it's possible with the native PHP DateTime `modify` method:
```php
$date->modify('-'.$date->micro.' microsecond');
```

Does it fit your need?

**Comment by spawnia** [comment]
Let me clarify on the microseconds bit: Carbon should absolutely keep the microsecond precision, i totally agree. However, when storing a date in second precision, rounding the value seems like a sensible default. Cutting off the value is equivalent to getting the floor - which might be useful but seems like it would be the exception.

The `isSame...` methods do offer the kind of comparison i am looking for, i did not catch that. However, it still might be useful to have more of them. Since Carbon already has `isSameYear/Month/Day`, do you think adding Hour, Minute and Second would make sense?

On the rounding bit: Your suggestions are cool, however they do not seem obvious or intuitive. Isn't the whole point of carbon to add a nice, simple to use API for dealing with dates? Adding methods for doing `floor`, `ceil` and `round` to arbitrary precision could certainly be a nice enhancement.

**Comment by kylekatarnls** [comment]
Indeed, I find this idea interesting, but rounding at second granularity is opinionated, user could want to round to closest minute/hour, etc. or even some more custom ones: milliseconds, second hundredth, tenth, hour quarters, and so on.

So your can submit a PR for `floor`, `ceil` and `round` if you find a way to specify precision and/or unit, else it should better be named `floorSecond`, `ceilSecond` and `roundSecond`.

`isSame(Hour|Minute|Second)`, why not, feel free to propose a PR for them.

**Comment by spawnia** [comment]
I am on it.

Actually, i started working on `isSameHour` because it seemed like a low hanging fruit. I am going to finish up `Minute|Second` in a bit and make a first pull request for that. When i do so, should i open a new branch for that in my fork? If not, what branch should i commit my changes to?

I have noticed that `isSameMonth()` has a parameter, specifying if it should be `$ofSameYear`, and actually defaults to false. However, `isSameDay()` has no such parameter - it does an exact comparison. This behaviour seems inconsistent. Having the same level of granularity for day would mean adding two parameters, in which case i think one would be better of by just using `isSameAs()` directly, formatting accordingly.

There is still value in having the `isSameAs` methods, although i think they should be simplified and have a unified form. I propose adding a second parameter to each of those, including Day and Month, which is a boolean `$exact`. When set to true, the whole date is compared, when it is false, only the aspect in question is looked at.

Do you think it is reasonable to set the default to true? Also, can you think of a better name to give the parameter? I thought about calling it something like `$onlyConsider(Month|Day|...)`

Thank you.

**Comment by kylekatarnls** [comment]
`isSameMonth` is an exception because it's more ambiguous than other units:
- "we have our birthday the same month", mostly understood as  same month of any year
- "we were born the same month", mostly understood as  same month of the same year

That does not happen for `isSameDay` because a day number can be day of week, day of month, day of year, etc.

So I think the flag is not needed for isSame(Hour|Minute|Second) and the comparison can always be exact.

I also know that the default value would better have to be true for consistency in `isSameMonth` but it would break existing app that use it with default value, so it cannot be changed before a major release (version 2).

**Comment by kylekatarnls** [comment]
Planned for 1.27

**Comment by spawnia** [comment]
Actually, #1261 only covers one aspect of this issue: adding more fine-grained comparison methods.

I would like to take a shot at implementing the rounding methods we discussed, too. Should we open a new issue for that or reopen this one?

**Comment by kylekatarnls** [comment]
No need for an issue, you can create the PR and we will discuss on it. I do not have a concrete solution, but the expectation of rounding methods would be:
- having a precision/unit control: minute/second/milliseconds, etc. cherry on the cake (optional): allow non-decimal precision such as hour quater. (It can be different methods or an argument if explicit enough.)
- having floor/ceil/round
- this should be mutable and allow chaining for consistency with startOf/endOf methods (modify the current instance then return `$this`)

**Comment by vivere-dally** [comment]
Adding a comment that's somewhat related and might be useful for other readers.

I wanted a behavior with `diffInHours` where I could round up to compare with a certain value, but you can achieve that in a different manner:

```php
// $c1 and $c2 are carbon instances, $c1 < $c2
$hours = 168; // some value

echo $c1->diffInHours($c2, absolute: true) < $hours; // vs
echo $c1->addHours($hours)->lte($c2);
```
