### ISSUE TITLE
CarbonPeriod extension of DatePeriod

### ISSUE THREAD

**Issue by imbrish** [briannesbitt/Carbon#1249]
@kylekatarnls have you been working on that concept already? After you mentioned it in https://github.com/briannesbitt/Carbon/pull/1247#issuecomment-381563472 you got me thinking about it.

Now having some ideas of mine own I'm quite excited to start implementing. I think I could draft a preliminary PR today. Just wouldn't like to re-do the work already done!

**Comment by kylekatarnls** [comment]
I just asked the same to myself, and so cleaned up my fork branches and nop, I kept nothing useful about that. Just have a look at the @Denys-Bushulyak work and snippets posted on #1058.

**Comment by imbrish** [comment]
Major setback, "Writing to DatePeriod properties is unsupported".

- https://stackoverflow.com/a/24791999/2646927
- https://bugs.php.net/bug.php?id=53437

So we cannot extend `DatePeriod` in any useful way. Even `Reflection` does not help. Alternative would be to create a wrapper class, but then it won't be possible to pass `CarbonPeriod` around as a `DatePeriod`.

At least it came up early.

**Comment by kylekatarnls** [comment]
We will use a wrapper of DatePeriod or create a CarbonPeriod from scratch, I close this issue, refer to following PRs:

https://github.com/kylekatarnls/Carbon/pull/3
#1257
