### ISSUE TITLE
Carbon 1.26.0 breaks Laravel compability

### ISSUE THREAD

**Issue by alshenetsky** [briannesbitt/Carbon#1250]
After `composer update` it says:

> PHP Fatal error:  Carbon\Carbon and Illuminate\Support\Traits\Macroable define the same property ($macros) in the composition of Illuminate\Support\Carbon. However, the definition differs and is considered incompatible.

Downgrade to 1.25.0 works fine

**Comment by 36864** [comment]
This is a Laravel issue, not a Carbon issue.

A quick glance at laravel's package.json shows a recent commit updated the dependency from "^1.24.1" to "1.25.*" which would fix this issue.

**Comment by kylekatarnls** [comment]
Very unexpected, I just upgraded a Laravel project with no problem. What is your Laravel and PHP version?

**Comment by 36864** [comment]
Laravel 5.6.16 requires nesbot/carbon at "^1.24.1" which does try to pull 1.26.0, which is grossly incompatibly with Laravel's Carbon extension.

Current fix is to manually restrict carbon to "1.25.*" or lower in any laravel projects.

**Comment by kylekatarnls** [comment]
When did you get this error? on update, on run, on extend? I use Laravel 5.6 with Carbon 1.26 just now and my macros work.

**Comment by 36864** [comment]
On updating an existing project. More specifically, on executing `artisan package:discover` to generate the autoload file.

**Comment by alshenetsky** [comment]
This error just throws in runtime also, not just in console. It breaks entire project.

**Comment by 36864** [comment]
I'd just like to ask that you refrain from tagging a new release reverting these changes before speaking with Taylor to prevent a repeat of the last time there was a Laravel/Carbon compatibility issue.

**Comment by kylekatarnls** [comment]
We will use an other variable name. But I still do not understand, I just ran `artisan package:discover` and `composer create-project laravel/laravel` with no problem at all.

**Comment by kylekatarnls** [comment]
@36864 @alshenetsky Can you try if installing dev-master version solves the problem?

**Comment by alshenetsky** [comment]
Seems to be fixed. Thank you very much.
