### ISSUE TITLE
Class 'Carbon\Translator' not found 

### ISSUE THREAD

**Issue by 0203** [briannesbitt/Carbon#1264]
hi, im having issue with **Class 'Carbon\Translator' not found**  when i using $announcement->created_at->diffForHumans() in my blade. could you give some suggestion why i get this error

**Comment by kylekatarnls** [comment]
Hi, how do you load classes? Do you use the autoload of composer? If so, try to run `composer dump-autoload` to recreate it.

**Comment by 0203** [comment]
yes.. I have try 

> composer dump-autoload

 but still not working..it still show error **Class 'Carbon\Translator' not found**..you think I need to do 

> composer update

?

**Comment by kylekatarnls** [comment]
If your vendor directory may have been corrupted, you should. The new translator comes with version 1.25.0 and superior.

If you have not a matching version, you should update.

If you have a matching version, check if vendor/nesbot/carbon/src/Carbon/Translator.php exists.
If it does, only the autoloading is broken (composer autoload not in use or broken)

If it does not exist, your vendor directory is corrupted, run `composer update`.

**Comment by 0203** [comment]
Thanks for your explanation.. I have checked my vendor/nesbot/carbon/src/Carbon/ then the Translator.php file is not exists..I run composer update then it works..thanks!

**Comment by kylekatarnls** [comment]
Glad to here that.
