### ISSUE TITLE
gt() working with string on local but not on test server

### ISSUE THREAD

**Issue by sagarmedput** [briannesbitt/Carbon#1279]
```
$date = Carbon::today()->startOfMonth()->addMonth()->format('Y-m-d');
if (Carbon::parse("07/01/2018")->gt($date)) {
	echo "yes";
} else {
	echo "no";
}
dump($date);
```

> Type error: Argument 1 passed to Carbon\Carbon::gt() must be an instance of Carbon\Carbon, string given

I am getting this error on my test server. 
But somehow it won't trigger an error on my local.  I am getting an answer "yes" in my local. 
Just want to know what is the reason for that it is working on my local?

**Comment by Glavic** [comment]
Just give `Carbon` instance as parameter in `gt()` method.

```
$date = Carbon::today()->startOfMonth()->addMonth();
if (Carbon::parse("07/01/2018")->gt($date)) {
```

**Comment by sagarmedput** [comment]
Thank you for responding. I got that point. But want to know why the same code is working on my local machine. Means in a local using string in gt function I can compare dates. But on my server, it's generating an error. the same lines of code work on my local machine but not on a server machine. Really interested to know the reason behind that.

**Comment by sagarmedput** [comment]
perfect make sense. 
Thank you so much.
