### ISSUE TITLE
subMonth() issue on 29-03-2018

### ISSUE THREAD

**Issue by congacon95** [briannesbitt/Carbon#1290]
Hi guys,
Recently I want to get sub month from these day: 29, 30 and 31 of  03-2018 but the return dates are wrong.

Code: 
```
(new \Carbon\Carbon('28-03-2018'))->subMonth(); //This work just find
```
Result: 
```
=> Carbon\Carbon {#774
     +"date": "2018-02-28 00:00:00.000000",
   }
```

Code: 
```
(new \Carbon\Carbon('29-03-2018'))->subMonth(); //This return the wrong result
```

Result:
```
=> Carbon\Carbon {#756
     +"date": "2018-03-01 00:00:00.000000",
   }
```
Expected:
```
=> Carbon\Carbon {#756
     +"date": "2018-02-28 00:00:00.000000",
   }
```

**Comment by Glavic** [comment]
Can you show us more? Like working code that fails in your case?

**Comment by congacon95** [comment]
@Glavic sorry I accidentally press the enter key.

**Comment by Glavic** [comment]
https://github.com/briannesbitt/Carbon/issues/881

**Comment by kylekatarnls** [comment]
What you show is the expected behavior (native behavior of PHP DateTime).

From the documentation (https://carbon.nesbot.com/docs/#api-addsub):

> By default, Carbon relies on the underlying parent class PHP DateTime behavior. As a result adding or subtracting months can overflow, example:
> ```php
> $dt = Carbon::create(2017, 1, 31, 0);
> 
> echo $dt->copy()->addMonth();            // 2017-03-03 00:00:00
> echo $dt->copy()->subMonths(2);          // 2016-12-01 00:00:00
> ```
> You can prevent the overflow with `Carbon::useMonthsOverflow(false)`
> ```php
> Carbon::useMonthsOverflow(false);
> 
> $dt = Carbon::createMidnightDate(2017, 1, 31);
> 
> echo $dt->copy()->addMonth();            // 2017-02-28 00:00:00
> echo $dt->copy()->subMonths(2);          // 2016-11-30 00:00:00
> 
> // Call the method with true to allow overflow again
> Carbon::resetMonthsOverflow(); // same as Carbon::useMonthsOverflow(true);
> ```
> The method `Carbon::shouldOverflowMonths()` allows you to know if the overflow is currently enabled. You also can use `->addMonthsNoOverflow`, `->subMonthsNoOverflow`, `->addMonthsWithOverflow` and `->subMonthsWithOverflow` (or the singular methods with no s to "month"). to explicitly add/sub months with or without overflow no matter the current mode.
> ```php
> Carbon::useMonthsOverflow(false);
> 
> $dt = Carbon::createMidnightDate(2017, 1, 31);
> 
> echo $dt->copy()->addMonthWithOverflow();          // 2017-03-03 00:00:00
> // plural addMonthsWithOverflow() method is also available
> echo $dt->copy()->subMonthsWithOverflow(2);        // 2016-12-01 00:00:00
> // singular subMonthWithOverflow() method is also available
> echo $dt->copy()->addMonthNoOverflow();            // 2017-02-28 00:00:00
> // plural addMonthsNoOverflow() method is also available
> echo $dt->copy()->subMonthsNoOverflow(2);          // 2016-11-30 00:00:00
> // singular subMonthNoOverflow() method is also available
> 
> echo $dt->copy()->addMonth();                      // 2017-02-28 00:00:00
> echo $dt->copy()->subMonths(2);                    // 2016-11-30 00:00:00
> 
> Carbon::useMonthsOverflow(true);
> 
> $dt = Carbon::createMidnightDate(2017, 1, 31);
> 
> echo $dt->copy()->addMonthWithOverflow();          // 2017-03-03 00:00:00
> echo $dt->copy()->subMonthsWithOverflow(2);        // 2016-12-01 00:00:00
> echo $dt->copy()->addMonthNoOverflow();            // 2017-02-28 00:00:00
> echo $dt->copy()->subMonthsNoOverflow(2);          // 2016-11-30 00:00:00
> 
> echo $dt->copy()->addMonth();                      // 2017-03-03 00:00:00
> echo $dt->copy()->subMonths(2);                    // 2016-12-01 00:00:00
> 
> Carbon::resetMonthsOverflow();
> ```
> From version 1.23.0, overflow control is also available on years

**Comment by imbrish** [comment]
Or recently here https://github.com/briannesbitt/Carbon/issues/1233 :)

**Comment by Glavic** [comment]
or here https://github.com/briannesbitt/Carbon/issues/881 :)
