### ISSUE TITLE
Calling startOfWeek() then endOfWeek() and get twice the same date

### ISSUE THREAD

**Issue by rennokki** [briannesbitt/Carbon#1297]
I have encountered a weird behaviour:

```php
$date = Carbon::today();
$startOfWeek = $date->startOfWeek(); // This returns 2018-05-20 23:59:59.999999 UTC (+00:00)
```

I have tried using the static functions to set the weekend days and even setWeekStartsAt() and setWeekEndsAt() to set both ends of the week, still no success.

**Comment by kylekatarnls** [comment]
```php
<?php

use Carbon\Carbon;

include 'vendor/autoload.php';

$date = Carbon::today();
$startOfWeek = $date->startOfWeek();

echo $startOfWeek->format('Y-m-d H:i:s.u');
```

Outputs: `2018-05-14 00:00:00.000000`

Can you provide a minimal code to reproduce the bug (a file that just include Carbon library and can run as stand-alone).

**Comment by kylekatarnls** [comment]
First of all, start/end OfWeek like most Carbon methods doesn't return new instances, they modify the given one then return the same instance. So the right way to do this is:
```php
<?php

use Carbon\Carbon;

include 'vendor/autoload.php';

$date = Carbon::parse('2000-01-05 12:30:45.123456');
$start = $date->copy()->startOfWeek();
$end = $start->copy()->endOfWeek();
```
This way you will have 3 different objects, `$date`, `$start` and `$end` and each one will handle the right value.

And this is nothing related with the `parse()` method it's about the mutability of Carbon (related to the mutability of orignal PHP DateTime object).

**Comment by rennokki** [comment]
Yes, that was the problem. I have worked it out using this.
Thank you for your reply. :D
