### ISSUE TITLE
range of dates

### ISSUE THREAD

**Issue by abdofariss** [briannesbitt/Carbon#132]
How to create a range of dates ?

**Comment by reinink** [comment]
This can also be done like this:

```php
new DatePeriod($startDate, new DateInterval('P1D'), $endDate)
```

Just keep in mind that `DatePeriod` is an iterator, so if you want an actual array:

```php
iterator_to_array(new DatePeriod($startDate, new DateInterval('P1D'), $endDate))
```

In you're using Laravel, you could always create a Carbon macro:

```php
Carbon::macro('range', function ($start, $end) {
    return new Collection(new DatePeriod($start, new DateInterval('P1D'), $end));
});
```

Now you can do this:

```php
foreach (Carbon::range($start, $end) as $date) {
   // ...
}
```

**Comment by kylekatarnls** [comment]
Will be added to the documentation:
https://github.com/briannesbitt/Carbon/compare/gh-pages...kylekatarnls:gh-pages-1.26
