### ISSUE TITLE
InvalidArgumentException: Data missing when selecting from DB

### ISSUE THREAD

**Issue by thomasdevin525** [briannesbitt/Carbon#1322]
Inside of a schedule, the only thing I'm calling is:
`Custom::whereNull('address')->get();`

In my Custom.php file I have:
```
protected $dates = ['effective_date', 'end_date', 'proposed_date', 'approved_date', 'created_at', 'updated_at'];
protected $dateFormat = 'Y-m-d H:i:s.u';
```

My dates are stored as datetimes in SQL Server in this format
`2016-06-29 00:00:00.000`

When the cron runs I get:
```
InvalidArgumentException: Data missing in /home/vagrant/admin/vendor/nesbot/carbon/src/Carbon/Carbon.php:836
Stack trace:
#0 /home/vagrant/admin/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php(709): Carbon\Carbon::createFromFormat('Y-m-d H:i:s.u', '2018-05-01 00:0...')
#1 /home/vagrant/admin/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php(122): Illuminate\Database\Eloquent\Model->asDateTime('2018-05-01 00:0...')
```

When I use:
`DB::table('custom')->whereNull('address')->get();`
it works fine except I can't call my custom methods off of the returned stdClasses

or
`Custom::select('id')->whereNull('address')->get();`
works but obviously it's only getting the id, this is just to show Custom is definitely working.

What seems to be the issue here or what alternative methods are there to account for this?
The issue appears to be unique to the cron because I've never experienced it before.

**Comment by kylekatarnls** [comment]
Due to a PHP bug with PDO, the dates does not handle correctly milliseconds/microseconds, so you need to hack it. I did that do handle microseconds with Laravel and MySQL:

```php
<?php

namespace App\Services;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Query\Grammars\MySqlGrammar as GrammarBase;
use Illuminate\Support\Facades\DB;

class MySqlGrammar extends GrammarBase
{
    public function getDateFormat()
    {
        return 'Y-m-d H:i:s.u';
    }

    public static function addMicroSeconds(Builder $query, ...$columns)
    {
        return $query->select('*', ...array_map(function ($column) {
            return DB::raw("concat($column) as $column");
        }, $columns));
    }
}
```

Then in a middleware, I set the grammar:
```php
<?php

namespace App\Http\Middleware;

use App\Services\MySqlGrammar;
use Closure;
use Illuminate\Support\Facades\DB;

class DbSettings
{
    public function handle($request, Closure $next)
    {
        DB::connection()->setQueryGrammar(new MySqlGrammar());

        return $next($request);
    }
}
```
I must warn, it's a hack. It converts dates into strings, so they are not cut by PDO. And so DateTime can get the whole data.
https://stackoverflow.com/questions/31227069/laravel-timestamps-to-show-milliseconds/31930762#31930762

I'm sorry there is nothing we can do in Carbon, and this bug is open for a long time the PHP bug tracker so we must work around.

**Comment by kylekatarnls** [comment]
I will consider this solved your problem. If not, please tell me and I'll re-open the issue.
