### ISSUE TITLE
Method Request: isCurrentWeek()

### ISSUE THREAD

**Issue by gofishwbeeler** [briannesbitt/Carbon#1331]
Hi Carbon Folks!

I use Carbon a lot, and I really appreciate all your hard work on this project! I was just writing to request a new method. You currently have ->isLastWeek(), and ->isNextWeek(), but no ->isThisWeek, or ->isCurrentWeek(). I figured that could be helpful. I could definitely use that in my project.

Thanks!

Will

**Comment by kylekatarnls** [comment]
Already fixed in Carbon version-2.0 branch. If you want to add this method for Carbon 1, you can fork the **version-1.29** branch then add it and submit a PR.

**Comment by gofishwbeeler** [comment]
Oh, my bad.. I understand what's going on now. Uh, I may do that later on. I appreciate your help again. No worries.

Will

**Comment by imbrish** [comment]
@gofishwbeeler hereby I offer you this macro:
```php
Carbon::macro('isCurrentWeek', function () {
    return $this->weekOfYear === $this->nowWithSameTz()->weekOfYear;
});

if ($date->isCurrentWeek()) {
    // It's this week!
} else if ($date->isLastWeek()) {
    // It's last week!
}
```

**Comment by kylekatarnls** [comment]
Will match same week number of other years. So I recommend what we did in Carbon 2:
```php
Carbon::macro('isSameWeek', function ($otherDate = null) {
    return $this->isSameAs('Y-W', $otherDate);
});
Carbon::macro('isCurrentWeek', function () {
    return $this->isSameWeek();
});
```

**Comment by imbrish** [comment]
@kylekatarnls I thought about it for a brief moment, but then forgot completely.
@gofishwbeeler Note that this is how v1's `isNextWeek` and `isLastWeek` work - return true for same week number any other year!

**Comment by kylekatarnls** [comment]
Whaou, week 50 of 1900 is the next week of week 49 of 2018. This must definitely be changed in Carbon 2.

**Comment by gofishwbeeler** [comment]
Thank you @kylekatarnls and @imbrish for all your help and code! I truly appreciate it.

Will

**Comment by 36864** [comment]
If you change it in Carbon 2, please add a way to keep the current behavior. There are use cases for wanting to know if something took place "on this week last year", for example.

**Comment by kylekatarnls** [comment]
@36864 I recommend to use explicitly the `->weekOfYear`:

```php
$date1->weekOfYear === $date2->weekOfYear
```
