### ISSUE TITLE
Error creating object on leap day today & tomorrow...

### ISSUE THREAD

**Issue by jimmypuckett** [briannesbitt/Carbon#1338]
So, we have some code that gets the end of the month from a year & month.  We have an automated test to make sure that our code works on a leap year.  It has been working for over a month, but started failing today.  If we set the system date to yesterday, it works.  Also, if we set it tomorrow it fails.  Finally, if we set system clock to June 1, it works again...

*System date set to today -- FAILED*
```php
>>> Carbon\Carbon::now()
=> Carbon\Carbon @1527692856 {#3188
     date: 2018-05-30 15:07:36.460332 UTC (+00:00),
   }
>>> Carbon\Carbon::create('2020', '2')
=> Carbon\Carbon @1583075263 {#3192
     date: 2020-03-01 15:07:43.0 UTC (+00:00),
   }
>>>
```

*System date set to yesterday -- GOOD*
```php
>>> Carbon\Carbon::now()
=> Carbon\Carbon @1527606517 {#3188
     date: 2018-05-29 15:08:37.815871 UTC (+00:00),
   }
>>> Carbon\Carbon::create('2020', '2')
=> Carbon\Carbon @1582988919 {#3192
     date: 2020-02-29 15:08:39.0 UTC (+00:00),
   }
>>>
```

*System date set to tomorrow -- FAILED*
```php
>>> Carbon\Carbon::now()
=> Carbon\Carbon @1527779345 {#3188
     date: 2018-05-31 15:09:05.410265 UTC (+00:00),
   }
>>> Carbon\Carbon::create('2020', '2')
=> Carbon\Carbon @1583161747 {#3190
     date: 2020-03-02 15:09:07.0 UTC (+00:00),
   }
>>>
```

*System date set to day after tomorrow -- GOOD*
```php
>>> Carbon\Carbon::now()
=> Carbon\Carbon @1527865771 {#3188
     date: 2018-06-01 15:09:31.353524 UTC (+00:00),
   }
>>> Carbon\Carbon::create('2020', '2')
=> Carbon\Carbon @1580569772 {#3193
     date: 2020-02-01 15:09:32.0 UTC (+00:00),
   }
>>>
```

**Comment by kylekatarnls** [comment]
Today we have all the variations of this bug, see other open/closed today issues. All the same, `Carbon\Carbon::create('2020', '2')` will create a date on 2020 february with the current day, current time. But current day in february 2020 does not exist, so it jump to next valid day.

It's the PHP native behavior and it works as expected, what else do you expect?

**Comment by imbrish** [comment]
Standard end-of-month issue :D It has nothing to do with leap years, same will happen if tomorrow (31st of May) you will try to shift back to April.

As @kylekatarnls mentioned earlier, just set the day explicitly with `Carbon\Carbon::create(2020, 2, 1)`.

**Comment by kylekatarnls** [comment]
Or if you want the same day of month, you need a fallback, such as:

```php
$date = Carbon\Carbon::create(2020, 2);
if ($date->day !== Carbon::now()->day) {
    // This day does not exist in February 2020
   $date->modify('last day of previous month'); // Fallback to February 29
}
```

**Comment by jimmypuckett** [comment]
Everyone, thanks for taking the time to respond.  I get that I can make a change to the code, and we will default our `Carbon\Carbon::create()` to alway use the first day of the month as we don't care about the day.

I think that the key take away in this issue & all of the "other open/closed today issues", is that atleast some people are assuming (rightfully or not) that if you are not passing a day that the day is irrelevant, when in actuality it is using today's day.

I will close this issue as I get that it is a mis matched expectation--not a bug.

**Comment by imbrish** [comment]
@jimmypuckett just wanted to mention that you can alternatively use `Carbon::parse('2020-02')` which will default to the start of month.

I think you may be right that the behavior of `Carbon::create` method is somewhat unexpected with taking omitted values from current time. This differs from `new DateTime` which defaults to lowest possible value (0 or 1). Now that you mentioned you don't care about the day this seems to be the crux of the issue. I would advocate for changing that behavior in Carbon 2, @kylekatarnls what's your take here?

However I don't think this applies to the other issues, because posters there mostly expect add/sub operations to "stay" in the new month (cut-off overflowing days), meanwhile DateTime will prefer overflowing to the next month. I expect diverging from native implementation in this respect would be confusing to even more people.

**Comment by kylekatarnls** [comment]
Yes, I agree, that was one reason why I created `createMidnightDate` to avoid having time set on current time.

`create` should use the minimal values by default, and it could be possible to pass to it a date/time string. The equivalent of version 1 `create` could be something more explicit like `Carbon::now()->set(...)`
