### ISSUE TITLE
Is there a way to get CarbonPeriod filter values?

### ISSUE THREAD

**Issue by kevdotbadger** [briannesbitt/Carbon#1359]
I have a pretty simple CarbonPeriod which spans from 9am to 5pm. I've added a simple filter that filters out lunchtime (1pm - 2pm) and an afternoon break (3pm - 3:15pm).

Is there a way to get the filterered date ranges, so I can check if it's currently lunchtime?

If i use `getFilter()` and loop through them, I only get the closures, I need to actual date values.

**Comment by kylekatarnls** [comment]
Maybe I do not understand the whole thing but I don't think `CarbonPeriod` fit this need.

What about simply counting comparing the hour:minute of the day?
```php
// Get the date you want to analyse as Carbon instance
$date = Carbon::now();
// Extract hour and minute as a single concatenated number
$hourAndMinute = $date->format('Gi');

if ($hourAndMinute < 900) {
  echo 'Business not yet open';
} else if ($hourAndMinute < 1300) {
  echo 'Morning work';
} else if ($hourAndMinute < 1400) {
  echo 'Lunchtime';
} else if ($hourAndMinute < 1500) {
  echo 'Afternoon work';
} else if ($hourAndMinute < 1515) {
  echo 'Afternoon break';
} else if ($hourAndMinute < 1700) {
  echo 'Afternoon work again';
} else if ($hourAndMinute < 1700) {
  echo 'Business is no closed';
}
```

**Comment by kevdotbadger** [comment]
Yeah, that's how I was previously doing it. But then I moved over to CarbonPeriod because it allowed me to remove parts of the day from a date range.

**Comment by kylekatarnls** [comment]
Sorry, still does not understand why you use CarbonPeriod which is simply an iterable over a repeated interval from a start instant. Please provide code.

**Comment by kevdotbadger** [comment]
The filters remove parts of a range though. So the range could go from 9am to 5pm, but exclude 10-10:30. So when looping over that, it'll ignore the filtered times.

Anyway, nevermind, I found a way to do it with CarbonPeriod by iterating over the entire thing, as opposed to trying to iterate over just the filtered out times.

Perhaps I'm not explaining myself clearly, but I got it working.
