### ISSUE TITLE
Multiple diffFilters

### ISSUE THREAD

**Issue by mgrahamx** [briannesbitt/Carbon#1361]
This is kind of a feature request rather than an issue, but it would be great to be able to run multiple filters on a diff between dates and pull out separate values for each filter.

For example, if you had two dates with several months difference and then wanted to determine the amount of weekends, Thursdays and public holidays throughout that timeframe there's a significant amount of manual work involved in that calculation.

Maybe passing multiple callbacks into a `diffFilters` function and then receiving an array with the results with the keys being the filter name?

Thanks.

**Comment by kylekatarnls** [comment]
Maybe you could give us an example of the code you're currently writing and how you would expect to write it with what you call multiple  diffFilters.

**Comment by imbrish** [comment]
If I understand your idea of `diffFilters` correctly it seems to be best suited as a macro or maybe a set of single-purpose macros like `countThursdays` or `countPublicHolidays`. Check the documentation about [Carbon macros](https://carbon.nesbot.com/docs/#api-macro) - same can be done with CarbonPeriod!

Anyway I don't think it's that much work to do it already. You may not be aware that filters can not only be added but also removed on one-by-one basis or in bulk!

```php
// Some complicated logic to create a CarbonPeriod.
$period = CarbonPeriod::create(...)->addFilter(...)->...;

// Now let's get the dates filter-by-filter.
$weekends = $period->addFilter('isWeekend')->toArray();

// Remove previous and move on to the next filter.
// Let's assume "isPublicHoliday" macro was previously added to Carbon.
$publicHolidays = $period->removeFilter('isWeekend')->addFilter('isPublicHoliday')->toArray();

// Finally let's count all days in the period by temporarily resetting filters.
$filters = $period->getFilters();
$daysCount = $period->resetFilters()->count();
$period->setFilters($filters);
```

**Comment by mgrahamx** [comment]
@imbrish thanks for your comment. I considered adding/removing filters as many times as necessary however in this particular case my `CarbonPeriod` could contain up to 720 iterations (every hour within a maximum of one month). So won't adding/removing filters as you describe create a significant performance impact?

For clarity, I need to apply 10 or so filters. This would mean 7,200 loop cycles right?

For my current code I'm using a single loop of the entire `CarbonPeriod`, running my 'filters' (not actually Carbon filters, they were manually crafted currently) and storing the results manually. This means a maximum of 720 iterations in the worst case.

Essentially I need to classify every single hour within a one month period according to several filters. I also cannot iterate by day, it has to be by hour (since single days can have multiple filters within them).

**Comment by imbrish** [comment]
Then they're not technically filters - you want to classify 10 different aspects of every date-time within the period. I think adding this to the library wouldn't be very useful because your use case seems quite specific and can easily be implemented in the user code.

CarbonPeriod without filters iterates indefinitely, so we would need to limit classifier to alternate only between passed filters. What if someone would want to check 2 filters together not only one? What about applying some extra logic to resulting dates? In that case one cannot avoid extra iteration no matter what. Not to mention that grouping go way beyond an iterator.

Regarding performance - no other way than checking. Measure both cases and decide whether timing is acceptable. 7200 doesn't sound that scary, not gonna vouch for it but you may be surprised :)

**Comment by kylekatarnls** [comment]
Classify means "groupBy" to me, not "filter", it's a different operation. I suggest you to iterate with no filters, Get the group by any logic of your own inside the iteration, then dispatch values in an other array.

Agree with @imbrish about performance. Replacing loop with some if-else combination will not provide you a significant improvement. It would be nothing comparing to a caching system your side.

So what would you exactly expect from the library?

**Comment by kylekatarnls** [comment]
I close this issue for now, if you wish to provide code and your expectations, I'll re-open it.
