### ISSUE TITLE
Make it possible to force diffForHumans() to return "before/after" or "ago/from now" as I wish, independently of the $other argument being present or not

### ISSUE THREAD

**Issue by rulatir** [briannesbitt/Carbon#1364]
I have valid use cases where I want diffForHumans() to say "ago" even though I am giving a reference date, and "before" even though I am not giving a reference date.

Please make it possible to specify this with an extra option, as opposed to binding this to whether the reference date was given or not.

**Comment by imbrish** [comment]
I don't think that will justify adding fifth parameter to `diffForHumans`.

You can instead call `$date->diffForHumans($other/null, true)` to get the difference without either "ago" or "before" and add wanted suffix yourself.

It could be possible to rename second parameter to `$suffix` and let it accept special values like `Carbon::ABSOLUTE` and `Carbon::RELATIVE` in addition to default true for automatic and false for none, but as it is BC break I guess only in 2.0.

**Comment by kylekatarnls** [comment]
@imbrish Warning, ago, from now, before, after, are not suffixes in every languages, in French, ago and from_now gives prefixes. So I recommend to always use the translator:

```php
$date->diffForHumans(null, true);
// Get absolute syntax even if $other is null
$transId = $date->isFuture() ? 'after' : 'before';
echo Carbon::translator()->trans($transId, array('time => $date));

$date->diffForHumans($other, true);
// Get relative syntax even if $other is not null
$transId = $date->isFuture() ? 'from_now' : 'ago';
echo Carbon::translator()->trans($transId, array('time => $date));
```

Else I agree to change the `$absolute` boolean parameter with `$mode` integer parameter using constants in the version 2.

**Comment by kylekatarnls** [comment]
Will be implemented in version 2 with the following: https://github.com/briannesbitt/Carbon/pull/1372

**Comment by kylekatarnls** [comment]
Merged, you can test it by installing the verions `dev-version-2.0`
