### ISSUE TITLE
Inconsistency with diffInMonths()

### ISSUE THREAD

**Issue by markdwhite** [briannesbitt/Carbon#1376]
The diffInMonths() method seems to return inconsistent values:

> Carbon::parse('2018-06')->diffInMonths(Carbon::parse('2017-03'))
=> 15
> Carbon::parse('2018-05')->diffInMonths(Carbon::parse('2017-02'))
=> 14

If this is a feature due to different numbers of days in months, how can the above be changed to give a consistent response?

Thanks,

**Comment by kylekatarnls** [comment]
I get 15 for both, can you give more input:
PHP version
Carbon version
Timezon `var_dump(Carbon::parse('2018-06')->getTimezone()->getName());`

**Comment by markdwhite** [comment]
PHP 7.0.30-0ubuntu0.16.04.1 (cli) ( NTS )

name     : nesbot/carbon
versions : * 1.31.1
source   : [git] https://github.com/briannesbitt/Carbon.git 385780c8ca2dbfd25452666e3f55e8dc1df58c41

Timezone: Asia/Bangkok (no DST here)

This is only happening on a local dev server when the test suite runs, and only at the end/beginning of the month. Production is on UTC so I can work around this by forcing UTC in this code. 

Though it suggests that something is awry in calculation of month differences if UTC is not being used. If this is due to DateTime, I suppose not much can be done here.

Cheers.
