### ISSUE TITLE
Documentation clarification

### ISSUE THREAD

**Issue by lucasff** [briannesbitt/Carbon#1379]
Hi! I'm writing this issue because of the following text on the documentation.

> The default DateTime provides a couple of different methods for easily adding and subtracting time. There is modify(), add() and sub(). modify() takes a magical date/time format string, 'last day of next month', that it parses and applies the modification **while add() and sub() use a DateInterval class that's not so obvious, `new \DateInterval('P6YT5M')`**. Hopefully using these fluent functions will be more clear and easier to read after not seeing your code for a few weeks. But of course, I don't make you choose since the base class functions are still available.

I highlighted the part that doesn't make so much sense. Could it be rewritten? I want to understand why there's an indication of `new \DateInterval('P6YT5M')` there

**Comment by kylekatarnls** [comment]
Indeed, it's there for more than 3 years and it clearly needs an update.
