### ISSUE TITLE
CarbonInterval constructors don't perform conversion

### ISSUE THREAD

**Issue by LukasWieditz** [briannesbitt/Carbon#1390]
Creating an interval via `$interval = CarbonInterval::seconds(300)` and then accessing `$interval->minutes` returns `0`, even though the expected (or at least preferred) result would be `5`.

**Comment by imbrish** [comment]
Values of a CarbonInterval are not cascaded automatically, because this may work well for seconds to minutes conversion, but will be approximation and may lead to errors further down the road.

To achieve the result you want you'll need to call the cascade method explicitly:

```php
echo CarbonInterval::seconds(300)->cascade()->minutes; // 5
```

**Comment by kylekatarnls** [comment]
> CarbonInterval constructors don't perform conversion

No, indeed it doesn't, we never say it does.

There is a `cascade` method to do that (and fromString can also be used depending on the context). Please refer to the doc:
https://carbon.nesbot.com/docs/#api-interval

The behavior is inherited from PHP native DateInterval:
```php
var_dump(new DateInterval('PT300S')); // 300 seconds, 0 minutes
```

DateInterval and so CarbonInterval is unit-agnostic, it store them as separated values with no maximum value, and cascading operation depends on factors that can be customized.
