### ISSUE TITLE
Remove JsonSerializable file and increase min version to 5.4  

### ISSUE THREAD

**Issue by tonybolzan** [briannesbitt/Carbon#1394]
PHP 5.3.9 released in 10 January 2012 reached **EOL** in 14 Aug 2014, **3 years 11 months ago.**

This is time to increase min version of carbon at least to 5.4.

**Comment by kylekatarnls** [comment]
Carbon 1 will not drop PHP 5.3 as it's a breaking change and Carbon 2 requires PHP 7.1.

**Comment by tonybolzan** [comment]
Ok, you have a alpha/tech preview of Carbon2 ?

**Comment by kylekatarnls** [comment]
You can install the composer version `dev-version-2.0`.

An alpha will be release by the beginning of August.

And you can try it with http://try-carbon.herokuapp.com
