### ISSUE TITLE
Incoherent behavior of diffInMonths() ?

### ISSUE THREAD

**Issue by paulghz** [briannesbitt/Carbon#1395]
Hello everyone,

Using v1.27.0 of Carbon in a Laravel5.5 project, I've noticed a behavior that doesn't seem very logic :

In both cases I create 2 Carbon objects using the parse() function and the values below.

- If I use diffInMonths between '2019-03-15' and '2018-07-15', I get 8 (seems right)
- If I use diffInMonths between '2019-03-01' and '2018-07-01', I get 7 (seems not right, right ?)

**Comment by kylekatarnls** [comment]
Seems like a DST bug, try to do the same using UTC dates.

**Comment by kylekatarnls** [comment]
Let me know if it does not solve your problem and I'll re-open the issue if so.
