### ISSUE TITLE
diffInHours error

### ISSUE THREAD

**Issue by Henshall** [briannesbitt/Carbon#1397]
diffInHours() method doesnt always work properly - it will return '0' instead of the actual difference in hours between two carbon instances.

**Comment by Henshall** [comment]
thats strange... I was just having major issues with this method. I ran the exact code that was giving me problems and now it works fine... I also cloned the repo and tried the code and it also worked. I am closing this issue

**Comment by kylekatarnls** [comment]
I suspect you expected immutability, example:

```php
$date2 = $date->addHours(3);
$date2->diffInHours($date);
```
This returns `0` because `addHours` modify `$date` and returns it. So `$date2` and `$date` are the same object.

Here you need to clone/copy the date or with the version 2 of Carbon, use the CarbonImmutable class:
```php
$date2 = $date->copy()->addHours(3);
$date2->diffInHours($date);
```

**Comment by Henshall** [comment]
Yes that exactly what I was expecting. Thanks for letting me know how it works.

Have a great day!

Wes
