### ISSUE TITLE
gte() does not return expected value

### ISSUE THREAD

**Issue by louisluu** [briannesbitt/Carbon#1408]
Hi there,

Just setup a basic test for the gte() method, and realise the result is not as I expected.

Here is what I did:

```
$c1 = \Carbon\Carbon::now()->startOfDay()->addYear(1);

$c2 = \Carbon\Carbon::createFromTimestamp( strtotime('2019-08-01') );

dd( $c1->getTimestamp(), $c2->getTimestamp(), $c2->getTimestamp() >= $c1->getTimestamp(), $c2->gte($c1) );
```

Then here was the output from the `dd()`:

```
1564581600
1564581600
true
false
```

P/S: I have run composer update, so I believe Im using the latest version

Thanks

**Comment by louisluu** [comment]
Hey @kylekatarnls 

The code is used was exactly the same here, and they are in the same scope, nothing more.

I tried on https://try-carbon.herokuapp.com/ and I got `true` `true` as well.

Then I `dd()` that 2 objects and here we go:

```
$c1: date: 2019-08-02 00:00:00.496784 Australia/Melbourne (+10:00)

$c2: date: 2019-08-02 00:00:00.0 Australia/Melbourne (+10:00)
```

So the problem is: `modify('00:00:00.000000')` (called via `startOfDay()`) does not affect the millisecond ?!?

Am I missing something?

Thanks

**Comment by kylekatarnls** [comment]
Hum, it's a PHP bug of the version 7.0 if I remember well that makes microseconds immutable (it happens with DateTime native object, microseconds can be set but not changed). You should first consider upgrading to PHP 7.1 or newer. Then you can try:
```php
Carbon::useMicrosecondsFallback(false);
```
It should give you now without microseconds.

Or last, to be sure to get now without microseconds (in PHP 7.0),  you can use: `Carbon::today()->modify('now')`, this trick will initialize a date with 00:00:00.000000 and modify it to get current time. So if microseconds are not mutable, it will keep 0.

**Comment by louisluu** [comment]
Oh yeah, Im running 5.6. Tried 7.1 in localhost and it works like a charm.

And your trick works for me in PHP 5.6 as well.

Thanks
