### ISSUE TITLE
Localization does not affect ->format()

### ISSUE THREAD

**Issue by nasrulhazim** [briannesbitt/Carbon#1417]
Hi,

I've tried to use localization in Carbon, but it seems that the localization is not working.

Following are the simple test I did on Laravel Tinker

```
>>> \Carbon\Carbon::setLocale('ms')
=> true
>>> \Carbon\Carbon::getLocale()
=> "ms"
>>> \Carbon\Carbon::now()->format('l')
=> "Thursday"
```
Expected output is `Khamis` instead of `Thursday`. 

Or did I really need to use `formatLocalized()` and need to call `setlocale()`?

**Comment by nasrulhazim** [comment]
At the moment I have the following helper used:

```php
if (! function_exists('locale_date')) {
    function locale_date($datetime)
    {
        return (new IntlDateFormatter(
            config('app.locale'),
            IntlDateFormatter::GREGORIAN,
            IntlDateFormatter::NONE
        ))->format(\Carbon\Carbon::parse($datetime, config('app.timezone')));
    }
}
```

> `config('app.locale')` can be replace with other language.

> `config('app.timezone')` can be replace with other timezzone.

**Comment by kylekatarnls** [comment]
`format` is the native method of `DateTime`, it's not localized as explained in the documentation. `formatLocalized` is made for that in Carbon v1 but need languages packages to be installed on your OS. Carbon 2 has `isoFormat` that use internal translations and same format as in momentjs if you know it, it's the recommended way to translate date formats in Carbon v2 and will be soon documented.

If PHP native stuff such as `IntlDateFormatter` fit your need, there is no reason to look for something else.

Finally, you can put it in a macro if you ant it as a Carbon method:

```php
Carbon::macro('intlFormat', function () {
    return (new IntlDateFormatter(
        config('app.locale'),
        IntlDateFormatter::GREGORIAN,
        $formatter
    ))->format($this);
});
// ...
echo \Carbon\Carbon::parse($datetime, config('app.timezone'))->intlFormat();
```

Overriding the `format` method to get it affected by the chosen locale is an approach we wanted to avoid but if this is really what you want, you may be interested in https://github.com/jenssegers/date (Carbon v1 wrapper).

**Comment by kylekatarnls** [comment]
PS: in Carbon 2 if you just want the day name:
```php
echo \Carbon\Carbon::now()->locale('ms')->dayName;
// Or by changing the locale globally

\Carbon\Carbon::setLocale('ms');
echo \Carbon\Carbon::now()->dayName;
```

**Comment by nasrulhazim** [comment]
Ah, i see. 

Got it, didn't know that `Carbon` use macro. 

I will have macro work for my case - since I have quite a lot of places using carbon, so want to utilise and standardised everything to use macro.

Anyway, thanks for tips!
