### ISSUE TITLE
daysInMonth returns 31 days on februari

### ISSUE THREAD

**Issue by timwass** [briannesbitt/Carbon#1429]
Great library but I have found a small issue. When I create a new Carbon object with:

`$date = Carbon::create(2018, 2); //februari 2018`

When I check the date of the object it is februari 2018 like expected but when I want to return the number of days I get 31 days while februari only has 28 days.

`echo $date->daysInMonth //returns 31`

For other months daysInMonth seems to work like expected. I'm using Carbon in Laravel 5.6 and I'm running PHP 7.2.

Thanks!

**Comment by Vulfoliac** [comment]
Not a bug, 
When you don't pass the day as the 3rd parameter in the create method carbon will use today. eg my output is `2018-03-02 11:30:59.0 UTC`. (today is the 30th of aug so its adding 2 days to Feb getting you to the second of March) You need to pass the 3rd parameter or use a combination of startOfMonth, startOfDay, subMonth methods to get your result. 

Hope this helps

**Comment by kylekatarnls** [comment]
On last version `echo Carbon::create(2018, 2)->daysInMonth;` returns `28`.

On Carbon 1, your assertion `Carbon::create(2018, 2)` is februari 2018 can be wrong because of the behavior explained by @Vulfoliac. Use `Carbon::create(2018, 2, 1)` instead or upgrade to Carbon 2.

Thanks.

**Comment by timwass** [comment]
I checked what version of Carbon Laravel 5.6 is using and it's Carbon 1. So I have added the day param and you are right, I'm getting 28 days now for februari.

Thanks!

**Comment by kylekatarnls** [comment]
As I said above, Laravel 5.6 is on Carbon 1.25, the last stable version is 1.33 and Carbon 2 will be released soon. So you miss a lot of new features of Carbon. Laravel 5.8 will soon be released too and will probably use Carbon 2.

So I highly recommend to upgrade from Laravel 5.6 to 5.7 whenever possible (it will upgrade your Carbon version to 1.33) or else upgrade Carbon using `"nesbot/carbon": "1.33.0 as 1.25.0"` in your **composer.json** or the version using steps given in the doc as it's mostly backward compatible.
