### ISSUE TITLE
Create an array of "inverted" dates using CarbonPeriod

### ISSUE THREAD

**Issue by kevdotbadger** [briannesbitt/Carbon#1433]
Hello, I have a `CarbonPeriod` 

```
$day = new CarbonPeriod('2018-09-08 09:00', '15 minutes', '2018-09-08 17:00');
```

and an array of `CarbonPeriod`s.

```
$events = [
    new CarbonPeriod('2018-09-08 13:00', '15 minutes', '2018-09-08 14:00'),
    new CarbonPeriod('2018-09-08 15:00', '15 minutes', '2018-09-08 15:45'),
];
```

I'm not sure if it's possible using the filters, but I would like to return an array containing the reverse of any array. If this case it'll return an array container

```
[
    new CarbonPeriod('2018-09-08 09:00', '15 minutes', '2018-09-08 13:00'),
    new CarbonPeriod('2018-09-08 14:00', '15 minutes', '2018-09-08 15:00'),
    new CarbonPeriod('2018-09-08 15:45', '15 minutes', '2018-09-08 17:00'),
];
```

**Comment by kylekatarnls** [comment]
I don't understand a 3-items array being the inversion of a 2-items array. So I guess the array part is your app-side logic. For each period I see you take end for start then add the previous duration to the new interval to do that:

```php
$period = new CarbonPeriod('2018-09-08 13:00', '15 minutes', '2018-09-08 14:00');
$nextPeriod = new CarbonPeriod($period->getEndDate(), $period->getDateInterval(), $period->getEndDate()->add($period->getStartDate()->diff($period->getEndDate())));
```

Here `$nextPeriod` is equivalent to `new CarbonPeriod('2018-09-08 14:00', '15 minutes', '2018-09-08 15:00')`

Is it what you need?
