### ISSUE TITLE
Breaking changes between v1 and v2?

### ISSUE THREAD

**Issue by iget-master** [briannesbitt/Carbon#1435]
Hi,

I was reading changelog for version 2, and was just wondering if there's any breaking changes between version 1 and version 2, or it's a painless upgrade?

Sorry about that question, but your changelog isn't clear about that, and reading all commits between the releases is very time consuming. 

That answer may help https://github.com/laravel/ideas/issues/1313 to be accepted

**Comment by kylekatarnls** [comment]
We will provide a complete list but the very majority of methods are backward compatibles. A major change is the support drop of PHP <7.1.8.

**Comment by kylekatarnls** [comment]
https://carbon.nesbot.com/docs/#api-carbon-2

**Comment by connecteev** [comment]
+1 
This doesn't work with Laravel 5.8 without nesbot/carbon v 2.19

**Comment by kylekatarnls** [comment]
Nope, Carbon 1 is compatible with Laravel 5.8, but you may have an other dependency that doesn't. Still we highly recommend to use Carbon 2 as soon as you can since we'll soon stop updating Carbon 1.x

**Comment by kylekatarnls** [comment]
But Laravel dev-master (future 5.9) will drop Carbon 1, and require Carbon >= 2.0
