### ISSUE TITLE
 Interface 'Carbon\CarbonInterface' not found

### ISSUE THREAD

**Issue by sharmasourabh18** [briannesbitt/Carbon#1445]
Hello,

I encountered an issue :

 Interface 'Carbon\CarbonInterface' not found

**Comment by kylekatarnls** [comment]
Please do not remove the issue pattern, we can't help you without knowing your version, your code, how you load the library (composer autoload vs. manual includes).

**Comment by sharmasourabh18** [comment]
Hello,

I encountered an issue with the following code:
```php
include('Carbon-master/src/Carbon/Carbon.php');
include('lavacharts-3.1/src/Lavacharts.php');
use \Khill\Lavacharts\Lavacharts;
$lava = new Lavacharts;
$stocksTable = $lava->DataTable();  // Lava::DataTable() if using Laravel

$stocksTable->addDateColumn('Day of Month')
            ->addNumberColumn('Projected')
            ->addNumberColumn('Official');

// Random Data For Example
for ($a = 1; $a < 30; $a++)
{
    $rowData = array(
      "2014-8-$a", rand(800,1000), rand(800,1000)
    );

    $stocksTable->addRow($rowData);
}
```
Carbon version: **2.2.0**
PHP version: **5.6**

Thanks!

**Comment by kylekatarnls** [comment]
As explained in the documentation (https://carbon.nesbot.com/), you must not Carbon.php alone (Carbon rely on many files), you should  include the autoload.php file, then it will load each file for you only when needed.

But the very recommended way is to use composer instead. It will handle the autoload for you with as many composer libraries as you want.
