### ISSUE TITLE
Some methods from docs are undefined

### ISSUE THREAD

**Issue by kikky7** [briannesbitt/Carbon#1446]
Hello,

I need to get difference in milliseconds between 2 dates which is later passed to JS countdown.

When I use diffInSeconds() * 1000, I get different results in different browsers, so I tried to find a way to get milliseconds directly through API (I found some methods, but they are undefined when I try to use them)

I found those methods here:
https://carbon.nesbot.com/docs/#api-getters

I encountered an issue with the following code:
```php
$endsAt->diffInMicroseconds($now) - method does not exist
$now->valueOf() - method does not exist
$now->valueOf - unknown getter
```
Carbon version: 1.25.0
PHP version: 7.1.14

Thanks!

**Comment by kylekatarnls** [comment]
If you double-click on each of these methods, you will see they have been added in the version 2.0.0, so you can't use it if you do not upgrade your Carbon version. 1.25.0 is a bit old now (april) you may miss a lot of new features, you can upgrade safely to 1.34.0 or to 2.2.0 with a few breaking changes (https://carbon.nesbot.com/docs/#api-carbon-2).
