### ISSUE TITLE
issue on method today

### ISSUE THREAD

**Issue by mtferreira** [briannesbitt/Carbon#1452]
Hello,

I encountered an issue with the following code:
```php
echo Carbon::today()->addDays(30);
```
Carbon version: **1.34.0**
PHP version: **7.1.16**

I expected to get:
```
2018-11-04 00:00:00
```

But I actually get:
```
2018-11-04 01:00:00
```

OBS: My timezone is **America/Sao_paulo**

Thanks!

**Comment by kylekatarnls** [comment]
It's because of the summer time on 18 nov 2018. It's the native PHP behavior. Prefer to use UTC timezone `Carbon::today('UTC')->addDays(30)` and switch to your locale timezone for display only.

Or as it happens only on forward hour, you can also use `->setTime(0, 0)`

`echo Carbon::today()->addDays(30)->setTime(0, 0);`

**Comment by mtferreira** [comment]
Hey, thanks for the support ...
In fact, I came to think of this hypothesis, which I found a bit strange is that if I changed the days I mentioned to 31 or 29 everything would happen normally.

But regardless of daylight savings or not, should 'today' method not return the date with the hour, minutes and seconds set to zero?

**Comment by kylekatarnls** [comment]
If you `echo` the `today()` method before the adding, you'll see the hour is `00:00`, today() method has nothing to do with your problem, Carbon is just a wrapper of `DateTime`, so you can test it in raw PHP and see it's behave the same:
```php
$tz = new DateTimeZone('America/Sao_paulo');
$date = new DateTime('today', $tz); // Carbon::today()
// or to get the same date : new DateTime('2018-11-04 00:00:00', $tz);
$date->modify('30 days'); // ->addDays(30)
echo $date->format('Y-m-d H:i:s'); // 2018-11-04 01:00:00
```

Note that I tested 1.33 and 1.34 with PHP 7.1.9 and cannot reproduce the bug. Thanks to confirm you get consistent results with raw PHP.

**Comment by mtferreira** [comment]
ah yes I understood that this is native to PHP, but I did not pay attention that the 'addDays' method called after 'today' would not have the same treatment for the time information.

Again, thank you very much for the support ... I will use `` -> setTime (0, 0) `` in this case.

closing issue ...
