### ISSUE TITLE
diffAsCarbonInterval throw exception

### ISSUE THREAD

**Issue by arxeiss** [briannesbitt/Carbon#1456]
Hello,

I encountered an issue with the following code:
```php
date_default_timezone_set('Europe/Prague');
$now = new Carbon("2018-10-08 14:53:00");
echo((new Carbon("2018-11-15 14:00:00"))->diffAsCarbonInterval($now, false));
```
Carbon version: 1.33.0
PHP version: 7.2.10

I expected to get:
Some result

But I actually get:
Exception `Error: DateInterval::__construct(): Unknown or bad format (P1M7DT-1H7M)`

Thanks!

**Comment by kylekatarnls** [comment]
Thanks, it will now longer throw an error (you can test it using `"nesbot/carbon": "dev- version-1.next"` in **composer.json**

I aligned the behavior with the one of the version 2.

But the interval produced (by the native PHP DateTime::diff method) is still ver difficult to work with.

Now we have to think of a way to resolve negative units.

**Comment by arxeiss** [comment]
Can you please explain reason of this error? Because 

1. If I ommit timezone, it works as expected.
2. If I keep or remove timezone, but second date is in the same month, it works as well.

When I posted it, I expected that problem will be more complicated.

**Comment by kylekatarnls** [comment]
Confirmed and it also appears that PHP 5.3 does not have the bug. 2.x-dev no longer exist. I think you have an old branch. Now it's just master.

Native PHP Date API comes with a ton of bugs with daylight saving time. We always recommend to not doing any operation in a timezone. Always work with UTC date. Then apply timezone on display only. You neither should store timezoned dates in your database or other storage. Timezone should be something you can easily change any time (by just a per-user setting for example) without braking your data.

Any moment can always be represented as UTC and it gives your app dates reference that work all around the world.

A simple setTimezone before displaying it to the user will make everything transparent for the user.

I think we won't add any other fix unless for the version 1. We had enough regressions in the past by trying to work-around DST bugs.

**Comment by arxeiss** [comment]
I don't have old branch, I tested everything in your https://try-carbon.herokuapp.com. 

However, I don't expect any bug fix about timezones. I just found this because I use Laravel and updated timezone in the config.

But the main bug is fixed, I think, issue can be closed after mergin.

Thanks

**Comment by kylekatarnls** [comment]
I assure you it's a PHP bug and operations with timezones will produce a lot a problem. Most often, silent bugs that just make results wrong. My timezone on Laravel is always UTC, and I display dates with the timezone of the user's browser, user are all around the world, and even if you want to display the Prague timezone to everyone, there is no problem to work with UTC internally to have a timezone-agnostic backend. What would be the reason to set every dates on a particular timezone?

I recommend the following to fix negatives units of an interval produced by DST bug:
```php
$before = new Carbon('2018-10-08 14:53:00', 'Europe/Prague');
$after = new Carbon('2018-11-15 14:00:00', 'Europe/Prague');
$diff = $after->diffAsCarbonInterval($before, false);
$averageDaysInMonth = 30;
if ($diff->h < 0 && ($diff->d > 0 || $diff->m > 0 || $diff->y > 0)) {
    $diff->add(CarbonInterval::hours(24));
    if ($diff->d > 0) {
        $diff->add(CarbonInterval::day()->invert());
    } else if ($diff->m > 0) { // In this case, we use approximation
        $diff->add(CarbonInterval::days($averageDaysInMonth - 1));
        $diff->add(CarbonInterval::month()->invert());
    } else { // In this case, we use approximation
        $diff->add(CarbonInterval::months(11));
        $diff->add(CarbonInterval::days($averageDaysInMonth - 1));
        $diff->add(CarbonInterval::year()->invert());
    }
}

echo $diff;
```
