### ISSUE TITLE
Incorrect week day names in russian.

### ISSUE THREAD

**Issue by baldrs** [briannesbitt/Carbon#1458]
Hello,

I encountered an issue with the following code:
```php
require_once 'vendor/autoload.php';

use \Carbon\Carbon;

function mb_ucfirst($string, $encoding)
{
    $strlen = mb_strlen($string, $encoding);
    $firstChar = mb_substr($string, 0, 1, $encoding);
    $then = mb_substr($string, 1, $strlen - 1, $encoding);

    return mb_strtoupper($firstChar, $encoding) . $then;
}

setlocale(LC_TIME, 'ru_RU.UTF-8');
Carbon::setLocale('ru');

$now = Carbon::now('Europe/Kiev');

$now->locale('ru');

echo mb_ucfirst($now->isoFormat('dddd, D MMMM YYYY'), 'UTF-8');
```
Carbon version: 2.3.0
PHP version: 7.2.10

I expected to get:
```
Среда, 10 октября 2018
```

But I actually get:
```
Среду, 10 октября 2018
```
Which is incorrect as this is form used in something like "This Wednesday". I've also noticed  a weekend_standalone array in Lang/ru.php which has correct names but is not used anywhere.

Thanks!

**Comment by kylekatarnls** [comment]
This problem has no solution yet. And **weekdays_standalone** is there waiting for a solution to implement it. We know both forms exist in Russian but we just have no real way to know the context:
```php
echo Carbon::now('Europe/Kiev')->nextSunday()->isoFormat('[This] dddd'); // "Среду" expected
echo Carbon::now('Europe/Kiev')->isoFormat('dddd, D MMMM YYYY'); // "Среда" expected
```
It sounds like we should check other element in the expression to now how to display the day. But so what about:
```php
echo 'This ' . Carbon::now('Europe/Kiev')->nextSunday()->isoFormat('dddd'); // "Среду" expected
echo Carbon::now('Europe/Kiev')->isoFormat('dddd') . ', 10 октября 2018'; // "Среда" expected
```
In this example, we ran twice the exact same Carbon call but expect different outputs. And as tricky cases exists when you get multiple some complex sentences:
```php
echo Carbon::now('Europe/Kiev')->nextSunday()->isoFormat('[This] dddd [will be] D MMMM YYYY') . ', 10 октября 2018';
// or
echo Carbon::now('Europe/Kiev')->nextSunday()->isoFormat('[This] dddd [is] dddd, D MMMM YYYY') . ', 10 октября 2018'; 
```

Regarding of all examples above, what would you propose as a rule to take **weekdays_standalone** translations?

**Comment by baldrs** [comment]
I think default should be unaltered forms: понедельник, вторник, среда, четверг, пятница, суббота, воскресенье.

In most of the cases you want these forms, and others almost exclusively as moment.js defines them(see isFormat): 

```javascript     
    weekdays : {
            standalone: 'воскресенье_понедельник_вторник_среда_четверг_пятница_суббота'.split('_'),
            format: 'воскресенье_понедельник_вторник_среду_четверг_пятницу_субботу'.split('_'),
            isFormat: /\[ ?[Вв] ?(?:прошлую|следующую|эту)? ?\] ?dddd/
    },
```

**Comment by kylekatarnls** [comment]
In fact, the moment.js is probably the best it can be and could be enough in a russian-only application where you can have:
```php
echo Carbon::now()->isoFormat('[В] dddd');
```
Or in moment.js:
```js
console.log(moment().format('[В] dddd'));
```
This way, we will be able to well detect `[В]` as `following day need to be formatted`. But if you have multiple languages `[В]` need to be also translated. So you need to know day names can have multiple forms according to the context and so translate first the context, then inject it in the format string.

I will implement it this way first, but it would be great to have something more obvious for non-polyglot developers.

**Comment by kylekatarnls** [comment]
You can yet test the new output on `dev-master` version:

```php
$date->isoFormat('[в] dddd') // в среду
$date->isoFormat('dddd, D MMMM YYYY') // среда, 10 октября 2018
$date->dayName // среда
```

It will not be released yet as I first want to apply equivalent logic for other languages with multiple forms and document it.

Thanks.

**Comment by baldrs** [comment]
@kylekatarnls thanks for resolving this quickly! I'm going to check it little bit later
