### ISSUE TITLE
Docs outdated for `add()` - only accept DateInterval

### ISSUE THREAD

**Issue by jrmadsen67** [briannesbitt/Carbon#1462]
Hello,

I encountered an issue with the following code in the docs:
```php
// Generic methods add/sub (or subtract alias) can take many different arguments:
echo $dt->add(61, 'seconds');                      // 2012-02-03 00:01:01
echo $dt->sub('1 day');                            // 2012-02-02 00:01:01
```
The api now only supports a single argument of a DateInterval:

```
public function add (DateInterval $interval) {}
```

**Comment by jrmadsen67** [comment]
Thanks! The code I was trying was:

`Carbon::now()->add('30 minutes')`

and

`Carbon::now()->add(30, 'minutes')`

from inside a Laravel 5.7 app (with Carbon ^1.26.3, it seems). Is there
anything I can check to help confirm/deny/explain a problem?

**Comment by kylekatarnls** [comment]
No, it works as expected. Laravel 5.7 use Carbon 1 by default, so you can't use Carbon 2 features. Either upgrade to Carbon 2 following the doc explanations for Laravel users: https://carbon.nesbot.com/, either upgrade to Laravel 5.8 that natively fully support Carbon 2 but it's not yet released as stable.

Remember Carbon is not part of Laravel, it's a standalone library. Examples always use the last version no matter the Laravel state of art.

And we provide a complete list of the methods with versions notes to let users know when they have been added and what changes happened in which version.

**Comment by jrmadsen67** [comment]
right, apologies!

I thought for some reason that those particular ways of using the function
dated back to version 1. Looks like we'll be getting them in V5.8 - sorry
to waste your time, and go ahead and close this

Jeff
