### ISSUE TITLE
[FEATURE] Fast static conversion to string for json-response

### ISSUE THREAD

**Issue by KartaviK** [briannesbitt/Carbon#1463]
Hello,

I encountered an issue with the following code:
```php
/** @var DateTimeInterface|string|null $date*/

$json = [
    'date' => [
        'short' => Carbon::make($date)->toDateString(), // if $date is null will throw an exception
        'full' => Carbon::make($date)->toDateTimeString(),
    ],
];
```
Carbon version: 1.33
PHP version: 7.2

I constantly develop various small libraries for their further integration into projects. Projects are server applications that communicate using `json`. And very often it is required for models to use `\JsonSerializable`. The model field type for dates is set to `?\DateTimeInterface` for `typehint` validation. In the `jsonSerialize()` method, I need to check for the presence of `null` in the field, so as not to throw an exception when calling the method on `null`.

I suggest adding a method like `make`, but it will return `string|null`. If a string, then it will be in the form in which the format is specified. If null, then just null. This, I think, will make the code more beautiful for json-serialization.

Method `serializeUsing()` not so convenient as I would like, because I need to form dates of different formats in one response, including `null`

Proposed method:
```php
/** @var DateTimeInterface|string|null $date*/
/** @var callable|null $callback */
$json = [
    'date' => Carbon::trySerialize($date, $callback),
]
```

Thanks!

P.S. sorry if my english look bad :(

**Comment by kylekatarnls** [comment]
This sounds like a perfect candidate for a macro. Something like:
```php
Carbon::macro('trySerialize', function ($date) {
  if (is_null($date)) {
    return null;
  }
  return Carbon::make($date)->toDateString();
});
```

PS: Note than in Carbon 2, Carbon instance are automatically turned into strings in JSON.

**Comment by KartaviK** [comment]
This is a good solution, but we have design rules for not using this magic in libraries.

**Comment by kylekatarnls** [comment]
I'm sorry for that but we're not going to re-implement every features without magic methods.

1/ Anything you can do with macro can be done the same way with extends:
```php
class MyCarbon extends Carbon
{
  public static function ($date){
    if (is_null($date)) {
      return null;
    }
    return static::make($date)->toDateString();
  }
}
```
That's the way it always works in PHP, you want custom behavior over a library, you extends it. You want it keeping the same base class, we offer marcos and mixins features for this purpose. But is feature is not enough generic to be in the core library in my opinion.
2/ Carbon 2 use a lot more of magic methods, but as they are all documented with PHPDoc and consistently set, it makes no difference for the developer, you cannot know what method is magic without opening the code. And magic methods can avoid a lot of duplicate code, so such nazi rule can be really anti-productive and create more maintenance pain that what it aims to avoid.
