### ISSUE TITLE
Function for showing difference between dates in floating value not working

### ISSUE THREAD

**Issue by beingbishwa** [briannesbitt/Carbon#1477]
Hello,

I encountered an issue with the following code:
```php
echo Carbon::parse('06:01:23.252987')->floatDiffInSeconds('06:02:34.321450');
```
Carbon version: In both 1.22.1 and 2.3.0
PHP version: 7.1.3

I expected to get:
```
71.068463
```

But I actually get:
```
Error: Method floatDiffInMinutes does not exist.
```

The error can be reproduced by clicking the link below:
[Function for showing difference between dates in floating value not working](https://try-carbon.herokuapp.com/?embed&theme=xcode&border=silver&options-color=rgba(120,120,120,0.5)&input=Carbon%3A%3Aparse(%2706%3A01%3A23%27)-%3EfloatDiffInMinutes(%2706%3A02%3A34%27)%3B%0A)

Thanks!
[Bishwa Poudel](https://github.com/beingbishwa)

**Comment by kylekatarnls** [comment]
As you can see by clicking the **Reference** menu in the doc, `floatDiff*` methods have been added in **2.4.0**
