### ISSUE TITLE
CarbonPeriod success even if the date is invalid

### ISSUE THREAD

**Issue by HarikiRito** [briannesbitt/Carbon#1478]
Hello,

I encountered an issue with the following code:
```php
echo CarbonPeriod::between('2018-02-31', '2018-11-31');
```
Carbon version: **2.4.0**
PHP version: **7.2.9**

I expected to get:
```
InvalidDateException
```

But I actually get:
```
Every 1 day from 2018-03-03 to 2018-12-01
```

[Link to TryCarbon](https://try-carbon.herokuapp.com/?embed&theme=xcode&border=silver&options-color=rgba(120,120,120,0.5)&input=echo%20CarbonPeriod%3A%3Abetween(%272018-02-31%27%2C%20%272018-11-31%27)%3B)

Thanks!

**Comment by kylekatarnls** [comment]
Yes, you can show the following with pure PHP:

```php
echo (new DateTime('2018-02-29'))->format('Y-m-d')."\n";
echo (new DateTime('2018-02-31'))->format('Y-m-d')."\n";
echo (new DateTime('2018-02-36'))->format('Y-m-d')."\n";
```

```
2018-03-01
2018-03-03
Error: DateTime::__construct(): Failed to parse time string (2018-02-36) at position 9 (6): Unexpected character
```

https://try-carbon.herokuapp.com/?embed&theme=xcode&border=silver&options-color=rgba(120,120,120,0.5)&input=echo%20(new%20DateTime(%272018-02-29%27))-%3Eformat(%27Y-m-d%27).%22%5Cn%22%3B%0Aecho%20(new%20DateTime(%272018-02-31%27))-%3Eformat(%27Y-m-d%27).%22%5Cn%22%3B%0Aecho%20(new%20DateTime(%272018-02-36%27))-%3Eformat(%27Y-m-d%27).%22%5Cn%22%3B

**Comment by kylekatarnls** [comment]
Note: you can check dates with `echo Carbon::createSafe(2018, 2, 31);` and so you can do the following for periods:
```php
echo CarbonPeriod::between(Carbon::createSafe(2018, 2, 31), Carbon::createSafe(2018, 11, 31));
```
Here, you will get `day : 31 is not a valid value`.

**Comment by kylekatarnls** [comment]
Yes you can check dates with `echo Carbon::createSafe(2018, 2, 31);` and so you can do the following for periods:
```php
echo CarbonPeriod::between(Carbon::createSafe(2018, 2, 31), Carbon::createSafe(2018, 11, 31));
```
Here, you will get `day : 31 is not a valid value`.

**Comment by kylekatarnls** [comment]
Yes you can check dates with `echo Carbon::createSafe(2018, 2, 31);` and so you can do the following for periods:
```php
echo CarbonPeriod::between(Carbon::createSafe(2018, 2, 31), Carbon::createSafe(2018, 11, 31));
```
Here, you will get `day : 31 is not a valid value`.
