### ISSUE TITLE
floatDiffInMonths not working correctly

### ISSUE THREAD

**Issue by beingbishwa** [briannesbitt/Carbon#1490]
Hello,

I encountered an issue with the following code:
```php
echo Carbon::parse('2000-01-15 00:00')->floatDiffInMonths('2000-02-20 00:00');
```
Carbon version: master of github
PHP version: 7.1.3

I expected to get:
```
any value more than 1
```

But I actually get:
```
0.82758620689655
```
I tried with other dates as well and it seems to have issue.
Like:
```php
echo Carbon::parse('2018-12-16 00:00')->floatDiffInMonths('2019-12-15 00:00');
```
Above code must output a floating value nearing to 12 but instead output shows 10.048387096774

Thanks!

**Comment by kylekatarnls** [comment]
I ran the exact the exact same code and get 1.1724137931034484:
```php
Carbon::parse('2000-01-15 00:00')->floatDiffInMonths(Carbon::parse('2000-02-20 00:00')) // 1.1724137931034484
Carbon::parse('2000-01-15 00:00')->floatDiffInMonths('2000-02-20 00:00') // 1.1724137931034484
Carbon::parse('2018-12-16 00:00')->floatDiffInMonths('2019-12-15 00:00') // 11.951612903225806
```
I'm on master too and PHP 7.2  but this should not depends on the PHP version.

Can you provide more context? Do you reproduce that on a stand-alone file (that would just include vendor/autoload.php then run this code)?

**Comment by beingbishwa** [comment]
That is still reproducible in stand alone file including just carbon package.
My composer.json looks like this:
```
{
    "require": {
        "nesbot/carbon": "^2.5"
    }
}
```

The output is recorded in following gif file:


![click here to open gif](https://user-images.githubusercontent.com/16562819/47759188-865aa680-dcd6-11e8-8845-2b9e970e636c.gif)

**Comment by kylekatarnls** [comment]
@hlgkb Do you get the same result for this code? (0.82758620689655)
@beingbishwa I added a unit test for this: https://github.com/kylekatarnls/Carbon/commit/81d097aa40e8d46ccd8f084bf8e3a19d710002ad

And it passes in PHP 7.1, 7.2 and 7.3 on Travis. Could you compare with UTC timezone and tell me what is your default timezone used:

```php
echo Carbon::parse('2000-01-15 00:00', 'UTC')->floatDiffInMonths('2000-02-20 00:00') ;
```

**Comment by kylekatarnls** [comment]
It's not a timezone issue neither, I tried with all of them:

```php
        foreach (timezone_identifiers_list() as $zone) {
            $this->assertSame(1.1724137931034484, Carbon::parse('2000-01-15 00:00', $zone)->floatDiffInMonths(Carbon::parse('2000-02-20 00:00', $zone)));
            $this->assertSame(1.1724137931034484, Carbon::parse('2000-01-15 00:00', $zone)->floatDiffInMonths('2000-02-20 00:00'));
            $this->assertSame(11.951612903225806, Carbon::parse('2018-12-16 00:00', $zone)->floatDiffInMonths('2019-12-15 00:00'));
        }
```
I have no idea what you get different result than on my machine and on the Travis CI. I cannot go further as I can't reproduce the bug. Maybe a bug in your OS calendar. What's your OS and what is your version of Xampp?

Ideally it could help me a lot to fix it if you could reproduce it on Travis CI (fork Carbon and make a unit test that fails on Travis too). You could also try to run all Carbon unit tests with phpunit on your machine to see if there are other broken tests.

**Comment by kylekatarnls** [comment]
The same code still works on the live editor: https://try-carbon.herokuapp.com/?input=echo%20Carbon%3A%3Aparse(%272000-01-15%2000%3A00%27)-%3EfloatDiffInMonths(%272000-02-20%2000%3A00%27)%3B

I'm really sorry but this bug seems not related to the library. I will let this issue on hold waiting for getting more clues.

**Comment by drupol** [comment]
> The same code still works on the live editor: https://try-carbon.herokuapp.com/?input=echo%20Carbon%3A%3Aparse(%272000-01-15%2000%3A00%27)-%3EfloatDiffInMonths(%272000-02-20%2000%3A00%27)%3B
> 
> I'm really sorry but this bug seems not related to the library. I will let this issue on hold waiting for getting more clues.

Hi,

I really like this interface to test your library, where can I get the source ?

Thanks !

**Comment by kylekatarnls** [comment]
It's open-source too:
https://github.com/kylekatarnls/try-carbon

I originally designed for the documentation of Phug: https://www.phug-lang.com
https://pug-demo.herokuapp.com/
https://github.com/pug-php/pug-demo

**Comment by kylekatarnls** [comment]
Hi @beingbishwa the track of https://github.com/mongodb/mongo-swift-driver/pull/136 is quite interesting I think, would you please tell me what OS and OS version you run the code and get the wrong result?

**Comment by hlgkb** [comment]
@kylekatarnls Sorry for the late reply. I am also facing the same issue. 

For Difference in date `2000-01-15 00:00` and `2000-02-20 00:00`

Calculating the duration we get
 
[Days difference between `2000-01-15 00:00` and `2000-02-20 00:00`](https://www.timeanddate.com/date/timezoneduration.html?d1=15&m1=01&y1=2000&d2=20&m2=02&y2=2000&h1=00&i1=00&s1=00&h2=0&i2=0&s2=0&)
```
35 days, 18 hours, 15 minutes and 0 seconds
```
Using Carbon's `floatDiffInDays` 
```php
echo Carbon::parse('2000-01-15 00:00')->floatDiffInDays(Carbon::parse('2000-02-20 00:00', 'asia/kathmandu')) . "\n";
```
Results in
```
35
```

But when using Carbon's `floatDiffInMonths` we get  
```php
echo Carbon::parse('2000-01-15 00:00', 'UTC')->floatDiffInMonths(Carbon::parse('2000-02-20 00:00', 'asia/kathmandu')) . "\n";

```
Result
```
0.86206896551724
```

PHP version: 7.2.0
Carbon Version: 2.5.0

![image](https://user-images.githubusercontent.com/9023528/48036664-7db01780-e191-11e8-8f27-c60232ef7d4d.png)

**Comment by kylekatarnls** [comment]
Thanks @hlgkb so it can happen on both PHP 7.1 and 7.2. You both use Kathmandu timezone but I still have not those wrong results even using this timezone neither on https://try-carbon.herokuapp.com/ or on my local machine.

I see you have Windows, so it's not related to Mac OS bug mentioned earlier.

I will try some tests with raw PHP.

@hlgkb, @beingbishwa Can you get the result of:

```php
$start = Carbon::parse('2000-01-15 00:00', 'UTC');
$end = Carbon::parse('2000-02-20 00:00', 'asia/kathmandu');

var_dump($start->daysInMonth);
var_dump($end->daysInMonth);
$monthsDiff = $start->diffInMonths($end):
var_dump($monthsDiff);
$floor = $start->copy()->addMonths($monthsDiff);
echo $floor . "\n";
echo $floor->copy()->addMonth()->startOfMonth() . "\n";
```

They are values we use internally to calculate the floating difference, To know which one is different on your machines could help to find what could be set differently.

Could you also dump your `phpinfo()` please? If I could have it from both of you, it could help me to know what extensions you have in common.

**Comment by drupol** [comment]
Hi guys, 

I'm building a new app to test any php library in your browser. 
You can try it here : http://try-a-lib.herokuapp.com/

Let me know how it goes :)

**Comment by kylekatarnls** [comment]
Dude, that's awesome!

So often I had to download libraries to test them. I will always use this.

Goes pretty fine for most libraries. I noticed however that I was unable to select the 2.5.0 version of Carbon and had a 500 error on loading big framework (such as laravel/framework).

If you have a GitHub repository for this, I would be glad to give you more detailed feedback and help you checking code if you like.

**Comment by drupol** [comment]
Thanks mate, i'm planning to set it up today, I will ping you when its done. 

I noticed a huge load on heroku, maybe hosting it somewhere else would be better.

**Comment by kylekatarnls** [comment]
Hi guys @hlgkb, @beingbishwa, I suspect a broken/incomplete/incompatible install (missing calendar extension, 32bit vs. 64bit) or an OS calendar problem, do your systems use gregorian calendar?

There are still multiple possible root causes and I cannot filter them without `<?php phpinfo()` data and I will not be able to reproduce it without the results of the code chunk I gave above.

If you find the reason or a way to fix it. It would be nice to share it. Meanwhile, I will stop investigating until having more output from you.

Thanks.

**Comment by Healyhatman** [comment]
Is there anything you would need to try and get a resolution on this? Running the following

`Carbon::parse('2000-01-15 00:00')->floatDiffInHours('2000-02-15 00:00')`

gives me 744, but my colleague gets -0.46099797333333 

I know it's been 2 years but this is still the most relevant search result.

**Comment by kylekatarnls** [comment]
Try with pure PHP:
```php
echo ((new DateTime('2000-02-15 00:00'))->getTimestamp() - (new DateTime('2000-01-15 00:00'))->getTimestamp()) / 3600;
```

If you get the same problem, it's not a Carbon issue (what I presume) and means your colleague should re-install properly his/her PHP version, check his/her OS calendar and clock settings.

**Comment by Healyhatman** [comment]
The code you gave spits out 744 for him, the carbon I showed still gives the crazy negative float.

**Comment by kylekatarnls** [comment]
Thanks. Can you try with `floatDiffInRealHours()` instead?

`floatDiffInRealHours` uses timestamps as the code above, while `floatDiffInHours()` used the `diff()` method of `DateTime` internally (the only difference is supposed to be in DST changes).

If `floatDiffInRealHours` you should try to check the output of:

```php
var_dump((new DateTime('2000-02-15 00:00'))->diff(new DateTime('2000-01-15 00:00'));
```

If here you get difference, it's the root cause, and would also mean something is wrong with the PHP install.

**Comment by Healyhatman** [comment]
The last thing you posted gives
```
object(DateInterval)#4703 (16) {
  ["y"]=>
  int(0)
  ["m"]=>
  int(1)
  ["d"]=>
  int(0)
  ["h"]=>
  int(0)
  ["i"]=>
  int(0)
  ["s"]=>
  int(0)
  ["f"]=>
  float(0)
  ["weekday"]=>
  int(0)
  ["weekday_behavior"]=>
  int(0)
  ["first_last_day_of"]=>
  int(0)
  ["invert"]=>
  int(1)
  ["days"]=>
  int(31)
  ["special_type"]=>
  int(0)
  ["special_amount"]=>
  int(0)
  ["have_weekday_relative"]=>
  int(0)
  ["have_special_relative"]=>
  int(0)
}

```

Using floatDiffInRealHours gives 744 so I don't know why or what that means

**Comment by Healyhatman** [comment]
It's all sorted now thanks. Appears to be an issue with PHP 7.2.1. Upgrading to 7.2.14 fixed it.

**Comment by kylekatarnls** [comment]
Awesome to finally know the root cause! Great job. I hope this will help other people.

For the record, we will no longer the method using `DateTime::diff` in Carbon 3, "real" method will replace the default one. #2119
