### ISSUE TITLE
Oct 31 bug

### ISSUE THREAD

**Issue by tarekadam** [briannesbitt/Carbon#1491]
Hello,

I encountered an issue with the following code on October 31st:

Carbon::parse('last month');

Carbon version: 1.34.0
PHP version: 7.2.3

I expected to get: the end of last month
But I actually get: the start of this month

I've seen dates evaluate like this before.  Sept 31 becomes Oct 1.  Nov 31 becomes Dec 1.  I wouldn't say it's a bug.  Just an  improvement to the language parsing.

Thanks!

**Comment by kylekatarnls** [comment]
Carbon is not responsible for this parsing, we give those string as is to PHP DateTime native object and as you can see, when calling "last month", if the current day does not exist in this month, it fallback to 1st, this avoids an overflow which would be clearly worst.

See this raw PHP snippet: https://3v4l.org/TgO9v

But you still can work around this behavior by choosing explicitly to go to end of month if the day is not the same:

```php
$lastMonth = Carbon::parse('last month');
if ($lastMonth->day != Carbon::now()->day) {
  $lastMonth->endOfMonth();
}
```

**Comment by tarekadam** [comment]
gotcha.
