### ISSUE TITLE
Cannot extends Carbon classes in a symfony (4) project because of @alias annotations

### ISSUE THREAD

**Issue by Cethy** [briannesbitt/Carbon#1502]
Hello,

I encountered an issue with the following code:
```php
class Foo extends CarbonImmutable{}
```
Carbon version: **2.5.1**
PHP version: **7.2**
Symfony version: **4.1.7**

I expected to get:
```
// something working
```

But I actually get:
```
An exception has been thrown during the rendering of a template ("[Semantical Error] The annotation "@alias" in method Carbon\CarbonImmutable::clone() was never imported. Did you maybe forget to add a "use" statement for this annotation? in config/routes/../../src/ (which is being imported from "config/routes/annotations.yaml"). Make sure annotations are installed and enabled."). (Twig_Error_Runtime)
```

`routes/annotations.yaml`
```yaml
actions:
    resource: ../../src/
    type: annotation
```

The Foo class is ignored from service autoloading (as it is a "model"), but is not ignored from routes scanning.

Thanks!

**Comment by Cethy** [comment]
I fixed my use-case w/ the decoration pattern.
But since this lib has some symfony dependencies, I feel like it should integrate seamlessly with the rest of the ecosystem.

**Comment by Cethy** [comment]
The 2 ways I see to resolve it :
- adding a annotation which does nothing in Carbon library ;
- using [some kind of magic](https://www.doctrine-project.org/api/annotations/1.6/Doctrine/Common/Annotations/DocParser.html#method_setIgnoredAnnotationNames) to ignore the annotation in symfony ;

the first solution add clutter to the library (which is far from ideal, but seem to work as per my tests), the second could be done with a [flex recipe](https://flex.symfony.com/) and a way to hook in the `AnnotationReader`, but I sadly lack the expertise to do it.

**Comment by Cethy** [comment]
**Update:** 
Opened an issue on the symfony repo : https://github.com/symfony/symfony/issues/29161

**Comment by kylekatarnls** [comment]
I really don't understand why CarbonImmutable works while a sub-class extending it does not.

**Comment by kylekatarnls** [comment]
As for as I understand, it only happens when you extends it inside the src directory. If you do you `extends`, outside this directory, it will work fine, so this sounds like a check Symfony do on project declared classes.

**Comment by kylekatarnls** [comment]
In fact only extends inside a directory configured with annotations (like Controllers) has this constraint (and it seems fair as it means annotations of Carbon can be seen as route annotations.

But if you declared your date extends in the Entity directory (semantically far more logical than Controller directory), Symfony will not reject it.

So I just recommend to follow Symfony architecture and PHP best practice: each file should contains only one class declaration or one symbol, and controller file should contains only controllers.

**Comment by Cethy** [comment]
@kylekatarnls Your understanding of the problem is right. But the particular architecture used in the project does not and could not allow the routing mechanisms to not check some irrelevant classes.

Anyway, closing here as the problem should be fixed symfony-side.
