### ISSUE TITLE
Version 1.34.2 brake application

### ISSUE THREAD

**Issue by pavinthan** [briannesbitt/Carbon#1506]
Hello,

I encountered an issue with the following code:
```php
ErrorException: Undefined property: DateInterval::$f 
in vendor/nesbot/carbon/src/Carbon/Carbon.php:3979
```
Carbon version: **1.34.2**
PHP version: **PHP 7.0.15-0ubuntu0.16.04.4 (cli) ( NTS )**

Thanks!

**Comment by kylekatarnls** [comment]
Hi,

Sorry, as tests passed on PHP 7.0.25, I forgot PHP had this shitty bug until 7.0.22:
https://bugs.php.net/bug.php?id=74852

It is what you get.

We will release a patch compatible with PHP 7.0 to 7.0.22.

Still you're far behind PHP 7.0.35 (the current 7.0.x) and this include security fixes, so I recommend to update as soon as possible.

Thanks.

**Comment by kylekatarnls** [comment]
Hi, you can now upgrade to Carbon 1.34.3. Thanks.

**Comment by pavinthan** [comment]
OK, Thanks @kylekatarnls really a good work 👍
