### ISSUE TITLE
[v1.35.0] diffInSeconds() incorrect by 86399 seconds if one date has microseconds

### ISSUE THREAD

**Issue by uphlewis** [briannesbitt/Carbon#1515]
Hello,

I encountered an issue with the following code:
```php
$requestTime = new \Carbon\Carbon('2018-11-14 18:23:12.0 +00:00');
$serverTime = new \Carbon\Carbon('2018-11-14 18:23:12.307628 +00:00');

return  $serverTime->diffInSeconds($requestTime); //should be int 0 or int 1, but actually returns int 86399
```
Carbon version: 1.35.0
PHP version:7.2.12-1+ubuntu18.04.1+deb.sury.org+1

I expected to get:
```
0
```

But I actually get:
```
86399
```

Obviously this is very close to being 1 day worth of seconds, so something strange appears to be going on somewhere...

Thanks!

**Comment by uphlewis** [comment]
Further to the above if you do the diff in the other direction, it works as expected...

```php
echo $requestTime->diffInSeconds($serverTime, true) // 0 <-- correct
echo $serverTime->diffInSeconds($requestTime, true); // 86399 <-- incorrect
```

**Comment by uphlewis** [comment]
To give some more context, the `$requestTime` is created out of an RFC-7231 formatted timestamp which doesnt have microseconds. The `$serverTime` is created with a simple `Carbon::now(new \DateTimeZone('GMT');)` so obviously does have microseconds.

This bug only happens when the time being diffed doesn't have microseconds, but the time doing the diffing does have microseconds.

**Comment by uphlewis** [comment]
The above is on a Homestead Vagrant VirtualBox VM.

Running the same code on my local machine with `PHP 7.2.11-4+ubuntu18.04.1+deb.sury.org+1`, I can't reproduce the bug.

So it could be specific to `PHP 7.2.12-1`

**Comment by pulkitjalan** [comment]
Having the same issue, specifically on 7.2.12, not happening on 7.2.10

**Comment by stueynet** [comment]
Also not happening on 7.2.11.

**Comment by uphlewis** [comment]
http://php.net/ChangeLog-7.php#7.2.12

> Date:
> - Upgraded timelib to 2017.08.
> - Fixed bug #75851 (Year component overflow with date formats "c", "o", "r" and "y").
> - Fixed bug #77007 (fractions in `diff()` are not correctly normalized).

**Comment by kylekatarnls** [comment]
Or simplest work-around (often more relevant too), use `diffInRealSeconds` that uses internally timestamps rather than date intervals. (So no call to `diff()` which has changed on 7.2.12)

**Comment by kylekatarnls** [comment]
This should fix this case: #1517 waiting for tests to pass in every PHP versions to be sure.

**Comment by kylekatarnls** [comment]
Hi guys, please retry with 1.35.1.

Note: `diff()` results still uses native PHP DateTime with no filtering, so this fix catch the PHP bug introduced in PHP 7.1.12 in diffAsCarbonInterval and diffInXxx methods but raw methods from DateTime class will still produce unexpected outputs for differences less than 1 second.

**Comment by uphlewis** [comment]
Yep `1.35.1` fixes it :) Awesome stuff thanks so much for the rapid turnaround !!

```php
$ artisan tinker
Psy Shell v0.9.9 (PHP 7.2.12-1+ubuntu18.04.1+deb.sury.org+1 — cli) by Justin Hileman
>>> $requestTime = new \Carbon\Carbon('2018-11-14 18:23:12.0 +00:00');
=> Carbon\Carbon @1542219792 {#2980
     date: 2018-11-14 18:23:12.0 +00:00,
   }
>>> $serverTime = new \Carbon\Carbon('2018-11-14 18:23:12.307628 +00:00');
=> Carbon\Carbon @1542219792 {#2981
     date: 2018-11-14 18:23:12.307628 +00:00,
   }
>>> $serverTime->diffInSeconds($requestTime);
=> 0
>>> $requestTime->diffInSeconds($serverTime);
=> 0
```

**Comment by pulkitjalan** [comment]
Thanks for the fix, works great 👍

Pulkit Jalan
