### ISSUE TITLE
Difference in days with filter returning same as difference in weekdays

### ISSUE THREAD

**Issue by SirReno** [briannesbitt/Carbon#1528]
Hello,

I encountered an issue with the following code:
```php
    $start=Carbon::createFromDate(2018, 11, 17);
    $end=Carbon::createFromDate(2018, 11, 20);
$holidays = [
                        Carbon::createFromDate(2018, 11, 19),
];
                    $days = $start->diffInDaysFiltered(function (Carbon $date) use ($holidays) {
                        echo " ".$date->isWeekday()."\n";
                        return $date->isWeekday() && !in_array($date, $holidays);
                    }, $end);
```
Carbon version: 1.32.0
PHP version: 7.1.20

I expected to get only 1 since its from saturday to tuesday, but monday is holiday
```
1
```

But I actually got locally
```
2
```
![image](https://user-images.githubusercontent.com/21368425/48810278-185e3980-ecee-11e8-9a06-973384021aec.png)

But I actually got on https://try-carbon.herokuapp.com/
```
0
```
![image](https://user-images.githubusercontent.com/21368425/48810297-2a3fdc80-ecee-11e8-92a2-0d3640ffb5cd.png)

Thanks!

**Comment by kylekatarnls** [comment]
First of all,

We made dedicated mixins to handle holidays:
https://github.com/kylekatarnls/business-day

Holidays + Opening hours
https://github.com/kylekatarnls/business-time

It would probably save a lot of your time.

If you have different results locally and on try-carbon, you probably have actually different input. For exemple be aware that `createFromDate` compose the date you give with the current time. In your case `createMidnightDate` sounds like a better choice.

Finally as $end is not included (we test `< $end`), you should shift the end, for example add a second.

```php
$start=Carbon::createMidnightDate(2018, 11, 17);
$end=Carbon::createMidnightDate(2018, 11, 20);
$holidays = [
  Carbon::createMidnightDate(2018, 11, 19),
];
$days = $start->diffInDaysFiltered(function (Carbon $date) use ($holidays) {
  echo "$date\n";
  return $date->isWeekday() && !in_array($date, $holidays);
}, $end->addSecond());
var_dump($days);
```
Outputs `1`

**Comment by SirReno** [comment]
mmm... alright ill have to check those business-day, the problem with the CreateMidnightDate(), is that I need the hours and minutes :/

**Comment by kylekatarnls** [comment]
OK, not a problem, but if you have hours and minutes you must understand `in_array` comparing the objects will necessarily return false because `Carbon::parse('2018-11-17 12:34:56') != Carbon::parse('2018-11-17 00:00:00')` when you compare 2 Carbon objects (or even 2 DateTime objects) they are not equal if time is different. That's why business-day compare only `Carbon::parse('2018-11-17 12:34:56')->format('d/m') == 'day/month'`.
