### ISSUE TITLE
weekOfYear property does not take weekStartsAt into account

### ISSUE THREAD

**Issue by dark0fire** [briannesbitt/Carbon#1529]
Hello,

I encountered an issue with the following code:
```php
Carbon::now()->startOfWeek()->weekOfYear; //Returns 47, like it supposed to.
Carbon::setWeekStartsAt(Carbon::SUNDAY);
Carbon::setWeekEndsAt(Carbon\Carbon::SATURDAY)
Carbon::now()->startOfWeek()->weekOfYear; //Returns 46, which is odd since im still asking this week's start.
```
Carbon version: 1.35.1
PHP version: 7.1.24

I expected to get:
```
47
```

But I actually get:
```
46
```
Thanks!

**Comment by kylekatarnls** [comment]
The recommended way to do this is:
```php
echo Carbon::now()->locale('en_US')->startOfWeek()->week();
```` 
This way, you get `startOfWeek` based on first day of week in the en_US locale (Sunday) then the week number related to it.

Avoid using `setWeekStartsAt` as it will apply on every possible code and library that use Carbon in your app.

As you may find in the PHPDoc (some IDE like PHPStorm will show it if you click on `->weekOfYear`): `weekOfYear` is ISO-8601 week number of year, weeks starting on Monday. It's always based on Monday.

It's equivalent to `->format('W')` as integer value (see the PHP native `W` format http://php.net/manual/en/function.date.php)
