### ISSUE TITLE
Format Ignores Being Set to Start of Hour

### ISSUE THREAD

**Issue by ToothlessRebel** [briannesbitt/Carbon#1559]
Hello,

I encountered an issue with the following code:
```php
$c = \Carbon\Cabon::now();
$c->copy()->startOfHour()->format('g:m A T \o\n F j, Y');
```
Carbon version: 1.33.0
PHP version: 5.6.37

I expected to get:
```
"9:00 PM UTC on December 20, 2018"
```

But I actually get:
```
"9:12 PM UTC on December 20, 2018"
```

Thanks!

**Comment by kylekatarnls** [comment]
Hi, `m` is `month`, not `minutes`, use `i` for minutes:

```php
$c = \Carbon\Carbon::now();
echo $c->copy()->startOfHour()->format('g:i A T \o\n F j, Y');
```

`format` is the native date from PHP: http://php.net/manual/en/datetime.format.php

So you can refer to `date()` function for the codes:
http://php.net/manual/en/function.date.php

**Comment by ToothlessRebel** [comment]
Oh man, embarrassing.
