### ISSUE TITLE
Discrepancy in carry-over to next month when setting day

### ISSUE THREAD

**Issue by google-mac** [briannesbitt/Carbon#1563]
Hello,

I encountered an issue with the following code:
```php
Carbon::setTestNow( Carbon::create(2019, 2, 28, 0) );

echo Carbon::now()->startOfDay()->day(31);
```

In all of my other tests, if a date is specified that doesn't exist in the month, it rolls over to the FIRST DAY of the next month.

In my own code, I can account for this discrepancy by using `->startOfMonth()`, but I wanted to also list the issue here.

Carbon version: 1.35.1
PHP version: 7.2.2

I tried it in the test Heroku environment on [master](https://try-carbon.herokuapp.com/?embed&theme=xcode&border=silver&options-color=rgba(120,120,120,0.5)&input=Carbon%3A%3AsetTestNow(%20Carbon%3A%3Acreate(2019%2C%202%2C%2028%2C%200)%20)%3B%0A%0Aecho%20Carbon%3A%3Anow()-%3EstartOfDay()-%3Eday(31)%3B) and on my version.

I expected to get:
```
Carbon @1551596400 {#3460
     date: 2019-03-01 00:00:00.0 America/Phoenix (-07:00),
}
```

But I actually get:
```
Carbon @1551596400 {#3460
     date: 2019-03-03 00:00:00.0 America/Phoenix (-07:00),
}
```

Thanks!

**Comment by kylekatarnls** [comment]
Hello,

`it rolls over to the FIRST DAY of the next month` this is a miss-interpretation of what really happen. First Carbon does nothing on its own, it's the PHP behavior for DateTime overflows. When you set the day to a greater value than the maximum, an overflow to the next month is calculated:

```
31 (new value) - 30 (number of days in the month) = 1 (go to 1st on next month)
31 (new value) - 29 (number of days in the month) = 2 (go to 2nd on next month)
31 (new value) - 28 (number of days in the month) = 3 (go to 3rd on next month)
```
So it's expected to go to 1/2/3 depending on the number of days in the month. PHP itself handle it this way.

Using `startOfMonth` as you did is perfectly correct. Understand that your case is not a common expectation, we mostly expect either not to overflow or to overflow, but very rarely to overflow only 1 day. Still you can automate it in a macro:

```php
Carbon::macro('setDayMaxOverflow', function ($day, $maxOverflow = 1) {
  $this->day($day);
  if ($this->day < $day && $this->day > $maxOverflow) {
    $this->day($maxOverflow);
  }

  return $this;
});

echo Carbon::now()->startOfDay()->setDayMaxOverflow(31);
```

Note that in Carbon 2, you can prevent the overflow using:
```php
$date->setUnitNoOverflow('day', 31, 'month');
```

Feel free to ask if you have any trouble, I will re-open the issue.
