### ISSUE TITLE
subQuater problems

### ISSUE THREAD

**Issue by thomasdominic** [briannesbitt/Carbon#1565]
Hello,

I encountered an issue with the following code:
```php
echo Carbon::createFromTimeString("2018-12-31 00:00:00")->quarter; // 4
echo Carbon::createFromTimeString("2018-12-31 00:00:00")->subQuarter()->quarter; // 4
```
Carbon version: **1.36.1**
PHP version: **7.2.12**

I expected to get:
```
3 on the second line
```

But I actually get:
```
4
```

I think the method can be tested different end-of-the-month cases.

Thanks!

**Comment by kylekatarnls** [comment]
Hello,

That's a tricky one, in this case we will try to do 12 - 3 = 9, so we set the date to 2018-09-31, the 31st of september does not exist so PHP native DateTime behavior will force us to go to the next valid date: 2018-10-01, then we're on the quarter 4 again.

Here you should use the `NoOverflow` suffix that revert the overflow behavior of PHP:
```php
echo Carbon::createFromTimeString("2018-12-31 00:00:00")->subQuarterNoOverflow()->quarter;
```

**Comment by thomasdominic** [comment]
OK it's not possible on 1.36.1 and Laravel use 1.36.1

**Comment by kylekatarnls** [comment]
Laravel 5.7, not 5.8. You still can upgrade to Carbon 2 in any version of Laravel following the documentation instructions: https://carbon.nesbot.com/

You can also do manually what `subQuarterNoOverflow` do:

```php
$date = Carbon::createFromTimeString("2018-12-31 00:00:00");
$day = $date->day;
$date->subQuarter();
if ($date->day !== $day) {
  $date->subMonth()->endOfMonth();
}
```

**Comment by thomasdominic** [comment]
Nice ! Thanks you
