### ISSUE TITLE
DateTime::__construct() expects parameter 1 to be string, object given

### ISSUE THREAD

**Issue by AlexAbraham1** [briannesbitt/Carbon#157]
Does anyone else get this issue after installing with Laravel 4 and PHP 5.4?

I got the issue after running "composer update" as well as when calling Carbon::now() from a laravel module

**Comment by stanleydesigner** [comment]
Hello @AlexAbraham1, how did you resolve it, I have the same error on a site
http://dev.lenouvelliste.com/

**Comment by abhijeetkumar** [comment]
hi @AlexAbraham1 , I am totally new in laravel, Please reply on the above issue that how you resolve it. Even I am having same error while reset my password.

**Comment by God9ps** [comment]
@AlexAbraham1 how did you resolve it please?

**Comment by kylekatarnls** [comment]
@God9ps You may have a different problem. It's 4 years old and Carbon changed a lot. Please give your code (the way you create your Carbon instance), the error stack trace and the exact message of your error.

**Comment by God9ps** [comment]
@kylekatarnls the error that return is:

Type error: DateTime::__construct() expects parameter 1 to be string, object given

and my code is a simple:

public function create()
    {

        //create a new event
        $event = new Event;

        $event->name = 'Test';
        $event->startDateTime = Carbon::now();
        $event->endDateTime = Carbon::now()->addDay();
        $event->addAttendee(['email' => 'test@gmail.com']);
        $event->addAttendee(['email' => 'test1@gmail.com']);

        return $event->save();
    }

The Event Object is from Google Calendar API.

Thank you

**Comment by kylekatarnls** [comment]
I also need the complete stack trace. And if the but prevent the upgrade, we need to now the version you currently use.

**Comment by God9ps** [comment]
I'm using the 5.6 Laravel version and 1.25 Carbon Version.

**Comment by God9ps** [comment]
I think that is a problem in the composer update action, but I'd tryied make all the proccess since the beggining and the problem continues...

**Comment by kylekatarnls** [comment]
The discover command of Laravel call Carbon::now(), so if something is broken between Carbon and DateTime, it's logical than the discover script fail. You can update with: `composer update --no-scripts` to test with no scripts.

Else, what can possibly break the line 439 of Carbon 1.25 is your macros and custom formats, did you override/macro the `format()` method?

**Comment by God9ps** [comment]
composer update --no-scripts

I try test with no script and the error stills...

did you override/macro the format() method?

No I did not, but before the composer update my code was working with the current fomat() method, after the composer update was when the problem was comming.

I've tried a lot of suggestion and anyones solve this problem. grrrrrrrrrrr

**Comment by kylekatarnls** [comment]
As I have my Laravel 5.6 project still working with Carbon 1.25.0, I will need you to do some debug:

First, let see what is this object given, add 3 lines in Carbon.php line 439 just before `parent::__construct($time, $timezone);`:
```php
var_dump($time);
echo (new \Exception())->getTraceAsString();
exit;
```
To see what contains `$time`, call again your code with `Carbon::now()`, then give the output here.

If the stack trace mention other files than Carbon.php, please copy-paste matching code extracts from files of the stack.

Second, create a `format` method in Carbon.php to mock the DateTime's one:
```php
public function format($string)
{
    exit('here');
    return parent::format($string);
}
```
Re-run the code, if "here" does not appear, then it means a macro or a override is running (can be any of your third-party dependencies), if it appears, try to remove `exit('here');` and see if you still have the error.
