### ISSUE TITLE
Problem with month translation

### ISSUE THREAD

**Issue by kossa** [briannesbitt/Carbon#1576]
Hello,

I'm using Carbon on Laravel, version 1.34.0, I have a problem to get month/day in French.
```
Carbon::setLocale('fr');
dd(Carbon::yesterday()->diffForHumans()); // "il y a 1 jour"
```

```
Carbon::setLocale('fr');
dd(Carbon::yesterday()->format('F l')); // "January Thursday"
```

**Comment by kylekatarnls** [comment]
Please check https://carbon.nesbot.com/docs/#api-localization (there is a link to toggle version 1 internationalization documentation).

Please also note some points:
`format` is the native method of `DateTime` so no translation support for this method. You can use `formatLocalized` instead in Carbon 1 but you will need to rely on the installed packages on your machine: http://php.net/manual/fr/function.setlocale.php

With Carbon 2, you will be able to get translated every output of `calendar`, `isoFormat` etc. with no additional install and you will get every examples of the documentation working.

Migrating from Carbon 1 to Carbon 2 is smooth: https://carbon.nesbot.com/docs/#api-carbon-2 and for many third-party constraint such as Laravel < 5.8, you can use the composer alias method to get Carbon 2 as explained here: https://carbon.nesbot.com/

**Comment by kossa** [comment]
Thank you for help :)
