### ISSUE TITLE
carbon add month failed

### ISSUE THREAD

**Issue by Movahed-IRI** [briannesbitt/Carbon#1579]
Hello,

I encountered an issue with the following code:
```php
            $carbon_ = Carbon::now();
            $carbon_->year = $toGregorian[0];
            $carbon_->month = $toGregorian[1];
            $carbon_->day = $toGregorian[2];
```
Carbon version: **1.36.1**
PHP version: **7.1**

$toGregorian[1] value is 2
I expected to get:
```
2019/02/01 
```

But I actually get:
```
2019/03/01 
```

```php
            $carbon_ = Carbon::create($toGregorian[0] , $toGregorian[1] , $toGregorian[2] , $persian_time_array[0] , $persian_time_array[1] , 0 , 'Asia/Tehran');

```

carbon::create() do as i suppose

Thanks!

**Comment by kylekatarnls** [comment]
`$carbon_ = Carbon::now();` will set the day to 29, so when you set month to 2 you get an invalid date and it overflow to the next valid day.

The real question here is why using `Carbon::now()` if you change the whole date?

**Comment by kylekatarnls** [comment]
Note that, by changing individually each unit, you generate 3 changes and validations. Even using `Carbon::now()`, you should set the date at once:

```php
$date = Carbon::now()->setDate($year, $month, $day);
```

And if you have a string like `"2016-04-29"` you simply can use modify:

```php
$date = Carbon::now()->modify($string);
```

I close this issue. If I misunderstood the problem, let me know and I'll re-open.
