### ISSUE TITLE
Whenever I add hours that pass to the next day, the date stays the same

### ISSUE THREAD

**Issue by LCD344** [briannesbitt/Carbon#1587]
Hello,

I encountered an issue with the following code:
```php
$startOfDay = Carbon::now();
$startOfDayClone = $startOfDay->clone();
$startOfDay->addHour(25);
dd($startOfDay->diffAsCarbonInterval($startOfDayClone)->format('%H:%I'));
```
Carbon version: **PUT HERE YOUR COMPOSER CARBON VERSION**
PHP version: 7.31

since I added 25 hours I expect to have 25 hours difference. but apparently the day doesn't update, which means I will need to do this manually. Is there a way to by pass it?

I expect to get
```
25:00
```

But I actually get:
```
01:00
```
Thanks!

**Comment by kylekatarnls** [comment]
Hi,

You added 25 hours to a date (not to the interval that do not yet exist). And a date will always be valid (it will not have more than 23 hours, it overflow to the next day.

Your interval contains 1 day + 1 hour. Use `diffInHours` instead.
```php
$startOfDay = Carbon::now();
$startOfDayClone = $startOfDay->clone();
$startOfDay->addHour(25);
dd($startOfDay->diffInHours($startOfDayClone));
```

Thanks.

**Comment by LCD344** [comment]
Thanks for the explanation
