### ISSUE TITLE
lessThan fail when It are Equals

### ISSUE THREAD

**Issue by millan2993** [briannesbitt/Carbon#1594]
Hello,

I encountered an issue with the following code:
```php
$date_start = Carbon::now();  // lógica diferente
$today = Carbon::now();
if ($date_start->lessThan($today)) {
    // validation fail
}
```
Carbon version: **^1.24.1**
PHP version: **7.2**

I expected that it does not into in the validation, but  does it.

Thanks!

**Comment by kylekatarnls** [comment]
I need your exact version for this case, ^1.24.1 can be any version from 1.24.1 to 1.36.2. Use `composer update` to be sure to get the latest version 1, then `composer show` to check your version (other dependencies can lock it.)

Then lessThan in 1.36.2 is a simple alias for:
```php
if ($date_start < $today) {
```

So you need to check if you dates are really different.
