### ISSUE TITLE
Carbon now() producing different results from create() 

### ISSUE THREAD

**Issue by rayblair06** [briannesbitt/Carbon#1596]
Hello,

I encountered an issue with the following code:
```php
    $date = [
        // Day
        "29",
        // Month
        "03",
        // Year
        "2019"
    ];

    $wrong = Carbon::now()
        ->day($date[0])
        ->month($date[1])
        ->year($date[2])
        ->hour(0)
        ->minute(0)
        ->second(0);

    $right = Carbon::create(
        $date[2],
        $date[1],
        $date[0],
        0,
        0,
        0
    );

    dd($wrong, $right);
    
    // $wrong produces
    // date: 2019-03-01 00:00:00.0 UTC (+00:00)

    // $right produces
    // date: 2019-03-29 00:00:00.0 UTC (+00:00)
```
Carbon version: * 1.22.1
PHP version: PHP 7.2.3

I expected to get:
```
date: 2019-03-29 00:00:00.0 UTC (+00:00)
```

But I actually get:
```
date: 2019-03-01 00:00:00.0 UTC (+00:00)
```

Thanks!

**Comment by rayblair06** [comment]
After some thought, I'm assuming this is because I'm setting the day before the month based off the current date. Thus 29th doesn't exist within Feb, before I'm setting it as March.

Closed as it was my mistake.

**Comment by kylekatarnls** [comment]
Hello,

Event with the right order (bigger to smaller), the first method is a bad idea, You call 7 methods and change 6 times the date object to get a date completely different from the one you created initially (now). There is nothing related to "now" here, so don't call `now()` it's misleading for next developers (including you) that will have to maintain this code.

Simply use `Carbon::create()` or `Carbon::parse()` to create directly the date you need in one call, it's far more optimized.

It's a general rule, reduce data alteration, calls, prefer dedicated methods over combining methods, you'll get a code easier to maintain and less bug risks.

Have a nice day,

**Comment by rayblair06** [comment]
Thank you for the information, I was actually the next developer working on this :) Having it explained I can clearly see the issue, what you said is correct and I'll make sure not to make the same mistake as my predecessor in the future.

Thanks.
