### ISSUE TITLE
The Live Editor is down

### ISSUE THREAD

**Issue by thegrumpyscot** [briannesbitt/Carbon#1597]
The documentation - while brilliant; seems to be broken. Specifically the Live Editor features. Seems to have been hacked? Opening any of the live editor examples in a fresh window simply displays "Localheartz ~ IndoXploit" .

Since this falls outside of the usual bug report, I've chosen not to follow the default issue template, however I've verified with a number of people using different browsers.

**Comment by kylekatarnls** [comment]
Thanks. It's now blocked with strict no-write CHMOD on every file. So the sandbox in no longer "shared" between users.
