### ISSUE TITLE
[Translation tool] pt_BR

### ISSUE THREAD

**Issue by victortobias** [briannesbitt/Carbon#1600]
|English|pt_BR|comments|
|--|--|--|
|a few seconds|segundos|alguns segundos|
|January|janeiro|Janeiro|
|Jan|jan|Jan|
|February|fevereiro|Fevereiro|
|Feb|fev|Fev|
|March|março|Março|
|Mar|mar|Mar|
|April|abril|Abril|
|Apr|abr|Abr|
|May|maio|Maio|
|May|mai|Mai|
|June|junho|Junho|
|Jun|jun|Jun|
|July|julho|Julho|
|Jul|jul|Jul|
|August|agosto|Agosto|
|Aug|ago|Ago|
|September|setembro|Setembro|
|Sep|set|Set|
|October|outubro|Outubro|
|Oct|out|Out|
|November|novembro|Novembro|
|Nov|nov|Nov|
|December|dezembro|Dezembro|
|Dec|dez|Dez|

## Additional fixes
Some corrections I made were only lowercase

**Comment by kylekatarnls** [comment]
`alguns segundos` checked ✅ 
Uppercase: deeper checking needed, contradictory sources found:
- moment.js: uppercase ✅ 
- glibc: lowercase ⛔️ 
- rails-i18n ✅

**Comment by kylekatarnls** [comment]
lower/upper case for months/days is a tricky point.

Example:
`See you Monday` Monday is always uppercase, it belongs to a group of words that are exceptions in English, so it's uppercase in our file.
`Rendez-vous lundi` the same sentence in French requires lowercase and is wrong with uppercase. So it's lowercase in our file.
`Bis Montag`, in German, every noun is uppercase, no hesitation at all, uppercase everywhere.
`Do zobaczenia w poniedziałek` (and same for months as it seems: `Do zobaczenia w marcu`)

So the right thing to do would be to keep the lowercase, then when you need to put this at the beginning of a sentence, you can use `ucfirst()`

I plan to fix `alguns segundos` and keep lowercases. If you have other arguments, please add them.
