### ISSUE TITLE
[Translation tool] uk_UA

### ISSUE THREAD

**Issue by alecrabbit** [briannesbitt/Carbon#1602]
|English|uk_UA|comments|
|--|--|--|
|Apr|квіт|кві|
|May|трав|тра|
|Jun|черв|чер|
|Aug|серп|сер|
|Oct|жовт|жов|
|Nov|лист|лис|
|Dec|груд|гру|

**Comment by kylekatarnls** [comment]
Confirmed with glibc abbreviated months.
