### ISSUE TITLE
[Translation tool] fr_FR

### ISSUE THREAD

**Issue by Fastfuel** [briannesbitt/Carbon#1604]
|English|fr_FR|comments|
|--|--|--|
|2s|2 sec.|It should be "2 s", as s, without the quotes and the dot is [the official symbol for second, as time unit](https://fr.wikipedia.org/wiki/Seconde_(temps)), and ["sec." is erroneous in french](https://fr.wikipedia.org/wiki/Seconde_(temps)#Notations_erronées). ([A more official reference, page 20](https://www.legifrance.gouv.fr/content/download/10387/120534/version/3/file/Charte_typographique_jo_septembre_2016.pdf))|

**Comment by kylekatarnls** [comment]
I'm French myself and saw "sec." very often. In Carbon, it's needed to have a clear disambiguation with "semaine" (week).

In the given PDF, "semaine" does not appear, this make things a lot easier.

**Comment by kylekatarnls** [comment]
We have to find a consistent way to represent all units (year, month, week, day, hour, minute, second) that all can appears in the same interval sentences. But I agree we should be as close as possible from scientist notation.

**Comment by kylekatarnls** [comment]
Crossing different sources, I will keep `sem.` as the only exception, `an(s)` (year) is short enough so not abbreviated, `mois` (month) too. Then `j`, `h`, `min` and `s` will be clear and correct for scientist usage too.

**Comment by Fastfuel** [comment]
Bonjour Kyle,
Merci pour ces explications très claires. Je comprends parfaitement le souci d'ambiguïté. Tu as surement passé plus de temps que moi sur ces problématiques de nomage, abréviation et traduction !
Merci également pour tes contributions sur Carbon, sur l'excellente API qu'est Carbon !
