### ISSUE TITLE
[Translation tool] fa

### ISSUE THREAD

**Issue by cmsnegar** [briannesbitt/Carbon#1605]
|English|fa|comments|
|--|--|--|
|January|ژانویه|دی|
|Jan|ژانویه|دی|
|February|فوریه|بهمن|
|Feb|فوریه|بهمن|
|March|مارس|اسفند|
|Mar|مارس|اسفند|
|April|آوریل|فروردین|
|Apr|آوریل|فروردین|
|May|مه|اردیبهشت|
|May|مه|اردیبهشت|
|June|ژوئن|خرداد|
|Jun|ژوئن|خرداد|
|July|ژوئیه|مرداد|
|Jul|ژوئیه|مرداد|
|August|اوت|تیر|
|Aug|اوت|تیر|
|September|سپتامبر|شهریور|
|Sep|سپتامبر|شهریور|
|October|اکتبر|مهر|
|Oct|اکتبر|مهر|
|November|نوامبر|آبان|
|Nov|نوامبر|آبان|
|December|دسامبر|آذر|
|Dec|دسامبر|آذر|

**Comment by kylekatarnls** [comment]
Hello @cmsnegar, thanks a lot. By trying those translations in Google Translate, both `ژانویه` and `دی` give `January` from Persian to English, then the reverse translation of `January` gives `ژانویه` (and I found the same `ژانویه` in glibc).

Could you please explain to me (as a non Persian-speaker) what is the difference between both. If it depends on the context, we should probably provide both with different formats/methods.

**Comment by kylekatarnls** [comment]
It seems those are the Solar Hijri calendar months if I well understand. Sadly PHP does not support it as far as I know (http://php.net/manual/en/book.calendar.php) and our library relies on the native PHP `DateTime` class which only supports Gregorian calendar.

We do not plan to support other calendars, it's a lot of work and probably some other libraries dedicated to them could better suit that need. If I mistaken, please tell me and provide some details and I will re-open.
