### ISSUE TITLE
Need help checking if a date belongs to the current/present week or month

### ISSUE THREAD

**Issue by collizo4sky** [briannesbitt/Carbon#1608]
I am already using the code below to check if a given mysql datetime is of the current/present day

```
Carbon::createFromFormat('Y-m-d H:i:s', '2019-02-23 18:17:19', $timezone)->isToday()
```

I also want to check if the mysql datetime is of the current week and of the current month.

Really don't know how to pull this off. 

Would be grateful if anyone will help. Happy to send a tip your way.

**Comment by collizo4sky** [comment]
Figured it.

**Comment by kylekatarnls** [comment]
Hi @collizo4sky.

Documented in [Comparison section of the documentation](https://carbon.nesbot.com/docs/#api-comparison):

```php
// isCurrentDay:
Carbon::createFromFormat('Y-m-d H:i:s', '2019-02-23 18:17:19', $timezone)->isCurrentDay();
// equivalent as ->isSameAs('Y-m-d', Carbon::now());

// isCurrentWeek (available since 2.0)
Carbon::createFromFormat('Y-m-d H:i:s', '2019-02-23 18:17:19', $timezone)->isCurrentWeek();
// equivalent as ->isSameAs('o-w', Carbon::now());
// For Carbon < 2.0:
Carbon::createFromFormat('Y-m-d H:i:s', '2019-02-23 18:17:19', $timezone)->isSameAs('o-w', Carbon::now());

// isCurrentMonth
Carbon::createFromFormat('Y-m-d H:i:s', '2019-02-23 18:17:19', $timezone)->isCurrentMonth();
// equivalent as ->isSameAs('Y-m', Carbon::now());
```

`isSameAs` will compare using `format` with the given format and compare the output strings, so you can use it with any custom unit.

Tips are welcome on https://opencollective.com/carbon

Thanks,

Let me know if you have any trouble and I'll re-open this issue.

**Comment by collizo4sky** [comment]
I donated $5. Thanks @kylekatarnls

**Comment by kylekatarnls** [comment]
Awesome, thanks. You motivated me to finish the OpenCollective integration. Your name will appear very soon on the README.

**Comment by collizo4sky** [comment]
Hi @kylekatarnls doesn't work currectly. Eg

`var_dump(Carbon::createFromFormat('Y-m-d H:i:s', '2019-02-27 18:17:19')->isSameAs('o-w', Carbon::now()));` returns false

And 27th is this week.

**Comment by collizo4sky** [comment]
Also, any difference between `$dt->isCurrentDay();` and `$dt->isToday();`

**Comment by kylekatarnls** [comment]
So sorry, it's `W` uppercase (week of year) `->isSameAs('o-w', Carbon::now())`, lower `w` is the day of week.

**Comment by kylekatarnls** [comment]
And indeed their should be no difference between `isToday` and `isCurrentDay`, isToday is an a specific method, while isCurrentXyz() is a generic method where `Xyz` can be any unit.

**Comment by collizo4sky** [comment]
Worked. Thanks.

**Comment by kylekatarnls** [comment]
I guess you use `->isSameAs` instead of `isCurrentWeek` because you use Carbon 1. May I ask why not to upgrade to Carbon 2?

**Comment by collizo4sky** [comment]
I am the owner of a commercial WordPress plugin (https://mailoptin.io) and as per WordPress requirement, they support PHP 5.4 and higher and most of our users are not on PHP 7.

I am guessing 2.x is PHP > 7 only right?

**Comment by kylekatarnls** [comment]
Yes, even PHP 7.1. But it seems last version of Wordpress requires an even higher version 7.3: https://wordpress.org/about/requirements/ so I guess it will be soon safe to drop PHP 5 and enter the wonderful world of the Seven :D

**Comment by collizo4sky** [comment]
Yes. Before then, sticking to 1.x
