### ISSUE TITLE
Error when parse format using Y:m:d H:i:s.v

### ISSUE THREAD

**Issue by vasymus** [briannesbitt/Carbon#1615]
Hello,

I encountered an issue with the following code:
```php
$format = "Y:m:d H:i:s.v";
$str = Carbon::now()->format($format);
var_dump(Carbon::createFromFormat($format, $str));
```
Carbon version: **~1.35.1**
PHP version: **7.2.4**

I expected to get:
```
object(Carbon\Carbon)#831 (3) { ["date"]=> string(26) "2019-02-26 08:27:16.709863" ["timezone_type"]=> int(3) ["timezone"]=> string(15) "Europe/Helsinki" }
```

But I actually get:
```
// error
// The format separator does not match\n
// Trailing data
```

Thanks!

**Comment by kylekatarnls** [comment]
I can't reproduce the error neither on my locale machine nor in our sandbox: https://try-carbon.herokuapp.com/

You may have a `setlocale(LC_NUMERIC, 'xx');` where xx is a locale using coma as decimal separator (French for example). It could also be `LC_ALL` instead of `LC_NUMERIC`.

You can try this:
```php
if (strpos((string) .1, '.') === false) {
    $locale = setlocale(LC_NUMERIC, '0');
    setlocale(LC_NUMERIC, 'C');
}
$format = "Y:m:d H:i:s.v";
$str = Carbon::now()->format($format);
var_dump(Carbon::createFromFormat($format, $str));
if (isset($locale)) {
    setlocale(LC_NUMERIC, $locale);
}
```

It's the work-around we use for `new Carbon()` constructor. Maybe we should extend this work-around to `createFromFormat`.

**Comment by kylekatarnls** [comment]
Hello,

Can you inspect what `$str` contains.

Quick note about your expectation: you will not get microseconds `709863`, you can only have `709000` as `.v` is only milliseconds.

Could you try to reproduce your bug in our sandbox: https://try-carbon.herokuapp.com/

I can't reproduce your bug, your code chunk works well without context.

Thanks.

**Comment by vasymus** [comment]
Hm, strange, no error in your sandbox

actually, i was using Laravel when i encountered in this error

http://i.imgur.com/6PzuGXU.png

http://i.imgur.com/WG18Idl.png

**Comment by kylekatarnls** [comment]
Note than Laravel extends Carbon and add some specific formatting in some versions, so it might be a Laravel issue. What is your Laravel version?

The exact same input is OK in the sandbox, so it's not specific to your data: `var_dump(Carbon::createFromFormat("Y:m:d H:i:s.v", "2019:02:26 10:40:19.636"));`

Can you also provide:
```php
var_dump(setlocale(LC_ALL, '0'), setlocale(LC_NUMERIC, '0'), php_uname());
```

**Comment by vasymus** [comment]
Sure:

Laravel version is 5.7.13

as for provided data:
Linux 4c7ca4a7d18c 4.15.0-45-generic #48-Ubuntu SMP Tue Jan 29 16:28:13 UTC 2019 x86_64

http://i.imgur.com/urNzoKL.png

Should i go to Laravel github repo and place an issue there ?

**Comment by kylekatarnls** [comment]
Not needed, it's a PHP bug, it has been fixed in PHP 7.3 (that's why it succeed on my machine and on the sandbox): https://3v4l.org/h35T7

I will see if we can work around it.

**Comment by kylekatarnls** [comment]
It seems port to PHP 7.2 is not planned: https://bugs.php.net/bug.php?id=75577

**Comment by kylekatarnls** [comment]
Quick fix:

```php
var_dump(Carbon::createFromFormat(str_replace('.v', '.u', $format), $str));
```

**Comment by kylekatarnls** [comment]
Laravel took this path too: https://github.com/laravel/framework/blob/v5.7.27/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php#L797

It's pretty fine in most situation. The inconvenient is if you want some number just after `v`: `s.vi` very not common, but this would be broken by the .v -> .u replacement.

**Comment by vasymus** [comment]
Thank you very much!

**Comment by kylekatarnls** [comment]
The replacement will be automatic in the next version (unless using PHP 7.3+):
https://github.com/briannesbitt/Carbon/pull/1619

And I will try to get the same behavior on Laravel:
https://github.com/laravel/framework/pull/27672
