### ISSUE TITLE
[Translation tool] nl

### ISSUE THREAD

**Issue by proclame** [briannesbitt/Carbon#1620]
|English|nl|comments|
|--|--|--|
|a year|één jaar|This should rather be een jaar because één means explicitly one instead of a|
|a month|één maand|This should rather be een maand because één means explicitly one instead of a|
|a week|één week|This should rather be een week because één means explicitly one instead of a|
|a day|één dag|This should rather be een dag because één means explicitly one instead of a|
|an hour|één uur|This should rather be een uur because één means explicitly one instead of a|
|a minute|één minuut|This should rather be een minuut because één means explicitly one instead of a|

**Comment by kylekatarnls** [comment]
The "aUnit" is supposed to get the most fluent representation of interval in sentences. In the following example: "Bob is away for a week", in this case, can you confirm `een week` is more common than `één week`?

**Comment by proclame** [comment]
Confirmed.

`één week` would only be used when you want to say "Bob is away for one week"

**Comment by RikSomers** [comment]
Can confirm indeed.

**Comment by kylekatarnls** [comment]
Fixed in the next release.
