### ISSUE TITLE
[Translation tool] nl_NL

### ISSUE THREAD

**Issue by GilHoe** [briannesbitt/Carbon#1622]
Hello,

I encountered an issue with the following code:
```php
echo Carbon::parse('2018-06-01')->subDay()->month;
```
Carbon version: **PUT HERE YOUR COMPOSER CARBON VERSION**
PHP version: **PUT HERE YOUR PHP VERSION**

I expected to get:
```
6
```

But I actually get:
```
5
```

Thanks!

**Comment by kylekatarnls** [comment]
Hello @GilHoe, I don't know why it happened, but the table summary that should contain the fixes has been replaced by the default issue template.

Could you retry please and if you get `PUT HERE YOUR COMPOSER CARBON VERSION` in the issue contents after clicked the `Submit` button, please copy the URL in your address bar and paste it after the content, so I will try to figure out why it failed, it's the first time it happens.
