### ISSUE TITLE
[Translation tool] ru_RU

### ISSUE THREAD

**Issue by andrey-helldar** [briannesbitt/Carbon#1624]
|English|ru_RU|comments|
|--|--|--|
|2yrs|2 г|"года" ("2 g" reads like "2 grams")|
|a year|1 год|"год" (The number does not need to specify)|
|2mos|2 м|"2 m" is "2 meters". Correctly is "2 мес"|
|a month|1 месяц|"месяц" (The number does not need to specify)|
|2w|2 н|"2 н" - generally unclear what the value. Correctly is "2 нед"|
|a week|1 неделю|"неделю" (The number does not need to specify)|
|2d|2 д|"2 д" reads like "2D, 3D, 4D ... cinema". Correctly is "2 дня"|
|a day|1 день|"день" (The number does not need to specify)|
|an hour|1 час|"час" (The number does not need to specify)|
|a minute|1 минуту|"минуту" (The number does not need to specify)|
|2s|2 с|"2 с" is correct, but "2 сек" is better.|
|a few seconds|1 секунду|"секунду" (The number does not need to specify)|

**Comment by kylekatarnls** [comment]
Thanks, will be changed for the next release.

**Comment by kylekatarnls** [comment]
Will be in the next release.
