### ISSUE TITLE
Add and sub Minutes does not work with UTC

### ISSUE THREAD

**Issue by marcoapferegrino** [briannesbitt/Carbon#1626]
Hello,

Carbon version: **1.36.2**
PHP version: **7.2**

I encountered an issue with the following code:

I actually make a explode for **2019-02-24T01:03** thinking the **T** letter was causing an issue, but not. 
The problem, I guess is when I create a Date is by default in **UTC** but it seems it ignores de functions `add and sub Minutes`. 

```php
   $dateUTC = Carbon::create((int)$date[0], (int)$date[1], (int)$date[2],(int)$time[0],(int)$time[1],0); //2019-02-24 01:03:00.000000 in UTC

    $fromTime = $dateUTC->subMinutes(25); //2019-02-24 01:03:00.000000 in UTC
    $toTime = $dateUTC->addMinutes(25); //2019-02-24 01:03:00.000000 in UTC

```

I expected the subs and adds minutes. Actually, this happens event If doing `Carbon::now()` because the `now` creates a date in UTC

Example expected : 

fromTime = `2019-02-24 01:02:35.000000 in UTC`
toTime = `2019-02-24 01:03:25.000000 in UTC`

Thanks in advance!!

**Comment by kylekatarnls** [comment]
Hello,

Your trouble is about mutability. Dates in `Carbon` are mutable as is the `DateTime` class from PHP it extends. It means `$dateUTC` will change when you add/sub things, so if you add then sub the same interval, you get the initial date. And here, `$fromTime` and `$toTime` are just references of the same object.

You need to copy the date to create a new date and you don't needs to explode your date, just use `parse`:

```php
$dateUTC = Carbon::parse('2019-02-24T01:03');

$fromTime = $dateUTC->copy()->subMinutes(25);

$toTime = $dateUTC->copy()->addMinutes(25);

echo "$fromTime\n";
echo "$toTime\n";
```

```
2019-02-24 00:38:00
2019-02-24 01:28:00
```

As you use PHP 7.2, you could safely upgrade to Carbon 2 and simply use `CarbonImmutable` (extension of `DateTimeImmutable` that create an new object for each change):
```php
$dateUTC = CarbonImmutable::parse('2019-02-24T01:03');

$fromTime = $dateUTC->subMinutes(25);

$toTime = $dateUTC->addMinutes(25);

echo "$fromTime\n";
echo "$toTime\n";
```

Same output.

Thanks,
