### ISSUE TITLE
[Translation tool] he_IL

### ISSUE THREAD

**Issue by GabMic** [briannesbitt/Carbon#1628]
|English|he_IL|comments|
|--|--|--|
|2 hours from now|בעוד שעתיים|בעוד שעתיים מעכשיו|

**Comment by kylekatarnls** [comment]
Hello @GabMic, thanks for your help. Can the Arabic digits (meaning `0123456789`) be used in dates and duration like this. Would it be something clear and correct enough in Hebrew?

Else we would need an alternative digits complete list (such as https://en.wikipedia.org/wiki/Hebrew_numerals) and we would also need to handle a new logic for the gender.

**Comment by kylekatarnls** [comment]
Hello @GabMic thanks for your help, will be fixed in the next release.
