### ISSUE TITLE
[Translation tool] ar

### ISSUE THREAD

**Issue by atefBB** [briannesbitt/Carbon#1629]
|English|ar|comments|
|--|--|--|
|Monday|الإثنين|الاثنين|
|Mon|إثنين|اثنين|

## Additional fixes
fix typo
This word in arabic is from the origin `اثنين` (`two`) with a `Hamza waslia` (همزة وصل) not a `Hamza Khatiia` (همزة قطع).

**Comment by kylekatarnls** [comment]
Both soruces above gave the `الإثنين` variant:
https://translate.google.com/#view=home&op=translate&sl=en&tl=ar&text=Monday
https://en.wiktionary.org/wiki/%D9%8A%D9%88%D9%85_%D8%A7%D9%84%D8%A7%D8%AB%D9%86%D9%8A%D9%86
Can you provide some sources?
Does it depends on the region/country?

**Comment by atefBB** [comment]
Thank you. it doesn't depends on country or region. Actually same native speakers use the wrong one too. So it should returned to it origin to distinguish between the right and wrong.

**Comment by kylekatarnls** [comment]
https://glosbe.com/en/ar/monday show `الاثنين` but it also show a third variant: `الأثنين`

For my knowledge @atefBB is `الأثنين` wrong too?

**Comment by atefBB** [comment]
`الإثنين` or `الأثنين` are wrongs spelling of the word !

**Comment by kylekatarnls** [comment]
Fixed in next version.

**Comment by atefBB** [comment]
Thx
