### ISSUE TITLE
Deprecation Notice

### ISSUE THREAD

**Issue by MattHadfield113** [briannesbitt/Carbon#1631]
Hello,

I encountered an issue with the following code:
```php
echo \Carbon\Carbon::parse('12 Hours from now')->diffInHours()
```
Carbon version: 2.14.0
PHP version: 7.3
Symfony/Translation Version: 4.2.3

I expected to get:
```
12
```

But I actually get:
```
Error: [16384] The "Symfony\Component\Translation\Translator::transChoice()" method is deprecated since Symfony 4.2, use the trans() one instead with a "%count%" parameter.
```

I have read the existing issue at https://github.com/briannesbitt/Carbon/issues/1548

The issue only appeared this morning, ive been using the library fine until i ran a composer update. This project is in core PHP, using composer to install the library.

Thanks!

**Comment by kylekatarnls** [comment]
The conclusion of #1548 is that deprecation notice should not throw an exception. You have to check your app/framework settings to set a proper error reporting level. And check if no dependencies override or ignore those settings.
