### ISSUE TITLE
[Translation tool] vi_VN

### ISSUE THREAD

**Issue by haivh-nws** [briannesbitt/Carbon#1632]
|English|vi_VN|comments|
|--|--|--|
|2yrs|2 nă.|2 năm|
|2mos|2 th.|2 tháng|
|2w|2 tu.|2 tuần|
|2d|2 ng.| 2 ngày|
|2m|2 p.|2ph|

**Comment by haivh-nws** [comment]
In Vietnamese, we usually do not shorten word.

**Comment by kylekatarnls** [comment]
So `phút` is the only unit we can shorten to `ph`? Or should we better keep `phút` for consistency.

For example the following can appears: `2h 34m 45s` (meaning 2 hours, 34 minutes and 45 seconds).

Could you please give me the most appropriate way to represent in a short (but comprehensive) way such a time interval?
