### ISSUE TITLE
[Translation tool] vi

### ISSUE THREAD

**Issue by tranghaviet** [briannesbitt/Carbon#1634]
|English|vi|comments|
|--|--|--|
|2m|2 p.|Nên là "2p" vì từ từ này hay được viết như vậy|

**Comment by kylekatarnls** [comment]
@haivh-nw suggested "2ph": #1632

For next released I planned to use "2 phút" for consistency with other units.

Would you say #1632 is correct? Usage of shorten words is not used except for phút?

**Comment by tranghaviet** [comment]
@haivh-nw was right, except for "minute" vietnamese don't use shorten words for time like "2 ng" for "2d", "2 tu"  for  "2w"...
So for consistency I suggest to *not* use shorten words for vietnamese :).
Some refs:
1. https://vi.wikipedia.org/wiki/Ng%C3%A0y
2. https://vi.wikipedia.org/wiki/Gi%E1%BB%9D
3. https://vi.wikipedia.org/wiki/Ph%C3%BAt
4. https://vi.wikipedia.org/wiki/Gi%C3%A2y

**Comment by kylekatarnls** [comment]
Thanks! So changes for the next release will match:
https://github.com/briannesbitt/Carbon/commit/946d55c57c29ed1de8c6040c9d70b4f71ef6b1c1#diff-af09a78e65588535a64cb68523641755
