### ISSUE TITLE
[Translation tool] pt_BR

### ISSUE THREAD

**Issue by rafael-affonsor** [briannesbitt/Carbon#1635]
|English|pt_BR|comments|
|--|--|--|
|2 hours before|2 horas atrás|2 horas antes, because i think "2 horas atrás" should be the same of "2 hours ago"|
|2 hours after|após 2 horas|2 horas depois. To keep the context|

**Comment by kylekatarnls** [comment]
Seems right, pt uses "ante"s, so I guess it's a mistake of the pt_BR override.

before is for an interval before a date that is not now.

**Comment by kylekatarnls** [comment]
Fixed in next release

**Comment by rafael-affonsor** [comment]
Thank you, Kyle.
