### ISSUE TITLE
[Translation tool] de_DE

### ISSUE THREAD

**Issue by Karag2006** [briannesbitt/Carbon#1636]
|English|de_DE|comments|
|--|--|--|
|a few seconds|eine Sekunde|This should rather be "ein paar Sekunden" , becasue "eine Sekunde" would mean "one second" and not "a few seconds".|

**Comment by kylekatarnls** [comment]
Thanks,

Indeed, we have different translations coming from different sources. "a few seconds" is originally a moment.js feature that converts "1 second", it's relevant only for interval with only 1 part when you know it can be approximately of use as a difference from now.

But I will change it for consistency between languages and will explain this in the documentation.
