### ISSUE TITLE
[Translation tool] ru_RU

### ISSUE THREAD

**Issue by psxx** [briannesbitt/Carbon#1638]
|English|ru_RU|comments|
|--|--|--|
|2yrs|2 г|This should rather be "2 г." because it is how we shorten words|
|a year|1 год|This should rather be "год" without "1" because what are you trying to say in english by "a year" is directly translates to Russian as a "год" without quantity.|
|2mos|2 м|This should rather be "2 мес." because it is how we shorten words|
|a month|1 месяц|This should rather be "месяц" without "1" because what are you trying to say in english by "a month" is directly translates to Russian as a "месяц" without quantity.|
|2w|2 н|This should rather be "2 нед." because it is how we shorten words|
|a week|1 неделю|This should rather be "неделя" without "1" because what are you trying to say in english by "a week" is directly translates to Russian as a "неделя" without quantity.|
|2d|2 д|This should rather be "2 д." because it is how we shorten words|
|a day|1 день|This should rather be "день" without "1" because what are you trying to say in english by "a day" is directly translates to Russian as a "день" without quantity.|
|an hour|1 час|This should rather be "час" without "1" because what are you trying to say in english by "an hour" is directly translates to Russian as a "час" without quantity.|
|2m|2 мин|This should rather be "2 мин." because it is how we shorten words|
|a minute|1 минуту|This should rather be "минуту" without "1" because what are you trying to say in english by "a minute" is directly translates to Russian as a "минуту" without quantity.|
|2s|2 с|This should rather be "2 сек." because it is how we shorten words|
|1 second|1 секунду|This should rather be "1 секунда" because what are you trying to say in english by "1 second" is directly translates to Russian as a "1 секунда". "1 секунду" means slightly different thing.|
|a few seconds|1 секунду|This should rather be "несколько секунд" without "1" because what are you trying to say in english by "a few seconds" is directly translates to Russian as a "несколько секунд". "1 секунду" is simply wrong and it means other thing.|
|Monday|понедельник|Понедельник|
|Mon|Пн|Пнд|
|Mo|Пн|Пн|
|Tuesday|вторник|Вторник|
|Tue|Вт|Втр|
|Tu|Вт|Вт|
|Wednesday|среда|Среда|
|Wed|Ср|Срд|
|We|Ср|Ср|
|Thursday|четверг|Четверг|
|Thu|Чт|Чтв|
|Th|Чт|Чт|
|Friday|пятница|Пятница|
|Fri|Пт|Птн|
|Fr|Пт|Пт|
|Saturday|суббота|Суббота|
|Sat|Сб|Сбт|
|Sa|Сб|Сб|
|Sunday|воскресенье|Воскресенье|
|Sun|Вс|Вск|
|Su|Вс|Вс|
|January|январь|Январь|
|Jan|янв.|Янв|
|February|февраль|Февраль|
|Feb|февр.|Фев|
|March|март|Март|
|Mar|март|Мар|
|April|апрель|Апрель|
|Apr|апр.|Апр|
|May|май|Май|
|May|май|Май|
|June|июнь|Июнь|
|Jun|июнь|Июн|
|July|июль|Июль|
|Jul|июль|Июл|
|August|август|Август|
|Aug|авг.|Авг|
|September|сентябрь|Сентябрь|
|Sep|сент.|Сен|
|October|октябрь|Октябрь|
|Oct|окт.|Окт|
|November|ноябрь|Ноябрь|
|Nov|нояб.|Ноя|
|December|декабрь|Декабрь|
|Dec|дек.|Дек|

----
Russian, RU, and ru_RU should be the same :-)

**Comment by kylekatarnls** [comment]
Thanks, this will be merged with #1624 + #1623, I checked all the differences and ru_RU will be a perfect alias of ru in the next version.
