### ISSUE TITLE
[Translation tool] de_AT

### ISSUE THREAD

**Issue by Namoshek** [briannesbitt/Carbon#1641]
|English|de_AT|comments|
|--|--|--|
|January|Jänuar|It should be "Jänner" or "Januar". "Jänner" is often used as colloquial alternative in Austria (on a level where it's considered language compliant and not just dialect or slang), whereas "Januar" is the actual official German word for the month - also in Austria. The word "Jänuar" - as currently given in the translation - does __NOT__ exist.|

---

### On a side note

If `Januar` was chosen over `Jänner` (which is absolutely fine for the Austrian German language), there wouldn't be any need at all for customizations in the `de_AT.php` language file:

https://github.com/briannesbitt/Carbon/blob/c7b14d2907f7b79fe92a9e3315ba0987a29b509b/src/Carbon/Lang/de_AT.php#L18-L22

The different (and not even consistent) style for weekday and month abbreviations compared to the German defaults is not necessary and has no rationale based on grammar or something similar. In general, abbreviations are marked as such with a trailing dot `.` in the German language. This means that the `months_short` in the `de.php` translation file should also be marked as such (see `de_AT.php` for the desired result):

https://github.com/briannesbitt/Carbon/blob/c7b14d2907f7b79fe92a9e3315ba0987a29b509b/src/Carbon/Lang/de.php#L80-L83

As every German reading person will understand month and weekday names either way, with or without trailing dot, the variants for `weekdays_min` can be kept as such for brevity. `months_short` and `weekdays_short` should be adjusted for uniformity though.

**Comment by kylekatarnls** [comment]
Thanks a lot so I'll pick `Januar` to get `de_AT` a perfect `de` alias, and so less maintenance :)
