### ISSUE TITLE
[Translation tool] pt_BR

### ISSUE THREAD

**Issue by claudsonm** [briannesbitt/Carbon#1642]
|English|pt_BR|comments|
|--|--|--|
|Monday|Segunda-feira|This should rather be "segunda-feira" because the warning says to translate as if were in the middle of the sentence, and portuguese doesn't require to be uppercase.|
|Mon|Seg|This should rather be "seg." because the warning says to translate as if were in the middle of the sentence, and portuguese doesn't require to be uppercase.|
|Tuesday|Terça-feira|This should rather be "terça-feira" because the warning says to translate as if were in the middle of the sentence, and portuguese doesn't require to be uppercase.|
|Tue|Ter|This should rather be "ter." because the warning says to translate as if were in the middle of the sentence, and portuguese doesn't require to be uppercase.|
|Wednesday|Quarta-feira|This should rather be "quarta-feira" because the warning says to translate as if were in the middle of the sentence, and portuguese doesn't require to be uppercase.|
|Wed|Qua|This should rather be "qua." because the warning says to translate as if were in the middle of the sentence, and portuguese doesn't require to be uppercase.|
|Thursday|Quinta-feira|This should rather be "quinta-feira" because the warning says to translate as if were in the middle of the sentence, and portuguese doesn't require to be uppercase.|
|Thu|Qui|This should rather be "qui." because the warning says to translate as if were in the middle of the sentence, and portuguese doesn't require to be uppercase.|
|Friday|Sexta-feira|This should rather be "sexta-feira" because the warning says to translate as if were in the middle of the sentence, and portuguese doesn't require to be uppercase.|
|Fri|Sex|This should rather be "sex." because the warning says to translate as if were in the middle of the sentence, and portuguese doesn't require to be uppercase.|
|Saturday|Sábado|This should rather be "sábado" because the warning says to translate as if were in the middle of the sentence, and portuguese doesn't require to be uppercase.|
|Sat|Sáb|This should rather be "sáb." because the warning says to translate as if were in the middle of the sentence, and portuguese doesn't require to be uppercase.|
|Sa|Sá|This should rather be "sá." because the warning says to translate as if were in the middle of the sentence, and portuguese doesn't require to be uppercase.|
|Sunday|Domingo|This should rather be "domingo" because the warning says to translate as if were in the middle of the sentence, and portuguese doesn't require to be uppercase.|
|Sun|Dom|This should rather be "dom." because the warning says to translate as if were in the middle of the sentence, and portuguese doesn't require to be uppercase.|
|Su|Do|This should rather be "do." because the warning says to translate as if were in the middle of the sentence, and portuguese doesn't require to be uppercase.|
|Jan|jan|This should rather be "jan." because the warning says to translate as if were in the middle of the sentence, and portuguese doesn't require to be uppercase, so we need the dot to know it is an abbreviation.|
|Feb|fev|This should rather be "fev." because the warning says to translate as if were in the middle of the sentence, and portuguese doesn't require to be uppercase, so we need the dot to know it is an abbreviation.|
|Mar|mar|This should rather be "mar." because the warning says to translate as if were in the middle of the sentence, and portuguese doesn't require to be uppercase, so we need the dot to know it is an abbreviation.|
|Apr|abr|This should rather be "abr." because the warning says to translate as if were in the middle of the sentence, and portuguese doesn't require to be uppercase, so we need the dot to know it is an abbreviation.|
|May|mai|This should rather be "mai." because the warning says to translate as if were in the middle of the sentence, and portuguese doesn't require to be uppercase, so we need the dot to know it is an abbreviation.|
|Jun|jun|This should rather be "jun." because the warning says to translate as if were in the middle of the sentence, and portuguese doesn't require to be uppercase, so we need the dot to know it is an abbreviation.|
|Jul|jul|This should rather be "jul." because the warning says to translate as if were in the middle of the sentence, and portuguese doesn't require to be uppercase, so we need the dot to know it is an abbreviation.|
|Aug|ago|This should rather be "ago." because the warning says to translate as if were in the middle of the sentence, and portuguese doesn't require to be uppercase, so we need the dot to know it is an abbreviation.|
|Sep|set|This should rather be "set." because the warning says to translate as if were in the middle of the sentence, and portuguese doesn't require to be uppercase, so we need the dot to know it is an abbreviation.|
|Oct|out|This should rather be "out." because the warning says to translate as if were in the middle of the sentence, and portuguese doesn't require to be uppercase, so we need the dot to know it is an abbreviation.|
|Nov|nov|This should rather be "nov." because the warning says to translate as if were in the middle of the sentence, and portuguese doesn't require to be uppercase, so we need the dot to know it is an abbreviation.|
|Dec|dez|This should rather be "dez." because the warning says to translate as if were in the middle of the sentence, and portuguese doesn't require to be uppercase, so we need the dot to know it is an abbreviation.|

**Comment by kylekatarnls** [comment]
Thanks a lot, indeed I added this warning because I realized days/months of many languages kept the uppercase from English, and saw it was not correct for most languages but I didn't know which of them.

Thanks for the disambiguation for Portuguese. I will lowercase them and check dot abbreviations.

**Comment by kylekatarnls** [comment]
glibc: no dot
momentjs: no dot
rails-i18n: no dot
angular: no dot

So it seems to be some consensus on this. I will keep them without dots and precise a bit the warning.
