### ISSUE TITLE
Carbon gives invalid date

### ISSUE THREAD

**Issue by sujith2014** [briannesbitt/Carbon#1643]
Hello,

I encountered an issue with the following code:
```php

       echo $request->arrival;//2019-Mar-4
       $arrival = Carbon::parse($request->arrival)->format('d F Y');
       dd($arrival );//01 March 2019
```
Carbon version:  1.36.2
PHP version: PHP 7.3.1-1+ubuntu18.04.1+deb.sury.org+1 

I expected to get:
```
04 March 2019
```

But I actually get:
```
01 March 2019
```

Thanks!

**Comment by kylekatarnls** [comment]
When you use a custom format to create an object you must specify it to le PHP know how to parse the date:
```php
Carbon::createFromFormat('Y-M-d', '2019-Mar-4')->format('d F Y');
```
This gives you the date you expect and set the time to current time, you can specify an other time with `->setTime(0, 0, 0)`

`createFromFormat` comes from the native PHP DateTime class:
http://php.net/manual/en/datetime.createfromformat.php
