### ISSUE TITLE
[Translation tool] es_MX

### ISSUE THREAD

**Issue by rubenrp81** [briannesbitt/Carbon#1645]
## Additional fixes
yo he tenido que modificar para ver cuando llego un mensaje... he necesitado quitar la palabra "antes". Porque se olle raro leer el mensaje llego en una tabla y que diga en la celda "2 horas antes" es raro.... es mejor que diga: "hace 2 horas" o solo "2 horas", pero leer en una lista de mensajes "2 horas antes" es raro.

**Comment by kylekatarnls** [comment]
Hello. It's not a translation problem, it's an option:

```php
// Distance from now:
echo Carbon::now()->subHours(2)->locale('es_MX')->diffForHumans(); // hace 2 horas
// Distance from an other date:
echo Carbon::now()->subHours(2)->locale('es_MX')->diffForHumans(Carbon::now()); // 2 horas antes
```
And you can force a specific syntax:
```php
echo Carbon::now()->subHours(2)->locale('es_MX')->diffForHumans(['syntax' => CarbonInterface::DIFF_RELATIVE_TO_OTHER]); // 2 horas antes
echo Carbon::now()->subHours(2)->locale('es_MX')->diffForHumans(Carbon::now(), ['syntax' => CarbonInterface::DIFF_RELATIVE_TO_NOW]); // hace 2 horas
```
