### ISSUE TITLE
[Translation tool] ro

### ISSUE THREAD

**Issue by oriceon** [briannesbitt/Carbon#1646]
|English|ro|comments|
|--|--|--|
|2s|o sec.|2 sec.|
|Monday|luni|Luni|
|Tuesday|marți|Marți|
|Wednesday|miercuri|Miercuri|
|Thursday|joi|Joi|
|Friday|vineri|Vineri|
|Saturday|sâmbătă|Sâmbătă|
|Sunday|duminică|Duminică|
|January|ianuarie|Ianuarie|
|Jan|ian.|Ian.|
|February|februarie|Februarie|
|Feb|febr.|Febr.|
|March|martie|Martie|
|Mar|mart.|Mart.|
|April|aprilie|Aprilie|
|Apr|apr.|Apr.|
|May|mai|Mai|
|May|mai|Mai|
|June|iunie|Iunie|
|Jun|iun.|Iun.|
|July|iulie|Iulie|
|Jul|iul.|Iul.|
|August|august|August|
|Aug|aug.|Aug.|
|September|septembrie|Septembrie|
|Sep|sept.|Sept.|
|October|octombrie|Octombrie|
|Oct|oct.|Oct.|
|November|noiembrie|Noiembrie|
|Nov|nov.|Nov.|
|December|decembrie|Decembrie|
|Dec|dec.|Dec.|

----
a few seconds in romanian means "câteva secunde" but depends what you want. If you want to say a second, means "o secundă" ...

**Comment by kylekatarnls** [comment]
Thanks, "câteva secunde" would be better. It provide a approximation for recent events: "a few seconds ago".
And "o sec." is a typo bug, thanks for the fix.

However as per https://glosbe.com/en/ro/Monday
days and months are not uppercase in Romanian.

The uppercase in English is an English-specific rule, days and months are always this way even in the middle of a sentence.

**Comment by oriceon** [comment]
> The uppercase in English is an English-specific rule, days and months are always this way even in the middle of a sentence.

In this case, yes, you`re right.
