### ISSUE TITLE
[Translation tool] ro_RO

### ISSUE THREAD

**Issue by oriceon** [briannesbitt/Carbon#1647]
|English|ro_RO|comments|
|--|--|--|
|Monday|luni|Luni|
|Tuesday|marți|Marți|
|Tue|Mar|Mar|
|Tu|Ma|Ma|
|Wednesday|miercuri|Miercuri|
|Thursday|joi|Joi|
|Friday|vineri|Vineri|
|Saturday|sâmbătă|Sâmbătă|
|Sunday|duminică|Duminică|
|January|ianuarie|Ianuarie|
|Jan|ian.|Ian.|
|February|februarie|Februarie|
|Feb|febr.|Febr.|
|March|martie|Martie|
|Mar|mart.|Mart.|
|April|aprilie|Aprilie|
|Apr|apr.|Apr.|
|May|mai|Mai|
|May|mai|Mai|
|June|iunie|Iunie|
|Jun|iun.|Iun.|
|July|iulie|Iulie|
|Jul|iul.|Iul.|
|August|august|August|
|Aug|aug.|Aug.|
|September|septembrie|Septembrie|
|Sep|sept.|Sept.|
|October|octombrie|Octombrie|
|Oct|oct.|Oct.|
|November|noiembrie|Noiembrie|
|Nov|nov.|Nov.|
|December|decembrie|Decembrie|
|Dec|dec.|Dec.|

**Comment by kylekatarnls** [comment]
As per https://glosbe.com/en/ro/Monday
days and months are not uppercase in Romanian.

The uppercase in English is an English-specific rule, days and months are always this way even in the middle of a sentence.

If you have some references for uppercase in Romanian, please provide them here.

**Comment by oriceon** [comment]
No. Is ok as you said. They should be lowercase.
