### ISSUE TITLE
[Translation tool] pt_BR

### ISSUE THREAD

**Issue by tdoval** [briannesbitt/Carbon#1648]
|English|pt_BR|comments|
|--|--|--|
|January|janeiro|Janeiro - first letter uppercase|
|Jan|jan|Jan - first letter uppercase|
|February|fevereiro|Fevereiro - first letter uppercase|
|Feb|fev|Fev - first letter uppercase|
|March|março|Março - first letter uppercase|
|Mar|mar|Mar - first letter uppercase|
|April|abril|Abril - first letter uppercase|
|Apr|abr|Abr - first letter uppercase|
|May|maio|Maio - first letter uppercase|
|May|mai|Mai - first letter uppercase|
|June|junho|Junho - first letter uppercase|
|Jun|jun|Jun - first letter uppercase|
|July|julho|Julho - first letter uppercase|
|Jul|jul|Jul - first letter uppercase|
|August|agosto|Agosto - first letter uppercase|
|Aug|ago|Ago - first letter uppercase|
|September|setembro|Setembro - first letter uppercase|
|Sep|set|Set - first letter uppercase|
|October|outubro|Outubro - first letter uppercase|
|Oct|out|Out - first letter uppercase|
|November|novembro|Novembro - first letter uppercase|
|Nov|nov|Nov - first letter uppercase|
|December|dezembro|Dezembro - first letter uppercase|
|Dec|dez|Dez - first letter uppercase|

**Comment by kylekatarnls** [comment]
Thanks for you contribution.

I need some proofs:

https://blogs.transparent.com/portuguese/months-in-portuguese/
> One thing to note, however, is that when you’re writing a month in Portuguese, you do not capitalize the first letter of it.  So for example, when I write, “I was born in November,” in Portuguese, I would write, “Eu nasci em novembro.”

https://www.italki.com/question/176295
> Days, months and season.. sábado, fevereiro, verão.. aren't capitalized.**

http://www.portugueselanguageguide.com/vocabulary/months.asp
> examples in lowercase

I know these are not official references, but I don't find much more about this.

If you can provide other references in favor of uppercase, I will re-open this issue.
