### ISSUE TITLE
->total... properties returning double value on CarbonInterval

### ISSUE THREAD

**Issue by Zxurian** [briannesbitt/Carbon#1651]
Hello,

When using `CarbonInterval::milliseconds(<value>);` or `CarbonInterval::microseconds(<value>);` to instiate a `CarbonInterval` object, the corresponding `->total...` magic properties for seconds units or higher are returning double the internal value.

Carbon version: **2.4.12**
PHP version: **7.2.16**

Hero Carbon test link: https://try-carbon.herokuapp.com/?embed&theme=xcode&border=silver&options-color=rgba(120,120,120,0.5)&input=%24interval%20%3D%20CarbonInterval%3A%3Amilliseconds(500000)%3B%0D%0A%0D%0Avar_dump(%24interval)%3B%0D%0Avar_dump(%24interval-%3EtotalSeconds)%3B%0D%0Avar_dump(%24interval-%3EtotalMinutes)%3B%0D%0Avar_dump(%24interval-%3EtotalHours)%3B#

Test Code:
```php
$interval = CarbonInterval::milliseconds(600000);
var_dump($interval->totalMicroseconds);
var_dump($interval->totalMilliseconds);
var_dump($interval->totalSeconds);
var_dump($interval->totalMinutes);
var_dump($interval->totalHours);
```
I expected to get:
```
int(600000000)
int(600000)
int(600)
int(10)
float(0.16666666666667)
```

But I actually get:
```
int(600000000)
int(600000)
int(1200)
int(20)
float(0.33333333333333)
```

dumping the CarbonInterval object itself it looks like the `->f` property is being set correctly, on instiation, it's just the return of the magic `->total...` properties that are incorrect.

Thanks!

**Comment by kylekatarnls** [comment]
Hello, the total properties can only work on valid intervals (intervals that have microseconds between 0 and 999999, seconds between 0 and 59, etc.). To get such interval from a 600000 milliseconds interval, you first need to cascade it (dispatch units to a bigger one on overflow):

```php
$interval = CarbonInterval::milliseconds(600000)->cascade();

var_dump($interval->totalMicroseconds);
var_dump($interval->totalMilliseconds);
var_dump($interval->totalSeconds);
var_dump($interval->totalMinutes);
var_dump($interval->totalHours);
```

I will add something about that in the documentation.

Thanks,

**Comment by Zxurian** [comment]
okay, so not providing a value higher than than the upper bound of the respective unit is understandable, however even with a valid unit, the `->total...` properties are still off.
New Heroku link: https://try-carbon.herokuapp.com/?embed&theme=xcode&border=silver&options-color=rgba(120,120,120,0.5)&input=%24interval%20%3D%20CarbonInterval%3A%3Amilliseconds(500)%3B%0D%0A%0D%0Avar_dump(%24interval)%3B%0D%0Avar_dump(%24interval-%3EtotalSeconds)%3B%0D%0Avar_dump(%24interval-%3EtotalMinutes)%3B%0D%0Avar_dump(%24interval-%3EtotalHours)%3B#

500 is a valid value for milliseconds (as far as I know), and the internal property of `f` is properly set to 0.5, but the output is wrong:
Expected:
```
int(0.5)
float(0.00833333333333)
float(0.00013888888889))
```
Actual:
```
int(1)
float(0.016666666666667)
float(0.00027777777777778)
```

**Comment by Zxurian** [comment]
Awesome, appreciate the quick fix.

**Comment by kylekatarnls** [comment]
This ends this huge release:
https://github.com/briannesbitt/Carbon/releases/tag/2.15.0

**Comment by mikerockett** [comment]
I've just bumped into something quite similar when using work-week cascade factors:

```php
CarbonInterval::setCascadeFactors([
  'minute' => [60, 'seconds'],
  'hour' => [60, 'minutes'],
  'day' => [8, 'hours'],
  'week' => [5, 'days'],
]);

CarbonInterval::make('1d')->totalDays; // 1
CarbonInterval::make('1w')->totalDays; // 10
CarbonInterval::make('1w')->totalWeeks; // 2 😲
```

Using Carbon 2.29.1.

**Comment by kylekatarnls** [comment]
It will be fixed in 2.30, please try to require `"nesbot/carbon": "dev-master"` to test it.

**Comment by mikerockett** [comment]
Thanks Kyle – will test it out shortly.

**Comment by mikerockett** [comment]
Working perfectly, thank you!
