### ISSUE TITLE
[Translation tool] ru

### ISSUE THREAD

**Issue by AlexWalkerson** [briannesbitt/Carbon#1656]
|English|ru|comments|
|--|--|--|
|1 week|1 неделю|1 неделя|
|a week|неделю|неделя|
|1 minute|1 минуту|1 минута|
|a minute|минуту|минута|
|1 second|1 секунду|1 секунда|
|a few seconds|секунду|несколько секунд|

**Comment by kylekatarnls** [comment]
Hi @AlexWalkerson, thanks for your help!

May I ask if you know Ukrainian, and if so, if you can check the **uk** locale?
