### ISSUE TITLE
Consider updating Standard Moroccan Tamazight to the following

### ISSUE THREAD

**Issue by BAKTETE** [briannesbitt/Carbon#1665]
**File**           : `zgh.php` 
**Language** : Standard Moroccan Tamazight

[zgh.txt](https://github.com/briannesbitt/Carbon/files/2985892/zgh.txt)

**Comment by kylekatarnls** [comment]
Hi, thanks a lot. I see you removed the meridiem: `['ⵜⵉⴼⴰⵡⵜ', 'ⵜⴰⴷⴳⴳⵯⴰⵜ']` it means it will fallback to `AM / PM`. Is it relevant?

**Comment by BAKTETE** [comment]
thank you for noticing 
**Updated file**  : [zgh.txt](https://github.com/briannesbitt/Carbon/files/2987124/zgh.txt)

**Comment by kylekatarnls** [comment]
There are difference between this file and what you put here #1665
Like plural year: `ⵉⵙⴳⴳⵓⵙⴰ` vs. `ⵉⵙⴳⴳⵯⴰⵙⵏ`

Pleas explain what fit which context. If it's a declension, it would need a closure to choose the right declension.

**Comment by BAKTETE** [comment]
singular : ⵓⵙⴳⴳⵯⴰⵙ
for the plural can be both : ⵉⵙⴳⴳⵯⴰⵙⵏ/ⵉⵙⴳⴳⵓⵙⴰ
based on official dictionary of ircam.ma

http://tal.ircam.ma/dglai/lexieam.php
![848D5A82-9CD9-4595-8A4E-21AD632725BC](https://user-images.githubusercontent.com/27772375/54681345-03f74580-4b04-11e9-9a81-027dc8e389d5.jpeg)

**Comment by BAKTETE** [comment]
it's not updated in tha package 
```
'a_year' => 'un an|:count ⵉⵙⴳⴳⵓⵙⴰ',
'y' => ':count an|:count ⵉⵙⴳⴳⵓⵙⴰ',
```
should have become
```
'a_year' => 'ⵓⵙⴳⴳⵯⴰⵙ|:count ⵉⵙⴳⴳⵓⵙⴰ',
'y' => ':count ⵓⵙⴳⴳⵯⴰⵙ|:count ⵉⵙⴳⴳⵓⵙⴰ',
```

**Comment by kylekatarnls** [comment]
Thanks, a 2.18.1 patch will be released soon with this fix.
