### ISSUE TITLE
problem when installing carbon in laravel 5.7.28

### ISSUE THREAD

**Issue by josermarinr** [briannesbitt/Carbon#1672]
Hello,
i used composer require nesbot/carbon

Problem 1
    - laravel/framework v5.7.28 requires nesbot/carbon ^1.26.3 -> satisfiable by nesbot/carbon[1.26.3, 1.26.4, 1.27.0, 1.28.0, 1.29.0, 1.29.1, 1.29.2, 1.30.0, 1.31.0, 1.31.1, 1.32.0, 1.33.0, 1.34.0, 1.34.1, 1.34.2, 1.34.3, 1.34.4, 1.35.0, 1.35.1, 1.36.0, 1.36.1, 1.36.2] but these conflict with your requirements or minimum-stability.

in my composer.json i put "nesbot/carbon": "^2.16.0" in require

i use laravel 5.7 and i dont know why i have this issue

thank you

**Comment by kylekatarnls** [comment]
This message means: Laravel 5.7 requires Carbon 1 (Carbon 2 not fully supported as with Laravel 5.8) that's why we made an adaptater, it's all explained the the documentation how you can install it:
https://carbon.nesbot.com/#gettingstarted
