### ISSUE TITLE
[Translation tool] ru_RU

### ISSUE THREAD

**Issue by UnsealedOne** [briannesbitt/Carbon#1674]
|English|ru_RU|comments|
|--|--|--|
|2yrs|2 года|2 г. (because it is how we shorten words)|
|2w|2 нед|2 нед. (because the point is necessary after the non-weights and non-measures abbreviation)|
|2d|2 дня.|2 д. (because it is how we shorten words)|
|1 minute|1 минуту|1 минута (but in case of 1 minute ago it still should be 1 минуту назад)|
|a minute|минуту|минута (but in case of a minute ago it still should be минуту назад)|

----
There are $transformDiff function at Carbon/src/Carbon/Lang/ru.php:11 in which you need to add the third line 'минута' => 'минуту' to solve the problem with minute/minute ago, like this:

```
$transformDiff = function ($input) {
    return strtr($input, [
        'неделя' => 'неделю',
        'секунда' => 'секунду',
        'минута' => 'минуту',
    ]);
};
```

Hope this helps :)

**Comment by kylekatarnls** [comment]
Perfect! Thanks.
