### ISSUE TITLE
Failed to parse time string

### ISSUE THREAD

**Issue by whthT** [briannesbitt/Carbon#1675]
I've been getting that kind of error over Carbon lately. I've generally seen the problem on Linux systems. I couldn't figure out if the problem was about me or the Carbon updates.

Thanks.

/var/www/:private:/vendor/nesbot/carbon/src/Carbon/Carbon.php(548): DateTime -> __ construct ('1553669292', Object (DateTimeZone))

**Comment by kylekatarnls** [comment]
Some informations we ask in our issue template are missing, to get support please ensure to give at least:

- [ ] your Carbon version;
- [ ] your PHP version;
- [ ] a minimal code chunk to reproduce your case.

Thanks.
