### ISSUE TITLE
Problem parse february into number

### ISSUE THREAD

**Issue by mromimuhtarom** [briannesbitt/Carbon#1677]
Hello,

I encountered an issue with the following code:
```
<?php
echo Carbon::parse('february')->month;
?>
```
and this is the result
https://drive.google.com/open?id=1ftbZHfLOodxv7O2HlEv9r3llewtkRG_d
Carbon version: **1.25.**
PHP version: **PHP7**
I got some problem when I  parse february into number. the show of number february is 3 that should be is 2 

Thanks!

**Comment by kylekatarnls** [comment]
Hello, it's how PHP itself decided to handle it.

To understand see, this raw PHP code:
```php
$date = new DateTime('february');
echo $date->format('Y-m-d H:i:s');
```

You get:
```
2019-03-01 00:00:00
```

And if you try with `31 february` you will get `2019-03-03 00:00:00`.

In fact PHP assume if you do not specify day and year, you mean current day and current year, so PHP will convert it for you into `29 february 2019`. Sadly this date does not exist, and again, PHP has a very opinionated way to handle it, it take the overflow (1/2/3 days after the previous valid date), then it add it to this last valid date so 28 february + 1 day if you're the 29th like today, (+2 if you're the 30, +3 for the 31).

So the only way to deal properly with it is to specify the day:
```php
echo Carbon::parse('1 february')->month;
```

Hope it helps.

**Comment by mromimuhtarom** [comment]
thank you for your information
