### ISSUE TITLE
Project name issue

### ISSUE THREAD

**Issue by peter279k** [briannesbitt/Carbon#1680]
As title, I want to know about the follwing projects difference.

What's different from [CarbonDate/Carbon](https://github.com/CarbonDate/Carbon) package?

**Comment by kylekatarnls** [comment]
Hi,

Anyone can fork a project or make its own copy and publish it in composer, that's how open-source works. We are not responsible for CarbonDate/Carbon. This project is just a copy of briannesbitt/Carbon created in April 2018 and abandoned in May 2018, you probably don't want to use it.

briannesbitt/Carbon (nesbot/carbon in composer) is the original Carbon project used in Laravel for example and is still maintained (last version released 19 hours ago).

Official documentation is here: https://carbon.nesbot.com/ and you can see https://github.com/briannesbitt is the original author of the project.
