### ISSUE TITLE
[Translation tool] ar

### ISSUE THREAD

**Issue by yazan-alnugnugh** [briannesbitt/Carbon#1682]
|English|ar|comments|
|--|--|--|
|a few seconds|ثانية|بضع ثواني|
|Mo|ن|اث|
|Tu|ث|ثل|
|We|ر|أر|
|Th|خ|خم|

**Comment by kylekatarnls** [comment]
Hi, thanks for your help. Is there some reference link where we can see the days shortened this way?

**Comment by kylekatarnls** [comment]
If anyone confirm `اث`, `ثل`, `أر`, `خم` and ideally provide a reference I would reopen the issue.

**Comment by yazan-alnugnugh** [comment]
if you want to take first two letter it's true

________________________________
من: Kyle <notifications@github.com>
‏‏تم الإرسال: 01/شعبان/1440 08:12 م
إلى: briannesbitt/Carbon
نسخة: yazan-alnugnugh; Author
‏‏الموضوع: Re: [briannesbitt/Carbon] [Translation tool] ar (#1682)


If anyone confirm اث, ثل, أر, خم and ideally provide a reference I would reopen the issue.

**Comment by kylekatarnls** [comment]
It's not basically the two first letters (because in some language several days would have the same). It should be a way as short as possible but still clear to shorten days, for example to make a calendar:

|Su|Mo|Tu|We|Th|Fr|Sa|
|-|-|-|-|-|-|-|
||||||1|2|
|3|4|5|6|7|8|9|
|10|11|12|13|14|15|16|
|17|18|19|20|21|22|23|
|24|25|26|27|28|||

In this case, what would you have in the table header?

**Comment by yazan-alnugnugh** [comment]
I see but in arabic we don't have  shurtcut
For day but if use to letters we can understand
Best regard
Yazan alnughnugh



-------- الرسالة الأصلية --------
من: Kyle <notifications@github.com>
التاريخ: ٧‏/٤‏/٢٠١٩ ١١:١٦ ص (GMT+03:00)
إلى: briannesbitt/Carbon <Carbon@noreply.github.com>
نسخة: yazan-alnugnugh <yazan-n100@hotmail.com>, Author <author@noreply.github.com>
الموضوع: Re: [briannesbitt/Carbon] [Translation tool] ar (#1682)


It's not basically the two first letters (because in some language several days would have the same). It should be a way as short as possible but still clear to shorten days, for example to make a calendar:

Su      Mo      Tu      We      Th      Fr      Sa
                                        1       2
3       4       5       6       7       8       9
10      11      12      13      14      15      16
17      18      19      20      21      22      23
24      25      26      27      28

In this case, what would you have in the table header?

**Comment by kylekatarnls** [comment]
Thanks!
