### ISSUE TITLE
Leap Week Issue

### ISSUE THREAD

**Issue by KillermenBE** [briannesbitt/Carbon#1683]
Hello,

I encountered an issue with the following code:
```php
echo Carbon::createFromDate(2020)->weeksInYear
```
Carbon version: 2.16.1
PHP version: 7.3.1

I expected to get:
```
53
```

But I actually get:
```
52
```

2020 is a year where we have 53 weeks instead of 52. (What we call a leapweek)

> An ISO week-numbering year (also called ISO year informally) has 52 or 53 full weeks. That is 364 or 371 days instead of the usual 365 or 366 days. The extra week is sometimes referred to as a leap week, although ISO 8601 does not use this term.

Thanks!

**Comment by kylekatarnls** [comment]
Yep ISO has its own method:
```php
echo Carbon::createFromDate(2020)->weeksInYear; // 52
echo "\n";
echo Carbon::createFromDate(2020)->isoWeeksInYear; // 53
```

`weeksInYear` depends on the locale (because you don't have the same week number in every regions depending on first day of week, can be Monday, Sunday, Saturday, etc. and how many day of the new year must have the first week, can be 1, 4, 7):
```php
echo Carbon::createFromDate(2020)->locale('en_US')->weeksInYear; // 52
echo "\n";
echo Carbon::createFromDate(2020)->locale('fr_FR')->weeksInYear; // 53
```
