### ISSUE TITLE
[RuntimeException]  Failed to clone https://github.com/briannesbitt/Carbon.git via https, ssh protocols, aborting. 

### ISSUE THREAD

**Issue by ankit20893** [briannesbitt/Carbon#1692]
[RuntimeException]                                                                                           
  Failed to clone https://github.com/briannesbitt/Carbon.git via https, ssh protocols, aborting.               
                                                                                                               
  - https://github.com/briannesbitt/Carbon.git                                                                 
    Cloning into '/var/www/devnagri-web/vendor/nesbot/carbon'...                                               
    fatal: unable to access 'https://github.com/briannesbitt/Carbon.git/': Could not resolve host: github.com  
                                                                                                               
  - git@github.com:briannesbitt/Carbon.git                                                                     
    Cloning into '/var/www/devnagri-web/vendor/nesbot/carbon'...                                               
    ssh: Could not resolve hostname github.com: Temporary failure in name resolution                           
    fatal: Could not read from remote repository.                                                              
                                                                                                               
    Please make sure you have the correct access rights                                                        
    and the repository exists. 

@note Internet is working

**Comment by kylekatarnls** [comment]
`Could not resolve hostname github.com` is typical network issue and as it's "github.com" that is not found, it means it's a Carbon specific issue. It could require you to clear your DNS cache (search for "clear DNS cache on Windows/Mac/Linux"). Even if you can see github.com in your browser, you may have an other cache in ssh.

You also may have blocked ports on your firewall.
