### ISSUE TITLE
Functionnality : AgeForHumans 

### ISSUE THREAD

**Issue by Nuranto** [briannesbitt/Carbon#1700]
Hello,

There's no way as far I as I know to display a decent age.
The closest way I found is this one : 
``` 
$age = $this->date_of_birth->diff(Carbon::now());
        if($age->days == 0) {
            return __('Borned today !');
        }
        if($age->days >= 365) {
            return $this->date_of_birth->diffForHumans(Carbon::now(), true, true, 1);
        }
        return $this->date_of_birth->diffForHumans(Carbon::now(), true, true, 2);
```

However it's not perfect, far from there.
For instance, it displays : `1 year 10 hours` or `3 years 2 days`. And if we reduce the parts, it will display `1 year` for someone who's second birthday is tomorrow... :(

I think age display (for humans) is very specific and should have its own helper.

Here is, I think, generic needs for age : 
0 : Just borned
Below 1 month : Display in days
Below 1 year : Display in half months, rounded : `2 months`, `2 month and a half` (or `2 months ½`), or months+rounded weeks (if short parameter = false)
Then : Display in half years, rounded, or years+rounded months (if short parameter = false)

**Comment by kylekatarnls** [comment]
Hi,

Use the `age` property (it's automatically from now, floor value, so complete years only):
```php
$this->date_of_birth->age
```

**Comment by Nuranto** [comment]
I understand it is debatable.
Thank you for the macro solution example !
