### ISSUE TITLE
Functionnality - New option for diffForHumans - sequential parts

### ISSUE THREAD

**Issue by Nuranto** [briannesbitt/Carbon#1701]
Hello,

Here is a suggestion for diffForHumans helper : 
New option = SEQUENTIAL_PARTS_ONLY

which would behave like this (assuming parts = 2 for the example)

diff | without SEQUENTIAL_PARTS_ONLY (actual result/default)  | with SEQUENTIAL_PARTS_ONLY
------------ | ------------ | -------------
2019-01-04 - 2019-02-04 | 1 month | 1 month
2019-01-04 - 2019-02-05 | 1 month 1 day | 1 month 1 day
2019-01-04 - 2020-01-04 | 1 year | 1 year
2019-01-04 - 2020-01-05 | 1 year 1 day | 1 year
2019-01-04 - 2020-02-04 | 1 year 1 month | 1 year 1 month
2019-01-04 12:00:00 - 2020-01-04 13:00:00 | 1 year 1 hour | 1 year
2019-01-04 12:00:00 - 2019-02-04 13:00:00 | 1 month  1 hour| 1 month

Possible implementation  : 

```
--- a/CarbonInterval.php
+++ b/CarbonInterval.php
@@ -978,6 +978,8 @@
                 $unit = $short ? $diffIntervalData['unitShort'] : $diffIntervalData['unit'];
                 $count = $diffIntervalData['value'];
                 $interval[] = $transChoice($short, $diffIntervalData);
+            } else if(CarbonInterface::SEQUENTIAL_PARTS_ONLY && count($interval)>0) {
+                break;
             }
 
             // break the loop after we get the required number of parts in array
```

**Comment by kylekatarnls** [comment]
I approve. Target version 2.18. Of course, it's open to pull-requests.

**Comment by kylekatarnls** [comment]
@serima implemented a solution and provided many good unit tests. @Nuranto as you may notice, `2019-01-04 -> 2019-02-05` will output `1 month` and not `1 month 1 day` as you wish because month and day are not consecutive in our array (we have week between them).

The `SEQUENTIAL_PARTS_ONLY` is a good short-cut we can keep, but what you want would need a more precise API such as a mapping from max unit to min unit:

```php
$origin->diffForHumans($comparison, [
    'minUnits' => [
        'year' => 'month',
        'month' => 'day',
        'week' => 'day',
        'day' => 'hour',
        'hour' => 'minute',
        'minute' => 'second',
    ],
]);
```

**Comment by Nuranto** [comment]
Actually, that was a mistake of mine in my first message -_- Sorry about that.
@serima's PR is exactly what I needed.

**Comment by kylekatarnls** [comment]
OK, so I will close this and you'll get it in the May release 2.18.0.
