### ISSUE TITLE
Incorrect daylight saving handling

### ISSUE THREAD

**Issue by laurencei** [briannesbitt/Carbon#1704]
Hello,

I encountered an issue with the following code:
```php
$start = Carbon::createFromFormat('Y-m-d H:i:s', '2019-04-07 01:00:00', 'Australia/Sydney');
$finish = Carbon::createFromFormat('Y-m-d H:i:s', '2019-04-07 04:00:00', 'Australia/Sydney');

while ($start < $finish) {
     var_dump($start->addMinutes(15)->format('c'));
}
```

Carbon version: 2.16.3

PHP version: 7.2.11

This is what I get:

```
'2019-04-07T01:15:00+11:00'
'2019-04-07T01:30:00+11:00'
'2019-04-07T01:45:00+11:00'
'2019-04-07T02:00:00+10:00'
'2019-04-07T02:15:00+10:00'
'2019-04-07T02:30:00+10:00'
'2019-04-07T02:45:00+10:00'
'2019-04-07T03:00:00+10:00'
'2019-04-07T03:15:00+10:00'
'2019-04-07T03:30:00+10:00'
'2019-04-07T03:45:00+10:00'
'2019-04-07T04:00:00+10:00'
```

But this is what I would have expected to get:

```diff
  '2019-04-07T01:15:00+11:00'
  '2019-04-07T01:30:00+11:00'
  '2019-04-07T01:45:00+11:00'
+ '2019-04-07T02:00:00+11:00'
+ '2019-04-07T02:15:00+11:00'
+ '2019-04-07T02:30:00+11:00'
+ '2019-04-07T02:45:00+11:00'
  '2019-04-07T02:00:00+10:00'
  '2019-04-07T02:15:00+10:00'
  '2019-04-07T02:30:00+10:00'
  '2019-04-07T02:45:00+10:00'
  '2019-04-07T03:00:00+10:00'
  '2019-04-07T03:15:00+10:00'
  '2019-04-07T03:30:00+10:00'
  '2019-04-07T03:45:00+10:00'
  '2019-04-07T04:00:00+10:00'
```

Basically on the 7th of April 2019, DST ended at 0259, and the clocks went back to 0200. So you have a "doubling" of time between 0200 and 0259 (for pre and post DST).

Except when Carbon increments through this time period, it simply skips DST ending an hour early, and does not handle the time changes as expected.

**Comment by kylekatarnls** [comment]
It's a known PHP bug: https://bugs.php.net/bug.php?id=30532

As Carbon rely on PHP DateTime API for manipulations (like addMinutes), we cannot change this behavior without breaking other features.

My recommandation is to never do any calculation using timezone, you should work with UTC server-side and only change the timezone for parse a user input or display a date to the user end. With or without this bug, it's a best practice.

```php
$start = Carbon::createFromFormat('Y-m-d H:i:s', '2019-04-07 01:00:00', 'Australia/Sydney')->tz('UTC');
$finish = Carbon::createFromFormat('Y-m-d H:i:s', '2019-04-07 04:00:00', 'Australia/Sydney')->tz('UTC');

while ($start < $finish) {
    $date = $start->addMinutes(15)->copy();
    var_dump($date->tz('Australia/Sydney')->format('c'));
}
```

**Comment by laurencei** [comment]
@kylekatarnls - ok, thanks for that.

And yeah, UTC is king, I just had a 3rd party datasource that is causing me headaches, but I'll do something like what you've proposed. Thanks.
