### ISSUE TITLE
Carbon 1.37.0 causing exceptions on all add/sub methods

### ISSUE THREAD

**Issue by robinnydahl** [briannesbitt/Carbon#1708]
Hey there,

We've started to experience this exception when we first had a deployment today before [this commit](https://github.com/briannesbitt/Carbon/commit/f8a29bb3b0cf1f4dc94ba1deaeccd8084b206ce8), all went okay. Then we made a second deployment a while back after it was merged to master, bumping the version up to 1.37.0. Now we have application wide failures.

For example when we run:
```php
Carbon::parse('2019-01-01)->subDays(1)->isToday()
```

We get: 
```php
BadMethodCallException: Method subDays does not exist.
```

The same issue goes for all sub/add of Days, Hours, Minutes, Seconds. We've manually downgraded to the `1.36.2` version for now and the issue is then gone.

Carbon version: `1.37.0`
PHP version: `7.1.28`
Laravel version: `5.5.45`

Thanks!

**Comment by robinnydahl** [comment]
Ping: @matt-allan and @kylekatarnls

**Comment by matt-allan** [comment]
I don’t think it’s that change, it’s a bad tag. It looks like master was tagged as 1.37 which means it contains all of the 2.0+ breaking changes?

**Comment by robinnydahl** [comment]
@matt-allan That might be it. Haven't looked into the actual code changes.

**Comment by matt-allan** [comment]
I can’t create tags, only maintainers can.  I think you need @kylekatarnls to do that.

**Comment by kylekatarnls** [comment]
Tag removed, i Will retag today

**Comment by kylekatarnls** [comment]
Patch released.

**Comment by kylekatarnls** [comment]
Run `composer update` to get 1.37.1.
