### ISSUE TITLE
[Translation tool] ru_RU

### ISSUE THREAD

**Issue by axel-verse** [briannesbitt/Carbon#1711]
## Additional fixes
Please note that there is a rather difficult case system in Russian.
Please note common date/time format difference.
So `May 1 2019` could be translated as `Май, 1, 2019` but should be translated as `1 мая 2019` ( with the month's name in the genitive case).

Correct date/time formats for Russian are `d.m.Y`, `d M Y` and `d F Y` for dates and `H:I` / `H:i:s` for time `(PHP date() format)`.

Y-m-d | m/d/Y | d.m.Y | d M Y | d F Y | F, d, Y
--- | --- | --- | --- | --- | ---
2019-01-01 | 01/01/2019 | 01.01.2019 | 1 янв 2019 | 1 января 2019 | январь, 1, 2019
2019-02-01 | 02/01/2019 | 01.02.2019 | 1 фев 2019 | 1 февраля 2019 | февраль, 1, 2019
2019-03-01 | 03/01/2019 | 01.03.2019 | 1 мар 2019 | 1 марта 2019 | март, 1, 2019
2019-04-01 | 04/01/2019 | 01.04.2019 | 1 апр 2019 | 1 апреля 2019 | апрель, 1, 2019
2019-05-01 | 05/01/2019 | 01.05.2019 | 1 мая 2019 | 1 мая 2019 | май, 1, 2019
2019-06-01 | 06/01/2019 | 01.06.2019 | 1 июн 2019 | 1 июня 2019 | июнь, 1, 2019
2019 -07-01 | 07/01/2019 | 01.07.2019 | 1 июл 2019 | 1 июля 2019 | июль, 1, 2019
2019-08-01 | 08/01/2019 | 01.08.2019 | 1 авг 2019 | 1 августа 2019 | август, 1, 2019
2019-09-01 | 09/01/2019 | 01.09.2019 | 1 сен 2019 | 1 сентября 2019 | сентябрь, 1, 2019
2019-10-01 | 10/01/2019 | 01.10.2019 | 1 окт 2019 | 1 октября 2019 | октябрь, 1, 2019
2019-11-01 | 11/01/2019 | 01.11.2019 | 1 ноя 2019 | 1 ноября 2019 | ноябрь, 1, 2019
2019-12-01 | 12/01/2019 | 01.12.2019 | 1 дек 2019 | 1 декабря 2019 | декабрь, 1, 2019

## Date/time ranges

Also there are some difficulties with date/time ranges:

### 1) YEARS

En | Ru
--- | ---
1 year | 1 год
2 years - 4 years | 2 года - 4 года 
but then
5 years - 20 years | 5 лет - 20 лет
and then
21 years | 21 год
22 years - 24 years | 22 года - 24 года
25 years - 30 years | 25 лет - 30 лет
... | ...
95 years - 100 years | 95 лет - 100 лет
101 years | 101 год
102 years - 104 years | 102 года - 104 года
105 years - 120 years | 105 лет - 120 лет

etc

### 2) MONTHS

En | Ru
--- | ---
1 month | 1 месяц
2 months - 4 months | 2 месяца - 4 месяца
5 months - 20 months | 5 месяцев - 20 месяцев

etc like years

### 3) DAYS

En | Ru
--- | ---
1 day | 1 день
2 days - 4 days | 2 дня - 4 дня
5 days - 20 days | 5 дней - 20 дней

etc

### 4) HOURS

En | Ru
--- | ---
1 hour | 1 час
2 hours - 4 hours | 2 часа - 4 часа
5 hours - 20 hours | 5 часов - 20 часов

etc

### 5) MINUTES

En | Ru
--- | ---
1 minute | 1 минута
2 minutes - 4 minutes | 2 минуты - 4 минуты
5 minutes - 20 minutes | 5 минут - 20 минут

etc

### 6) SECONDS

En | Ru
--- | ---
1 second | 1 секунда
2 seconds - 4 seconds | 2 секунды - 4 секунды
5 seconds - 20 seconds | 5 секунд - 20 секунд

etc

Hope this information can help somehow

**Comment by kylekatarnls** [comment]
Hi,

Thanks for the check and cases list. I'll keep this for next checking.

Column `d F Y` is OK:
```php
echo Carbon::parse('2019-01-01')->locale('ru_RU')->translatedFormat('d F Y');
echo "\n";
echo Carbon::parse('2019-02-01')->locale('ru_RU')->translatedFormat('d F Y');
// ...
```

Column `d M Y` is OK:
```php
echo Carbon::parse('2019-01-01')->locale('ru_RU')->translatedFormat('d M Y');
echo "\n";
echo Carbon::parse('2019-02-01')->locale('ru_RU')->translatedFormat('d M Y');
// ...
```

Column `F, d, Y` is OK:
```php
echo Carbon::parse('2019-01-01')->locale('ru_RU')->translatedFormat('F, d, Y');
echo "\n";
echo Carbon::parse('2019-02-01')->locale('ru_RU')->translatedFormat('F, d, Y');
// ...
```

Year OK:
```php
echo CarbonInterval::year()->locale('ru_RU')->forHumans();
echo "\n";
echo CarbonInterval::years(2)->locale('ru_RU')->forHumans();
echo "\n";
echo CarbonInterval::years(4)->locale('ru_RU')->forHumans();
echo "\n";
echo CarbonInterval::years(5)->locale('ru_RU')->forHumans();
echo "\n";
echo CarbonInterval::years(21)->locale('ru_RU')->forHumans();
```

Month OK:
```php
echo CarbonInterval::month()->locale('ru_RU')->forHumans();
echo "\n";
echo CarbonInterval::months(2)->locale('ru_RU')->forHumans();
echo "\n";
echo CarbonInterval::months(4)->locale('ru_RU')->forHumans();
echo "\n";
echo CarbonInterval::months(5)->locale('ru_RU')->forHumans();
echo "\n";
echo CarbonInterval::months(21)->locale('ru_RU')->forHumans();
```

Day OK:
```php
CarbonInterval::setCascadeFactors([
    'week' => [999999, 'days'],
]);

echo CarbonInterval::day()->locale('ru_RU')->forHumans();
echo "\n";
echo CarbonInterval::days(2)->locale('ru_RU')->forHumans();
echo "\n";
echo CarbonInterval::days(4)->locale('ru_RU')->forHumans();
echo "\n";
echo CarbonInterval::days(5)->locale('ru_RU')->forHumans();
echo "\n";
echo CarbonInterval::days(21)->locale('ru_RU')->forHumans();
```

Hour OK:
```php
echo CarbonInterval::hour()->locale('ru_RU')->forHumans();
echo "\n";
echo CarbonInterval::hours(2)->locale('ru_RU')->forHumans();
echo "\n";
echo CarbonInterval::hours(4)->locale('ru_RU')->forHumans();
echo "\n";
echo CarbonInterval::hours(5)->locale('ru_RU')->forHumans();
echo "\n";
echo CarbonInterval::hours(21)->locale('ru_RU')->forHumans();
```

Minute OK:
```php
echo CarbonInterval::minute()->locale('ru_RU')->forHumans();
echo "\n";
echo CarbonInterval::minutes(2)->locale('ru_RU')->forHumans();
echo "\n";
echo CarbonInterval::minutes(4)->locale('ru_RU')->forHumans();
echo "\n";
echo CarbonInterval::minutes(5)->locale('ru_RU')->forHumans();
echo "\n";
echo CarbonInterval::minutes(21)->locale('ru_RU')->forHumans();
```

Second OK:
```php
echo CarbonInterval::second()->locale('ru_RU')->forHumans();
echo "\n";
echo CarbonInterval::seconds(2)->locale('ru_RU')->forHumans();
echo "\n";
echo CarbonInterval::seconds(4)->locale('ru_RU')->forHumans();
echo "\n";
echo CarbonInterval::seconds(5)->locale('ru_RU')->forHumans();
echo "\n";
echo CarbonInterval::seconds(21)->locale('ru_RU')->forHumans();
```

I check them quickly and get results you list.

If you see any differences between Carbon 2.17 and your table, please show your code.

**Comment by axel-verse** [comment]
Good day,

at the moment everything is ok with my code. I just visited the Carbon site to read the documentation and saw an offer to help with the translation. So I thought that it would not hurt you to get some information from a native Russian speaker. So this is just a bit of background information.

Regards.

And thank you so much for your wonderful project.
