### ISSUE TITLE
laravel.   include(/www/mall/vendor/composer/../nesbot/carbon/src/Carbon/Traits/Test.php): failed to open stream: No such file or directory

### ISSUE THREAD

**Issue by wangtxxl** [briannesbitt/Carbon#1712]
CentOS Linux release 7.6.1810 (Core)
Linux wsc 5.0.0-1.el7.elrepo.x86_64 #1 SMP Mon Mar 4 09:43:09 EST 2019 x86_64 x86_64 x86_64 GNU/Linux

don't support  xx/../xx  

cat: /www/mall/vendor/composer/../nesbot/carbon/src/Carbon/Traits/Test.php 

php -v
PHP 7.3.5 (cli) (built: Apr 30 2019 08:37:17) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.5, Copyright (c) 1998-2018 Zend Technologies

**Comment by kylekatarnls** [comment]
Some informations we ask in our issue template are missing, to get support please ensure to give at least:

- [ ] your Carbon version;
- [ ] a minimal code chunk/installation process to reproduce your case;

Thanks.
