### ISSUE TITLE
[Translation tool] ka_GE

### ISSUE THREAD

**Issue by akalongman** [briannesbitt/Carbon#1716]
|English|ka_GE|comments|
|--|--|--|
|2 hours ago|2 საათშიში|This should be "2 საათის უკან"|
|2 hours from now|2 საათის წინ|This should be "2 საათში"|
|2 hours before|2 საათი უკან|This should be "2 საათით ადრე"|
|2 hours after|2 საათი შემდეგ|This should be "2 საათის შემდეგ"|

----
Please make these changes as soon as possible

**Comment by kylekatarnls** [comment]
I acknowledge this and will try to add it in the May release but I have to check it deeper, Google Translate and moment.js both give different results for those cases and ka locale is a special case:
https://github.com/briannesbitt/Carbon/blob/master/src/Carbon/Lang/ka.php

Only some words ends change according to past/future but not all (so the closures in ka.php) we have to handle this in a way that does not make things worst (for other units mostly) and we also should handle composite intervals: `2 hours and 30 minutes ago`.

It would help me if you could give me more samples with composite intervals, with 1 hour, with days.

Or if you know the exact rule and can implement it in PHP, feel free to propose a pull-request on **Lang/ka.php**.

**Comment by akalongman** [comment]
@kylekatarnls first of all I'll send a PR with updated tests, which result is correct for each case (obviously they will fail for now).
Second step should be updating the ka rules and in this I need your help, because translation mechanism was changed when I updated ka rules in the library last time.

**Comment by kylekatarnls** [comment]
Thanks a lot. If you can do the tests and provide some official references where we can se the same sentences, I will implement the function.

**Comment by kylekatarnls** [comment]
Hi,

I have a difficulty, why do we need the `შემდეგ` suffix after `3 წლის` but not `2 საათის` what is the rule?

**Comment by kylekatarnls** [comment]
I compared with i18n in closure-library to get the rules. I close this issue to continue the discussion on the PR, please review the test changes. #1719
