### ISSUE TITLE
DatePeriod::between doesn't change from default DateInterval

### ISSUE THREAD

**Issue by tomtomau** [briannesbitt/Carbon#1717]
Hello,

I encountered an issue with the following code, presented as a failing test case:
```php

class BetweenTest extends AbstractTestCase
{
	public function testBetweenReturnsCorrectInterval() {
		$period = CarbonPeriod::between(new \DateTimeImmutable(), new \DateTimeImmutable('+1 hour'));
		$interval = $period->getDateInterval();

		static::assertSame(1, $interval->totalHours);
	}
}
```

Carbon version: **master**

PHP version: **7.2**

I expected to get:

```
1 - the dateinterval I get back out of it should only be 1 hour
```

But I actually get:

```
24 - as it is using the default interval
```

-------

My use case is wanting to get a DateInterval between two dates that excludes weekends. From reading the documentation, I assumed I would be able to:

* create a DatePeriod::between($start, $end)
* filter out weekends
* Then call getDateInterval on the period

However, when setting the start and end, it doesn't actually change the DateInterval, nor does filtering update this DateInterval either.

I'm not totally sure if this is expected or not? It seems odd to be able to construct a DatePeriod without an interval and get a non-null interval when you call getDateInterval.

Thanks!

**Comment by kylekatarnls** [comment]
Hi,

There is nothing in you code that would allow `CarbonPeriod` to know you want a 1-hour interval.

`CarbonPeriod` allow you to loop over an interval you choose (or 1 day by default) n times from a start or between a start and an end. So the interval can be 2 minutes and the end can be 4 years after the start. Or the contrary you can have a year interval and the end just one minute after the start.

More about the `CarbonPeriod` class here: https://carbon.nesbot.com/docs/#api-period

For you weekend case, you need to explicitly specify you want 1-hour interval:
```php
foreach (CarbonPeriod::hour()->between(new \DateTimeImmutable(), new \DateTimeImmutable('+1 hour')) as $date) {
  if ($date->isWeekend()) {
    continue;
  }

  // Here it's not the week-end and it loop every hour
}
```

**Comment by kylekatarnls** [comment]
If you have any other question, feel free to ask. If you think there is something needed to be changed, tell me and I would re-open the issue if needed.
