### ISSUE TITLE
[Translation tool] ca

### ISSUE THREAD

**Issue by qcardona** [briannesbitt/Carbon#1725]
|English|ca|comments|
|--|--|--|
|2yrs|2 a.|2 anys, because it's not usual to abbreviate "year" word|
|2mos|2 me.|2 mesos, because it's not usual to abbreviate "month" word|
|2w|2 st.|2 setmanes, because it's not usual to abbreviate "week" word|
|2m|2 mi.|2 min, because "min" is the usual abbreviation for "minute"|
|2s|2 sg.|2 s, because "s" is the usual abbreviation for "second"|

**Comment by kylekatarnls** [comment]
Thanks @qcardona for you help.
@Quenty31 @v0ctor Can you confirm or not, short notation is understandable in Catalan?

Short unit can be used for example for interval display in small place like work time logging:
`2 st. 30 mi.`

**Comment by v0ctor** [comment]
According to [this document](https://www.avl.gva.es/documents/31595/32337/Gram%C3%A0tica+normativa+valenciana/825a1c69-34c9-43b6-83f9-7a527a2833e3) by [Acadèmia Valenciana de la Llengua](https://en.wikipedia.org/wiki/Acad%C3%A8mia_Valenciana_de_la_Llengua) (Valencian Language Academy) and [this one](http://llengua.gencat.cat/web/.content/documents/publicacions/altres/arxius/abrevia.pdf) by [Generalitat de Catalunya](https://en.wikipedia.org/wiki/Generalitat_de_Catalunya), seconds and minutes should be abbreviated as "s" and "min", respectively. However, I'm afraid that it is not possible to abbreviate weeks, months or years.

I agree with @qcardona. I think his/her proposal is the most suitable option. As a native speaker I think that "a.", "me." and "st." are not understandable.

**Comment by kylekatarnls** [comment]
Thanks a lot everybody, I will change it for the next version.

**Comment by Quenty31** [comment]
Yes the same here, it's the same with Occitan, years and months cannot be shortened like so.
