### ISSUE TITLE
[Translation tool] uk_UA

### ISSUE THREAD

**Issue by Andrend** [briannesbitt/Carbon#1727]
|English|uk_UA|comments|
|--|--|--|
|2yrs|2 роки|2р|
|2mos|2 місяці|2м|
|2w|2 тижні|2т|
|2d|2 дні|2д|
|2h|2 години|2г|
|2m|2 хвилини|2хв|
|2s|2 секунди|2 сек|

**Comment by kylekatarnls** [comment]
Thanks will be fixed in the next release.
