### ISSUE TITLE
Returning nov. instead of nov for locale fr

### ISSUE THREAD

**Issue by jjoey87** [briannesbitt/Carbon#1728]
I encountered an issue with the following code:
```php
        $start = Carbon::createFromDate(2019, 05, 01);

        $this->assertEquals('1 mai 2019', $start->locale('fr')->isoFormat('D MMM YYYY'));

        $start = Carbon::createFromDate(2019, 11, 01);

        $this->assertEquals('1 nov 2019', $start->locale('fr')->isoFormat('D MMM YYYY'));
```

Carbon version: 2.17.1

PHP version: 7.2.3

I expected to get:

```
nov
```
But I actually get:

```
nov.
```

**Comment by kylekatarnls** [comment]
Hi @jjoey87 word abbreviations in French have a trailing dot. "mai" does not because it's not abbreviated, the may month is only 3 letters in French too, so it must not have a dot. "nov." is "novembre" abbreviated, it needs the dot to explicitly mention we cut letters. "nov" is incorrect in French.
