### ISSUE TITLE
add 

### ISSUE THREAD

**Issue by hasensuadik39** [briannesbitt/Carbon#1729]
Hello,

I encountered an issue with the following code:
```php
echo Carbon::parse('2018-06-01')->subDay()->month;
```

Carbon version: **PUT HERE YOUR COMPOSER CARBON VERSION**

PHP version: **PUT HERE YOUR PHP VERSION**

I expected to get:

```
6
```

But I actually get:

```
5
```

Thanks!

**Comment by kylekatarnls** [comment]
Hi,

This behavior is expected and 99.9% of Carbon users rely on it for their applications to works properly. Carbon is always on a valid date: day before June 1st is May 31st, May is month 5.

I don't understand why you're expecting 6.
