### ISSUE TITLE
[Translation tool] fi

### ISSUE THREAD

**Issue by Pikseli** [briannesbitt/Carbon#1732]
|English|fi|comments|
|--|--|--|
|2yrs|2 vuotta|2 v|
|2mos|2 kuukautta|2 kk|
|2w|2 viikkoa|2 vk|
|2d|2 päivää|2 pv|
|2h|2 tuntia|2 t|
|2m|2 minuuttia|2 min|
|2s|2 sekuntia|2 s|

----
Short versions of Finnish units.

http://www.kielitoimistonohjepankki.fi/ohje/190

**Comment by kylekatarnls** [comment]
Thanks! Will be released in 2.19.
