### ISSUE TITLE
Port simple methods from Carbon 2 to Carbon 1.39

### ISSUE THREAD

**Issue by kylekatarnls** [briannesbitt/Carbon#1736]
The following methods could be ported to Carbon 1 with moderate efforts:
  - [x] startOfMillennium
  - [x] endOfMillennium
  - [x] isAfter
  - [x] isBefore
  - [x] isBetween
  - [x] toDateTimeLocalString
  - [x] toObject
  - [x] toString
  - [x] toISOString
  - [x] toJSON
  - [x] toDateTime
  - [x] toDate
  - [x] diffInMicroseconds
  - [x] diffInMilliseconds
  - [x] diffInRealMicroseconds
  - [x] diffInRealMilliseconds
  - [x] from
  - [x] since
  - [x] to
  - [x] until
  - [x] fromNow
  - [x] toNow
  - [x] ago
  - [x] resetMacros
  - [x] cast
  - [x] __debugInfo

1.39 would be the last minor release of 1.x. Having those methods in Carbon 1 could help the transition and the compatibility for third-party libraries.

I'll try to implement the maximum of them during the next month, if anyone is interested in helping in this task feel free to propose pull-requests on the **version-1.next** branch.

**Comment by bobdenotter** [comment]
Thanks! I appreciate you doing this. 

With our project, we're sticking with Symfony 4's requirements, which means we'll need to support PHP 7.1.3, which means an update to Carbon 2 is not possible, yet. So, you taking the time to do this, will be helpful for our users. Thanks, again! 👍

**Comment by kylekatarnls** [comment]
Arf, crap, 7.1.3 is very close to our supported range. We require PHP 7.1.8 to include this bugfix of PHP:

> Fixed bug #74852 (property_exists returns true on unknown DateInterval property).
> https://bugs.php.net/bug.php?id=74852

**Comment by kylekatarnls** [comment]
1.39.0 released.
