### ISSUE TITLE
overmorrow() feature request

### ISSUE THREAD

**Issue by iateadonut** [briannesbitt/Carbon#1738]
Hello,

I would like a feature overmorrow() that would act the same as ->addDays(2).  "Overmorrow" is a neat word.  https://www.dictionary.com/browse/overmorrow - Assign it to me if you're willing to merge it!

Thanks!

**Comment by kylekatarnls** [comment]
Hi, I think a macro is enough for that:

```php
Carbon::macro('overmorrow', function () {
  $date = isset($this) ? $this : Carbon::now();

  return $date->addDays(2);
});
```

I believe +2 days is yet easy to do with `addDays(2)` and not so common to deserve its own method. Then `overmorrow` will not be an obvious name so it would not be too helpful.
