### ISSUE TITLE
createFromDate() bug when creating a February date

### ISSUE THREAD

**Issue by panyushov** [briannesbitt/Carbon#1739]
Hello,

I encountered an issue with the following code:
```php
echo Carbon::createFromDate(2019, 2)->month;
```

Carbon version: 2.17.1

PHP version: 7.3.3

I expected to get:

```
2
```

But I actually get:

```
3
```

Thanks!

**Comment by kylekatarnls** [comment]
Hi,

It's how PHP handle it, it takes current day, then if this day does not exist in the month you want, it overflows to the next month:

See the explanation of this behavior here: https://github.com/briannesbitt/Carbon/issues/1677#issuecomment-477908839

You have to specify the day:
```php
echo Carbon::createFromDate(2019, 2, 1)->month;
```

Or to set a maximum:
```php
$date = Carbon::createFromDate(2019, 2);
$monthLastDay = Carbon::createFromDate(2019, 2, 1)->endOfMonth()->startOfDay();

if ($date > $monthLastDay) {
  $date = $monthLastDay;
}
```

**Comment by panyushov** [comment]
@kylekatarnls Wouldn't it be better to add in createFromDate doc line explaining that any missing year, month or day would be set to now() just like it's specified for Carbon\Traits\Creator::create method? Now this behavior feels counterintuitive to me. Thank you

**Comment by kylekatarnls** [comment]
It's yet documented:

> createFromDate() will default the time to now

**Comment by kylekatarnls** [comment]
You have an example with year in documentation:

```php
$xmasThisYear = Carbon::createFromDate(null, 12, 25);  // Year defaults to current year
```

It's not more obvious to take `1` or any other value as default. Normal use-case for `Carbon::createFromDate()` is to pass a date so year, month and day. It makes your code explicit and matches the method name.

But indeed we can add an example with day default and usage recommendation. Feel free to propose a PR on the documentation:
https://github.com/briannesbitt/Carbon/blob/gh-pages/docs/index.src.html#L218

**Comment by kylekatarnls** [comment]
It's now documented.
