### ISSUE TITLE
[Translation tool] cs_CZ

### ISSUE THREAD

**Issue by tommaskraus** [briannesbitt/Carbon#1740]
|English|cs_CZ|comments|
|--|--|--|
|a month|1 měsíc|měsíc|
|a week|1 týden|týden|
|a day|1 den|den|
|1 hour|1 hodinu|1 hodina|
|an hour|1 hodinu|hodina|
|1 minute|1 minutu|1 minuta|
|a minute|1 minutu|minuta|
|1 second|1 sekundu|1 sekunda|
|a few seconds|1 sekundu|pár sekund|
|Jun|čer|čvn|
|Jul|čer|čvc|
|2 hours ago|2 hodiny nazpět|2 hodiny před|
|2 hours before|2 hodiny předtím|2 hodiny před|
|2 hours after|o 2 hodiny později|2 hodiny po|

**Comment by kylekatarnls** [comment]
Hi @tommaskraus we need to understand somehow the difference between "2 hours ago" (before now) and "2 hours before" (an other date/time):

Examples:
I will leave **2 hours before** the end of the day.
The movie started **2 hours ago**, so now it's ended.

The same way "2 hours after" and "2 hours from now" must be clear enough to get the difference. without ambiguity.

Nevertheless, I will fix June/July abbreviated name and implement "a unit" form and fix singular units.

**Comment by kylekatarnls** [comment]
About hodinu/minutu/sekundu, they have been translated this way initially because they are usually output with nazpět, předtím, etc. So I need here to add a custom rule to take hodina by default but hodinu if it's with an after/before sentence.

**Comment by kylekatarnls** [comment]
Please check the PR I started to fix Czech translations #1741

**Comment by kylekatarnls** [comment]
Finally I kept the `před` for both `ago` and `before` and `za` for both `from now` and `after`, I close this to continue discussion on the PR #1741
