### ISSUE TITLE
[Translation tool] cs

### ISSUE THREAD

**Issue by calvera** [briannesbitt/Carbon#1742]
|English|cs|comments|
|--|--|--|
|2 hours ago|2 hodiny nazpět|před 2 hodinami|
|2 hours before|2 hodiny předtím|před 2 hodinami|

**Comment by kylekatarnls** [comment]
Hi @calvera, as mentioned #1740, we should distinguish both are not the same, ago is related to now, before is related to any other date:

2 hours before lunch (can be in the future).
2 hours ago (always 2 hours before now)

Please also check the PR I start to fix Czech translations #1741

**Comment by VaclavPavek** [comment]
@kylekatarnls 's description / solution is right

**Comment by kylekatarnls** [comment]
Finally I kept the `před` for both `ago` and `before` and `za` for both `from now` and `after`, I close this to continue discussion on the PR #1741
