### ISSUE TITLE
[Translation tool] nl

### ISSUE THREAD

**Issue by jhorie** [briannesbitt/Carbon#1744]
|English|nl|comments|
|--|--|--|
|2yrs|2j|This should rather be "2 jr", because the abbreviation for year is "jr" in Dutch|

**Comment by kylekatarnls** [comment]
I did not found this abbreviation and i18n google/closure-library also use "j". Could you provide some reference where it appears.

**Comment by jhorie** [comment]
Okay, so I looked for some references. The website below is a website, which shows Dutch abbreviations. And also the one we mentioned.

http://www.afkortingwoordenboek.nl/wat-betekent-de-afkorting-jr/

**Comment by kylekatarnls** [comment]
According to this page both j and jr can abbreviate jaar:
https://nl.wikipedia.org/wiki/Lijst_van_afkortingen_in_het_Nederlands#J

As lower j only abbreviate jaar, while jr can abbreviate both junior and jaar, I would be tempted to keep `j` for less ambiguity.

Would you say it's a personal preference or one of them is more common/obvious/clear?

**Comment by RikSomers** [comment]
To be honest, I'm pretty sure 'j' is more commonly used. e.g. "per year" is abbreviated to 'p.j.' not 'p.jr.',

**Comment by kylekatarnls** [comment]
Thanks @jhorie and @RikSomers for your help. I will add as an argument that we should avoid to change translations if it does not worth it (so texts do not change when you do `composer update` unless the new translation is really better.

So I close this issue. Thanks again for the checking.
