### ISSUE TITLE
Confusing dayOfWeek value

### ISSUE THREAD

**Issue by VVelda** [briannesbitt/Carbon#175]
EndOfWeek is sunday as it should be accroding to international norms. But dayOfWeek starts with sunday at index 0. But sunday should be on index 6 as the last day of week...
Why is it so chaotic?

**Comment by bryannielsen** [comment]
What's the reason for not changing this in a major release?  It's not adhering to the ISO standard right now and is confusing behavior.

**Comment by dereuromark** [comment]
+1 for changing it in a major release to adhere to ISO standard.

**Comment by briannesbitt** [comment]
Here is the PR for it.  I'll do it in a 2.0 release.

**Comment by bryannielsen** [comment]
Awesome, sorry didn't see the PR before!  
Here's a link for everyone's future reference: https://github.com/briannesbitt/Carbon/pull/214

**Comment by briannesbitt** [comment]
Ha... meant to paste the PR link when I said "Here is the PR for it"... oops.. thanks !

**Comment by bryannielsen** [comment]
No problem!  You've got lots on your plate, thanks for making my interactions with DateTime more pleasant :-)
