### ISSUE TITLE
CarbonInterval::times() method cannot handle float numbers like 1.5h

### ISSUE THREAD

**Issue by ToeiRei** [briannesbitt/Carbon#1750]
Hello,

I encountered an issue with the following code:
```php
// A work-week has 38.5 hours
$target = CarbonInterval::hours(38)->minutes(30);
// divide per 5 workdays aka multiply by 0.2
$target = $target->times( 0.20 );
echo $target->forHumans(['parts' => 2, 'short' => true]);
```

Carbon version: 2.19.1

PHP version: PHP 7.3.6

I expected to get:

```
7h 42m
```

But I actually get:

```
8h 6m
```

Thanks!

**Comment by kylekatarnls** [comment]
`times()` proceed a rounding for each unit, and no cascading from units to other ones. It means 30 minutes times 5, becomes 150 minutes (but adding `->cascade()` allows to get 2 hours 30 minutes).

I will check the impact for other features if we remove the rounding.

**Comment by ToeiRei** [comment]
The basic idea is to do some punchcard calculations. As there is no divide() I have tried to work around that. Went via minutes on various parts as I posted this bug - but it doesn't add to the readability of the code.

**Comment by kylekatarnls** [comment]
OK, so here is the work-around you need:
```php
$input = CarbonInterval::hours(38)->minutes(30);
$output = CarbonInterval::minutes($input->totalMinutes)->times(0.2)->cascade();

echo $output->forHumans(['parts' => 2, 'short' => true]);
```

You can use `CarbonInterval::seconds($input->totalSeconds)` if you `$input` interval may contain seconds.

**Comment by ToeiRei** [comment]
yeah, that's pretty much what I currently use.

**Comment by kylekatarnls** [comment]
If you have 38.5 as input it's even more easy since you need the minutes total:

```php
$target = CarbonInterval::minutes(38.5 * 60 * 0.2)->cascade();

echo $target->forHumans(['parts' => 2, 'short' => true]);
```

**Comment by ToeiRei** [comment]
Thanks - That actually made my day!

**Comment by kylekatarnls** [comment]
2.20 will come with:
- shares: shares(5) is equivalent to times(0.2)
- multiply: multiple() do a precise calculation from microseconds to year and cascade units
- divide: divide(5) is equivalent to multiply(0.2)
