### ISSUE TITLE
⬆️ CarbonPeriod could soon extend DatePeriod

### ISSUE THREAD

**Issue by imbrish** [briannesbitt/Carbon#1752]
Hei!

I haven't been actively developing in PHP since a year or so, but I'm still getting occasional updates from https://github.com/php/php-src. One of the news is that https://github.com/php/php-src/pull/3121 have finally been merged! It'll be available in PHP 7.4 but I'm not sure about the earlier releases.

It may be then a good idea to think about making CarbonPeriod extend the DatePeriod. However, as we had to remake the thing from scratch, I'm not sure about the compatiblity, particularly as I don't know which versions of PHP should be supported by Carbon 2.

In any case I think I should be able to help with the research and refactoring after the sommer if you think that should be done :)

**Comment by kylekatarnls** [comment]
Thanks @imbrish, "soon" is probably not so true, because using a PHP 7.4 feature means dropping PHP 7.1, 7.2 and 7.3. And even just dropping PHP 7.1 can't happen until the next major version and only if we decide it's acceptable to drop it as this moment. And even if PHP 7.1 is patched with this (let say PHP 7.1.31 contains the fix), it doesn't help since we need to drop PHP 7.1.8 to PHP 7.1.30 and it's also a breaking change for Carbon.

So I would rather say if someday we're about to drop PHP < 7.4, it's something we can reconsider.

**Comment by imbrish** [comment]
Guess "soon" was in fact bit optimistic, but I used it as opposed to "never" 😄 

Anyway if it's due to happen someday then it may be wise to go towards converging the implementation to match DatePeriod over the time. After having a brief look at the original pull request (https://github.com/briannesbitt/Carbon/pull/1270) I'm not sure if that's doable at all, for example because of the differences in handling recurrences. That's why I mentioned some research first, also to decide if it's a reasonable goal, given that people are satisfied with how CarbonPeriod is now. I dont' think it is all that common to use it as a DatePeriod replacement.

**Comment by kylekatarnls** [comment]
I started a branch for a version 3. It will mostly be used to make some breaking changes about some behavior and default values that could be more consistent and remove some stuff.

So I'm reconsidering `CarbonPeriod extends DatePeriod` so instances can be used directly when typing expect `DatePeriod`. But I would rather hesitate between 7.2 and 7.3 as minimum level. 7.4 is still a bit high regarding php.net/supported-versions.php and current usage.

**Comment by kylekatarnls** [comment]
Laravel 9 will drop PHP < 7.4, Carbon 3 will follow the move and so this is now in the run again for next major version.

**Comment by kylekatarnls** [comment]
This will have to be postponed again as `DatePeriod` iterable itself is not overridable before PHP 8.0:
https://3v4l.org/Bugtc

**Comment by kylekatarnls** [comment]
For now it's available requiring `"nesbot/carbon": "^4.0@dev"` in your **composer.json**. But for anyone wanting to try it, please keep in mind, that as even 3.0 is not yet released, this branch is a very draft prototype and can still receive many breaking change, and as PHP 7.4 will be supported by PHP team until 28 Nov 2021, we'll probably not release version 4 before 2022.

**Comment by kylekatarnls** [comment]
Available with `composer require nesbot/carbon:^3.0@dev`
