### ISSUE TITLE
[Translation tool] tr

### ISSUE THREAD

**Issue by ozgurky** [briannesbitt/Carbon#1758]
|English|tr|comments|
|--|--|--|
|2 hours from now|2 saat sonra|This should rather be "şu andan itibaren 2 saat" because "from now"  specifies the current time.|

**Comment by kylekatarnls** [comment]
Rather than current time, it should mean "in the future", in English it also can be "in 2 hours" (like in "we lunch in 2 hours") and `"şu andan itibaren 2 saat"` seems very long. 

Could you translate `we lunch in 2 hours` as an example?

Thanks.

**Comment by kylekatarnls** [comment]
I will close this for now, I would re-open if native speakers can give me more input.
