### ISSUE TITLE
Documentation issue

### ISSUE THREAD

**Issue by didotsonev** [briannesbitt/Carbon#1759]
Hello,

I encountered an issue with the following code:
```
dd(Carbon::createFromFormat('d-m-Y H:mm', '21-05-1975 22:00'));
```

Per documentation: 
```
Code: mm 
Example: 04 
Description: Minute with trailing zero from 00 to 59
```

![Screenshot from 2019-06-21 09-54-10](https://user-images.githubusercontent.com/25154121/59907969-98778980-940c-11e9-858d-8e05c98af298.png)

Carbon version: `"nesbot/carbon": "^1.26.0"`

PHP version: `"php": ">=7.0"`

I expected to get:
Carbon date
```
Carbon @169938000 {#784
  date: 1975-05-21 22:00:00.0 Europe/Oslo (+01:00)
}
```

But I actually get:

```
"Data missing"
OR
"A textual day could not be found↵Data missing"
OR
"Unexpected data found.↵Data missing"
```

(because of the minutes format)

If I use `i` for minutes everything works:
```
dd(Carbon::createFromFormat('d-m-Y H:i', '21-05-1975 22:00'));
```

Thanks!

**Comment by kylekatarnls** [comment]
Hi @didotsonev, documentation is for version 2.x as 1.x is now in end of life. And this table is for `isoFormat` (and `createFromIsoFormat`) (that are enhanced and can be internationalized) not for `format` and `createFromFormat` that simply use native PHP format:
https://www.php.net/manual/fr/function.date.php#refsect1-function.date-parameters

Thanks.
