### ISSUE TITLE
[Translation tool] uk_UA

### ISSUE THREAD

**Issue by lysyjpuzatik** [briannesbitt/Carbon#1762]
|English|uk_UA|comments|
|--|--|--|
|2h|2 години|2 год|
|2m|2 хвилини|2 хв|
|2s|2 секунди|2 сек|

**Comment by kylekatarnls** [comment]
Hi, this sounds like the translation tool is not up to date, those abbreviation are already fixed. I will update, thanks.

**Comment by kylekatarnls** [comment]
Thanks, translation tool updated.
