### ISSUE TITLE
Problem when serializing mutated carbon attribute on blade

### ISSUE THREAD

**Issue by mazzioficial** [briannesbitt/Carbon#1763]
Hello,

I encountered an issue with the following code:
```php
public function getInitDateAttribute()
    {
        return ($this->finish_date->subDay($this->quantity_days));
    }
```
I'm using laravel 5.8.26

Whereas
finish_date = '2018-12-20 00:00:00.000000'
quantity_days = 100

var finish_date is a carbon datetime value returned from the database.
var quantity_days is integer

When I return an object where there is a carbon mutated attribute the serialized value on the blade is **2018-12-20T02:00:59.000000Z** and not **2018-12-20 00:00:00.000000**

Carbon version: **2.20.0**

PHP version: **7.2.2**

I expected to get:

```
Mutated attribute serialize **2018-12-20 00:00:00.000000**
```

But I actually get:

```
2018-12-20T02:00:59.000000Z
```

Thanks!

**Comment by kylekatarnls** [comment]
This is how it's serialized as JSON. Default cast to string would give you what you need. An even better way is to call explictly the format method.
