### ISSUE TITLE
[Translation tool] fil

### ISSUE THREAD

**Issue by alohajaycee** [briannesbitt/Carbon#1764]
|English|fil|comments|
|--|--|--|
|2 years|2 gulang|This should rather be "2 taon" because "2 gulang" is used for pertaining to an age of someone or something|
|2yrs|2 gulang|This should rather be "2 taon" because "2 gulang" is used for pertaining to an age of someone or something|
|2 seconds|2 ulit|This should rather be "2 segundo" because "ulit" means repeat.|
|2s|2 ulit|This should rather be "2 segundo" because "ulit" means repeat.|
|1 second|1 ulit|This should rather be "1 segundo" because "ulit" means repeat.|
|a few seconds|1 ulit|This should rather be "1 segundo" because "ulit" means repeat.|
|2 hours before|2 oras before|this should be "2 oras bago" because the current one is still English|
|2 hours after|2 oras after|this should be "2 oras pagkatapos" because the current one is still English|

**Comment by kylekatarnls** [comment]
Thanks, if anyone want to do a PR for this, feel free, else I will hand le this n'est week.

**Comment by kylekatarnls** [comment]
Hi @alohajaycee you can check the PR #1771.

If everything is good, it will be released this month in the version 2.21.
