### ISSUE TITLE
Activate sponsorship setting

### ISSUE THREAD

**Issue by andrey-helldar** [briannesbitt/Carbon#1766]
You created a `.github/FUNDING.yml` file, but did't turn on the setting.

![2019-07-02_14-14-55](https://user-images.githubusercontent.com/10347617/60508674-c776e080-9cd3-11e9-8be4-07f6265f4bc6.png)

How to activate:
![screenshot-github com-2019 07 02-14-16-53](https://user-images.githubusercontent.com/10347617/60508865-40763800-9cd4-11e9-91aa-5d1e37f0c8ab.png)

**Comment by kylekatarnls** [comment]
Thank you @andrey-helldar I know, it's ready on my fork since the opening of this as you can see: https://github.com/kylekatarnls/Carbon

This is in discussion with the owner.
