### ISSUE TITLE
Add DateInterval factories

### ISSUE THREAD

**Issue by webmozart** [briannesbitt/Carbon#177]
What do you think about adding factory methods for DateIntervals to `Carbon`?

```php
$interval = Carbon::days(5);
$interval = Carbon::weeks(20);
$interval = Carbon::minutes(10);
```

See the API of the great [Period](http://www.joda.org/joda-time/apidocs/org/joda/time/Period.html) class in Joda Time for some inspiration.

**Comment by briannesbitt** [comment]
Not sure there is much interest in this at the moment.

**Comment by briannesbitt** [comment]
https://github.com/briannesbitt/Carbon/commit/552017d416c056f36955162440b5e9da495c6a7a

CarbonInterval::years(2);
