### ISSUE TITLE
TravisCI build failing because of carbon error: Source director has uncommitted changes.

### ISSUE THREAD

**Issue by collizo4sky** [briannesbitt/Carbon#1773]
Our build is failing on TravisCI => https://travis-ci.org/mailoptin/core/jobs/554846850#L258

...because of this error

[RuntimeException]                                                           
  Source directory /home/travis/build/mailoptin/core/vendor/nesbot/carbon has  
   uncommitted changes. 

Any idea why this is happening?

**Comment by kylekatarnls** [comment]
Merge this:
https://github.com/mailoptin/core/pull/14

And it will be green again:
https://travis-ci.org/mailoptin/core/jobs/552188241

**Comment by kylekatarnls** [comment]
For the record, it's not related to Carbon, it could happen with any package, some post-scripts, a bad install (interrupted during copying for example) or a manual edition can make the package with uncommitted changes. That's why, re-installing all the vendor directory is better.

**Comment by collizo4sky** [comment]
Thank you.
