### ISSUE TITLE
Add equalTo() to CarbonInterval and CarbonPeriod

### ISSUE THREAD

**Issue by kylekatarnls** [briannesbitt/Carbon#1775]
The method `equalTo()` and its `eq()` alias should be available on `CarbonInterval` and `CarbonPeriod` as they are on `Carbon`:

```php
CarbonInterval::day()->equalTo(CarbonInterval::hours(24)); // would be true
```

`->compare()` or `->totalMicroseconds` could be used for the comparison. The same way, it is possible to implement `greaterThan()` and `lesserThan()`, etc. (for `CarbonInterval` only).

```php
CarbonPeriod::create('2010-01-01', '2010-02-01')
  ->equalTo(Carbon::parse('2010-01-01')->daysUntil('2010-02-01')); // would be true
```

2 periods would be equal if they have equal starts, equal ends, equal interval and the same options.

**Comment by burobo** [comment]
I would like to add equalTo() to CarbonPeriod in the same way as that of CarbonInterval which invokes make().
So I'll implement it after make() method of CarbonPeriod is merged to master.

**Comment by burobo** [comment]
I would like to add equalTo() to CarbonPeriod. The method would invoke both make() of CarbonPeriod and eq() of CarbonInterval. They are in each PR now. The code would look like this.

```php
    /**
     * Determines if the instance is equal to another
     *
     * @param mixed $period
     *
     * @return bool
     */
    public function equalTo($period): bool
    {
        if (!($period instanceof self)) {
            $period = self::make($period);
        }

        return $period !== null
            && $this->getDateInterval()->eq($period->getDateInterval())
            && $this->getStartDate()->eq($period->getStartDate())
            && $this->getEndDate()->eq($period->getEndDate())
            && $this->getOptions() === $period->getOptions();
    }
```

How do I do?

**Comment by kylekatarnls** [comment]
I created a branch `version-2.22` and merged the 2 PRs for milestone 2.22, you can create a PR against this branch. Thanks!

**Comment by burobo** [comment]
Thank you so much!

Also, I can implement comparison methods notEqualTo(), greaterThan(), lesserThan(), greaterThanOrEqualTo(), lesserThanOrEqualTo() and their alias methods to CarbonInterval. May I make PR to this issue?

**Comment by kylekatarnls** [comment]
I created a dedicated issue for <> comparisons: #1796

So this issue is solved. Congratulations!
