### ISSUE TITLE
Trait 'Carbon\Traits\Comparison' not found

### ISSUE THREAD

**Issue by bhargav960143** [briannesbitt/Carbon#1780]
Hello,

I encountered an issue with the following code:
```
Symfony \ Component \ Debug \ Exception \ FatalErrorException (E_UNKNOWN)
Trait 'Carbon\Traits\Comparison' not found
```
vendor/nesbot/carbon/src/Carbon/Traits/Date.php
```php
* @method        string         shortRelativeToNowDiffForHumans(\DateTimeInterface $other = null, int $parts = 1)   Get the difference (short format, 'RelativeToNow' mode) in a human readable format in the current locale. ($other and $parts parameters can be swapped.)
 * @method        string         longRelativeToNowDiffForHumans(\DateTimeInterface $other = null, int $parts = 1)    Get the difference (long format, 'RelativeToNow' mode) in a human readable format in the current locale. ($other and $parts parameters can be swapped.)
 * @method        string         shortRelativeToOtherDiffForHumans(\DateTimeInterface $other = null, int $parts = 1) Get the difference (short format, 'RelativeToOther' mode) in a human readable format in the current locale. ($other and $parts parameters can be swapped.)
 * @method        string         longRelativeToOtherDiffForHumans(\DateTimeInterface $other = null, int $parts = 1)  Get the difference (long format, 'RelativeToOther' mode) in a human readable format in the current locale. ($other and $parts parameters can be swapped.)
 *
 * </autodoc>
 */
trait Date
{
    use Boundaries;
    use Comparison;
    use Converter;
    use Creator;
    use Difference;
    use Macro;
    use Modifiers;
    use Mutability;
    use Options;
    use Rounding;
    use Serialization;
    use Test;
    use Timestamp;
    use Units;
    use Week;
 
    /**
     * Names of days of the week.
     *
     * @var array
     */
    protected static $days = [
Arguments
"Trait 'Carbon\Traits\Comparison' not found"
```

Carbon version: **1.39.0**

PHP version: **7.3.3**

I expected to get:

```
No Error
```

But I actually get:

```
Symfony \ Component \ Debug \ Exception \ FatalErrorException (E_UNKNOWN)
Trait 'Carbon\Traits\Comparison' not found
```

Thanks!

**Comment by kylekatarnls** [comment]
Hi, the composer install seems broken, please remove vendor/nesbot/carbon and re-install it with `composer install` or `composer update`

**Comment by kylekatarnls** [comment]
Tell me if it does not solve the problem and I will re-open.

**Comment by bhargav960143** [comment]
```
"nesbot/carbon": "^1.39",
```

Same issue replicate.

**Comment by bhargav960143** [comment]
> ell me if it does not solve the problem and I will re-open.

Not solved.

**Comment by kylekatarnls** [comment]
There is a conflict on bin/upgrade-carbon as mentioned by composer. And the composer command should not end with "Killed".

I think you tried to upgrade and it only partially worked. Remove the whole `vendor` directory and re-install.

**Comment by kylekatarnls** [comment]
If removing vendor directory did not solve it, please provide more input so I can reproduce it. Ideally a minimum composer.json I can copy, then the command I should run to get the error.

Let me know and I will re-open.

**Comment by bhargav960143** [comment]
```
{
    "name": "envaysoft/fleetcart",
    "description": "The FleetCart E-Commerce System.",
    "type": "project",
    "authors": [
        {
            "name": "Martin Smith",
            "email": "martin@mailinator.com"
        }
    ],
    "require": {
        "php": ">=7.1.3",
        "fideloper/proxy": "^4.0",
        "floatingpoint/stylist": "^0.5",
        "fzaninotto/faker": "~1.4",
        "jackiedo/dotenv-editor": "^1.0",
        "laravel/framework": "5.7.*",
        "laravel/tinker": "^1.0",
        "nesbot/carbon": "^1.26.3",
        "nwidart/laravel-modules": "^3.0",
        "spatie/laravel-activitylog": "^3.2",
        "swayok/alternative-laravel-cache": "^5.4",
        "symfony/config": "^4.3",
        "symfony/intl": "^4.1",
        "symfony/yaml": "^4.3",
        "wikimedia/composer-merge-plugin": "^1.4"
    },
    "require-dev": {
        "barryvdh/laravel-debugbar": "^3.0",
        "beyondcode/laravel-dump-server": "^1.0",
        "beyondcode/laravel-query-detector": "^1.0",
        "composer/composer": "^1.8",
        "filp/whoops": "^2.0",
        "nunomaduro/collision": "^2.0"
    },
    "autoload": {
        "psr-4": {
            "FleetCart\\": "app/",
            "Modules\\": "Modules/",
            "Themes\\": "Themes/"
        }
    },
    "scripts": {
        "post-root-package-install": [
            "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-autoload-dump": [
            "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
            "@php artisan package:discover"
        ],
        "post-install-cmd": [
            "Illuminate\\Foundation\\ComposerScripts::postInstall"
        ],
        "post-update-cmd": [
            "Illuminate\\Foundation\\ComposerScripts::postUpdate"
        ]
    },
    "config": {
        "optimize-autoloader": true,
        "sort-packages": true,
        "preferred-install": "dist",
        "platform": {
            "php": "7.1.3"
        }
    },
    "extra": {
        "laravel": {
            "dont-discover": [
                "nwidart/laravel-modules"
            ]
        },
        "branch-alias": {
            "dev-master": "1.0.x-dev"
        },
        "merge-plugin": {
            "require": [
                "Modules/*/composer.json",
                "Themes/*/composer.json"
            ],
            "merge-extra": true,
            "merge-extra-deep": true,
            "merge-scripts": true
        }
    }
}

```

**Comment by kylekatarnls** [comment]
> and the command I should run to get the error

As you did not give it to me, I tried `composer install` and it works fine.

Note that as you have nwidart/laravel-modules at version 3, you're locked at Carbon 5.6 and so you can't upgrade to Carbon 2, both are no longer actively supported, so you should first update nwidart/laravel-modules to ^5 (cannot be handled automatically by the upgrade script) and laravel/framework to 5.8.*, then just remove nesbot/carbon from your dependencies and run `composer update`, it will install Carbon by default.

**Comment by bhargav960143** [comment]
> > and the command I should run to get the error
> 
> As you did not give it to me, I tried `composer install` and it works fine.
> 
> Note that as you have nwidart/laravel-modules at version 3, and you're locked at Laravel 5.7 and so you can't upgrade to Carbon 2, both are no longer actively supported, so you should first update nwidart/laravel-modules to ^5 (cannot be handled automatically by the upgrade script) and laravel/framework to 5.8.*, then just remove nesbot/carbon from your dependencies and run `composer update`, it will install Carbon by default.

Yes you are right issue with nwidart/laravel-modules, thanks for the update already working towards solving this issue.

I will update you after all this update done.

Appreciated your (@kylekatarnls ) efforts for quick replay in a single day.

**Comment by kylekatarnls** [comment]
I note you also have an config.platform.php setting to 7.1.3, Carbon 2 needs at least 7.1.8, pleas consider updating your environments to at least 7.1.8 (you should better have the last patch: 7.1.30) and you also should consider upgrading PHP: https://www.php.net/supported-versions.php

**Comment by bhargav960143** [comment]
> I note you also have an config.platform.php setting to 7.1.3, Carbon 2 needs at least 7.1.8, please consider updating your environments to at least 7.1.8 (you should better have the last patch: 7.1.30) and you also should consider upgrading PHP: https://www.php.net/supported-versions.php

Sure, Thanks man.

**Comment by DeadBillah0** [comment]
Fatal error: Trait "Carbon\Traits\Date" not found in C:\xampp\htdocs\mecom\vendo
r\nesbot\carbon\src\Carbon\Carbon.php on line 510




how to solved it?

**Comment by kylekatarnls** [comment]
I suggest you remove the vendor directory and re-install (with composer) your dependencies, then be sure your app load the vendor/autoload.php created by composer on bootstrap.
