### ISSUE TITLE
Chinese zh_* Translation "From Now"

### ISSUE THREAD

**Issue by danvim** [briannesbitt/Carbon#1782]
Hello,

I encountered an issue with the following code:
```php
echo (new Carbon\Carbon())->addDay(50)->diffForHumans();
```

Carbon version: **2.20**

PHP version: **7.3**

I wish to start a discussion regarding the translation in file zh_TW:

https://github.com/briannesbitt/Carbon/blob/master/src/Carbon/Lang/zh_TW.php#L44

This line contains: `'from_now' => ':time內',`

I expected to get:

```
2個月內
```

But I actually get:

```
1個月內
```

The English "1 month from now" seems appropriate, but from my understanding, the Chinese "1個月內" means "within 1 month", which conflicts with the idea of "50 days away from today".

"1個月後" meaning "after 1 month" might seem more appropriate?

Thanks!

**Comment by kylekatarnls** [comment]
Hi @danvim the calculation and rounding will not change from one locale to an other, we have 823 locales, it would unmaintainable.

By default, we use the biggest unit possible and floor the value, here it means we count full monts:

```php
echo Carbon::now()->addMonths(2)->subSecond()->diffForHumans(); // 1 month from now
echo "\n";
echo Carbon::now()->addMonths(2)->addSecond()->diffForHumans(); // 2 months from now
```

But you can use more precise diff having multiple units:

```php
echo Carbon::now()->addDays(50)->diffForHumans(['parts' => 3]); // 1 month 2 weeks 4 days from now
echo "\n";
echo Carbon::now()->addMonths(2)->addSecond()->locale('zh_TW')->diffForHumans(['parts' => 3]); // 2個月內
```

Thanks!

**Comment by kylekatarnls** [comment]
And also note than if you compare 2 dates, `after` is used instead of `from_now`:

```php
echo Carbon::now()->addMonths(2)->addSecond()->locale('zh_TW')->diffForHumans(Carbon::now(), ['parts' => 3]); // 1個月 2週 4天後
```
```php
echo Carbon::now()->addMonths(2)->addSecond()->locale('zh_TW')->diffForHumans(Carbon::now()); // 1個月後
```

**Comment by danvim** [comment]
@kylekatarnls Thanks for replying. I'm fully aware of what you are saying. The reason I bring this up is to open this discussion to improve the translation. I have no intention of modifying the code base. However, I couldn't think of a proper way to phrase the exact situation in Chinese. Therefore, I'm asking if anyone else seeing this issue could think of a better translation.

If you ask me, I still think this issue can be open for discussion though.

**Comment by kylekatarnls** [comment]
Hi @danvim, @williamyang233 suggested `后` in #1816

Do you think it should apply to zh_TW? And other zh_*?

**Comment by danvim** [comment]
@kylekatarnls `后` is Simplified Chinese, whereas `後` is Traditional Chinese. The Traditional Chinese form should be applied to zh_Hant* and the Simplified form to zh_Hans*. As I have suggested in my original question `xx后`/`xx後` means `after xx`.

I think it is at least better than the one that is in the current translation. The only thing is the Chinese translation would be the same for the actual "after" translation as well.

Well, I can't think of any better translation so `xx后`/`xx後` will do I guess.

**Comment by kylekatarnls** [comment]
OK, thanks @danvim it seems no one had much better to propose so we will go for the same translation of after and from_now. Thanks for your help.

**Comment by danvim** [comment]
@kylekatarnls I'm sorry I missed. The zh_HK translation should also use the Traditional Chinese form. 🙇 

In fact, the original `'after'` translation was using the wrong form as well. It should be:

zh_HK.php

```php
//...
    'from_now' => ':time後',
    'after' => ':time後',
//...
```

https://github.com/kylekatarnls/Carbon/blob/551e5dc50d230fb91a67be8ceacee83578e5ec3c/src/Carbon/Lang/zh_HK.php#L44

**Comment by kylekatarnls** [comment]
This would be a major and global change (not only for after/from_now) as right now the whole zh_HK uses the same as zh_Hans. Do we should get the same translations for zh_HK and zh_Hant for all keys?

**Comment by danvim** [comment]
@kylekatarnls Hong Kong uses traditional Chinese. So it would basically use what Taiwan zh_TW is using without any doubt. So whichever has more keys: Hant or TW, HK should be using those instead of CN or Hans.

**Comment by kylekatarnls** [comment]
OK, thanks I created a new issue for this: #1824
