### ISSUE TITLE
Invalid end-of-week date if translated from immutable to mutable

### ISSUE THREAD

**Issue by MrAjax** [briannesbitt/Carbon#1793]
Hello,

I encountered an issue with the following code:
```php
$date = CarbonImmutable::parse('2019-07-01');
echo $date->toMutable()->endOfWeek();
```

Carbon version: **2.17.1**

PHP version: **7.2.11**

I expected to get:

```
2019-07-07 23:59:59.999999 Europe/Moscow (+03:00)
```

But I actually get:

```
2019-07-06 23:59:59.999999 Europe/Moscow (+03:00)
```

Thanks!

**Comment by kylekatarnls** [comment]
As explained in the documentation: https://carbon.nesbot.com/docs/#api-week

Week consideration depends on the locale:
[Start of week world map](https://fr.wikipedia.org/wiki/Fichier:First_Day_of_Week_World_Map.svg)

So you need to specify a locale:
```php
$date = CarbonImmutable::parse('2019-07-01');
echo $date->toMutable()->locale('ru_RU')->endOfWeek();
// Or set globally CarbonImmutable::setLocale('ru_RU')
```
