### ISSUE TITLE
[Translation tool] ca

### ISSUE THREAD

**Issue by jmquarck** [briannesbitt/Carbon#1802]
|English|ca|comments|
|--|--|--|
|2 hours from now|d'aquí 2 hores|d'aquí a 2 hores|

**Comment by jmquarck** [comment]
In Catalan, the preposition **"a"** must be included before the number of hours.

**Comment by kylekatarnls** [comment]
Hi @jmquarck, could you tell me if it applies all units (year, month, week, day, hours, minutes and seconds) or if this preposition can vary?

**Comment by kylekatarnls** [comment]
@Quenty31, @v0ctor, @jmquarck, this seems to be needed for all units but wouldn't be better to simply use `en 2 hores`?

**Comment by Quenty31** [comment]
It would be a calque to Spanish.
As we say it without the preposition "a" in Occitan it should be correct to in Catalan although not the more frequent form.

**Comment by jmquarck** [comment]
> Hi @jmquarck, could you tell me if it applies all units (year, month, week, day, hours, minutes and seconds) or if this preposition can vary?

Yes, it applies to all units.

**Comment by jmquarck** [comment]
> @Quenty31, @v0ctor, @jmquarck, this seems to be needed for all units but wouldn't be better to simply use `en 2 hores`?

Sure, but it is not what people would say. Should the space available in the UI be scarce, Catalan speakers would understand an expression like _en 2 dies_, though it sounds unfamiliar, like translated by an AI.

**Comment by kylekatarnls** [comment]
So I will change it for `d'aquí a`. Release of this will be in 2.22 (beginning of August), if anyone has an objection, please tell.

**Comment by Quenty31** [comment]
D’aquí a, sounds better to be than "en" because it's not the same idea.
En 2 horas, would be to say "I did it in 2h", where "d’aquí" would mean «in 2h from now»
