### ISSUE TITLE
[Translation tool] sv

### ISSUE THREAD

**Issue by litemerafrukt** [briannesbitt/Carbon#1803]
|English|sv|comments|
|--|--|--|
|2d|2 d.|I think this should be "dgr" instead of just "d" but it could be that "d" as an abbreviation for "dagar" is how people are starting to write it because "dgr" only give you to less from the full form. "dagar" is not often abbreviated in Swedish.|
|2h|2 t.|This should rather be 2 h. or 2 tim. I cant recall that I have seen timmar (hours) be shortened to "t" in Swedish. It usually is shortened as "h" (as in English, from the latin word) or as "tim". Some googling confirmed this references as wikipedia and språkbruket (https://www.sprakbruk.fi/-/sprakfra-10) and more. "h" as short for "timmar" is used in more technical contexts where as "tim" is probably what you would want here.|

----
The dot after the abbreviations mån, v, d, t, min and s, is optional and I think it is more common to write them without the dot.

**Comment by kylekatarnls** [comment]
Hi,

Thanks for your contribution, I will fix that as soon as possible.

**Comment by kylekatarnls** [comment]
Will be available in 2.22
