### ISSUE TITLE
[Translation tool] pl

### ISSUE THREAD

**Issue by adobrucki** [briannesbitt/Carbon#1811]
|English|pl|comments|
|--|--|--|
|a month|1 miesiąc|This should rather be just 'miesiąc' because it means an month in singular. '1 miesiąc' means rather one month|
|a week|1 tydzień|tydzień (same reason as above)|
|an hour|1 godzina|godzina (same reason as above)|
|a minute|1 minuta|minuta (same reason as above)|

**Comment by kylekatarnls** [comment]
Hi @adobrucki, do we should apply it to rok and dzień?
