### ISSUE TITLE
Handle PHP changes in static closure binding

### ISSUE THREAD

**Issue by kylekatarnls** [briannesbitt/Carbon#1814]
PHP 8 will disallow to unbind `$this` from a closure. To avoid a fatal error, for now we let the binding on static macros if it exists. It means we can no longer use safely `isset($this)` to detect rather a macro is called statically or dynamically from inside a macro if it's ran on PHP 8. For now on Laravel, this simply throws a fatal error.

This can wait until PHP 8 stabilize its specifications, release a first alpha then discuss with Laravel team to adopt a common approach.

**Comment by kylekatarnls** [comment]
For now (as long as it's just a deprecation), we can be compatible PHP 7.4/8 by muting the deprecation with `@`

The most prudent option for mixin/macro owner is to progressively migrate to traits.

Carbon 2.23 will have a better support of mixins as traits.

Then if PHP 8.x or 9 completely removes the unbinding possibility, those traits could be used in sub-classes that extend Carbon/CarbonInterval/CarbonPeriod.

**Comment by kylekatarnls** [comment]
I still get very useful feedback from Laravel and think we'll find a common way to handle it:
https://github.com/laravel/framework/issues/29411

**Comment by kylekatarnls** [comment]
One more PHP 8 problem: https://bugs.php.net/bug.php?id=78401&thanks=4

**Comment by kylekatarnls** [comment]
https://github.com/php/php-src/pull/4548 could allow us to continue to use macros/mixins in next PHP versions.

**Comment by driesvints** [comment]
The new PHP build reverts the unbinding behavior.
