### ISSUE TITLE
[Translation tool] fa

### ISSUE THREAD

**Issue by hpez** [briannesbitt/Carbon#1815]
## To be fixed by #1817:

|English|fa|comments|
|--|--|--|
|2 years|2 سال|۲ سال|
|2yrs|2 سال|۲ سال|
|1 year|1 سال|۱ سال|
|2 months|2 ماه|۲ ماه|
|2mos|2 ماه|۲ ماه|
|1 month|1 ماه|۱ ماه|
|2 weeks|2 هفته|۲ هفته|
|2w|2 هفته|۲ هفته|
|1 week|1 هفته|۱ هفته|
|2 days|2 روز|۲ روز|
|2d|2 روز|۲ روز|
|1 day|1 روز|۲ روز|
|2 hours|2 ساعت|۲ ساعت|
|2h|2 ساعت|۲ ساعت|
|1 hour|1 ساعت|۱ ساعت|
|2 minutes|2 دقیقه|۲ دقیقه|
|2m|2 دقیقه|۲ دقیقه|
|1 minute|1 دقیقه|۱ دقیقه|
|2s|2 ثانیه|۲ ثانیه|
|1 second|1 ثانیه|۱ ثانیه|

----
Numbers should all be persian numbers as I have corrected among a few minor issues

----

## To be fixed in translations

|English|fa|comments|
|--|--|--|
|an hour|یک دقیقهیک ساعت|یک ساعت|
|2 seconds|چند ثانیه|۲ ثانیه|
|a few seconds|1 ثانیه|چند ثانیه|
|2 hours ago|2 ساعت پیش|۲ ساعت پیش|
|2 hours from now|در 2 ساعت|۲ ساعت دیگر|
|2 hours before|2 ساعت پیش از|۲ ساعت پیش از|
|2 hours after|2 ساعت پس از|۲ ساعت پس از|

**Comment by kylekatarnls** [comment]
Thanks @hpez, currently we can only handle custom number either globally or nowhere. So I have to know if it's also correct to use persian numbers in year: is `۲۰۱۹` better than `2019` and the same for day of the month or any numbers what Carbon would output translated in `fa` locale?

**Comment by hpez** [comment]
Yes it is correct for using it anywhere in fa locale.

**Comment by kylekatarnls** [comment]
I just check and persian numbers are already properly output in years and days of month. This is a general issue, alternative numbers (for all languages using them) are not displayed in translated duration strings. I will open a dedicated issue.

**Comment by kylekatarnls** [comment]
Hi, so I split the fix related to #1817 and the pure translation fixes. For the from_now/ago/before/after, I will need more input as we need the complete rule for all units and quantities.

I also need to know if the current translations are wrong or just a bit less accurate to decide if it worth to change them.

Right now, static wording is used:
https://github.com/briannesbitt/Carbon/blob/master/src/Carbon/Lang/fa.php#L43

But custom rules can be handled using closure:
https://github.com/briannesbitt/Carbon/blob/master/src/Carbon/Lang/ru.php#L67
https://github.com/briannesbitt/Carbon/blob/master/src/Carbon/Lang/tk_TM.php#L64
https://github.com/briannesbitt/Carbon/blob/master/src/Carbon/Lang/ka.php#L48

**Comment by hpez** [comment]
There are rather small but I think necessary fixes to the fa locale file which I made a pull request for regarding this issue.

**Comment by kylekatarnls** [comment]
Thanks!

**Comment by kylekatarnls** [comment]
Finally the current behavior will be kept as it seems in many language where we support alternative numbers, the digits `0..9` can be used. And for some languages where it could be relevant, we simply don't have the list of digits and rules in our translation files.

So with 2.23.0, you will be able to get duration translated strings (`forHumans`, `diffForHumans`, `ago`, `fromNow` etc.) with alternative numbers using:
```php
->forHumans(['altNumbers' => true]); // for all locales
->forHumans(['altNumbers' => 'fa']); // for fa* locales
->forHumans(['altNumbers' => ['fa', 'ja']]); // for fa* and ja* locales
```
