### ISSUE TITLE
[Translation tool] zh

### ISSUE THREAD

**Issue by williamyang233** [briannesbitt/Carbon#1816]
|English|zh|comments|
|--|--|--|
|2 hours from now|距现在2小时|2小时后|

**Comment by kylekatarnls** [comment]
Hi @williamyang233, can you tell me if the current form is wrong `距现在2小时` or just less accurate. Then can you confirm `内` is generic enough for all situations: all units, all quantities, all expressions that would indicate something happen in the future like:

> We will lunch in 2 hours from now
> Meeting date: 1 day from now
> Next Star Wars episode is in 4 months from now
> etc.

**Comment by williamyang233** [comment]
`距现在2小时`may less accurate in lots of Chinese situations. `from now` always equal to `later` in China. But we never say 'from now'.
For example, we don't say `我们将在距现在两小时吃午饭(We will lunch in 2 hours from now)` but say ‘我们将在2小时'后'吃午饭’.

**Comment by kylekatarnls** [comment]
OK, thank you. So could you confirm `后` as a suffix to the duration text will be OK for all types of duration (from seconds to years, no matter the quantity and/or if it's a composite interval like `1 day 2 hours and 30 minutes`)?

**Comment by williamyang233** [comment]
Yes!

**Comment by kylekatarnls** [comment]
Thanks. A last thing, I see now we have same word for after and from now, then same word for before and ago. Is there any possible way to differentiate both?

```
We will lunch **in 2 hours from now**
We will lunch **2 hours after** the meeting
```

after/before is to compare 2 dates (there is no past/future implication, only a relative comparison)
from now/ago is to compare a date to now (present instant).

**Comment by williamyang233** [comment]
Just like Default Value. When there is not comparison, we default to the now as a reference. This is a fixed language expression habit. Actually, 'later/after/from now' are both translated to '后', but we can distinguish by different context.

**Comment by kylekatarnls** [comment]
Thanks. Released in https://github.com/briannesbitt/Carbon/releases/tag/2.22.0-beta.3
