### ISSUE TITLE
Unexpected diffInDays behaviour?

### ISSUE THREAD

**Issue by forrestedw** [briannesbitt/Carbon#1819]
Hello,

I encountered an issue with the following code:
```php
        $now = new Carbon('2019-07-29 14:02:53');

        $then = new Carbon('2019-07-27 14:02:54');

        $diffInDays = $then->diffInDays($now);

        $isYesterday = $then->isYesterday();
```

Carbon version: 2.21.2

PHP version: 7.2.12

I expected to get:

```
        dump($diffInDays); // 2

        dump($isYesterday); // false
```

But I actually get:

```
        dump($diffInDays); // 1

        dump($isYesterday); // false
```

herokuapp not working.

You can see that I have set the time difference to be just one second off exactly two days. Maybe this is the intended behaviour, for it to only ever round down, never round up. Apologies if this is the case. 

But it confused me, as I assumed that something _so_ close to two days would come back as two days.

Thanks!

**Comment by kylekatarnls** [comment]
Hi,

You can use alternatively: https://try-carbon-lib.herokuapp.com/

This is intended behavior, even 1 microseconds would be enough, diffInDays is a floor result. If you want a rounded result you can use: `round($then->floatDiffInDays($now))`

You probably understand that it's not the library responsibility to decide what is close enough to be rounded (1 second/1 minutes/1 hour, it would be arbitrary and leads to bugs in many situations).

Thanks,
