### ISSUE TITLE
not working as expected with `json_encode()`

### ISSUE THREAD

**Issue by icylace** [briannesbitt/Carbon#182]
I thought that a Carbon date object would automatically convert into a datetime string when using `json_encode()` on it.  It doesn't because it needs to implement the `JsonSerializable` interface to make it work.  I don't see an advantage to JSON-encoding the Carbon object itself rather than its standard string form.

**Comment by briannesbitt** [comment]
The plan is to drop 5.3 support since its end of life.  Then we would add the JsonSerializable implementation along with a 2.0 release.
