### ISSUE TITLE
diffForHumans    2019-12-30    2019-07-30     says 4 months later

### ISSUE THREAD

**Issue by PatrickCaneloDigital** [briannesbitt/Carbon#1820]
Hello,

I encountered an issue with the following code:
```php
Duration: {{\Illuminate\Support\Carbon::createFromFormat('Y-m-d','2019-12-30')->diffForHumans(\Illuminate\Support\Carbon::createFromFormat('Y-m-d','2019-07-24'))}}<br>
                    Left:  {{\Illuminate\Support\Carbon::createFromFormat('Y-m-d','2019-12-30')->diffForHumans(\Illuminate\Support\Carbon::now())}}
// now is 2019-07-30 17:39:00
```

Carbon version: **name     : nesbot/carbon
versions :  2.18.0**

PHP version: **PHP 7.2.9 (cli) (built: Aug 21 2018 07:42:00) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.9, Copyright (c) 1999-2018, by Zend Technologies
    with Xdebug v2.6.1, Copyright (c) 2002-2018, by Derick Rethans**

I expected to get:

```
Duration: 2019-12-30 2019-07-24 5 months later
Remaining: 2019-12-30 2019-07-30 17:39:00 5 months later
```

But I actually get:

```
Duration: 2019-12-30 2019-07-24 5 months later
Remaining: 2019-12-30 2019-07-30 17:39:00 4 months later
```

I very much assume that it is a timezone issue, where the now date makes the diff slightly under 5 months and thus displaying 4 months.
BUT: As it is specifically diffForHumans I would assume that, very much as the human does roundings, the diff would make roundings too and saying 5 months... or at least 4 months and 30 days... But 4 months is confusing...

Thanks!

**Comment by kylekatarnls** [comment]
Hi,

This is not a timezone problem, you compare a date that have no time (so it's midnight) to a date that have time. So today will be only some hours in your interval:

Use `->startOfDay()` to get midnight from a date or use `Carbon::today()` instead of now:
```php
echo Carbon::createFromFormat('Y-m-d','2019-12-30')->diffForHumans(Carbon::today());
```

If you 2 more precision on interval, you should specify the `'parts'` option:
```php
echo Carbon::createFromFormat('Y-m-d','2019-12-30')->diffForHumans(Carbon::now(), ['parts' => 2]);
```

Thanks.
