### ISSUE TITLE
Chinese fix default Traditional/Simplified variant by region

### ISSUE THREAD

**Issue by kylekatarnls** [briannesbitt/Carbon#1824]
Check and fix for each `zh` region if it should use Traditional or Simplified Chinese by default.

Right now (because of how it has been built initially) zh_Hant alias zh_TW and zh_Hans alias zh_HK.

We should first put the common translation in zh_Hant and zh_Hans that should not extend any other file. Then regional variants should extend one or the other of those two bases.

As I have no Chinese knowledge, help is very welcome here.

**Comment by danvim** [comment]
From my personal knowledge and judging from the lang code names:

| code | form |
|---|---|
| zh_CN.php | Simplified | 
| zh_HK.php  | Traditional | 
| zh_Hans.php  | Simplified | 
| zh_Hans_HK.php  | Simplified | 
| zh_Hans_MO.php  | Simplified | 
| zh_Hans_SG.php  | Simplified | 
| zh_Hant.php  | Traditional | 
| zh_Hant_HK.php  | Traditional | 
| zh_Hant_MO.php  | Traditional | 
| zh_MO.php  | Traditional | 
| zh_SG.php  | Simplified | 
| zh_TW.php  | Traditional | 
| zh_YUE.php | Traditional? (Non-standard? But Wikipedia's zh-yue uses traditional) |

**Comment by kylekatarnls** [comment]
Thanks a lot. I will check line by line in translations what belongs to hans or hant.

**Comment by kylekatarnls** [comment]
Will be fixed in 2.24 via #1824, discussion to be continued in the pull-request.
