### ISSUE TITLE
locale('en') uses locale specified by setLocale()

### ISSUE THREAD

**Issue by stidges** [briannesbitt/Carbon#1831]
Hello,

I encountered an issue with the following code:
```php
Carbon::setLocale('nl');
echo Carbon::now()->locale('en')->isoFormat('dddd D MMMM');
```

Carbon version: **2.22.0**
PHP version: **7.2.20**

Reproduction link: https://try-carbon.herokuapp.com/?embed&theme=xcode&border=silver&options-color=rgba(120,120,120,0.5)&input=Carbon%3A%3AsetLocale(%27nl%27)%3B%0Aecho%20Carbon%3A%3Anow()-%3Elocale(%27en%27)-%3EisoFormat(%27dddd%20D%20MMMM%27)%3B

I expected to get:

```
"Tuesday 6 August"
```

But I actually get:

```
"dinsdag 6 augustus"
```

**Context:** I'm running a Laravel app that has the default locale set to `'nl'`. This causes `Carbon::setLocale('nl')` to be called. In a test case I'm trying to ensure that some dates are correctly localized for a user, by using the `locale('en')` method provided by Carbon. This method seems to work correctly for all locales except `'en'`, where it will fallback to the locale specified in `setLocale()`. If I explicitly use a specific sub-locale (e.g. `'en_US'`) it does work as expected.

Thanks!

**Comment by kylekatarnls** [comment]
Hi @stidges, it's a big concern. I make this my top priority. Thanks for the report.

**Comment by kylekatarnls** [comment]
I'm testing a fix #1832, if all is fine I will release a patch **2.22.1** with just this fix.

**Comment by kylekatarnls** [comment]
Patch released: [2.22.1](https://github.com/briannesbitt/Carbon/releases/tag/2.22.1)

**Comment by stidges** [comment]
Awesome, thank you for the quick fix and release @kylekatarnls!!

**Comment by stidges** [comment]
@kylekatarnls I just pulled this in and tried it, and I'm still seeing the same bug unfortunately on version 2.22.2. I did a bit of digging and it seems that the `Translator` class is showing some incorrect behavior:

```php
Carbon::setLocale('nl');
echo Translator::get('en')->getLocale();
// Expected: "en"
//   Actual: "nl"
```
[Sandbox code](https://try-carbon.herokuapp.com/?embed&theme=xcode&border=silver&options-color=rgba(120,120,120,0.5)&input=Carbon%3A%3AsetLocale(%27nl%27)%3B%0Aecho%20Translator%3A%3Aget(%27en%27)-%3EgetLocale()%3B)

After calling `Carbon::setLocale('en')` everything goes back to working as expected.

**Comment by stidges** [comment]
@kylekatarnls I found the issue, in version 2.22.2 the fix you made in the Translator class is missing for some reason, it is included in 2.22.1 though, maybe it got overwritten or something (I compared by downloading the zips from the releases page)

**Comment by kylekatarnls** [comment]
Hi, sorry for that, I used the 2.21 branch instead. Here is the new patch: 2.22.3

**Comment by stidges** [comment]
Everything is working great now, thanks again!
