### ISSUE TITLE
Running composer update breaks Lumen

### ISSUE THREAD

**Issue by Ekman** [briannesbitt/Carbon#1834]
Hello,

We're using Lumen for our applications and in the last 1-1.5 months running `composer update` breaks our application. Our applications are heavily tested, both unit- and integration tests, and identical code breaks after updating composer. Note that we're not using Carbon (directly) in our code, it's solely being used by Lumen, nor have we updated our version ranges in `composer.json`, this breaking change has been introduced in a minor or patch version.

Carbon version: 2.22.1

PHP version: 7.3.7

This is a stack trace of our issue:

```json
{
    "class": "Symfony\\Component\\Debug\\Exception\\FatalThrowableError",
    "message": "Call to undefined method Laravel\\Lumen\\Application::getLocale()",
    "code": 0,
    "file": "/home/app/app/vendor/nesbot/carbon/src/Carbon/Laravel/ServiceProvider.php",
    "line": 32,
    "stacktrace": {
        "#0": "/home/app/app/vendor/nesbot/carbon/src/Carbon/Laravel/ServiceProvider.php(14): Carbon\\Laravel\\ServiceProvider->updateLocale()",
        "#1": "[internal function]: Carbon\\Laravel\\ServiceProvider->boot()",
        "#2": "/home/app/app/vendor/illuminate/container/BoundMethod.php(32): call_user_func_array(Array, Array)",
        "#3": "/home/app/app/vendor/illuminate/container/BoundMethod.php(90): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()",
        "#4": "/home/app/app/vendor/illuminate/container/BoundMethod.php(34): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Laravel\\Lumen\\Application), Array, Object(Closure))",
        "#5": "/home/app/app/vendor/illuminate/container/Container.php(576): Illuminate\\Container\\BoundMethod::call(Object(Laravel\\Lumen\\Application), Array, Array, NULL)",
        "#6": "/home/app/app/vendor/laravel/lumen-framework/src/Application.php(244): Illuminate\\Container\\Container->call(Array)",
        "#7": "/home/app/app/vendor/laravel/lumen-framework/src/Application.php(229): Laravel\\Lumen\\Application->bootProvider(Object(Stockfiller\\CustomerService\\ServiceProviders\\AppServiceProvider))",
        "#8": "[internal function]: Laravel\\Lumen\\Application->Laravel\\Lumen\\{closure}(Object(Stockfiller\\CustomerService\\ServiceProviders\\AppServiceProvider), 'Stockfiller\\\\Cus...')",
        "#9": "/home/app/app/vendor/laravel/lumen-framework/src/Application.php(230): array_walk(Array, Object(Closure))",
        "#10": "/home/app/app/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(159): Laravel\\Lumen\\Application->boot()",
        "#11": "/home/app/app/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(108): Laravel\\Lumen\\Application->dispatch(NULL)",
        "#12": "/home/app/app/public/index.php(27): Laravel\\Lumen\\Application->run()",
        "#13": "{main}"
    },
    "previousException": null
}
```

Do you have any idea how we can fix this?

Thanks!

**Comment by Ekman** [comment]
I should probably add that we're using version 5.8.12 of Lumen and downgrading Carbon works as a temporary solution: `composer require nesbot/carbon:2.20.*`

**Comment by kylekatarnls** [comment]
Hi, I just created a fresh Lumen app 5.8.12. Carbon 2.22.1 has been installed with no trouble and works fine.

I'm inspecting.

**Comment by kylekatarnls** [comment]
Maybe you could produce a ZIP to reproduce the bug?

**Comment by kylekatarnls** [comment]
As you get it working with 2.20.0 the probable cause is: https://github.com/briannesbitt/Carbon/commit/4654d12f4f760f5175940c1fea2d5d9054379d9b#diff-c6d3363924b18196b6980b9cc6f5665fR14

**Comment by Ekman** [comment]
Thanks for the quick response, I'll see if I can produce a ZIP.

I'm trying to find anything that we might've missed in a upgrade guide of Lumen. Something that would make `Application` not have those methods.

**Comment by kylekatarnls** [comment]
Hi, could you try to require `"nesbot/carbon": "dev-lumen"` to see if the error's gone.

**Comment by Ekman** [comment]
That fixes it! :)

Do you know if Lumens `Application` object is supposed to have the translation methods? I'd want to fix our installation if something is wrong with it.

**Comment by kylekatarnls** [comment]
I know in a previous version Lumen was synchronized: when locale changed, Carbon locale changed too. I will release this fix for 2.22.2 and will work on the compatibility of this feature for 2.23.0.

**Comment by Ekman** [comment]
OK, thank you so much for the speedy response and fix.

**Comment by kylekatarnls** [comment]
It seems that Lumen no longer trigger an event on locale change. So we will probably not be able to restore the automatic synchronization.
