### ISSUE TITLE
[Translation tool] fi

### ISSUE THREAD

**Issue by powergrip** [briannesbitt/Carbon#1837]
|English|fi|comments|
|--|--|--|
|2m|2 min|2 minuuttia|
|a few seconds|1 sekunti|muutama sekunti|
|2 hours from now|2 tuntia tästä hetkestä|2 tunnin päästä|

**Comment by kylekatarnls** [comment]
Hi @powergrip, we have v, kk, vk, pv, t and s to shorten units, is there any understandable way to shorten minuutti while all other are shown in the short form?

**Comment by kylekatarnls** [comment]
Could you also confirm than `päästä` fit for any kind of time in the future:

Build will finnish **in 45 seconds**
We'll lunch **in 2 hours**
We'll move **in 3 months and 2 weeks**
I'll retire in **in 5 years**

**Comment by powergrip** [comment]
min is shortened version of minuutti

**Comment by powergrip** [comment]
> Could you also confirm than `päästä` fit for any kind of time in the future:
> 
> Build will finnish **in 45 seconds**
> We'll lunch **in 2 hours**
> We'll move **in 3 months and 2 weeks**
> I'll retire in **in 5 years**

CONFIRMED

**Comment by kylekatarnls** [comment]
Thanks so the fix in #1839 will be OK.
