### ISSUE TITLE
[Translation tool] lv

### ISSUE THREAD

**Issue by zakse** [briannesbitt/Carbon#1842]
|English|lv|comments|
|--|--|--|
|2 years|2 gadiem|2 gadi / because "2 gadiem" is more like "for 2 year"|
|2yrs|2 gadiem|2 gadi / because "2 gadiem" is more like "for 2 year"|
|1 year|1 gada|1 gads / because there is not such "gada"|
|a year|1 gada|gads /  because there is not such "gada"|
|2 months|2 mēnešiem|2 mēneši / because it is correct|
|2mos|2 mēnešiem|2 mēn. / because it is correct|
|1 month|1 mēneša|1 mēnesis / because this is correct|
|a month|1 mēneša|mēnesis / because this is correct|
|2 weeks|2 nedēļām|2 nedēļas
2 nedēļas|
|2w|2 nedēļām|2 ned.|
|1 week|1 nedēļas|1 nedēļa|
|a week|1 nedēļas|nedēļa|
|2 days|2 dienām|2 dienas|
|2d|2 dienām|2 dienas|
|1 day|1 dienas|1 diena|
|a day|1 dienas|diena|
|2 hours|2 stundām|2 stundas|
|2h|2 stundām|1 st.|
|1 hour|1 stundas|1 stunda|
|an hour|1 stundas|stunda|
|2 minutes|2 minūtēm|divas minūtes|
|2m|2 minūtēm|2 min. |
|1 minute|1 minūtes|viena minūte|
|a minute|1 minūtes|minūte|
|2 seconds|2 sekundēm|2 sekundes|
|2s|2 sekundēm|2 sek.|
|1 second|1 sekundes|viena sekunde|
|a few seconds|1 sekundes|dažas sekundes|

**Comment by kylekatarnls** [comment]
Hi, thanks for your help,

To be considered: for now `lv` has the following translations:
```php
    'ago' => 'pirms :time',
    'from_now' => 'pēc :time',
    'after' => ':time vēlāk',
    'before' => ':time pirms',
```

"2 gadi" is used for:
```
pirms 2 gadi
pēc 2 gadi
2 gadi vēlāk
2 gadi pirms
```

Does this need to be different for "2 gadi" alone and when it's in such sentences?

If yes, what is the exact rule (so I can write it in PHP)?

Thank you.
