### ISSUE TITLE
startOfCentury not working correctly

### ISSUE THREAD

**Issue by Hesesses** [briannesbitt/Carbon#1843]
Hello,

I encountered an issue with the following code:
```php
$value = "31122000";
$dt = Carbon::createFromFormat('dmY', $value); // 2000-12-31 13:45:57.0 UTC (+00:00)
$century = $dt->startOfCentury(); // 1901-01-01 00:00:00.0 UTC (+00:00)
```

Carbon version: * 2.19.1

PHP version: 7.2

I expected to get:

```
2000-01-01 00:00:00.0 UTC (+00:00)
```

But I actually get:

```
1901-01-01 00:00:00.0 UTC (+00:00)
```

Thanks!

**Comment by kylekatarnls** [comment]
Hello,

Centuries are counted according to strict Gregorian point of view. And as the year 0 does not exist in the Gregorian calendar (year 1 immediately follows year -1), so first 100 years are from 1 to 100 included, second century is 101 to 200, etc.

See here strict usage vs general usage:
https://en.wikipedia.org/wiki/Century

What you want can be done like this:

```php
echo $dt->startOfYear()->year(floor($date->year / 100) * 100);
```

Hope it works for you.

**Comment by Hesesses** [comment]
Thank you for clarifying
