### ISSUE TITLE
Extracting dates from text document

### ISSUE THREAD

**Issue by daita** [briannesbitt/Carbon#1844]
Cannot find anything in documentation about an existing feature

I am looking for a way to extract dates (in any usable format) from a complete text document.

As an example, the document can be a mail:
```
Subject: meeting tomorrow

Let's have a meeting tomorrow at 14:00 to talk about this feature.
```

I was wondering if something like this can be implemented within Carbon, or by using Carbon in a way or another.

**Comment by kylekatarnls** [comment]
`Carbon::parse('tomorrow 14:00')` give you the right date. So you know have to parse your text with the right regex: `preg_match_all('/meeting\s+(?<date>\S+)\s+(at\s+)?(?<time>\d{1,2}(:\d{1,2})?)/')`

Example:
```php
$message = "Subject: meeting tomorrow

Let's have a meeting tomorrow at 14:00 to talk about this feature.";

$count = preg_match_all('/meeting\s+(?\S+)\s+(at\s+)?(?\d{1,2}(:\d{1,2})?)/', $message, $mettings, PREG_SET_ORDER);

echo "The message contains $count meetings\n\n";

foreach ($mettings as ['date' => $date, 'time' => $time]) {
  $date = Carbon::parse("$date $time");
  echo $date->format(" - m/d g:ia\n");
}
```
