### ISSUE TITLE
Where can I find Carbon version 1 documentation? Can't get month full name.

### ISSUE THREAD

**Issue by guizoxxv** [briannesbitt/Carbon#1845]
Hello,

I encountered an issue with the following code:
```php
echo Carbon::parse('2018-06-01')->format('MMMM');
```

Carbon version: 1.25.0

PHP version: 7.2.11

I expected to get:

```
June
```

But I actually get:

```
JunJunJunJun
```

I believe that the problem is that the format *MMMM* used to get full month name is from Carbon version 2 but I'm unable to find the old documentations. Where are they?

Thanks!

**Comment by kylekatarnls** [comment]
Hello,

`MMMM` is indeed only for the `isoFormat()` in Carbon 2 and it can give you the month in any language.

`format()` can give you the full month name in English only and is a native method of `DateTime` so the documentation is here: https://www.php.net/manual/en/datetime.format.php

```php
echo Carbon::parse('2018-06-01')->format('F');
```

Thanks,

**Comment by guizoxxv** [comment]
Thank you. It worked. But where can I find the version 1 documentation?

**Comment by kylekatarnls** [comment]
Version 1 is deprecated and documentation is always only last version but if you double-click on a method you can open the API reference panel and it will tell you for each method at which version it appears and changes of parameters.
