### ISSUE TITLE
[Translation tool] zh_CN

### ISSUE THREAD

**Issue by insunshine** [briannesbitt/Carbon#1850]
|English|zh_CN|comments|
|--|--|--|
|Mo|一|This should rather be '星期一' or '周一' because Th means Thursday, but '一' just mean one，and similarly for the others.|

**Comment by kylekatarnls** [comment]
Hi @insunshine does this mean it should be same words for long and short forms of day names? Is there is any way of mentioning week days in a shorter way in Chinese that can be commonly understood?

**Comment by insunshine** [comment]
> Hi @insunshine does this mean it should be same words for long and short forms of day names? Is there is any way of mentioning week days in a shorter way in Chinese that can be commonly understood?

I think "周一" means that Monday is the shortest word.

**Comment by kylekatarnls** [comment]
I have to think about different case it could be actually used.

Moment.js use the same:
https://github.com/moment/moment/blob/develop/src/locale/zh-cn.js#L13

And the same for glibc:
```
"日";"一";"二";"三";"四";"五";"六"
```

Can the calendar below be understood in Chinese?

|日|一|二|三|四|五|六|
|-|-|-|-|-|-|-|
||||||1|2|
|3|4|5|6|7|8|9|
|10|11|12|13|14|15|16|
|17|18|19|20|21|22|23|
|24|25|26|27|28|||

**Comment by insunshine** [comment]
Haha, watching the calendar every day actually forgets that the calendar is so displayed.

> I have to think about different cases it could be actually used.
> 
> Moment.js use the same:
> https://github.com/moment/moment/blob/develop/src/locale/zh-cn.js#L13
> 
> And the same for glibc:
> 
> ```
> "日";"一";"二";"三";"四";"五";"六"
> ```
> 
> Can the calendar below be understood in Chinese?
> 
> 日	一	二	三	四	五	六
> 1	2
> 3	4	5	6	7	8	9
> 10	11	12	13	14	15	16
> 17	18	19	20	21	22	23
> 24	25	26	27	28

Haha, watching the calendar every day actually forgets that the calendar is so displayed.
