### ISSUE TITLE
javascript timestamp to createFromTimestamp error

### ISSUE THREAD

**Issue by testingatswt** [briannesbitt/Carbon#1853]
Hello,

I encountered an issue with the following code:
```php
echo Carbon::createFromTimestamp(1566041250628)->toDateTimeString();
```
Timestamp is creating from javascript's `Date.now()`
tested on [Carbon docs live editor](https://carbon.nesbot.com/docs/)

I expected to get:

```
2019-08-17 16:27:30
```

But I actually get:

```
51595-11-15 10:30:28
```

Thanks!

**Comment by kylekatarnls** [comment]
Hi,

JS timestamps are milliseconds, while PHP timestamps are seconds, so you need to use:
```php
echo Carbon::createFromTimestampMS(1566041250628)->toDateTimeString();
```

Thanks.
