### ISSUE TITLE
method isSameDay doesn't exist

### ISSUE THREAD

**Issue by lu3do** [briannesbitt/Carbon#1856]
Hello,

I encountered an issue with the following code:
```php
$date_created = '2019-08-19';
$last_run = '2019-08-20';
var_dump(Carbon::parse($date_created)->isSameDay($last_run));
```

Carbon version: 2.23.1

PHP version: 7.2.21

I expected to get:

```
false
```

But I actually get:

```
Error: Method isSameDay does not exist.
```
same issue on the herokuapp btw.

Also for some reason when I ran `composer update nesbot/carbon` it actually downgraded from 2.5.3 to 2.23.1 ??
```
~:$ composer update nesbot/carbon
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 0 installs, 1 update, 0 removals
  - Updating nesbot/carbon (2.5.3 => 2.23.1) Downloading: 100%
```

**Comment by kylekatarnls** [comment]
The error is wrong indeed, in fact isSameDay expect `DateTimeInterface`:

```php
$date_created = '2019-08-19';
$last_run = '2019-08-20';
var_dump(Carbon::parse($date_created)->isSameDay(Carbon::parse($last_run)));
```

We could probably support strings here. I will check that.

**Comment by lu3do** [comment]
Ah ok, yea the error threw me off a bit, didn't even try to use a `DateTimeInterface` as argument there because it looked like the method wasn't even available on the  `Carbon::parse($date_created)`

thanks.

**Comment by kylekatarnls** [comment]
#1859 merged, `Carbon::parse('2019-08-19')->isSameDay('2019-08-19')` will be `true` in version **2.24.0**.
