### ISSUE TITLE
weekNumberInMonth return 0

### ISSUE THREAD

**Issue by fengliang2011** [briannesbitt/Carbon#1879]
what does mean of "weekNumberInMonth return 0"?

Version: 1.39.0

**Comment by kylekatarnls** [comment]
It's a bug fixed in 2.0.0 (released in August last year).

The version 1.x is no longer supported. So we won't fix it ourselves but if you propose a fix on the branch [version-1.39](https://github.com/briannesbitt/Carbon/tree/version-1.39) we would consider merging it for a patch version.
