### ISSUE TITLE
[Translation tool] fa

### ISSUE THREAD

**Issue by rezacr588** [briannesbitt/Carbon#1881]
## Additional fixes
pls make numbers persian

**Comment by kylekatarnls** [comment]
Thanks for your checking.

Alternative numbers are supported (but optional):

Code | Example | Description
-- | -- | --
OD | 5 | Day number with alternative numbers such as 三 for 3 if locale is ja_JP
OM | 1 | Month number with alternative numbers such as ၀၂ for 2 if locale is my_MM
OY | 2017 | Year number with alternative numbers such as ۱۹۹۸ for 1998 if locale is fa
OH | 17 | 24-hours number with alternative numbers such as ႑႓ for 13 if locale is shn_MM
Oh | 5 | 12-hours number with alternative numbers such as 十一 for 11 if locale is lzh_TW
Om | 4 | Minute number with alternative numbers such as ୫୭ for 57 if locale is or
Os | 5 | Second number with alternative numbers such as 十五 for 15 if locale is ja_JP

Those format are used when relevant in the given language in macro-formats like LLLL, LTS, etc.

And it's also available in duration:
```php
echo Carbon::now()->subMonths(2)->locale('fa')->diffForHumans(['altNumbers' => true]);
```
