### ISSUE TITLE
[Translation tool] id_ID

### ISSUE THREAD

**Issue by dheariarachman** [briannesbitt/Carbon#1884]
|English|id_ID|comments|
|--|--|--|
|2yrs|2thn|2 thn|
|2mos|2bln|2 bln|
|2w|2mgg|2 mgg|
|2d|2hr|2 hr|

**Comment by kylekatarnls** [comment]
Hi @dheariarachman, thanks for your checking. I was wondering if it would not be weird to have thn/bin/mgg/hr with a space, and j/mnt/dt without space?

**Comment by kylekatarnls** [comment]
If someone can give me more feedback on this I will re-open. For now I close as I don't have the required knowledge to analyze if thn/bin/mgg/hr can have a different spacing than j/mnt/dt.
