### ISSUE TITLE
isTomorrow - unexpected behaviour with CarbonImmutable

### ISSUE THREAD

**Issue by kotfire** [briannesbitt/Carbon#1885]
Hello,

I encountered an issue with the following code:
```php
Carbon::setTestNow(Carbon::create(2019, 1, 1, 10));

$immutableTomorrow = CarbonImmutable::create(2019, 1, 2, 20);

var_dump($immutableTomorrow->isTomorrow());
```

Carbon version: 2.24.0

PHP version: 7.3.9

[Link to the editor reproducing the error](https://try-carbon.herokuapp.com/?embed&theme=xcode&border=silver&options-color=rgba(120,120,120,0.5)&input=%2F%2F%20Working%20as%20expected%0A%0Aecho%20%27Working%20as%20expected%27%3B%0Aecho%20%22%5Cn%22%3B%0A%0A%2F%2F%20Both%20mutable%0ACarbon%3A%3AsetTestNow(Carbon%3A%3Acreate(2019%2C%201%2C%201%2C%2010))%3B%0A%0A%24mutableTomorrow%20%3D%20Carbon%3A%3Acreate(2019%2C%201%2C%202%2C%2020)%3B%0A%0Aecho%20%22%5Cn%22%3B%0Aecho%20%27Both%20mutable%27%3B%0Aecho%20%22%5Cn%22%3B%0Avar_dump(%24mutableTomorrow-%3EisTomorrow())%3B%0A%0A%2F%2F%20Now%20immutable%20and%20tomorrow%20mutable%0ACarbon%3A%3AsetTestNow(CarbonImmutable%3A%3Acreate(2019%2C%201%2C%201%2C%2010))%3B%0A%0A%24mutableTomorrow%20%3D%20Carbon%3A%3Acreate(2019%2C%201%2C%202%2C%2020)%3B%0A%0Aecho%20%22%5Cn%22%3B%0Aecho%20%27Now%20immutable%20and%20tomorrow%20mutable%27%3B%0Aecho%20%22%5Cn%22%3B%0Avar_dump(%24mutableTomorrow-%3EisTomorrow())%3B%0A%0A%2F%2F%20Unexpected%20behaviour%0A%0Aecho%20%22%5Cn%22%3B%0Aecho%20%27Unexpected%20behaviour%27%3B%0Aecho%20%22%5Cn%22%3B%0A%0A%2F%2F%20Now%20mutable%20and%20tomorrow%20immutable%0ACarbon%3A%3AsetTestNow(Carbon%3A%3Acreate(2019%2C%201%2C%201%2C%2010))%3B%0A%0A%24immutableTomorrow%20%3D%20CarbonImmutable%3A%3Acreate(2019%2C%201%2C%202%2C%2020)%3B%0A%0Aecho%20%22%5Cn%22%3B%0Aecho%20%27Now%20mutable%20and%20tomorrow%20immutable%27%3B%0Aecho%20%22%5Cn%22%3B%0Avar_dump(%24immutableTomorrow-%3EisTomorrow())%3B%0A%0A%2F%2F%20Both%20immutable%0ACarbon%3A%3AsetTestNow(CarbonImmutable%3A%3Acreate(2019%2C%201%2C%201%2C%2010))%3B%0A%0A%24immutableTomorrow%20%3D%20CarbonImmutable%3A%3Acreate(2019%2C%201%2C%202%2C%2020)%3B%0A%0Aecho%20%22%5Cn%22%3B%0Aecho%20%27Both%20immutable%27%3B%0Aecho%20%22%5Cn%22%3B%0Avar_dump(%24immutableTomorrow-%3EisTomorrow())%3B)

>I have included the same code but using a mutable object that works as expected.

I expected to get:

```php
bool(true)
```

But I actually get:

```php
bool(false)
```

Thanks!

**Comment by kylekatarnls** [comment]
Hi,

Each `CarbonImmutable` and `Carbon` can be set individually:

```php
CarbonImmutable::setTestNow(CarbonImmutable::create(2019, 1, 1, 10));
```
