### ISSUE TITLE
possible to add years and months format for multi-languages?

### ISSUE THREAD

**Issue by spencerchang** [briannesbitt/Carbon#1888]
I notice the default format like 'L','LL','LLL','LLLL' are awesome to handle multi-languages website. But I have a further request is that the (MMM YYYY) and (MMMM YYYY) are usually using for many sites and default custom sequence format for different languages will be useful.
For example:
In English the format is (Jan 2019) and (January 2019).
In Japanese the format is (2019 Jan) and (2019 January).
In Chinese the format is (2019 Jan) and (2019 January).

Any possible to add (MMM YYYY) and (MMMM YYYY) with custom sequence format for each language?
Much Thanks.

**Comment by kylekatarnls** [comment]
Some informations we ask in our issue template are missing, to get support and provide readable issues for later viewers, please fill the template and give at least:

- [ ] the Carbon version you use;
- [ ] the PHP version you use;
- [x] the output you expect.

Thanks.

**Comment by kylekatarnls** [comment]
A macro can do the job:
```php
\Carbon\Translator::get('en')->setTranslations([
  'long-month-year' => 'MMMM YYYY',
  'short-month-year' => 'MMM YYYY',
]);
\Carbon\Translator::get('ja')->setTranslations([
  'long-month-year' => 'YYYY MMMM',
  'short-month-year' => 'YYYY MMM',
]);
\Carbon\Translator::get('zh')->setTranslations([
  'long-month-year' => 'YYYY MMMM',
  'short-month-year' => 'YYYY MMM',
]);

Carbon::macro('longMonthYear', function () {
  return $this->isoFormat($this->translate('long-month-year'));
});

Carbon::macro('shortMonthYear', function () {
  return $this->isoFormat($this->translate('short-month-year'));
});


echo Carbon::now()->locale('en')->longMonthYear()."\n";
echo Carbon::now()->locale('ja')->longMonthYear()."\n";
echo Carbon::now()->locale('zh')->longMonthYear()."\n";

echo "\n";

echo Carbon::now()->locale('en')->shortMonthYear()."\n";
echo Carbon::now()->locale('ja')->shortMonthYear()."\n";
echo Carbon::now()->locale('zh')->shortMonthYear()."\n";
```
