### ISSUE TITLE
[Translation tool] be_BY

### ISSUE THREAD

**Issue by AbadonnaAbbys** [briannesbitt/Carbon#1889]
|English|be_BY|comments|
|--|--|--|
|a year|1 год|год|
|a month|1 месяц|месяц|
|a week|1 тыдзень|тыдзень|
|2 days|2 ні|2 дні|
|2d|2 ні|2 дні|
|a day|1 дзень|дзень|
|1 hour|1 гадзіну|1 гадзіна|
|an hour|1 гадзіну|гадзіна|
|1 minute|1 хвіліну|1 хвіліна|
|a minute|1 хвіліну|хвіліна|
|1 second|1 секунду|1 секунда|
|a few seconds|1 секунду|некалькі секунд|

**Comment by kylekatarnls** [comment]
Thanks for you help. I will check this soon.

**Comment by kylekatarnls** [comment]
Thanks, it will be fixed in 2.25.
