### ISSUE TITLE
Issue modify time on Daylight Saving Time (DST)

### ISSUE THREAD

**Issue by ggvunh** [briannesbitt/Carbon#1890]
Hello,

I encountered an issue with the following code on end day light saving at UK timezone, this is my function convert to startOfHour:
```php
    public function getStartHour($timestamp)
    {
        $carbonDate = Carbon::createFromTimestamp($timestamp, 'Europe/London');
        $startHour = $carbonDate->startOfHour()->timestamp;
        return $startHour;
    }
   
   // Case 1:
   // Sunday October 27, 2019 00:00:00 (am) GMT
   // Sunday October 27, 2019 01:00:00 (am) (Timezone + 1 , On daylight saving)
   $time = $this->getStartHour(1572134400); // 1572138000 (Issue here)
   //My expected: 1572134400

   // Case 2:
   // Sunday October 27, 2019 00:30:00 (am) GMT
   // Sunday October 27, 2019 01:30:00 (am) (Timezone + 1 , On daylight saving)
   $time = $this->getStartHour(1572136200); // 1572138000 (Issue here)
   //My expected: 1572134400

   // Case 3:
   // Sunday October 27, 2019 01:00:00 (am) UCT
   // Sunday October 27, 2019 01:00:00 (am) UK (Timezone + 0)
   $time = $this->getStartHour(1572138000); // 1572138000 - 01:00:00 (Ok)

   // Case 4:
   // Sunday October 27, 2019 01:30:00 (am) UTC
   // Sunday October 27, 2019 01:00:00 (am) (Timezone + 0)
   $time = $this->getStartHour(1572139800); // 1572138000 - 10:00:00 (Ok)
```
4 case these return same result (1572138000). It not right on the real case.
Carbon version: **1.31.0**

PHP version: **5.6.11**

I expected to get:

```
Case 1: 1572134400
Case 2: 1572134400
```

But I actually get:

```
Case 1: 1572138000
Case 2: 1572138000
```

Please give me the idea to fix this.
P/s: I tried to on MomentJs (Java script) with these case and it return right my expected.
Thanks!

**Comment by kylekatarnls** [comment]
Hi, first the tool used (timestamp) is probably not the right to use. Timestamp is a number of seconds since 1970-01-01 00:00:00 UTC. Considering a timestamp relative to any other moment (including other timezones) will lead to code difficult to maintain. Plus, timestamp does not support DST since DST cheats with elapsed seconds.

So if you want timestamp as input and output, then, simply don't use Carbon in your function:
```php
    public function getStartHour($timestamp)
    {
        return $timestamp - ($timestamp % 3600);
    }
```
