### ISSUE TITLE
[Translation tool] sk_SK

### ISSUE THREAD

**Issue by Plasto13** [briannesbitt/Carbon#1891]
|English|sk_SK|comments|
|--|--|--|
|Monday|pondelok|Pondelok|
|Tuesday|utorok|Utorok|
|Wednesday|streda|Streda|
|Thursday|štvrtok|Štvrtok|
|Friday|piatok|Piatok|
|Saturday|sobota|Sobota|
|Sunday|nedeľa|Nedeľa|
|January|január|Január|
|Jan|jan|Jan|
|February|február|Február|
|Feb|feb|Feb|
|March|marec|Marec|
|Mar|mar|Mar|
|April|apríl|Apríl|
|Apr|apr|Apr|
|May|máj|Máj|
|May|máj|Máj|
|June|jún|Jún|
|Jun|jún|Jún|
|July|júl|Júl|
|Jul|júl|Júl|
|August|august|August|
|Aug|aug|Aug|
|September|september|September|
|Sep|sep|Sep|
|October|október|Október|
|Oct|okt|Okt|
|November|november|November|
|Nov|nov|Nov|
|December|december|December|
|Dec|dec|Dec|

**Comment by kylekatarnls** [comment]
Hi @Plasto13, thanks for your contribution. The capitalization of months and days name is an English rule. But it seems Slovak language does not have such rule:
https://translate.google.com/#view=home&op=translate&sl=en&tl=sk&text=See%20you%20Monday

<details>
<summary>
See the warning in https://carbon.nesbot.com/contribute/translate/
</summary>
> Warning, do not uppercase the first letter if it's not required, days/months are always uppercase in English, so "Monday" is written this way even in a sentence like "See you Monday", please translate the following as if it could be in the middle of such sentences. Short versions are used in short date formats and minimalist days are used calendar headings and such custom usages.
</details>

If you want to capitalize it no matter the language, you can use [ucfirst](https://www.php.net/manual/en/function.ucfirst.php)

If you're sure months and days names should be capitalized in Slovak, please provide some references mentioning the rule.

Thanks.
