### ISSUE TITLE
Not able to user hasFormat with the format 'd/m/Y'

### ISSUE THREAD

**Issue by spacedog4** [briannesbitt/Carbon#1896]
Hello,

I encountered an issue with the following code:
```php
var_dump(Carbon::hasFormat($value, 'd/m/Y'))
```

Carbon version: 2.23.1

PHP version: 7.2

I expected to get: true

```
6
```

But I actually get: this error preg_match(): Unknown modifier '('

tracking the code I discovered that Carbon is testing the date with this regex "/^(3[01]|[12][0-9]|0[1-9])/(1[012]|0[1-9])/([1-9]?[0-9]{4})$/" that is wrong, the bars should be "\\/"

```
5
```

Thanks!

**Comment by kylekatarnls** [comment]
It will be fixed in 2.25: https://github.com/briannesbitt/Carbon/issues/1886 You can try to install: 2.25.0-beta.2.
