### ISSUE TITLE
[Translation tool] hr_BA

### ISSUE THREAD

**Issue by DarkoDevelop** [briannesbitt/Carbon#1902]
|English|hr_BA|comments|
|--|--|--|
|2 years|2 years|This should rather be 2 godine because we say so.|
|2yrs|2yrs|This should rather be 2g because we say so.|
|1 year|1 year|This should rather be 1 godina because we say so.|
|a year|a year|This should rather be godina because we say so.|
|2 months|2 months|This should rather be 2 mjeseca because we say so.|
|2mos|2mos|This should rather be 2mj because we say so.|
|1 month|1 month|This should rather be 1 mjesec because we say so.|
|a month|a month|This should rather be mjesec because we say so.|
|2 weeks|2 weeks|This should rather be 2 tjedna because we say so.|
|2w|2w|This should rather be 2tj because we say so.|
|1 week|1 week|This should rather be 1 tjedan because we say so.|
|a week|a week|This should rather be tjedan because we say so.|
|2 days|2 days|This should rather be 2 dana because we say so.|
|2d|2d|This should rather be 2d because we say so.|
|1 day|1 day|This should rather be 1 dan because we say so.|
|a day|a day|This should rather be dan because we say so.|
|2 hours|2 hours|This should rather be 2 sata because we say so.|
|2h|2h|This should rather be 2h because we say so.|
|1 hour|1 hour|This should rather be 1 sat because we say so.|
|an hour|an hour|This should rather be sat because we say so.|
|2 minutes|2 minutes|This should rather be 2 minute because we say so.|
|2m|2m|This should rather be 2min because we say so.|
|1 minute|1 minute|This should rather be 1 minuta because we say so.|
|a minute|a minute|This should rather be minuta because we say so.|
|2 seconds|2 seconds|This should rather be 2 sekunde because we say so.|
|2s|2s|This should rather be 2s because we say so.|
|1 second|1 second|This should rather be 1 sekunda because we say so.|
|a few seconds|a few seconds|This should rather be nekoliko sekundi because we say so.|
|2 hours ago|2 hours ago|prije 2 sata|
|2 hours from now|2 hours from now|2 sata od sada|
|2 hours before|2 hours before|2 sata prije|
|2 hours after|2 hours after|2 sata poslije|

**Comment by kylekatarnls** [comment]
Hi @DarkoDevelop. Thanks for your finding. Indeed hr_BA inherit en language instead of hr language. I will fix this and release a patch.

**Comment by kylekatarnls** [comment]
You can update to [2.25.1](https://github.com/briannesbitt/Carbon/releases/tag/2.25.1)
