### ISSUE TITLE
Carbon::parse timestamp issue

### ISSUE THREAD

**Issue by SFLAQiu** [briannesbitt/Carbon#1905]
**Describe the bug**

why Carbon::parse timestamp set timezone no role？

**To Reproduce**
```php
var_export(date_default_timezone_get());
var_export(Carbon::parse(time(), date_default_timezone_get())->timezone);
var_export(Carbon::parse(time())->timezone(date_default_timezone_get())->timezone);

var_export(Carbon::parse(time(), date_default_timezone_get())->format('Y-m-d H:i:s'));
var_export(Carbon::parse(time())->timezone(date_default_timezone_get())->format('Y-m-d H:i:s'));
```

1. Go to run
2. See log
```
'Asia/Shanghai'

Carbon\CarbonTimeZone::__set_state(array(
   'timezone_type' => 1,
   'timezone' => '+00:00',
))

Carbon\CarbonTimeZone::__set_state(array(
   'timezone_type' => 3,
   'timezone' => 'Asia/Shanghai',
))

'2019-10-08 10:36:29'
'2019-10-08 18:36:29'

```

**Expected behavior**
normal understanding should be used 'timezone' => 'Asia/Shanghai' output

use "nesbot/carbon": "^2.23",

**Comment by kylekatarnls** [comment]
According to https://en.wikipedia.org/wiki/Timestamp
Unix time is:
> the number of seconds since 00:00:00 UTC on January 1, 1970

There is "UTC" in the definition. This makes it fair to consider "normal understanding" is considering timestamps as UTC moments and so would require a manuel timezone change to be converted to timezoned moments.

It's what native PHP DateTime do too:
```php
date_default_timezone_set('Asia/Shanghai');

echo (new DateTime('@'.time()))->format('Y-m-d H:i:s e'); // 2019-10-09 09:31:17 +00:00
```

`new DateTime()` gives you now if Shangai, while `new DateTime('@'.time())` gives you now UTC.

PHP do it on purpose in my opinion. Changing this behavior would be a breaking change: it could break a lot of application relying on this behavior.

So we could reconsider this if when starting to work on Carbon 3 (not planned for now) but I'm not sure it's a so good idea.

And as for changing it as a minor release of Carbon 2, I disapprove at a first sight.

What we can imagine is a dedicated tool (shortcut for `Carbon::parse($time)->timezone(date_default_timezone_get()`) For now you can use a macro:

```php
Carbon::macro('fromTimestamp', static function (int $time) {
  return Carbon::parse($time)->timezone(date_default_timezone_get());
});

echo Carbon::fromTimestamp(time())->format('Y-m-d H:i:s e');
```

**Comment by SFLAQiu** [comment]
Thank you for your patience，Macro is a good ideal，But Carbon users maby  can’t know DateTime parsing timestamps use UTC，The expectation is that you can optimize to avoid this problem

**Comment by kylekatarnls** [comment]
Please precise: how could it be optimized without breaking the current behavior for users relying on timestamps giving UTC dates?

**Comment by SFLAQiu** [comment]
I know what you mean，no good way， you can add annotation remind users

Finally I found that could call Carbon::createFromTimestamp ，Is in accordance with the date_default_timezone 

```php
var_export(date_default_timezone_get());
var_export(Carbon::createFromTimestamp(time())->format('Y-m-d H:i:s'));
var_export((new DateTime())->setTimestamp(time())->format('Y-m-d H:i:s'));
```

**Comment by kylekatarnls** [comment]
Glad you have what you need. A last note: user timezone should be used for final output only (to display it to a user), but any app handling dates can and should use UTC as default timezone internally.

I explained here in details the benefit of it:

https://medium.com/@kylekatarnls/always-use-utc-dates-and-times-8a8200ca3164
https://medium.com/@kylekatarnls/handle-dates-the-right-way-in-php-c215650fc4fa

**Comment by SFLAQiu** [comment]
Thanks again for your patience
