### ISSUE TITLE
[Translation tool] sh

### ISSUE THREAD

**Issue by mikki021** [briannesbitt/Carbon#1910]
|English|sh|comments|
|--|--|--|
|2 seconds|2 sekunda|2 sekunde because 'sekunde' is plural of 'sekund'|
|2s|2 sekunda|2 sekunde because 'sekunde' is plural of 'sekund'|

**Comment by kylekatarnls** [comment]
Thanks for your help.

**Comment by kylekatarnls** [comment]
Released in 2.25.2.
