### ISSUE TITLE
📖 Document translation

### ISSUE THREAD

**Issue by dongasai** [briannesbitt/Carbon#1919]
Hello:
    As described in the  in the title, do you plan to translate the documents of the project? Or do you have MD version of the documents of the project? I plan to translate the documents into other languages, because the English version is not convenient for me to read

**Comment by dongasai** [comment]
Please forgive me for being tired of HTML format documents, because the useless HTML tags and CSS content are not easy to modify and source reading, so I decided to make an MD version of the document source code.

**Comment by dongasai** [comment]
https://github.com/dongasai/Carbon_doc  Here, you can watch its progress

**Comment by kylekatarnls** [comment]
I'm completely in favor of a markdown documentation. I used it already for my other project https://phug-lang.com

An we surely could find a way to convert existing HTML source files into markdown then create HTML compiled files directly from makrdown. At least for the main page to begin.

**Comment by dongasai** [comment]
[transifex](https://www.transifex.com/carbon/public/) This tool is expected to be used for translation

**Comment by dongasai** [comment]
The setup work for [transifex](https://www.transifex.com/carbon/public/)  has been completed, it links to [Carbon_doc](https://github.com/dongasai/Carbon_doc), maybe we can get up and do the translation work

**Comment by dongasai** [comment]
I used the logo of the [website](https://carbon.nesbot.com/) in the [translation project](https://www.transifex.com/carbon/public/). If there is any infringement, please inform me and I will modify it

**Comment by dongasai** [comment]
https://dongasai.github.io/Carbon_doc/#/
This is a site built using github pages, he is awesome
@kylekatarnls @lucasmichot @briannesbitt 
I hope that the focus of the project's documentation can be on this git repository.you can fork or join

**Comment by kylekatarnls** [comment]
Awesome! Yes I will try to find a way to synchronize changes.

**Comment by dongasai** [comment]
I think this better method is:
1. Synchronize existing documents to the target repository
2. Newly generated documents are generated in the new warehouse

**Comment by dongasai** [comment]
I have completed the transfer of existing documents

**Comment by dongasai** [comment]
ding

**Comment by kylekatarnls** [comment]
This does not seem ready to be published: https://dongasai.github.io/Carbon_doc/#/zh_CN/

But if there is significant part of the documentation available in Chinese, I would add a link on https://carbon.nesbot.com/ to go to the Chinese page.
