### ISSUE TITLE
Diff in seconds goes wildly wrong with exact date/times but difference in microseconds

### ISSUE THREAD

**Issue by wucdbm** [briannesbitt/Carbon#1924]
Hello,

I encountered an issue with the following code:
```php
$start = Carbon::parse('2019-11-03 00:53:08.204051');
$end = Carbon::parse('2019-11-05 00:53:08.000000');
$diff = $start->diffInHours($end);
var_dump($diff); // 71
// Expected: 47
// Actual: 71
// Reason: DateInterval's days property does NOT account for microseconds
// Solution: Use DateInterval's d property instead ?
```

```php
// From
$diff = $this->diff($this->resolveCarbon($date));
        $value = $diff->days * static::HOURS_PER_DAY * static::MINUTES_PER_HOUR * static::SECONDS_PER_MINUTE +
            $diff->h * static::MINUTES_PER_HOUR * static::SECONDS_PER_MINUTE +
            $diff->i * static::SECONDS_PER_MINUTE +
            $diff->s;
```

```php
// To
$diff = $this->diff($this->resolveCarbon($date));
        $value = $diff->d * static::HOURS_PER_DAY * static::MINUTES_PER_HOUR * static::SECONDS_PER_MINUTE +
            $diff->h * static::MINUTES_PER_HOUR * static::SECONDS_PER_MINUTE +
            $diff->i * static::SECONDS_PER_MINUTE +
            $diff->s;
```

Carbon version: 1.25.3

PHP version: PHP 7.3.11-1+ubuntu18.04.1+deb.sury.org+1 (cli) (built: Oct 24 2019 18:23:23) ( NTS )

Unfortunately, upgrade from that version is impossible:
```
$ composer depends nesbot/carbon
laravel/framework  v5.6.39  requires  nesbot/carbon (1.25.*) 
```

I expected to get:

```
47 hours diff
```

But I actually get:

```
71 hours diff
```

https://pasteboard.co/IERoDBy.png
https://pasteboard.co/IERoLywX.png
https://pasteboard.co/IERoRxj.png
https://pasteboard.co/IERoY3v.png

I have no clue whether this is fixed in a later version of Carbon. I stumbled upon this while working on a laravel project. I am quite unfamiliar with both Laravel and Carbon.

I just had to dig deep enough while chasing a bizarre bug.

Main question here is, why use `\DateInterval::days`, rather than `\DateInterval::d`?

**Comment by kylekatarnls** [comment]
Hi, Carbon v1 is no longer supported and so is Laravel 5.6 (end of life 2018-08-07). And as the behavior is correct (47) with the current version of Carbon 2, without other argument, I won't modify this behavior for the v1.

> upgrade from that version is impossible

Not impossible, it just requires either to upgrade to Laravel 5.8 or greater or to follow the steps mentioned in the main page of the documentation about using a composer version alias:
https://carbon.nesbot.com/

Thanks,

**Comment by wucdbm** [comment]
Fair enough. Upgrading Laravel is unfortunately not something I get to decide on.

Thank you very much for pointing the alias thing out, I'll give it a try!
