### ISSUE TITLE
Urdu language missing

### ISSUE THREAD

**Issue by talhahai** [briannesbitt/Carbon#1931]
Hello,

I encountered an issue with the following code:
```php
echo Carbon::parse('2018-06-01')->subDay()->month;
```

Carbon version: **PUT HERE YOUR CARBON VERSION (exact version, not the range)**

PHP version: **PUT HERE YOUR PHP VERSION**

I expected to get:

```
6
```

But I actually get:

```
5
```

Thanks!

**Comment by kylekatarnls** [comment]
For the record, Urdu is not missing, they are `ur` locale, `ur_IN` and `ur_PK`.
