### ISSUE TITLE
[CLDR] Korean month and week translation

### ISSUE THREAD

**Issue by kylekatarnls** [briannesbitt/Carbon#1953]
Dear @ukits, @appkr and all Korean users and contributors, I found differences between CLDR translations and Carbon translations:

| ID | English | CLDR | Carbon |
|---|---|---|---|
| 1 | 99 months ago | 99개월 전 | 99달 전 |
| 2 | in 99 months| 99개월 후 | 99달 후 |
| 3 | 99 weeks ago | 99주 전 | 99주일 전 |
| 4 | in 99 weeks | 99주 후 | 99주일 후 |

Could you please tell me for each ID in this list if Carbon translation is OK or if CLDR translation would be better?

Thanks,

**Comment by appkr** [comment]
Hi Kyle,


No difference in meaning though, I would choose:
1 Carbon
2 Carbon
3 CLDR
4 CLDR


The reason behind the selection was the `git log` presented in Korean.
$ git log
cc5f7eeab 10주 전 hymesh PP-642 ***
9b579bfd0 3달 전 hymesh PP-642 ***


Always thank you for your effort to maintain a great open source project.
Happy Christmas!
 
appkr (Juwon Kim)

2019년 12월 7일 오후 9:33에 Kyle <notifications@github.com> 작성:



Dear @ukits, @appkr and all Korean users and contributors, I found differences between CLDR translations and Carbon translations:

ID	English	CLDR	Carbon
1	99 months ago	99개월 전	99달 전
2	in 99 months	99개월 후	99달 후
3	99 weeks ago	99주 전	99주일 전
4	in 99 weeks	99주 후	99주일 후

Could you please tell me for each ID in this list if Carbon translation is OK or if CLDR translation would be better?

Thanks,

**Comment by trauma2u** [comment]
CLDR translation looks better than Carbon's :)

**Comment by progh2** [comment]
CLDR better~

**Comment by youngiggy** [comment]
"달" and "개월" are both possible expressions. "달" means "one period divided by twelve years," and "개월" means "unit for counting months." - National Institute of Korean Language

Natural to feel in everyday conversation with humans
1~4 CLDR

For compulsive engineers :) (Looking good / Easy to recognize with other units such as "년", "월", "일", "주" )
1, 2 Carbon
3, 4 CLDR

**Comment by kylekatarnls** [comment]
Thanks! This will be updated in 2.8.0.
