### ISSUE TITLE
[CLDR] Armenian from_now translation

### ISSUE THREAD

**Issue by kylekatarnls** [briannesbitt/Carbon#1954]
Dear @mhamlet and all Armenian users and contributors, I found differences between CLDR translations and Carbon translations:

| English | CLDR | Carbon |
|---|---|---|
| in 9 days | 9 օրից | 9 օր ներկա պահից |

"in" meaning "in the future".

Could you please tell me if Carbon translation is OK or if CLDR translation would be better?

Thanks,

**Comment by mhamlet** [comment]
Hi @kylekatarnls.

Carbon translation (9 օր ներկա պահից) literally means "9 days from this moment"

So CLDR translation is more accurate.

**Comment by kylekatarnls** [comment]
Thanks! It will be fixed in 2.8.0.
