### ISSUE TITLE
Carbon returns current date if variable is a single alphabetic character. Carbon::parse("M")

### ISSUE THREAD

**Issue by omordach** [briannesbitt/Carbon#1960]
Hello,

I encountered an issue with the following code:
```php
echo Carbon::parse("M");
```

Carbon version: **2.27.0**

PHP version: **7.3.11**

I expected to get:

```
Error: DateTime::__construct(): Failed to parse time string (M)
```

But I actually get:

```
2019-12-13 09:35:36 - current date and time
```

Thanks!

**Comment by kylekatarnls** [comment]
Hello,

This is by design in PHP:
```php
var_dump(new DateTime("M"));
```

It creates a date with current moment in "M" timezone:
https://www.timeanddate.com/time/zones/m

**Comment by omordach** [comment]
:astonished: :astonished: :astonished: 

> It creates a date with current moment in "M" timezone:
https://www.timeanddate.com/time/zones/m

That makes sense. Thank you for explanation.
