### ISSUE TITLE
Parse string with timezone ignores tz parameter

### ISSUE THREAD

**Issue by stebogit** [briannesbitt/Carbon#1965]
Hello,

I ran the following code on `try-carbon.herokuapp.com` (`master`).
I'm not sure if the result is correct, certainly it is not what I expected. In fact, I would expect the result of these expressions to be equal and all returning `2016-04-18T12:03:34+00:00` (a `UTC` value):
```php
date_default_timezone_set('UTC');
$date = '2016-04-18T12:03:34';
Carbon::parse($date.'-08:00')->toIso8601String();        // 2016-04-18T12:03:34-08:00
Carbon::parse($date.'-08:00', 'UTC')->toIso8601String(); // 2016-04-18T12:03:34-08:00
Carbon::parse($date, 'UTC')->toIso8601String();          // 2016-04-18T12:03:34+00:00
Carbon::parse($date.'-08:00')
    ->setTimezone('UTC')->toIso8601String();             // 2016-04-18T20:03:34+00:00
$d = Carbon::create($date.'-08:00');
echo Carbon::parse($d, 'UTC')->toIso8601String();        // 2016-04-18T12:03:34-08:00
```
My assumption is that this expression
```php
Carbon::parse($date, $tz);
```
is equivalent to
```php
Carbon::create($date)->setTimezone($tz);
```
but apparently it is not the case. Is my assumption incorrect?
 It looks like the timezone parameter of `::parse()` is ignored if the date includes a timezone value.

**Comment by kylekatarnls** [comment]
Hello. Nope, those both codes are not equivalent:
```php
date_default_timezone_set('America/New_York');

var_dump(Carbon::parse('2019-05-10 00:00:00', 'Asia/Tokyo'));

var_dump(Carbon::parse('2019-05-10 00:00:00')->tz('Asia/Tokyo')); // or setTimezone
```

Output:
```
object(Carbon\Carbon)#3 (3) {
  ["date"]=>
  string(26) "2019-05-10 00:00:00.000000"
  ["timezone_type"]=>
  int(3)
  ["timezone"]=>
  string(10) "Asia/Tokyo"
}
object(Carbon\Carbon)#3 (3) {
  ["date"]=>
  string(26) "2019-05-10 13:00:00.000000"
  ["timezone_type"]=>
  int(3)
  ["timezone"]=>
  string(10) "Asia/Tokyo"
}
```

Both code give a date in Asia/Tokyo timezone, but first one gives you midnight in Tokyo, second one gives you datetime in Tokyo when it's midnight in the server default timezone (America/New_York in the example).

What you did (`date_default_timezone_set('UTC')`) is the best setting for your server and changing the timezone with `tz()` or `setTimezone()` should be the last step before displaying the date to the user. And parsed dates from other timezones should be immediately converted in UTC dates: `Carbon::parse('2019-05-10 00:00:00', 'Asia/Tokyo')->tz('UTC')`, so you know you're safely working on UTC dates everywhere in your back-end.

**Comment by stebogit** [comment]
@kylekatarnls thanks for the explanation, that makes more sense to me now.
However, why
```php
date_default_timezone_set('America/New_York');
var_dump(Carbon::parse('2019-05-10T00:00:00-04:00', 'Asia/Tokyo'));
```
returns 
```
object(Carbon\Carbon)#3 (3) {
  ["date"]=>
  string(26) "2019-05-10 00:00:00.000000"
  ["timezone_type"]=>
  int(1)
  ["timezone"]=>
  string(6) "-04:00"  <-- ?
}
```
That's neither `America/New_York` or `Asia/Tokyo`.

My point is, if the first argument of `parse` defines a timezone, that prevails both the default and the passed timezone value of the instance you expect.

**Comment by kylekatarnls** [comment]
Here `Asia/Tokyo` is your fallback timezone if untimezoned/local date passed, but if the timezone is explicitly in the string (like here with `-04:00` suffix), it has the precedence.

The order of precedence is closest to the farthest:

Inner string => fallback to second argument => fallback to date_default_timezone_get()
