### ISSUE TITLE
[Translation tool] ta_LK

### ISSUE THREAD

**Issue by Satheez** [briannesbitt/Carbon#1966]
|English|ta_LK|comments|
|--|--|--|
|2 hours before|before|2 மணித்தியாலங்களின் முன்|
|2 hours after|after|2 மணித்தியாலங்களின் பின் |

**Comment by kylekatarnls** [comment]
Thanks,

That's sounds pretty long, the meaning of *2 hours before* is comparing to an other date, like in:
The car runs out of fuel but the red light switched on:
`2 hours before`

In such meaning can you confirm the actual form (`2 மணி நேரம் முன்`) is wrong?

And if so, are you sure there is no shorter way to say it that what you propose?

**Comment by Satheez** [comment]
@kylekatarnls Thank you for responding.

 As I can see the translation is shown in English.
If the given translation is too long, then we can stick with the following.

2 hours before => 2 மணி நேரம் முன்
2 hours after  => 2 மணி நேரம் பின்

**Comment by kylekatarnls** [comment]
Thank you very much, it will be fixed in 2.29.
