### ISSUE TITLE
[Translation tool] tk_TM

### ISSUE THREAD

**Issue by isadma** [briannesbitt/Carbon#1968]
|English|tk_TM|comments|
|--|--|--|
|2 months|aý 2|2 aý|
|2mos|aý 2|2 aý|
|1 month|aý 1|1 aý|
|a month|aý 1|1 aý|
|Mo|Siş|Si|
|Tu|Çar|Ça|
|We|Pen|Pe|
|Th|Ann|An|
|Fr|Şen|Şe|
|Sa|Ýek|Ýe|
|Su|Duş|Du|

**Comment by kylekatarnls** [comment]
Thanks @isadma I'll fix that for the next release.
