### ISSUE TITLE
diffInDays vs. diffInWeekdays

### ISSUE THREAD

**Issue by schulzefelix** [briannesbitt/Carbon#197]
If I have two Carbon Objects:

$now:
```
object(Carbon\Carbon)[545]
  public 'date' => string '2014-09-30 16:01:13' (length=19)
  public 'timezone_type' => int 3
  public 'timezone' => string 'Europe/Berlin' (length=13)
```
$endOfMonth:
```
object(Carbon\Carbon)[537]
  public 'date' => string '2014-09-30 23:59:59' (length=19)
  public 'timezone_type' => int 3
  public 'timezone' => string 'Europe/Berlin' (length=13)
```
Why I get different Difference values?
$now->diffInWeekdays($endOfMonth) => 1
$now->diffInDays($endOfMonth) => 0

Did I miss something here?

**Comment by rokkamokka** [comment]
Why was this closed? Is it not considered a bug? It is at the least very misleading behavior.

If the time part of the dates differ, `diffInWeekdays()` will consider a day having passed, while `diffInDays()` will not.
```
>>> \Carbon\Carbon::create(2017,6,5,0,0,0)->diffInDays(\Carbon\Carbon::create(2017,6,6,23,59,59));
=> 1
>>> \Carbon\Carbon::create(2017,6,5,0,0,0)->diffInWeekDays(\Carbon\Carbon::create(2017,6,6,23,59,59));
=> 2
```

If the time parts of the date are the same, the behavior is the same between the two methods (assuming the dates in the span are weekdays).
```
>>> \Carbon\Carbon::create(2017,6,5,0,0,0)->diffInDays(\Carbon\Carbon::create(2017,6,6,0,0,0));
=> 1
>>> \Carbon\Carbon::create(2017,6,5,0,0,0)->diffInWeekDays(\Carbon\Carbon::create(2017,6,6,0,0,0));
=> 1
```
