### ISSUE TITLE
[Translation tool] uz_UZ

### ISSUE THREAD

**Issue by ilyosjon09** [briannesbitt/Carbon#1970]
|English|uz_UZ|comments|
|--|--|--|
|2 hours ago|Bir necha 2 soat oldin|This should rather be "2 soat avval" because the meaning of current translation is "Several 2 hours ago"!|
|2 hours before|2 soat пеш аз он|This should rather be "2 soatdan oldin" because there are no words like  "пеш аз он" uzbek|
|2 hours after|2 soat пас аз он|This should rather be "2 soatdan keyin" because there are no words like  "пеш аз он" uzbek|

**Comment by kylekatarnls** [comment]
Hi @ilyosjon09 thanks a lot!

Is the suffix "dan" constant across units, meaning are those correct too:
```
bir daqiqadan oldin
6 haftadan keyin
2 yildan oldin
```

And so on for any year/month/week/day/hour/minute/second units?

**Comment by ilyosjon09** [comment]
Hi @kylekatarnls!

Sorry this was my first translation PR thus did some mistakes. Normally, "dan" suffix is used when we talk about years so "2 yildan oldin" sounds more natural. Even we can use the suffix for other examples you listed, according to my comparison, they sound bit robotic. Thus I suggest following:
Using "dan" suffix when "keyin" comes before year/month/week/day/hour/minute/second

**Comment by kylekatarnls** [comment]
Thanks, it will be released in 2.29.0.
