### ISSUE TITLE
Feature request format diff to `hour:minute:seconds`. So, the hour can more than 24.

### ISSUE THREAD

**Issue by erlangp** [briannesbitt/Carbon#1976]
Hello,

Feature request format diff to `hour:minute:seconds`. So, the hour can more than 24.
Currently carbon only support format a diff in one unit. 

Thanks!

**Comment by kylekatarnls** [comment]
Hello,

Please provide more details, for a feature description, we need at least:
- [ ] purpose, choices justifications (what this particular format, why no milliseconds/microseconds, the norm you chose if applicable, etc.)
- [ ] the public API (code examples)
- [ ] expected output for each example
- [ ] results for various edge-cases (negative diff, diffs over 1 day, DST : days of 23/25 hours)

Thanks.

**Comment by kylekatarnls** [comment]
I close this as there is not enough details.

Here is a macro that may be what you expect:
```php
Carbon::macro('diffAsTimeString', static function ($other = null, $format = '%H:%I:%S') {
  $hours = self::this()->floatDiffInHours($other);
  $interval = CarbonInterval::hours(floor($hours))->minutes(floor($hours * 60) % 60)->seconds(floor($hours * 3600) % 60);

  return $interval->format($format);
});

echo Carbon::parse('2020-01-10 12:25:26')->diffAsTimeString('2020-01-08 05:45:14');
```

**Comment by erlangp** [comment]
Thanks very much @kylekatarnls that's what i am looking for

```php
$format = '%H:%I:%S';
$other = '2020-01-02 01:02:03';
$c = Carbon::parse('2020-01-01 00:00:00');
$hours = $c->floatDiffInHours($other);
$interval = CarbonInterval::hours(floor($hours))->minutes(floor($hours * 60) % 60)->seconds(floor($hours * 3600) % 60);
echo $interval->format($format); // 25:02:03
```

**Comment by erlangp** [comment]
@kylekatarnls like this (in Java) sir :) 

https://commons.apache.org/proper/commons-lang/apidocs/org/apache/commons/lang3/time/DurationFormatUtils.html#formatDurationHMS-long-
