### ISSUE TITLE
[Translation tool] el

### ISSUE THREAD

**Issue by mkMoSs** [briannesbitt/Carbon#1977]
|English|el|comments|
|--|--|--|
|2 hours ago|2 ώρες πριν|This should be "πριν 2 ώρες" because "2 ώρες πριν" is not syntactically correct when translating "2 hours ago" and it's not the same as "2 hours before"|
|2 hours from now|σε 2 ώρες|This should be "2 ώρες από τώρα", because "σε 2 ώρες" translates to "in 2 hours" and including "από τώρα" translates to and means "from now"|

**Comment by kylekatarnls** [comment]
`in 2 hours` is actually the translation used in most English regional variants. So `σε 2 ώρες` is OK as long as it's "in" meaning *happening in the future*, not "in" meaning *how long it takes*

After cross-checking indeed `πριν 2 ώρες` seems better.

**Comment by kylekatarnls** [comment]
Thanks, it will be released in 2.29.0

**Comment by mkMoSs** [comment]
> `in 2 hours` is actually the translation used in most English regional variants. So `σε 2 ώρες` is OK as long as it's "in" meaning _happening in the future_, not "in" meaning _how long it takes_
> 
> After cross-checking indeed `πριν 2 ώρες` seems better.

Yes but that's not what the English variant on the table is.
It says `2 hours from now`, not `in 2 hours from now`
So `2 hours from now` = `2 ώρες από τώρα`

My point is I understand to a degree that the `in` might be implied here but that totally depends on usage and context, so translating directly without anything implied would be `2 ώρες από τώρα`
