### ISSUE TITLE
Question: replacements for deprecated setWeekStartsAt, setWeekEndsAt ?

### ISSUE THREAD

**Issue by cjaoude** [briannesbitt/Carbon#1981]
Question: what are the replacements for deprecated setWeekStartsAt, setWeekEndsAt ?

IDE is complaining they're deprecated.

thanks,

**Comment by kylekatarnls** [comment]
Deprecation notice:

>      * @deprecated To avoid conflict between different third-party libraries, static setters should not be used.
>      *             Use $weekEndsAt optional parameter instead when using endOfWeek method. You can also use the
>      *             'first_day_of_week' locale setting to change the start of week according to current locale
>      *             selected and implicitly the end of week.

In priority, you should use the locale, for instance: `Carbon::setLocale('en_US')` set week start to Sunday, `Carbon::setLocale('en_GB')` to Monday, `Carbon::setLocale('ar')` set it to Saturday. And locale can be set for a given object: `Carbon::now()->locale('en_US')`, for other days, you can create a custom locale and override `'first_day_of_week'` (see https://carbon.nesbot.com/docs/#api-localization)

And you can also check this example:
```php
$en = CarbonImmutable::now()->locale('en_US');

echo "-----------\n";

// We still can force to use an other day as start/end of week
$start = $en->startOfWeek(Carbon::TUESDAY); // Start of week assuming Tuesday is the first day of week
$end = $en->endOfWeek(Carbon::MONDAY); // End of week assuming Monday is the last day of week
```

(see https://carbon.nesbot.com/docs/#api-week)
