### ISSUE TITLE
[Translation tool] nb_NO

### ISSUE THREAD

**Issue by haugen86** [briannesbitt/Carbon#1982]
|English|nb_NO|comments|
|--|--|--|
|2mos|2 md.|2 mnd.|

**Comment by kylekatarnls** [comment]
Hi, CLDR uses `md.` for both short and narrow versions. Could you provide some references (newspapers, official regional administration websites, etc.) where this abbreviation appears?

**Comment by haugen86** [comment]
After further investigation, both can be used, but `md.` is recommended by the Norwegian language Council.

Closing issue.
