### ISSUE TITLE
[Translation tool] sl_SI

### ISSUE THREAD

**Issue by burut13** [briannesbitt/Carbon#1984]
|English|sl_SI|comments|
|--|--|--|
|a few seconds|1 sekunda|nekaj sekund (because this is real translation of "a few seconds"|
|Monday|Ponedeljek|ponedeljek|
|Mon|Pon|pon|
|Mo|Po|po|
|Tuesday|Torek|torek|
|Tue|Tor|tor|
|Tu|To|to|
|Wednesday|Sreda|sreda|
|Wed|Sre|sre|
|We|Sr|sr|
|Thursday|Četrtek|četrtek|
|Thu|Čet|čet|
|Th|Če|če|
|Friday|Petek|petek|
|Fri|Pet|pet|
|Fr|Pe|pe|
|Saturday|Sobota|sobota|
|Sat|Sob|sob|
|Sa|So|so|
|Sunday|Nedelja|nedelja|
|Sun|Ned|ned|
|Su|Ne|ne|
|January|Januar|januar|
|Jan|Jan|jan|
|February|Februar|februar|
|Feb|Feb|feb|
|March|Marec|marec|
|Mar|Mar|mar|
|April|April|april|
|Apr|Apr|apr|
|May|Maj|maj|
|May|Maj|maj|
|June|Junij|junij|
|Jun|Jun|jun|
|July|Julij|julij|
|Jul|Jul|jul|
|August|Avgust|avgust|
|Aug|Avg|avg|
|September|September|september|
|Sep|Sep|sep|
|October|Oktober|oktober|
|Oct|Okt|okt|
|November|November|november|
|Nov|Nov|nov|
|December|December|december|
|Dec|Dec|dec|

----
In Slovene, day and month names are not capitalized. References:
https://en.wikipedia.org/wiki/Slovene_months
https://en.wikipedia.org/wiki/Names_of_the_days_of_the_week#Numbered_days_of_the_week

**Comment by kylekatarnls** [comment]
Thanks, I'll fix that in the next version.
