### ISSUE TITLE
Setting ->timezone stop working after iterating on date properties or after unserialization

### ISSUE THREAD

**Issue by sorinsarca** [briannesbitt/Carbon#1992]
Hello,

According to the [docs](https://carbon.nesbot.com/docs/#api-setters), the `timezone` property setter should work: 
 _The following setters are implemented via PHP's `__set()` method. Its good to take note here that none of the setters, **with the obvious exception of explicitly setting the timezone, will change the timezone of the instance**._

But this stops working when the Carbon instance is unserialized or after the object was exported, printed, etc.

Working example

```php
$date = new \Carbon\Carbon("2020-01-01", "America/Vancouver");

echo $date->getTimezone()->getName(), PHP_EOL; // America/Vancouver

$date->timezone = "UTC";

echo $date->getTimezone()->getName(), PHP_EOL; // UTC
```

`unserialize` bug

```php
$date = new \Carbon\Carbon("2020-01-01", "America/Vancouver");

$date = \unserialize(\serialize($date));

echo $date->getTimezone()->getName(), PHP_EOL; // America/Vancouver

$date->timezone = "UTC";

// It should display UTC but it shows America/Vancouver
echo $date->getTimezone()->getName(), PHP_EOL; 
```

`var_export`, `print_r` or similar bug

```php
$date = new \Carbon\Carbon("2020-01-01", "America/Vancouver");

echo $date->getTimezone()->getName(), PHP_EOL; // America/Vancouver

$contents = var_export($date, true);

$date->timezone = "UTC";

// It should display UTC but it shows America/Vancouver
echo $date->getTimezone()->getName(), PHP_EOL;
```

`foreach` bug

```php
$date = new \Carbon\Carbon("2020-01-01", "America/Vancouver");

echo $date->getTimezone()->getName(), PHP_EOL; // America/Vancouver

foreach ($date as $value) {}

$date->timezone = "UTC";

// It should display UTC but it shows America/Vancouver
echo $date->getTimezone()->getName(), PHP_EOL;
```

`get_object_vars` bug

```php
$date = new \Carbon\Carbon("2020-01-01", "America/Vancouver");

echo $date->getTimezone()->getName(), PHP_EOL; // America/Vancouver

$vars = get_object_vars($date);

$date->timezone = "UTC";

// It should display UTC but it shows America/Vancouver
echo $date->getTimezone()->getName(), PHP_EOL;
```

And probably a lot of other examples.

------------

Carbon version: 2.28

PHP version: 7.3.*

**Comment by kylekatarnls** [comment]
This seems related to a behavior of `DateTime` I did not expect:

```php
$date = new DateTime();

var_dump(property_exists($date, 'timezone'));

$date = unserialize(serialize($date));

var_dump(property_exists($date, 'timezone'));
```

Output:
```
false
true
```

I guess it's more probably a PHP bug than the expected behavior.

**Comment by sorinsarca** [comment]
My conclusion, after checking the source code of DateTime class, is that this bug cannot be fixed for PHP <= 3. Here is why: every time we try to get the properties of a DateTime object (using foreach, get_object_vars, etc.) the DateTime class will internally add date, timezone and timezone_type properties to the object. 

You can see the code responsible for this [here](https://github.com/php/php-src/blob/php-7.3.13/ext/date/php_date.c#L2293).

[Here](https://github.com/php/php-src/blob/php-7.3.13/ext/date/php_date.c#L2310) is set the date property.

[Here](https://github.com/php/php-src/blob/php-7.3.13/ext/date/php_date.c#L2315) is set the timezone_type property.

[Here](https://github.com/php/php-src/blob/php-7.3.13/ext/date/php_date.c#L2337) is set the timezone property.

And of course [zend_hash_str_update](https://github.com/php/php-src/blob/php-7.3.13/Zend/zend_hash.c#L844) updates the properties or creates them if missing.

This bug cannot be solved from user land code.

So, my suggestion is to remove the `timestamp` property setter in the future major version and add a warning in the docs for current versions.

I think you agree with me now that this is a buggy or faulty implementation of the DateTime. Other Date related classes might have similar issues.

**Comment by kylekatarnls** [comment]
> to remove the timestamp property setter

You mean timezone property I guess?

I think so, the work-around is to use the `->tz` alias instead.

It is possible to cleanup the properties on `__wakeup` but it solves only the `unserialize` bug.

Others seems not fixable in the user-land.

Note than `foreach` is not supported in theory as `DateTime` does not implements `Traversable`, it only works by luck, but it's not something we should be striving for.

`get_object_vars` is not so much relevant for a date object.

However I discovered a very unlucky case:
```php
$old = new \Carbon\Carbon("2020-01-01", "America/Vancouver");
echo $old->getTimezone()->getName(), PHP_EOL; // America/Vancouver
$new = clone $old;
$old->timezone = "UTC";
echo $old->getTimezone()->getName(), PHP_EOL; // UTC
echo $new->getTimezone()->getName(), PHP_EOL; // America/Vancouver
```

It prevents us to use `clone` to solve the problem.

I won't take the risk to override many methods. I will simply deprecate `->timezone` and document to use `->tz` instead.

**Comment by kylekatarnls** [comment]
Documentation updated.
