### ISSUE TITLE
[Translation tool] id

### ISSUE THREAD

**Issue by ranialmonk** [briannesbitt/Carbon#1996]
|English|id|comments|
|--|--|--|
|2 years|2 tahun|fix|
|2yrs|2thn|fix|
|1 year|1 tahun|fix|
|a year|setahun|fix|
|2 months|2 bulan|fix|
|2mos|2bln|fix|
|1 month|1 bulan|fix|
|a month|sebulan|fix|
|2 weeks|2 minggu|fix|
|2w|2mgg|fix|
|1 week|1 minggu|fix|
|a week|seminggu|fix|
|2 days|2 hari|fix|
|2d|2hr|fix|
|1 day|1 hari|fix|
|a day|sehari|fix|
|2 hours|2 jam|fix|
|2h|2j|fix|
|1 hour|1 jam|fix|
|an hour|sejam|fix|
|2 minutes|2 menit|fix|
|2m|2mnt|fix|
|1 minute|1 menit|fix|
|a minute|semenit|fix|
|2 seconds|2 detik|fix|
|2s|2dt|fix|
|1 second|1 detik|fix|
|a few seconds|beberapa detik|fix|
|Monday|Senin|fix|
|Mon|Sen|fix|
|Mo|Sn|fix|
|Tuesday|Selasa|fix|
|Tue|Sel|fix|
|Tu|Sl|fix|
|Wednesday|Rabu|fix|
|Wed|Rab|fix|
|We|Rb|fix|
|Thursday|Kamis|fix|
|Thu|Kam|fix|
|Th|Km|fix|
|Friday|Jumat|fix|
|Fri|Jum|fix|
|Fr|Jm|fix|
|Saturday|Sabtu|fix|
|Sat|Sab|fix|
|Sa|Sb|fix|
|Sunday|Minggu|fix|
|Sun|Min|fix|
|Su|Mg|fix|
|January|Januari|fix|
|Jan|Jan|fix|
|February|Februari|fix|
|Feb|Feb|fix|
|March|Maret|fix|
|Mar|Mar|fix|
|April|April|fix|
|Apr|Apr|fix|
|May|Mei|fix|
|May|Mei|fix|
|June|Juni|fix|
|Jun|Jun|fix|
|July|Juli|fix|
|Jul|Jul|fix|
|August|Agustus|fix|
|Aug|Agt|fix|
|September|September|fix|
|Sep|Sep|fix|
|October|Oktober|fix|
|Oct|Okt|fix|
|November|November|fix|
|Nov|Nov|fix|
|December|Desember|fix|
|Dec|Des|fix|
|2 hours ago|2 jam yang lalu|fix|
|2 hours from now|2 jam dari sekarang|fix|
|2 hours before|2 jam sebelumnya|fix|
|2 hours after|2 jam setelahnya|fix|

----
Indonesian people rarely use short words like jm for jumat (Friday), sn for senin (Monday), 2mgg for 2minggu. They wrote it in full.

**Comment by kylekatarnls** [comment]
Hello, thanks for your contribution.

What is "fix"? You're supposed to give the form yo think it's correct on wrong line and let blank on correct lines, see #1977 or #1968 as an example.

Please retry.
