### ISSUE TITLE
\Carbon\CarbonInterface::createFromTimestampMs() documentation

### ISSUE THREAD

**Issue by SergeyBarabash** [briannesbitt/Carbon#1997]
Hello,

I encountered an issue with the following code:
```php
echo Carbon::createFromTimestampMs($_SERVER['REQUEST_TIME_FLOAT'] * 1000);
```

Carbon version: **2.26.0**

PHP version: **7.3.13**

Method `\Carbon\CarbonInterface::createFromTimestampMs()` in fact can receive float value for the first argument. This is convenient when we create Carbon object from float timestamp with microseconds.

But now first argument is documented as `int`. Using `createFromTimestampMs()` for float timestamps with microseconds looks like undocumented feature. 

Thus we use `Carbon::rawCreateFromFormat('U.u', sprintf('%F', $_SERVER['REQUEST_TIME_FLOAT']))` construction instead.

Can you change documentation for this method?

Thanks!

**Comment by kylekatarnls** [comment]
Indeed, `@param int` should be `@param float` in both `CarbonInterface.php` and `Traits/Timestamp.php` to match the actual feature. Ideally it should also be tested in unit tests with various numbers of decimals.

**Comment by kylekatarnls** [comment]
I see the CarbonInterface miss the new 2.9 methods and will need a patch, I will use this one to fix the createFromTimestampMs typing.
