### ISSUE TITLE
CarbonInterval not supported for v1.x php5

### ISSUE THREAD

**Issue by jaycee04** [briannesbitt/Carbon#1998]
Hello,

I encountered an issue with the following code:
```php
$from = $this->carbon->parse($myDate1);
                $to = $this->carbon->parse($myDate2);
                $diff1 = $to->diffInWeekdays($from);
```

Carbon version: **1.39.1**

PHP version: **5**

I expected to get:

```
Hours in difference withour weekdays
```

But I actually get:

```
A PHP Error was encountered
Severity: Error

Message: Class 'Carbon\CarbonInterval' not found

Filename: libraries/Carbon.php

Line Number: 4087

Backtrace:
```

Thanks!

**Comment by kylekatarnls** [comment]
Hello,

Every class needs to be loaded to be used using `include "libraries/CarbonInterval.php";` same for CarbonPeriod etc.

That's why the vast majority of the PHP world uses composer so every class is automatically loaded on demand.

Thanks.

**Comment by kylekatarnls** [comment]
Reminder: active support of PHP 5 ended in 2017 (security support ended 1 year ago):
https://www.php.net/supported-versions.php
Carbon v1 will neither no longer receive any update since last summer.
And Composer is the very recommended way to install Carbon
https://carbon.nesbot.com/#withcomposer
