### ISSUE TITLE
Still mutable

### ISSUE THREAD

**Issue by beberlei** [briannesbitt/Carbon#2]
The most annoying thing about PHP DateTime is that they objects are mutable. It seems this is not changed in Carbon?

**Comment by amitailanciano** [comment]
+1, would love to see this -- remembering to chain ->copy() all the time is pretty annoying/frustrating

**Comment by tabennett** [comment]
+1, this just bit us today at work. Side-effects sucks and make Carbon more difficult to use as a value object.

**Comment by timacdonald** [comment]
I've just made a little wrapper library around Carbon to make it immutable if anyone is interested.

https://github.com/timacdonald/immutable-carbon
