### ISSUE TITLE
Wrong month when using month() and endOfYear()

### ISSUE THREAD

**Issue by avdft** [briannesbitt/Carbon#2000]
Using `Carbon::month()` after `Carbon::endOfYear()` results in wrong month.

I encountered the issue with the following code:
```php
for ($i = 1; $i <= 12; $i++) {
    echo Carbon::create(2020)->endOfYear()->month($i)->format("m") . "\n";
}
```

Carbon version: **2.29**

PHP version: **7.2.24**

I expected to get:

```
01
02
03
04
05
06
07
08
09
10
11
12
```

But I actually get:

```
01
03
03
05
05
07
07
08
10
10
12
12
```

Thanks!

**Comment by kylekatarnls** [comment]
Hello, it's not about `endOfYear()`, it's how `DateTime` works when you change the month with a `day = 31st`:

```php
$d = new DateTime('2020-12-31');

$d->modify('previous month');

echo $d->format('Y-m-d');
```

Output: 2020-12-01

As you may notice, this is pure PHP code, and it does not take the last day of November, it takes 31st day starting from November and so it falls to December 1st.

Maybe you could provide a more concrete use case so I can understand why you're using `Carbon::create(2020)->endOfYear()` which does not make too much sense to me.

Are you trying to get last second moment of each month of a given year?

**Comment by kylekatarnls** [comment]
If you want last instant of each month, you should use:

```php
foreach (Carbon::create(2020)->toPeriod(12, '1 month') as $monthStart) {
  echo $monthStart->endOfMonth()."\n";
}
```

If you're looking for something else, please provide details and I will re-open.

**Comment by avdft** [comment]
The example was just a proff of concept of my finding when I was debugging the problem.

This was the original code:
```php
$start = Carbon::create((int) $year)->startOfYear();
$end = Carbon::create((int) $year)->endOfYear();

if ($month) {
    $start = $start->month($month)->startOfMonth();
    $end = $end->month($month)->endOfMonth();
}
```

I have fix the problem, but still wanted to open an issues, just in case if it was a bug.

In any case, I still think this behavior is , and can cause alot of problems for people if it is not documented somewhere.

**Comment by kylekatarnls** [comment]
This behavior is not in Carbon's hands, it's up to PHP team to decide.

Then I still don't understand why you use `->endOfYear()` this is useless (and note than `Carbon::create((int) $year)` is the start of year already). I would simply do this (it would call way less methods):
```php
$start = CarbonImmutable::create((int) $year, (int) $month ?: 1);
$end = $month ? $start->endOfMonth() : $start->endOfYear();
```

In your case `CarbonImmutable` seems more appropriate too, but you can use `Carbon` and `->copy()` instead.

**Comment by kylekatarnls** [comment]
The point is `(new DateTime('2020-12-31'))->modify('November')` (equivalent to `Carbon::parse('2020-12-31')->month(11)` is ambiguous: it would expect `2020-11-31` which does not exist so it gives `2020-12-01`, it could have gave `2020-11-30` but both are equally wrong. So as the operation is not safe (cannot produce a valid date without shifting to a previous/next date), you should just avoid having logic based on that kind of operations.
