### ISSUE TITLE
Cannot create date using year and week 

### ISSUE THREAD

**Issue by ahmedali5530** [briannesbitt/Carbon#2001]
Hello,

I encountered an issue with the following code:
```php
$this_week = Carbon::now()->format('Y-W');
$last_week = Carbon::createFromFormat('Y-W', $this_week)->subYear()->startOfWeek()->addHours(6)->toDateTimeString();
```

Carbon version: **1.36.2**

PHP version: **7.3.0**

I expected to get:

Same week no. last year

But I actually get:

```
The format separator does not match
Trailing data
Carbon::createFromFormat('Y-W', '2020-04')
```

Thanks!

**Comment by ahmedali5530** [comment]
After updating to version `2.29.1` i get the exact same result
```
The format separator does not match
Trailing data
```

**Comment by kylekatarnls** [comment]
This is a PHP bug (`DateTime::createFromFormat('Y-w', '2020-04');` produces the same error):
https://3v4l.org/V6qJH

I will check if a specific bug is open for that. But `Carbon` does not override this method extending `DateTime`, so you always get the same behavior as in pure PHP.

**Comment by kylekatarnls** [comment]
The bug is already reported in PHP bugs list and assigned:
https://bugs.php.net/bug.php?id=51472

**Comment by kylekatarnls** [comment]
The Carbon documentation currently says:
> createFromFormat() is mostly a wrapper for the base php function DateTime::createFromFormat. The difference being again the $tz argument can be a DateTimeZone instance or a string timezone value. Also, if there are errors with the format this function will call the DateTime::getLastErrors() method and then throw a InvalidArgumentException with the errors as the message.

and links to http://php.net/manual/en/datetime.createfromformat.php

So we're currently aligned: we refer the PHP doc, PHP doc list the available letters for the format and this list does not contain `w` and `W`.
