### ISSUE TITLE
[Translation tool] lv

### ISSUE THREAD

**Issue by guntars** [briannesbitt/Carbon#2009]
|English|lv|comments|
|--|--|--|
|February|ferbruārī|februārī  ... because "r" after "e" is a typo|
|Feb|Febr|Feb   .. because this is how you abbreviate it in Latvian|
|Mar|Marts|Mar ... current one is NOT abbreviation|
|May|Maijs|Mai ....... current one is NOT abbreviation|

**Comment by kylekatarnls** [comment]
Thanks. It will fixed on the next release.
