### ISSUE TITLE
Maybe add Carbon::createFromDateTimeInterface() as alias for ::instance() ?

### ISSUE THREAD

**Issue by HenkPoley** [briannesbitt/Carbon#2011]
Hello,

I encountered an issue. It is not very discoverable how to go from a PHP DateTime / DateTimeImmutable / DateTimeInterface to a Carbon or CarbonImmutable object. Apparently \Carbon\Carbon::instance() is used for that, but I didn't find it through the documentation; only through a Google search.

(Maybe because there is something that breaks Chromium's search on the documentation page)

Carbon version: 2.30

PHP version: 7.1.33 & 7.3.14-6+ubuntu18.04.1+deb.sury.org+1 (cli) 

I would propose to add `Carbon::createFromDateTimeInterface(DateTimeInterface $datetime)`.

It would be nice if some more discoverable interface was in place.

**Comment by kylekatarnls** [comment]
Hello, first of all, there is a chapter about instanciation: https://carbon.nesbot.com/docs/#api-instantiation

> Finally, if you find yourself inheriting a `\DateTime` instance from another library, fear not! You can create a `Carbon` instance via a friendly `instance()` method. Or use the even more flexible method `make()` which can return a new `Carbon` instance from a `DateTime`, `Carbon` or from a `string`, else it just returns null.

```php
$dt = new \DateTime('first day of January 2008'); // <== instance from another API
$carbon = Carbon::instance($dt);
echo get_class($carbon);                               // 'Carbon\Carbon'
echo $carbon->toDateTimeString();                      // 2008-01-01 00:00:00
```

The fact is we can't anticipate all the way a feature can be searched.

Then `instance()` is a standardized way across the library classes, it means we would also need `CarbonInterval::createFromDateInterval(\DateInterval $interval)` `CarbonPeriod::createFromDatePeriod(\DatePeriod $period)` and `CarbonTimeZone::createFromDateTimeZone(\DateTimeZone $timezone)` for consistency.

So I need to think if it's worth it.

**Comment by HenkPoley** [comment]
Fact is, if I use the API search thingy on website. E.g. click some code, open the API documentation, use the search bar, enter "DateTime", then _no_ Carbon creation/instantiation function pops up that ingests DateTime/DateTimeImmutable/DateTimeInterface.

Furthermore, _something_ on the Carbon website breaks scrolling for Chrome/Chromium search (e.g. all browsers except Safari and Firefox). So you cannot search in the regular story-documentation as well.

**Comment by kylekatarnls** [comment]
I don't get the point about scrolling and regular search:

Chrome:
![image](https://user-images.githubusercontent.com/5966783/74530161-b78dd300-4f29-11ea-96aa-39f1d5c8159f.png)

Firefox:
![image](https://user-images.githubusercontent.com/5966783/74530368-223f0e80-4f2a-11ea-869b-0e0119d79aa4.png)

Both scrolled automatically to the section on clicking on "Next".

About:
> PhpStorm's code completion does not match anything either (because it's not in the name)

That's a point but having aliases for each method and every words the user could search for is not reliable neither. Following this principle, we should have a `createFromString` aliasing `parse`, a `createFromNumbers` aliasing `create`, `setLanguageAndRegion` aliasing `setLocale` and so on. So I agree this would be nice for this particular case of a developer searching "create from DateTime" in its IDE but we have yet a lot of aliases and I have to weight new ones with parsimony avoiding bloating too much the library.

**Comment by HenkPoley** [comment]
Chrome `Versie 80.0.3987.106 (Officiële build) (64-bits)`. Search on [the documentation page](https://carbon.nesbot.com/docs/) certainly from Chrome itself (Ctrl+F) works very wonky, mostly not scrolling or progressing at all. Even in incognito mode, e.g. with no extensions.

**Comment by kylekatarnls** [comment]
For the record you can also use constructors since 2.30.0:
```php
new Carbon(new DateTime())
```

**Comment by kylekatarnls** [comment]
I finally decide to promote this last way instead of adding methods:
https://carbon.nesbot.com/docs/#api-instantiation

**Comment by c33s** [comment]
@kylekatarnls just as feedback: additionally having the static methods would help to find such features without searching the docs and would also be consistent with the original `DateTime` classes. this would result in a much better DX.

i searched for `create` in phpstorm i wondered why there is no function to create from `DateTimeInterface`. i happily found `createFromInterface()` just to see that is the php native function which ships with php8 and returns a `DateTimeImmutable` object. 
![image](https://user-images.githubusercontent.com/649209/125855775-a5443997-2cd8-4e7d-8859-19d78af2c5ad.png)

also i often write in feedbacks or blogposts that software has the big advantage that we don't have to make design/architecture decisions in a binary matter. opposite to the real life buildings where we have to choose if we want a flat or a pitched roof, we can have both at the same time in our software.

just me 2ct

thanks for the great lib :)

**Comment by kylekatarnls** [comment]
The point is actually that we let the native `createFromInterface()` function. It's a PHP team choice to use `new self()` and not `new static()` but can assume it's a mistake and override it to "fix" the native method, but when by the past we override many native functions we actually had issue for `Carbon` being compatible where a `DateTimeInterface` is expected (also with different signatures over PHP versions). Now I would better opt for letting inherited methods as untouched as possible, mostly when there are already multiple other ways to get the expected result.
