### ISSUE TITLE
If `$equal = true` means Carbon::between() does inclusive matching, then documentation is wrong

### ISSUE THREAD

**Issue by HenkPoley** [briannesbitt/Carbon#2012]
Carbon documentation version 2.30

Under Carbon::between() the documentation seems to assume the default $equals setting is false. Since it tells the behaviour changes when you set it to true.

```php
Carbon::parse('2018-07-25')->between('2018-07-14', '2018-08-01'); // true
Carbon::parse('2018-07-25')->between('2018-08-01', '2018-08-20'); // false
Carbon::parse('2018-07-25')->between('2018-07-25', '2018-08-01'); // false
Carbon::parse('2018-07-25')->between('2018-07-25', '2018-08-01', true); // true
```

But the actual library seems to have $equals = true as default. So (also) setting it to true yourself, should not change the behaviour. The last two calls should in reality return the same result.

Also the actual implementation in `src/Carbon/Traits/Comparison.php` sets $equals = true as default.

**Comment by HenkPoley** [comment]
Under `php artisan tinker`, running `use Carbon\Carbon;` and then `Carbon::parse('2018-07-25')->between('2018-07-25', '2018-08-01');` results in true. 

Just as `Carbon::parse('2018-07-25')->between('2018-07-25', '2018-08-01', true);` results in true.

**Comment by kylekatarnls** [comment]
Note than for a more descriptive way, you can use `betweenExcluded()` then results of examples of the documentation are also generated, so there is a bug here maybe in the documentation generation.

**Comment by HenkPoley** [comment]
I would like to use the inclusive version. So `betweenExcluded()` is not for me.

Maybe someone needs to check if there was a behaviour change for `between()`, somewhere along the way.

**Comment by HenkPoley** [comment]
I notice there is an `inBetween()` too, with the same behaviour as `between()`.

**Comment by kylekatarnls** [comment]
I get it, doc is correct, but not the PHPDoc. That's just it, `between()` is the current `betweenInclusive()`

**Comment by kylekatarnls** [comment]
PHPDoc fixed and `betweenIncluded()` method added so it can be more explicit in the code when bounds matter.

Will be released in 2.31.0.

**Comment by lloricode** [comment]
Hello, I attempted this task (as shown in the image), and I found it confusing. Is it supposed to return `true`, or is there something I'm not aware of?

![Screenshot_2023-12-05_11-05-37](https://github.com/briannesbitt/Carbon/assets/8251344/00a31caf-d14c-4ca7-92cb-226ebeddbedb)

**Comment by kylekatarnls** [comment]
It's perfectly expected, and unrelated to `$equal = true`

If you call `now()` 3 times, you get 3 different moments because your code is not ran instantly.

Here is the order of what happen:

```php
$now1 = now(); // 12:00:00.000000
$now2 = now(); // 12:00:00.000123
$now3 = now(); // 12:00:00.000456

$now3->beetweenIncluded($now1, $now2); // false, since $now3 > $now2 and $now3 > $now1
```
