### ISSUE TITLE
Small interface fix around createFromFormat()

### ISSUE THREAD

**Issue by HenkPoley** [briannesbitt/Carbon#2018]
Improves handling of typehinting on this function in editors and vimeo/psalm.

https://github.com/briannesbitt/Carbon/pull/2016
https://github.com/briannesbitt/Carbon/pull/2017

Just like the standard library `DateTime::createFromFormat()` it may fail, on the garbage in garbage out principle.

**Comment by kylekatarnls** [comment]
The default behavior of `Carbon` is to throw an exception instead of silently returning `false` like its `DateTime` parent.

So for now I prefer to close and keep the PHPDoc as is. I would re-open if there are other issues to be considered.
