### ISSUE TITLE
Fix Russian month termination of isoFormat('LLL')

### ISSUE THREAD

**Issue by dima-bzz** [briannesbitt/Carbon#2025]
Hi. When I want to get the date through isoFormat ('LLL'), I get the wrong end of the month. For some reason, months_standalone is substituted instead of months. Russian language. Everything is true in the momentjs package.

My code:
```php
Carbon::parse('2024-02-29 12:24:00')->isoFormat('LLL')
```

Expected:
```
29 февраля 2020 г., 12:24
```

Actual:
```
29 февраль 2020 г., 12:24
```

**Comment by kylekatarnls** [comment]
Some informations we ask in our issue template are missing, to get support please ensure to give at least:

- [ ] your Carbon version;
- [ ] your PHP version;
- [ ] a minimal code chunk to reproduce your case;
- [ ] the current output of this code;
- [ ] the output you expect.

Thanks.
