### ISSUE TITLE
[Translation tool] Short non-standalone months in Catalan

### ISSUE THREAD

**Issue by joseballester** [briannesbitt/Carbon#2027]
## Additional fixes
Short non-standalone month names (`months_short`) should be preceeded by either _de_ or _d'_, in a similar way to long non-standalone month names (`months`).

----
The [current translation](github.com/briannesbitt/Carbon/blob/master/src/Carbon/Lang/ca.php) differentiates between `months` and `months_standalone`, but `months_short` and `months_short_standalone` are currently the same. I'd suggest changing `months_short` by:
```
['de gen.', 'de febr.', 'de març', 'd\'abr.', 'de maig', 'de juny', 'de jul.', 'd\'ag.', 'de set.', 'd\'oct.', 'de nov.', 'de des.']
```

**Comment by kylekatarnls** [comment]
Thanks, it will be fixed in 2.31.
