### ISSUE TITLE
[Translation tool] de_AT

### ISSUE THREAD

**Issue by BernhardBaumrock** [briannesbitt/Carbon#2031]
|English|de_AT|comments|
|--|--|--|
|January|Januar|Jänner|

----
January
In other parts of the Upper German-speaking area, such as Austria and South Tyrol, "Jänner"[6], on the other hand, is still the common name for the first month of the year, both in colloquial and written language and according to the Austrian Dictionary. On the other hand, the use of the term Feber for the second month becomes less frequent. Contrary to general usage in Austria, some Austrian editors replace the word Jänner with January in order to take into account the entire German-speaking area and its book market. [7] In Austria, the word "Januar" is hardly ever used. [8]

Translated with www.DeepL.com/Translator (free version)
https://de.wikipedia.org/wiki/Januar

**Comment by kylekatarnls** [comment]
Thanks it will be fixed in 2.32.

**Comment by BernhardBaumrock** [comment]
Awesome, thx :)
