### ISSUE TITLE
Equality of dst-conflated timestamps changed behaviour

### ISSUE THREAD

**Issue by troelskn** [briannesbitt/Carbon#2032]
Hello,

I encountered an issue with the following code:
```php
<?php

use PHPUnit\Framework\TestCase as TestCase;
use Carbon\Carbon;

class NesbotTest extends TestCase
{
    public function setUp()
    {
        date_default_timezone_set('+00:00');
        parent::setUp();
    }

    public function testNativeDst()
    {
        $x = new DateTime("@1540684800"); // 2018-10-28 00:00:00.000000 @ UTC
        $y = new DateTime("@1540688400"); // 2018-10-28 01:00:00.000000 @ UTC
        $x->setTimezone(timezone_open('Europe/Copenhagen'));
        $y->setTimezone(timezone_open('Europe/Copenhagen'));
        // 2018-10-28 02:00:00.000000 @ Europe/Copenhagen
        $this->assertFalse($x == $y);
    }

    public function testCarbonDst()
    {
        $x = new Carbon("@1540684800"); // 2018-10-28 00:00:00.000000 @ UTC
        $y = new Carbon("@1540688400"); // 2018-10-28 01:00:00.000000 @ UTC
        $x->setTimezone(timezone_open('Europe/Copenhagen'));
        $y->setTimezone(timezone_open('Europe/Copenhagen'));
        // 2018-10-28 02:00:00.000000 @ Europe/Copenhagen
        $this->assertFalse($x == $y);
    }
}
```

Carbon version: `1.23.0`

PHP version: `7.3.10`

I expected to get:

```
PHPUnit 5.7.27 by Sebastian Bergmann and contributors.

..                                                                  2 / 2 (100%)

Time: 363 ms, Memory: 4.00MB

OK (2 tests, 2 assertions)
```

But I actually get:

```
PHPUnit 5.7.27 by Sebastian Bergmann and contributors.

.F                                                                  2 / 2 (100%)

Time: 455 ms, Memory: 4.00MB

There was 1 failure:

1) NesbotTest::testCarbonDst
Failed asserting that true is false.

/var/app/tests/NesbotTest.php:31

FAILURES!
Tests: 2, Assertions: 2, Failures: 1.
```

Note: This behaviour changed from `1.22.1` to `1.23.0`. I'm not even sure which behaviour is more correct, although I find it suspicious that Carbon does not agree with native Datetime.

I realise these are ancient versions, but I am genuinely confused as to whether this is a bug-fix or a bug. I am upgrading a pretty big application, and I need to know if I should expect the new behaviour or the old. The goal is eventually to migrate on to Carbon 2, but first we want to make sure it works with the latest 1.x.x.

Thanks!

**Comment by troelskn** [comment]
I can see that this behaviour was reneged on from `2.27.0` to `2.28.0`, so that the most current version of Carbon agrees with native PHP Datetime. Is this the expected behaviour?

**Comment by kylekatarnls** [comment]
Carbon previously worked around PHP DateTime DST bugs. But PHP progressively solved some of them. So it behaved even more unexpectedly on different PHP versions and try to be DateTime-compatible as much as possible. We now removed those overrides and recommend to use UTC for all date calculations and use location timezones only before displaying the date.

See more detailed advices:
https://medium.com/@kylekatarnls/always-use-utc-dates-and-times-8a8200ca3164
https://medium.com/@kylekatarnls/handle-dates-the-right-way-in-php-c215650fc4fa

**Comment by troelskn** [comment]
Thanks for the clarification @kylekatarnls - That makes sense, in its own twisted ways.

So, to summarise, in case google leads someone else to this place:

PHP's native Datetime implementation (currently) has a bug whereby changing the tz does not change the internal representation right away. The result being that two apparently equal datetime's can be different, if they were converted from different initial datetime's of a different tz. However, if one calls `getTimestamp` on them first, they will be "reset" to the current representation and thus become properly equal. Carbon used to try and work around this buggy behaviour by transparently calling `getTimestamp`. Later, it was decided that Carbon shouldn't try to correct this bug and so the patch was removed.
