### ISSUE TITLE
[Translation tool] pt_BR

### ISSUE THREAD

**Issue by luhansalimena** [briannesbitt/Carbon#2034]
|English|pt_BR|comments|
|--|--|--|
|2 hours before|2 horas antes|2 horas atrás|

----
"2 horas antes" is not a common way to describe something that has past

**Comment by luhansalimena** [comment]
Hello,

> "2 hours before" is not always in the past. "I will leave the office 2 hours before going to the party" both events are in the future and "before" is a about relative time between the two events.

Sorry about this mistake, I had a misconception about the phrase 

Here is the translation of your example:
> "I will leave the office 2 hours before going to the party"

"Vou sair do escritório 2 horas antes de ir para a festa"

So "2 horas antes" is the correct way of writing

**Comment by kylekatarnls** [comment]
Great! Thanks for the confirmation.
