### ISSUE TITLE
diffInMonths calc error

### ISSUE THREAD

**Issue by buffge** [briannesbitt/Carbon#2039]
Hello,

I encountered an issue with the following code:
```php
ini_set('date.timezone','Asia/Shanghai');
echo Carbon::parse('2020-03')->diffInMonths(Carbon::parse('2020-02'));
```

Carbon version: 2.31

PHP version: php7.4.3
 

I expected to get:

```
1
```
 

But I actually get:

```
0
```
 

Thanks!

**Comment by kylekatarnls** [comment]
When I try it in https://try-carbon.herokuapp.com/ I get 1.

Can you precise the default timezone you use?

**Comment by buffge** [comment]
current timezone is Asia/Shanghai

**Comment by kylekatarnls** [comment]
This is a PHP bug:

```php
$tz = new DateTimeZone('Asia/Shanghai');

var_dump((new DateTime('2020-03-01', $tz))->diff(new DateTime('2020-02-01', $tz)));
```

It gives 0 in the month slot, while the same code gives 1 with UTC timezone.

My recommandation is to work with UTC and use local timezone only for the display to user.

See:
https://medium.com/@kylekatarnls/always-use-utc-dates-and-times-8a8200ca3164
https://medium.com/@kylekatarnls/handle-dates-the-right-way-in-php-c215650fc4fa

**Comment by buffge** [comment]
Thinks
