### ISSUE TITLE
Carbon AddWeekdays if weekend was changed works not correct

### ISSUE THREAD

**Issue by lipton4egg** [briannesbitt/Carbon#2044]
Hello,

I encountered an issue with the following code:
```php
Carbon::setWeekendDays([Carbon::THURSDAY, Carbon::FRIDAY]);

Carbon::setWeekStartsAt(Carbon::SATURDAY);
Carbon::setWeekEndsAt(Carbon::FRIDAY);

Carbon::create(2020, 3, 25, 0, 0, 0)->addWeekdays(2);
```

Carbon version: 1.25.0

PHP version: 7.3

I expected to get:

```
2020-03-29
```

But I actually get:

```
2020-03-27
```

Thanks!

**Comment by kylekatarnls** [comment]
Hello,

This feature has been implemented in 2.0 version. Carbon 1.x support ended in June 2019. What prevents you to upgrade?

**Comment by lipton4egg** [comment]
Hello Kyle, so all I need is to upgrade to 2.0 version and issue will be fixed?

**Comment by kylekatarnls** [comment]
Please upgrade rather to the latest version 2.32 and keep having new features and bugfixes using `"nesbot/carbon": "^2.32"` in your composer.json. If you're using Laravel 5.8 or greater, you should just remove carbon from your composer.json and run `composer update`. If no other package locks your carbon version, it will upgrade to the latest 2.x as it's the default for Laravel if you're running PHP >= 7.1.

As you can see here:
https://try-carbon.herokuapp.com/

We get 2020-03-29 with the latest version.

**Comment by lipton4egg** [comment]
Thanks for advice, yes we are currently on Laravel 5.6, so there lots of updates needed
