### ISSUE TITLE
subMonth method does not produce expected result

### ISSUE THREAD

**Issue by skadimoolam** [briannesbitt/Carbon#2047]
Hi All,

The subMonth() method does not produce expected results
```php
echo Carbon::now();                         // 2020-03-30 05:59:12
echo Carbon::now()->subMonth();   // 2020-03-01 05:59:12
```

Carbon version: 2.31.0
PHP version: 7.2.15

I expected to get:

```
2020-02-30 05:59:12
```

But I actually get:

```
2020-03-01 05:59:12
```

Thanks!

**Comment by kylekatarnls** [comment]
Hello,

Please read the "Addition and subtraction" part of the documentation:
https://carbon.nesbot.com/docs/#api-addsub

This is the native PHP behavior as explained in #1335

Thanks.

**Comment by skadimoolam** [comment]
Thank you
