### ISSUE TITLE
createFromFormat for February returns March

### ISSUE THREAD

**Issue by r3nt3r** [briannesbitt/Carbon#2048]
Hello,

I encountered an issue with the following code:
```php
Carbon::createFromFormat('Y-m', '2020-02')
```

Carbon version: **1.25.0**

PHP version: **7.2.11**

I expected to get:

```
Carbon\Carbon @1583081517 {#3029
     date: 2020-02-01 16:51:57.0 Europe/London (+00:00),
   }

```

But I actually get:

```
Carbon\Carbon @1583081517 {#3029
     date: 2020-03-01 16:51:57.0 Europe/London (+00:00),
   }

```

 
However if I use createFromFormat with this format it will show February
```php
Carbon::createFromFormat('Y-m-d', '2020-02-01')
```

Thanks!

**Comment by kylekatarnls** [comment]
Hello,

This is the PHP behaviour (explained here: https://www.php.net/manual/fr/datetime.createfromformat.php), as 2020-02-30, it takes the next valid date:
```php
var_dump(DateTime::createFromFormat('Y-m', '2020-02')); // same output as Carbon
```

You need the `!`:
```php
var_dump(Carbon::createFromFormat('!Y-m', '2020-02')); // 2020-02-01
```

To reset values, else values of the current moment will be used if not specified and overflow if date is not valid.
