### ISSUE TITLE
Problem subtracting month in February

### ISSUE THREAD

**Issue by joseojedaf** [briannesbitt/Carbon#2054]
>>> use Carbon\Carbon;

>>> Carbon::now()

=> Carbon\Carbon @1585679387 {#3272
     date: 2020-03-31 12:29:47.727844 America/Costa_Rica (-06:00),
   }

>>> Carbon::now()->subMonth()

=> Carbon\Carbon @1583173805 {#3274
     date: 2020-03-02 12:30:05.833899 America/Costa_Rica (-06:00),
   }

>>>

**Comment by geidsonc** [comment]
Hello. I was having the same problem. Solved when I started using the `subMonthNoOverflow` method.

**Comment by geidsonc** [comment]
For more informations read in [https://carbon.nesbot.com/docs/#overflow-static-helpers] https://carbon.nesbot.com/docs/#overflow-static-helpers

**Comment by kylekatarnls** [comment]
See #2047
