### ISSUE TITLE
startOfMonth() problem (very very very specific, rare use case)

### ISSUE THREAD

**Issue by sizijay** [briannesbitt/Carbon#2064]
Hello,

I encountered an issue with the following code:
```
printf(Carbon::createFromDate( 2020, 2, NULL )->startOfMonth()->format( 'jS F Y' ));
//Executed on 2020/03/31 (current date should be 31 [maybe 30 as well])
//printf(Carbon::createFromDate( 2020, 2, 31 )->startOfMonth()->format( 'jS F Y' ))
```

Carbon version: **This happens with every version**

PHP version: **Latest**

Condition: **This is very specific. Let's say today is 2020/03/31. So that NULL above gets the value 31. Then when we get the start of the Month, it returns March 1st instead of Feb 1st. I think this is a bug. Please  fix it.
Basically this happens when the current date is beyond the maximum date of given month**

I expected to get:

```
1st February 2020
```

But I actually get:

```
1st March 2020
```

Thanks!

**Comment by kylekatarnls** [comment]
Hello,

This is the PHP behavior. When creating a invalid date, it overflow the extra days on the next month:

See https://3v4l.org/EnjUj
```php
$date = new DateTime('2020-02-31');

echo $date->format('Y-m-d');
```

We get a date on 2020-03-02 and we have now way to know you want a date in February.

Some users may want to get the $n day of the year using this behavior:
```php
Carbon::createFromDate(2020, 1, $n);
```
If $n is between 1 and 31, you get a January date, from 32 to 61, February, from 62 to 93, March, etc. Those users would probably not appreciate if we forced all those dates to become Januray 31st suddenly at the next version.

Also `Carbon` aims to stay compatible whenever possible with the `DateTime` class it extends.

The solution is simple: don't create invalid dates, check it before and decide your own handling of invalid dates, as what to do when invalid can lead to very different expectations from one application to an other.

Thanks,

**Comment by kylekatarnls** [comment]
Note: Why `Carbon::createFromDate(2020, 2, 31)->startOfMonth()` rather than simply `Carbon::createFromDate(2020, 2)` which would already give you the start of month?

**Comment by sizijay** [comment]
Hi @kylekatarnls ,
Thank you for the clarification. Using the way you mentioned worked. The problem was that I had set a null value from the API side if a date is not pseed from the client. So I hard coded a default value. Now it works. 
Thank You

Regards,
Sisira
