### ISSUE TITLE
Inconsistent behavior of DatePeriod and CarbonPeriod

### ISSUE THREAD

**Issue by claytonrcarter** [briannesbitt/Carbon#2072]
Hello,

Perhaps this is the intended behavior, but I think I've found an inconsistency in the behavior of DatePeriod and CarbonPeriod, which can be demonstrated by this code:
```php
<?php

require 'vendor/autoload.php';

use Carbon\CarbonPeriod;

$params = [
    new DateTime(date('Y-m-d', strtotime("Apr 27 +3 days"))),
    new DateInterval('P1D'),
    new DateTime(date('Y-m-d', strtotime("Apr 27 +17 days")))
];

$datePeriod = new DatePeriod(...$params);
$carbonPeriod = new CarbonPeriod(...$params);

echo "DatePeriod: " . count(iterator_to_array($datePeriod));
echo "\n";
echo "CarbonPeriod: " . count(iterator_to_array($carbonPeriod));
```

Carbon version: 2.32.2

PHP version: 7.4.1

[Try Carbon reproduction example](https://try-carbon.herokuapp.com/?embed&theme=xcode&border=silver&options-color=rgba(120,120,120,0.5)&input=%0A%24params%20%3D%20%5B%0A%20%20%20%20new%20DateTime(date(%27Y-m-d%27%2C%20strtotime(%22Apr%2027%20%2B3%20days%22)))%2C%0A%20%20%20%20new%20DateInterval(%27P1D%27)%2C%0A%20%20%20%20new%20DateTime(date(%27Y-m-d%27%2C%20strtotime(%22Apr%2027%20%2B17%20days%22)))%0A%5D%3B%0A%20%20%0A%24datePeriod%20%3D%20new%20DatePeriod(...%24params)%3B%0A%24carbonPeriod%20%3D%20new%20CarbonPeriod(...%24params)%3B%0A%0Aecho%20%22DatePeriod%3A%20%22%20.%20count(iterator_to_array(%24datePeriod))%3B%0Aecho%20%22%5Cn%22%3B%0Aecho%20%22CarbonPeriod%3A%20%22%20.%20count(iterator_to_array(%24carbonPeriod))%3B%0A%0A)

I expected to get:

```
DatePeriod: 14
CarbonPeriod: 14
```

But I actually get:

```
DatePeriod: 14
CarbonPeriod: 15
```

Thanks!

**Comment by kylekatarnls** [comment]
Hello, it's changed on purpose as explained in the documentation:

> Thus it will give one less result when the start date is excluded. [...] For that reason we changed the implementation slightly, and recurrences are treated as an overall limit for number of returned dates.
> ```php
> // Possible options are: CarbonPeriod::EXCLUDE_START_DATE | CarbonPeriod::EXCLUDE_END_DATE
> // Default value is 0 which will have the same effect as when no options are given.
> $period = CarbonPeriod::createFromIso('R4/2012-07-01T00:00:00Z/P7D', CarbonPeriod::EXCLUDE_START_DATE);
> $dates = [];
> foreach ($period as $date) {
>     $dates[] = $date->format('m-d');
> }
> 
> echo implode(', ', $dates); // 07-08, 07-15, 07-22, 07-29
> ```

This flag gives you the output you expect:
```php
$params = [
    new DateTime(date('Y-m-d', strtotime("Apr 27 +3 days"))),
    new DateInterval('P1D'),
    new DateTime(date('Y-m-d', strtotime("Apr 27 +17 days")))
];
  
$datePeriod = new DatePeriod(...$params);
$carbonPeriod = new CarbonPeriod(...$params);
$carbonPeriod->excludeStartDate();
// excludeStartDate is short-cut for ->setOptions(CarbonPeriod::EXCLUDE_START_DATE)
// Or in one line
// CarbonPeriod::create(...$params)->excludeStartDate()

echo "DatePeriod: " . count(iterator_to_array($datePeriod));
echo "\n";
echo "CarbonPeriod: " . count(iterator_to_array($carbonPeriod));
```

I hope this option is fine for you.

**Comment by claytonrcarter** [comment]
Duh, sorry. Another case of #rtfm 

Thanks again.

**Comment by kylekatarnls** [comment]
I know our doc is pretty long and this was quite a big question when implementing to keep or not this unintuitive behavior of DatePeriod.
