### ISSUE TITLE
Uses Kyrgyz instead of Uzbek translation

### ISSUE THREAD

**Issue by GeneralCheesecake** [briannesbitt/Carbon#2074]
Hello,

I encountered an issue with the following code:
```php
echo Carbon::parse("2020-03-02 11:01:26")->locale('uz')->diffForHumans();
```

Carbon version: 2.27.0

PHP version: 7.2.24-0ubuntu0.18.04.3

I expected to get:

```
2 oy oldin 
```
(2 months ago in Uzbek, according to Google Translate)

The language code for Uzbek should be 'uz', which I used as a parameter

But I actually get:

```
Бир неча 2 ой олдин 
```
(A few 2 months ago in Kyrgiz, according to Google Translate)

The language code for Kyrgiz should be 'ky'. When I use that as a parameter I get the following:
```
2 ай мурун
```
(2 months ago in Kyrgiz)

It seems that using 'uz' as parameter does not return real Uzbek, for that should be different, but it doesn't match with correct Kyrgiz as well. 

Thanks in advance!

**Comment by kylekatarnls** [comment]
Uzbek can be either Cyrillic or Latin, so what you're looking for is `uz_Latn` locale or a regional locale that use it such as `uz_UZ` I think.

**Comment by kylekatarnls** [comment]
I would avoid to change the whole current "uz" translations, as it would be a very unexpected change for users now using uz as Cyrillic variant. Unless there would be some official ISO reference mentionning uz locale should be latin by default.

**Comment by GeneralCheesecake** [comment]
Thank you for your clear answer. I did not know there were different versions of Uzbek. So thank you for clearing that up for me! I will look for a way to implement this in my code.
