### ISSUE TITLE
[Translation tool] si

### ISSUE THREAD

**Issue by MalindaWMD** [briannesbitt/Carbon#2076]
|English|si|comments|
|--|--|--|
|1 year|වසර|වසර 1|
|a year|වසර|වසරක්|
|1 month|මාසය|මාස 1|
|1 week|සතියක්|සති 1|
|1 day|දිනය|දින 1|
|a day|දිනය|දිනක් or එක් දිනක්|
|1 hour|පැය|පැය 1|
|an hour|පැය|පැයක්|
|1 minute|මිනිත්තුව|මිනිත්තු 1|
|a minute|මිනිත්තුව|මිනිත්තුවක්|
|1 second|තත්පර කිහිපය|තත්පර 1 or තත්පරයක්|
|a few seconds|තත්පර කිහිපය|තත්පර කිහිපයකට|
|2 hours before|before|පැය 2 කට පෙර|
|2 hours after|after|පැය 2 කට පසු|

**Comment by kylekatarnls** [comment]
Thanks for your help. I will double-check that and fix it in 2.34.

**Comment by kylekatarnls** [comment]
Hi, it's alright for the 1/a variants.

About after/before, it looks pretty similar to ago/from_now.

First, can you tell me if `පැය 2කට පෙර` is OK for "2 hours ago" or if we should add a space after `2`?

Then we should be able to distinguish "ago" (absolute past) from "before" (relative to an other date). See the following example:

> We will leave the office **2 hours before** the party begin.

Both of those events are in the future, but the first one is 2 hours "less in the future" than the second one.

Can you confirm `පැය 2 කට පෙර` will fit for such event in the future? And if yes, is there any way to have before/after translations with no ambiguity regarding to ago/from_now?

**Comment by MalindaWMD** [comment]
Hello,
For the first point, `පැය 2කට පෙර` is okay.

And for the second one, `පැය 2කට පෙර` can use for both `2 hours before` and `2 hours ago`, because for both **before** and **ago** `පෙර` can be used in Sinhala.

**Comment by kylekatarnls** [comment]
Please could you check the changes here:
https://github.com/briannesbitt/Carbon/pull/2083/files#diff-c606b54e7e9369ac03195584570fcd00
and verify that green lines are better than red lines for situation (code given in comment above)?

**Comment by MalindaWMD** [comment]
Hello,
Just took a rough look and I think there are more transactions that can be
improved.
Is there a way to make those amendments?

Also, I'll check this thoroughly in the coming week since I am a little
busy these days.

Thank you

**Comment by kylekatarnls** [comment]
The translation source is here:
https://github.com/briannesbitt/Carbon/blob/master/src/Carbon/Lang/si.php
And `si_LK` locale currently alias `si` (extends with no change).

They are used to generate the translated strings.

The test file SiTest.php is here:
https://github.com/briannesbitt/Carbon/blob/master/tests/Localization/SiTest.php
(and so https://github.com/briannesbitt/Carbon/blob/master/tests/Localization/SiLkTest.php should be identical if there is no "LK" region specificity).

It checks what output actually are, when running the code above.

You can submit a pull-request on those files.

If the current changes in #2083 are better than the current situation, I would prefer to merge it first, then you could do an other pull-request afterwards.

If you can only update the tests files, it's fine, you can push it as a PR and I will edit the source files.

**Comment by MalindaWMD** [comment]
Sure mate got you.

I'll make the necessary changes and PR.

Thanks
