### ISSUE TITLE
Calling week() does not work when there are 53 weeks in the year (e.g. 2015 or 2020)

### ISSUE THREAD

**Issue by jimmiw** [briannesbitt/Carbon#2077]
Hello,

I encountered an issue with the following code:
```php
echo Carbon::parse('2020-12-30')->week;
```

Carbon version: **2.33.0**

PHP version: **7.3.11**

I also tested this on the "try-carbon" app, so it's not my PHP version that is causing the issue.

Link to the exported script is here: https://try-carbon.herokuapp.com/?embed&theme=xcode&border=silver&options-color=rgba(120,120,120,0.5)&input=%24date%20%3D%20Carbon%3A%3Aparse(%272020-12-30%27)%3B%0Aecho%20%27calling%20week()%3A%20%27%20.%20%24date-%3Eweek()%20.%20%22%5Cn%22%3B%0A%2F%2F%20expected%20result%20is%2053%0Aecho%20%27expected%3A%20%27%20.%20%24date-%3Eformat(%27W%27)%3B

I expected to get:

```
53
```

But I actually get:

```
1
```

According to google calendar, there is a week 53 in 2020. (also in 2015 btw).

NOTE: the internal week actually works in Carbon (Datetime), since format('W') gives the correct result:
```php
echo Carbon::parse('2020-12-30')->format('W'); // works
```

Thanks!

**Comment by kylekatarnls** [comment]
Hello,

Week number depends on the locale (language and region). If you want the Denmark usual week number, you need to use:

```php
$date->locale('da_DK')->week()
```

This will gives you 53.

**Comment by jimmiw** [comment]
Why does format() take a locale (which I did not set on you test app) into consideration, if your week() doesn't? Wouldn't the expected behaviour be, that these two match each other?

**Comment by kylekatarnls** [comment]
Both are not related, `format()` is a method of `DateTime` (which `Carbon` extends) and does not support internationalization:
https://www.php.net/manual/en/datetime.format.php

And the code `W` is explicitly (as per PHP documentation) ISO-8601 week number of year.

While `week()` and `week` are from `Carbon` class which support internationalization and use `en_US` as default locale. There is a dedicated chapter in our documentation:
https://carbon.nesbot.com/docs/#api-week
