### ISSUE TITLE
Ukrainian weekdays not in array

### ISSUE THREAD

**Issue by denisdulici** [briannesbitt/Carbon#2081]
Hello,

I encountered an issue with the following code:
```php
echo Carbon::parse('2020-05-09')->toDateString();
```

Carbon version: **2.33.0**

PHP version: **7.3.9**

I expected to get:

```
2020-05-09
```

But I actually get:

![Screenshot - 2020-05-09T104016 998](https://user-images.githubusercontent.com/5254835/81467475-83047d00-91e1-11ea-88a5-3589b238dce4.png)

This happens only in Ukrainian language.

https://github.com/briannesbitt/Carbon/blob/master/src/Carbon/Lang/uk.php#L197

Thanks!

**Comment by kylekatarnls** [comment]
Hi, I can't reproduce it with the code you give:
```php
$d = Carbon::parse('2020-05-09')->locale('uk');
echo $d->toDateString();
echo "\n";

Carbon::setLocale('uk');
$d = Carbon::parse('2020-05-09');

echo $d->toDateString();
echo "\n";
```
Both display pretty well.

Please recheck all you settings. Did you customize the `toDateString` format?

Then provide a minimal standalone code to reproduce the bug. Ideally reproduce it on https://try-carbon.herokuapp.com/ so I can have the exact same result.

**Comment by kylekatarnls** [comment]
I'm not sure it's your bug but I was able to get the same error with the code:
```php
Carbon::parseFromLocale('-1 хвилина', 'uk');
```

**Comment by denisdulici** [comment]
Thanks @kylekatarnls for your prompt response. Not sure if it's related but we extend Carbon via [this](https://github.com/akaunting/akaunting/blob/master/app/Utilities/Date.php) class.

**Comment by kylekatarnls** [comment]
Yeah, it's related, this wrapper takes days of the week and replace them in the input string you pass to parse. It comes initially from Jenssegers/Date which does not handle such language declination using closures. I will make it compatible with closures.
