### ISSUE TITLE
Non-static method Carbon\CarbonPeriod::overlaps() should not be called statically

### ISSUE THREAD

**Issue by abewartech** [briannesbitt/Carbon#2087]
Hello,

I encountered an issue with the following code:
```php
echo CarbonPeriod::overlaps($range, $range2);
```

Carbon version: 2.33.0

PHP version: 7.3.16

I also tested this on the "try-carbon" app, so it's not my PHP version that is causing the issue.

Link to the exported script is here: https://try-carbon.herokuapp.com/?embed&theme=xcode&border=silver&options-color=rgba(120,120,120,0.5)&input=%24range%20%3D%20CarbonPeriod%3A%3Acreate(%222020-05-01T07%3A02%3A03.171Z%22%2C%20%222020-05-01T10%3A02%3A03.171Z%22)%3B%0A%24range2%20%3D%20CarbonPeriod%3A%3Acreate(%222020-05-01T07%3A02%3A03.171Z%22%2C%20%222020-05-01T10%3A02%3A03.171Z%22)%3B%0Aecho%20CarbonPeriod%3A%3Aoverlaps(%24range%2C%20%24range2)%3B

I expected to get: 

```
true
```

But I actually get:

```
Error: Non-static method Carbon\CarbonPeriod::overlaps() should not be called statically
```

Thanks!

**Comment by Farhatdjehan** [comment]
same here bro

**Comment by kylekatarnls** [comment]
Yes, you get this error because the method isn't static. Use it as it is shown in the documentation (https://carbon.nesbot.com/docs/#api-period):
```php
$range->overlaps($range2)
```

Thanks.
