### ISSUE TITLE
🌎 [Translation tool] lv - Latvian

### ISSUE THREAD

**Issue by NihilScio** [briannesbitt/Carbon#2091]
|English|lv|comments|
|--|--|--|
|2 years|2 gadiem|2 gadi / Because '2 gadiem' is Dativum and it means 'For whom' .. 'For 2 years'|
|2 months|2 mēnešiem|2 mēneši .. Because '2 mēnešiem' means 'for 2 months'.|
|1 month|1 mēneša|1 mēnesis|
|a month|mēneša|mēnesis|
|2 weeks|2 nedēļām|2 nedēļas|
|1 week|1 nedēļas|1 nedēļa|
|2 days|2 dienām|2 dienas|
|2d|2 dienām|2 d.|
|1 day|1 dienas|1 diena|
|2 hours|2 stundām|2 stundas|
|1 hour|1 stundas|1 stunda|
|2 minutes|2 minūtēm|2 minūtes|
|2 seconds|2 sekundēm|2 sekundes|
|1 second|1 sekundes|1 sekunde|
|January|janvārī|janvāris. Because 'janvārī' means where (Lokativum) - 'in January'|
|February|februārī|februāris|
|March|martā|marts|
|April|aprīlī|aprīlis|
|May|maijā|maijs|
|June|jūnijā|jūnijs|
|July|jūlijā|jūlijs|
|August|augustā|augusts|
|September|septembrī|septembris|
|October|oktobrī|oktobris|
|November|novembrī|novembris|
|December|decembrī|decembris|
|2 hours before|2 stundas pirms|pirms 2 stundām|

----
In Latvian prepositions like 'in' are shown at the end of the noun. For instance, 'January' is in Nominativum - 'Janvāris'. However, if you would like to say 'I started a project in January' - you would have to say '.. janvārī', and 'ī' shows 'in'. In the January'.

If it helps, I'm ready to assist with Latvian translation also further. Just write me an email.

**Comment by kylekatarnls** [comment]
Months are very likely to be displayed in date (in the future, the past, in recurrences).

And time intervals so to have a different translation of "2 hours" according to the context (2 stundas/2 stundām with "before"), we use a declension system.

See for instance:
https://github.com/briannesbitt/Carbon/blob/master/src/Carbon/Lang/cs.php

It uses 'month_ago' měsícem while 'month' is měsíc.

And there are closure functions for before/after that take the time and transform it according to the language declensions.

Latvian already have after/before declensions:
https://github.com/briannesbitt/Carbon/blob/master/src/Carbon/Lang/lv.php

But we don't have particular translation for "for" (if you're talking about "how long it last"). Actually we can't know the user will put the duration in a sentence using "for". We would have to provide an additional `diffForHumans()` option for that.

Else you can see the result of the translation in the tests:
https://github.com/briannesbitt/Carbon/blob/master/tests/Localization/LvTest.php

For example, you can see "Tomorrow at (time)" is not translated. This would need to add the `calendar` array in lv.php (see https://github.com/briannesbitt/Carbon/blob/master/src/Carbon/Lang/fr.php#L71 as an example)

If you can add missing translations and fix the translation file either on the [source file](https://github.com/briannesbitt/Carbon/blob/master/src/Carbon/Lang/lv.php) or the [test file](https://github.com/briannesbitt/Carbon/blob/master/tests/Localization/LvTest.php), it would be awesome. If you can do only once, I can handle the other according to your fixes.
