### ISSUE TITLE
Problem with the version for php 7.4.6

### ISSUE THREAD

**Issue by omexlu** [briannesbitt/Carbon#2100]
Good afternoon,

I had previously installed the version for php 7.1.33, today I wanted to update to the version for 7.4.6 via composer.

But the following lines causes me problems here, something with bool:
`return Carbon::parse($dateDatePassedOrFuture)->setLocale($setLanguage)->shortAbsoluteDiffForHumans(Carbon::parse($dateDateNow), $dateParts);`

Call:
`timeAgoOrFuture(date("Y-m-d H:i:s"), '2019-12-10 21:23:00', 3)`

Can you help me understand why this error occurs?

The line with the return makes the problems here, before this worked without problems.

Vielen Dank.

**Comment by kylekatarnls** [comment]
Hello,

There is no such thing like "version for php 7.1.33" or "version for 7.4.6" All the version of Carbon >= 2 are compatible with PHP from 7.1.8 to 8-dev as you can see in our Travis build:
https://travis-ci.org/github/briannesbitt/Carbon/builds/690684950

To help you, we need all the informations we asked you in our issue template:
- [ ] your Carbon version;
- [x] your PHP version;
- [ ] a minimal code chunk to reproduce your case;
- [ ] the current output of this code;
- [ ] the output you expect.

The code you give is not reproductible (it contains variables I can't guess the values).

And you don't say what is the problem: I need the exact error and the complete stack trace.

Thank you.

**Comment by omexlu** [comment]
The current version of php 7.4.6, the latest version of Carbon (composer).

`echo Carbon::parse('2020-06-02 21:23:00')->setLocale('de')->shortAbsoluteDiffForHumans(Carbon::parse(2019-12-10 21:23:00), 3);`

I can't not give you exactly the because i reinstalled the backup but something with bool, i don't know what is from with the code above. It worked since 2019 and now i updated an give me this book error only on this row.

If i comment it out, the website works again, so i think somethink is wrong in this row above in the syntax.

**Comment by omexlu** [comment]
Yes but the error come here from shortAbsoluteDiffForHumans some seems to be wrong, please take a look at the row if this is correct.

**Comment by kylekatarnls** [comment]
As per our documentation, since `setLocale()` was introduced (in Carbon 1.18) it was never meant to return a `Carbon` instance, it returns a boolean value:

> Carbon::setLocale
> $locale
> returns bool

So you're trying to do:

```php
true->shortAbsoluteDiffForHumans()
```

This does not work in PHP and there is nothing our library could do about that.

**Comment by omexlu** [comment]
But it worked before... I'm used it for about a year this way

echo Carbon::parse('2020-06-02 21:23:00')->shortAbsoluteDiffForHumans(Carbon::parse('2019-12-10 21:23:00'), 3)->locale('de');

This may maybe?

**Comment by kylekatarnls** [comment]
"before" means nothing to me. Please provide Carbon version _numbers_.

The valid code with Carbon 2.35 for what I suppose to be your expected output (you didn't give neither) is:
```php
echo Carbon::parse('2020-06-02 21:23:00')->locale('de')->shortAbsoluteDiffForHumans(Carbon::parse('2019-12-10 21:23:00'), 3);
```

"modifty this now" What modification? What for?

I'm really sorry. I do my very best with the very few input I have.

**Comment by omexlu** [comment]
I do not want to show the difference of these two data in human readable forum more :) (in the language German)

I thank you for that :)

**Comment by omexlu** [comment]
I tried again, but get errors here because of symphony translation.
This package is not installed.

Do you need it recently and if so, which packages do I have to include here?

Couldn't find anything in the docs?

**Comment by kylekatarnls** [comment]
symfony/translation is here since 1.18.0 (February 2015): https://github.com/briannesbitt/Carbon/commit/fcacc6c3e33c17d6663eb08020c0451fcffd96ef

It's installed automatically via `composer update` or `composer install` like any other sub-dependencies you may have.

And it's also installed in the stand-alone package, so there is nothing to document about this.

**Comment by omexlu** [comment]
Okay but why i get this error and 500, i just updated to actual version and take a simple example from docs to test, but i get this error:
`2020/06/03 10:45:22 [error] 101050#101050: *629260 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Carbon\CarbonInterval::setLocalTranslator() must implement interface Symfony\Component\Translation\TranslatorInterface, instance of Carbon\Translator given, called in /var/www/domain.tld/public/vendor/nesbot/carbon/src/Carbon/Traits/Difference.php on line 778 and defined in /var/www/domain.tld/public/vendor/nesbot/carbon/src/Carbon/Traits/Localization.php:154
Stack trace:
#0 /var/www/domain.tld/public/vendor/nesbot/carbon/src/Carbon/Traits/Difference.php(778): Carbon\CarbonInterval->setLocalTranslator()
#1 /var/www/domain.tld/public/includes/functions.php(178): Carbon\Carbon->diffForHumans()
#2 /var/www/domain.tld/public/includes/globalTplvars.php(13): timeAgoOrFuture()
#3 /var/www/domain.tld/public/index.php(158): include('/var/www/home.s...')
#4 {main}
  thrown in /var/www/domain.tld/public/vendor/nesbot/carbon/src/Carbon/Traits/Localization.php on line 154" while reading response header from upstream, client: 94.242.219.130, server: domain.tld, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.4-fpm-domain.tld.sock:", host: "domain.tld"
`

**Comment by kylekatarnls** [comment]
You installed the last packages (including Symfony 5 translation package) that requires PHP 7.2 and you're trying to run it with PHP 7.1 (this message only happen when you run PHP 7.1 version), that can't work. You need to upgrade the version used by your FastCGI.

**Comment by omexlu** [comment]
No.... fastcgi://unix:/var/run/php/php7.4-fpm-domain.tld.sock: => php 7.4.6 is running

And i get this message.

**Comment by kylekatarnls** [comment]
For the Nth time, I also need you nesbot/carbon exact version and symfony/translation exact version.

**Comment by omexlu** [comment]
As i said before, the actual version that i get when running 'composer update' under php 7.4.6

**Comment by omexlu** [comment]
I have only included this 'use':
use Carbon\Carbon;

Do i need to include some other 'uses' to get working translations?
