### ISSUE TITLE
Range not working as expected

### ISSUE THREAD

**Issue by dangerdan** [briannesbitt/Carbon#2110]
Hello,

I encountered an issue with the following code:
```php
$fromDate = Carbon::now()->setTimeFromTimeString('09:00');
$toDate = Carbon::now()->setTimeFromTimeString('17:00');
$period = $fromDate->range($toDate, 1, 'hours')->toArray();
        
echo count($period);
```

Carbon version: 2.35.0

PHP version: 7.4.6

I expected to get:

```
8
```
But I actually get:

```
9
```

Apologies if i'm not understanding range correctly, what am I doing wrong?

**Comment by kylekatarnls** [comment]
Hello,

By default, it will include you start and end, so you need to exclude either the start or the end to get 8, I don't know which one you want to get rid of, so here are all the possibilities:

```php
$fromDate = Carbon::now()->setTimeFromTimeString('09:00');
$toDate = Carbon::now()->setTimeFromTimeString('17:00');

$period = $fromDate->range($toDate, 1, 'hours')->toArray();
print_r(array_map('strval', $period));

$period = $fromDate->range($toDate, 1, 'hours')->options(CarbonPeriod::EXCLUDE_START_DATE)->toArray();
print_r(array_map('strval', $period));

$period = $fromDate->range($toDate, 1, 'hours')->options(CarbonPeriod::EXCLUDE_END_DATE)->toArray();
print_r(array_map('strval', $period));

$period = $fromDate->range($toDate, 1, 'hours')->options(CarbonPeriod::EXCLUDE_START_DATE | CarbonPeriod::EXCLUDE_END_DATE)->toArray();
print_r(array_map('strval', $period));
```

More documentation about those options can be found here:
https://carbon.nesbot.com/docs/#api-period

Thank you.

**Comment by dangerdan** [comment]
Thank you for the fast response! My Mac struggles with the size of the documentation page and Cmd+F find doesn't work as expected so maybe that could be looked into/improved to avoid questions like my own! :)
