### ISSUE TITLE
Issue getting certain Abbreviated Timezone Names

### ISSUE THREAD

**Issue by DGeoWils** [briannesbitt/Carbon#2111]
Hello again,

We have run into issues getting abbreviated names for timezones on certain timezones. These include: Australia/Eucla, Pacific/Marquesas, Asia/Katmandu, and potentially others

Here is encountered an issue with the following code:
```php
$timezone = new CarbonTimeZone("Pacific/Marquesas");
echo $timezone->toRegionName(); // "Pacific/Marquesas"
echo "\n";
echo $timezone->getAbbreviatedName(); // "unknown" -- expected "mart"
```

Carbon version: dev-master

PHP version: 7.2.26

Thanks!

**Comment by kylekatarnls** [comment]
The following pure-PHP code:
```php
var_dump(new DateTimeZone("mart"));
```

Output:
```
Error: DateTimeZone::__construct(): Unknown or bad timezone (mart)
```

I'm afraid if PHP itself does not support this abbreviated name, then there is no chance we could implement it unless we would maintain our own custom matching array and it should be updated as even if it's rare timezones can change over years.

I would be OK to review it if you would like to propose a pull-request for this but I would need:
- to have an official data source reference, ideally a source that can be extracted with a script to remained synchronized with,
- find out if there is a reason for this timezone abbreviated not to be handled by PHP.
