### ISSUE TITLE
Unable to use doctrine types with doctrine migrations bundle

### ISSUE THREAD

**Issue by jon-ht** [briannesbitt/Carbon#2117]
Hello,

I encountered an issue when using Carbon Doctrine types with migrations on a SF project. you can find a repro here https://github.com/jon-ht/nesbot-doctrine-datetime

> Run `make start` or `make db` after your first fail

If you comment these lines https://github.com/jon-ht/nesbot-doctrine-datetime/blob/5cfda4b65829baea9a0edb8ec96efd10b7aad76b/config/packages/doctrine.yaml#L5-L7 migration table should be up and you will see `Could not find any migrations to execute.`

Carbon version: **2.35.0**

PHP version: **7.4.3**

I expected to get:

Migration table created with correct columns

But I actually get:

```
docker-compose -f docker-compose.yml -f etc/dev/docker-compose.yml -f etc/dev/docker-compose.windows.yml exec -T php sh -lc './bin/console d:m:m -n'

In AbstractMySQLDriver.php line 106:

  An exception occurred while executing 'CREATE TABLE migration_versions (ver
  sion VARCHAR(14) NOT NULL, executed_at DATETIME(10) NOT NULL COMMENT '(DC2T
  ype:datetime_immutable)', PRIMARY KEY(version)) DEFAULT CHARACTER SET utf8m
  b4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB':

  SQLSTATE[42000]: Syntax error or access violation: 1426 Too-big precision 1
  0 specified for 'executed_at'. Maximum is 6.


In PDOConnection.php line 43:

  SQLSTATE[42000]: Syntax error or access violation: 1426 Too-big precision 1
  0 specified for 'executed_at'. Maximum is 6.


In PDOConnection.php line 41:

  SQLSTATE[42000]: Syntax error or access violation: 1426 Too-big precision 1
  0 specified for 'executed_at'. Maximum is 6.
```

Thanks!

**Comment by kylekatarnls** [comment]
Hello,

Could you try to add `\Carbon\Doctrine\DateTimeDefaultPrecision::set(6)` in `registerBundles()` in **src/Kernel.php** please?

Thank you.

**Comment by jon-ht** [comment]
Thanks for your reply,

It didn't work because when execution reach this line, `$fieldDeclaration['precision']` has a value of 10 https://github.com/briannesbitt/Carbon/blob/d9d633f411289f6e048add6fcf7e34fd48cdafd0/src/Carbon/Doctrine/CarbonTypeConverter.php#L25

**Comment by kylekatarnls** [comment]
Indeed, something is pretty wrong in there in Doctrine:
```php
    public function setPrecision($precision)
    {
        if (! is_numeric($precision)) {
            $precision = 10; // defaults to 10 when no valid precision is given.
        }

        $this->_precision = (int) $precision;

        return $this;
    }
```
This applies to any column, and this override any particular per-type default value we could try to set.

We previously assumed that 9 was the maximum supported precision for dates and 10 was considered as default precision, but this has been lost in this merge:

https://github.com/briannesbitt/Carbon/commit/7fe08deb42f68327e5046d4c107d67ad34b8f890#diff-c2e936310dd03f393c9e80428e0624e6L24

I will double-check it does not break something else and revert this regression if so.
