### ISSUE TITLE
Incorrect annotation in Comparison

### ISSUE THREAD

**Issue by kirya-dev** [briannesbitt/Carbon#2125]
Hello! I encountered an issue with the following code:
```php
function echoDate(Carbon\Carbon $date) {
//...
}
echoDate(Carbon::tomorrow());
```

I get error in PHPStan (level 5):
`Parameter #1 $date of method echoDate() expects Carbon\Carbon, Carbon\CarbonInterface given.`          

Carbon version: 2.35.0

PHP version: 7.4

I expected to get no errors.

Bug occurs because in this lines:
https://github.com/briannesbitt/Carbon/blob/master/src/Carbon/Traits/Comparison.php#L29-L30

Please just remove them =)

**Comment by kylekatarnls** [comment]
Hello,

This annotation is here to make the dependence of the trait explicit.

And I think PHPStan should give the precedence to the actual method PHPDoc over annotations:
```php
    /**
     * Create a Carbon instance for tomorrow.
     *
     * @param DateTimeZone|string|null $tz
     *
     * @return static
     */
    public static function tomorrow($tz = null)
```

**Comment by kylekatarnls** [comment]
Using `Carbon|CarbonImmutable` raise an error on level 7+, while `CarbonInterface` raise it on 5+. Not sure to understand the logic.

**Comment by kylekatarnls** [comment]
`static` sounds to work correctly even if it's less precise for the dependency documentation.
