### ISSUE TITLE
[Translation tool] pa

### ISSUE THREAD

**Issue by RamnSingh** [briannesbitt/Carbon#2129]
|English|pa|comments|
|--|--|--|
|2 hours ago|2 ਘੰਟੇ ਪਿਛਲੇ|2 ਘੰਟੇ ਪਹਿਲਾਂ|
|2 hours before|before|2 ਘੰਟੇ ਤੋਂ ਪਹਿਲਾਂ|
|2 hours after|after|2 ਘੰਟੇ ਤੋਂ ਬਾਅਦ|

----
Digits are being represented in latin script which is the only thing missing. In Panjabi, digits are : ੦ ੧ ੨ ੩ ੪ ੫ ੬ ੭ ੮ ੯ (0 to 9). But these digits are not being used by Panjabi people in thier daily routines thay use latin script digits. But the real Panjabi digitS are in trend now maybe in few upcoming years you guys need to update it to Panjabi digits.

**Comment by kylekatarnls** [comment]
Hello,

Alternative numbers are an option to enable. When implemented you will be able to choose either Arabic numerals or local ones:
```php
echo Carbon::now()->subHours(8)->locale('pa')->ago(['altNumbers' => true]);
```

**Comment by kylekatarnls** [comment]
You can now check the new translations in unit tests:
https://github.com/briannesbitt/Carbon/pull/2131/files#diff-4cf88e803063b0a12cfbb28575ea0dd9

Thanks,
