### ISSUE TITLE
Allowing overflow false for CarbonInterval and CarbonPeriod

### ISSUE THREAD

**Issue by wildcard27** [briannesbitt/Carbon#2133]
Hello,

I encountered an issue with the following code:
```php
$di = CarbonInterval::create('P1M');
$end = CarbonImmutable::parse('10 april 2020')->startOfDay();
$diff = CarbonImmutable::parse('31 january 2020')
    ->startOfDay()
   ->toPeriod($end, $di)
   ->settings(['monthOverflow' => false]);

$items = [];
foreach ($diff as $item) {
    echo $item->format('Y-m-d');
}
```

Carbon version: 2.36.1

PHP version: 7.3.13

I expected to get:

```
2020-01-31
2020-02-29
2020-03-30
```

But I actually get:

```
2020-01-31
2020-03-02
2020-04-02
```

There are similar issues and suggestions out there such as using

```
CarbonImmutable::parse('31 january 2020')->addMonthsNoOverflow()
```

But this does not work if using `CarbonInterval` or `CarbonPeriod` which is required when creating a list of dates between others using a dynamically generated `DateInterval`.

The fact that you can set the `'monthOverflow' => false` setting is just adding to the confusion and annoyance.

Thanks!

**Comment by kylekatarnls** [comment]
Hello,

Good news, `CarbonInterval` actually support dynamic intervals:

```php
$di = CarbonInterval::create(function (CarbonImmutable $date) {
  return $date->addMonthNoOverflow();
});
$end = CarbonImmutable::parse('10 april 2020')->startOfDay();
$diff = CarbonImmutable::parse('31 january 2020')
    ->startOfDay()
    ->toPeriod($end, $di);
```

The `monthOverflow` will apply for "pure" methods such as: addMonth, but not for string intervals like: 'P1M'.

When it's a string, you can do `'P1M10D'` and here as you can guess, there is now way mix 10 days + 1 months without overflow (as the native PHP behavior is the overflow).

I hope the closure interval is fine for you app.

**Comment by wildcard27** [comment]
Unfortunately this still does not return the correct result. All it is doing is adding a month without overflow and starting the period from there. This returns the result set:

```
2020-02-29
2020-03-29
```

**Comment by kylekatarnls** [comment]
Period may not be the right tool.

Your problem looks similar to https://stackoverflow.com/questions/51295911/set-next-month-payment-date-with-php-carbon#answer-51297980

```php
$end = CarbonImmutable::parse('10 april 2020')->startOfDay();
$date = CarbonImmutable::parse('31 january 2020')->startOfDay();

for ($i = 0; $date < $end; $i++) {
  $date = $date->addMonthsNoOverflow($i);
  echo $date->format('Y-m-d') . "\n";
}
```

**Comment by wildcard27** [comment]
Close. Let me correct your code for anyone playing at home:

```php
$endDate = CarbonImmutable::parse('10 april 2020')->startOfDay();
$startDate = CarbonImmutable::parse('31 january 2020')->startOfDay();

$workingDate = Carbon::instance($startDate);

for ($i = 0; $workingDate <= $endDate; $i++) {
    $workingDate = $startDate->addMonthsNoOverflow($i);
    echo $workingDate->format('Y-m-d');
}
```

**Comment by kylekatarnls** [comment]
I see the point, I recommend not to mix mutable and immutable. Actually I just mistaken the variable name, but you don't need the extra instanciation of `$workingDate`:
```php
$end = CarbonImmutable::parse('10 april 2020')->startOfDay();
$start = CarbonImmutable::parse('31 january 2020')->startOfDay();

for ($i = 0; $date < $end; $i++) {
  $date = $start->addMonthsNoOverflow($i);
  echo $date->format('Y-m-d') . "\n";
}
```

**Comment by wildcard27** [comment]
Ah, but you do. Otherwise `$date` is undefined. Even if you mean `$date` to be `$startDate`, that would put you in an infinite loop

**Comment by wildcard27** [comment]
Also, I have just tried:
```php
$end = CarbonImmutable::parse('10 april 2020')->startOfDay();
$start = Carbon::parse('31 january 2020')->startOfDay();

for ($i = 0; $start < $end; $i++) {
    $date = $start->addMonthsNoOverflow($i);
    echo $date->format('Y-m-d');
}
```
This adds `$i` to the ever-increasing, muteable `$startDate`. I see no other way around than with my separate `$workingDate` variable.

**Comment by kylekatarnls** [comment]
Indeed, the 3rd variable created before the loop seems the right thing to do. I would still recommend to have all the date as immutable:

```php
$endDate = CarbonImmutable::parse('10 april 2020')->startOfDay();
$startDate = CarbonImmutable::parse('31 january 2020')->startOfDay();

$workingDate = $startDate->copy();

for ($i = 0; $workingDate <= $endDate; $i++) {
    $workingDate = $startDate->addMonthsNoOverflow($i);
    echo $workingDate->format('Y-m-d');
}
```

**Comment by wildcard27** [comment]
I like the `copy()` idea. This seems to work and is much easier on the eye!

I also have to correct myself. My previous solution added `2020-04-30`. This is > `2020-04-10` so should not be included. The solution is to switch the date set and the `echo`. I have also included the possibility for adding a dynamic number of months for free (since this is what my code calls for):

```php
$endDate = CarbonImmutable::parse('10 april 2020')->startOfDay();
$startDate = CarbonImmutable::parse('31 january 2020')->startOfDay();
$interval = CarbonInterval::create('P1M');

$workingDate = $startDate->copy();

for ($i = 1; $workingDate <= $endDate; $i = $i + $interval->m) {
    echo = $workingDate->format('Y-m-d') . "\n";
    $workingDate = $startDate->addMonthsNoOverflow($i);
}
```

There is much about this problem that is unclean, so there is a good chance the solution will be as such - unfortunately.

**Comment by kylekatarnls** [comment]
Indeed, you can include/exclude the start with initial value of `$i` with 0/1 and include/exclude the end date with `<=`/`<`.

I recommend not to use `CarbonInterval` for the customization, as it won't work with composite intervals (`P1M15D`). This will only work with an integer number of months, so the settings should be an integer too: `$i += $numberOfMonths`

**Comment by wildcard27** [comment]
I had thought of that. I don't have that issue in my app, thankfully! The only way to get around using composite intervals would be to count the number of days and add that.

I believe this falls outside of the scope of what I was looking to achieve in this issue but if I find myself needing it I will post my solution here for clarity.

Thanks for your help, Kyle. I really appreciate the small feedback loop!
