### ISSUE TITLE
More accurate information about isoFormat function ISO replacement patterns - docs

### ISSUE THREAD

**Issue by rafal-kanski-stp** [briannesbitt/Carbon#2145]
Hello,

I encountered an issue with the following code:
```php
echo Carbon::parse('2018-06-01')->isoFormat('G');
```

Which is located [here](https://github.com/briannesbitt/Carbon/blob/2.37.0/src/Carbon/Traits/Date.php#L2040)

Carbon version: **2.37.0**

PHP version: **7.2**

Basically, I would like to know what "ISO replacement patterns" are for `isoFormat` function. Seems for me it is like a mix of ISO-8601 and [icu](http://userguide.icu-project.org/formatparse/datetime). But maybe only one standard stands behind this. I'm really curious and could not find it anywhere in the documentation. Also tried to figure this out on my own and have not succeeded.

Thanks!

**Comment by kylekatarnls** [comment]
Hello,

It's explained in the [Localization chapter](https://carbon.nesbot.com/docs/#api-localization) this uses the norm ISO 8601, the same replacements can be found in momentjs.

If you scroll down this chapter, you'll find the complete table of the available replacements with an example and a description for each one:
https://carbon.nesbot.com/docs/#iso-format-available-replacements
