### ISSUE TITLE
⭐ Create toRfc3339ExtendedString method

### ISSUE THREAD

**Issue by xorock** [briannesbitt/Carbon#2146]
Carbon covers almost all php DateTime constants for different formats. Can You also add a shortand for https://www.php.net/manual/en/class.datetimeinterface.php#datetime.constants.rfc3339_extended ? It could be toRfc3339ExtendedString() or toRfc3339String(bool $extended = false).

Thanks!

**Comment by kylekatarnls** [comment]
Indeed this could be fairly added. I have no preference between `toRfc3339ExtendedString` or the `$extended`.

This is open to pull-request:

The method can be added after:
https://github.com/briannesbitt/Carbon/blob/master/src/Carbon/Traits/Converter.php#L398

And unit tests should be added after:
https://github.com/briannesbitt/Carbon/blob/master/tests/Carbon/StringsTest.php#L257

I would be happy to merge it.
