### ISSUE TITLE
can't get the six month

### ISSUE THREAD

**Issue by chenjianeng0201** [briannesbitt/Carbon#2147]
when i use subMonth() or subMonths(1) 
```
$birthdayMonth = carbon()->now()->subMonths(1)->month;
dd(carbon()->now()->toDateTimeString(), carbon()->now()->subMonths(1)->firstOfMonth()->toDateTimeString(), $birthdayMonth);
```
![image](https://user-images.githubusercontent.com/42136057/88991551-8e180680-d313-11ea-9c45-aa03775ec058.png)
when i use subMonths(2)
```
$birthdayMonth = carbon()->now()->subMonths(2)->month;
dd(carbon()->now()->toDateTimeString(), carbon()->now()->subMonths(2)->firstOfMonth()->toDateTimeString(), $birthdayMonth);
```
![image](https://user-images.githubusercontent.com/42136057/88991600-af78f280-d313-11ea-80e7-24bf59d46305.png)
so where is the six month or how can i get the six month, is this a bug?

**Comment by kylekatarnls** [comment]
See the [Addition/Subtraction chapter of the doc](https://carbon.nesbot.com/docs/#api-addsub).
Use `subMonthsNoOverflow`

Thanks.

**Comment by chenjianeng0201** [comment]
> subMonthsNoOverflow

it's work, thx
