### ISSUE TITLE
🌎 [Translation tool] es_MX

### ISSUE THREAD

**Issue by iksaku** [briannesbitt/Carbon#2149]
|English|es_MX|comments|
|--|--|--|
|2w|2sem|2 semanas|

**Comment by fitojb** [comment]
It’s supposed to be an abbreviated version. The current es_MX is okay; maybe I’d just add a (no-break) space between the number and the word.

**Comment by kylekatarnls** [comment]
Indeed, this will be used in abbreviated intervals such as: `2sem 4d 6h`.

d/h are standard unit and those have commonly no space before. Currently "sem" is appended with no space for consistency with d/h/m/s. But we could reconsider as años/meses (considered short enough to not being abbreviated) have no space either.

**Comment by iksaku** [comment]
Yeah, I think it would be worth keeping as "sem" but with a non breaking space before it.
