### ISSUE TITLE
Problem with starting day in week

### ISSUE THREAD

**Issue by filipzelic** [briannesbitt/Carbon#215]
I have read documentation and saw that you use by ISO8601 monday as a start of week. 
So for example, If now is saturday 2014-10-25 and I want to create Carbon object this way 
-    `new Carbon('saturday this week')` I will get object with `date => '2014-10-25 00:00:00.000000'` which is ok

And  if I try today (sunday 2014-10-26) to get it same way:
-    `new Carbon('sunday this week')` I will get object with `date => '2014-11-02 00:00:00.000000'` in another words next Sunday. I assume this happens because it thinks that sunday is new week (not monday) and this sunday represent day that is +7 from now

**Comment by briannesbitt** [comment]
The ctor is passing the parameter up to PHP so it will behave as new DateTime() in PHP.
