### ISSUE TITLE
🌎 [Translation tool] ast

### ISSUE THREAD

**Issue by fitojb** [briannesbitt/Carbon#2150]
|English|ast|comments|
|--|--|--|
|2 years|2 añu|2 años|
|2 weeks|2 selmana|2 selmanes|
|2 days|2 día|2 díes|
|2 hours|2 hora|2 hores|
|2 minutes|2 minutu|2 minutos|
|2 seconds|2 segundu|2 segundos|
|2 hours ago|2 hora ago|Hai 2 hores|
|2 hours from now|2 hora from now|En 2 hores|
|2 hours before|2 hora before|2 hores enantes|
|2 hours after|2 hora after|2 hores dempués|

**Comment by kylekatarnls** [comment]
Is Asturian supposed to be very close to Spannish?

If so, it sounds like only months should be kept in the ast file and all other translations could be inherited from es.php:
https://github.com/briannesbitt/Carbon/blob/master/src/Carbon/Lang/ast_ES.php#L20

**Comment by fitojb** [comment]
The languages are close but the declension is different in Asturian.

* Nouns (masculing) ending in -u in Asturian (-o in Spanish) pluralize as -os
* Feminine Asturian nouns (ending in -a) pluralize as (-es)
* It’d be unacceptable to use Spanish terms instead of Asturian ones in places like _hace/hai_, _antes/enantes_ and _después/dempués_.

**Comment by kylekatarnls** [comment]
Those translations has been added and other translation will now fallback to Spanish language.

Can you check that All the green lines are better than the red ones in the resulting unit test file:
https://github.com/briannesbitt/Carbon/pull/2167/files#diff-ea2214cac6cc3ce6e8eab3ba8633c748

Thank you.
