### ISSUE TITLE
diffAsCarbonInterval() results in empty days property (it is filled when using diff())

### ISSUE THREAD

**Issue by MeesterDev** [briannesbitt/Carbon#2151]
Hello,

I encountered an issue with the following code:
```php
$a = Carbon::now();
$b = $a->clone()->modify('+1 month');

$diff = $b->diffAsCarbonInterval($a);

var_dump((string)$a, (string)$b, $diff->d, $diff->days, $diff->m);
```

Carbon version: 2.38.0 (fresh install)

PHP version: 7.4.6

I expected to get:

```
string(19) "2020-08-08 06:44:59"
string(19) "2020-09-08 06:44:59"
int(0)
int(31)
int(1)
```

But I actually get:

```
string(19) "2020-08-08 06:44:59"
string(19) "2020-09-08 06:44:59"
int(0)
bool(false)
int(1)
```

As the totalDays property returns 28, that is not a viable alternative for me. I haven't taken an extensive look at cascading, so I do not know if this is also a bug (and it should be 31) or the expected behaviour.

Thanks!

**Comment by kylekatarnls** [comment]
The `days` is set only when using the native `diff()` method (inherited from `DateTime`). `->diff()` return a `DateInterval` instance with 1 letter properties as the more "optimized" set based on the 2 given dates and `->days` the total number of days between those 2 dates. But `->days` cannot be modified in user-land (reserved to PHP internal). If we do any conversion, we lost this property and as the 2 dates are not stored in the interval we can't recompose it. Without start and end, there is no particular reason to choose 31 over 30 for the month length. Default cascade is 1 month = 4 weeks, this avoid getting non-integer "rests" which pollute the interval on cascade.

Still if you just need the days count, you don't need the whole interval:

```php
$b->diffInDays($a)
```

**Comment by MeesterDev** [comment]
Ah, I didn't know it wasn't writable (the PHP docs show it as public).

diffInDays will be fine for us. Thanks!

**Comment by kylekatarnls** [comment]
Here is the demo of the main problem:
https://3v4l.org/plWBu

Trying to change the `days` property of an `DateInterval` will just fail silently and keep the original value.

**Comment by MeesterDev** [comment]
Ah, that's too bad. Seems there is a PHP bug open for this (https://bugs.php.net/bug.php?id=65654) but based on the age of the bug, I'm going to guess it's not going to be fixed and certainly not anytime soon.
