### ISSUE TITLE
In Translator.php line 325:    strtolower() expects parameter 1 to be string, array given

### ISSUE THREAD

**Issue by asis-parajuli** [briannesbitt/Carbon#2157]
When i try to install i receives this sort of issue.

Hello,

I encountered an issue with the following code:
```php
echo Carbon::parse('2018-06-01')->subDay()->month;
```

Carbon version: "nesbot/carbon": "^2.0",

PHP version: 7.4.8

I expected to get:

```
6
```

But I actually get:

```
5
```

Thanks!

**Comment by kylekatarnls** [comment]
Hello,

I cannot reproduce the issue (if you mean getting the title of this issue as an error) on https://try-carbon.herokuapp.com/ with the details you gave.

Please fulfill the issue template with exact Carbon version, actual/expected output and a minimum way to reproduce the issue.

Thanks.

**Comment by kylekatarnls** [comment]
This call is inside `Carbon::setLocale()` so you (or a third-party of your application) probably called this method with an array while it expects a string.

**Comment by asis-parajuli** [comment]
Thanks for your support you save my day.
