### ISSUE TITLE
this week

### ISSUE THREAD

**Issue by superboys2017** [briannesbitt/Carbon#2161]
check if datum is in this week

**Comment by superboys2017** [comment]
how can i do that

**Comment by kylekatarnls** [comment]
`Carbon::isCurrentWeek`

**Comment by superboys2017** [comment]
if (Carbon::isCurrentWeek = 2020-08-17)
??

this wond work

**Comment by kylekatarnls** [comment]
This is not valid PHP syntax. Strings need quotes, comparison needs `==` and methods calls need parentheses. Please check the PHP doc to see how to call the methods on instances of a class (like the `Carbon` class) and see the Carbon doc for usage of the `isCurrentXyz()` methods:
https://carbon.nesbot.com/docs/#api-comparison
