### ISSUE TITLE
Problem Setting Month

### ISSUE THREAD

**Issue by warkior** [briannesbitt/Carbon#217]
Hi there,

I've put the following code on a page of my site, and it is returning the wrong month:
`Carbon::now(new DateTimeZone('America/Vancouver'))->month(6)->toRfc850String()`

When dumped returns:
`string 'Tuesday, 01-Jul-14 09:48:35 PDT' (length=31)`

Note that month 6 is returning July. I assume setting the month manually is not zero based.

This *may* be related to this issue, but then I'm not sure.
https://github.com/briannesbitt/Carbon/issues/216

Thanks in advance,
James.

**Comment by tshelburne** [comment]
Have a look at PR #239 - it creates a set of methods that handle this situation. I also submitted an idea to update the interface to make it more "predictable", but that's much more subjective.

**Comment by kylekatarnls** [comment]
Same problem source as #236 created by @tshelburne and so you can check the day after set the month in the same way:
<pre>$oldDate = Carbon::now(new DateTimeZone('America/Vancouver'));
$newDate = $oldDate->month(6)->toRfc850String();
if($newDate->day &lt; $oldDate->day) {
    $newDate->subMonth();
    $newDate->day = $newDate->daysInMonth;
}</pre>

**Comment by briannesbitt** [comment]
I'll look at the PR
