### ISSUE TITLE
Format Carbon:ISO8601 vs format('c')

### ISSUE THREAD

**Issue by Chrysweel** [briannesbitt/Carbon#2170]
Hello,

I encountered an issue with the following code:
```php
$subscription->getDateFinish()->format(Carbon::ISO8601);
$subscription->getDateFinish()->format('c');
```

Carbon version: **2.39.0**

PHP version: **7.4.4**

I get different result

```
"dateFinish": "2020-07-05T12:45:55+0200 (carbon format result)
"dateFinish": "2020-07-05T12:45:55+02:00 (c format result)
```

The documentation php in [datetime.format.php](https://www.php.net/manual/en/datetime.format.php) says that format c is: **15:19:21+00:00**
```
c | ISO 8601 date (added in PHP 5) | 2004-02-12T15:19:21+00:00
```
In [class.datetime.php](https://www.php.net/manual/en/class.datetime.php)
```
const string DateTimeInterface::ISO8601 = "Y-m-d\TH:i:sO" ;
```
But in documentation php I see the format O without colon
```
O | Difference to Greenwich time (GMT) without colon between hours and minutes | Example: +0200
```

[In Wikipedia](https://en.wikipedia.org/wiki/ISO_8601) we have two formats basic and extended

```
So a time might appear as either "134730" in the basic format or "13:47:30" in the extended format.
```
In [version spanish](https://es.wikipedia.org/wiki/ISO_8601) we have an example
```
13:18:05-03:00 or 31805-0300
```

What format is correct?
Why format(Carbon::ISO8601) and format('c') doesnot result same output?

Is it a bug?

Thanks!

**Comment by Chrysweel** [comment]
Maybe only is a inconsistency in documentation php.. I dont know..
I opened an issue there also ... https://bugs.php.net/bug.php?id=80022
¿any feedback?

**Comment by kylekatarnls** [comment]
Hello,

From the PHP doc: https://www.php.net/manual/en/class.datetimeinterface.php

> DATE_ISO8601
> ISO-8601 (example: 2005-08-15T15:52:01+0000)
> Note: This format is not compatible with ISO-8601, but is left this way for backward compatibility reasons. Use DateTime::ATOM or DATE_ATOM for compatibility with ISO-8601 instead.

Using `ATOM` instead of `ISO8601` is also our recommendation.
