### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by superboys2017** [briannesbitt/Carbon#2174]
![image](https://user-images.githubusercontent.com/40305210/91701356-77b1d480-eb77-11ea-8c2b-b94fb1c5f348.png)
i get this error how to fix

**Comment by kylekatarnls** [comment]
Upgrade Laravel at least to **5.8** (5.7 is an obsolete version of Laravel), ideally to the latest stable: **7.26.1**

See the upgrade guides:
5.7 => 5.8 https://laravel.com/docs/5.8/upgrade
5.8 => 6 https://laravel.com/docs/6.x/upgrade
6 => 7 https://laravel.com/docs/7.x/upgrade
