### ISSUE TITLE
Unexpected `subMonths(2)` behaviour on August 31

### ISSUE THREAD

**Issue by AlbinoDrought** [briannesbitt/Carbon#2176]
Hello,

I encountered an issue with the following code:
```php
echo Carbon::parse('2020-08-31')->subMonths(2)->month;
```

Carbon version: **2.34.0**

PHP version: **7.4.9**

I expected to get June:

```
6
```

But I actually get July:

```
7
```

Thanks!

**Comment by AlbinoDrought** [comment]
I'm not sure if I agree with it, but I see similar issues have been closed as duplicates and point to https://github.com/briannesbitt/Carbon/issues/1335#issuecomment-393178515

A PHPCS or similar rule to prevent this could be cool. For now we've thrown in a quick `! grep -wR 'now()->subMonth' .`

**Comment by kylekatarnls** [comment]
`subMonths` and `addMonths` (and so equivalent methods for quarter/year) behave just exactly like the `DateTime` native class of PHP:

```php
$date = new DateTime('2020-08-31');
$date->modify('+1 month');

echo $date->format('Y-m-d'); // 2020-01-01
```

https://3v4l.org/vnqFT

Carbon just respect this as the default behavior (PHP consider adding 1 month is adding the number of days of the month of the current date). It's not up to Carbon to decide rather it's a mistake or not. It would be opinionated to say the difference between 2020-08-31 and 2020-09-30 is 1 month as it would mean it's the same then the difference between 2020-08-30 and 2020-09-30. So, as you can see, it's not so obvious that what you expect here is universal.

I don't think some PHPCS rule should advocate for overflowing or not or any other option. Using explicitly `settings()` to chose the overflow strategy or `subMonthsWithOverflow()` or `subMonthsNoOverflow()` handled from the application side is better I think.
