### ISSUE TITLE
The locale is one, but the days of the week are from another language

### ISSUE THREAD

**Issue by Velstad** [briannesbitt/Carbon#2178]
Hello,

The property 'localeDayOfWeek' does not work. For example, the 'diffForHumans' method gives the correct result in Ukrainian.
```
echo now()->locale; //   "uk"
echo now()->localeDayOfWeek; // "Wednesday"
echo now()->subHours(3)->diffForHumans(); // "3 години тому"
```

Carbon version: **2.38.0**

PHP version: **7.2**

Laravel version: **6.18.34**

I expected to get:

```
"Середа"
```

But I actually get:

```
"Wednesday"
```

![image](https://user-images.githubusercontent.com/61826239/91980874-9effd180-ed30-11ea-94f4-e898c315c9cc.png)

Thanks!

**Comment by kylekatarnls** [comment]
You can simply use `now()->dayName`

`->localeDayOfWeek` actually use the translations of your OS and the locale setting of `LC_TIME` while `dayName` use the internal translations of Carbon and the locale set via `Carbon::setLocale()` (so the one set by Laravel).

Sorry for the confusion, that's legacy stuff (before Carbon handled translation on its own, it was delegated to `setlocale` and `formatLocalized` which use `strftime` but this approach is no longer recommended as the supported languages and their encoding differ from an OS to an other).

**Comment by Velstad** [comment]
> You can simply use `now()->dayName`
> 
> `->localeDayOfWeek` actually use the translations of your OS and the locale setting of `LC_TIME` while `dayName` use the internal translations of Carbon and the locale set via `Carbon::setLocale()` (so the one set by Laravel).
> 
> Sorry for the confusion, that's legacy stuff (before Carbon handled translation on its own, it was delegated to `setlocale` and `formatLocalized` which use `strftime` but this approach is no longer recommended as the supported languages and their encoding differ from an OS to an other).
