### ISSUE TITLE
Parse Error breaking website

### ISSUE THREAD

**Issue by nickyoung87** [briannesbitt/Carbon#2179]
Hello,

I am getting the following error:
```
Parse error: syntax error, unexpected 'const' (T_CONST), expecting variable (T_VARIABLE) in /.../public_html/wp-content/plugins/.../vendor/nesbot/carbon/src/Carbon/CarbonInterface.php on line 526
```

Carbon version: **2.38.0**

PHP version: **7.3.0 (on Microsoft-IIS/10.0)**

I expected to get:

```
No error because to my knowledge it is a PHP 7.1+ feature (and we are running 7.3+)
```

But I actually get:

```
The error above
```

Thanks!

**Comment by kylekatarnls** [comment]
Hello,

Multiple versions of PHP can be installed on the same machine. Please double-check the PHP version you run using `phpinfo()` from inside `/.../public_html/` checked from the browser (not using the CLI).

Thanks.

**Comment by nickyoung87** [comment]
Thanks for the quick response. The PHP version is being pulled from a plugin (WordPress) through its admin settings. It is using the constant `PHP_VERSION` to grab the info. Is that not accurate?

**Comment by kylekatarnls** [comment]
Each commit of Carbon is tested on Travis with various versions of PHP:
https://travis-ci.org/github/briannesbitt/Carbon

This error is a certain sign of trying to run Carbon >= 2 on PHP < 7.1.

`PHP_VERSION` is accurate in a clean install of PHP. It's telling you the current version of the PHP program that is executed to run this code.

If we assume the plugin you're talking about properly retrieves it, it means you're not running the same PHP program when you see it via your admin and when you get the error. You maye have different hosts/virtual-hosts/domains configured in IIS with potentially different PHP version.

**Comment by nickyoung87** [comment]
Thanks for the confirmation. This looks like it might be related to the plugin not fully installing properly. I will close this now and re-open it if it comes back around to an issue here.
