### ISSUE TITLE
[Translation tool] lb

### ISSUE THREAD

**Issue by slelorrain** [briannesbitt/Carbon#2187]
|English|lb|comments|
|--|--|--|
|2 hours ago|ago|virun 2 Stonnen|
|2 hours from now|from_now|an 2 Stonnen|
|2 hours before|before|2 Stonnen virdrun|
|2 hours after|after|2 Stonnen duerno|

**Comment by kylekatarnls** [comment]
Thank you @slelorrain I will add them.

**Comment by kylekatarnls** [comment]
The PR to fix it is open, you can check the result in green lines of the test file:
https://github.com/briannesbitt/Carbon/pull/2188/files#diff-55ba6a9954db4e7b2eb485b94a2c5e39

**Comment by slelorrain** [comment]
After reading the PR, I've two remarks:
- the commit message of the fix should be modified as it's not Lebanese but Luxembourgish :)
- for 'second' it's always the plural form. It should be 'second' => ':count Sekonn|:count Sekonnen' instead of 'second' => ':count Sekonnen'

Thank you

**Comment by kylekatarnls** [comment]
Thank you, it will be released on 2.40.0.

**Comment by slelorrain** [comment]
Thank you
