### ISSUE TITLE
Carbon::setDate Not Same Value as CarbonImmutable::setDate

### ISSUE THREAD

**Issue by parkerj** [briannesbitt/Carbon#2190]
I was testing the `setDate` method for both` Carbon` and `CarbonImmutable`. I was assuming that the `setDate` methods were the same for both, but my IDE tells me that `CarbonImmutable::setDate` is not the same as `Carbon::setDate`. If I am doing it wrong, please let me know.

Hello,

I encountered an issue with the following code:
```php
$carbon = new Carbon;
$carbon->setDate(2013, 12, 3);

$carbonImmutable = new CarbonImmutable;
$carbonImmutable->setDate(2013, 12, 3);

echo 'carbon = ' . $carbon . '<br />';
echo 'carbonImmutable = ' . $carbonImmutable;
```

Carbon version: 2.39.2

PHP version: 7.4.9

I expected to get:

```
carbon = 2013-12-03 00:39:22
carbonImmutable = 2013-12-03 00:39:22
```

But I actually get:

```
carbon = 2013-12-03 00:39:22
carbonImmutable = 2020-09-15 00:39:22
```

Thanks!

**Comment by kylekatarnls** [comment]
Hello,

That's exactly what "immutable" stands for, in a `CarbonImmutable` instance, date/time properties (year, month, day, hour, minute, second and milliseconds) will never change as long as you don't reassign the variable.

When you call any setter on a `CarbonImmutable` you get a new instance as the returned value of the method.

So you should write:
```php
$carbon = new Carbon;
$carbon->setDate(2013, 12, 3);

$carbonImmutable = new CarbonImmutable;
$carbonImmutable = $carbonImmutable->setDate(2013, 12, 3);

echo 'carbon = ' . $carbon . '<br />';
echo 'carbonImmutable = ' . $carbonImmutable;
```

**Comment by parkerj** [comment]
"That's exactly what "immutable" stands for . . ."
Doh!!!! Of course. I am going to blame my oversight on my migraine.
