### ISSUE TITLE
Drop Carbon::minValue() and Carbon::maxValue()

### ISSUE THREAD

**Issue by kylekatarnls** [briannesbitt/Carbon#2192]
I encountered an issue with the following code:
```php
echo Carbon::maxValue()->addYears(99); // 10098-12-31 23:59:59
echo Carbon::minValue()->subYears(99); // -0098-01-01 00:00:00
```

Carbon version: **2.40.0**
PHP version: **7.4.0**

minValue and maxValue are legacy helpers for virtually extreme safe values for date objects depending on the platform (32-bit vs 64-bit), they are no longer relevant.

32-bit is now barely inexistant and mostly not recommended in server machines, and Carbon can properly handle dates from Year -99999999999 to 99999999999.

This concern should be handled on a by-application basis and so it's time in 3.0 for Carbon to let those methods go.

**Comment by HenkPoley** [comment]
Just noting for people, a potential replacement is:

```php
\Carbon\CarbonImmutable::endOfTime();
````

**Comment by kylekatarnls** [comment]
Hello,

Indeed, `CarbonImmutable::startOfTime` and `CarbonImmutable::endOfTime` can address needs that were potentially filled previously by `minValue`/`maxValue`

What is different with those methods:
- They are static dates guaranteed to be really far:
  - `-1118290769066898816-01-01 00:00:00.0000`
  - `1118290769066902787-12-31 23:59:59.999999`
- Carbon objects can be checked with `->isStartOfTime()` and  `->isEndOfTime()` so particular behavior can be triggered for those values.
- They are only available on `CarbonImmutable` so to prevent as much as possible subtracting time from startOfTime, not adding time to endOfTime.

Few things to consider:
- If you're building an application, it's likely that you can have stricter limits in your business rules. When trying to validate a date is in certain workable bounds, you should consider: what are the limits in your storage if you store it, what are limits for the third-parties you send dates to if you do, etc. And so you will likely have more relevant value that would specifically fit your needs when talking about min/max.
- startOfTime/endOfTime should not be used as values or limits but more like flags, for instance, they can be used as start/end of a period to represents something started at some date-time but will continue forever or something that always was but will stop at some date-time. They are basically for dates period what -∞ and +∞ are for number interval representation.

**Comment by Bloemendaal** [comment]
Can you maybe add this to the upgrade guide from 2.x? I've searched for at least half an hour to finally find out what's the best replacement for these methods that we suddenly gone... 😅 

https://carbon.nesbot.com/docs/#api-carbon-3

**Comment by reesebutler** [comment]
> Can you maybe add this to the upgrade guide from 2.x? I've searched for at least half an hour to finally find out what's the best replacement for these methods that we suddenly gone... 😅
> 
> https://carbon.nesbot.com/docs/#api-carbon-3

I second this. I find it very confusing that the upgrade doc makes zero mention of this change.

**Comment by kylekatarnls** [comment]
Yes 👍 

Section added: https://carbon.nesbot.com/docs/#api-carbon-3-remove-min-max
