### ISSUE TITLE
🌎 [Translation tool] nn_NO

### ISSUE THREAD

**Issue by gaute** [briannesbitt/Carbon#2195]
|English|nn_NO|comments|
|--|--|--|
|2 weeks|2 uker|2 veker ("uker" is nb_NO)|
|2w|2 uker|2v|
|1 week|1 uke|1 veke|
|a week|eit uke|ei veke|
|2 hours before|before|2 timar før|
|2 hours after|after|2 timar etter|

**Comment by kylekatarnls** [comment]
Thanks for your contribution. I will fix that for 2.41.

**Comment by kylekatarnls** [comment]
@gaute I see you propose `2v` as week abbreviation but I see we have no abbreviations for other units. Could you tell what should be the abbreviation for year/month/date/hours/minute/second?

**Comment by gaute** [comment]
Sure:

English | nn_NO | comments
-- | -- | --
2yrs | 2 år | 
2mos | 2 md | 
2w | 2v | 
2d | 2d | 
2h | 2t | 
2m | 2m | 
2m | 2s |
