### ISSUE TITLE
add create methods from float and string types microtime result

### ISSUE THREAD

**Issue by userator** [briannesbitt/Carbon#2199]
Add create methods from float and string types microtime result

```php
Carbon::createFromFloatMicrotime(float $microtime);
Carbon::createFromWhitespaceMicrotime(string $microtime);
```

Carbon version: **2.40.1**

PHP version: **7.4**

**Comment by kylekatarnls** [comment]
As discussed in #2200 I approve the feature, but in order to avoid adding methods and require the user to know the type of the timestamp and pick the right method depending on he has int, float or string, I propose instead to support string and float in existing methods: #2205

**Comment by kylekatarnls** [comment]
String and float timestamps such as the ones produced by `microtime()` will be supported by `createFromTimestampUTC()` and
`createFromTimestamp()` in the version 2.41.0.
