### ISSUE TITLE
Carbon under XDebug - __debugInfo call can result in ->format on incompletely-initialized underlying DateTime parent

### ISSUE THREAD

**Issue by spronkey** [briannesbitt/Carbon#2201]
Hi all,

When calling Carbon::now(), and only when running under debugger (xdebug via phpstorm, also xdebug via dbgpClient on CLI), I'm getting the following exception:

Uncaught ErrorException: DateTime::format(): The DateTime object has not been correctly initialized by its constructor in /Users/keith/Development/solvam/beep/api/vendor/nesbot/carbon/src/Carbon/Traits/Converter.php:102

The exact issue appears to be that XDebug, is calling the __debugInfo method (probably from var_dum()ing) before Carbon's __construct()or calls the parent constructor. __debugInfo then attempts to ->format the current object (Traits/Options.php:430), which obviously fails because the parent hasn't been constructed yet.

I can replicate the issue with the following file run under debugger in PHPStorm as soon as I put a breakpoint on the new Carbon() call and try to step in. Note that Carbon::now() and new Carbon() both cause this exception.
```php
<?php
require_once(__DIR__.'/vendor/autoload.php');
$d = \Carbon\Carbon::now();
echo 'never gets here';
```
I'm using Carbon 2.40.0

PHP 7.3.20 + Xdebug 2.9.4

I expected to get: A Carbon instance with the current time.

But I actually get: an exception thrown:

PHP Warning:  Uncaught ErrorException: DateTime::format(): The DateTime object has not been correctly initialized by its constructor in /Users/keith/Development/solvam/beep/api/vendor/nesbot/carbon/src/Carbon/Traits/Converter.php:102

Thanks!

**Comment by spronkey** [comment]
Have done some further tests and removed references to other libraries - there's no odd interaction going on here, this is solely within Carbon's __debugInfo making assumptions about the state of the object being valid and breaking.

**Comment by kylekatarnls** [comment]
Our tests are run with xDebug and have no problem with that. I also can debug your code with PHPStorm wihout any trouble:
![image](https://user-images.githubusercontent.com/5966783/94115846-93448e00-fe4a-11ea-90f2-fa897db33668.png)
![image](https://user-images.githubusercontent.com/5966783/94115808-89bb2600-fe4a-11ea-9038-122714d2e611.png)

And it ends outputing "never gets here". I will try in a Laravel project. But I can't see how it could be any different as Laravel does no override on Carbon.

So I will need some more details.

**Comment by spronkey** [comment]
@kylekatarnls Can you try stepping into the Carbon::now() call and see whether you can get the same result?

I believe the issue is that the debugger at some point is calling var_dump() on the object before it has been fully constructed - but its difficult to get any visibility into when the debugger calls var_dump.

**Comment by kylekatarnls** [comment]
I reproduced it by trying with PHP 7.3.5. So what I can yet tell is it works fine with PHP 7.4. If it's a PHP bug in `DateTime` constructor, I'm not sure there is much to do to fix it.

Please consider debugging with PHP 7.4.

**Comment by spronkey** [comment]
@kylekatarnls I can't seem to reproduce in PHP 7.4 either with XDebug v2.9.4. I can, however, reproduce in 7.2.

Found this XDebug bug from a long time ago that seems to be very similar to this issue, seems that it may be an XDebug bug specifically: https://bugs.xdebug.org/bug_view_page.php?bug_id=00001140

**Comment by kylekatarnls** [comment]
Basically, we could not fix the error, but we could catch it so it would return partial infos without error.

**Comment by kylekatarnls** [comment]
This will no longer occur in 2.41.0.
