### ISSUE TITLE
CarbonPeriod is not tested in two points

### ISSUE THREAD

**Issue by rentalhost** [briannesbitt/Carbon#2209]
Hello,

I am testing a new code analyzis tool that I am developing. It currently checks if functions that returns only boolean (like `is_string()`, `is_bool()`, so on) is tested by returning `true` and `false` values after tests. So I have identified two points of code that never returns `false`:

* https://github.com/briannesbitt/Carbon/blob/b489cf3d4d36e66d5224e7029a2221d5d433d873/src/Carbon/CarbonPeriod.php#L1110-L1121

  At this point, `is_callable()` will never fails, so `$key` will never be `1` and the `$tuple[$key]` will never be tested like `$tuple[1]`.

* https://github.com/briannesbitt/Carbon/blob/b489cf3d4d36e66d5224e7029a2221d5d433d873/src/Carbon/CarbonPeriod.php#L745-L760

  At same file, at the `elseif ()`, `is_a()` will never fails.

For now I am just posting it to check some theories for my project, and it could fails. I will publish here on github when it have some more maturity. So if you could help me checking if my indications is true, I appreciate. My objective is help others projects to get a really full code coverage.

**Carbon version:** 2.40.1
**PHP version:** 7.4.7

Thanks!

**Comment by rentalhost** [comment]
I have found four new cases:

* https://github.com/briannesbitt/Carbon/blob/b489cf3d4d36e66d5224e7029a2221d5d433d873/src/Carbon/Exceptions/NotLocaleAwareException.php#L25-L30

  `$object` will never been a non-object, so `is_object()` will never fails and `$dump` will be always `get_class($object)`.

* https://github.com/briannesbitt/Carbon/blob/b489cf3d4d36e66d5224e7029a2221d5d433d873/src/Carbon/Laravel/ServiceProvider.php#L36-L59

  This method have three points:

  * `method_exists()` will be always `true`, so it will returns always `$this->app`;
  * the first `class_exists()` will be always `false`, so it will always skip this path. It is acceptable once that it depends of Laravel itself;
  * `the second `class_exists()` will be always `false` too, by the same case above.

For test this last two cases, I suggests create the class and load it during tests. It will helps to full coverage this method too.

**Comment by kylekatarnls** [comment]
Hi @rentalhost that's an awesome job. It has always let me sad to see, JS (thanks to the precise line+offset locator) could show the very precise coverage by every branches while the per-line coverage of PHP put many ternary uncovered operand under the carpet.

How did you achieve this magic trick? Do you split the code to create new line before operators? Add some `else { /*noop*/ }` to spot missed branches?

**Comment by rentalhost** [comment]
@kylekatarnls thanks! It currently only checks if some PHP functions that returns a boolean will returns `true`/`false` at least one time during all tests execution. But my idea is create new features like detailed branch test for conditionals, for instance.

I am using the [`nikic/php-parser`](https://github.com/nikic/PHP-Parser) and modifying the nodes to injects an additional capture code, all in PHP. Not is too fast, but it must be useful as a last process of testing.

You could check initial development code here https://github.com/TudoCodigo/burning-php.

**Comment by kylekatarnls** [comment]
I added missing unit tests. Thanks for your help. Once burning-php will be available via composer, I'll be glad to add it and run the check automatically with TravisCI.
