### ISSUE TITLE
Compare times without date

### ISSUE THREAD

**Issue by christian-kolb** [briannesbitt/Carbon#2215]
Hello,

I encountered an issue that I'm not able to compare times with each other, "just" dates.

I can use `isBefore` or `isAfter`, but this always checks the Date.

When storing a DateTime as Time in a database (for example opening hours) which simply have no date, the resulting DateTime from the database will ether be the Time with `1990-01-01` or with the current date. When I get an incoming DateTime from the user (which includes the Date) I can't really compare it as the date will always be off.

It's possible to set the current date to the time and then compare, but this will break as soon as you introduce changing winter and summer times (with an hour difference). Because then setting the date won't affect the offset delivered by the object of the user (API).

It would be great to have methods which ignore the Date and only validate the Time. Those could be equivalent to `isBefore` and `isAfter`, just as `isTimeBefore` and `isTimeAfter`.

Or is there a way to do the same with the current methods and I just haven't found them?

Carbon version: **2.41.0**

PHP version: **7.4.2**

Thanks!

**Comment by kylekatarnls** [comment]
Hello,

What about:
```php
$date1->format('His.u') > $date2->format('His.u')
```

**Comment by christian-kolb** [comment]
Hi @kylekatarnls,

that's really smart 🙂 Thank you!

What I came up with is something that leads into the same direction:

```
private static function secondsOfDayForTime(\DateTime $dateTime): int
{
    return ((int) $dateTime->format('G')) * 60 * 60
        + ((int) $dateTime->format('i')) * 60
        + (int) $dateTime->format('s')
        ;
}

public static function isTimeBefore(\DateTime $before, \DateTime $base): bool
{
    return self::secondsOfDayForTime($before) < self::secondsOfDayForTime($base);
}
```

The only drawback is the readability. With this helper, a compare looks like this:

```
DateHelper::isTimeBefore($earlierTime, $compareTime);
```

If it would be integrated into Carbon, it could look like this:

```
$earlierTime->isTimeBefore($compareTime);
```

Which is way easier to understand as you know which is the time object that has to be earlier and which is the one getting compared.

Would it be possible to add this and the after, same, sameOrAfter variants to Carbon?

**Comment by kylekatarnls** [comment]
This can be achieved with macro or mixin:
```php
Carbon::macro('isBeforeTime', static function ($other) {
    $this = self::this();

    return $this->format('Gis.u') < $this->resolve($other)->format('Gis.u');
});
```

**Comment by kylekatarnls** [comment]
I fixed the previous example and here is the mixin way for multiple methods:
```php
trait TimeComparator
{
    public function isTimeBefore($other)
    {
        return self::this()->format('Gis.u') < $other->format('Gis.u');
    }

    public function isTimeAfter($other)
    {
        return self::this()->format('Gis.u') > $other->format('Gis.u');
    }
}

Carbon::mixin(TimeComparator::class);
```

A last option for more explicit naming is using `secondsSinceMidnight()` (but until 3.x it ignores microseconds-precision).

So I think the current tooling is enough and such methods would be just fine as macros if you need shortcuts.

Thanks,

**Comment by christian-kolb** [comment]
I wasn't aware of Mixins, thanks for the input 🙂
