### ISSUE TITLE
preg_replace(): No ending delimiter '$' found

### ISSUE THREAD

**Issue by SlyDave** [briannesbitt/Carbon#2218]
Hello,

I encountered an issue with the following code:

When Laravel is casting a date/datetime to Carbon via the HasAttributes Trait, Since Carbon 2.41.0 is crashing out:
```php
$updated_ats = Model::all()->only('updated_at');
```

Carbon version: 2.41.0

PHP version: 
PHP 7.2.20 (cli) (built: Jul  2 2019 13:00:53) ( NTS MSVC15 (Visual C++ 2017) x64 )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Xdebug v2.7.2, Copyright (c) 2002-2019, by Derick Rethans

I expected to get:

```
No Exceptions
```

But I actually get:

```
{
    "message": "preg_replace(): No ending delimiter '$' found",
    "exception": "ErrorException",
    "file": "/mnt/c/www/workrest/vendor/nesbot/carbon/src/Carbon/Traits/Creator.php",
    "line": 593,
    "trace": [
        {
            "function": "handleError",
            "class": "Illuminate\\Foundation\\Bootstrap\\HandleExceptions",
            "type": "->"
        },
        {
            "file": "/mnt/c/www/workrest/vendor/nesbot/carbon/src/Carbon/Traits/Creator.php",
            "line": 593,
            "function": "preg_replace"
        },
        {
            "file": "/mnt/c/www/workrest/vendor/nesbot/carbon/src/Carbon/Traits/Creator.php",
            "line": 665,
            "function": "rawCreateFromFormat",
            "class": "Carbon\\Carbon",
            "type": "::"
        },
        {
            "file": "/mnt/c/www/workrest/vendor/laravel/framework/src/Illuminate/Support/DateFactory.php",
            "line": 217,
            "function": "createFromFormat",
            "class": "Carbon\\Carbon",
            "type": "::"
        },
        {
            "file": "/mnt/c/www/workrest/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php",
            "line": 261,
            "function": "__call",
            "class": "Illuminate\\Support\\DateFactory",
            "type": "->"
        },
        {
            "file": "/mnt/c/www/workrest/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php",
            "line": 916,
            "function": "__callStatic",
            "class": "Illuminate\\Support\\Facades\\Facade",
            "type": "::"
        },

```

This appears to be caused by the addition for bug https://bugs.php.net/bug.php?id=80141 introduced in 2.40.1
```
        // Work-around for https://bugs.php.net/bug.php?id=80141
        $format = preg_replace('/(?<!\\\\)((?:\\\\{2})*)c/', '$1Y-m-d\TH:i:sP', $format);
```

Thanks!

**Comment by SlyDave** [comment]
Downgrading to 2.40.0 and the problem goes away.

**Comment by kylekatarnls** [comment]
Hello,

Thanks for the report. I still have many Laravel applications that work fine and for 4 days we would have way more complains if it would break all Laravel applications. It more likely concern only a particular case/setting. But this code chunk is not enough for me to guess.

Could you first tell me which format is used such as configured by `$dateFormat` property or the method `getDateFormat` in your Model/BaseModel and an example of the raw data you have (in your DB for instance)?

**Comment by SlyDave** [comment]
Totally agree, if this was occurring all the time, it'd have blown up instantly.

Format is the default
`$this->getConnection()->getQueryGrammar()->getDateFormat()` which results in `Y-m-d H:i:s`

With that said, I've not been up able to reproduce this morning since rebooting my dev machine... so that's a thing, will close it for now and if I can get it to happen again I'll get some more in-depth details
