### ISSUE TITLE
weekOfMonth property is ambiguous

### ISSUE THREAD

**Issue by MalikinSergey** [briannesbitt/Carbon#222]
Hi,

In case of weekOfMonth magic property, it calculates as
`return (int) ceil($this->day / self::DAYS_PER_WEEK)`
so, this code return number of __seven-day segments__ from __first__ day of month.

And max number of this method week is 5 (31/7).

But, in real, first week of month can start in last month, and max number of week will be 6, 
as well as said in your phpdoc for this magic property:
` * @property-read integer $weekOfMonth 1 through 6`

Example:
`(new Carbon('2014-10-07'))->weekOfMonth // will be 1, but it's second week of October, 2014`

**Comment by briannesbitt** [comment]
Your right.  The question then is what should each execution return?

Should it be relative to the 1st of the month or relative to a week starting on a monday.

Is this a better implementation?

```php
  return 1 + ($this->weekOfYear - $this->copy()->startOfMonth()->weekOfYear);
```

**Comment by PrplHaz4** [comment]
I think it is semantically correct as is - which ordinal week of this month...if it were going to relate to a months "number", it would need to adhere to a standard (and likely need to change standards based on the users' need - ISO, North American...etc)

http://en.wikipedia.org/wiki/Seven-day_week#Week_numbering

**Comment by briannesbitt** [comment]
I left it as is for now and just updated the doc indicating a max value of 5.  The value of "->weekOfYear" is implemented as per your link.

**Comment by ebencarljo** [comment]
Here is the solution as external function http://stackoverflow.com/questions/5853380/php-get-number-of-week-for-month
