### ISSUE TITLE
Feature Request: Default epoch time helper function

### ISSUE THREAD

**Issue by Sn0wCrack** [briannesbitt/Carbon#2220]
I often tend to use epoch as a pseudo default or placeholder for date time values, currently I'd instantiate these via Carbon::createFromTimepstamp(0) or similar.

Personally I'd find it useful if a short cut to get the default epoch time would be available.

I'd imagine the API would look similar to this or similar:

```
function epoch($nz = null)
{
    return static::createFromTimestamp(0, $tz);
}

$epoch = Carbon::epoch($tz = null);
```

**Comment by kylekatarnls** [comment]
Hello, I can't see the need it would fulfill in real applications.

So having this function in an helper file application-side or as a static method using Carbon::macro() looks just fine to me.

**Comment by Sn0wCrack** [comment]
Ah apologies, didn't realise Carbon had macro support like this, I'll just use that then, thanks!
