### ISSUE TITLE
🌎 [Translation tool] id_ID

### ISSUE THREAD

**Issue by raymondginting** [briannesbitt/Carbon#2222]
|English|id_ID|comments|
|--|--|--|
|a few seconds|beberapa detik|beberapa detik yang lalu|

**Comment by kylekatarnls** [comment]
Hello,

As per my researches and or current translations, `"yang lalu"` sounds to mean `"ago"` which is not present in `"a few seconds"`. It also implies when you will call `->diffForHumans()` you will get `"beberapa detik yang lalu yang lalu"` or `"beberapa detik yang lalu dari sekarang"` such I doubt can be correct even if I don't speak Indonesian.

Thanks.
