### ISSUE TITLE
can't find autoload.php inside Carbon folder without using (Composer)

### ISSUE THREAD

**Issue by Ahmed-Elrayes** [briannesbitt/Carbon#2228]
Hello,
at first i wanna say that basically it's not an issue but a request.
i want to use the library without composer, but i can't find the autoload.php inside Carbon folder, i hope someone can share it with me since it's not provided in the new versions.

Carbon version: **2.41.3**

PHP version: **7.4**

Thanks!

**Comment by kylekatarnls** [comment]
Hello, thanks for noticing it. I added the missing built versions.

The file named Carbon-2.41.3.zip here: https://github.com/briannesbitt/Carbon/releases

Still be aware composer can be used anywhere PHP can and is a must-have nowadays.

Thanks.
