### ISSUE TITLE
Possible issue with Carbon::parse()

### ISSUE THREAD

**Issue by kevinkhill** [briannesbitt/Carbon#223]
I am trying to use your library as a catch all parser for a string representation of a date or time or datetime. I don't know if the input will be "10/20/2014" or "March 5th" or "12:00pm" before hand, so the issue I am having is that with just a plain year, Carbon::parse("2004") converts to a time at today's date, instead of what I expected, just the year to be set.

Am I assuming behavior that isn't possible or is this behavior correct and I might need to try and filter the input some, and use a more specific Carbon function, instead of relying on parse()

Thank you for making a wonderful library :+1:

**Comment by briannesbitt** [comment]
I would filter it a bit to avoid the year being interpreted as a time.

Use a regular expression and if it matches `^[0-9]{4}$` then concatenate `"-01-01"` before passing it to Carbon?  (or use `Carbon::create($year);` for current month and day).
