### ISSUE TITLE
`CarbonInterval->forHumans` not working as expected on empty intervals

### ISSUE THREAD

**Issue by shengslogar** [briannesbitt/Carbon#2233]
Greetings!

I encountered an issue with the following code:
```php
echo Carbon\CarbonInterval::seconds(0)->forHumans();
```

Carbon version: **2.41.5**

PHP version: **7.4.5**

I expected to get:

```
"0 seconds"
```

But I actually get:

```
"1 second"
```

`Carbon\CarbonInterval::seconds(>=1)->forHumans()` outputs as expected.

Appreciate all your work on this project.

SS

**Comment by kylekatarnls** [comment]
Hello,

Please check the second example of the ["Difference for humans" chapter](https://carbon.nesbot.com/docs/#api-humandiff), you need to disable the NO_ZERO_DIFF option using:

```php
echo CarbonInterval::seconds(0)->forHumans(['options' => 0]);
```
Thanks.

**Comment by shengslogar** [comment]
Ah, thank you!
