### ISSUE TITLE
canBeCreatedFromFormat does not encapsulate all possibilities

### ISSUE THREAD

**Issue by buffalobrain** [briannesbitt/Carbon#2236]
Hello,

I encountered an issue with the following code:
```php
$class_start_date = '1/19/2021';
Carbon::canBeCreatedFromFormat('m/d/Y', $class_start_date);
```
(Issue occurs whenever `$class_start_date` has a single-digit month or date without any leading zeroes.) 

Carbon version: 2.41.0

PHP version: 3.3.21

I expected to get:

```
true
```

But I actually get:

```
false
```
When `Carbon::createFromFormat('m/d/Y',$class_start_date);` still successfully creates the expected date.

Thanks!

**Comment by kylekatarnls** [comment]
Hello,

`m` accepts 01 but not 1. As per the doc it verifies both the data is in a given format and valid to be created.

Example from the doc:

> ```php
> // As 21 is too high for a month number and day is expected to be formatted "05":
> var_dump(Carbon::hasFormatWithModifiers('5/21/1975', 'd#m#Y!')); // bool(false)
> ```

If you just need to test `createFromFormat` works, use a try-catch.

Thanks.

**Comment by kylekatarnls** [comment]
The second problem is the order of the parameters:

```php
Carbon::canBeCreatedFromFormat($class_start_date, 'm/d/Y');
```

**Comment by buffalobrain** [comment]
Thanks for the quick response! I suppose I just found the function names to be misleading as they seem to be closely related and I would expect `canBeCreatedFromFormat` to capture all `createFromFormat` possibilities but I suppose that can be a bit challenging.
