### ISSUE TITLE
Timezone not working.

### ISSUE THREAD

**Issue by abhishekdeshkar** [briannesbitt/Carbon#2237]
Hi,

I'm using latest Carbon and Laravel.

While using ```Carbon::now('Asia/Kolkata');``` it doesn't show time of my region. It still picks up ```UTC``` timezone.

I have used ```date_default_timezone_set('Asia/Kolkata');``` when function calls but still no help.

It prints : ```"2020-11-19T04:16:04.258661Z"```

While it should print: ```"2020-11-19T09:46:04.251111Z"```

I also tried, ```Carbon::now(new DateTimeZone('Asia/Kolkata'));```

Plus I have already set default timezone to ```Asia/Kolkata``` in ```app.php```

Any fixes ?

**Comment by kylekatarnls** [comment]
Hello,

`Z` in the ISO-8601 string means GMT (UTC) as per the norm and this format you use (`toJSON()` or `toISO8601String()`) is always in UTC. SO when you pass to JS `Date` for instance it will apply the local timezone:

```js
date= new Date("2020-11-19T04:16:04.258661Z") // will be 09:46 in a browser in Kolkata
```

You should use `format` or `calendar` methods (actually all other formatting methods will use the timezone): https://carbon.nesbot.com/docs/#api-formatting

But first unless you want all the world to see Kolkata dates everywhere in your app, you should not use this timezone as the default in backend. I provided detailed explanations here: https://medium.com/@kylekatarnls/always-use-utc-dates-and-times-8a8200ca3164

Thanks,
