### ISSUE TITLE
🌎 [Translation tool] es

### ISSUE THREAD

**Issue by obokaman-com** [briannesbitt/Carbon#2238]
## Additional fixes
The generic spanish translation for "diff_before_yesterday" is now "antier". Although this is a coloquial form accepted in some latin american countries, Mexico especially, the RAE recommended form is "anteayer".

----
You can check this recommendation at https://www.rae.es/dpd/anteayer

**Comment by kylekatarnls** [comment]
Thanks, your fix will be released in 2.24.0.
