### ISSUE TITLE
Many tests failing in 32-bit environments

### ISSUE THREAD

**Issue by rgson** [briannesbitt/Carbon#2252]
Hi,

Many tests are failing in 32-bit environments.

Carbon version: Commit `a810c01` (current `master`)

PHP version: 7.3

I expected to get:

```
OK (5381 tests, 190019 assertions)
```

But I actually get:

```
FAILURES!
Tests: 5381, Assertions: 189710, Failures: 51.
```

I believe the failures are caused by overflows in calculations within Carbon. Some of the involved functions perform calculations on a microsecond-level (a 32-bit signed integer cannot hold all that many of those) and other functionality deals with dates on the wrong side of the Epochalypse. While e.g. dates far in the future would be commonly expected to be incompatible with 32-bit systems, some of these cases are not the obvious usual suspects when it comes to 32-bit problems, seen from a user's perspective. Others are probably just overly strict tests.

For example, [`testAverageFromGreater`][1] will fail despite using seemingly 32-bit compatible dates:

```php
$dt1 = Carbon::create(2000, 1, 1, 1, 1, 1);
$dt2 = Carbon::create(2009, 12, 31, 23, 59, 59)->average($dt1);
$this->assertCarbon($dt2, 2004, 12, 31, 12, 30, 30);
```
```
12) Tests\Carbon\StartEndOfTest::testAverageFromGreater
Failed asserting that two arrays are identical.
--- Expected
+++ Actual
@@ @@
 Array &0 (
-    'years' => 2004
+    'years' => 2009
     'months' => 12
     'day' => 31
-    'hours' => 12
-    'minutes' => 30
-    'seconds' => 30
+    'hours' => 23
+    'minutes' => 25
+    'seconds' => 18
 )

/home/user/Carbon/tests/AbstractTestCase.php:137
/home/user/Carbon/tests/Carbon/StartEndOfTest.php:525
```

As another example, [`testFloor`][2] will fail despite producing a seemingly equivalent result, albeit of a different data type:
```php
$this->assertSame(1000, CarbonInterval::milliseconds(1234)->floor()->totalMilliseconds); 
```
```
42) Tests\CarbonInterval\RoundingTest::testFloor
Failed asserting that 1000.0 is identical to 1000.

/home/user/Carbon/tests/CarbonInterval/RoundingTest.php:30
```

I'm not sure whether you'd consider this a problem with Carbon or these tests or just a platform limitation in 32-bit environments. If all of this is considered expected behavior on 32-bit platforms, then the failing tests should perhaps be either adapted to pass or be skipped when running on a 32-bit system.

PHPUnit output: [carbon-32bit-test-results.txt](https://github.com/briannesbitt/Carbon/files/5683747/carbon-32bit-test-results.txt)

[1]: https://github.com/briannesbitt/Carbon/blob/a810c01ed9fcaeaa95e8919c4201c953bc9118fb/tests/Carbon/StartEndOfTest.php#L521,L526
[2]: https://github.com/briannesbitt/Carbon/blob/a810c01ed9fcaeaa95e8919c4201c953bc9118fb/tests/CarbonInterval/RoundingTest.php#L30

**Comment by kylekatarnls** [comment]
Hi,

As you know 32-bit timestamp ends `19 janvier 2038` and in many applications you may need to refer to later dates than this.

And this is only with second-precision. When dealing with microseconds-precision, which is the recommended standard in PHP, limits are reached way more easily.

To be short, working with dates from year to microseconds on a 32-bit system is unreliable and we won't work around this limitation as 32-bit is disappearing and 32-bit servers, OS or softwares will get more and more interoperability problems. Carbon being compatible with 32-bit would represent an effort (and likely performance cost) that probably would not worth it and would not make a big difference regarding general issues you may have sticking on a 32-bit OS.

> Many tests are failing in 32-bit environments.

Actually not so many regarding the whole, 51/5381 means 99% of the functions work as expected on on 32-bit platforms. int vs. float is likely an issue related to the 32-bit version of PHP itself, and calcul-precision or limit issues such as average of 2 dates far one from the other is also something that would happen working with pure PHP `DateTime` and would need to rewrite completely some native PHP inner methods.

I would consider any pull-request submitted to improve 32-bit support if impact on 64-bit performances remains low but I don't plan to handle this point myself.
