### ISSUE TITLE
AddDays(1) goes to year 2121 on January 1 from December 13, 2020

### ISSUE THREAD

**Issue by grsherwin** [briannesbitt/Carbon#2257]
Hello,

I encountered an issue with the following code:

        for ($i = 0; $i < $numberOfDays; $i++) {
            $loopDate = Carbon::parse($loopDate->addDays(1)->format('m/d/yy'));
            $loopDateDay = Carbon::parse($loopDate)->format('l');
            $this->dueDate = $loopDate;

Carbon version: * 2.43.0

PHP version: 7.4.9

I expected to get:

```
I use addDays(1) to increment the day by one day
2020-12-28
2020-12-29
2020-12-30
2020-12-31
2021-01-01
```

But I actually get:

```
2020-12-28
2020-12-29
2020-12-30
2020-12-31
2121-01-01

it goes to 2121
```

Thanks!

**Comment by grsherwin** [comment]
Solved the issue.  The year format of yy worked great for 2020, but not so good for 2021.  I needed to change it to Y.

**Comment by kylekatarnls** [comment]
`yy` means you display twice the 2 last digit of the year, it's either `y` or `Y` in `format()` [See PHP Doc](https://www.php.net/manual/en/datetime.format)

Second, this code is rather overkill, and there is no point in format then re-parse:
```php
for ($i = 0; $i < $numberOfDays; $i++) {
        $loopDate = $loopDate->copy()->addDays(1);
        $loopDateDay = $loopDate->format('l');
        $this->dueDate = $loopDate;
```
