### ISSUE TITLE
Question: Do carbon supports callbacks in a date range?

### ISSUE THREAD

**Issue by Aristona** [briannesbitt/Carbon#226]
Hi,

I need something like this:

 ```
Carbon::forEachDayBetween('today', '-7 days', function($day) {
      echo $day->format("Y-m-d");
});
 ```

Output: 2014-11-26 2014-11-25 ... 2014-11-19

Checked documentation but couldn't find anything related.

**Comment by briannesbitt** [comment]
Not at the moment.
