### ISSUE TITLE
Switching months is not always reliable

### ISSUE THREAD

**Issue by rikvdh** [briannesbitt/Carbon#2260]
Hello,

I encountered an issue with the following code:
```php
$cb = Carbon::createFromDate(2020);
$cb->endOfYear();
$cb->month(11);
echo $cb->month;
```

Carbon version: 2.43.0

PHP version: PHP 7.4.13

I expected to get:

```
11
```

But I actually get:

```
12
```

I understand why, because 'end of year' puts the date at 31-12, setting month to 11 changes to 01-12 since there is no 31-11. But this is IMO unexpected behavior.

Thanks!

**Comment by kylekatarnls** [comment]
Hello,

This was explained many times, this is a behavior inherited from the native `DateTime` PHP class, please read the chapter about overflow in:
https://carbon.nesbot.com/docs/#api-addsub

Duplicate #2176

Thanks.

**Comment by kylekatarnls** [comment]
You can see the "issue" with pure PHP using:
```php
$date = new DateTime('2020-12-31');
$date->modify('November');

echo $date->format('m');
```
https://3v4l.org/3Rh4J

Why PHP does not change the behavior is:

1. Avoid breaking change for apps that now taken this into account
2. It would lead to other bugs: create invalid dates like "2020-11-31" or having multiple date - 1 month leading to the same result
