### ISSUE TITLE
ceilMonth on 29 January ceiling to March

### ISSUE THREAD

**Issue by abou-uthmaan** [briannesbitt/Carbon#2268]
Hello,

I encountered an issue with the following code:
```php
echo Carbon::parse('2021-01-29')->ceilMonth();
```

Carbon version: **PUT HERE YOUR CARBON VERSION (exact version, not the range)**
2.44

PHP version: **PUT HERE YOUR PHP VERSION**
7.3.13

I expected to get:

```
2020-02-01
```

But I actually get:

```
2020-03-01
```

https://try-carbon.herokuapp.com/ not working
The dates 29 til 31 of januari only not working.

Thanks!

**Comment by kylekatarnls** [comment]
`ceilMonth()` basically rely on the following steps:

```php
echo (new DateTime('2021-01-31'))
    ->modify('next month')
    ->modify('first day of this month')
    ->format('Y-m-d');
```

And as you can see, this produces `2020-03-01` also using only pure PHP. Not sure yet how to deal with it as ceil/round/floor are meant to be the same for all and with an optional `$precision` parameter. It would be annoying to write a specific implementation for month with specifically `$precision = 0`

**Comment by kylekatarnls** [comment]
Work-around added for 2.45.0

**Comment by willrowe** [comment]
> ceilMonth() basically relies on the following steps:

> ```php
> echo (new DateTime('2021-01-31'))
>    ->modify('next month')
>    ->modify('first day of this month')
>    ->format('Y-m-d');
> ```

Would this work more reliably?
```php
echo (new DateTime('2021-01-29'))
    ->modify('last day of')
    ->modify('next day')
    ->format('Y-m-d');
```

**Comment by kylekatarnls** [comment]
This was just an illustration. `ceilXyz($n)` is actually a magic method. There is nothing specific to "month". It can take any unit from millisecond to millenium, any of the floor/round/ceil method. And it has a precision parameter, so the same process applies to: rounding 10 minutes, flooring 0.5 day, ceiling 1 month. Obviously we won't customize all possible combinations.

Still this is fixed on `dev-master` version, to be released during the month.
