### ISSUE TITLE
Broken translation tool

### ISSUE THREAD

**Issue by jurchiks** [briannesbitt/Carbon#2271]
Hello,

I was working on #2091 and was trying to find info on all the different translation keys when I saw the "Contribute to translations" link in your page, but opening it yielded a blank page (in Google Chrome and Firefox).

The error I'm seeing is this:
```
Access to XMLHttpRequest at 'https://try-carbon-package.herokuapp.com/api/carbon.php' from origin 'https://carbon.nesbot.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```
The page in question is https://carbon.nesbot.com/contribute/translate/

I'm not sure if this is the right place for this bug report, but the homepage repo didn't seem to have anything to do with the `carbon.` subdomain, so I decided to post here.

**Comment by kylekatarnls** [comment]
Hello,

With the in-development 3.x version, master has been split into 2.x-dev and 3.x-dev and translation tool was still retrieving translation file from master version. Heroku is the hosting provider allowing to handle multiple versions of the same package. It failed before CORS headers was sent so this error appears. I added an alias so it's now up again.

Thanks.
