### ISSUE TITLE
addSeconds(x) - missing 1 second

### ISSUE THREAD

**Issue by jurchiks** [briannesbitt/Carbon#2273]
Hello,

I encountered an issue with the following code:
```php
echo Carbon::now()->addSeconds(5)->diffForHumans();
```

I expected to get:
```
'5 seconds from now'
```

But I actually get:
```
'4 seconds from now'
```

Any amount of seconds will work. One might expect this to be an issue with the diff taking a whole second - or close to it -, but the test runs in 200-ish milliseconds, so rounding shouldn't be the cause.

Carbon version: master branch, forked just prior to making this issue (0d87f3d) / also tried in a separate repo with 2.44.0
PHP version: 7.4.12

**Comment by kylekatarnls** [comment]
Hello,

The code do not run instantly, few microseconds elapse between `now()` is executed and `diffForHumans()` is.

By default, the result is rounded down (`CarbonInterface::FLOOR`) but you can get `5` seconds using `ROUND`:

```php
echo Carbon::now()->addSeconds(5)->diffForHumans(['options' => CarbonInterface::ROUND]);
```

Thanks.

**Comment by jurchiks** [comment]
Yeah, I get that it doesn't run instantly, but that doesn't look right to me. Why would it be rounded down by default?

**Comment by kylekatarnls** [comment]
I won't change the default behavior, it would be a breaking change. `FLOOR` is safe and unambiguous, and not worse as `ROUND` neither 4 or 5 are 4.99, both are opinionated way to approximate the exact value. And years of Carbon tickets told me than the intuitive expectation of the ones is a big surprise for the other who use a given method in different contexts and cases.

**Comment by kylekatarnls** [comment]
For the record, if you are in a unit test context, you should freeze the time and you would not get such problem using `Carbon::setTestNow(Carbon::now())`

See more in the doc: https://carbon.nesbot.com/docs/#api-testing
