### ISSUE TITLE
parse method has somehting wrong when timestamp is passed in ,version laravel7

### ISSUE THREAD

**Issue by MIKOTO123** [briannesbitt/Carbon#2277]
![image](https://user-images.githubusercontent.com/19549093/106873728-b55eee80-670f-11eb-914f-5ffc738512f8.png)

result:
![image](https://user-images.githubusercontent.com/19549093/106873794-ca3b8200-670f-11eb-9f7e-4c36bdfe0726.png)
the timezone be fixed in utc????

**Comment by MIKOTO123** [comment]
$time = time();
        Logger::debugLog($time);
        Logger::debugLog(Carbon::parse($time,'Asia/Shanghai')->toDateTimeString());//focus this one
        Logger::debugLog(Carbon::parse($time,'Asia/Shanghai')->timestamp);
        Logger::debugLog(Carbon::createFromTimestamp($time)->toDateTimeString());
        Logger::debugLog(Carbon::createFromTimestamp($time)->timestamp);
        Logger::debugLog(config('app.timezone'));


result:


[2021-02-04 17:28:43] local.INFO: 1612430923  
[2021-02-04 17:28:43] local.INFO: 2021-02-04 09:28:43  
[2021-02-04 17:28:43] local.INFO: 1612430923  
[2021-02-04 17:28:43] local.INFO: 2021-02-04 17:28:43  
[2021-02-04 17:28:43] local.INFO: 1612430923  
[2021-02-04 17:28:43] local.INFO: Asia/Shanghai

**Comment by kylekatarnls** [comment]
`time()` don't take your `config('app.timezone')` into account, it's a PHP native function that always gives you the timestamp, and the timestamp is by definition UTC as it's number of seconds since January 1st 1970 midnight UTC.

As you don't follow the issue pattern, it's not clear to me what you expect. If you need further details, please complete all the required fields of the issue template the GitHub form kindly asked you not to remove.

Thanks.

**Comment by MIKOTO123** [comment]
> Hello,
> 
> I can't see anything wrong in your screenshot and no timezone isnot fixed in UTC for the one date you highlighted.
> 
> `time()` don't take your `config('app.timezone')` into account, it's a PHP native function that always gives you the timestamp, and the timestamp is by definition UTC as it's number of seconds since January 1st 1970 midnight UTC.
> 
> As you don't follow the issue pattern, it's not clear to me what you expect. If you need further details, please complete all the required fields of the issue template the GitHub form kindly asked you not to remove.
> 
> Thanks.

oh,it's my fault.I knew "time()" is not have nothing to do with timezone .I mean Carbon::parse() method the second parameter Isn't it for set timezone?Is it dont work? What does the second parameter for Carbon::parse($time,$tz)????

**Comment by kylekatarnls** [comment]
We pass directly the timezone to PHP inherited DateTime class, and that's how it works with timestamp (enforce UTC):

https://3v4l.org/LNWNE

You can `Carbon::createFromTimestamp($time)->tz('Asia/Shanghai')->toDateTimeString)` (or `Carbon::parse($time)->tz('Asia/Shanghai')->toDateTimeString)` but I recommend the first explicit one).

So it's generally the timezone argument when the given string is a timezone-dependent date string, but if the timezone is already specified in the string, then PHP will ignore this parameter, for instance:

```php
new DateTime('2021-01-05 Europe/Paris', new DateTimeZone('Asia/Shanghai'))
```
Here you get Paris. That's actually the same principle with timestamp, timestamp kinda have "UTC" appended to it.

If you feel like it should behave differently, you'll need to open a ticket on https://bugs.php.net/ but I doubt they'll change that.

**Comment by MIKOTO123** [comment]
> We pass directly the timezone to PHP inherited DateTime class, and that's how it works with timestamp (enforce UTC):
> 
> ```
> new DateTime('@1612515258', new DateTimeZone('Asia/Shanghai')) // Shanghai timezone ignored, UTC applied
> ```
> 
> https://3v4l.org/LNWNE
> 
> You can `Carbon::createFromTimestamp($time)->tz('Asia/Shanghai')->toDateTimeString()` (or `Carbon::parse($time)->tz('Asia/Shanghai')->toDateTimeString()` but I recommend the first explicit one).
> 
> So it's generally the timezone argument when the given string is a timezone-dependent date string, but if the timezone is already specified in the string, then PHP will ignore this parameter, for instance:
> 
> ```
> new DateTime('2021-01-05 Europe/Paris', new DateTimeZone('Asia/Shanghai'))
> ```
> 
> Here you get Paris. That's actually the same principle with timestamp, timestamp kinda have "UTC" appended to it.
> 
> If you feel like it should behave differently, you'll need to open a ticket on https://bugs.php.net/ but I doubt they'll change that.

Ok,thank you very much!After that,I had seen the Carbon project source,it really extend DateTime class.But I still think that's more reasonable.I also think they'll change that not.
