### ISSUE TITLE
Intallation problem

### ISSUE THREAD

**Issue by birdiebel** [briannesbitt/Carbon#228]
I am a Laravel Newbies. 
I install Laravel 4.2 then I install Carbon with Composer.
I add to config/app.php :  
in Providers : 'Carbon/Carbon'
in Alliasses : 'Carbon'  => 'Carbon/Carbon'

When I start app I get this message : 
DateTime::__construct() expects parameter 1 to be string, object given 

Please help, thanks !

**Comment by tjbenator** [comment]
You shouldn't have to install Carbon in your project. It is already a dependency of the laravel/framework package and will already be autoloaded in to your environment.
https://github.com/laravel/framework/blob/4.2/composer.json

There isn't a Carbon service provider, so adding it to the Providers array isn't necessary. I don't know that the alias is necessary either.

**Comment by briannesbitt** [comment]
You'd probably have better luck on the laravel forums.
