### ISSUE TITLE
Carbon 2.45.0 - ceilMonth() returns incorrect year when overflowing

### ISSUE THREAD

**Issue by nXu** [briannesbitt/Carbon#2285]
Hello,

I encountered an issue with the following code:
```php
echo Carbon::parse('2021-12-17')->ceilMonth()->format('Y-m-d');
```

Carbon version: **2.45.0**

PHP version: **7.3**

I expected to get:

```
2022-01-01
```

But I actually get:

```
2023-01-01
```

Thanks!

Reproducible on https://try-carbon.herokuapp.com/

**Comment by kylekatarnls** [comment]
Thanks, it's a regression, I will fix it quickly, meanwhile you can downgrade carbon to 2.44.0.
