### ISSUE TITLE
Format UTC date to locale and locale pattern

### ISSUE THREAD

**Issue by naveenabt** [briannesbitt/Carbon#2289]
Hi Team,

How to format the UTC date to locale and locale pattern?

Ex: 

**India en-IN** locale pattern: dd/mm/yyyy HH:mm:ss
**US en-US**  locale pattern: mm/dd/yyyy HH:mm:ss

How we can achieve this?
Is this feature available or not?

Thanks,

**Comment by kylekatarnls** [comment]
Hello,

https://carbon.nesbot.com/docs/#api-localization

```php
echo Carbon::now()->locale('en_IN')->isoFormat('L LTS');
echo "\n";
echo Carbon::now()->locale('en_US')->isoFormat('L LTS');
```

Will give you standard date and standard time format for each locale, note that en_US does not use HH:mm:ss but am/pm notation. And en_IN has year on 2 digits only. This should be the common standard for each but you can customize those for each locale (see the documentation link above).

**Comment by naveenabt** [comment]
Thanks kylekatarnls.

Could you please address below queries?

**1->** I am looking for Carbon php code for the below JS code.

date = new Date(date);
date.toLocaleDateString('en-IN');

**2->** is there any function to get the locale date pattern?

ex: If we pass **en-IN** as input, it should provide output as 'dd/mm/yyyy HH:mm:ss'

**Comment by kylekatarnls** [comment]
1. Answered above (`L` is for the date,`LTS` is for the time), please read https://carbon.nesbot.com/docs/#api-localization
2. `en_IN` format is `DD/MM/YY HH:mm:ss` (not `yyyy`):
`echo Translator::get('en-IN')->trans('formats.L') . ' '. Translator::get('en-IN')->trans('formats.LTS');`

**Comment by naveenabt** [comment]
Thanks a lot **kylekatarnls**

**Comment by naveenabt** [comment]
`echo  \Carbon\Translator::get('en_US')->trans('formats.L') . ' '.  \Carbon\Translator::get('en_US')->trans('formats.LTS');`

**Output**:

formats.L formats.LTS

for en_US it is not working.

**Comment by kylekatarnls** [comment]
Indeed, it's because it does not have specific format but has the fallback formats. This snippet may be easier to solve this:

```php
$formats = Carbon::now()->locale('en_US')->getIsoFormats();

echo $formats['L'] . ' '. $formats['LTS'];
echo "\n";

$formats = Carbon::now()->locale('en_IN')->getIsoFormats();

echo $formats['L'] . ' '. $formats['LTS'];
```

**Comment by naveenabt** [comment]
Thanks **kylekatarnls** ,

**Below is the my query.**

In Javascript(frontend) using below code to fromat date for locale.

```
date = new Date('2020-12-11 17:49:14');
formattedDate = date.toLocaleDateString('en-IN');
formattedDate += ' ' + date.toLocaleTimeString('en-IN',{ hour12: false,  timeStyle: 'medium' });
```

**Output**:

11/12/2020 17:49:14

In JS date formatting with pattern  dd/MM/YYYY HH:mm:ss


In **backend(php)**, using **carbon library** to convert date to locale pattern.

1- > Below code output is **dd/MM/YY HH:mm:ss**

```
$formats = Carbon::now()->locale('en_IN')->getIsoFormats();

echo $formats['L'] . ' '. $formats['LTS'];
```

2-> Below code output is **16/02/21 14:52:46**

`echo Carbon::now()->locale('en_IN')->isoFormat('L LTS');`

Now in frontend and backend date is showing in different format.

_is there any way to format the date in carbon as JS code?_

**Comment by kylekatarnls** [comment]
As explained in my post above and in the documentation I linked, you can set the format for a locale to whatever you like:
```php
\Carbon\Translator::get('en_IN')->setTranslations([
    'formats.L' => 'DD/MM/YYYY',
]);
$formats = Carbon::now()->locale('en_IN')->getIsoFormats();

echo $formats['L'] . ' '. $formats['LTS'];
echo "\n";
echo Carbon::now()->locale('en_IN')->isoFormat('L LTS');
```

**Comment by naveenabt** [comment]
I have 400+ locale, in this case we have to make configuration for pattern to each locale.


As you can see in below JS code, no where we are passing pattern.

```
date = new Date('2020-12-11 17:49:14');
formattedDate = date.toLocaleDateString('en-IN');
formattedDate += ' ' + date.toLocaleTimeString('en-IN',{ hour12: false,  timeStyle: 'medium' });
```

is there any carbon code which is equivalent to above JS code?

**Comment by naveenabt** [comment]
@kylekatarnls  Please provide the response for the above post.

Thanks.

**Comment by kylekatarnls** [comment]
Most of the locales in Carbon follows the [CLDR](http://cldr.unicode.org/index/downloads/cldr-38) and are fixed if relevant here by submitting a PR.

I don't know where the 4-digits year of `toLocaleDateString` comes from precisely.

To run JS code and get the exact same result, you need Node.js.

Node.js could also be used to generate the needed formats for all our 800+ locales because the sure thing is I won't implement this manually. And I don't think we should provide 1 more formatting method, but it could make a good mixin. I would refer it in the doc if you or someone else would propose some to implement equivalent `toLocaleDateString` / `toLocaleTimeString`

Note that the ISO format codes `L`, `LTS` are compatible with some libraries like [momentjs](https://momentjs.com/) `moment().format('L LTS')`

But what each code is in each language change and vary from implementations, and it's impossible to guarantee a 100%-matching.
