### ISSUE TITLE
diffAsCarbonInterval thinks there is 28 days in Jan 2021

### ISSUE THREAD

**Issue by PaulMcRoar** [briannesbitt/Carbon#2296]
Hello,

I encountered an issue with the following code:

use Carbon\Carbon
$s = Carbon::create('2021','01','01','00','00','00','UTC');
$e = Carbon::create('2021','02','01','00','00','00','UTC');

echo $s->diffAsCarbonInterval($e)->totalDays;
=> 28

This also impacts totalHours etc.

Carbon version: **PUT HERE YOUR CARBON VERSION (exact version, not the range)**
2.45.1

PHP version: **PUT HERE YOUR PHP VERSION**
7.4.3

I expected to get:
31

But I actually get:
28

Thanks!

**Comment by PaulMcRoar** [comment]
Actually, it looks like carbon interval considers every month to be 28 days long

**Comment by kylekatarnls** [comment]
Interval has no memory (in version 2.x) of the date you used to create it. And then you can create an interval from pure value:

```php
CarbonInterval::months(1)
```

So we have no particular reason to choose 31. 28 is the default as it allow an integer factor of 4 weeks, but you can change it as mentioned in the doc:

```php
CarbonInterval::setCascadeFactors([
    'minute' => [60, 'seconds'],
    'hour' => [60, 'minutes'],
    'day' => [8, 'hours'],
    'month' => [31, 'days'],
]);
```

But in your precise case, you just don't need the extra-step with `diffAsCarbonInterval`, just use `diffInDays`:

```php
$s = Carbon::create('2021','01','01','00','00','00','UTC');
$e = Carbon::create('2021','02','01','00','00','00','UTC');

echo $s->diffInDays($e); // 31
```
