### ISSUE TITLE
Fatal Error occurs when calling msgpack_unpack() function in PHP 7.4 or higher environment.

### ISSUE THREAD

**Issue by suzunone** [briannesbitt/Carbon#2299]
Hello,
Fatal Error occurs when calling msgpack_unpack() function in PHP 7.4 or higher environment.

The msgpack_unpack() function can be used if pecl msgpack is enabled.
https://pecl.php.net/package/msgpack

I encountered an issue with the following code:
```php
$now = \Carbon\Carbon::parse('2018-06-01');
$message = @msgpack_pack($now);
$copy = msgpack_unpack($message);
```

Carbon version: **2.46.0**

PHP version: **7.4.14**

pecl msgpack version:**msgpack-2.1.2**
https://pecl.php.net/package/msgpack

I expected to get:

```
PHP Fatal error:  Uncaught Error: Invalid serialization data for DateTime object in ./vendor/nesbot/carbon/src/Carbon/Traits/Serialization.php:131
Stack trace:
#0 ./vendor/nesbot/carbon/src/Carbon/Traits/Serialization.php(131): DateTime->__wakeup()
#1 [internal function]: Carbon\Carbon->__wakeup()
#2 ./test.php(6): msgpack_unpack('\x84\xC0\xADCarbon\\Carbo...')
#3 {main}
  thrown in ./vendor/nesbot/carbon/src/Carbon/Traits/Serialization.php on line 131
```

But I actually get:

```
$now  = $copy;
```

Thanks!

**Comment by kylekatarnls** [comment]
Hello, 👋 

Does the following work:
```php
$now = new DateTime('2018-06-01');
$message = @msgpack_pack($now);
$copy = msgpack_unpack($message);
```

If it does not, then it would be way more relevant to fix the error in `msgpack` as it impact any `DateTime` sub-class.

Else it means it impact only classes that extends `DateTime` and override `parent::__wakeup()` which is still a normal PHP case that should work in PHP >= 7.4 as per the `unserialize()` test:
https://github.com/briannesbitt/Carbon/blob/b5cb758d2cc28edf2e2490d423b466be785f376d/tests/Carbon/SerializationTest.php#L54

Replacing `__wakeup` with `__construct` as proposed https://github.com/briannesbitt/Carbon/pull/2300 would be a work-around that may cause other issues. `DateTime::__wakeup` is supposed to be called on unserialization and I'm a bit reluctant to short-circuit it just to please a minor package.

Finding what exactly msgpack is failing on here may help to get a better long-term fix.

**Comment by suzunone** [comment]
Hello, 
Thanks for your reply.

If it use the vanilla DateTime class instead of Carbon as suggested, it works fine.

``` .php
<?php

$now = new DateTime('2018-06-01');
$message = @msgpack_pack($now);
$copy = msgpack_unpack($message);

var_dump($copy);
```

```
test.php:7
class DateTime#2 (3) {
  public $date =>
  string(26) "2018-06-01 00:00:00.000000"
  public $timezone_type =>
  int(3)
  public $timezone =>
  string(10) "America/Toronto"
}
```

If it call __wakeup() method directly, as in the following example,  will get a Fatal error.

``` .php
<?php

$now = new DateTime('2018-06-01');
$now->__wakeup();

```

```
PHP Fatal error:  Uncaught Error: Invalid serialization data for DateTime object in ./test.php:4
Stack trace:
#0 /data/webapp/test.php(4): DateTime->__wakeup()
#1 {main}
  thrown in /data/webapp/test.php on line 4

```
This error did not occur in 7.3 or earlier.

Pecl msgpack calls __wakeup() method when msgpack_unpack() is called, as expected.
I haven't tried other libraries than msgpack, but I think the same problem may occur with similar serialize libraries.
