### ISSUE TITLE
diffForHumans() shows 1s even with subSeconds(0)

### ISSUE THREAD

**Issue by dcortez** [briannesbitt/Carbon#2302]
Hello,

I believe the following is potentially a bug. Running the following code:

```php
echo \Carbon\Carbon::now()->subSeconds(0)->shortAbsoluteDiffForHumans(3);
```

Carbon version: **2.46.0**

PHP version: **7.3.27** 

I expected to get:

```
0s 
```

But I actually get:

```
1s
```

Thanks!

**Comment by kylekatarnls** [comment]
Hello, 👋 

This behavior is due to the option `Carbon::NO_ZERO_DIFF` (on by default):
https://carbon.nesbot.com/docs/#diff-for-humans-options

You can get `0s` using:
```php
echo Carbon::now()->diffForHumans(['syntax' => CarbonInterface::DIFF_ABSOLUTE, 'options' => 0, 'short' => true, 'parts' => 3]);
```

I will re-evaluate the relevance of those default options for the version 3.

Thanks.
