### ISSUE TITLE
Get Dates By Passing Day name

### ISSUE THREAD

**Issue by afrasiyabhaider** [briannesbitt/Carbon#2306]
I wanted to get dates of only specific days within given range e.g
From 19-March-2021
To      6-June-2021
Days = ['Monday','Tuesday']

So it should give me dates within my given range and the dates should only be of Monday and Tuesday
Do anyone have idea about this?

**Comment by kylekatarnls** [comment]
Use `CarbonPeriod` to iterate over each day between 2 dates:
https://carbon.nesbot.com/docs/#api-period

Then you can easily check if a day is one of the value of your array using:
```php
foreach (CarbonImmutable::parse('19-March-2021')->daysUntil('6-June-2021') as $dateTime) {
  if (in_array($dateTime->dayName, ['Monday','Tuesday'])) {
    echo $dateTime->format('Y-m-d') . "\n";
  }
}
```
