### ISSUE TITLE
Gitlab CI error: uncommited..

### ISSUE THREAD

**Issue by m-bosch** [briannesbitt/Carbon#2307]
Hello,

I encountered an issue with the following code:
```php
vendor/nesbot/carbon has uncommitted changes.  
```
"name": "nesbot/carbon",
            "version": "2.46.0",
            "source": {
                "type": "git",
                "url": "https://github.com/briannesbitt/Carbon.git",

**Comment by kylekatarnls** [comment]
Hello 👋 

Which are the changes?

```
cd /home/travis/build/vendor/nesbot/carbon && git status
```

Please note that anything from your app or your other packages can modify the vendor directory fairly or not so I will need way more info to help your.

As for any regular issue, I need your code and so a `.travis.yml` and `composer.json` files and minimum project files to reproduce the issue.

Thanks.

**Comment by m-bosch** [comment]
The problem was in the cache of the Gitlab-CI. with removing cache it was solved. Never the less there was a broken release earlier on, but that is fixed :-)
