### ISSUE TITLE
Best way to transform \DateTime in \Carbon

### ISSUE THREAD

**Issue by Unibozu** [briannesbitt/Carbon#231]
Hi there,

This is not a proper issue, but more a question : is there a proper way to transform a \DateTime object (often returned by third party library - like Doctrine in my case) to a Carbon powered object ?
As the constructor accepts the same arguments as \DateTime it is possible to format the \DateTime to a unambiguous string and send it to Carbon but it doesn't feel nice.

Keep up the good work

**Comment by dinamic** [comment]
@kylekatarnls thanks for explaining. Turned out we are running 1.22. We'll get to revise on what's stopping us from migrating to a newer version.

**Comment by kylekatarnls** [comment]
New features require minor update in semantic version, that's why you should have `^1.x` or `^2.x` and should run `composer update` from time to time (for example when your own library/product has a minor release). Also, Carbon 1 was mostly still supported because of Laravel requirement, as Laravel stopped to support its version 5.7 (the last one that used Carbon 1), we'll progressively stop the maintenance of the version 1. The last minor release of Carbon 1 should come before the end of 2019, so prefer to upgrade directly to `^2`, it's not a big step, it's 99% backward compatible, breaking changes are listed here: https://carbon.nesbot.com/docs/#api-carbon-2

**Comment by top-master** [comment]
Notice that this is an issue's thread, hence the 100+ votes show that it's a huge design issue,
and that it is time to support something like:
```php
$carbon = Carbon::createFromDateTime($dateTime);
```

Not something confusing, like:
```php
$carbon = Carbon::instance($dateTime);
```

**Comment by kylekatarnls** [comment]
The cleanest way is given in the very first example of the first chapter after intro in docs:
https://carbon.nesbot.com/docs/#api-instantiation

```php
$carbon = new Carbon($dateTime);
```

It can't be more neat and I don't think we should add more alias for this. Also making all the features being guessable for preferences of everybody without having to read the doc isn't a challenge I would plan to try.

Thanks.

**Comment by TomasVotruba** [comment]
I've found this issue when I wanted to migrate `DateTime` to Carbon to fix our tests. In case anyone is looking for similar solution, we've just added Rector set to handle the migration: https://getrector.com/blog/migrate-datetime-to-carbon

**Comment by kylekatarnls** [comment]
Thank you @TomasVotruba! I think it can be pretty handy, mainly for people looking for a way to mock time in their tests for their existing code :) 

I suggest to also include the conversion for immutable dates:
https://github.com/rectorphp/rector/pull/8645

**Comment by TomasVotruba** [comment]
@kylekatarnls Makes sense, thank you :+1: :)  
If you find any other case, let me know. We're still exploring this area and look for new use cases.

**Comment by kylekatarnls** [comment]
Yep, I think I can suggest few things and might try to get PR for them. I see you have `date()` to `Carbon::now()->format()` conversion. In the same way (assuming people are looking for a way to mock time) then we can add `time()` to `Carbon::now()->getTimestamp()` (or `Carbon::now()->timestamp`)

**Comment by TomasVotruba** [comment]
Sounds great 👍 

> then we can add time() to Carbon::now()->getTimestamp() (or Carbon::now()->timestamp)

I thought of that but wasn't sure about best practice. PR would be awesome 🙏
