### ISSUE TITLE
,, Poland ,, is recognized as Timezone (Or whatever).

### ISSUE THREAD

**Issue by JovanS-BAD** [briannesbitt/Carbon#2311]
Hello,

I encountered an issue with the following code:
```php
echo Carbon::parse('Poland');
```

Carbon version: v2.46.0

PHP version: 8.0

I expected to get: 

```
Failed to parse time string (Poland) at position 0....
```

But I actually get:  (Current time for server)

```
2021-04-07 16:59:25
```
I have tested this also on https://web.tinkerwell.app/#/
just run:
use Carbon\Carbon;
echo Carbon::parse('Poland');

Thanks!

**Comment by JovanS-BAD** [comment]
If you do any other country Italy, Serbia, Russia, Germany... You will get Failed to parse time string.

**Comment by kylekatarnls** [comment]
Hello 👋 

`Carbon` extends native PHP `DateTime` and as for timezone support, we simply pass the string as is to `DateTimeZone` which means anything the native PHP `DateTimeZone` class supports is also supported by `Carbon`:

As you can see it handle `"Poland"` as a valid timezone:
https://3v4l.org/h0R1a

Also if we try the following pure PHP code:
```php
echo (new DateTime('2021-04-07 19:20 Poland'))->format('Y-m-d H:i:s e T');
```

We get:
```
2021-04-07 19:20:00 Poland CEST
```

Honestly I don't know if it's intended or not for PHP team. Using country names as timezone is a very bad practice (for Russia or such countries which multiple timezones it would be way too ambiguous) and even for countries with only 1 timezone, it will lead to interoperability problems when trying to parse it again in some other languages/systems.

So I would say it's a bug as a first sight but it's on the PHP side you may try to open a bug if there is not yet one open for that issue:
https://bugs.php.net/search.php?cmd=display&search_for=timezone&x=0&y=0

**Comment by kylekatarnls** [comment]
This is actually known and kept for backward compatibility:

https://www.php.net/manual/en/timezones.others.php

PHP recommends not to use them.

**Comment by kylekatarnls** [comment]
We can see:

```php
$t = new DateTimeZone('Poland');
var_dump($t->getLocation()['country_code']); // ??
$t = new DateTimeZone('Europe/Warsaw');
var_dump($t->getLocation()['country_code']); // PL
```

Which mean you can detect an object has a obsolete timezone using:
```php
$tz = 'Poland';
$date = Carbon::parse($tz');

if ($date->tz->getLocation()['country_code'] === '??') {
  throw new \InvalidArgumentException("$tz is not a valid timezone");
}
```
