### ISSUE TITLE
Add support for adding microseconds or milliseconds

### ISSUE THREAD

**Issue by dmyers** [briannesbitt/Carbon#232]
Could there be a way to add microseconds or milliseconds somehow or is there a way already?

**Comment by briannesbitt** [comment]
Currently its not supported.  Only reading the current value is supported.

**Comment by cjunge-work** [comment]
If the constructor generates "now" using a timestamp with microseconds, then DateTime will store that internally. ie. 
```
list($usec, $sec) = explode(' ', microtime());
$dt = new DateTime(date('Y-m-d\TH:i:s', $sec) . substr($usec, 1));  
echo $dt->format('Y-m-d\TH:i:s.u');
```
It's messy, but it works!

**Comment by mazhuravlev** [comment]
Still not works for version 1.21.0.

**Comment by mazedulislamkhan** [comment]
In the meantime, why not convert the milliseconds to the seconds by driving it to the thousand?

Example for Laravel:
`Carbon::createFromTimestamp(1467507452744 / 1000)->diffForHumans() // 1 second ago`

**Comment by abhimanyu003** [comment]
:+1:

**Comment by asch3ron** [comment]
👍

**Comment by eman1986** [comment]
This would be great to have baked in as MongoDB for PHP gives you back milliseconds, the code suggestion above is working for me so I'll be using that until this is added in

**Comment by agengdp** [comment]
+1

**Comment by briannesbitt** [comment]
Not a full implementation, but you can now create an instance with milliseconds. #988 988
