### ISSUE TITLE
Invalid GMT timezones (GMT+62) are supported

### ISSUE THREAD

**Issue by saibotd** [briannesbitt/Carbon#2331]
Hello,

I encountered an issue with the following code:
```php
echo Carbon::now('GMT+62')->toDateTimeString();
```

Carbon version: **2.48.0**

PHP version: **7.4.16**

I expected to get:

```
Error: Unknown or bad timezone (GMT+62)
```

But I actually get:

```
2021-05-21 01:04:04
(three days in the future)
```
I think that might be a serious issue whenever the user-provided timezone has to be trusted, but can exceed +-12h like this.

btw. `date_default_timezone_set("Etc/GMT+62");` warns `<b>Notice</b>:  date_default_timezone_set(): Timezone ID 'Etc/GMT+62' is invalid in <b>[...][...]</b> on line <b>4</b><br />`

Thanks!

**Comment by kylekatarnls** [comment]
Hello,

This is not part of the Carbon responsibility. PHP decides what is a valid timezone (if `new \DateTimeZone('GMT+62')` is valid or not is determined by PHP itself).

The validation is simple: anything between -99 to 99 is valid. And that's actually fair. Timezones are not limited to -12/+12, The Kirimati Island uses officially the timezone GMT+14. And those can evolve. Timezones with minutes (and even seconds shift) also exist. Basically you should take any assertion on a timezone being in a particular range or following particular pattern.

However you could (and likely should) enforce city timezones (`America/Toronto`, `Europe/Paris`, etc.) which are not necessarily offset fixed but are real timezones on world, while offset are not representing any real point on earth. Numeric offset just means the datetime is seen with more or less time. You can choose to set your device to show the time with a GMT+1.45 or GMT-99 shift if you like, it does have to be official somewhere.

Side note about "three days in the future" => that's not true. GMT + or - is not something in the past or future `now()` is always "now", but you see the representation of it with a particular clock setting.

Thanks.
