### ISSUE TITLE
Breaking change in CarbonPeriod tag 2.49.0 by adding `-` to regex

### ISSUE THREAD

**Issue by Levivb** [briannesbitt/Carbon#2352]
Hello,

I encountered an issue with the following code:
```php
foreach (new CarbonPeriod('-30 minutes', '1 minute', 'now') as $time) {
```

Carbon version: **2.49.0**

PHP version: **7.4.19**

I expected to get:

```
An iterator with 30 items from 30 minutes ago till current time with 1 minute steps
```

But I actually get:

```
An empty iterator
```

Addition:
diff: https://github.com/briannesbitt/Carbon/compare/2.48.1...2.49.0
file: src/Carbon/CarbonPeriod.php
```diff
- '/^(\d(\d(?![\/-])|[^\d\/-]([\/-])?)*|P[T0-9].*|(?:\h*\d+(?:\.\d+)?\h*[a-z]+)+)$/i',
+ '/^(-?\d(\d(?![\/-])|[^\d\/-]([\/-])?)*|P[T0-9].*|(?:\h*\d+(?:\.\d+)?\h*[a-z]+)+)$/i',
```

The addition of the leading `-` causes the first argument of the `new CarbonPeriod('-30 minutes', '1 minute', 'now')` statement to be applied to `$this->setDateInterval($parsed);`, but it should have been applied to `$this->setStartDate($parsed);`

This might be a desired change, bit it's unfortunately not really backwards compatible

Thanks!

**Comment by Levivb** [comment]
FYI I'm currently fixing it on our side by using `CarbonPeriod::start('-30 minutes')->step('1 minute')->until('now')` instead

**Comment by kylekatarnls** [comment]
Hello 👋

I don't think we'll re-allow this syntax, because it's ambiguous (and so dangerous). For instance there is no reason to get différent behavior with `30 minutes` or `-30 minutes` but in your examples you can see that with Carbon 2.48 you get `30 minutes` as interval (without the minus sign) and not now + 30 minutes as the start date, so we recommend instead to use the explicit syntax:

```php
foreach (new CarbonPeriod('now -30 minutes', '1 minute', 'now') as $time) {
  echo "$time\n";
}
```

With this syntax, it's clear what is a moment (start/end) and what is the step interval. This is way safer.

**Comment by kylekatarnls** [comment]
Side note `floorMinutes()` should not be needed in your example to get the same behavior, there is no floor-rounding neither with the version you had before the 2.49 release.

Other solution is:
```php
foreach (Carbon::parse('-30 minutes')->minutesUntil('now') as $time) {
  echo "$time\n";
}
```
It provide the exact same output in a code even shorter and and unambiguous way.

So I'll keep the 2.49 behavior as the lack of support for negative interval string is inconsistent and a real disadvantage while `-30 minutes` used as a start date is quite more an edge case and can more easily be worked around.

Thanks for the issue, it can likely help other people to find and adapt their code.

**Comment by kylekatarnls** [comment]
BC added to release notes: https://github.com/briannesbitt/Carbon/releases/tag/2.49.0

**Comment by Levivb** [comment]
Thanks for the tips, alternatives and the addition in the release notes 👍  that will do!

I'll keep it to `CarbonPeriod::start(...)->step(...)->until(...)` as it's the most explicit one

`floorMinutes` is indeed not needed because of this change here, but just so happens to catch an edge case in our code I noticed when interpreting the flow :)
