### ISSUE TITLE
Month overflow

### ISSUE THREAD

**Issue by tshelburne** [briannesbitt/Carbon#236]
This isn't necessarily an issue, since it appears to be tested [here](https://github.com/briannesbitt/Carbon/blob/master/tests/AddTest.php#L56), but I'm curious as to why the preferred mechanism for adding a month would allow for overflow? Conceptually, I expect adding a month to increment the month by one, and if overflow happens, it will end up on the last day of the next month.

Is there an alternative to `addMonth` that works this way? Would you be opposed to either a boolean flag or a new method that would work this way? I'm going to be looking through the code, but... it's a pretty long file.

**Comment by kylekatarnls** [comment]
It's a bit tricky since adMonth directly call the DateTime::modify function. But you can fix the date after modify:
<pre>$oldDate = Carbon::createFromDate(2012, 1, 31);
$newDate = $oldDate->addMonth();
if($newDate->day < $oldDate->day) {
    $newDate->subMonth();
    $newDate->day = $newDate->daysInMonth;
}</pre>

**Comment by tshelburne** [comment]
@kylekatarnls That is exactly the PR I would submit, except that it would be the default behavior of the `addMonth` function. From my perspective, the more natural behavior is to return a date in the following month, regardless of how many days are in that month. When I call `addDate` on a date in January, I will always expect a date in February to be returned.

**Comment by briannesbitt** [comment]
Rolling over is the expected default behaviour.

Sounds like you want a addMonthNoOverflow() which wouldn't be hard to add, just depends on desired results.

If it were Feb 28 and you added 1 month would you expect Mar 28 or Mar 31 ? (Ie. Do you want it to stick to the end of the month when its longer as well?) Since Jan 31 + 1 month you want Feb 28.

**Comment by tshelburne** [comment]
@briannesbitt Good question - I just submitted PR #239 that shows the exact behavior I would expect, plus my idea for what I think would be a more intuitive interface. That said, it's all subjective.

Happy new year!

**Comment by kylekatarnls** [comment]
Intuitive to you indeed. In all project, we do not break existing functions in minor versions. So if every body think the default PHP DateTime behaviour is a bug, it should only be added in the next major version. But I think (and I'm pretty sure I'm not the only one), default overflow is a good behavior, and you should do what @briannesbitt suggest: create addMonthNoOverflow() and as it do not seem to be a very needed function, you should better to extend Carbon with your own class and add the function in it. Anyway, it's a very interesting poin and it should be great some users give their opinion.

**Comment by tshelburne** [comment]
@kylekatarnls That's all exactly what I did in the PR. As far as whether it's needed, that's seems as subjective a judgment as finding it unintuitive - and having an option in the library that provides the functionality while also acting as documentation of what some people may consider unintuitive seems like a good move to me.

**Comment by PrplHaz4** [comment]
I agree that this functionality is more intuitive at first blush, but as @briannesbitt pointed out, the details make it not as obvious.  I do feel it's a necessary feature, but not worth breaking BC.

I've implemented similar behavior on my own, and for my use case, I need the last day of the month (how can something be monthly if February is skipped altogether?)...

anyways, thanks for this @tshelburne!

**Comment by briannesbitt** [comment]
Merged.

**Comment by judgej** [comment]
Just FYI, I'm using Carbon with Moment.JS When I add a month in Moment.JS, and the day would be beyond the end of the next month, then it will move the date to the end of that month. So 2015-01-31->addMonth(1) gives 2015-02-28. Adding another month takes you to 2015-03-28, so if you need to work back up to the day number you started with, then you have to account for that. What adding a single month does *not* do, is unintuitively take you forward *two* calende months, but missing a whole month out.

**Comment by lucasmichot** [comment]
See #710
