### ISSUE TITLE
Problem with week numbers ???

### ISSUE THREAD

**Issue by pibit-dev** [briannesbitt/Carbon#2363]
Hello,

I encountered an issue with the following code:
```php
echo Carbon::parse('2020-12-28')->week(null,1,1);
```

Carbon version: 2.42.0
PHP version: 7.4.13

I expected to get:

```
53
```

But I actually get:

```
1
```

Why in some years (e.g. 2000, 2012) is there week with number 53 but in others (eg. 2020, 2021) after week 52 (in December) is week 1?

**Comment by kylekatarnls** [comment]
Hello,

It depends the minimum number you ask to consider the week is the last of 2020 or the first of 2021 (couple `$dayOfWeek` `$dayOfYear`).

For instance the ISO-8601 norm (https://en.wikipedia.org/wiki/ISO_8601#Week_dates) tells if there is >= 4 days (more than the half) in 2020 it's the 53th of 2020, if there is less, it's the first of 2021. And the norm consider the first day of a week is Monday. So to follow this norm, you should then set `$dayOfYear = 4` and `$dayOfWeek = 1` (Monday):

```php
echo Carbon::parse('2020-12-28')->week(null, 1, 4); // 53
// Or the shortcut:
echo Carbon::parse('2020-12-28')->isoWeek(); // 53
// Equivalent to W format of DateTime::format:
echo (new DateTime('2020-12-28'))->format('W'); // 53
```

But with your current setting (`$dayOfYear = 1` ), 1 day is enough to consider the week is already the first one of 2021.

Last if you don't precise the settings, you'll get the default as per the current locale (en by default).
