### ISSUE TITLE
Precision bug when converting float with leading zero in decimal part to Carbon instance

### ISSUE THREAD

**Issue by pichanz** [briannesbitt/Carbon#2368]
Hello,

I encountered an issue with the following code:
```php
$micro = 1624881411.0603;
$fromMicro = Carbon::createFromTimestamp($micro);
dump(
    [
        $micro,
        $fromMicro->format('Y-m-d H:i:s.u'),
        floatval($fromMicro->format('U.u'))
    ]
);
```

Carbon version: 2.49.0

PHP version: 8.0.7

I expected to get:

```
array:3 [
  0 => 1624881411.0603
  1 => "2021-06-28 11:56:51.060300"
  2 => 1624881411.0603
]
```

But I actually get:

```
array:3 [
  0 => 1624881411.0603
  1 => "2021-06-28 11:56:51.603000"
  2 => 1624881411.603
]
```

Thanks!

**Comment by kylekatarnls** [comment]
Hello, `dump` is neither a PHP function not a Carbon one, please provide code that does not involve any third-party. In this case, this is very likely just how your `dump()` function (from your framework or other library) round float values to display them.

You can see that there is any precision loss using `var_dump()`
```php
$micro = 1624881411.0603;
$fromMicro = Carbon::createFromTimestamp($micro);

var_dump([
    $micro,
    $fromMicro->format('Y-m-d H:i:s.u'),
    floatval($fromMicro->format('U.u'))
]);
```
[Result](https://try-carbon.herokuapp.com/?embed&theme=xcode&border=silver&options-color=rgba(120,120,120,0.5)&input=%24micro%20%3D%201624881411.0603%3B%0D%0A%24fromMicro%20%3D%20Carbon%3A%3AcreateFromTimestamp(%24micro)%3B%0D%0A%0D%0Avar_dump(%5B%0D%0A%20%20%20%20%24micro%2C%0D%0A%20%20%20%20%24fromMicro-%3Eformat(%27Y-m-d%20H%3Ai%3As.u%27)%2C%0D%0A%20%20%20%20floatval(%24fromMicro-%3Eformat(%27U.u%27))%0D%0A%5D)%3B%0D%0A)

Then, `format('U.u')` just returns a string (which contains the full precision) so you will get the exact same result if you do `floatval('1624881411.0603')`
https://3v4l.org/09HJl

So there is actually no relation with the `Carbon` (or even `DateTime` instance), any loss you get happen after `Carbon::format` so there is nothing `Carbon` can do about that.

Thanks.

**Comment by pichanz** [comment]
Hello @kylekatarnls
Thanks for the reply.

I think i should've explained it more in the description.

The loss of precision is because of the leading zero in the decimals.
The decimals in the value `1624881411.0603` is `0603` which is loss because the conversion in `\Carbon\Traits\Timestamp::getIntegerAndDecimalParts()` returns array of integer (will return 603 in the decimal part)

So the resulting time from that timestamp should be `2021-06-28 11:56:51.060300` instead of `2021-06-28 11:56:51.603000`

```php
$micro = 1624881411.0603;
$standardDateTime = \DateTime::createFromFormat('U.u', number_format($micro, 4,'.', ''));
$standardDateTime->format('Y-m-d H:i:s.u');
$fromMicroCarbon = Carbon::createFromTimestamp($micro);

var_dump(
    [
        $standardDateTime->format('Y-m-d H:i:s.u'),
        $fromMicroCarbon->format('Y-m-d H:i:s.u'),
    ]
);
```

Result
```
array(2) {
  [0] =>
  string(26) "2021-06-28 11:56:51.060300"
  [1] =>
  string(26) "2021-06-28 11:56:51.603000"
}
```

or maybe i'm doing it wrong when trying to parse that value with carbon?

**Comment by kylekatarnls** [comment]
Sorry. Indeed, that's a bug `Carbon::createFromTimestamp('0.01')->format('u')` should return `010000` instead of `100000`
