### ISSUE TITLE
Disabling month overflow is providing incorrect output if "months" is provided as unit instead of "month"

### ISSUE THREAD

**Issue by al2k4** [briannesbitt/Carbon#2395]
Hello,

I encountered an issue with the following code:
```php
$dt = \Carbon\CarbonImmutable::parse("2021-01-31");

echo $dt->add(1, "months", false)->format("Y-m-d");
echo "\n";
```

Carbon version: 2.50.0

PHP version: 7.4.13

I expected to get:

```
2021-02-28
```

But I actually get:

```
2021-03-03
```

Thanks!

**Comment by kylekatarnls** [comment]
Hello 👋 

`$overflow` param will apply strictly when using the singular normalized unit:
```php
$dt = \Carbon\CarbonImmutable::parse("2021-01-31");

echo $dt->add(1, "month", false)->format("Y-m-d");
```

Any other string, composite interval (such as "1 month 15 days"), `DateInterval` or other parameters will ignore `$overflow` as they rely to native methods `DateTime::add` or `DateTime::modify`.

I'm not sure we can allow plural unit there without side effect, but I will check.

**Comment by al2k4** [comment]
Hi 👋, I think the fix is to ensure that the `$units` variable that's passed into `Units::addUnit()` is singular if it happens to equal `months` or `years`, these are the only two strings that would trigger this edge case.

```php
if($unit === "months") $unit = "month";
if($unit === "years") $unit = "year";
```

It will not cause any side effects from what I can tell. 🤔

**Comment by kylekatarnls** [comment]
Thanks for your report, plural units will be allowed and will behave the same in the next version 2.52.0.
