### ISSUE TITLE
Warning: Cannot bind an instance to a static closure

### ISSUE THREAD

**Issue by cgunnels** [briannesbitt/Carbon#2396]
Hello,

I encountered an issue with the following code:
```php
Carbon::now(config('settings.timezone'))->nextBusinessDay();
```

Carbon version: **2.50.0**

PHP version: **7.4.1**

I expected to get:

```
I received what was expected except for the warning.
```

But I actually get:

![Screen Shot 2021-07-26 at 10 06 02 AM](https://user-images.githubusercontent.com/63998/127022149-0c5720f7-2d14-4318-8255-7e16a02a2502.png)

Thanks!

**Comment by kylekatarnls** [comment]
Hello, I can't reproduce using a fresh install of Laravel, installing `cmixin/business-time` and calling your code. Can you provide steps to reproduce this error from scratch?

**Comment by kylekatarnls** [comment]
Can you check if you have custom error_handler and if it's respect error muted using `@`?
