### ISSUE TITLE
Support for Non-Gregorian Calendars

### ISSUE THREAD

**Issue by bigsinoos** [briannesbitt/Carbon#240]
Hi thanks for great work, 
There are non-Gregorian calendars (like Jalali) that it is very cool to have features like what Carbon offers. Is it a good Idea for us to fork the Repository do some works to add the support for Non-Gregorian Calendars , Or we should Create a new pakcage and extend the current Carbon ? just want to know your opinion, thanks.

**Comment by briannesbitt** [comment]
New package and extend Carbon?  You would just use composer to require Carbon.
