### ISSUE TITLE
Adding extension.neon to .gitattributes breaks other tools

### ISSUE THREAD

**Issue by gubler** [briannesbitt/Carbon#2400]
Hello,

I encountered an issue with the following code:
```php
phpstan analyze
```

Carbon version: 2.51.0

PHP version: 8.0.6

I expected to get:

PHPStan results

But I actually get:

Config file /var/www/symfony/vendor/nesbot/carbon/extension.neon does not exist or isn't readable
make: *** [phpstan] Error 1

---

I see that in 2.51.0, `extension.neon` was added to `.gitattributes`, so that it is no longer available after a `composer update`. I don't know if the missing `extension.neon` breaks other tools, but it definitely breaks PHPStan.

I originally reported this as a bug to PHPStan and they said this was something that needed to be changed in this project.

Thanks for a great tool!

**Comment by kylekatarnls** [comment]
Thank you, you can update to 2.51.1 now to fix it.

**Comment by gubler** [comment]
Thank you very much for the quick fix :)
