### ISSUE TITLE
Replace `M` with `MM` instead of `MMM` in translatedFormat

### ISSUE THREAD

**Issue by spaanse** [briannesbitt/Carbon#2411]
Hello,

I encountered an issue with the following code:
```php
echo Carbon::now()->locale('nl')->translatedFormat('M');
```

Carbon version: **2.51.1**

PHP version: **7.4**

I expected to get:

```
aug
```

But I actually get:

```
aug.
```

Thanks!

**Comment by kylekatarnls** [comment]
Hello 👋 

`MM` would give you `08` so it's clearly not a solution to get what you expect here.

Also, the presence of `.` will depends on the grammar rule for each language. You can easily customize it if you don't want to apply the rule:

```php
\Carbon\Translator::get('nl')->setTranslations([
    'mmm_suffix' => '',
]);
echo Carbon::now()->locale('nl')->translatedFormat('M') . "\n";
```

Would it fit?
