### ISSUE TITLE
Invalid difference in months

### ISSUE THREAD

**Issue by dmitriyl99** [briannesbitt/Carbon#2415]
Hello,

I encountered an issue with the following code:
```php
$currentDate = Carbon::parse('2020-09');
$nextDate = Carbon::parse('2020-10');
echo $nextDate->diffInMonths($currentDate);
```
I expected to get:

```
1
```
But I actually get:

```
0
```
Difference in days is 30
But if we take another months: 
```php
$currentDate = Carbon::parse('2020-10');
$nextDate = Carbon::parse('2020-11');
echo $nextDate->diffInMonths($currentDate);
```
The result will be 1.
Difference in days is 31.
I can't understand how works diffInMonth() method, but if I count between 30 and 31 the difference in months will be 0 and if I count between 31 and 30 the difference in months will be 1. Why?
I tried on my local machine, test and production servers, result is the same. But in try-carbon.herokuapp.com all works correctly.

Carbon version: 2.48.0

PHP version: 8.0.8

My timezone: Asia/Tashkent

Thanks!

**Comment by kylekatarnls** [comment]
It's because `Tashkent` as a DST change (switching from summer to winter time) which make this month incomplete (miss 1 hour).

So you can:

```php
$currentDate = Carbon::parse('2020-10 UTC');
$nextDate = Carbon::parse('2020-11 UTC');
echo $nextDate->diffInMonths($currentDate);
```

Or:

```php
$currentDate = Carbon::parse('2020-10');
$nextDate = Carbon::parse('2020-11')->addHour();
echo $nextDate->diffInMonths($currentDate);
```

Recommendation is to always use UTC back-end side and only deal with user timezone at input/output.
