### ISSUE TITLE
Why don't factories convert dates to the correct timezone when formatting

### ISSUE THREAD

**Issue by grantholle** [briannesbitt/Carbon#2416]
Hello,

I tried searching to see if this question has come up before, and for some reason it hasn't.

I'm having trouble understanding why factories don't automatically convert the date and time to the factory's timezone when parsing/making from the factory.

```php
$factory = new \Carbon\Factory([
    'locale' => 'zh_CN',
    'timezone' => 'Asia/Shanghai',
]);

$baseDate = \Carbon\Carbon::parse('2021-08-01 08:00:00', 'UTC');

echo $baseDate->format('c') . "\n";
// 2021-08-01T08:00:00+00:00

$date = $factory->make($baseDate);
echo $date->format('c');
// 2021-08-01T08:00:00+08:00
```

Carbon version: 2.51.1

PHP version: 8.0.8

I expected to get:

```php
$date = $factory->make($baseDate);
echo $date->format('c');
// 2021-08-01T16:00:00+08:00
```

But I actually get:

```php
$date = $factory->make($baseDate);
echo $date->format('c');
// 2021-08-01T08:00:00+08:00
```

I don't understand the reasoning of giving the factory a timezone if it just displays the same date and time, but a different timezone. When I give a factory a date in UTC and give it to a factory, I expect it to convert that date to its configured timezone.

Take the [documentation example](https://try-carbon-package.herokuapp.com/?hide-output-gutter&output-left-padding=10&theme=tomorrow_night&border=none&radius=4&v-padding=15&input=%2F%2F%20Let%20say%20Martin%20from%20Paris%20and%20John%20from%20Chicago%20play%20chess%0A%24martinDateFactory%20%3D%20new%20Factory(%5B%0A%20%20%20%20%27locale%27%20%3D%3E%20%27fr_FR%27%2C%0A%20%20%20%20%27timezone%27%20%3D%3E%20%27Europe%2FParis%27%2C%0A%5D)%3B%0A%24johnDateFactory%20%3D%20new%20Factory(%5B%0A%20%20%20%20%27locale%27%20%3D%3E%20%27en_US%27%2C%0A%20%20%20%20%27timezone%27%20%3D%3E%20%27America%2FChicago%27%2C%0A%5D)%3B%0A%2F%2F%20Each%20one%20will%20see%20date%20in%20his%20own%20language%20and%20timezone%0A%0A%2F%2F%20When%20Martin%20moves%2C%20we%20display%20things%20in%20French%2C%20but%20we%20notify%20John%20in%20English%3A%0A%24gameStart%20%3D%20Carbon%3A%3Aparse(%272018-06-15%2012%3A34%3A00%27%2C%20%27UTC%27)%3B%0A%24move%20%3D%20Carbon%3A%3Anow(%27UTC%27)%3B%0A%24toDisplay%20%3D%20%24martinDateFactory-%3Emake(%24gameStart)-%3EisoFormat(%27lll%27).%22%5Cn%22.%0A%20%20%20%20%24martinDateFactory-%3Emake(%24move)-%3Ecalendar().%22%5Cn%22%3B%0A%24notificationForJohn%20%3D%20%24johnDateFactory-%3Emake(%24gameStart)-%3EisoFormat(%27lll%27).%22%5Cn%22.%0A%20%20%20%20%24johnDateFactory-%3Emake(%24move)-%3Ecalendar().%22%5Cn%22%3B%0Aecho%20%24toDisplay%3B%0A%2F*%0A15%20juin%202018%2012%3A34%0AAujourd%E2%80%99hui%20%C3%A0%2008%3A55%0A*%2F%0A%0Aecho%20%24notificationForJohn%3B%0A%2F*%0AJun%2015%2C%202018%2012%3A34%20PM%0AToday%20at%208%3A55%20AM%0A*%2F%0A&token=live-editor-129) for instance.

An event happened in time, `Carbon::parse('2018-06-15 12:34:00', 'UTC')`, and we want to display that event for different locales, which factories definitely solve. But it tells them (in the their own locale 👍 ) that the event happened at the exact same time (2018-06-15 12:34) in their own timezone, which isn't true at all. Martin sees the move happening at 12:34 in Paris, and John also sees it happening at 12:34 in Chicago, which doesn't make sense to me. Wouldn't it make sense to show the date in their locale _and_ relative to their timezone?

Thanks!

**Comment by kylekatarnls** [comment]
Hum I see where it broke. It's quite old:
https://github.com/briannesbitt/Carbon/commit/99976db35020b1b3aa6be6cf81d44bf3d13775e3#diff-4cb6bb84421fc609ad881f42ea5f250ad8f9e03c1c5b654f50929d8739c0d763R301

And we can't easily fix it because you can also use `make()` like this:
```php
$date = $factory->make('2021-08-01 16:00:00');
echo $date->format('c');
```

So it has to behave differently depending on the input data had a timezone information or not.

**Comment by grantholle** [comment]
Thanks for workaround @kylekatarnls. 

Since I couldn't find anyone who has brought this up, I wanted to validate that my expected behavior is what others expect as well. What a wonderful world timezones are! 🤪

**Comment by kylekatarnls** [comment]
It will be fixed for the next version, you can see various factory usages in tests and the output it will produce once 2.52.2 will be released:

https://github.com/briannesbitt/Carbon/pull/2418/files#diff-2adca31832a76f38aef5997d5d141c612c5f5261967210e8b57bfb37cf4fcb3d

**Comment by grantholle** [comment]
@kylekatarnls you are the bomb 💣 ! Thank you so much
