### ISSUE TITLE
isBirthday() call format() twice.

### ISSUE THREAD

**Issue by kylekatarnls** [briannesbitt/Carbon#242]
isBirthday() call format() twice. It could be simplified with:
<pre>$this->format('m-d') === $dt->format('m-d');</pre>
It have been mentionned in [the issue comment](https://github.com/briannesbitt/Carbon/commit/644dd15e5027b948697b6538c84cfe9f2d785415) and also proposed by @lucasmichot in https://github.com/lucasmichot/Carbon/commit/9eaa898b2bad616766a3d7120f0efe1bb6635299

**Comment by dereuromark** [comment]
Why not making a PR with it?

**Comment by kylekatarnls** [comment]
In all the project I participated in. A PR had to refer an issue.

**Comment by lucasmichot** [comment]
Why opening another PR ?

**Comment by kylekatarnls** [comment]
Oh sorry I searched with "isBirthday" and so missed yours.
