### ISSUE TITLE
Formatting diffAsCarbonInterval as %a returns "unknown" while diff returns the number of days

### ISSUE THREAD

**Issue by bilfeldt** [briannesbitt/Carbon#2423]
Hello,

I encountered an issue with the following code:
```php
\Carbon\Carbon::make('2021-08-30 00:00:00')
    ->diffAsCarbonInterval(\Carbon\Carbon::make('2021-09-02 12:48:32'))
    ->format('%a'); // Output: "(unknown)"
```

Carbon version: * 2.51.1

PHP version: 7.4.19

I expected to get:

```
"3"
```

But I actually get:

```
"unknown"
```

Note that using `diff` instead of `diffAsCarbonInterval` yields the expected results:

```php
\Carbon\Carbon::make('2021-08-30 00:00:00')
    ->diff(\Carbon\Carbon::make('2021-09-02 12:48:32')) // Using 'diff' instead of 'diffAsCarbonInterval'
    ->format('%a'); // output: "3"
```

Am I missing something here or is this a bug? 🤔

**Comment by kylekatarnls** [comment]
Hello,

`%a` is special as you can only have it from the result of a native diff, so a `DateInterval` but once you re-create a new interval in any other sub-class of `DateInterval` you can't assign this totalDays property.

Other than the work-around you found, you also can:
```php
echo \Carbon\Carbon::make('2021-08-30 00:00:00')
    ->diffInDays(\Carbon\Carbon::make('2021-09-02 12:48:32'));
```
Or
```php
echo (int) \Carbon\Carbon::make('2021-08-30 00:00:00')
    ->diffAsCarbonInterval(\Carbon\Carbon::make('2021-09-02 12:48:32'))
    ->totalDays;
```
I would recommend the first one as it's shorter and way more explicit than "format %a".

Possibly this limit will disappear in a future version of PHP, and I'm open to pull-requests to improve this but it would require that the `CarbonInterval` instance we get would pass all the tests that we have also when it's from a diff and pass in all the PHP versions we support (>= 7.1.8 for 2.x, >= 8.0 for 3.x).

Meanwhile I will close this issue as we don't lack of alternatives.

Thanks.

**Comment by bilfeldt** [comment]
@kylekatarnls Thanks for the detailed explanation - and for the super fast reply.

> once you re-create a new interval in any other sub-class of DateInterval you can't assign this totalDays property.

This does indeed seem to be somewhat of a showstopper 🤔 

I could not find a propper repo for submitting a change to the documentation about this, but maybe it would be worth mentioning in the [CarbonInterval section](https://carbon.nesbot.com/docs/#api-interval) that this is a limitation of `CarbonInterval` compared to the parent DateInterval class?
