### ISSUE TITLE
Date::formatLocalized vs PHP 8.1

### ISSUE THREAD

**Issue by drbyte** [briannesbitt/Carbon#2425]
PHP 8.1 deprecates `strftime()` per https://wiki.php.net/rfc/deprecations_php_8_1#strftime_and_gmstrftime

This affects all formats beginning with `%`, which triggers `Date::formatLocalized()`, which calls `strftime()`:

https://github.com/briannesbitt/Carbon/blob/369c0e2737c56a0f39c946dd261855255a6fccbe/src/Carbon/Traits/Date.php#L893

https://github.com/briannesbitt/Carbon/blob/369c0e2737c56a0f39c946dd261855255a6fccbe/src/Carbon/Traits/Date.php#L1819-L1829

**Comment by kylekatarnls** [comment]
Hello,

For the same reason than `strftime()` should not be used (it is platform-dependent) then you should not use `formatLocalizzed()` and `isoFormat()` exists for that purpose:
https://carbon.nesbot.com/docs/#api-localization

Carbon embed all the translations you need.

From our side it's the preferred way for a long time and `formatLocalized()` is just legacy. `formatLocalized()` is purely mirroring `strftime` using the current Carbon instance date-time. Consider it deprecated in PHP 8.1 too.

About the getters, use the `isoFormat` instead too:
`->localeDayOfWeek` => `->isoFormat('dddd')`
`->shortLocaleDayOfWeek` => `->isoFormat('ddd')`
`->localeMonth` => `->isoFormat('MMMM')`
`->shortLocaleMonth` => `->isoFormat('MMM')`

I think, we'll change those getters to use `isoFormat()` but `formatLocalized()` itself does not worth to be fixed.

**Comment by drbyte** [comment]
Thanks for the feedback.
I'll leave this issue open; feel free to close it when you've decided how you intend to address the points you mentioned.

**Comment by Stanislas-Poisson** [comment]
Thanks. It save my day

**Comment by rulatir** [comment]
Where can I find a 100% exhaustive, Rosetta-stone guide for migrating from `formatLocalized()` format strings to `isoFormat()` format strings?

**Comment by kylekatarnls** [comment]
Formats in `formatLocalized` are the ones of `strftime` as documented in PHPDoc:
https://www.php.net/manual/en/function.strftime

Formats in `isoFormat()` are listed in the 2 tables here:
https://carbon.nesbot.com/docs/#iso-format-available-replacements

They are not 1:1 equivalent so the mapping between both depends on your business logic.

**Comment by kylekatarnls** [comment]
Just a note to say this concern is not really on Carbon shoulders.

`strftime()` has been deprecated by PHP team for good reasons and `isoFormat()` uses a common standard used with ISO 8601. Carbon did not actually decided neither what each of the old and the new output for which code but only followed wider specs.
