### ISSUE TITLE
Odd results when setting month

### ISSUE THREAD

**Issue by beard7** [briannesbitt/Carbon#2438]
Hello,

I encountered an issue with the following code:
```php
echo Carbon::now()->year(2021)->month(4)->day(3)->startOfDay();
echo Carbon::now()->year(2021)->month(3)->day(3)->startOfDay();
```

Carbon version: 2.50.0

PHP version: 7.4.1

I expected to get:

```
2021-04-03 00:00:00
2021-03-03 00:00:00
```

But I actually get:

```
2021-05-03 00:00:00
2021-03-03 00:00:00
```

Can somebody please explain the inconsistency in setting the month? For some reason I always get a date in May when trying to get April.

Thanks!

**Comment by kylekatarnls** [comment]
Hello,

As explained in many other issues, when you start from a date on 31st and switch to a month with less than 31 days, you get an overflow by default (this is the native behavior of PHP for `DateTime` and it's actually pretty much the same in all other languages: JavaScript, Java, etc.)

In your case, this makes no sense to start from `now()`:
```php
echo Carbon::parse('2021-04-03');
```
Already gives you the start of the day for the date you want, and unlike the chaining style you use there, it will be way faster as it does not do 4 mutations after the date creation, it's just create the correct date immediately.

And the same can be easily done with variables:
```php
$year = 2021;
$month = 4;
$day = 3;
echo Carbon::parse("$year-$month-$day");
echo "\n OR \n";
echo Carbon::createMidnightDate($year, $month, $day);
```

Thanks.

**Comment by beard7** [comment]
I'm actually using `Carbon::create($year, $month, $day, 0, 0, 0);` but was just curious.

I guess this is the first time I'd ever looked on the 31st of a month.

Thanks for the info -- makes sense.
