### ISSUE TITLE
diffAsCarbonInterval and totalDays gives improper result

### ISSUE THREAD

**Issue by rela589n** [briannesbitt/Carbon#2444]
Hello,

I encountered an issue with the following code:
```php
var_dump((new CarbonImmutable('2020-05-12'))
            ->diffInDays(new CarbonImmutable('2021-09-07'))); // 483

var_dump((new CarbonImmutable('2020-05-12'))
            ->diffAsCarbonInterval(new CarbonImmutable('2021-09-07'))->totalDays); // 446
```

Carbon version: 2.51.1

PHP version: 8.0.9

In second case I expected to get:

```
483
```

But I actually get:

```
446
```

Thanks!

**Comment by kylekatarnls** [comment]
Hello,

It will changed in 3.0, you can try with `3.x-dev` and see you'll get 483.

But in 2.x, when you create an interval, it keeps no memory of the dates you used to create it (and it won't change in this version as we don't want breaking change here) and simply use integer factors (1 year => 12 month, 1 month => 4 weeks, 1 week => 7 days) as per documentation: https://carbon.nesbot.com/docs/#api-interval

Thanks.
