### ISSUE TITLE
⭐ Carbon::diffForHuman(): skip weeks

### ISSUE THREAD

**Issue by rentalhost** [briannesbitt/Carbon#2465]
Hello,

**Carbon version:** 2.47.0
**PHP version:** 8.0.10

I would like a way to avoid weeks in `Carbon::diffForHumans()`. For example, if there is **more than 1 week** and **less than 1 month**, the following will happen:

```php
Carbon::setLocale('en');

$carbonFrom = new Carbon('2021-09-01 08:00:00');
$carbonTo   = new Carbon('2021-09-30 12:00:00');

$carbonTo->diffForHumans($carbonFrom, [
    'parts'       => 2,
    'join'        => true,
    'syntax'      => CarbonInterface::DIFF_RELATIVE_TO_NOW,
    'minimumUnit' => 'hour',
]); // Output: 4 weeks and 1 day from now
```

But I really prefer something more clear, avoiding weeks. 

So my suggestion is added one more option to syntax to avoid weeks:

```php
$carbonTo->diffForHumans($carbonFrom, [
    'parts'       => 2,
    'join'        => true,
    'syntax'      => CarbonInterface::DIFF_RELATIVE_TO_NOW | CarbonInterface::AVOID_WEEKS,
    'minimumUnit' => 'hour',
]); // Output: 29 days and 4 hours from now
```

Thanks!

**Comment by kylekatarnls** [comment]
Hello,

I see no particular reason for a constant limited only to "weeks", the wish to have month and days but not weeks looks like a business/user preference, from our agnostic library point of view, week is just a time unit like any other one, so I would prefer to implement a feature like this:

```php
$carbonTo->diffForHumans($carbonFrom, [
    'parts'       => 2,
    'join'        => true,
    'syntax'      => CarbonInterface::DIFF_RELATIVE_TO_NOW,
    'skipUnits'   => ['week'],
    'minimumUnit' => 'hour',
]);
```
So each developer is free to decide what unit is relevant for her/his case..

If this can be implemented with no regression on existing behavior, then merge requests for this are welcome.

Thanks for the suggestion

**Comment by rentalhost** [comment]
@kylekatarnls I agree with you totally. When I said about "weeks", I figured it was the only unusual unit to works. But really, if can make this even more flexible, maybe can help it for more for another user cases.

**Comment by kylekatarnls** [comment]
The option `'skip'` is ready in master branch (you can test it with `composer require nesbot/carbon:dev-master`).

It can be simply `'skip' => 'week'` or a list of units `'skip' => ['week', 'day']`

**Comment by mbunal** [comment]
hi, i tried with dev-master. but it didint worked skip option. what can be wrong?
`Carbon::createFromTimestampMs($timestampsMS)->diffForHumans(Carbon::now(),['skip' => 'week', 'parts' => 4])`

**Comment by kylekatarnls** [comment]
Sorry, composer is not properly auto-updated, I just manually update dev-master to the last commit so you can test it.

**Comment by mbunal** [comment]
perfect. thank you very much...
