### ISSUE TITLE
`Carbon::setTestNow()` sets a date for `Carbon` class, but not `CarbonImmutable`

### ISSUE THREAD

**Issue by wijourdil** [briannesbitt/Carbon#2473]
Hello,

I encountered an issue with the following code:
```php
Carbon::setTestNow('2021-01-01 00:00');

Carbon::now(); // => 2021-01-01 00:00:00
CarbonImmutable::now(); // => 2021-10-11 13:34:44
```

Carbon version: 2.53.1

PHP version: 8.0.9

Exported demo in heroku :
https://try-carbon.herokuapp.com/?embed&theme=xcode&border=silver&options-color=rgba(120,120,120,0.5)&input=Carbon%3A%3AsetTestNow(%222021-01-01%2000%3A00%22)%3B%0A%0Aprint_r(%5B%0A%20%20Carbon%3A%3Anow()%2C%0A%20%20CarbonImmutable%3A%3Anow()%2C%0A%5D)%3B

When I set a date with `Carbon::setTestNow()`, it is ignored when my code uses the `CarbonImmutable::now()` method, I have to set it twice with : 
```php
Carbon::setTestNow(...);
CarbonImmutable::setTestNow(...);
```

Is it possible to have a way to initialize a test date for both `Carbon` and `CarbonImmutable` classes ? 

Thanks!

**Comment by wijourdil** [comment]
If this can help somebody, I have discovered that in Laravel you also can use the method `Illuminate\Support\Carbon::setTestNow()`
This method sets the date for both `Carbon\Carbon` and `Carbon\CarbonImmutable` classes.

See :
https://github.com/laravel/framework/blob/8.x/src/Illuminate/Support/Carbon.php

**Comment by kylekatarnls** [comment]
This behavior changed with the version 8.26.0 and this is not a great idea IMO.
