### ISSUE TITLE
Modifying the instance when modifying it in a method. Like passing by reference.

### ISSUE THREAD

**Issue by aginev** [briannesbitt/Carbon#248]
```
function modifyCarbon(\Carbon $obj) {
	$obj->setTimezone('Europe/Sofia');

	return $obj;
}

$time = new \Carbon('now');
echo 'Just before the function call: ' . $time . '<br/>';

$time_local = modifyCarbon($time);
echo 'Just after the function call: ' . $time . '<br/>';
echo 'Function call result: ' . $time_local . '<br/>';
```

Output:
Just before the function call: 2015-01-28 14:42:35
Just after the function call: 2015-01-28 16:42:35
Function call result: 2015-01-28 16:42:35

**Comment by Anahkiasen** [comment]
You need to do `$time_local = copy $time;`

**Comment by aginev** [comment]
Yep but it does not work as expected you are not passing the variable by reference.

**Comment by dereuromark** [comment]
Objects in PHP(5+) are always passed by reference - compared to simple variables.

**Comment by aginev** [comment]
You are right! Better to learn something later than never...
