### ISSUE TITLE
2.54.0 not reached packagist

### ISSUE THREAD

**Issue by leewillis77** [briannesbitt/Carbon#2485]
Hello,

Carbon version 2.54.0 was released here yesterday, but it looks like it's been done in a way that means that Packagist doesn't pick it up - since that seems stuck on 2.53.1:
https://packagist.org/packages/nesbot/carbon

Thanks!

**Comment by kylekatarnls** [comment]
Thank you for the report, it's about auto-update packagist token expiration. 🙏

**Comment by leewillis77** [comment]
Great. Thanks!
