### ISSUE TITLE
Carbon::parse('february') returns March 2

### ISSUE THREAD

**Issue by justinmacleod** [briannesbitt/Carbon#249]
I just discovered today that ```Carbon::parse('february')``` returns a date object for March 2, 2015:

```
object(Carbon\Carbon)#253 (3) {
  ["date"]=>
  string(26) "2015-03-02 00:00:00.000000"
  ["timezone_type"]=>
  int(3)
  ["timezone"]=>
  string(3) "UTC"
}
```

I am unsure exactly why but perhaps it is related to the fact that this February has exactly 4 weeks. That doesn't happen again until 2026. The assumption is that it should return the first day of the month I believe. By forcing a 1 after February it does return the proper date.

**Comment by briannesbitt** [comment]
What is happening is that the date is being populated with that day's date.

Ex.  If I run that same thing right now (Feb 5, 2015) I unsurprisingly get
```php
object(Carbon\Carbon)#2 (3) {
  ["date"]=>
  string(26) "2015-02-05 00:00:00.000000"
  ["timezone_type"]=>
  int(3)
  ["timezone"]=>
  string(15) "America/Toronto"
}
```

However if I ran it say (when you ran it) on Jan 30, 2015 it would try and create a date of Feb 30, 2014 which would then jump forward to March 2, 2015 as you show above.

**Comment by Hammaadh** [comment]
Carbon::parse('february-01')
