### ISSUE TITLE
Rounding off milliseconds

### ISSUE THREAD

**Issue by winvelod** [briannesbitt/Carbon#2499]
Hello,

I encountered an issue with the following code:
```php
echo (new Carbon(1635724800.001))->getPreciseTimestamp(3) / 1000;
```

Carbon version: **2.48.0**

PHP version: **8.0.3**

I expected to get:

```
1635724800.001
```

But I actually get:

```
1635724800.1
```

Thanks!

**Comment by kylekatarnls** [comment]
Hello, 👋 

This has been fixed at the version **2.50.0** please upgrade to the last version.

Thanks. 🙏
