### ISSUE TITLE
[Translation tool] nds

### ISSUE THREAD

**Issue by Slomox** [briannesbitt/Carbon#2505]
|English|nds|comments|
|--|--|--|
|2yrs|2 Johr|2J|
|a year|1 Johr|een Johr|
|2mos|2 Maand|2M|
|a month|1 Maand|een Maand|
|2 weeks|2 Week|2 Weken|
|2w|2 Week|2W|
|a week|1 Week|een Week|
|2 days|2 Dag|2 Daag|
|2d|2 Dag|2D|
|a day|1 Dag|een Dag|
|2 hours|2 Stünn|2 Stünnen|
|2h|2 Stünn|2St|
|an hour|1 Stünn|een Stünn|
|2 minutes|2 Minuut|2 Minuten|
|2m|2 Minuut|2m|
|a minute|1 Minuut|een Minuut|
|2 seconds|2 sekunn|2 Sekunnen|
|2s|2 sekunn|2s|
|1 second|1 sekunn|1 Sekunn|
|a few seconds|1 sekunn|en poor Sekunnen|
|Mo|Maan|Ma|
|Tu|Ding|Di|
|Wed|Migg|Midd|
|We|Migg|Mi|
|Th|Dunn|Du|
|Fr|Free|Fr|
|Sa|Svd.|Sa|
|Su|Sdag|Sd|
|2 hours ago|2 Stünn ago|vör 2 Stünnen|
|2 hours from now|2 Stünn from now|in 2 Stünnen|
|2 hours before|2 Stünn before|2 Stünnen vörher|
|2 hours after|2 Stünn after|2 Stünnen later|

**Comment by kylekatarnls** [comment]
Thanks for your help, this will be fixed in the next release. 🙏
