### ISSUE TITLE
Macro support for PHPStan ^1.0.0

### ISSUE THREAD

**Issue by gregtyler** [briannesbitt/Carbon#2507]
Hello,

I believe that Carbon's PHPStan Macro is incompatible with PHPStan ^1.0.0.

Carbon version: **2.54.0**

PHP version: **8.0.12**

When running PHPStan with Carbon's Macro (i.e. `phpstan analyze` with the extension referenced in `phpstan.neon`) I expected to get no errors.

But I actually get the error:

> Fatal error: Declaration of Carbon\PHPStan\Macro::getFileName() must be compatible with PHPStan\Reflection\Php\BuiltinMethodReflection::getFileName(): ?string in /{path redacted}/vendor/nesbot/carbon/src/Carbon/PHPStan/Macro.php on line 152

This is because PHPStan's [BuiltinMethodReflection](https://github.com/phpstan/phpstan-src/blob/79e0a792a14a088af37e386fa93746d7e8b6c687/src/Reflection/Php/BuiltinMethodReflection.php) class (which the Carbon macro extends) has changed as of version 1.0.0.

Specifically:
- `getFileName` now returns `?string` (not `string|false`)
- `getStartLine` and `getEndLine` now return `?int` (not `int|false`)
- There is a new `getTentativeReturnType` abstract method which must be implemented

I don't _think_ it's possible to support both the old typehinting and the new, so I suspect this might require Carbon ^3.0.0 to specifically and uniquely support PHPStan ^1.0.0.

I'm also not clear on what `getTentativeReturnType` should actually return.

Thanks! And apologies that I don't have any advise for fixing it 😞

**Comment by kylekatarnls** [comment]
Hello,

We will do surface proxy classes as done for Symfony 6 support, so checking the type by reflection then require a different class accordingly.

**Comment by kylekatarnls** [comment]
Hello, can you try to require `nesbot/carbon:2@dev`?

**Comment by gregtyler** [comment]
Thanks @kylekatarnls I used `nesbot/carbon:2.x-dev` and that's worked great. Really appreciate the fast turnaround :)
