### ISSUE TITLE
Laravel 5 project on Forge

### ISSUE THREAD

**Issue by raffw7912** [briannesbitt/Carbon#252]
Hopefully I'm not mad and I'm only missing something. I have a project on Laravel 5.0 and a requestExpired function called every time I get an incoming request. Now, to calculate the difference between current time on the server and the timestamp within the request I'm using:

```
$now = Carbon::now('UTC');
$postedTime = Carbon::createFromTimestamp($timestamp, 'UTC');
```

For some reason request is always rejected because it's expired. When I debug these two lines from above and just dump data, I get:

    REQUEST'S TIMESTAMP IS: 1423830908279  

    $NOW OBJECT: Carbon\Carbon Object  
    (  
    [date] => 2015-02-13 12:35:08.000000  
    [timezone_type] => 3  
    [timezone] => UTC  
    )  
    
    $POSTEDTIME OBJECT: Carbon\Carbon Object  
    (  
    [date] => 47089-05-28 09:37:59.000000  
    [timezone_type] => 3  
    [timezone] => UTC  
    )  

Any ideas why $postedTime is so wrong? Obviously server's time is ok, because now() is correct, but what is happening on createFromTimestamp here?

**Comment by briannesbitt** [comment]
My guess is the timestamp was from javascript which uses ms ?

**Comment by raffw7912** [comment]
Hi, not really, that's why I was so misguided! Actually it is Brightpearl's API (http://brightpearl.com). They are using Java and PHP and for some reason, without writing about it in docs, they use ms timestamps. I'm glad I spotted 3 digits too many before I went mental ;) Thanks for great lib!
