### ISSUE TITLE
Method setHour does not exist.

### ISSUE THREAD

**Issue by grekpg** [briannesbitt/Carbon#2521]
After auto update i lost functions, example 

Method setHour does not exist.

```
 "name": "nesbot/carbon",
            "version": "1.39.1",
```

where is reason to remove this function and with version i last with this function exist ?

**Comment by kylekatarnls** [comment]
`setHour` still exist as a dynamic setter (via `__set`) in 2.* and 3.* versions.

See by yourself with the code:
```php
echo Cabon::now()->setHour(2);
```

If you have any issue with one of the currently supported version (1.x is no longer supported), please open an issue following the template giving a code chunk that can be used to reproduce your issue, expected and actual behavior.

Thanks.
