### ISSUE TITLE
Adding 

### ISSUE THREAD

**Issue by peter279k** [briannesbitt/Carbon#2526]
Hello,

According to the [ISO-8601](https://en.wikipedia.org/wiki/ISO_8601) introduction, it should have three formats.
But it only supports two formats at this moment. One is standard ISO-8601 and another one is Zulu ISO-8601 strings.
I think it should have the ordinal ISO-8601 string. E.g. `20211229T061701Z`.

The sample codes are as follows if above feature is implemented:

```php
$dt = Carbon::createFromFormat('Y-m-d H:i:s.u', '2019-02-01 03:45:27.612584');
echo $dt->toIso8601OrdinalString();    // 20190201T034527Z
```

Carbon version: **master**

PHP version: **7.4.27**

Thanks!

**Comment by kylekatarnls** [comment]
Hello, 👋 

Regarding the norm, it also states that:
> If necessary for a particular application, the standard supports the addition of a decimal fraction to the smallest time value in the representation

Which means, each format could also have variants with millisecond/microseconds, delimiter/no delimiter, offset/zulu. In the end ISO-8601 is a wide matrix with many possible outputs for a given date.

We already have a lot (likely too much) `to**String` methods and this actually defeat the normalization purpose.

As a first option, I would avoid to use `20190201T034527Z` which is way less readable, not immediately recognizable as a date, and starts to be ambiguous once introducing the second fraction or years > 9999. Prefer to communicate with `'Y-m-d\TH:i:s.u\Z'` e.g. `toISOString()`.

As an alternative, you can easily create your own macro for this:
```php
Carbon::macro(
  'toIso8601OrdinalString',
  static fn () => self::this()->utc()->format('Ymd\THis\Z'),
);

$dt = Carbon::createFromFormat('Y-m-d H:i:s.u', '2019-02-01 03:45:27.612584');

echo $dt->toIso8601OrdinalString();
```

Thanks.
