### ISSUE TITLE
Handling infinite recurrences on parsing from ISO 8601 string

### ISSUE THREAD

**Issue by dbohn** [briannesbitt/Carbon#2527]
Hello,

I encountered an issue with the following code:
```php
$period = CarbonPeriod::create('2018-05-31', 'P3M', INF);

echo CarbonPeriod::create($period->toIso8601String())->toIso8601String();
```

Carbon version: **2.55.2**

PHP version: **8.0.14**

I expected to get:

```
RINF/2018-05-31T00:00:00+00:00/P3M
```

But I actually get:

```
Error: Could not parse 'RINF': DateTime::__construct(): Failed to parse time string (RINF) at position 0 (R): The timezone could not be found in the database
```

I expected, that the ISO8601 serialization created by CarbonPeriod could be used to create a new CarbonPeriod object, that is similarly constructed. I assume, that INF as a recurrence parameter might be a deviation from the standard format. Is this behaviour intended, that these periods can be serialized to an ISO8601 string but not deserialized again?

Thanks!

**Comment by kylekatarnls** [comment]
Hello,

"INF" is not actually part of the ISO-8601 norm, it's how the PHP `INF` constant get serialized automatically when casted to sring. And infinite recurrence is also a Carbon feature, it's not handled in ISO-8601 neither supported in the native `DatePeriod` PHP class.

However as it does not overlap any other syntax. we could handle it as a special syntax in the `CarbonPeriod` constructor as we manually check for syntax via this RegExp:
https://github.com/briannesbitt/Carbon/blob/master/src/Carbon/CarbonPeriod.php#L485
