### ISSUE TITLE
createFromTimestampMs on system32 does not work

### ISSUE THREAD

**Issue by buse974** [briannesbitt/Carbon#2535]
Hello,

I encountered an issue with the following code:
```php
echo Carbon::createFromTimestampMs("1642018148265");
```

Carbon version: 2.53.1

PHP version: 8.1.1

### Context.

I am developing an API which uses Carbon on several environments, the problem noted is a problem on a _**Raspberry arm7 32bits (PHP 32)**_.

When I use the **createFromTimestampMs** function on **system64** I get the result

```
2022-01-12 20:09:37
```

But when I use the **createFromTimestampMs** function on **system32** I get the result

```
1970-01-25 20:31:23
```

### The problem.

The **createFromTimestampMs** method calls **getIntegerAndDecimalParts** ($ timestamp, 3);
and in this method we execute a cast.

vendor/nesbot/carbon/src/Carbon/Traits/Timestamp.php:190
```
$integer += (int) $integerPart;
```
However on a **system32** **PHP_INT_MAX** is equal to **2147483647** and on a **system64** **PHP_INT_MAX** is equal to **9223372036854775807**

We can see on **system32**
```
echo (int)1642018148265;       we obtain  1340641193
echo (int)"1642018148265";     we obtain  2147483647
```
On **system64** no problem we have
```
echo (int)1642018148265;       we obtain  1642018148265
echo (int)"1642018148265";     we obtain  1642018148265
```

So in state createFromTimestampMs cannot work on any version of php compiled in 32.

### Possible solution

The only simple solution I have found is to change the cast to a (float)
```
$integer += (float) $integerPart;
```
And with a cast float I find the right result:
```
2022-01-12 20:09:37
```

Thanks!

**Comment by kylekatarnls** [comment]
Hello,

You should be able to work around with:
```php
echo Carbon::createFromTimestamp(floatval("1642018148265") / 1000);
```

I would check and merge if you would propose a merge-request and would have to check we don't have any precision loss (64bit system should continue to be milli-second precise).

If you can I would also suggest to use a more robust date-time representation such as `Y-m-d H:i:s.u` or ISO-8601.

Thanks.

**Comment by buse974** [comment]
Hello,

Thank you, It works perfectly, and with precision.
```
echo Carbon::createFromTimestamp(floatval("1642065959484")/1000)->format("Y-m-d H:i:s.u");  => 2022-01-13 09:25:59.484000
```

Otherwise, the solution I proposed (changing the cast by a float) is not correct (system32).
```
echo Carbon::createFromTimestampMs(("1642065959484")->format("Y-m-d H:i:s.u");  => 2022-01-13 09:25:59.412000
```
The precision is no longer correct, so this is not a good solution.

Anyway, I'll use "createFromTimestamp" which suits me. 

Thank you.
