### ISSUE TITLE
Carbon\CarbonInterval::setLocalTranslator(): Argument #1 ($translator) must be of type Symfony\Component\Translation\TranslatorInterface, Carbon\Translator given

### ISSUE THREAD

**Issue by techmahedy** [briannesbitt/Carbon#2536]
I am facing this issue with Laravel 8 version and my php version is 7.4

**Comment by kylekatarnls** [comment]
Please provide:

- [ ] your Carbon version;
- [ ] your Composer version;
- [ ] minimal steps to reproduce your case;

`Carbon\Translator` does implement this interface. So my wild guess is that the vendor installation is incomplete.

Be sure you have in your vendor directory at least:
- symfony/translation
- nesbot/carbon/src
- nesbot/carbon/lazy

Thanks.

**Comment by techmahedy** [comment]
Composer version 2.0.8 and nesbot\carbon version is ^2.0. 

Be sure you have in your vendor directory at least:

- symfony/translation
- nesbot/carbon/src
- nesbot/carbon/lazy

All the folders are there. But still facing this error

**Comment by kylekatarnls** [comment]
Hello `^2.0` can be anything from 2.0.0 to 2.55.2. As stated in the issue template, please run the command `composer show nesbot/carbon` to get the exact version.

Please also try to rebuild your autoload with `php artisan dump-autoload` or a reinstall with `composer install`

**Comment by fisharebest** [comment]
I have the same error, and I have been able to identify the cause.

My projects creates a distribution file (.zip) containing all the vendor files.  Users upgrade by unpacking the latest zip file.  This means that old files from previous versions not be deleted.  These are generally harmless.

[Yes, we should instruct users to delete old files, but upgrades have been kept intentionally simple to encourage users to upgrade regularly...]

Recently, my project upgraded from symfony 4 to symfony 5, which involved an interface moving from one namespace to another: `Symfony\Component\Translation\TranslatorInterface` -> `Symfony\Contracts\Translation\TranslatorInterface`.
            
Carbon uses the Symfony 4 class, and creates an alias from the symfony 5 class.
The code is here: https://github.com/briannesbitt/Carbon/blob/2.56.0/src/Carbon/Traits/Localization.php#L26-L31

Now, if the you are using symfony 5 **and** the old symfony 4 file still exists, then this logic fails.

The ideal solution is for carbon to reverse the logic.  i.e. to code against the symfony 5 class, and create the alias to the symfony 4 class when the symfony 5 class does not exist.

This would be a simple change, and I would be happy to create a PR for it - if it would be welcomed.

Until then, my workaround is to add the following code to my application's bootstrap method.

```
class_alias(
        'Symfony\\Contracts\\Translation\\TranslatorInterface',
        'Symfony\\Component\\Translation\\TranslatorInterface'
    );
```

**Comment by kylekatarnls** [comment]
We could do #2586 so we give precedence to Symfony 5 but would allow app to have Symfony 4 or both 4 and 5.

As a consequence, if an app has both Symfony 4 and 5 stuff and try to pass a Symfony 4 translator to `setLocalTranslator()` it should throw an exception. But anyway there is no way for us to support both unless we drop the typing here, but that's a breaking change too.

Still, the best move for anyone having this issue is to fully upgrade to Symfony 5 or 6 and get completely rid of Symfony 4.

**Comment by fisharebest** [comment]
> Still, the best move for anyone having this issue is ... completely rid of Symfony 4.

Agreed.  But this is harder than it sounds.

The thousands of users of my app have been upgrading for the last 19 years by simply unpacking the latest .ZIP file.

We do attempt to clean up old files - but on servers running PHP as an unprivileged user such as `www-data`, this isn't possible.

At the moment, my latest code has this in it's bootstrap, which isn't very user-friendly.

```
// @see https://github.com/briannesbitt/Carbon/issues/2536
$file = '/vendor/symfony/translation/TranslatorInterface.php';
if (file_exists(__DIR__ . $file) && !unlink(__DIR__ . $file)) {
    echo 'Please delete the file ' . $file;
    return;
}
```

I'm happy to put any workarounds in my own codebase - rather than asking you to change yours - but I can't find any.

And also, I do appreciate you looking at this, especially since it is not your fault/problem...

**Comment by kylekatarnls** [comment]
I added a new change on the same PR to skip the type check. When it's called internally (e.g. translator created from within Carbon) can you retry with this last change?
https://github.com/briannesbitt/Carbon/pull/2586/commits/847b5dcd6e1fe6b9ba452b420d19d39c5a36bb93

**Comment by kylekatarnls** [comment]
Then, we'll fix it this way.

If users have other cases when they call manually `->setLocaleTranslator()` and have a mix Symfony 4+5, they'll have to create a wrapper class (implementing the old interface) to make the translator compatible.

We likely won't support more other cases like this in Carbon v2 and Carbon v3 will only support `Symfony\Contracts\Translation\TranslatorInterface` (no compatibility alias).

**Comment by austenstrine** [comment]
It looks like you have a workaround as of 2.58.0, and it shouldn't be a problem until 3.0.0, but I'm using Carbon 2.65.0 and this is happening to me. Is there something I have to do on my end? Did I misunderstand the solution?

I tried downgrading to carbon 2.58.0 and it didn't help.
laravel 5.8.38
php 7.4.26

**Comment by austenstrine** [comment]
FYI this workaround appears to have disappeared when calling ->diffForHumans(), at least for carbon 2.66.0, I'm not sure on any other versions.

vendor\nesbot\carbon\src\Carbon\Traits\Difference.php on line 848
Argument 1 passed to Carbon\CarbonInterval::setLocalTranslator() must implement interface Symfony\Component\Translation\TranslatorInterface, instance of Carbon\Translator given

I downgraded to 2.58.0 and the exception disappeared.
