### ISSUE TITLE
`startOfWeek` behaviour is not consistent.

### ISSUE THREAD

**Issue by edalzell** [briannesbitt/Carbon#2539]
Hello,

I encountered an issue with the following code:
```php
$foo = Carbon::now()->locale('en');
$bar = Carbon::now()->locale('en_US');

echo $foo->locale().PHP_EOL;
echo $bar->locale().PHP_EOL;
echo $foo->startOfWeek()->dayOfWeek.PHP_EOL;
echo $bar->startOfWeek()->dayOfWeek.PHP_EOL;
echo  $foo->week.PHP_EOL;
echo  $bar->week.PHP_EOL;
echo  $foo->format('Y-m-d H:i:s').PHP_EOL;
echo  $bar->format('Y-m-d H:i:s').PHP_EOL;
echo  $foo->tz.PHP_EOL;
echo  $bar->tz.PHP_EOL;
```

Carbon version: 2.55.2
PHP version: 8.0.14

I expected to get:

```
en
en_US
1
0
3
3
2022-01-10 00:00:00
2022-01-09 00:00:00
UTC
UTC
```

But I actually get:

```
en
en_US
0
0
3
3
2022-01-09 00:00:00
2022-01-09 00:00:00
UTC
UTC
```

If I change the first line to `$foo = Carbon::now();` I get the results I expect.

Thanks!

**Comment by edalzell** [comment]
I should add that I'm trying this in a Laravel app who's locale IS set to `en_us` and getting diff results as well:
<img width="1354" alt="CleanShot 2022-01-13 at 12 21 19@2x" src="https://user-images.githubusercontent.com/6069653/149403456-790c032c-50bb-40cf-8805-ccb0e62ddfdd.png">

**Comment by kylekatarnls** [comment]
Hello, sorry for the delay. `en` is the default and it inherit inconsistency for backward compatibility because some methods were actually there before Carbon start supporting localization.

What you need is to explicitly as for `en_001` (International English):
```php
$foo = Carbon::now()->locale('en');
$bar = Carbon::now()->locale('en_US');

echo $foo->locale().PHP_EOL;
echo $bar->locale().PHP_EOL;
echo $foo->startOfWeek()->dayOfWeek.PHP_EOL;
echo $bar->startOfWeek()->dayOfWeek.PHP_EOL;
echo  $foo->week.PHP_EOL;
echo  $bar->week.PHP_EOL;
echo  $foo->format('Y-m-d H:i:s').PHP_EOL;
echo  $bar->format('Y-m-d H:i:s').PHP_EOL;
echo  $foo->tz.PHP_EOL;
echo  $bar->tz.PHP_EOL;
```

As you can see if you try the next major version (3.x-dev), it will become the default. E.g. your code gives the exact result you expect with the version 3. And as it's a breaking change, we won't fix it in the version 2.

Thanks.

**Comment by edalzell** [comment]
I'm sorry @kylekatarnls but I don't understand how I'm supposed to determine if a given date string is the start of the week, can  you please explain?

**Comment by SimonJ** [comment]
+1 on this

**Comment by kylekatarnls** [comment]
I recommend:
```php
$sunday = Carbon::parse('next Sunday');
$monday = Carbon::parse('next Monday');

function isStartOfWeek(Carbon $date, string $locale): bool
{
  return $date->isSameDay($date->copy()->locale($locale)->startOfWeek());
}

var_dump(isStartOfWeek($sunday, 'en_US'));
var_dump(isStartOfWeek($monday, 'en_US'));

var_dump(isStartOfWeek($sunday, 'fr_FR'));
var_dump(isStartOfWeek($monday, 'fr_FR'));
```
