### ISSUE TITLE
any way to check that date is not valid from timestamp `0000-00-00 00:00:00`

### ISSUE THREAD

**Issue by saqueib** [briannesbitt/Carbon#254]
Is there any way to check that given date is not valid in Carbon, I am using Laravel and default timestamp is `0000-00-00 00:00:00` which is showing as `-0001-11-30 06:12:32` and even bad when using `->diffForHumans()` its giving me `2044 years ago`

I want to do something like this.

     return ((string) $model->last_activity == '0000-00-00 00:00:00') 
                             ? "Never" 
                             :  $model->last_activity->diffForHumans();

is there any simpler way to check that date is not valid, like on any `Carbon` instance 

    return $model->last_activity->valid()   // return boolean

**I will appreciate if you can add this checking in `->diffForHumans()` method, so it doesn't return `2044 years ago` on invalid dates.**

I have checked [this solution](http://stackoverflow.com/questions/19174592/how-to-handle-unset-default-dates-in-laravel-with-carbon) on SE, but its changes the `Carbon` date to string

**Comment by briannesbitt** [comment]
Assuming this is coming from a db, I would expect a nullable value if it really is optional?!?  Then you just have a simple null check.

Anyway, you could check the year value `$dt->year < 1` or something more like:

```php
return $model->last_activity->lt(Carbon::minValue()) ? "Never" : $model->last_activity->diffForHumans();
```

**Comment by saqueib** [comment]
Thanks for clarification, keep up the great work

**Comment by halilim** [comment]
FYI, I needed this too, but `lt()` adds a little bit overhead (or not so little if you are calling it multiple times, e.g. in a data grid). Hence I'm doing something like this:

    return $model->last_activity->timestamp <= 0
        ? "Never"
        : $model->last_activity->diffForHumans();

**Comment by ericmagnuson** [comment]
+1 For using `$model->last_activity->timestamp <= 0` to check for zero-value dates. I wish there was a cleaner way but this has low overhead.

**Comment by blur-dave-amphlett** [comment]
https://gist.github.com/blur-dave-amphlett/b7076497c273e79a7a552446c169291b

**Comment by JoshMoreno** [comment]
In case this helps any laravel devs. In your model, you can override the `asDateTime` and `asDate` methods from the `Illuminate\Database\Eloquent\Concerns\HasAttributes` trait.

This should work. 
```php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Carbon;

class MyModel extends Model
{
    protected function asDate(mixed $value): ?Carbon
    {
        return $value ? parent::asDate($value) : null;
    }

    protected function asDateTime(mixed $value): ?Carbon
    {
        return $value ? parent::asDateTime($value) : null;
    }
}
```
