### ISSUE TITLE
holidays

### ISSUE THREAD

**Issue by paskuale75** [briannesbitt/Carbon#2540]
Hello,

Carbon version: ^2.16

PHP version: 7.4.3

**Ask: can I manage the holidays with this library?**

Thanks!

**Comment by kylekatarnls** [comment]
Hello 👋 

There are dedicated mixins for that:

https://github.com/kylekatarnls/business-day
https://github.com/kylekatarnls/business-time

You'll also find the methods from those mixins directly documented in the Carbon doc with the mention "Requires cmixin/business-time"
![image](https://user-images.githubusercontent.com/5966783/150387633-17938890-1e33-46cc-8207-d2eb320c471b.png)

**Comment by paskuale75** [comment]
many thanks @kylekatarnls
