### ISSUE TITLE
strange breaking changes between 2.55.2 and 2.56.0

### ISSUE THREAD

**Issue by danijelk** [briannesbitt/Carbon#2545]
Hello,

I encountered an issue with the following code:
```php
        $last_transaction_at = now()->setTime(12, 0);
        $this->assertDatabaseHas((new ApiIntegration)->getTable(), [
            'id' => $this->apiIntegration->id,
            'last_transaction_at' => $last_transaction_at,
            'next_run_at' => now()->addMinutes(15),
        ]);
```

Carbon version: 2.56.0
PHP version: 8.0.14
Laravel: 8.81.0

I expected to get:

```
Green test
```

But I actually get:

```

Failed asserting that a row in the table [api_integrations] matches the attributes {
      "id": 70,
      "last_transaction_at": {
          "date": "2019-02-01 10:00:00.000000",
          "timezone_type": 3,
          "timezone": "UTC"
      },
      "next_run_at": {
          "date": "2019-02-02 03:00:00.000000",
          "timezone_type": 3,
          "timezone": "UTC"
      }
  }.
  
  Found similar results: [
      {
          "id": 70,
          "type": "import",
          "collector": "sensor",
          "location_id": 21792,
          "config": "{\"organisation_id\":\"1234\"}",
          "service": "zoined",
          "last_transaction_at": null,
          "next_run_at": "2019-02-02 03:00:00",
          "disabled": 0,
          "created_at": "2019-02-01 10:00:00",
          "updated_at": "2019-02-01 10:00:00"
      }
  ].
```

Thanks!

**Comment by kylekatarnls** [comment]
I can see anything in 2.56.0 changing the behavior of `setTime` or `addMinutes` and here the difference sounds to be `last_transaction_at` being `null` in the record. So likely the test is not the relevant part, but more likely `last_transaction_at` happens to be `null` in the DB and not before.

Can you also double check that the test pass when downgrading carbon (and keeping all the other dependencies at the same version)?

**Comment by kylekatarnls** [comment]
Hello,

date vs string shouldn't be an issue. Laravel automatically cast dates to string for DB comparison using the configuration in your schema (depending if it's marked as datetime() or timestamp() and the precision you chose for the number of decimals after the second) but this part has no reason behave differently.

So I would compare the 2 records you have for `$this->apiIntegration->id` before and after the upgrade to figure out what differs.

**Comment by danijelk** [comment]
I see, it's the new string compare from #2529

we have `$date->greaterThan($this->apiIntegration->last_transaction_at)`

where last_transaction_at is undefined and not null so it fails to be less than, will rework our logic to fit the new patch. Thanks for assistance

**Comment by danijelk** [comment]
null compare didn't matter, so we just added a !== null on the variable on our if clause and that fixed the test, hopefully others wont have same unexpected behaviour but at least they have this ticket to refer to if they do.
