### ISSUE TITLE
PHP 8.1 Implicit conversion from float to int loses precision

### ISSUE THREAD

**Issue by levu42** [briannesbitt/Carbon#2549]
Hello,

I encountered an issue with the following code:
```php
echo Carbon::parse('2018-06-15')->isoFormat('Do');
```

Carbon version: 2.56.0

PHP version: 8.1.2

I expected to get:

```
15th
```

But I actually get:

```
"Error: Implicit conversion from float 1.5 to int loses precision"
```

The issue is in src/Carbon/Lang/en.php on line 75:

```php
    'ordinal' => function ($number) {
        $lastDigit = $number % 10;

        return $number.(
            (~~($number % 100 / 10) === 1) ? 'th' : (
                ($lastDigit === 1) ? 'st' : (
                    ($lastDigit === 2) ? 'nd' : (
                        ($lastDigit === 3) ? 'rd' : 'th'
                    )
                )
            )
        );
    },

```

Specifically in:

```php
~~($number % 100 / 10) === 1
```

Thanks!

**Comment by kylekatarnls** [comment]
Thanks for the report.

For the record, I can't reproduce as an "Error" I can only get "Deprecated: Implicit conversion from float 1.5 to int loses precision".

Normally this will only happen with `E_DEPRECATED` on and will become an error only in PHP 9.
