### ISSUE TITLE
Holidays ?

### ISSUE THREAD

**Issue by barbuslex** [briannesbitt/Carbon#255]
Hi,

Carbon he supports the holidays ?
Here for more info : http://www.informatix.fr/tutoriels/php/trouver-les-jours-feries-francais-en-php-137

Thanks,
++

**Comment by kylekatarnls** [comment]
No Brian suggest to extends Carbon in a subclass for that, see discussion and some codes in #116 

Maybe laravel-date do it.

Sorry

**Comment by briannesbitt** [comment]
Good luck with that!  :-)

**Comment by rmblstrp** [comment]
I created a PR which adds Carbon extensions that check to see if a given date is a business day. Custom holiday and business schedules can be provided which allow you to properly determine what the date is for next or previous number of business days.

https://github.com/briannesbitt/Carbon/pull/706
