### ISSUE TITLE
diffInDays() difference between 2.55.2 and 2.57.0

### ISSUE THREAD

**Issue by tmannherz** [briannesbitt/Carbon#2555]
We're seeing different return values in the method `diffInDays()` between versions `2.55.2` and `2.57.0` when running the same snippet:

```php
$d1 = Carbon\Carbon::now()->addDay();
$d2 = Carbon\Carbon::now();

echo $d1->toISOString() . "\n";
echo $d2->toISOString() . "\n";
echo $d2->diffInDays($d1) . "\n";
```

`2.55.2`
```
2022-03-01T20:55:26.742291Z
2022-02-28T20:55:26.742503Z
1
```

`2.57.0`
```
2022-03-01T20:52:27.360350Z
2022-02-28T20:52:27.360536Z
0
```

I would expect that this test would return `1`, not `0` for `diffInDays()`.

Carbon version: **2.57.0**

PHP version: **8.0.10**

I expected to get:

```
1
```

But I actually get:

```
0
```

Thanks!

**Comment by kylekatarnls** [comment]
Hello 👋 

Your interval is 1 day minus 6 microseconds (PHP execution is not instantaneous), so as `diffInDays` return `int`, `0` is the correct output, and so it has been fixed. If you're looking for the precise `float` number, use `floatDiffInDays()`.

Alternatives are to freeze the time (reuse the same now() as a base for all operations) or to use rounding, such as `round($d2->floatDiffInDays($d1))`
