### ISSUE TITLE
Doctrine ORM : does not have a property named "secondPrecision"

### ISSUE THREAD

**Issue by aguidis** [briannesbitt/Carbon#2570]
Hello,

I encountered an issue with the following code from the [documentation](https://carbon.nesbot.com/symfony/).
```php
/**
 * @ORM\Column(type="datetime", secondPrecision=true)
 */
private $createdAt;
```

Carbon version: **2.57.0**

PHP version: **7.4.22**
Symfony version: **5.4**
Doctrine version: **2.11.0**

I expected to get in my migration file:

```
created_at DATETIME DEFAULT CURRENT_TIMESTAMP
```

But I actually get:

```
[Creation Error] The annotation @ORM\Column declared on property App\Audit\Entity\ActionHistory::$createdAt does not have a property named "secondPrecision"
  that can be set through its named arguments constructor.
  Available named arguments: name, type, length, precision, scale, unique, nullable, insertable, updatable, enumType, options, columnDefinition, generated
```

In the mean time, we put the line `\Carbon\Doctrine\DateTimeDefaultPrecision::set(0)` in the file **project/config/bundles.php** and everything works fine.

But I wanted to report this case for the others.

Thanks!

**Comment by kylekatarnls** [comment]
Hello 👋 

Thanks for the report, indeed the syntax is not correct:

It's as below with the last version:
```php
/**
 * @ORM\Column(type="datetime", options={"secondPrecision"=true})
 */
```

Doc updated, thanks 🙏 

For the record, I recommend as much as possible to keep maximum precision and prefer to set fields individually than globally, it makes your bundle standalone (able to be extracted/moved in other applications).
