### ISSUE TITLE
Febuary bug

### ISSUE THREAD

**Issue by Ignas2526** [briannesbitt/Carbon#2579]
Hello,

I encountered a very strange issue specifically with February. The non-Febuary dates work fine, but every Febuary there's this issue. This is a very serious issue in my opinion. There are no warnings and other dates work fine. Is this a Carbon bug or a PHP one?

```php
echo Carbon::createFromFormat('Ym','202202')->startOfMOnth()->toDateTimeString();
```
Expected:
2022-02-01 00:00:00
Actual result:
2022-**03**-01 00:00:00

```php
Carbon::now()->year('2022')->month('02')->day('1')->startOfMOnth()->toDateTimeString();
```
Expected:
2022-02-01 00:00:00
Actual result:
2022-**03**-01 00:00:00

Carbon version: 2.56.0

PHP version: 7.4.19

Timezone (php.ini)
```ini
date.timezone = "Europe/Stockholm"
```

**Comment by kylekatarnls** [comment]
Hello,

Use `Carbon::createFromFormat('`!Ym','202202')`
instead of `Carbon::createFromFormat('Ym','202202')->startOfMOnth()`

As per https://www.php.net/manual/en/datetime.createfromformat.php
