### ISSUE TITLE
an bug on addMonths or set mounth on 31-3-2022

### ISSUE THREAD

**Issue by alirayaneh** [briannesbitt/Carbon#2582]
Hello,

I encountered an issue with the following code:
```php

Carbon::now()

Illuminate\Support\Carbon @1648731658 {#3814
     date: 2022-03-31 08:00:58.421546 America/Chicago (-05:00),
   }


Carbon::now()->month;
3

 Carbon::now()->addMonths(1);

Illuminate\Support\Carbon @1651409976 {#3830
     date: 2022-05-01 07:59:36.293933 America/Chicago (-05:00),
   }


```

Thanks!

**Comment by kylekatarnls** [comment]
Hello,

This is inherited from PHP DataTime class behavior and explained in the [doc Addition and subtraction chapter].

Duplicate https://github.com/briannesbitt/Carbon/issues/2173#issuecomment-683684740
