### ISSUE TITLE
[Translation tool] da

### ISSUE THREAD

**Issue by kokoshneta** [briannesbitt/Carbon#2584]
|English|da|comments|
|--|--|--|
|Mon|man|man.|
|Mo|ma|ma.|
|Tue|tir|tir.|
|Tu|ti|ti.|
|Wed|ons|ons.|
|We|on|on.|
|Thu|tor|tor.|
|Th|to|to.|
|Fri|fre|fre.|
|Fr|fr|fr.|
|Sat|lør|lør.|
|Sa|lø|lø.|
|Sun|søn|søn.|
|Su|sø|sø.|
|Jan|jan|jan.|
|Feb|feb|feb.|
|Mar|mar|mar.|
|Apr|apr|apr.|
|Jun|jun|jun.|
|Jul|jul|jul.|
|Aug|aug|aug.|
|Sep|sep|sep.|
|Oct|okt|okt.|
|Nov|nov|nov.|
|Dec|dec|dec.|
|2 hours ago|2 timer siden|for 2 timer siden|

----
1. According to the recommendations of the Danish Language Council, abbreviations of weekdays and months should have a closing stop (to match “min.”, “t.”, “s.”, etc., which already have the stop). They also appear as such in “Rigtigt kort: Anbefalede forkortelser” (“Properly brief: Recommended abbreviations”), published by the Council in 2004 and available at https://dsn.dk/wp-content/uploads/2021/01/Rigtigt-kort-indskannet.pdf.

2. The preposition _for_ in “for 2 timer siden” is required to express that something happened ‘2 hours ago’.

**Comment by kylekatarnls** [comment]
🙏 Thanks for the report. Sounds correct.

If you or anyone is willing to fix the translations, those are the files to be updated:
https://github.com/briannesbitt/Carbon/blob/master/src/Carbon/Lang/da.php

And tests:
https://github.com/briannesbitt/Carbon/blob/master/tests/Localization/DaTest.php
https://github.com/briannesbitt/Carbon/blob/master/tests/Localization/DaDkTest.php
https://github.com/briannesbitt/Carbon/blob/master/tests/Localization/DaGlTest.php

**Comment by kokoshneta** [comment]
PR #2585 added (I think correctly… let me know if I did something wrong.)

**Comment by kylekatarnls** [comment]
Thank you so much 🙏 running the automated tests, if all green it's good to be merged.

**Comment by kylekatarnls** [comment]
This will be fixed in the next release, it can be tested using `composer require "nesbot/carbon:dev-master as 2.58.0"`

Thanks 🙏
