### ISSUE TITLE
`CarbonTimeZone` behaves differently from `DateTimeZone` for short, signed offset values

### ISSUE THREAD

**Issue by Nextra** [briannesbitt/Carbon#2588]
Hello,

I encountered an issue with the following code:
```php
echo (new CarbonTimeZone('+01'))->getName()
```

Carbon version: 2.57.0
PHP version: 8.1.1

I expected to get:

```
+01:00
```

But I actually get an exception:

```
DateTimeZone::__construct(): Unknown or bad timezone (++01:00)
```

Doing the same with a native DateTimeZone works as expected:

```php
echo (new DateTimeZone('+01'))->getName()
```

shows:

```
+01:00
```

Thanks!

**Comment by kylekatarnls** [comment]
Hello 👋 

Thanks for the report.

I will check if we can and should support this.

In the meantime I recommend to use the explicit full timezone string:

```php
echo (new CarbonTimeZone('+01:00'))->getName();
```

It's supported, and the less ambiguous way IMO.

**Comment by Nextra** [comment]
I'm all good, don't worry about that. Found out about this discrepancy when playing around with 8601, pretty much by accident. Just figured I'd make someone aware.

Cheers for all you do!
