### ISSUE TITLE
[Translation tool] sk_SK

### ISSUE THREAD

**Issue by AlterwebStudio** [briannesbitt/Carbon#2593]
|English|sk_SK|comments|
|--|--|--|
|a few seconds|sekundu|pár sekúnd|
|Mon|po|pon|
|Tuesday|utorok|uto|
|Wed|st|str|
|Thu|št|štv|
|Fri|pi|pia|
|Sat|so|sob|
|Sun|ne|ned|
|2 hours from now|za 2 hodiny|o 2 hodiny|
|2 hours after|o 2 hodiny neskôr|2 hodiny potom|

**Comment by kylekatarnls** [comment]
Hello, can we check `o 2 hodiny neskôr` vs. `2 hodiny potom` (and maybe `2 hodiny predtým` for consistency).

Here are the case where it's supposed to be used:

Incident happened: `2 days ago` / `pred 2 dni` (absolute : relative to now)
Incident resolution: `2 hours after` / `2 hodiny potom` (note that this is in the past, but after the other event : relative to an other date), can you check if here `o 2 hodiny neskôr` is better?

Next meeting: `2 days from now` / `o 2 hodiny`
Room will be available: `2 hours before` / `2 hodiny predtým`

I would like to be sure we have 4 consistent phrasing and that would be common/natural enough.

**Comment by kylekatarnls** [comment]
Hi @AlterwebStudio, I got advised po/pred would be more commong than potom/predtým, so I changed it and it's now released in 2.59.0. Thanks. 🙏
