### ISSUE TITLE
Where is the implementation of `addWeekdays()`?

### ISSUE THREAD

**Issue by DurandA** [briannesbitt/Carbon#2602]
Hello and sorry for the dumb question.

I cannot find the implementation of the `addWeekdays()` method in the _Carbon_ source code. It seems that there are only interface definition of `addWeekdays` and it is not part of PHP _DateTime_ object. Sorry for the dumb question, but where can I find the implementation of this method?

**Comment by kylekatarnls** [comment]
Hello,

The add* methods use the magic __call method and "weekday" is a unit DateTime supports nativeley in modify() wich is what we use:

https://3v4l.org/5YnX5
