### ISSUE TITLE
Invalid floatDiffInDays calculate

### ISSUE THREAD

**Issue by dreeh** [briannesbitt/Carbon#2605]
Hello,

I encountered an issue with the following code:
```php
$now = new Carbon('2016-10-28 16:00:00');
$then2 = new Carbon('2016-10-31 15:00:00');

echo $now->floatDiffInDays($then2);
// actual: 3.9583333333333
// expecting: 2.9583333333333

echo PHP_EOL;

echo $then2->floatDiffInDays($now);
// actual: 3.9583333333333
// expecting: 2.9583333333333
```

Carbon version: **2.57.0**

PHP version: **7.4.27**

Comes with issue #2531.

I expected to get:

```
2.9583333333333
```

But I actually get:

```
3.9583333333333
```

Thanks!

**Comment by viniciusss** [comment]
Hello, i found something similar.

```php
$duedate = new Carbon('now'))->addDays(20);
$today = new Carbon('now');

echo $duedate->diffInDays($today);

```

I expected to get:
```
-20
```

But i got

```
-19
```

I don't have this problem in 2.56 release.

**Comment by kylekatarnls** [comment]
Hello, I don't reproduce. As a wild guess I'd say you are in a timezone with a DST change in the period. They have some known bugs in PHP.

By the way, it way safer to use only UTC on the back-end side.
