### ISSUE TITLE
Typehints for CarbonInterval

### ISSUE THREAD

**Issue by func0der** [briannesbitt/Carbon#2606]
Context: https://github.com/briannesbitt/Carbon/blob/10248a6fc66648b5a928e5714056aa0cb2ce7d53/src/Carbon/CarbonInterval.php#L347

Here it say that `years` can be `int|null`, when from the code it could actually be `int|null|\Closure|\DateInterval|string` according to:
https://github.com/briannesbitt/Carbon/blob/master/src/Carbon/CarbonInterval.php#L360 -> Closure
https://github.com/briannesbitt/Carbon/blob/master/src/Carbon/CarbonInterval.php#L365 -> \DateInterval
https://github.com/briannesbitt/Carbon/blob/master/src/Carbon/CarbonInterval.php#L375 -> string

This confuses static code analysers like PHPStan.

Can we clarify that behavior and/or create dedicated methods to address those types?
Or is this intentionally and you want the public api of `CarbonInterval` to be `int|null` only? If that is the case, the documentation is misleading, because you give examples like this:

```php
$ci = CarbonInterval::create('P1Y2M3D');
var_dump($ci->isEmpty()); // bool(false)
$ci = new CarbonInterval('PT0S');
var_dump($ci->isEmpty()); // bool(true)
```

**Comment by kylekatarnls** [comment]
Hello, `int|\Closure|\DateInterval|string|null` is clearly the expected behavior, `$years` will indeed be used as an global interval representation if it's not `int|null`.

Pull-request to update the PHPDoc would be welcome.
