### ISSUE TITLE
PHPStan macro doesn't support PHPStan 1.7.x

### ISSUE THREAD

**Issue by gregtyler** [briannesbitt/Carbon#2629]
Hello,

When running PHPStan 1.7.x with the Carbon macro the following error occurs:
> PHP Fatal error:  Declaration of `Carbon\PHPStan\AbstractMacro::getReflection(): ?ReflectionMethod` must be compatible with `PHPStan\Reflection\Php\BuiltinMethodReflection::getReflection(): ?PHPStan\BetterReflection\Reflection\Adapter\ReflectionMethod` in /var/www/vendor/nesbot/carbon/src/Carbon/PHPStan/AbstractMacro.php on line 211                              

This is because [PHPStan 1.7.0 included an overhaul of static reflection](https://github.com/phpstan/phpstan/releases/tag/1.7.0) which included [changing the return type](https://github.com/phpstan/phpstan-src/pull/1265/files#diff-118ce1aee3922aeae65327b5e79f318af404a8ea22ed773ea31e3ab3e8a2c83b) of `BuiltinMethodReflection::getReflection()` from the native `ReflectionMethod` to `PHPStan\BetterReflection\Reflection\Adapter\ReflectionMethod`.

Unfortunately, I can't see a way of fixing this without changing the macro to match PHPStan's changes, which would probably be incompatible with versions 1.6 and older of PHPStan.

Carbon version: **2.58.0**
PHP version: **8.1.6**
PHPStan version: **1.7.15** (though I believe this is true of all 1.7.x)

Thanks!

**Comment by kylekatarnls** [comment]
Hello,

I'm aware of it and tried multiple fixes with no luck and just wasting hours. We declared compatibility with `phpstan 1.x` assuming it would follow semver, but they narrowed return type of a public method declared by the interface `BuiltinMethodReflection` which is a breaking change and as this version requires PHP 7.2 while Carbon 2.x still supports 7.1, it will be quite a pain to support everything in the same Carbon version.

I'm not sure how we'll work around this but possibly we'll have to completely drop all the PHPStan support.

**Comment by kylekatarnls** [comment]
Fixed in 2.59.0.
