### ISSUE TITLE
PHP 8.2 - `utf8_encode` deprecated

### ISSUE THREAD

**Issue by systemsolutionweb** [briannesbitt/Carbon#2630]
Hello,

I encountered an issue with the following code: 
`utf8_encode()` deprecated
https://github.com/briannesbitt/Carbon/blob/88ac19cad69487d9345b65023f580920667d17de/src/Carbon/Traits/Date.php#L1856

Carbon version: **latest**

PHP version: 8.2

https://php.watch/versions/8.2/utf8_encode-utf8_decode-deprecated

**Suggestion:**
```php
return static::$utf8 ? (function_exists('mb_convert_encoding') ?
    mb_convert_encoding($formatted, 'UTF-8', mb_list_encodings()) :
    utf8_encode($formatted)) : $formatted;
```

Thanks!

**Comment by kylekatarnls** [comment]
Hi, thanks for the report. `mb_convert_encoding` is recommended as a replacement in [the official documentation](https://wiki.php.net/rfc/remove_utf_8_decode_encode) so your suggestion is good.

As the Carbon method `formatLocalized` it's in is also deprecated, we'll get rid of all that in a later version.

Would you mind to create a pull-request for it?

Maybe indent both ternary for readability:
```php
return static::$utf8
    ? (function_exists('mb_convert_encoding')
        ? mb_convert_encoding($formatted, 'UTF-8', mb_list_encodings())
        : utf8_encode($formatted)
    )
    : $formatted;
```
