### ISSUE TITLE
Release 2.59.0 not in Packagist

### ISSUE THREAD

**Issue by spawnia** [briannesbitt/Carbon#2633]
Hello Kyle,

the latest release [2.59.0](https://github.com/briannesbitt/Carbon/releases/tag/2.59.0) seems to be missing from Packagist: https://packagist.org/packages/nesbot/carbon

![image](https://user-images.githubusercontent.com/12158000/176413791-86f5d5cf-aace-4113-9473-3cbdaca70f29.png)

Maybe you need to reconnect the GitHub integration?

Thanks!

**Comment by kylekatarnls** [comment]
Thanks 🙏 updated.
