### ISSUE TITLE
Release 2.59.0 introduced Internal error; when running PHPStan

### ISSUE THREAD

**Issue by evertharmeling** [briannesbitt/Carbon#2634]
Hello,

I encountered an issue when running `phpstan`

Carbon version: **2.59.0**

PHP version: **7.4.25**

I think by accident a `var_dump` is commited and part of the latest release see: https://github.com/briannesbitt/Carbon/blob/master/src/Carbon/PHPStan/MacroExtension.php#L53-L57

I expected to get:

```
No error
```

But I actually get:

```
Internal error: Internal error: Failed to start the session because headers have already been sent by
     "/vendor/nesbot/carbon/src/Carbon/PHPStan/MacroExtension.php" at line 53.
```

Thanks!

**Comment by kylekatarnls** [comment]
Oh my... 🤦‍♂️

**Comment by evertharmeling** [comment]
Ah well, we are all human after all 😉
