### ISSUE TITLE
Accuracy loss problem

### ISSUE THREAD

**Issue by Ulyssesyi** [briannesbitt/Carbon#2636]
Hello,

I encountered an issue with the following code:
```php
echo Carbon::parse('2018-06-01')->endOfDay()->valueOf();
```

Carbon version: **2.59.1**

PHP version: **7.4.30**

I expected to get:

```
1527868799999
```

But I actually get:

```
1527868800000
```

All these is function **getPreciseTimestamp** loss accuracy. Can you change it to 
```
public function getPreciseTimestamp($precision = 6)
{
    return bcdiv($this->rawFormat('Uu'), pow(10, 6 - $precision));
}
```

Thanks!

**Comment by kylekatarnls** [comment]
Hello,

As per the documentation, `valueOf()` is milliseconds-precise:

> Returns the milliseconds timestamps used amongst other by Date javascript objects.

So this the correct rounding (1527868799999.999 is closest to 1527868800000 than to 1527868799999). Choosing `floor` (or `bcdiv`) over `round` is a specific case need, not generally wanted (if we deal with something like having an interval of 0.333333333333 hours representing 1/3 with some precision loss when sending/reading input and we want to add 6 of this interval to 12:00:00.000

```php
$interval = 0.333333333333;
echo Carbon::parse('2022-07-04 12:00:00.000 UTC')->addMicroseconds(round(3600000000.0 * $interval * 6)); // 2022-07-04 14:00:00
echo "\n";
echo Carbon::parse('2022-07-04 12:00:00.000 UTC')->addMicroseconds(floor(3600000000.0 * $interval * 6)); // 2022-07-04 13:59:59
```

I don't say it's always wanted. But if you need to truncate precision, you can still do it explicitly:

```php
echo Carbon::parse('2018-06-01')->endOfDay()->floorMillisecond()->valueOf();
```

And IMO it's good to be explicit 

While on the opposite, if we do this right into `valueOf` it would be a breaking change and it would not be an easy to recover the precise value for usages than need a rounding to the closest.

**Comment by Ulyssesyi** [comment]
I see, but this result is really confusing, hope to add an explanation to all **endOf** function. That would be very helpful. I think most developer who use **endOf** function wanted result is 1527868799999 not 1527868800000

**Comment by Ulyssesyi** [comment]
Change ```Resets the time to 23:59:59.999999 end of day``` to ```Resets the time to 23:59:59.999999 end of day, and if you want get unix timestamp maybe need to add floorSecond/floorMillisecond to truncate it, otherwise it will round to 00:00:00```
