### ISSUE TITLE
Can't createFromFormat() with more than 2 digit minutes

### ISSUE THREAD

**Issue by dinofarese** [briannesbitt/Carbon#2637]
Hello,

I encountered an issue with the following code:
```php
echo Carbon::createFromFormat('i', 100)->format('H:i:s');
```

Carbon version: 2.58.0

PHP version: 8.1.3

I expected to get:

```
01:40:00
```

But I actually get:

```
Error: Trailing data
/app/var/engines/carbon/2.x-dev/vendor/nesbot/carbon/src/Carbon/Traits/Creator.php:676
#0 /app/var/engines/carbon/2.x-dev/vendor/nesbot/carbon/src/Carbon/Traits/Creator.php(699): Carbon\Carbon::rawCreateFromFormat()
#1 /app/api/carbon.php(55) : eval()'d code(1): Carbon\Carbon::createFromFormat()
#2 /app/api/carbon.php(55): eval()
#3 {main}
```

Thanks!

**Comment by dinofarese** [comment]
Same issue with the current latest version (2.59.1)

**Comment by kylekatarnls** [comment]
Hello 👋 [createFromFormat](https://www.php.net/manual/en/datetimeimmutable.createfromformat.php) is a method from PHP native `DateTime` class (`Carbon` inherits it with no behavior change), as per the documentation above:

`i` represents the `Minutes with leading zeros` component of a date.

Documentation also gives the allowed range:
> 00 to 59. (2 digit numbers higher than 59 are accepted, in which case they will make the hour overflow. For example using 66 means :06 the next hour)

So it accepts values from 60 to 99, but don't do that it makes no sense. You can't create a date with its component minutes equal to 66, or 100, eventually you mean 1 hour and 40 minutes, but it's not a date it's an interval:

```php
echo Carbon::parse('00:00')->addMinutes(100)->format('H:i:s');
```

Thanks.
