### ISSUE TITLE
Add Laravel Octane Support

### ISSUE THREAD

**Issue by mcolominas** [briannesbitt/Carbon#2638]
Responding to a thread on laravel/octane (https://github.com/laravel/octane/issues/551#issuecomment-1180210039), I discovered a bug in this package.

From what I indicate in the title, this package is not supported when using Laravel Octane.

- What is the problem?
When updating the language of the application using `app()->setLocale('xx')`, the language in carbon is not updated

- Where does the problem originate?
In:
https://github.com/briannesbitt/Carbon/blob/a9000603ea337c8df16cc41f8b6be95a65f4d0f5/src/Carbon/Laravel/ServiceProvider.php#L47
Gets the application from when laravel octane is instantiated, so even if the language is changed, it will continue to return the default language, causing carbon to not update.

- How to solve the problem?
Change the `$this->app` inside `updateLocale` https://github.com/briannesbitt/Carbon/blob/a9000603ea337c8df16cc41f8b6be95a65f4d0f5/src/Carbon/Laravel/ServiceProvider.php#L45
to `Illuminate\Container\Container::getInstance()`

This solution should work whether laravel octane is used or not.

**Comment by kylekatarnls** [comment]
We'll try to work around this issue, but this is a global pitfall for any laravel service provider, it should instead be fixed in https://github.com/laravel/octane/blob/1.x/src/CurrentApplication.php#L25 IMO where Octane could change the app for each provider.

**Comment by kylekatarnls** [comment]
I proposed instead a global fix in laravel/octane for any provider doing similar boot process: https://github.com/laravel/octane/pull/556
