### ISSUE TITLE
PHP core change in 8.0.22 and 8.1.9 means DatePeriod no longer returns Carbon or CarbonImmutable

### ISSUE THREAD

**Issue by yitznewton** [briannesbitt/Carbon#2652]
Hello,

There's a breaking change in PHP 8.0.22 and 8.1.9 that affects Carbon when used with `DatePeriod`. It was meant to resolve this issue: http://bugs.php.net/80047

I encountered an issue with the following code:
```php
<?php

require __DIR__ . '/vendor/autoload.php';

$start = new \Carbon\CarbonImmutable();
$period = new \DatePeriod(
    $start,
    \Carbon\CarbonInterval::hour(),
    2,
);
foreach ($period as $date) {
    $class = get_class($date);
    if ($class !== \Carbon\CarbonImmutable::class) {
        echo "Oh no, it's a $class\n";
        exit(1);
    }
}

echo "All good\n";
```

Carbon version: 2.61.0

PHP version: 8.0.22, 8.1.9. Breaking change from previous patch version (8.1.8)

I expected to get:

```
All good
```

But I actually get:

```
Oh no, it's a DateTimeImmutable
```

This is a problem because the new return value breaks my type expectations. Note that the PHP core team did mention Carbon in the issue conversation (linked above)

Thanks!

**Comment by kylekatarnls** [comment]
Yes it's me asking in the link you posted.

`DatePeriod` is no under our control. You should use `CarbonPeriod` instead, or retry to ask on https://github.com/php/php-src as PHP team is the only one to decide what is the behavior of the vanilla `DatePeriod`.

```php
$start = new \Carbon\CarbonImmutable();
$period = new \Carbon\CarbonPeriod(
    $start,
    \Carbon\CarbonInterval::hour(),
    2,
);
$period->setDateClass(\Carbon\CarbonImmutable::class);

foreach ($period as $date) {
    echo get_class($date) . ':' . $date . "\n";
}
```

Thanks.
