### ISSUE TITLE
Wrong time when using timezone

### ISSUE THREAD

**Issue by forxer** [briannesbitt/Carbon#2654]
Hello,

I encountered an issue with the following code:
```php
Carbon::createFromFormat('Y-m-d H:i', '2015-06-18 09:30', 'Europe/London');
new Carbon('Thursday, June 18 2015 9:30:00', 'Europe/London');
Carbon::createFromTimestamp(1434619800, 'Europe/Paris');
Carbon::createFromTimestamp(1434619800, 'Europe/London');
```

Carbon version: **2.61.0**

PHP version: **8.0.12**

I expected to get:

```
2015/06/18 08:30
2015/06/18 08:30
2015/06/18 09:30
2015/06/18 08:30
```

But I actually get:

```
2015/06/18 09:30
2015/06/18 09:30
2015/06/18 11:30
2015/06/18 10:30
```

Here is a summary of my local tests :

`Carbon::now('Europe/Paris')`
Expected: 2022/08/18 22:14
Result:      2022/08/18 22:14
                ✓ OK

`Carbon::now('Europe/London')`
Expected: 2022/08/18 21:14
Result:      2022/08/18 21:14
                ✓ OK

`Carbon::createFromFormat('Y-m-d H:i', '2015-06-18 09:30', 'Europe/Paris')`
Expected: 2015/06/18 09:30
Result:      2015/06/18 09:30
                ✓ OK

`Carbon::createFromFormat('Y-m-d H:i', '2015-06-18 09:30', 'Europe/London')`
Expected: 2015/06/18 **08:30**
Result:      2015/06/18 **09:30**
                ❌ KO

`new Carbon('Thursday, June 18 2015 9:30:00', 'Europe/Paris')`
Expected: 2015/06/18 09:30
Result:      2015/06/18 09:30
                ✓ OK

`new Carbon('Thursday, June 18 2015 9:30:00', 'Europe/London')`
Expected: 2015/06/18 **08:30**
Result:      2015/06/18 **09:30**
                ❌ KO

`Carbon::createFromTimestamp(1434619800, 'Europe/Paris')`
Expected: 2015/06/18 **09:30**
Result:      2015/06/18 **11:30**
                ❌ KO

`Carbon::createFromTimestamp(1434619800, 'Europe/London')`
Expected: 2015/06/18 08:30
Result:      2015/06/18 10:30
                ❌ KO

I tested with https://try-carbon.herokuapp.com/ and got the same results.

Maybe I'm not doing it the right way, I don't know.

Thanks!

**Comment by kylekatarnls** [comment]
Hello,

I don't get why you expect those results:

# createFromTimestamp

```php
echo Carbon::createFromTimestamp(1434619800, 'Europe/Paris')->format('Y-m-d H:i:s e');
```

Which is equivalent to:
```php
$date = new DateTIme('@1434619800');
$date->setTimezone(new DateTimeZone('Europe/Paris'));
echo $date->format('Y-m-d H:i:s e');
```

Both give:
```
2015-06-18 11:30:00 Europe/Paris
```
Which is indeed the correct date and time in Paris for the timestamp `1434619800` (e.g. 1434619800 seconds after `January 1st 1970 00:00:00 UTC` which is the Unix timestamp definition: https://en.wikipedia.org/wiki/Unix_time)

# createFromFormat

```php
echo Carbon::createFromFormat('Y-m-d H:i', '2015-06-18 09:30', 'Europe/London')->format('Y-m-d H:i:s e');

Output:
```
2015-06-18 09:30:00 Europe/London
```
You asked for 9:30 in London and you get exactly what you ask, why would a conversion to an other timezone would happen if you didn't call `->setTimezone()` (or `->tz()`) to specify what other timezone you want?
```

**Comment by forxer** [comment]
So it was really me who was using the method argument the wrong way.

I thought this achieved the conversion but it's actually to specify the timezone of the date supplied to the method.

So I have to use `->setTimezone()` (or `->tz()`) to do the conversion. Ok I understand better, thanks for that.

There remains the problem with createFromTimestamp(); in fact I think I have the lag with the DST.

I'm going to close this issue. I might open another one if I can't find a solution regarding the createFromTimestamp() and the DST.

Merci beaucoup.
