### ISSUE TITLE
Time zone Europe/Kyiv to map to Europe/Kiev and vice versa

### ISSUE THREAD

**Issue by dinamic** [briannesbitt/Carbon#2657]
Hello,

I encountered an issue with the following code:
```php
var_dump(Carbon\Carbon::now()->tz('Europe/Kyiv'));
```

Carbon version: **2.32.2**

PHP version: **7.4, 8.1.9**

I expected to get:

```
The Carbon object with the Kyiv timezone set.
```

But I actually get:

```
An exception that tells me the timezone is not valid.

Warning: Uncaught InvalidArgumentException: Unknown or bad timezone (Europe/Kyiv) in /project/vendor/nesbot/carbon/src/Carbon/CarbonTimeZone.php:101
Stack trace:
#0 /project/vendor/nesbot/carbon/src/Carbon/Traits/Date.php(616): Carbon\CarbonTimeZone::instance('Europe/Kyiv', NULL)
#1 /project/vendor/nesbot/carbon/src/Carbon/Traits/Date.php(1519): Carbon\Carbon::safeCreateDateTimeZone('Europe/Kyiv')
#2 /project/vendor/nesbot/carbon/src/Carbon/Traits/Date.php(1507): Carbon\Carbon->setTimezone('Europe/Kyiv')
#3 php shell code(1): Carbon\Carbon->tz('Europe/Kyiv')
#4 {main}
  thrown in /project/vendor/nesbot/carbon/src/Carbon/CarbonTimeZone.php on line 101
```

According to the official time zones, this should be [supported](https://www.php.net/manual/en/timezones.europe.php
). However, I was able to find [this PHP bug](https://bugs.php.net/bug.php?id=80254), which leads me to believe the time zone would be renamed while the short-term solution should be to have an alias from `Europe/Kyiv` to `Europe/Kiev` and is a matter of mapping the values in the interim. It feels like Carbon could be handling this for the users.

Thanks!

**Comment by kylekatarnls** [comment]
Hello,

Actually PHP does not support it despites it's documented in this supported timezone section:
https://3v4l.org/vrKR5

And yes, I agree we could have an alias mapping as a work-around.

There is just a pitfall as devs would have to be careful that input `->tzName` would still give `Kiev` even if you passed `Kyiv`, this may lead to risky assertions.

**Comment by kylekatarnls** [comment]
On https://www.php.net/manual/en/timezones.php

It says:
> Note: This list is based upon the timezone database version 2022.2.

If I understand correctly it means the support for the Kyiv alias will depends on the timezone database installed on the the OS, which is to be installed/updated independently.

**Comment by kylekatarnls** [comment]
https://serverpilot.io/docs/how-to-update-the-php-timezonedb-version/
