### ISSUE TITLE
Non-static method DateTime::createFromFormat() cannot be called statically

### ISSUE THREAD

**Issue by niyonx** [briannesbitt/Carbon#2662]
Hello,

I received this error unexpectedly

```
 production.ERROR: Error: Non-static method DateTime::createFromFormat() cannot be called statically in vendor/nesbot/carbon/src/Carbon/Traits/Creator.php:596
```

Carbon version: 2.16

PHP version: v8.0

I expected to get:

no errors

But I actually get:

errors

Thanks!

**Comment by kylekatarnls** [comment]
Please provide the code you run to get this error.

**Comment by niyonx** [comment]
```
Carbon::createFromFormat('Y-m-d H:i:s', $startTime->format('Y-m-d').' '.$time);
```

What's weird is the method is actually static.

**Comment by kylekatarnls** [comment]
2.16 is no longer supported BTW, I suspect it's swapped number and you mean, 2.61?

If so I tried:
```php
$startTime = new Carbon();
$time = '12:00:00';

echo Carbon::createFromFormat('Y-m-d H:i:s', $startTime->format('Y-m-d').' '.$time);
```
But it works fine: https://play.phpsandbox.io/embed/nesbot/carbon?input=%3C%3Fphp%0D%24startTime%20%3D%20new%20Carbon%28%29%3B%0A%24time%20%3D%20%2712%3A00%3A00%27%3B%0A%0Aecho%20Carbon%3A%3AcreateFromFormat%28%27Y-m-d%20H%3Ai%3As%27%2C%20%24startTime-%3Eformat%28%27Y-m-d%27%29.%27%20%27.%24time%29%3B&sidebar=false&version=2.61.0

Please provide complete code allowing me to reproduce your error.

Else, note that: `(clone $startTime)->modify($time)` would also work just fine for your case (clone is not even needed if you `$startTime` is immutable.
