### ISSUE TITLE
Uncaught Exception: DateTime::__construct(): Failed to parse time string (16/10/2022) at position 0 (1): Unexpected character in

### ISSUE THREAD

**Issue by bilalmalkoc** [briannesbitt/Carbon#2672]
Hello. I got this error:
`Uncaught Exception: DateTime::__construct(): Failed to parse time string (16/10/2022) at position 0 (1): Unexpected character in`
PHP: 8.0.0
Carbon: 2.62.1  (Same in 2.61)

```
$carbon = new Carbon\Carbon();
\Carbon\Translator::get( 'fr_FR' )->setTranslations( [
	'formats' => [
		'LT' => 'H\hmm',
	],
] );

return $carbon::parse( '16/10/2022' )->locale( 'fr_FR' )->isoFormat( 'DD/MM/YYYY' );
```

**Comment by kylekatarnls** [comment]
Hello,

Slash-date is interpreted by `DateTime` as Month/Day/Year (US format), so 5/10/2022 will give you May 10th, not October 5th. and Month > 12 raises an error.

To use a format that is not one of the defaults, use `createFromFormat`:

```php
echo Carbon::createFromFormat( 'd/m/Y', '16/10/2022' )->locale( 'fr_FR' )->isoFormat( 'DD/MM/YYYY' );
```

Side note: `parse` is static, you should simply call `\Carbon\Carbon::parse()` or `$carbon = \Carbon\Carbon::class; $carbon::parse()` but you should avoid to call it from an object.
