### ISSUE TITLE
createFromFormat return type 

### ISSUE THREAD

**Issue by mad-briller** [briannesbitt/Carbon#2676]
Hello,

I encountered an issue with the following code:
```php
echo Carbon::createFromFormat();
```

Carbon version 2.62.1

PHP version: 8.1.10

The createFromFormat method is documented as returning a `false` value but the [docs](https://carbon.nesbot.com/docs/#api-instantiation) state:

>  Also, if there are errors with the format this function will call the DateTime::getLastErrors() method and then throw a InvalidArgumentException with the errors as the message.

I have never encountered a case where `createFromFormat` returned `false` instead of throwing, is it even possible? 

If not, it would be great to update the `@method` phpdoc to reflect that, as currently when using `Carbon::createFromFormat` with tools like PHPStan is prone to ignoring warnings for the return type.

Thanks for your time.

**Comment by kylekatarnls** [comment]
Hello 👋 

It can still return `false` by disabling strict mode (not recommended, it's there for backward compatibility):

```php
Carbon::useStrictMode(false);

var_dump(Carbon::createFromFormat('ydy', 'rt'));
```

In 3.0, the strict mode will always be `true` and not changeable and `false` returns will disappear.

**Comment by mad-briller** [comment]
thank you @kylekatarnls, i look forwards to 3.0!
