### ISSUE TITLE
Unknown or bad timezone (Europe/Kyiv)

### ISSUE THREAD

**Issue by jameswilson34** [briannesbitt/Carbon#2680]
Hello,

I encountered an issue with the following code:
```php
$now = Carbon::now()->setTimezone($geoip->timezone);
```

**Unknown or bad timezone (Europe/Kyiv)**

Carbon version: 2.62.1

PHP version: 8.1

I am getting the users timezone via:

`$geoip = geoip()->getLocation(getIp());
`

And only Europe/Kyiv is throwing the error.

Thanks!

**Comment by kylekatarnls** [comment]
Hello,

Your timezone DB (which is not a Carbon component) must be updated, see #2657
