### ISSUE TITLE
PHPStan macro doesn't support PHPStan >=1.7.0 with any arguments.

### ISSUE THREAD

**Issue by JonathanGawrych** [briannesbitt/Carbon#2685]
Hello,

This issue is very similar to https://github.com/briannesbitt/Carbon/issues/2629. While that issue was resolved in version 2.59.0, it only works for macros without any arguments. If you add an argument to the phpunit tests/PHPStan:
```php
Carbon::macro('foo', function ($someArg) {
    return $someArg;
});
```

Then you'll get the crash again with a slightly different error:
>Internal error: Internal error: `PHPStan\Reflection\Php\PhpMethodReflection::PHPStan\Reflection\Php\{closure}()`: Argument <span>#</span>1 (`$reflection`) must be of type
`PHPStan\BetterReflection\Reflection\Adapter\ReflectionParameter`, `ReflectionParameter` given in file /Volumes/code/external/Carbon/tests/PHPStan/Fixture.php

Carbon version: 2.62.1
PHP version: 8.1.9
PHPStan version: 1.8.10 (but it seems like it fails for anything >=1.7.0)

Thanks!

**Comment by kylekatarnls** [comment]
Hello, fix has been merged, can you retry with `composer require "nesbot/carbon:2.x-dev as 2.63.0"`?

**Comment by JonathanGawrych** [comment]
Yep, now it works without PHPStan complaining. Thanks so much!
