### ISSUE TITLE
[Translation tool] es

### ISSUE THREAD

**Issue by guestpectacular** [briannesbitt/Carbon#2686]
|English|es|comments|
|--|--|--|
|Mon|lun.|Lun|
|Mo|lu|Lu|
|Tuesday|martes|Martes|
|Tue|mar.|Mar|
|Tu|ma|Ma|
|Wednesday|miércoles|Miércoles|
|Wed|mié.|Mie|
|We|mi|Mi|
|Thursday|jueves|Jueves|
|Thu|jue.|Jue|
|Th|ju|Ju|
|Friday|viernes|Viernes|
|Fri|vie.|Vie|
|Fr|vi|Vi|
|Saturday|sábado|Sábado|
|Sat|sáb.|Sab|
|Sa|sá|Sa|
|Sunday|domingo|Domingo|
|Sun|dom.|Dom|
|Su|do|Do|
|January|enero|Enero|
|Jan|ene|Ene|
|February|febrero|Febrero|
|Feb|feb|Feb|
|March|marzo|Marzo|
|Mar|mar|Mar|
|April|abril|Abril|
|Apr|abr|Abr|
|May|mayo|Mayo|
|May|may|May|
|June|junio|Junio|
|Jun|jun|Jun|
|July|julio|Julio|
|Jul|jul|Jul|
|August|agosto|Agosto|
|Aug|ago|Ago|
|September|septiembre|Septiembre|
|Sep|sep|Sep|
|October|octubre|Octubre|
|Oct|oct|Oct|
|November|noviembre|Noviembre|
|Nov|nov|Nov|
|December|diciembre|Diciembre|
|Dec|dic|Dic|

----
All your translations are localized on lowercase, doesn't keep the same syntax as english translation. And I'm breaking my head trying to overwrite your language files with my code, also, it's kinda weird to have a short month name instead "Jan" => "Ene" into "ene." doesn't make any sense.

**Comment by kylekatarnls** [comment]
From https://carbon.nesbot.com/contribute/translate/ just before the form, there is this warning, explaining about the case, which is not a matter of syntax, but an actual grammar rule of the English:
> Warning, do not uppercase the first letter if it's not required, days/months are always uppercase in English, so "Monday" is written this way even in a sentence like "See you Monday", please translate the following as if it could be in the middle of such sentences. Short versions are used in short date formats and minimalist days are used calendar headings and such custom usages.

So the first point is: why are you trying to uppercase the Spanish via translations, as it's grammatically wrong to uppercase days and month in Spanish? If you need it because it's a title or the start of a sentence, you shouldn't hack the translation, you just need to use `ucfrist()` around the the resulted string.

**Comment by kylekatarnls** [comment]
Hello,

I checked other source for "ene", it's in sync with CLDR:
https://github.com/unicode-org/cldr/blob/main/common/main/es.xml#L1862
And moment.js:
https://github.com/moment/moment/blob/develop/locale/es.js#L15

Which are what we tend to be compatible with.

As CLDR is also a project dedicated to the translation, it's supposed to be reviewed by many native speakers 🤔 

But mistakes can still pass through. you can reach https://cldr.unicode.org/ to submit an issue.
