### ISSUE TITLE
Pluralization problems with locales

### ISSUE THREAD

**Issue by dakira** [briannesbitt/Carbon#269]
I'm sure this is true for multiple languages, here's a German example:

The singular of year is Jahr, the plurar is Jahre. However, watch these translations:

1 year after - 1 Jahr später
2 years after - 2 Jahre später

So far so good. *after* and *before* are okay. But:

in 1 year - in 1 Jahr
in 2 years - in 2 Jahr**en**
2 years ago - vor 2 Jahr**en**

So the plural for year is a different one in the *ago* and *from_now* context. I'm pretty sure it's the same for Russian.

**Comment by tomhorvat** [comment]
Most of the slavic languages have the same problem!

**Comment by dakira** [comment]
@tomhorvat so for other slavic languages, is it also one pluralization for *after* and *before* and another one for *ago* and *from_now*?

**Comment by tomhorvat** [comment]
Well, it depends on the number.

Please, see timeago.js croatian localization:

https://github.com/rmm5t/jquery-timeago/blob/master/locales/jquery.timeago.hr.js

**Comment by dakira** [comment]
laravel-date seems to have solved this problem by having multiple pluralizations and seperate pluralizations for diffs:

https://github.com/jenssegers/laravel-date/blob/master/src/lang/de/date.php
https://github.com/jenssegers/laravel-date/blob/master/src/lang/sl/date.php

**Comment by briannesbitt** [comment]
Ok, we can tackle in a similar manner, makes sense.
