### ISSUE TITLE
Enchacement: LL without the year - and others sugestions

### ISSUE THREAD

**Issue by lwmirkk** [briannesbitt/Carbon#2690]
Hello,

My sugestion is to have a new macro format / template like LL, but without the year:

Today:
```
LL -> January 5, 2017
LLL -> January 5, 2017 5:04 PM
```

These suggestions below seem to be better to be standardized with LT and LTS macro-formats (T = hour/ minute? - S = seconds?)
So, my sugestion:
```
LL -> January 5
LLT -> January 5, 2017 5:04 PM
LLTS -> January 5, 2017 5:04:05 PM
LLL -> January 5, 2017 
```

This changes sugestion is just a sugestion, but the main purpose is to add the macro format of day and month alone, without the year.
`January 5`

P.S. : I can't use just : 
`MMMM D`
because of different patterns in different languages.
In PT_BR as example would be: 
`D [de] MMMM`

Thanks a lot! =)

**Comment by kylekatarnls** [comment]
Hello,

`LL` can't become `January 5` this would be a breaking change: application currently using it will unexpectedly lose the year when they'll upgrade.

However, on your side you can get the format and remove the year from it:

```php
$code = 'LLL';
$now = Carbon::now();
// To set a different language:
// $now = Carbon::now()->locale('pt_BR');
$formats = $now->getIsoFormats();

// Optional preg_replace_callback part to get lowercase formats (short day/month) formats "ll", "lll", "llll"
// If you need only upper case formats, you can just use $format = $formats[$code];
$format = $formats[$code] ?? preg_replace_callback(
    '/MMMM|MM|DD|dddd/',
    function ($code) {
        return mb_substr($code[0], 1);
    },
    $formats[strtoupper($code)] ?? ''
);

echo $format . "\n" . $now->isoFormat($code) . "\n\n";

$format = preg_replace('/(\[[^[]+]|[ \/,-])+y+/i', '', $format);

echo $format . "\n" . $now->isoFormat($format) . "\n\n";
```

Result in English:
```
MMMM D, YYYY h:mm A
October 30, 2022 9:17 PM

MMMM D h:mm A
October 30 9:17 PM
```

With pt_BR:
```
D [de] MMMM [de] YYYY [às] HH:mm
30 de outubro de 2022 às 21:17

D [de] MMMM [às] HH:mm
30 de outubro às 21:17
```

With pt_BR and code being LL:
```
D [de] MMMM [de] YYYY
30 de outubro de 2022

D [de] MMMM
30 de outubro
```

It would be possible to add new codes to return those, but not to change the behavior of existing codes, also this RegExp `(\[[^[]+]|[ \/,-])+y+/i` might remove properly the year in most of the case, but I can't guarantee it will be the best for all the 850 locales. What is the best way to give a date without the year is not an info we already have, so this would require native speaker of every language to check it, or an other reliable source, maybe CLDR has it.
