### ISSUE TITLE
[Translation tool] es_ES

### ISSUE THREAD

**Issue by gam04** [briannesbitt/Carbon#2692]
## Additional fixes
First => primer
Second => segundo
Third => tercer
Fourth => cuarto
Last => último

----
Currently there is no translation for Ordinal Numbers format.

Example:
`[EN_US] First Sunday of november`
`[ES_ES] Primer domingo de noviembre`

---- 
I would like to contribute to this but i don´t know where to start.

**Comment by kylekatarnls** [comment]
Thanks for the proposal, it will be implemented via #2693. The pitfall is that any new feature involving new translations means that each language supports the feature only once translations is added, so for now, it will be it/fr/de/es/pt/en only.
