### ISSUE TITLE
diffInHours returning incorrect number for dates across November 2022

### ISSUE THREAD

**Issue by flytedan** [briannesbitt/Carbon#2699]
Hello,

I encountered an issue with the following code:
```php
echo Carbon\Carbon::parse('2022-11-01 00:00:00')->diffInHours(Carbon\Carbon::parse('2022-11-29 23:59:59')); // Outputs 695
echo Carbon\Carbon::parse('2022-11-01 00:00:00')->diffInHours(Carbon\Carbon::parse('2022-11-30 23:59:59')); // Also Outputs 695

// I'm doing this in an environment where the timezone is set to America/Chicago. 
```

Carbon version: 2.62.1

PHP version: 8.0.21

I expected to get:

```
719
```

But I actually get:

```
695
```

NOTE: This only appears in PHP 8.0. It seems the issue is resolved in PHP 8.1, so maybe a bug in PHP 8.0 or something tied to behavior of the older version?

Thanks!

**Comment by kylekatarnls** [comment]
Hello, yes it's a PHP bug:
https://3v4l.org/tYnRA

Be warned that PHP >= 8.1 is better, but it's still quite unreliable to make calculation with non-UTC timezones, mostly timezones that have DST (summer/winter time), if you have a DST change in the interval, you'll get many unexpected results.

For instance here 719 is the "visual" difference, but the real time between both is 720 as you have +1 for the DST change.

To get real-time difference always work with UTC dates:

```php
echo Carbon::parse('2022-11-01 00:00:00 America/Chicago')->tz('UTC')->diffInHours(Carbon::parse('2022-11-29 23:59:59 America/Chicago')->tz('UTC')) . "\n";
echo Carbon::parse('2022-11-01 00:00:00 America/Chicago')->tz('UTC')->diffInHours(Carbon::parse('2022-11-30 23:59:59 America/Chicago')->tz('UTC')) . "\n";
```
