### ISSUE TITLE
startofWeek does not give the correct date

### ISSUE THREAD

**Issue by rabol** [briannesbitt/Carbon#2706]
Hello,

I encountered an issue with the following code:
```php
debug(now()->year(2022)->week(47)->startofWeek(Carbon::MONDAY));
```

Carbon version: 2.63.0

PHP version: 8.1.12

I expected to get:

```
2022-11-21 00:00:00.0 UTC (+00:00)
```

But I actually get:

```
2022-11-14 00:00:00.0 UTC (+00:00)
```

Thanks!

**Comment by rabol** [comment]
my mistake, had the wrong locale

**Comment by kylekatarnls** [comment]
Yup :)

```php
echo Carbon::now()->locale('fr_FR')->year(2022)->week(47)->startofWeek() . "\n";
echo Carbon::now()->year(2022)->week(47)->startofWeek(Carbon::MONDAY) . "\n";
```

**Comment by kylekatarnls** [comment]
When you pass a locale you don't need to enforce `Carbon::MONDAY` as the locale has the info.

And when calling `->week(47)` the week this 47 refers to will differ depending on the the way to count,
some locales use the rule:
> Week 1 is the first week with any number of days in it
some locales:
> Week 1 is the first week with at least 4 days in it
