### ISSUE TITLE
createFromFormat return type must be static

### ISSUE THREAD

**Issue by julien-fontaine** [briannesbitt/Carbon#2720]
Hello,

I encountered an issue with the following code:
```php
echo Carbon::createFromFormat($format, $date);
echo CarbonImmutable::createFromFormat($format, $date);
```

Carbon version: **2.63.0**

PHP version: **8.1.13**

When extending the `Carbon` or `CarbonImmutable` class and using their `createFromFormat` method, I get an instance of the child class. However, the PHPDocs inside these classes describe that they return a `Carbon`/`CarbonImmutable` instance, instead of returning `static`. This causes static analysis tools to fail.

The PHPDocs from `CarbonInterface` and from the trait `\Carbon\Traits\Creator`, however, describe the correct type `static`.

`createFromFormat`'s PHPDocs from `Carbon` and `CarbonImmutable` should be fixed.

Thanks!

**Comment by kylekatarnls** [comment]
Thank you, this was initially a work-around for #1914 but I tried on PhpStorm 2022.3 and it handles it correctly now.
