### ISSUE TITLE
PHP Less than 8 Issue. Please help

### ISSUE THREAD

**Issue by w3guy** [briannesbitt/Carbon#2722]
Doesn't work with PHP less than 8.

Fatal error: Uncaught Error: Call to undefined function str_contains() in /home/yyy/xxxx/../vendor/nesbot/carbon/src/Carbon/Traits/Creator.php:69

**Comment by w3guy** [comment]
@kylekatarnls can you help look into this? Consider using `strpos()` instead.

**Comment by kylekatarnls** [comment]
`str_contains` is provided by [symfony/polyfill-php80](https://github.com/briannesbitt/Carbon/blob/master/composer.json#L46) when PHP < 8.

We have many occurrences of it in the code.

Please ensure `symfony/polyfill-php80` and your autoload uses the correct PHP version so it include it.

**Comment by kylekatarnls** [comment]
Also line 69 does not match any `str_contains` with any version released this year.

Please don't remove the issue pattern and provide the info, giving exact version of carbon and PHP, and the steps to reproduce a bug are needed for any issue to be investigated.

**Comment by w3guy** [comment]
@kylekatarnls the issue here is, we are using phpscoper to namespace our dependency. Because of the backslash in str_contain call, it doesn't work.

After scoping, symfony PHP 8 polyfill becomes


<img width="493" alt="image" src="https://user-images.githubusercontent.com/4140659/206211754-3b29cd48-5a5a-4cb0-a471-39a1c5a1fcd0.png">

**Comment by kylekatarnls** [comment]
Hello, did you check php-scoper documentation?
https://github.com/humbug/php-scoper/blob/main/docs/further-reading.md#polyfills

In any case, you should refer to them, we shouldn't change our code to support a third-party tool that is modifying the libvrary code. We can't provide guarantee if our code or the composer autoload is re-processed.

**Comment by w3guy** [comment]
> Hello, did you check [php-scoper documentation about polyfills](https://github.com/humbug/php-scoper/blob/main/docs/further-reading.md#polyfills)?
> 
> In any case, you should refer to them, we shouldn't change our code to support a third-party tool that is modifying the library code. We can't provide guarantee if our code or the composer autoload is re-processed.

This worked. Thank you.
