### ISSUE TITLE
Incorrect operation type

### ISSUE THREAD

**Issue by yarscript** [briannesbitt/Carbon#2723]
Hello,

I encountered an issue with the following code:
https://github.com/briannesbitt/Carbon/blob/107ca469b2b6ef6e0b0fc6a6edbb92cbfaf282d9/src/Carbon/Traits/Units.php#L69

Carbon version: 
```json
{
    "name": "nesbot/carbon",
    "version": "2.64.0",
}
```

PHP version: 
```sh
PHP 8.2.0 (cli) (built: Dec  9 2022 16:19:06) (NTS)
```

I expected to get:

```php
   gettype($value); // 'int'
```

But I actually get:

```php
   gettype($value) // 'string'
```

<img width="1340" alt="image" src="https://user-images.githubusercontent.com/26656665/206924836-f395b451-dcad-4a74-a8e9-913ba35b46fe.png">

Thanks!

**Comment by yarscript** [comment]
#2724

**Comment by yarscript** [comment]
Please make sure that is it correct.
Thanks!

**Comment by kylekatarnls** [comment]
Hello, I tried to add a test to reproduce your issue: https://github.com/briannesbitt/Carbon/pull/2726/files but this test is not failing with  PHP 8.2.

Can you please provide a minimum code chunk to trigger this error? So I'll add it in unit tests and it will ensure the fix we merge actually fix it and will prevent regression.

Thanks 🙏

**Comment by kylekatarnls** [comment]
When I try it in PHP 8.2 no error is thrown, it just cast implicitly:
```php
var_dump($value); // "8"
$value *= static::SECONDS_PER_MINUTE;
var_dump($value); // 480
```

I can only trigger the error if I pass an invalid string such as `"rr"` but in this case we clearly want to have an error, we should definitely not silently convert it to `0` which is what happen if we add `(int)` or `(float)` explicit cast.

**Comment by yarscript** [comment]
@kylekatarnls 
In my case I received empty string there but anyway your're right - silently type converting is not for this case.
Thanks a lot for your time!
