### ISSUE TITLE
Installing Carbon without loading language files

### ISSUE THREAD

**Issue by w3guy** [briannesbitt/Carbon#2730]
Is it possible to install and use Carbon while not including and/or loading the language files in Lang folder?

**Comment by kylekatarnls** [comment]
Hello, I think it should be possible to fork the repo, then in the fork, create some `noi18n` branch and adding to `.gitattributes` the following line:

```
/src/Carbon/Lang export-ignore
```

should do the trick. Then would need to add to your application **composer.json**:
```json
"repositories": [
    {
        "type": "vcs",
        "url": "https://github.com/w3guy/Carbon.git"
    }
],
"require": {
    ...
    "nesbot/carbon": "dev-noi18n"
```

Ideally the branch should be rebased on master after each release, GitHub API could be used to list tags to automate this part with a script: https://api.github.com/repos/briannesbitt/Carbon/tags

**Comment by w3guy** [comment]
I think I can live with the lang files 😊
