### ISSUE TITLE
Huge phpdoc make phpstan analysis slow

### ISSUE THREAD

**Issue by staabm** [briannesbitt/Carbon#2733]
Hello,

projects which use this package and phpstan get statically analysed really slow.
See https://twitter.com/_DevNIX/status/1605594388687597570

I encountered an issue with the following code:

```php
echo Carbon::parse('2018-06-01')->subDay()->month;
```

 It's because of this huge PHPDoc: Carbon.php
See https://twitter.com/OndrejMirtes/status/1605660709106262016

could the magic stuff be declared in code instead?

Carbon version: **2.64.0**

PHP version: **any**

I expected to get:

```
Fast static analysis
```

But I actually get:

```
Phpstan analysis get slow
```

relevant phpstan upstream bug: https://github.com/phpstan/phpstan/issues/8349

Thanks!

**Comment by kylekatarnls** [comment]
Hello,

Issue seems well identified on https://github.com/phpstan/phpstan/issues/8349 the PHPDoc is integrally parsed as soon as you call 1 method. If it would be:
- Step 1: loading the list of method names this takes < 2 milliseconds with Carbon class using `preg_match_all('/@method\s+(?:[^(]+\s+)+([a-zA-Z]+)\(/', $c->getDocComment(), $matches, PREG_PATTERN_ORDER);` of course it's oversimplified, but even we more complex and various PHPDoc syntaxes, it would be possible to have this step fast. Actually it shouldn't even make a significant difference with actual methods.
- Step 2: would be triggered lazily (only when a method is in the code) such as `addMinutes`, so when it's in the code and static analysis need to know params and return type, only then it load and parse the definition.

And I guess both should be cached. The list of the methods can be file-saved as long as PHPDoc content does not change (hash check would be enough) and method definition can be save (it is already I think) in memory during a given project analysis.

Also there is no easy way to "could the magic stuff be declared in code instead", it uses magic methods so units and operations can be abstracted. This is a huge refactor that would probably have breaking changes implications.

@ondrejmirtes just acknowledged it, so let PHPStan team some time to investigate.

**Comment by staabm** [comment]
thx for the feedback. 

I am aware of the phpstan issue since I am contributing to phpstan-src a lot.

my goal of this issue here was to make you aware of said problem, since it hurts the DX of users of your library.
I don't see a phpstan fix coming in the near future, therefore I figured reporting it here might make some progress for the library users in the meantime.

I am also fine with waiting for the phpstan fix as we don't use Carbon in one of our projects.

**Comment by ondrejmirtes** [comment]
As the PHPStan creator, I agree this is a problem on PHPStan's side - we can't force library authors to refactor because of a performance problem in a certain tool.

Arguably it's also easier to fix this on PHPStan's side than to refactor Carbon.
