### ISSUE TITLE
Unknown or bad timezone (America/Ciudad_Juarez)

### ISSUE THREAD

**Issue by foremtehan** [briannesbitt/Carbon#2736]
Hello,

I encountered an issue with the following code:

```php
echo Carbon::now('America/Ciudad_Juarez');
```

Carbon version: ^2.62.1

PHP version: 8.1.13

I expected to get:

```
CarbonInterface
```

But I actually get:

```
Carbon\Exceptions\InvalidFormatException : Unknown or bad timezone (America/Ciudad_Juarez)
 /var/www/html/vendor/nesbot/carbon/src/Carbon/Traits/Creator.php:89
 /var/www/html/vendor/nesbot/carbon/src/Carbon/Traits/Creator.php:252
```

I copied the timezone from php doc https://www.php.net/manual/en/timezones.america.php

**Comment by kylekatarnls** [comment]
Hello,

This error comes from PHP itself, you can see you get exactly the same error with `DateTime`:
https://3v4l.org/WRSmT

Carbon is not doing anything with the list of supported timezones. It's all come from the [timezonedb](https://pecl.php.net/get/timezonedb) version installed on your machine.

Check the comments on this issue:
https://github.com/briannesbitt/Carbon/issues/2657#issuecomment-1230131329
