### ISSUE TITLE
when i input carbon month February but its return mar

### ISSUE THREAD

**Issue by alif989** [briannesbitt/Carbon#2737]
Hello,

I encountered an issue with the following code:

```php
Carbon::parse('February')->format('M');
```

Carbon version: **PUT HERE YOUR CARBON VERSION (exact version, not the range)**

PHP version: **PUT HERE YOUR PHP VERSION**

I expected to get:

```
Feb
```

But I actually get:

```
Mar
```

Thanks!

**Comment by kylekatarnls** [comment]
Hello,

This comes directly from PHP parent class:

```php
echo (new DateTime('February'))->format('M');
```
https://3v4l.org/4M2nr

It uses "now" as the start point and wants to keep the same day number so 29 then it does not find it in February and overflow to March.

The solution is to use an explicit start of point that does not trigger overflow such as the start of the month:
```php
echo Carbon::now()->startOfMonth()->modify('February')->format('M');
```
