### ISSUE TITLE
diffForHumans broken after commit 0f0a245

### ISSUE THREAD

**Issue by michaelm111** [briannesbitt/Carbon#2744]
Hello,

I encountered an issue with the following code:

```php
\Carbon\Carbon::yesterday()->diffForHumans([
  'syntax' => \Carbon\CarbonInterface::DIFF_ABSOLUTE,
  'parts' => 3,
  'skip' => 's',
]);
```

Carbon version: 2.64.0

PHP version: 7.4.33

I expected to get:

```
1 day 16 hours 57 minutes
```

But I actually get:

```
Uncaught Exception TypeError: "Argument 3 passed to Carbon\Carbon::diffAsCarbonInterval() must be of the type array, string given, called in /vendor/nesbot/carbon/src/Carbon/Traits/Difference.php on line 847" at /vendor/nesbot/carbon/src/Carbon/Traits/Difference.php line 151

```

Thanks!

**Comment by michaelm111** [comment]
The workaround is to pass 'skip" as array (['s']), however, documentation states that skip can be array of strings or single string.  This was working before version 2.64.0.

**Comment by kylekatarnls** [comment]
`string` is indeed intended to be supported. [Patch 2.64.1 released with a fix for it](https://github.com/briannesbitt/Carbon/releases/tag/2.64.1)

Test also added to make sure it remains supported.

Thanks for the report 🙏
