### ISSUE TITLE
isLongYear() is not determined from the ISO 8601 year

### ISSUE THREAD

**Issue by PatrickSJ** [briannesbitt/Carbon#2746]
Hello,

I encountered an issue with the following code:

```php
$date_1 = Carbon::parse('December 30, 2019');
$date_2 = Carbon::parse('January 1, 2020');

echo $date_1->isoFormat('G-W-E') . PHP_EOL;
echo $date_2->isoFormat('G-W-E') . PHP_EOL;

echo $date_1->isLongYear() ? 'true' : 'false' . PHP_EOL; // false, should be true if this based on the ISO year
echo $date_2->isLongYear() ? 'true' : 'false' . PHP_EOL; // true
```

Carbon version: 2.62.1
PHP version: 8.1.7

I expected to get true for both as the above dates are in ISO week 1 of 2020.  But `Carbon::parse('December 30, 2019')->isLongYear() ` is `false` while `Carbon::parse('January 1, 2020')->isLongYear()` is `true`.

Thanks!

**Comment by kylekatarnls** [comment]
Hello,

I see the point, it makes sense. But we will have a regression for users doing `Carbon::create(2016)->isLongYear()`. It's currently returning `false` and will return `true` (because it's January 1st) if we switch to ISO year.

I will check what I could do.

Meanwhile, you can:
```php
Carbon::create($date_1->isoWeekYear, 12, 28, 0, 0, 0, $date_1->tz)->weekOfYear === 53
```

Thanks.
