### ISSUE TITLE
Source directory /var/www/vendor/nesbot/carbon has uncommitted changes.

### ISSUE THREAD

**Issue by lav45** [briannesbitt/Carbon#2747]
```bash
~$ composer update --prefer-dist
Loading composer repositories with package information                                                                                                  Info from
Updating dependencies
....

In VcsDownloader.php line 267:
                                                                           
  Source directory /var/www/vendor/nesbot/carbon has uncommitted changes.  
```

it seems to me that this is due to the fact that you are doing `git push --force` to your repository

I solve the problem this way, but in my opinion it is not correct
```bash
~$ rm -rf vendor/nesbot/carbon
```

**Comment by kylekatarnls** [comment]
This can only happen if the folder was modified after installation.

Also we don't do --force push on the master branch (wich is the one used by composer) but anyway this is irrelevant, composer get commit hash and is able to jump from any version to any version no matter how the code were pushed.
