### ISSUE TITLE
CarbonPeriod start and end date are not of the expected type when using setDateClass(CarbonImmutable::class)

### ISSUE THREAD

**Issue by Naghal** [briannesbitt/Carbon#2755]
Hello,

I encountered an issue with the following code:

```php
<?php
$period = CarbonPeriod::create('2023-01-17 08:00:00', '2023-01-17 12:00:00')
    ->setDateClass(CarbonImmutable::class);

echo get_class($period->start_date);
```

Carbon version: **2.64.1**

PHP version: **8.1.12**

I expected to get:

```
Carbon\CarbonImmutable
```

But I actually get:

```
Carbon\Carbon
```

Thanks!

**Comment by kylekatarnls** [comment]
Hello, `setDateClass()` is for the class of the iteration items. But we definitely need a way to have start/end immutable too. 👍

**Comment by kylekatarnls** [comment]
On the next release (or on dev-master), a new `CarbonPeriodImmutable` class is available:
```php
$period = CarbonPeriodImmutable::create('2023-01-17 08:00:00', '2023-01-17 12:00:00');
```
It defaults everything to `CarbonImmutable` and it also is immutable itself (i.e. `->setStartDate()` and the like return new objects).
