### ISSUE TITLE
In Carbon 2.65, the warning Symfony\Contracts\Translation\TranslatorInterface.php): Failed to open stream is displayed.

### ISSUE THREAD

**Issue by mohamadshadkaminia** [briannesbitt/Carbon#2757]
Hello,

I get the following error when using it

```php
Warning: include_once(C:\wamp64\www\****/Symfony\Contracts\Translation\TranslatorInterface.php): Failed to open stream: No such file or directory in C:\wamp64\www\****\init.php on line 6
```

Carbon version: **2.65**

PHP version: **8.0.13**

init.php codes(using autoload):

```php
<?php
session_start();
include_once "vendor/autoload.php";
spl_autoload_register(function ($Class_name) {
    $File = __DIR__."/".$Class_name . '.php';
    include_once $File;
});

```
Wrong addressing in the following path caused the above warning 
```php
vendor/nesbot/Carbon/Traits/Localization.php

```

In lines 26, 27, 30, 31, the following addresses:
```php
Symfony\\Contracts\\Translation\\TranslatorInterface
Symfony\\Component\\Translation\\TranslatorInterface
```
Replace them with the following addresses:
```php
Symfony\\translation-contracts\\TranslatorInterface
```
I think an addressing error has occurred
Warning: Changing the addresses mentioned may cause carbon performance errors, the information provided is to help people who have a similar problem.

**Comment by kylekatarnls** [comment]
Hello,

We simply don't know in advance if the class exists or not as it depends on the Symfony version installed and it keep backward compatibility with older version, in next major version when dropping them, those checks will no longer be needed. But just changing the address will break this test so the Symfony compatibility too.

Performance wise, I guess the best work-around would be to add this in your own code:
```php
class_alias(
    'Symfony\\Contracts\\Translation\\TranslatorInterface',
    'Symfony\\Component\\Translation\\TranslatorInterface'
);
```

(after autoload or before you start using Carbon)

However, this kind of autoload is a wrong usage IMO.

First, when using composer, you should use only the composer autoload and make your own app using it too not registering an other custom autoload.

Second, when using `spl_autoload_register` it's not safe to assume the passed file always exists, it's actually prevent any usage of `class_exists` or `interface_exists` and I don't think one should expect all their dependencies to ban those methods.

But you can easily prevent this to happen by checking file exists:
```php
spl_autoload_register(function ($Class_name) {
    $File = __DIR__."/".$Class_name . '.php';

    if (file_exists($File)) {
        include_once $File;
    }
});
```
Or simply `@include_once $File;`

Alternatively, you can first check that `$Class_name` is in your application namespace:
```php
spl_autoload_register(function ($Class_name) {
    if (!str_starts_with($Class_name, 'MyAppNamespace\\') {
        return;
    }

    $File = __DIR__."/".$Class_name . '.php';

    include_once $File;
});
```

Scoping your application to a given namespace and make your autoload only handling this one is way better for isolation, but it's even better to that with composer itself (use psr-4 autoload in your composer.json for instance).

Thanks.
