### ISSUE TITLE
weekOfYear property doesn't account for Leap Years

### ISSUE THREAD

**Issue by JustinLawrenceMS** [briannesbitt/Carbon#2758]
Hello,

I encountered an issue with the following code:

```php
echo Carbon::createFromDate('2024-12-31')->weekOfYear;
```

Carbon version: 2.64.0

PHP version: 8.1.2-1ubuntu2.9

I expected to get:

```
53
```

But I actually get:

```
1
```

Thanks!

**Comment by kylekatarnls** [comment]
Hello,

It has nothing to do with leap year, `Carbon::createFromDate('2024-12-30')->weekOfYear` is also `1` and so does `Carbon::createFromDate('2025-12-31')->weekOfYear`.

As per documentation, this property returns the ISO-8601 week number of year and we follow the norm:
https://en.wikipedia.org/wiki/ISO_week_date

It states that the same week cannot belongs to 2 different years, and when a week has days in 2 different years (such as this one starting on 2024-12-30 and ending 2025-01-05) it is assigned to the years where it has the more days, or equivalent way of saying it:

> The first week of the year, hence, always contains 4 January.

Side note: week starts on Monday as per ISO-8601 (which is the most common worldwide)
