### ISSUE TITLE
Why does createFromFormat() not say it accepts CarbonTimeZone?

### ISSUE THREAD

**Issue by JohnnyWalkerDigital** [briannesbitt/Carbon#2765]
Hello,

I encountered an issue with the following code:
```php
        $timezone = CarbonTimeZone::create('America/New_York');
        $announceDateTime = Carbon::createFromFormat('Y-m-d H:i:s', '2022-12-01 08:00:00', $timezone);
```

Carbon version: 2.66.0

PHP version: 8.0.27

PHPStan (correctly) throws an error with the above code because the Carbon library states that `createFromFormat()` only accepts timezones in `string|DateTimeZone|null` format. ([Line 505](https://github.com/briannesbitt/Carbon/blob/master/src/Carbon/Carbon.php#L505).) While CarbonTimeZone extends DateTimeZone, it is still a different object.

Why doesn't Carbon support its own timezone object? (Note: The same is true for `setTimezone()`.)

Thanks!

**Comment by kylekatarnls** [comment]
PHPStan is wrong if it does that. Any method accepting A-class accepts any class that extends it, it's a basic concept of the inheritance, children can substitute the parent.

That's why for instance you can use Carbon anywhere a DateTime is expected.

**Comment by kylekatarnls** [comment]
PHPStan is wrong if it does that. Any method accepting A-class accepts any class that extends it, it's a basic concept of the inheritance, children can substitute the parent.

That's why for instance you can use Carbon anywhere a DateTime is expected.

And the type is correct since we support any DateTimezone, not just CarbonTimezone, we won't restrict to it because we have no reason to and it's way better for interoperability.

**Comment by kylekatarnls** [comment]
Indeed I was able to reproduce on a real project but not with an equivalent minimum reproduction of a `@method` annotation in the sandbox of phpstan, so I don't know yet why at this specific point PHPStan complains. But it shouldn't (also it doesn't on level 8 so it's somethinglikely in level 9 implementation).

And yes, `Carbon|DateTimeInterface` is redundant. It's not wrong nor shouldn't cause any issue, but it's indeed strictly equivalent to just `DateTimeInterface`.

**Comment by JohnnyWalkerDigital** [comment]
Thanks, seems like a big whole in PHPStan's logic! (I'm pretty sure I get that error on Level 7, but whatever the level it seems odd.) I'll flag it there and see what the response is.

**Comment by JohnnyWalkerDigital** [comment]
Not sure why this is behaving differently... Would welcome your attempt, @kylekatarnls if you're inclined to try!

https://phpstan.org/r/d6e758a3-37d1-449d-a93b-34bbbeafcb32

**Comment by ondrejmirtes** [comment]
There's no problem with PHPStan, nor Carbon, see my comment: https://github.com/phpstan/phpstan/issues/8852#issuecomment-1421373180

**Comment by JohnnyWalkerDigital** [comment]
> There's no problem with PHPStan, nor Carbon, see my comment: [phpstan/phpstan#8852 (comment)](https://github.com/phpstan/phpstan/issues/8852#issuecomment-1421373180)

Thank you for your assistance with this!

I do think Carbon should support its own CarbonDateTimeZone object without needing to separately account for `false` returns (and so manually implementing your own Exceptions every time), but there's no question that you lasered onto the issue. Thanks again.

**Comment by kylekatarnls** [comment]
I simply recommend to use:
```php
$timezone = new CarbonTimeZone('America/New_York');
```
So it's all clear for static analyze and no need for exception, `?:` operator or whatever.

I may also make `createFromFormat` accept `false` as it would be consistent with other methods.
