### ISSUE TITLE
Iran cancels daylight saving time

### ISSUE THREAD

**Issue by ealdev** [briannesbitt/Carbon#2774]
Hello,

I encountered an issue with the following code:

```php
echo Carbon::now()->setTimezone('Asia/Tehran');
```

Carbon version: 2.66.0

PHP version: 8.2.4

I expected to get:

```
2023-03-25 16:23:06.663893 Asia/Tehran (+03:30)
```

(Iran cancels daylight saving time, https://time.is/time_zone_news/iran_cancels_daylight_saving_time)

But I actually get:

```
2023-03-25 17:23:06.663893 Asia/Tehran (+04:30)
```

Thanks!

**Comment by kylekatarnls** [comment]
Hello,

Carbon does not handle anything for the timezone it all rely on https://www.php.net/manual/en/class.datetimezone.php which in turns rely on the timezonedb https://pecl.php.net/package/timezonedb

You'll need to update your servers to use a timezone DB that includes this change or to manually edit it. Depending on the notice period governments let, updates might not be done in time, and if the version of your timezone DB is oldest than the announcement of the change, it can't be taken into account.

Thanks.

**Comment by ealdev** [comment]
Thank you very much.
