### ISSUE TITLE
Incorrect date generation for specific format to createFromFormat method

### ISSUE THREAD

**Issue by wislert** [briannesbitt/Carbon#2779]
Hello,

I encountered an issue with the following code:

```php
\Carbon\Carbon::setTestNow(
    \Carbon\Carbon::create(2023, 3, 31)
);

$periods = [
    '01-2023',
    '02-2023',
    '03-2023',
    '04-2023',
    '05-2023',
];

foreach($periods as $period) {
    $date = \Carbon\Carbon::createFromFormat('m-Y', $period)->startOfMonth();
    var_dump("{$date->format("Y-m-d")}");
}
```

Carbon version: **2.66.0**

PHP version: **8.1.17**

I expected to get:

```
2023-01-01
2023-02-01
2023-03-01
2023-04-01
2023-05-01
```

But I actually get:

```
2023-01-01
2023-03-01
2023-03-01
2023-05-01
2023-05-01
```

Obviously, when the format does not specify days, Carbon uses the current day of the month, and we get an offset to the next month if the generated date is not valid. However, this behavior seems unclear to me. What if, in a situation where the day is not specified in the format, Carbon will use the first day of the month?

**Comment by kylekatarnls** [comment]
Hello, please see #2172
