### ISSUE TITLE
CarbonPeriod gives different values for periods of same duration

### ISSUE THREAD

**Issue by knobel-dk** [briannesbitt/Carbon#2780]
Hello,

I encountered an issue with the following code:

```php
use Carbon\CarbonPeriod;

$dates = [
        ["2023-03-02T00:00:00.000000Z", "2023-03-04T23:59:59.000000Z"],
        ["2023-03-24T00:00:00.000000Z", "2023-03-26T23:59:59.000000Z"]
];
foreach($dates as [$min, $max]) {
    echo CarbonPeriod::start($min, true)
        ->setEndDate($max, false)
        ->setDateInterval("1 day")
        ->setTimezone("Europe/Copenhagen")
        ->count() . "\n";
}

```

Carbon version: **2.66.0**

PHP version: **8.2.4**

I expected to get:

```
3
3
```

But I actually get:

```
3
4
```

Thanks!

**Comment by kylekatarnls** [comment]
Hello, you have a DST in it wich means one day of this period is only 23-hour-long, so you get one more iteration for the remaining 59min 59s. If you stay in UTC, you'll get 3-count.
