### ISSUE TITLE
endOfMillennium not working as expected

### ISSUE THREAD

**Issue by Sairahcaz** [briannesbitt/Carbon#2782]
Hello,

I encountered an issue with the following code:

```php
echo Carbon::create(2023, 3, 31, 13, 15, 15)->subMillennium()->endOfMillennium()->format("Y-m-d H:i:s");
```

Carbon version: **2.66**

PHP version: **8.1.16**

I expected to get:

```
1999-12-31 23:59:59
```

But I actually get:

```
2000-12-31 23:59:59
```

Thanks!

**Comment by kylekatarnls** [comment]
Hello,

From [Wikipedia "2nd millennium" article](https://en.wikipedia.org/wiki/2nd_millennium):

> The second millennium of the [Anno Domini](https://en.wikipedia.org/wiki/Anno_Domini) or [Common Era](https://en.wikipedia.org/wiki/Common_Era) was a [millennium](https://en.wikipedia.org/wiki/Millennium) spanning the years 1001 to 2000

And article for "3rd millennium":

> third millennium of the [Anno Domini](https://en.wikipedia.org/wiki/Anno_Domini) or [Common Era](https://en.wikipedia.org/wiki/Common_Era) in the [Gregorian calendar](https://en.wikipedia.org/wiki/Gregorian_calendar) is the current [millennium](https://en.wikipedia.org/wiki/Millennium) spanning the years 2001 to 3000

So 2nd millennium ends just before 3rd one starts: 2000-12-31 23:59:59.999999

**Comment by Sairahcaz** [comment]
@kylekatarnls thanks for clearing that out.
Is there though a function in carbon which gives me the value I was expecting?
So in this case: 1999-12-31 23:59:59

**Comment by kylekatarnls** [comment]
```php
$date = Carbon::create(2023, 3, 31, 13, 15, 15)->endOfYear();
$date->year = floor($date->year / 1000) * 1000 - 1;
echo $date->format("Y-m-d H:i:s");
```
