### ISSUE TITLE
24:00:00

### ISSUE THREAD

**Issue by kasperhartwich** [briannesbitt/Carbon#279]
Hi.

Instead of 2015-04-01 00:00:00, i need to present the date as 2015-03-31 24:00:00.

This is part of the ISO 8601 and used to present 'midnight'. You can get Carbon to return 12:00:00 AM, but not 24:00:00. If I make pull request for this, would it be a feature that would be included?

**Comment by briannesbitt** [comment]
Google search on gets 2,980 results?  Where is this used?  Did you mean ISO 8601?

`Midnight is a special case and may be referred to as either "00:00" or "24:00". The notation "00:00" is used at the beginning of a calendar day and is the more frequently used. At the end of a day use "24:00". "2007-04-05T24:00" is the same instant as "2007-04-06T00:00"`

PHP wraps 24:00 to 00:00 on the next day which is acceptable according to ISO 8601.

**Comment by kasperhartwich** [comment]
Yes. ISO 8601. Typo.

I know that php input works fine. I want to present this date.

**Comment by dereuromark** [comment]
I also think that it doesn't need both ways of representing the same thing here. You could also just str_replace() it in this case if you must :)

**Comment by briannesbitt** [comment]
What did you have in mind ?  You would need to check for a 00:00:00 time... then minus a day and make the time portion 24:00:00.

**Comment by Yahav** [comment]
Why Was this closed? still happens today.
when you set ->hour(24)  it will be converted to 0.

> I think that maybe it doesn't need both ways of representing the same thing here. You could also just str_replace() it in this case if you must :)
there's a huge difference between 24 and 00..

**Comment by kylekatarnls** [comment]
Because this is not the `Carbon` responsibility. `Carbon` is a `DateTime` (native PHP class) extension, and:

```php
$date = new DateTime('2015-03-31 24:00:00');
echo $date->format('Y-m-d H:i:s');
$date->modify('24:00:00');
echo "\n";
echo $date->format('Y-m-d H:i:s');
```

It will output:
```
2015-04-01 00:00:00
2015-04-02 00:00:00
```

This is how PHP works, when you set hours to something greater than 23, it will overflow to the next day.

As a date library we guarantee dates are always valid, so you will never have a `DateTime` instances (or `Carbon` instances since it's a sub-class of `DateTime`) with ->hours === 24, ->hours will always be between 0 and 23.

The way you format it to be displayed does not change the fact that internally we will never store hours = 24.

Here is how you can falsify the output if you wish:
```php
$date = Carbon::parse('2015-03-31 24:00:00');

if ($date->format('H:i:s') === '00:00:00') {
  echo $date->copy()->subDay()->format('Y-m-d').' 24:00:00';
} else {
  echo $date->format('Y-m-d H:i:s');
}
```

**Comment by projct1** [comment]
This problem actual for me too :)
I want to store in database two time-fields: `time_from` and `time_to`.
So, my SQL query is `SELECT * FROM table BETWEEN time_from AND time_to`.
And all rows with time from `00:00:00` to `24:00:00` will be include.
`BETWEEN '00:00:00' AND '00:00:00'` will not be what I need...

**Comment by kylekatarnls** [comment]
Hello, I'm not sure what you expect from `Carbon`, the class extends `DateTime` so we are tied to its limitations.

From your example, it sounds to be up to you to decide according to your business rule when to use `00:00:00` and when to use `24:00:00` you can then have your own condition and user one or the other as a string accordingly.

Also `DateTime` (and so `Carbon`) is not the most suitable tool to represent time-only, it's really made to represent an instant so date+time. If on the top of that you need to represent overflowing times (i.e. time greater than the maximum that can actually existing in a 24-hour day: 23:59:59.999999), then it sounds way more appropriate to me to represent it with an other type, either a string, or something more strict such as a value-object with hours, minutes and seconds as integers.
