### ISSUE TITLE
 Carbon::createFromFormat - Unknown named parameter $timezone

### ISSUE THREAD

**Issue by Eugene-Melbourne** [briannesbitt/Carbon#2790]
Hello,

I encountered an issue with the following code:

```php
    Carbon::createFromFormat(
                format: 'Y-m-d H:i:s',
                time: $a,
                timezone: $b);
```

Carbon version: **2.66.0**

PHP version: **8**

I expected to get:

```
it working
```

But I actually get:

```
Error - Unknown named parameter $timezone 
```

Thanks!

**Comment by FLAIR7** [comment]
It is tz instead of timezone

`  Carbon::createFromFormat(
                format: 'Y-m-d H:i:s',
                time: $a,
                tz: $b);`

**Comment by kylekatarnls** [comment]
Indeed interface and documentation both say `$tz`. So it's expected to be `tz: $b` I agree `timezone:` would be better but doing zo will break existing code for people currently using `tz:`. It might be considered for the next major version.
