### ISSUE TITLE
getAbbreviatedName() returning wrong timezone

### ISSUE THREAD

**Issue by umairrafiq1133** [briannesbitt/Carbon#2792]
Hello,

I encountered an issue with the following code:

```php
$date = Carbon::parse('2022-03-15 10:00', 'America/Detroit');
echo $date->timezone->getAbbreviatedName();

echo "<br>";

$date = DateTime::createFromFormat('Y-m-d H:i', '2022-03-15 10:00', new DateTimeZone('America/Detroit'));
echo $date->format('T');
```

Carbon version: **2.53.1**

PHP version: **8.1.8**

I expected to get:

```
EDT
EDT
```

But I actually get:

```
cst
EDT
```

I thinks its more to do with daylight savings but php is giving correct output but Carbon doesnt. CST and America/Detroit have one hour difference.

Thanks!

**Comment by kylekatarnls** [comment]
Hello,

Carbon does, just use `->format('T')` as you do with a `DateTime` object:
```php
$date = Carbon::parse('2022-03-15 10:00', 'America/Detroit');
echo $date->format('T') . "\n";
echo $date->timezone->getAbbreviatedName() . "\n";
echo $date->timezone->getAbbreviatedName(dst: true) . "\n";
```

When you call `getAbbreviatedName()` you call it on the `timezone` object, not on the date, the timezone object in you code here is not aware of `$date` it doesn't carry information about DST observance.

It's the same in PHP:

```php
$date = DateTime::createFromFormat('Y-m-d H:i', '2022-03-15 10:00', new DateTimeZone('America/Detroit'));
$timezone = $date->getTimezone();
unset($date);

// From here, you won't be able to get `->format('T')` information.
// `$timezone` is America/Detroit but it does not have any flag for CST vs. EDT
```

Thanks.

**Comment by umairrafiq1133** [comment]
Thank you @kylekatarnls
