### ISSUE TITLE
Problema con los traits

### ISSUE THREAD

**Issue by AitorCheVaq** [briannesbitt/Carbon#2793]
Hola,

estoy con un proyecto usando tu paquete pero no me deja acceder, el código es éste:

```php
<?php
namespace josemmo\Facturae;

use josemmo\Facturae\FacturaeTraits\PropertiesTrait;
use josemmo\Facturae\FacturaeTraits\UtilsTrait;
use josemmo\Facturae\FacturaeTraits\SignableTrait;
use josemmo\Facturae\FacturaeTraits\ExportableTrait;

/**
 * Class for creating electronic invoices that comply with the Spanish FacturaE format.
 */
class Facturae {
  const VERSION = "1.7.6";
  const USER_AGENT = "FacturaePHP/" . self::VERSION;
```

Pero me sale esto:

```console
Fatal error:  Trait &quot;josemmo\Facturae\FacturaeTraits\PropertiesTrait&quot; not found in josemmo\facturae-php\src\Facturae.php on line 12
```
Y la línea 12 es donde se inicia la clase.

PHP version: PHP 8.0.7

Gracias.

**Comment by kylekatarnls** [comment]
Hello,

As per what I can understand, this error is not related to Carbon. This is likely an issue with your autoload so `PropertiesTrait` is not discoverable, please check composer documentation for that.

This channel is to report issues happening when using the `nesbot/carbon` package. To get help you're expected to provide steps to reproduce your issue with no other dependency than Carbon.

If you have such an issue to report please do it following [the full template](https://github.com/briannesbitt/Carbon/issues/new/choose) (please disable auto-translation from your browser to keep it in English).

Thanks.
