### ISSUE TITLE
CreateFromFormat without specifying day in the format

### ISSUE THREAD

**Issue by diegobenetti** [briannesbitt/Carbon#2795]
Hello,

I encountered an issue with the following code:
```php
    use Carbon\Carbon;

    $testCase = function ($str, $format) {
        print_r("\n");
        print_r('Raw string: '.$str );
        print_r("\n");
        print_r("Format: ".$format);
        print_r("\n");
        $d = Carbon::createFromFormat($format, $str);
        print_r('Year: '.$d->format('Y'));
        print_r("\n");
        print_r('Month format: '.$d->format('m'));
        print_r("\n");
        print_r('Month getter: '.$d->month);
        print_r("\n");
        print_r("Full date: ".$d->format('d/m/Y') );
        print_r("\n\n");
    };

    echo "<pre>";
    $testCase( '202302', 'Ym' );
    $testCase( '20230201', 'Ymd' );
    $testCase( '2023-02', 'Y-m' );
    $testCase( '2023-02-01', 'Y-m-d' );
    die();
```

`202302` stands for: year 2023 and month 02

The code contains 4 scenarios to confirm what carbon behavior really was. Apparently it's not possible to use the `createFromFormat` method without the days number, even if in the format you don't specify a day.

Carbon version: 2.67

PHP version: 8.1

I expected to get:

`Carbon::createFromFormat("Ym", "202302")->month` should be equals to 2

But I actually get:
`Carbon::createFromFormat("Ym", "202302")->month` returns 3

Thanks!

**Comment by kylekatarnls** [comment]
https://github.com/briannesbitt/Carbon/issues/2172#issuecomment-683706170
