### ISSUE TITLE
[Propsal] Ability to add days but skip weekends

### ISSUE THREAD

**Issue by aranw** [briannesbitt/Carbon#28]
I think it'll be really useful to add the ability to add days but skip out the weekends. 

For example: 

If it was 15/08/2013 and I wanted to add 2 days to this but skip out the weekend. 

It'll return 19/08/2013.

Another example would be if the date was 16/08/2013 and again wanted to add 2 days to this date. 

The returned date would again be 19/08/2013 as its added 2 days as expected but missed the weekend as a date that can be returned. 

Hope this is understandable?

**Comment by sanketgawde** [comment]
`Carbon::setWeekendDays([
            Carbon::SUNDAY
]);
$date=Carbon::parse("2019-07-06");
$tat=14;`
`$tat_date=Carbon::parse("2019-07-06")->addWeekdays($tat);`

**Comment by kylekatarnls** [comment]
As I tested it on [https://try-carbon.herokuapp.com](https://try-carbon.herokuapp.com/?embed&input=Carbon%3A%3AsetWeekendDays(%5B%20Carbon%3A%3ASUNDAY%20%5D)%3B%0D%0A%24tat%3D15%3B%0D%0A%24tat_date%3DCarbon%3A%3Aparse(%222019-07-05%22)-%3EaddWeekdays(%24tat)%3B%0D%0A%0D%0Aecho%20%24tat_date%3B%0D%0A) it gaves me the right output: `2019-07-23 00:00:00`

If you have an issue, please open a new one as this one is closed and provide enough information so we can reproduce the problem.
