### ISSUE TITLE
Translation month name from Armenian to any other language not working

### ISSUE THREAD

**Issue by ArtMin96** [briannesbitt/Carbon#2811]
Hello,

When I want to translate the month from Armenian to any other language using `translateTimeStringTo` method, it returns to Armenian again.

```php
echo (new Carbon)->translateTimeStringTo('23 Հունիս', 'en');
```

Carbon version: **2.66.0**

PHP version: **7.4**

I expected to get:

```
23 June
```

But I actually get:

```
23 Հունիս
```

Thanks!

**Comment by kylekatarnls** [comment]
Hello,

You need to provide the ISO code of the source language:
```php
echo Carbon::translateTimeString('23 Հունիս', 'hy', 'en'):
```

`translateTimeStringTo` uses the locale of the current object:
```php
echo (new Carbon)->locale('hy')->translateTimeStringTo('23 Հունիս', 'en');
```

Thanks.

**Comment by ArtMin96** [comment]
Thanks @kylekatarnls
