### ISSUE TITLE
PHP 7 nightly: Declaration of Carbon\Carbon::createFromFormat() should be compatible with...

### ISSUE THREAD

**Issue by Macsch15** [briannesbitt/Carbon#282]
My build on travis has an error after added PHP 7 nightly to the test matrix:
```
Declaration of Carbon\Carbon::createFromFormat() should be compatible with DateTime::createFromFormat($format, $time, DateTimeZone $object = NULL) in /home/travis/build/Macsch15/Tricolore/lib/Carbon/Carbon.php on line 2213 (code 2048)
```

Can someone confirm this issue?

**Comment by briannesbitt** [comment]
Yes... as per:

https://github.com/php/php-src/commit/8e19705a93d785cd1ff8ba3a69699b00169fea47#commitcomment-9969747

**Comment by Macsch15** [comment]
I see :confused:
Carbon will have some fix for this?

**Comment by briannesbitt** [comment]
Yes we will, first RC isn't due until June though but we'll get something in soon enough.  Interesting though PHP 7 was just added to the test matrix and its passing... guess the referenced changed hasn't been merged yet for travis.
https://travis-ci.org/briannesbitt/Carbon/jobs/52878652

**Comment by Macsch15** [comment]
Passing because I convert all PHP errors (even notices) into exceptions, you have in build only notice "PHP Strict Standards..." https://travis-ci.org/briannesbitt/Carbon/jobs/52878652

**Comment by kenmulford** [comment]
I don't have time to do a PR (or more honestly, learn about PRs because I've never done one), but I'm using Rasmus' php7dev vagrant box and ran across this error. I seed 30ish tables with Laravel's artisan db:seed command and they all require Carbon timestamps. I was able to get the seeding working correctly by changing the arguments for this method (line 379 or thereabouts) from

<code>createFromFormat($format, $time, $tz = null)</code>
to 
<code>createFromFormat($format, $time, DateTimeZone $tz = null)</code>

Hope that's useful.

**Comment by Macsch15** [comment]
@kenmulford this solution works fine on php 7 or later but on php 5 throws errors.

**Comment by kenmulford** [comment]
Correct, I should have clarified it's a b/c break. I was thinking it'd be useful in the context of the php7 test builds for anyone else trying to test apps.

**Comment by goyney** [comment]
Now that 7.0.0alpha 1 is out, do we have a fix or workaround for this? A brand new Laravel 5.1 project fails with this exception.

**Comment by briannesbitt** [comment]
Still lots of conversation here: https://github.com/php/php-src/commit/8e19705a93d785cd1ff8ba3a69699b00169fea47#commitcomment-11644892

**Comment by securit** [comment]
I got this to work across PHP versions by adding a simple php version check in Carbon.php from line 374

    public static function createFromFormat($format, $time, $dtz = null)
    {
        if ($tz !== null) {
            if (phpversion() < 7 ) {
                $dt = $dtz;
            } else {
                $dt = new DateTimeZone;
                $dt = $dtz;
            }
            $dt = parent::createFromFormat($format, $time, static::safeCreateDateTimeZone($tz));
        } else {
            $dt = parent::createFromFormat($format, $time);
        }

**Comment by Teranode** [comment]
so uhh, when will this be fixed?

**Comment by GrahamCampbell** [comment]
This is fixed.

**Comment by GrahamCampbell** [comment]
alpha 2 fixed it

**Comment by Macsch15** [comment]
Yes, looks like it has been fixed.

**Comment by GrahamCampbell** [comment]
This issue can be closed now. :)

**Comment by nWidart** [comment]
I still have this error on php7 & carbon.

**Comment by GrahamCampbell** [comment]
It was fixed on alpha 2.

**Comment by GrahamCampbell** [comment]
You must be using an older version of php7.

**Comment by nWidart** [comment]
Indeed, had to re-compile php7. Thanks for the heads up & sorry for the trouble. :smiley:
