### ISSUE TITLE
The result of startOfWeek() varies when mixin() is used, and no locale is set.

### ISSUE THREAD

**Issue by dylanbr** [briannesbitt/Carbon#2820]
Hello,

I encountered an issue with the following code:

```php
require('vendor/autoload.php');

use Carbon\Carbon;

trait CarbonMixin {

    public function mixinCopy()
    {
        return $this->copy();
    }
}

Carbon::mixin(CarbonMixin::class);

// Use a known date for replicating this issue.
$date = '2023-07-08';

// No locale is set, but confirm that the default is 'en'.
echo "Carbon defalt locale: " . Carbon::now()->locale() . "\n";

// Before we call the mixin method, we get '2023-07-03', which is a Monday.
$startOfWeekWithoutMixin = Carbon::parse($date)->startOfWeek()->format("Y-m-d");
echo "Without the Mixin being used: {$startOfWeekWithoutMixin}\n";

// This causes the default locale to be loaded, as a side-effect, resulting in '2023-07-02', which is a Sunday.
$startOfWeekWithMixin = Carbon::parse($date)->mixinCopy()->startOfWeek()->format("Y-m-d");
echo "With the Mixin being used: {$startOfWeekWithMixin}\n";
```

Carbon version: 2.68.1

PHP version: 8.2.7

I expected to get:

```
Carbon defalt locale: en
Without the Mixin being used: 2023-07-03
With the Mixin being used: 2023-07-03
```

But I actually get:

```
Carbon defalt locale: en
Without the Mixin being used: 2023-07-03
With the Mixin being used: 2023-07-02
```

From what I can tell, this is the due to changes made in #2804, specifically where `->settings($result->getSettings())` is called (in `src/Carbon/Traits/Mixin.php`), which results in the `en` locale being loaded, whereas before this no locale is in use.

As to whether this should result in Monday or Sunday, I am not sure, but I do think it should be consistent. This returned Monday in both cases with v2.66.0.

My workaround for this is to set `en_001` as the locale, which I'd recommend to anyone else hitting this issue.

Thanks!

**Comment by kylekatarnls** [comment]
Hello,

I will investigate.

Meanwhile, you can also do: `->startOfWeek(Carbon::MONDAY)` which will guarantee to use Monday as the start of week.

Thanks.
