### ISSUE TITLE
[Translation tool] ms

### ISSUE THREAD

**Issue by junyang-chin** [briannesbitt/Carbon#2824]
|English|ms|comments|
|--|--|--|
|2 hours before|2 jam lepas|This should rather be '2 jam sebelum' because 'lepas' means 'after'. Refer: The [official dictionary](https://prpm.dbp.gov.my/Cari1?keyword=sebelum)|

**Comment by kylekatarnls** [comment]
Hello,

As a non speaker, Malay dictionary is not helpful to me as I have to rely on yet another source to translate it.

@ashrafk you changed "sebelum" to "lepas", maybe you can enlighten this issue?

**Comment by junyang-chin** [comment]
Hello @kylekatarnls 

Here's the definition by [Cambidge University's English-Malay Dictionary](https://dictionary.cambridge.org/dictionary/english-malaysian/before). Hope it helps.
