### ISSUE TITLE
DateTime::__construct() expects parameter 2 to be DateTimeZone

### ISSUE THREAD

**Issue by montogeek** [briannesbitt/Carbon#283]
I get this error `DateTime::__construct() expects parameter 2 to be DateTimeZone` using Carbon with Laravel 4.2.

My PHP version is 5.3.3 on CentOS 6.2.

I already set the timezone in the php.ini, phpinfo() display correctly the timezone but I continue getting the error.

Is there anything more to do?

**Comment by nunovieira** [comment]
Same issue on Laravel 4.1, Carbon 1.15.0, PHP 5.3.3

**Comment by montogeek** [comment]
Upgrade your PHP, at least to https://github.com/klaussilveira/gitlist/issues/175#issuecomment-8768896
I did it, and it works, now my problem is with the mcrypt extension...

**Comment by nunovieira** [comment]
Upgrading PHP may not be feasible right now.
Fixed it temporarily in my app by limiting the Carbon version:
```
	"require": {
		...
		"nesbot/carbon": "<1.15"
	},
```

This is still an issue with Carbon. It [requires PHP 5.3.0](https://github.com/briannesbitt/Carbon/blob/master/composer.json#L20). At the very least it should be changed to 5.3.6 (if that fixes it).
I believe a better solution would be to workaround that issue in PHP.

**Comment by briannesbitt** [comment]
Yes, its a PHP bug in <5.3.6... can't pass a null value to the 2nd param of the ctor.  Should be easy to fix as its just a call to `date_default_timezone_get()`.

**Comment by montogeek** [comment]
Can you please?

**Comment by briannesbitt** [comment]
Give me another 3 mins ?  ;-)

**Comment by montogeek** [comment]
Sure!

**Comment by briannesbitt** [comment]
Push is done... waiting on packagist.  Trying to force update but the site seems to be spinning.

**Comment by briannesbitt** [comment]
Managed to get it updated.  Let me know!

**Comment by nunovieira** [comment]
Working! Thanks :)
