### ISSUE TITLE
PHT as a valid timezone identifier

### ISSUE THREAD

**Issue by Eugene-Melbourne** [briannesbitt/Carbon#2833]
Hello,

I encountered an issue - seems that Carbon does not recognize PHT as a valid timezone identifier. PHT stands for Philippine Time, which is one of the names of UTC+8 time zone

        $now = Carbon::create(2019, 3, 30, 0, 0, 0); 
        $now->setTimezone('PHT');

Carbon version: **2.68.1**

PHP version: **8.1**

I expected to get:

```
it working
```

But I actually get:

```
\Carbon\Exceptions\InvalidTimeZoneException
```

Thanks!

**Comment by kylekatarnls** [comment]
Hello 👋 

Carbon does not decide which timezone is valid or not. It relies on [PHP native DateTimeZone](https://www.php.net/manual/fr/class.datetimezone.php)

As you can see, PHP does not support it:
https://3v4l.org/0Sro8

You can find here the list of supported timezones:
https://www.php.net/manual/en/timezones.php
