### ISSUE TITLE
Create From Date Retuns date in March when Febuary is passed in on the 29th and 30th of the Month

### ISSUE THREAD

**Issue by RetepTT** [briannesbitt/Carbon#2841]
Hello,

I encountered an issue with the following code:

When the current day of the month is 29 or 30, create from date returns a date in March when $month = 2.

```php
echo Carbon::createFromDate(2023, 2); 

echo Carbon::createFromDate(2023, 3);
```

I expected to get:

```
2023-02-28 08:53:40  
2023-03-30 08:53:40  
```

But I actually get:

```
2023-03-02 09:13:45
2023-03-30 09:13:52
```

Carbon version: 2.68.1

PHP version: 8.1

Thanks!

**Comment by kylekatarnls** [comment]
Hello,

This behavior is explained in the documentation. Search `createFromDate` in the [Instantiation chapter](https://carbon.nesbot.com/docs/#api-instantiation)

#1739
