### ISSUE TITLE
Macros are stripped from the Carbon instance when casting to immutable

### ISSUE THREAD

**Issue by mattyforth** [briannesbitt/Carbon#2844]
When using `toImmutable`, the macros I've defined are stripped from the instance and throw an `UnknownMethodException`.

```php
// Create macro
Carbon::macro('testMacro', static function() {
   return "This is a test macro";
});

$date = now();
echo $date->testMacro(); // "This is a test macro"

$date = now()->toImmutable();
echo $date->testMacro() // Carbon\Exceptions\UnknownMethodException
```

You can get around this by instead defining the macro on the `CarbonImmutable` class, as apposed to the regular `Carbon` class. However I'm not sure that stripping macros off after running `toImmutable` is the desired behaviour. 

Carbon version: versions : 2.66.0

PHP version: 8.1

I expected to get:

```
"This is a test macro"
```

But I actually get:

```
Carbon\Exceptions\UnknownMethodException
Method testMacro does not exist.
```

Thanks!

**Comment by kylekatarnls** [comment]
Hello,

It's highly recommended that you stick on either `\Carbon\CarbonImmutable` (prefered) or `\Carbon\Carbon` in a given project. Having both in the same project can add confusion and be error-prone. I.E. Immutability is safer than mutability, but mutability is still safer than unknown mutability-state.

If you still need to support both (if you're migrating from one to the other for instance), then define macros on both:
```php
$testMacro = static function() {
    return "This is a test macro";
};
\Carbon\Carbon::macro('testMacro', $testMacro);
\Carbon\CarbonImmutable::macro('testMacro', $testMacro);
```

Mixin can also help organizing and not having duplicate code or to use string for method names:
```php
// In some Util/Date/MyMacros.php
trait MyMacros
{
  public function testMacro(): string
  {
    return "This is a test macro";
  }
}
// In your app bootstrap:
\Carbon\Carbon::mixin(MyMacros::class);
\Carbon\CarbonImmutable::mixin(MyMacros::class);
```
