### ISSUE TITLE
Feature suggestion: endOfDay() alias

### ISSUE THREAD

**Issue by tarraq** [briannesbitt/Carbon#2846]
Hello,

I have a simple suggestion for a helper.
Now I'm often finding myself do something like this (in Laravel):

```php
echo now()->hour(23)->minute(59)->second(59)->millisecond(999);
```
to include all events of what I'm searching for. 
My proposal is to make an alias  
```php
echo now()->endOfDay();
```
to make this easier. In some cases, I will be able to just use the full date, but not always. 

Carbon version: 2.62.1 (Laravel 9)

PHP version: 8.2

I would happily implement this myself, but unsure where the proper place would be. 

Greetings from Denmark,
Tarraq

**Comment by kylekatarnls** [comment]
Hello,

This method exists since the very first version of Carbon.

From https://carbon.nesbot.com/docs/#api-difference

![image](https://github.com/briannesbitt/Carbon/assets/5966783/60c9ef21-45a1-4955-a6f5-1e71132f252a)

**Comment by tarraq** [comment]
I guess I can't read docs then. Well great idea you got there! :)
