### ISSUE TITLE
Translation tool: February missing, March listed twice

### ISSUE THREAD

**Issue by chrieinv** [briannesbitt/Carbon#2847]
Hello,

I encountered an issue with the translation tool at https://carbon.nesbot.com/contribute/translate/. In the month list March is listed twice, and February is missing.

Carbon version: N/A

PHP version: N/A

I expected to get:

```
February available for translation
```

But I actually get:

```
March listed twice
```

Thanks!

**Comment by kylekatarnls** [comment]
Thank you for the notice. 🙏 

Documentation fixed 👌
