### ISSUE TITLE
CarbonImmutable ignores second parameter (Timezone)

### ISSUE THREAD

**Issue by victorheid** [briannesbitt/Carbon#2849]
Hello,

`new CarbonImmutable($dt,$tz);` seems to ignore the second parameter - had a couple of bugs happening due to this issue. I've tried both sending as string and DateTimeZone object.

```php
// Works as expected
echo   (new CarbonImmutable('2023-09-12T08:45:00.000000Z
'))->setTimezone('Europe/Dublin');

// Won't apply Timezone
echo new CarbonImmutable('2023-09-12T08:45:00.000000Z
', 'Europe/Dublin');
```

Carbon version: 2.66.0

PHP version: 8.1.18

Thanks!

**Comment by kylekatarnls** [comment]
Hello, 👋

This behavior is expected, the `Z` in your date string actually is a timezome (Zulu time = GMT+0) and it takes precedence over the second argument (wich is a fallback timezone if not specified in the strinf).
