### ISSUE TITLE
CarbonPeriodImmutable::instance leads to 'Invalid constructor parameters' Exception in Version >= 2.68

### ISSUE THREAD

**Issue by ClashIsRadical** [briannesbitt/Carbon#2853]
Hello,

I encountered an issue with the following code:

```php
$singleDayPeriod = new \DatePeriod(
    new CarbonImmutable('2023-10-23 00:00:00.0'),
    new \DateInterval('P1D'),
    new CarbonImmutable('2023-10-23 23:59:59.0'),
);
CarbonPeriodImmutable::instance($singleDayPeriod);
```

Carbon version: 2.70     (also crashes on 2.69 and 2,68, but runs fine at 2.67)

PHP version: 8.1.14

I expected to get:

```
CarbonPeriodImmutable instance and no exception
```

But I actually get:

```
Carbon\Exceptions\InvalidPeriodParameterException with message 'Invalid constructor parameters.'
   null
```

U can see it here: https://play.phpsandbox.io/nesbot/carbon/wPk7eEx7bJ59RxVQ

Thx for your great work with Carbon, using it every Day for a long time now, this is my first issue, everything else always worked amazing.

Thanks!

**Comment by kylekatarnls** [comment]
Thanks for the report, it will be fixed in next version.
