### ISSUE TITLE
CarbonTypeConverter broken with Doctrine/Dbal 3.7

### ISSUE THREAD

**Issue by ph-il** [briannesbitt/Carbon#2858]
Hello,

I encountered an issue with the following code:

```sh
bin/console doctrine:migrations:diff
```

Carbon version: 2.71.0

PHP version: PHP 8.2.8

I expected to get:

```
Success
```

But I actually get:

```
In CarbonTypeConverter.php line 39:
                                            
  Warning: Undefined array key "precision"  
```

Thanks!

**Comment by ph-il** [comment]
Line 39 should use ?? instead of ? 
But 3.7.0 is bringing lot of preparation to 4.0, so it might bring more important change.

I had to go back to earlier version of DBAL.

**Comment by kylekatarnls** [comment]
That's a great news because in oldest versions of dbal, it was not possible to know if the precision was set to 0 or not set at all (so to use the default).

It would be great to take benefit of this enhancement and so to have behavior depending on the dbal version.

**Comment by kylekatarnls** [comment]
Hello can you try to `composer require "nesbot/carbon:dev-master as 2.72.0"`?
