### ISSUE TITLE
Undefined precision key in CarbonTypeConverter.php

### ISSUE THREAD

**Issue by munyoudoum** [briannesbitt/Carbon#2863]
Hello,

I encountered an issue with the following code:

![image](https://github.com/briannesbitt/Carbon/assets/60089135/a543be73-8d05-486d-b346-694c0c2e6009)

Carbon version: **2.71.0**

PHP version: 8.1.0

I expected to get:

```Success```

But I actually get:

```
In CarbonTypeConverter.php line 45:
                                            
  Warning: Undefined array key "precision"  
```

I tried to change the CarbonTypeConverter.php file in line 45:

from
```php
        $precision = $fieldDeclaration['precision'] ?: 10;
```

to

```php
        $precision = $fieldDeclaration['precision'] ?? 10;
```

It works because it would assign 10 when 'precision' key is not found in the array. The current carbon source code would raise errors when 'precision' key is not found.

Thanks!

**Comment by kjacquesmashbo** [comment]
This happens for me too. 
Downgraded doctrine/dbal from 3.7.0 to 3.6.7 and it works again.

**Comment by munyoudoum** [comment]
Ok. Thank you so much. I hope to see the fix for soon 😄

**Comment by kylekatarnls** [comment]
See #2858

**Comment by kylekatarnls** [comment]
For the record, master branch now supports dbal >= 3.7. I won't hurry the release because it's a breaking change on the dbal side, not a bug in Carbon. And you can use carbon master branch in the meantime.
