### ISSUE TITLE
[Translation tool] lu

### ISSUE THREAD

**Issue by fonz-lu** [briannesbitt/Carbon#2865]
|English|lu|comments|
|--|--|--|
|2 years|2 years|2 Joer|
|2yrs|2yrs|2j|
|1 year|1 year|1 Joer|
|a year|a year|ee Joer|
|2 months|2 months|2 Méint |
|2mos|2mos|2m|
|1 month|1 month|1 Mount |
|a month|a month|ee Mount|
|2 weeks|2 weeks|2 Woochen|
|2w|2w|2w|
|1 week|1 week|1 Wooch |
|a week|a week|eng Wooch |
|2 days|2 days|2 Deeg|
|2d|2d|2d|
|1 day|1 day|1 Dag|
|a day|a day|een Dag|
|2 hours|2 hours|2 Stonnen|
|2h|2h|2h|
|1 hour|1 hour|1 Stonn|
|an hour|an hour|eng Stonn|
|2 minutes|2 minutes|2 Minutten |
|2m|2m|2m|
|1 minute|1 minute|1 Minutt |
|a minute|a minute|eng Minutt|
|2 seconds|2 seconds|2 Sekonnen |
|2s|2s|2s|
|1 second|1 second|1 Sekonn|
|a few seconds|a few seconds|ë puer Sekonnen |
|Monday|Nkodya|Méindeg |
|Mon|Nko|Méi |
|Mo|Nko|Mé |
|Tuesday|Ndàayà|Dënschdeg |
|Tue|Ndy|Dën|
|Tu|Ndy|Dë |
|Wednesday|Ndangù|Mëttwoch |
|Wed|Ndg|Mët|
|We|Ndg|Më|
|Thursday|Njòwa|Donneschdeg |
|Thu|Njw|Don|
|Th|Njw|Do|
|Friday|Ngòvya|Freideg |
|Fri|Ngv|Fre|
|Fr|Ngv|Fr|
|Saturday|Lubingu|Samschdeg |
|Sat|Lub|Sam|
|Sa|Lub|Sa|
|Sunday|Lumingu|Sonndeg |
|Sun|Lum|Son|
|Su|Lum|So|
|January|Ciongo|Januar |
|Jan|Cio|Jan|
|February|Lùishi|Februar |
|Feb|Lui|Feb|
|March|Lusòlo|Mäerz |
|Mar|Lus|Mäe|
|April|Mùuyà|Abrëll |
|Apr|Muu|Abr|
|May|Lumùngùlù|Mee|
|May|Lum|Mee|
|June|Lufuimi|Juni|
|Jun|Luf|Jun|
|July|Kabàlàshìpù|Juli|
|Jul|Kab|Jul|
|August|Lùshìkà|August |
|Aug|Lush|Aug|
|September|Lutongolo|September |
|Sep|Lut|Sep|
|October|Lungùdi|Oktober |
|Oct|Lun|Okt|
|November|Kaswèkèsè|November |
|Nov|Kas|Nov|
|December|Ciswà|Dezember |
|Dec|Cis|Dez|
|2 hours ago|2 hours ago|virun 2 Stonnen |
|2 hours from now|2 hours from now|2 Stonnen ab elo|
|2 hours before|2 hours before|2 Stonnen virdrun |
|2 hours after|2 hours after|2 Stonnen dono|

**Comment by kylekatarnls** [comment]
Hello `2 Méint` and `2 Minutten` are both abbreviated `2m`? 🤔

**Comment by kylekatarnls** [comment]
Hello, can you provide some official source, I cross-checked with few ones and, for instance on Monday.

I couldn't find `Méindeg`

But I found `Nkodya` twice:
https://www.masteranylanguage.com/c/r/en/LubaKatanga/DaysOfWeek
https://glosbe.com/en/lu/Monday

FTR, `lu` is the [ISO code]((https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes)) for [Luba-Katanga](https://en.wikipedia.org/wiki/Luba-Katanga_language) 

Do you confirm that the language you meant to contribute to? (in the above "comments" column)

**Comment by fonz-lu** [comment]
Hi, I am really sorry, I thought the iso code for Luxembourgish was lu, but it actually is lb. My bad 😞
