### ISSUE TITLE
setLocale() not compatible with the Symfony interface, blocking Symfony 7 support

### ISSUE THREAD

**Issue by wouterj** [briannesbitt/Carbon#2875]
Hello,

I encountered an issue when trying to add support for Symfony 7 to this library.

Carbon version: dev-master

PHP version: 8.3

Symfony 7 comes with [native return types to all methods](https://github.com/symfony/symfony/issues/51563). Methods in this library that are hit by this are:

* `AbstractTranslator::setLocale()`, must be `void`
* `Localization::setLocale()`, must be `void`
* `TranslatorImmutable::setLocale()`, must be `void`
* `TranslatorImmutable::setConfigCacheFactory()`, must be `void`
* `TranslatorImmutable::setFallbackLocales()`, must be `void`

This library introduces its own logic in `setLocale()`, changing the return type to `bool`. This means it does not comply to the API of `Symfony\Contracts\Translation\LocaleAwareInterface`. As a result, the library as-is cannot support Symfony 7.

I think there are 3 options:

* Remove the feature that requires a bool return value of `setLocale()`
* Create a new method that implements the custom logic of `setLocale()` and make `setLocale()` compliant with the Symfony contract.
* Alternatively, ask in the Symfony issue to delay the `void` return type of `setLocale()`. Given the library did not comply with the previous PHPdoc, I'm not 100% confident that the core team agrees with this, but it may be worth a shot.

I'm happy to help here (given this blocks my eloquent bundle from supporting Symfony 7), but I don't want to make any decisions for you :)

Thanks!

**Comment by kylekatarnls** [comment]
Hello,

> `Localization::setLocale()`, must be `void`

Actually this one is not affected, but we will indeed set them all to void-return as of 3.0 version of Carbon.

**Comment by kylekatarnls** [comment]
Carbon 3 is now compatible with Symfony 7.

Tested on Symfony 7.1, you can install it with:

```
composer require nesbot/carbon:^3.0@dev
```

**Comment by wouterj** [comment]
Thank you!
