### ISSUE TITLE
Problem with November

### ISSUE THREAD

**Issue by rahman-nero** [briannesbitt/Carbon#2877]
Hello,

I encountered an issue with the following code:

```php
echo Carbon::createFromFormat('Y-m', '2023-11')->startOfMonth()->format('Y-m-d');
```

Carbon version: **2.64.0**

PHP version: **8.1.21**

I expected to get:

```
2023-11-01
```

But I actually get:

```
2023-12-01
```

If we replace '2023-11' with another month, it works perfectly fine. The problem is only with November.

I solved it with adding a day at the end:
```php
echo Carbon::createFromFormat('Y-m-d', '2023-11-01')->startOfMonth()->format('Y-m-d')
``` 

Thanks!

**Comment by kylekatarnls** [comment]
https://github.com/briannesbitt/Carbon/issues/2172#issuecomment-683706170
