### ISSUE TITLE
Carbon::now()->subMonth() function shows wrong month

### ISSUE THREAD

**Issue by arbenbytyqi** [briannesbitt/Carbon#2878]
Hello,

I encountered an issue with the following code:

```php
echo Carbon::now()->subMonth()->month;
```
Wrong month is shown if you are in the 31th day of month (31.10.2023).

Carbon version: 2.71.0

PHP version: 8.2.7

I expected to get:

```
09
```

But I actually get:

```
10
```

Thanks!

**Comment by kylekatarnls** [comment]
Duplicates #2047
