### ISSUE TITLE
Could not find next valid date.

### ISSUE THREAD

**Issue by sabina1997** [briannesbitt/Carbon#2889]
Hello,

I encountered an issue with the following code:

```php
            $timeRangeFilter = new TimeRangeFilter($startAt, $endAt);

            $weekDaysFilter = new WeekDaysFilter($daysOfWeek);
            
            $period = CarbonPeriod::create($start_date, "{$slotDurationInMinutes} minutes", $end_date)
                ->prependFilter($weekDaysFilter)
                ->prependFilter($timeRangeFilter);
                
            echo $period->toArray();
```

Carbon version: **2.71.0**

PHP version: **8.1**

I expected to get:

```
an array of carbon dates
```

But I actually get:

```
Carbon\Exceptions\UnreachableException Could not find next valid date.
```

This doesn't happen always but one example is if we want all mondays between two dates, and when the last monday is not the end date of the period,  when it continues iteration after the last recurrence it throws this.
Thanks!

**Comment by kylekatarnls** [comment]
Hello, we miss code for `TimeRangeFilter` and `WeekDaysFilter` to be able to reproduce it on our side.

`UnreachableException('Could not find next valid date.')` is expected to be thrown when iteration goes over more than `1000` intervals (`"{$slotDurationInMinutes} minutes"`) without finding a value that matches all filters.

If you iterate more than 1000 times, then `CarbonPeriod` is very likely not the more optimized tool to achieve what you want.

Looking at names of your filters, I guess you skip week-end and only care about slots in given ranges. [cmixin/business-time](https://github.com/kylekatarnls/business-time) can handle that in a more optimized way, you would be able to register time ranges and exclude week-end, then the library can jump to next open time range directly and you can iterate only inside the open ranges.

**Comment by kylekatarnls** [comment]
Thanks,

Just to say, that definitely sounds like a fit for [cmixin/business-time](https://github.com/kylekatarnls/business-time) I suggest to take a look not to reinvent the wheel and get tooling for weekly opening hours plus holidays/exceptions/filter out of the box.

Thanks for the code, I can now run it on my side, however I tried multiple values, even with Monday only and 10 minute slots, I don't hit `UnreachableException`.

I can only trigger it with an empty list of days such as `new WeekDaysFilter([])` but in this case the exception is expected.

Can you give an example of values that trigger the exception?

Overall, if you have `["FRI","SAT","MON"]` and 30 minutes interval, you will still iterate 48 times during TUE, WED, THU and SUN, you can slightly optimize by iterating days, then inside iterating the 30-minutes slots, this way you also are way less likely to it the `UnreachableException`:

```php

class WeekDaysFilter
{
    public function __construct(
        protected array $daysOfWeek,
    ) {
    }

    public function __invoke(Carbon $date): callable|array|bool
    {
        return in_array(strtoupper($date->shortEnglishDayOfWeek), $this->daysOfWeek);
    }
}

$startAt = Carbon::parse('2023-11-24 13:00');
$endAt = Carbon::parse('2023-11-30 17:00');

$weekDaysFilter = new WeekDaysFilter(['FRI', 'SAT', 'MON']);
$slotDurationInMinutes = 30;

$days = CarbonPeriod::create($startAt, '1 day', $endAt)
    ->prependFilter($weekDaysFilter);

foreach ($days as $day) {
    $dayStart = $day->copy()
        ->setTimeFromTimeString($startAt->toTimeString());
    $dayEnd = $day->copy()
        ->setTimeFromTimeString($endAt->toTimeString());
    $slots = CarbonPeriod::create($dayStart, "$slotDurationInMinutes minutes", $dayEnd);

    foreach ($slots as $slot) {
        echo $slot->toDateTimeString() . "\n";
    }
}
```

This is also how `cmixin/business-time` proceed under the hood to be more efficient (in term of number of iterations)
