### ISSUE TITLE
Symfony 7 support

### ISSUE THREAD

**Issue by sakarikl** [briannesbitt/Carbon#2891]
Hello,

composer dependencies do not allow installing symfony 7.0

**Comment by kylekatarnls** [comment]
https://github.com/briannesbitt/Carbon/pull/2888#issuecomment-1823262173

> Symfony 7 will be supported on Carbon 3, you can test it with
> ```
> composer require nesbot/carbon:^3.0@dev
> ```

**Comment by sakarikl** [comment]
Is there some timeline for 3.0 yet determined?

@kylekatarnls 
Tried our test set for carbon 3 and one different behaviour found. Where should I report it?

**Comment by kylekatarnls** [comment]
First please take a look at the list of the expected change. It's a new major version, it will include breaking changes such as diff() method will now return `float`

https://github.com/briannesbitt/Carbon/issues/1681

If not in the list and unexpected regression, you may open an issue.

**Comment by sakarikl** [comment]
diffAsCarbonInterval returns duration object which returns different string on spec method for some cases in 3 vs 2. 

I'll create a minimal code to reproduce it and open a new issue.

**Comment by kylekatarnls** [comment]
v3 compatibility with Laravel is now being checked: laravel/framework#49764

If you are on Laravel or have a composer constraint in your project needed carbon v2, you can still try the v3 using:

```
composer require "nesbot/carbon:3.x-dev as 2.99"
```

Do not hesitate to give it a try, your help in testing this new version will be gratefully welcome. The more it can be tested, the faster it will reach the stable release.
