### ISSUE TITLE
mysql date conversion to carbon date

### ISSUE THREAD

**Issue by davidtmnolan** [briannesbitt/Carbon#290]
Grinding my teeth on this one.
var_dumping $getDates from my sql query I get:

array (size=2)
      0 => string '2015-01-31 11:59:00' (length=19)
      1 => string '2015-01-31 15:59:00' (length=19)

$date1 = $this->carbon->createFromTimestamp(strtotime($getDates[0]));

this is resulting in a date of '1970-01-01 00:00:00'

without the strtotime i get the same result, and (strtotime($getDates[0])) is returning false

S.O.S!

**Comment by briannesbitt** [comment]
Easiest is:

```php
$getDates = array('2015-01-31 11:59:00', '2015-01-31 15:59:00');

foreach ($getDates as $i => $d) {
    $getDates[$i] = Carbon::parse($getDates[$i]);
}

var_dump($getDates);
```

You could also use `Carbon::createFromFormat()` but the simple parse works in your case.

**Comment by davidtmnolan** [comment]
Thank you Brian, 

How can I use parse with the 'carbon->' method?

I tried createFromFormat but was getting the same issue.
$this->carbon->createFromFormat('Y-m-d H', $getDates[0])

**Comment by baltun** [comment]
Carbon::parse($getDates[$i])->toDateString()
