### ISSUE TITLE
Bag to diff in February

### ISSUE THREAD

**Issue by KoRNeT46RuS** [briannesbitt/Carbon#2904]
If dates '2023-02-28 23:59:59.999999' and '2023-01-29 00:00:00.000000'. Diff months  = 0. Why, if in february 28 days?

Hello,

I encountered an issue with the following code:

```php
echo Carbon::parse('2018-06-01')->subDay()->month;
```

Carbon version: **PUT HERE YOUR CARBON VERSION (exact version, not the range)**

PHP version: **PUT HERE YOUR PHP VERSION**

I expected to get:

```
6
```

But I actually get:

```
5
```

Thanks!

**Comment by kylekatarnls** [comment]
Diff relies on `DateTime` which will consider 1 month starting from the start, so starting from the 29th, it won't consider the diff (which is floored integer value) reaches 1 until the day on next month is >=29.

You can use `floatDiffInMonths` to see the precise floating number.
