### ISSUE TITLE
Unable to install DBAL on a fresh Laravel application due to type package

### ISSUE THREAD

**Issue by timacdonald** [briannesbitt/Carbon#2905]
Hello,

Tim here from the Laravel core team 👋

I encountered an issue with the following code:

```sh
composer create-project laravel/laravel dbal-test
cd dbal-test
composer require doctrine/dbal
```

Carbon version: 2.72.1

PHP version: 8.2.11

I expected to get:

```
A successful installation of DBAL
```

But I actually get:

```
Your requirements could not be resolved to an installable set of packages.
```

We are currently trying to work out how to resolve this for our users. I've opened a PR on Laravel to conflict with the `^3.0` version of types package (https://github.com/laravel/framework/pull/49438), however this causes existing application to no longer be able to update their version of the framework without running special composer commands.

Is there any way we can remove this package from the `"require"` and possibly add it to `"suggest"` or document that it should be installed if you are using Doctrine?

Thanks!

**Comment by taylorotwell** [comment]
Can we please get this fixed? 🫣😵‍💫

**Comment by kylekatarnls** [comment]
```
composer require doctrine/dbal -W
```

So it will update https://github.com/CarbonPHP/carbon-doctrine-types which makes the link between the 2 and avoid 1 version of carbon to stretch with a range of compatibility.

**Comment by timacdonald** [comment]
Unfortunately that doesn’t allow the package to be installed. You must also specify the types package.

```
composer create-project laravel/laravel dbal-test
cd dbal-test
composer require doctrine/dbal ❌
composer require doctrine/dbal -w ❌
composer require doctrine/dbal -W ❌
composer require doctrine/dbal carbonphp/carbon-doctrine-types ✅
```

**Comment by kylekatarnls** [comment]
Thanks for the feedback, for people having dbal conflict in non-Laravel app, `-W` worked fine, so I guess `composer` might hit some limit to resolve the dependency. But the fact that `composer require doctrine/dbal carbonphp/carbon-doctrine-types` works is the proof that the constraint is actually not blocking.

**Comment by kylekatarnls** [comment]
Thanks @timacdonald and @taylorotwell 🙏 

Regarding pros and cons I could fine while investigating I think https://github.com/laravel/framework/pull/49438/files is the right move.

I'd close #2907 if it gets merged.

**Comment by kylekatarnls** [comment]
Fixed by https://github.com/laravel/framework/pull/49438
