### ISSUE TITLE
Should FactoryImmutable::now() use the factory timezone?

### ISSUE THREAD

**Issue by grantholle** [briannesbitt/Carbon#2906]
When using `FactoryImmutable` and calling `FactoryImmutable::now()`, it doesn't set the timezone to be the factory's timezone. I'm not sure if that's intended, but it feels weird to me.

```php
$factory = new FactoryImmutable([
    'timezone' => 'Asia/Shanghai',
]);

$factory->now()->toDateTimeString(); // 2023-12-20 06:18:13
CarbonImmutable::now()->toDateTimeString(); // 2023-12-20 06:18:13
```

Carbon version: 2.72.1

PHP version: 8.2.7

Intuitively, I feel like when I call `now()` on the factory, it should be based on its timezone. 

```php
$factory = new FactoryImmutable([
    'timezone' => 'Asia/Shanghai',
]);

$factory->now()->toDateTimeString(); // 2023-12-20 14:18:13
CarbonImmutable::now()->toDateTimeString(); // 2023-12-20 06:18:13
```

When looking at the `FactoryImmutable` class, I feel like `now()` function should be implemented like...

```php
public function now($tz = null): DateTimeImmutable
{
    $className = $this->className;

    // currently return new $className(null, $tz);
    return new $className(null, $this->settings['timezone'] ?? $tz);
}
```

I can get around it, but just seems extra verbose when I'm already using a factory with a timezone.

```php
$factory = new FactoryImmutable([
    'timezone' => 'Asia/Shanghai',
]);

$factory->now($factory->getSettings()['timezone']); // 2023-12-20 14:18:13
```

Thanks!

**Comment by grantholle** [comment]
Actually, I guess the timezone passed in should take precedence, the more I think about it.

```php
public function now($tz = null): DateTimeImmutable
{
    $className = $this->className;

    // currently return new $className(null, $tz);
    return new $className(null, $tz ?? $this->settings['timezone'] ?? null);
}
```

**Comment by kylekatarnls** [comment]
Hello, 

Yes, it's a general issue for all settings in factory: #2345

For carbon v3, settings stored statically in Carbon class should all move to actual properties of the factories.

You can test work in progress in this area with `composer require "nesbot/carbon:dev-feature/isolated-factories as 3.0.0"`

**Comment by grantholle** [comment]
Ok, thanks. I'll wait for v3 then!
