### ISSUE TITLE
setTestNow() and create() null values

### ISSUE THREAD

**Issue by VVelda** [briannesbitt/Carbon#291]
This does not work as expected, because create functions ingores testNow value, let me show:

	echo Carbon::now(); // 2015-03-03 22:38:53
	echo Carbon::create(null, null, null, null, null, null); // 2015-03-03 22:38:53
	// now and create with default values are same
	Carbon::setTestNow($now = Carbon::create(2015, 2, 28, 0));
	echo Carbon::now(); // 2015-02-28 00:00:00
	echo Carbon::create(null, null, null, null, null, null); // 2015-03-03 22:38:53
	// should be same as now() returned 2015-02-28 00:00:00

**Comment by briannesbitt** [comment]
Yes, according to the docs:
* A call to the static now() method, ex. Carbon::now()
* When a null (or blank string) is passed to the constructor or parse(), ex. new Carbon(null)
* When the string "now" is passed to the constructor or parse(), ex. new Carbon('now')

**Comment by VVelda** [comment]
Well this feature is meaned as simulation of time, isn't it? Then, how can there be different now times by way we use Carbon? Previous example shows malfunction of testNow, that's not real usage. Real usage can be something like this:
`Carbon::create(null, $month, $day, 0);`
This is obvious bad behaviour, it's enough that it is confusing and producing different nows.
I don't see any valid test case with use of testNow with this uncomplete implementation.

**Comment by briannesbitt** [comment]
There is a valid example in the docs. http://carbon.nesbot.com/docs/#api-testing

**Comment by VVelda** [comment]
I does not have issued invalid docs, but uncomplete, confusing functionality and probably without use case in real programmes, because it does not cover all aspects of Carbon lib.

**Comment by briannesbitt** [comment]
Thanks for your comments.  The doc link I provided shows a real world example.  I think the docs are pretty clear and indicate exactly where the shortcomings of the testing feature set are.

Seems to me you could easily check for all args being null and swap your call to `Carbon::now()` which would then use the testing features.  This could also be added to the library itself but I am hesitant.

**Comment by VVelda** [comment]
In real word you can use automatic completion of month or year or something with create function, but then when you set testNow to different month, automatic completed month remains.

Repair is easy, it is enough to change this:

      $year = ($year === null) ? date('Y') : $year;
      $month = ($month === null) ? date('n') : $month;
      $day = ($day === null) ? date('j') : $day;

      if ($hour === null) {
         $hour = date('G');
         $minute = ($minute === null) ? date('i') : $minute;
         $second = ($second === null) ? date('s') : $second;
      } else {
         $minute = ($minute === null) ? 0 : $minute;
         $second = ($second === null) ? 0 : $second;
      }
to this:

	  $now = static::hasTestNow() ? static::getTestNow()->getTimestamp() : time();
   
      $year = ($year === null) ? date('Y', $now) : $year;
      $month = ($month === null) ? date('n', $now) : $month;
      $day = ($day === null) ? date('j', $now) : $day;

      if ($hour === null) {
         $hour = date('G', $now);
         $minute = ($minute === null) ? date('i', $now) : $minute;
         $second = ($second === null) ? date('s', $now) : $second;
      } else {
         $minute = ($minute === null) ? 0 : $minute;
         $second = ($second === null) ? 0 : $second;
      }

**Comment by briannesbitt** [comment]
I don't mind that implementation.  See what others think.

**Comment by dirkpostma** [comment]
+1 for VVelda implementation!

Note that related methods also should behave differently:

```
$knownDate = Carbon::create(2001, 5, 21, 12);
Carbon::setTestNow($knownDate);

// 
echo Carbon::now();                      // 2001-05-21 12:00:00 

// Not as desired:
echo Carbon::parse("20:00");             // 2016-03-11 20:00:00 (at time of writing)
echo Carbon::createFromTime(20, 00, 00); // 2016-03-11 20:00:00 (at time of writing)
```

**Comment by lucasmichot** [comment]
See PR https://github.com/briannesbitt/Carbon/pull/633 that fixes that.
