### ISSUE TITLE
isLastMonth() does not account for year

### ISSUE THREAD

**Issue by tomsommer** [briannesbitt/Carbon#2910]
Hello,

I encountered an issue with the following code:

```php
echo Carbon::now()->subMonthNoOverflow()->subYearsNoOverflow(2)->isLastMonth();
```

It should return false, not true - as it should account for the year? If not then it should be better documented, or maybe an isPreviousMonth() should be added, or an option should be added to account for year?

Same applies for `isNextMonth()`

**Comment by kylekatarnls** [comment]
Hello,

`isLastMonth` doc:
> Checks if the instance is in the same month as the current moment last month.

In English, when starting a sentence with "Last month", as of Today it refers to December 2023, it would never refer to December of a farther year. "Next month" is February 2024, the one you would expect in a natural conversation.

"last" here is a synonym of "previous" like in the method `isLastWeek`.

I get the ambiguity with "last" one could expect to implicitly mean "last of the year", but I don't get how it would mean that `Carbon::now()->subMonthNoOverflow()->subYearsNoOverflow(2)->isLastMonth()` is `true`. So I'm not sure how to make it more explicit in this regard.

Here is where is generated the documentation for those next/previous methods:
https://github.com/briannesbitt/Carbon/blob/master/phpdoc.php#L264

If you see how it could be better documented, feel free to propose a pull-request.

**Comment by kylekatarnls** [comment]
Sorry for closing, yes it's a bug, I will double-check but it's not consistent with `Carbon::now()->subWeek()->subYearsNoOverflow(2)->isLastWeek()`

**Comment by kylekatarnls** [comment]
After a first investigation, we have 2 units currently not consistent with others: "month" and "quarter", the other unit will take upper units into account to same they are the same/next/last. While the behavior of next and last is not particular for month, they rely on "same": next => same(+1), last => same(-1) and "same" is handled differently for month => `isSameMonth("January 2023", "January 2024")` is currently `true`. (quarter unit inherit from month).

It's not consistent with isSameHour, isSameMinute etc. so it would make sense to align "month" with others. However it might still trigger breaking chances for some users. I will evaluate.

**Comment by kylekatarnls** [comment]
Will be changed in 3.0.0
