### ISSUE TITLE
Symfony 7.0 support

### ISSUE THREAD

**Issue by eman1986** [briannesbitt/Carbon#2914]
Hello,

I recently tried to upgrade to Symfony 7, but it claims you don't support that, which stalled my upgrade.

Carbon version: **2.72.1**

PHP version: **8.3.1**

I expected to upgrade to Symfony 7.

But I got told I can't because Carbon is using an older version of a symfony component.

Thanks!

**Comment by eman1986** [comment]
I see the dev wants you to use 3.0

**Comment by kylekatarnls** [comment]
v3 compatibility with Laravel is now being checked: laravel/framework#49764

If you are on Laravel or have a composer constraint in your project needed carbon v2, you can still try the v3 using:

```
composer require "nesbot/carbon:3.x-dev as 2.99"
```

Do not hesitate to give it a try, your help in testing this new version will be gratefully welcome. The more it can be tested, the faster it will reach the stable release.
