### ISSUE TITLE
make symfony 7 compatible

### ISSUE THREAD

**Issue by op-euga** [briannesbitt/Carbon#2915]
Hello,

I wanted to update my symfony from 6.4 to 7.0. But composer complains with the following line:
```
Your requirements could not be resolved to an installable set of packages.
``` 

I encountered an issue with the following code:

```php
composer update
```

Carbon version: 2.72.1

PHP version: 8.2.5

I expected to get:

```
composer update work with symfony 7.0 packages
```

But I actually get:

```
Problem 1
    - nesbot/carbon[2.67.0, ..., 2.72.1] require symfony/translation ^3.4 || ^4.0 || ^5.0 || ^6.0 -> found symfony/translation[v3.4.0, ..., v3.4.47, v4.0.0, ..., v4.4.47, v5.0.0, ..., v5.4.31, v6.0.0, ..., v6.4.2] but these were not loaded, likely because it conflicts with another require.
    - Root composer.json requires nesbot/carbon ^2.67 -> satisfiable by nesbot/carbon[2.67.0, ..., 2.72.1].

```

Thanks!

**Comment by kylekatarnls** [comment]
https://github.com/briannesbitt/Carbon/issues/2891#issuecomment-1833498351

**Comment by kylekatarnls** [comment]
v3 compatibility with Laravel is now being checked: laravel/framework#49764

If you are on Laravel or have a composer constraint in your project needed carbon v2, you can still try the v3 using:

```
composer require "nesbot/carbon:3.x-dev as 2.99"
```

Do not hesitate to give it a try, your help in testing this new version will be gratefully welcome. The more it can be tested, the faster it will reach the stable release.

**Comment by op-euga** [comment]
> v3 compatibility with Laravel is now being checked: [laravel/framework#49764](https://github.com/laravel/framework/pull/49764)
> 
> If you are on Laravel or have a composer constraint in your project needed carbon v2, you can still try the v3 using:
> 
> ```
> composer require "nesbot/carbon:3.x-dev as 2.99"
> ```
> 
> Do not hesitate to give it a try, your help in testing this new version will be gratefully welcome. The more it can be tested, the faster it will reach the stable release.

No I'm using symfony and the nesbot/carbon:3.x-dev is working. But I would rather wait until the final 3.x version is released. When will this be?

**Comment by kylekatarnls** [comment]
Our timeline will be synchronized with the Laravel one so to take advantage of people testing Laravel 11 nightly build to also test Carbon 3. If no major issue is detected during those tests, Carbon 3 will become stable before Laravel 11 stable is released (planned for February 6th, 2024). In any other case, we'll propose the upgrade for Laravel 12 but won't wait for it to be released, then it would probably happen in March.

**Comment by op-euga** [comment]
Thx for this info
