### ISSUE TITLE
[Lang - hu] - Wrong short form (Február)

### ISSUE THREAD

**Issue by dvidke** [briannesbitt/Carbon#2917]
Hello,

I encountered an issue with the following line of code:

[https://github.com/briannesbitt/Carbon/blob/master/src/Carbon/Lang/hu.php#L85](https://github.com/briannesbitt/Carbon/blob/master/src/Carbon/Lang/hu.php#L85)

Carbon version: **2.72.0**

PHP version: **8.1.13**

The line should be contain this:

```
'months_short' => ['jan.', 'febr.', 'márc.', 'ápr.', 'máj.', 'jún.', 'júl.', 'aug.', 'szept.', 'okt.', 'nov.', 'dec.'],
```

Instead of this:

```
'months_short' => ['jan.', 'feb.', 'márc.', 'ápr.', 'máj.', 'jún.', 'júl.', 'aug.', 'szept.', 'okt.', 'nov.', 'dec.'],
```

The difference is that the grammar correct short form of `február` is `febr.`, not `feb.` ([proof](https://www.arcanum.com/hu/online-kiadvanyok/Lexikonok-magyarorszag-a-masodik-vilaghaboruban-lexikon-a-zs-F062E/roviditesek-jegyzeke-F06BE/)).

Thanks!

**Comment by kylekatarnls** [comment]
Thanks for the report.

Feel free (you or anyone) to modify [the file pointed here](https://github.com/briannesbitt/Carbon/blob/master/src/Carbon/Lang/hu.php#L85) and submit a pull-request.
