### ISSUE TITLE
[Translation tool] uk_UA

### ISSUE THREAD

**Issue by LogicEveryWhere** [briannesbitt/Carbon#2919]
|English|uk_UA|comments|
|--|--|--|
|2yrs|2р|this should rather be "2 рр" because "2 р" used in Ukrainian language as a shorten for singular form and plural most common way to use is "2 рр" |

**Comment by kylekatarnls** [comment]
Hi, thanks for you help, is there any source where we can see it used? (Gov site, school site)?

**Comment by LogicEveryWhere** [comment]
Sure, 
non official but common used dictionary 
https://slovnyk.ua/pravopys.php?prav_par=62_1
search on page ("рр.")

This is web site of "Mykolaiv National Agriculture University" they do have PDF copy of the state standart of Ukraine of for abbreviation of words in the ukrainian language in bibliographical description  
https://lib.mnau.edu.ua/info5/Skorochen_sliv.pdf
search on page by ("рр") -> document page 2

This is example of usage on The Verkhovna Rada of Ukraine which is the unicameral parliament of Ukraine
https://www.rada.gov.ua/news/Novyny/245363.html
Just on title in brackets

https://www.rada.gov.ua/news/news_kom/245540.html
last link of the page content or search on page ("рр")

**Comment by LogicEveryWhere** [comment]
This popular news site 
https://life.pravda.com.ua/columns/2023/12/27/258544/
search on page ("рр") in author role description

**Comment by kylekatarnls** [comment]
Thanks, last question, does it apply to both `роки` and `років` plurals?

**Comment by LogicEveryWhere** [comment]
sorry for the late answer, I believe only "років"
"роки" is a very particular and specific case. So let's not overcomplicate things =)

**Comment by LogicEveryWhere** [comment]
"років" is for any range of years
"роки" applies for 2,3,4 and probably some other exceptions
