### ISSUE TITLE
createFromFormat() weird output with format 'Y-m' in february

### ISSUE THREAD

**Issue by Mehdimed** [briannesbitt/Carbon#2930]
Hello,

I encountered an issue with the following code:
```php
echo Carbon::createFromFormat('Y-m', '2023-02');
```

Carbon version: 2.72.2

PHP version: 8.2

https://play.phpsandbox.io/nesbot/carbon?version=3.0.0.0-beta3&input=%3C%3Fphp%0A%0Aecho%20Carbon%3A%3AcreateFromFormat(%27Y-m%27%2C%20%272023-02%27)%3B

I expected to get:

```
2023-02-28 12:14:58
```
But I actually get:

```
2023-03-03 12:14:58
```
i'm trying to guess what's going on here, by default the `createFromFormat()` method when used with the 'Y-m' format, will add 30 or 31 as days and as there's only 28 days in february , the date become march the 3rd or march the 2nd during leap year.

Thanks!

(I haven't time to check if this issue has already been opened , and sorry if it's normal behavior and just me that did not read correctly the documentation)

**Comment by kylekatarnls** [comment]
Hello,

This behavior is directly inherited from `DateTime::createFromFormat('Y-m', '2023-02')`

Use `'!Y-m'` to reset the day (see PHP doc for operator explanation: https://www.php.net/manual/en/datetimeimmutable.createfromformat.php)

Duplicates https://github.com/briannesbitt/Carbon/issues/1003#issuecomment-370336838
