### ISSUE TITLE
3.0.0-rc2 rollback on dependency versions

### ISSUE THREAD

**Issue by paullallier** [briannesbitt/Carbon#2932]
3.0.0-rc2 seems to be using the dependencies from 2.x, rather than 3.x - I'm assuming that wasn't intended?

**Comment by kylekatarnls** [comment]
Sorry for that, yes, the tag is from the wrong branch. [3.0.0-rc.3](https://github.com/briannesbitt/Carbon/releases/tag/3.0.0-rc.3) created instead.
