### ISSUE TITLE
File existence should be checked before attempting include

### ISSUE THREAD

**Issue by miken32** [briannesbitt/Carbon#2933]
Hello,

I encountered an issue with the following code:

```php
Carbon::setLocale("en_US.utf8");
```

Carbon version: 2.66.0

PHP version: 8.2.14

I expected to get:

```
Quiet logs
```

But I actually get:

```
[02-Feb-2024 17:15:28 America/Toronto] PHP Warning: include(vendor/nesbot/carbon/src/Carbon/Lang/en_US.utf8.php): Failed to open stream: No such file or directory in vendor/nesbot/carbon/src/Carbon/AbstractTranslator.php on line 163
[02-Feb-2024 17:15:28 America/Toronto] PHP Warning: include(): Failed opening 'vendor/nesbot/carbon/src/Carbon/Lang/en_US.utf8.php' for inclusion (include_path='.:/usr/share/pear:/usr/share/php:/usr/local/lib/php') in vendor/nesbot/carbon/src/Carbon/AbstractTranslator.php on line 163
```

This could be resolved with a simple `file_exists()` check before attempting to include the file in `Carbon\AbstractTranslator::resetMessages()`

Thanks!

**Comment by kylekatarnls** [comment]
Hello,

It does not happen with an error handler correctly configured to respect `error_reporting()`.

Check in your framework/application what is configuring the error handler (by calling `set_error_handler`)

It should start by checking that the error needs to be reported with something like:
```php
set_error_handler(function ($errno, $errstr, $errfile, $errline) {
    // mute-operator was used or error was explicitly set not to be reported as per the error level
    if (!(error_reporting() & $errno)) {
        return false;
    }
   // ...
```

Side note: the `2.66.0` version wouldn't receive a fix anyway, minor receive only security patches, features and normal bugfixes are released only on 2.x and 3.x stream for some times, then soon only on 3.x stream. It's generally not recommended to pin a minor version, you should consider updating regularly to the latest of `^2` (so 2.72.3 currently), then consider to upgrade to `^3`.

Thanks.

**Comment by miken32** [comment]
Well I don't have the ability to change error handlers or Composer settings (it's a third party app we use) but a check should be how it's done regardless; the error suppression operator has been a hacky solution for years.

**Comment by kylekatarnls** [comment]
Loggers must not ignore `error_reporting()`, the code above is given in PHP documentation itself: https://www.php.net/manual/en/function.set-error-handler.php

It's meant to be handled this way.

BTW, you should call `Carbon::setLocale("en_US");` (`.utf8` has no meaning for Carbon locale, all our language files are UTF-8) and then you would not have any error logged. You can easily trim this encoding from the string:

```php
$locale = "en_US.utf8";
Carbon::setLocale(preg_replace('/^([^.]+)\..*$/', '$1', $locale));
```
