### ISSUE TITLE
Proposal to remove hard dependency on carbonphp/carbon-doctrine-types

### ISSUE THREAD

**Issue by arokettu** [briannesbitt/Carbon#2939]
What does a DateTime library achieve by depending on a relatively huge DB lib that is not used by everybody?

**Comment by kylekatarnls** [comment]
This is already in the roadmap: #1681

**Comment by kylekatarnls** [comment]
Side note is it `carbonphp/carbon-doctrine-types` that you call a "relatively huge DB lib"? 👀 It's like 7 files of 10 lines of code. 🤷

**Comment by arokettu** [comment]
@kylekatarnls No, I mean Doctrine itself of course
It gave me conflicts when I was updating Doctrine (on a project that uses it) so I thought that carbonphp/carbon-doctrine-types depends on it, now I see the declaration where it is in a "conflicts" section, sorry
