### ISSUE TITLE
PHPDoc on `CarbonImmutable::createFromFormat` incompatible with actual return type

### ISSUE THREAD

**Issue by BusterNeece** [briannesbitt/Carbon#2945]
Carbon 3.0.2

The phpdoc annotation here:

https://github.com/briannesbitt/Carbon/blob/cc733884b9f619100e3b499f064afd4b5276dd28/src/Carbon/CarbonImmutable.php#L819

is incompatible with the actual return type from the `Creator` trait:

https://github.com/briannesbitt/Carbon/blob/cc733884b9f619100e3b499f064afd4b5276dd28/src/Carbon/Traits/Creator.php#L630-L642

If you have static analysis tools that trust the phpdoc annotations (i.e. phpstan), it'll throw that a comparison against `null` is invalid, even though the actual returned value can be `null`.

**Comment by kylekatarnls** [comment]
Thanks for report. Actually method that are declared in traits shouldn't be at all in the list of `@method` only methods that exist via `__call` should be there, it's a exclusion mistake from the doc generator.

**Comment by BusterNeece** [comment]
Thank you!
