### ISSUE TITLE
[Translation tool] bg

### ISSUE THREAD

**Issue by nosorrow** [briannesbitt/Carbon#2951]
|English|bg|comments|
|--|--|--|
|2w|2 седмици|This should rather be |2w|2 седм.| because it is short in bulgarian language|
|2d|2 дни|This should rather be |2d|2 д.| because it is short in bulgarian language|

**Comment by kylekatarnls** [comment]
Alternative translation sounds to be missing, I will re-open if suggested replacements are provided.
