### ISSUE TITLE
Method isFuture returns an incorrect result

### ISSUE THREAD

**Issue by Brenneisen** [briannesbitt/Carbon#2952]
Hello,

I encountered an issue with the following code:

```php
echo Carbon::parse('2024-02-29')->isFuture();
```

Carbon version: 2.72.3

PHP version: 8.2.14

I expected to get:

```
true
```

But I actually get:

```
false
```

Thanks!

**Comment by kylekatarnls** [comment]
Documentation of the method explicitly state reference point is `now`, not `Today`, and examples using hours demonstrates the granularity of it:

> Determines if the instance is in the future, ie. greater (after) than now.
> 
> Example:
> ```
> Carbon::now()->addHours(5)->isFuture(); // true
> Carbon::now()->subHours(5)->isFuture(); // false
> ```

Side note, you can easily exclude Today as a special case:

```php
$february29Midnight = Carbon::parse('2024-02-29');

if ($february29Midnight->isToday()) {
  echo 'Happily working 1 more day this year :D';
} elseif ($february29Midnight->isFuture()) {
  echo 'It's still after Today";
} else {
  echo 'It's before Today";
}
```

**Comment by Brenneisen** [comment]
Nevermind. I thought today was 28.02. I'm sorry.
