### ISSUE TITLE
Both Hong Kong and Macao are the Special Administrative Regions of China

### ISSUE THREAD

**Issue by Eno-CN** [briannesbitt/Carbon#2961]
### A widely-used open-source package SHOULD NOT be tainted by political colors.

https://github.com/briannesbitt/Carbon/blob/237716a15fcd4f25e26b80bfa3bf3d7a2827a3b1/src/Carbon/List/regions.php#L112
```diff
- 'HK' => 'Hong Kong,'
+ 'HK' => 'Hong Kong Special Administrative Region of the People's Republic of China',
```

https://github.com/briannesbitt/Carbon/blob/237716a15fcd4f25e26b80bfa3bf3d7a2827a3b1/src/Carbon/List/regions.php#L165
```diff
- 'MO' => 'Macao,'
+ 'MO' => 'Macao Special Administrative Region of the People's Republic of China',
```

**Comment by Eno-CN** [comment]
The integrity of a country’s national sovereignty is inviolable.

**Comment by kylekatarnls** [comment]
This list contains ISO-3166 short name, not the complete official state name. It's not meant to have any official value, it's not the right tool to use if you looking for an official country name list.

**Comment by Eno-CN** [comment]
> This list contains ISO-3166 short name, not the complete official state name. It's not meant to have any official value, it's not the right tool to use if you're looking for an official country name list.
> 

#2956 Since that's the case, why doesn't this comply with ISO standards? Isn't this a double standard?

**Comment by kylekatarnls** [comment]
I plan to cleanup everything and provide more details about this list: https://github.com/briannesbitt/Carbon/pull/2964/files#diff-a68ceb12a08fd412313da820e33452b16a568c4fa794bf160e2999148c0e066cR15

We want short names here, 70 characters-long names for single cities is in all good faith overkill.

But to summarize it, if this list does not meet your need, just don't use it.

**Comment by Eno-CN** [comment]
> I plan to cleanup everything and provide more details about this list: https://github.com/briannesbitt/Carbon/pull/2964/files#diff-a68ceb12a08fd412313da820e33452b16a568c4fa794bf160e2999148c0e066cR15
> 
> We want short names here, 70 characters-long names for single cities is in all good faith overkill.
> 
> But to summarize it, if this list does not meet your need, just don't use it.

Okay, thank you for treating this matter equally. And sincerely thank you for your contribution to the PHP open source community ecosystem.
