### ISSUE TITLE
Can no longer use `createFromFormat` with an non-string value as time input

### ISSUE THREAD

**Issue by Sn0wCrack** [briannesbitt/Carbon#2967]
Hello,

I encountered an issue with the following code after upgrading to Carbon v3 as part of the Laravel 11 upgrade:

```php
CarbonImmutable::createFromFormat('U', 1709589519);
```

Carbon version: 3.1.1

PHP version: 8.3

I expected to get:

A CarbonImmutable object is successfully created.

But I actually get:

An exception thrown with the following message:

```
Carbon\CarbonImmutable::rawCreateFromFormat(): Argument #2 ($time) must be of type string, int given, called in /home/vagrant/atlas/vendor/nesbot/carbon/src/Carbon/Traits/Creator.php on line 647

```

Unfortunately most of this code happens out of my control inside a library I'm using (spatie/laravel-data), which this previously used to work fine with in Carbon v2. I am aware this should probably be handled better by `::createFromTimestamp` or via just casting to string.

I'm assuming this is due to added types on the `::rawCreateFromFormat` function or the addition of strict types on these files.

**Comment by kylekatarnls** [comment]
Hello,

This is because of the (expected) switch to strict types in Carbon 3, this method is from PHP DateTime itself
https://www.php.net/manual/fr/datetime.createfromformat.php

And `int` is not accepted. (`string` has been enforced since PHP 8)

It's converted to `string` before given to `DateTimeImmutable::createFromFormat` anyway so I'd recommend to pass only string there:

`CarbonImmutable::createFromFormat('U', (string) 1709589519);`

But if you format is not dynamic, it's even better to use the method:
```php
CarbonImmutable::createFromTimestampUTC(1709589519);
```
That is super explicit about what it takes and give unlike the `U` that needs some doc or by-heart knowledge.

**Comment by Sn0wCrack** [comment]
That was my assumption relating to switching over to strict-typing in the library.

In this case the library I'm using, spatie/laravel-data, takes in a list of format strings and attempts to create a CarbonImmutable instance using createFromFormat on the given value, and in certain cases it is an integer timestamp stored in our database, so I don't have a ton of control over that flow.

In this case I have found a work around and created my own custom cast for these dates and instead use the parse method, which seems to work fine. I will probably bring this issue to them as well.

However, couple thing I will note though:
- Because the `createFromFromat` function in Carbon accepts a mixed typing for the time input, the `rawCreateFromFormat` method is what throws this error, as its what actually explicitly requires a string for the time input, so the issue is not immediately obvious in that regard.
- `createFromTimestamp` and the related functions allow passing through float, int and string
- In my own project code without strict typing enabled, using `DateTimeImmutable::createFromFormat('U', 1709589519);` doesn't throw any warnings or errors so the user-experience of the Carbon seems to different form native in that regard.

**Comment by kylekatarnls** [comment]
> In this case the library I'm using, spatie/laravel-data, takes in a list of format strings and attempts to create a CarbonImmutable instance using createFromFormat on the given value, and in certain cases it is an integer timestamp stored in our database, so I don't have a ton of control over that flow.

I see the point, spatie's good friend :) I think we can arrange that on spatie/laravel-data side.

I agree the fact that Carbon::createFromFromat type is not updated is a mistake and prevent the script-type to propagate all way long.

> createFromTimestamp and the related functions allow passing through float, int and string

Is it an issue?

**Comment by Sn0wCrack** [comment]
> 
> > createFromTimestamp and the related functions allow passing through float, int and string
> 
> Is it an issue?

Sorry I should have expanded on this point more, however I don't think it matters a ton now, as I've realized that typing the `createFromFormat` function would actually fix this issue by causing non-strict typed code to automatically cast the integer input into a string before passing it through to the function.

I've also opened an issue on the spatie/laravel-data repo about this as well.

**Comment by UtkuDalmaz** [comment]
It also throws an exception in Filament's DatePicker component.
