### ISSUE TITLE
Error addRealSeconds

### ISSUE THREAD

**Issue by ArtyshkoAndrey** [briannesbitt/Carbon#2968]
Hello, pls fixx >addRealSeconds method

I encountered an issue with the following code:

```php
echo Carbon\Carbon::now()->addRealSeconds(90)->getTimestamp();;
```

Carbon version: 3.1.1
PHP version: 8.3

![image](https://github.com/briannesbitt/Carbon/assets/22916635/7722a452-6475-4c07-92df-ff45062ca0cf)

I expected to get:

Thanks!

**Comment by kylekatarnls** [comment]
Hello,

I can't reproduce here, it does not fail neither in unit tests.

Do you reproduce if you create a file with only this:

```php
<?php

require __DIR__ . '/vendor/autoload.php';

echo \Carbon\Carbon::now()->addRealSeconds(90)->getTimestamp();
exit;
```

And no code executed before? I suspect you might have something such as `Carbon::setTestNow('1970-01-01 00:0 UTC')` in such case, then `90` would be the expected output.

**Comment by ArtyshkoAndrey** [comment]
But in version 3.0 methods has work correct. Sorry my English. In version 3.0 method return real timestamp, but 3.1 return int or string non-timestamp

**Comment by ArtyshkoAndrey** [comment]
After run addRealSeconds, timestamp not correct

**Comment by ArtyshkoAndrey** [comment]
Sorry. True, in version 3.1 and higher the script works correctly. Apparently there are problems in Laravel ^11.0
