### ISSUE TITLE
The output of diffInMonths is indeed incorrect

### ISSUE THREAD

**Issue by rakibhasansabbir** [briannesbitt/Carbon#2970]
Hello,

I encountered an issue with the following code:

```php
$date1 = Carbon::now();
$date2 = Carbon::now();

echo $date1->diffInMonths($date2);;
```

Carbon version: **3.1.1**

PHP version: **8.2**

Laravel version: **11.0.7**

I expected to get:

```
0
```

But I actually get:

```
4.0190106033453E-6
```

Thanks!

**Comment by kylekatarnls** [comment]
Hello, code is not executing instantly, so there are few microseconds elapsed between $date1 and $date2

You can use the PHP function floor() if you don't want the decimal part.
