### ISSUE TITLE
Daylight Savings for Europe/Dublin is incorrect

### ISSUE THREAD

**Issue by Mikiiw** [briannesbitt/Carbon#2978]
Hello,

I encountered an issue with the following code:

```php
Carbon::createFromDate(2012, 1, 1, 'Europe/Dublin')->isDST()
```

Carbon version: * 2.69.0

PHP version: 8.2.15

I expected to get:

```
false
```

But I actually get:

```
true
```

I've checked over the daylight savings time in Dublin

https://www.timeanddate.com/time/change/ireland/dublin

and the DST should line up with UK standard timezones. However this is flipped

I've checked on the latest pull and this issue still persists

Thanks!

**Comment by kylekatarnls** [comment]
Hello, it's the other way round:

```php
var_dump(Carbon::createFromDate(2012, 1, 1, 'Europe/Dublin')->isDST()); // true
var_dump(Carbon::createFromDate(2012, 6, 1, 'Europe/Dublin')->isDST()); // false
```
October to March is the "daylight saving time" period.

For the record, I'm not making the rule, it's baiscally `DateTime::format('I')` result.
![image](https://github.com/briannesbitt/Carbon/assets/5966783/c89ebacd-6aa0-4d3d-8d1f-87ca0aa4d8f5)

**Comment by Mikiiw** [comment]
@kylekatarnls 

![chrome_GjXYSWBzxq](https://github.com/briannesbitt/Carbon/assets/32526912/02333c37-e91c-4d90-8da6-ba56a0ddbe64)

I'm expecting 1st January 2012 to output false for Europe/Dublin

```
        dump((new \DateTime('now', new DateTimeZone('Europe/Dublin')))->setDate(2012, 7, 1)->getOffset()); // 0
        dd((new \DateTime('now', new DateTimeZone('Europe/Dublin')))->setDate(2012, 1, 1)->getOffset()); // 3600
```

So this above output is correct

If thats the case, `isDST()` is outputting the reverse of the logic above

**Comment by kylekatarnls** [comment]
Oh my gosh, it's worse that what I though.

It's indeed an exception for Dublin:
https://bugs.php.net/bug.php?id=81072
https://stackoverflow.com/questions/52586311/php-dst-detection-via-date-has-reversed

For other timezones, the `isDST()` is matching https://www.timeanddate.com/ and other sources.

**Comment by Mikiiw** [comment]
Digging into this and its definitely outside the scope of code implementation for us, pretty interesting stuff though
