### ISSUE TITLE
Period `start` and `end` always wrong with Carbon 3

### ISSUE THREAD

**Issue by bakerkretzmar** [briannesbitt/Carbon#2982]
In Carbon 3 the `start` and `end` properties of a CarbonPeriod or CarbonPeriodImmutable are always `2000-01-01` and `null`.

[Sandbox example.](https://play.phpsandbox.io/nesbot/carbon/mN7g4E1kZgKWn281)

Code to reproduce the issue:

```php
[
    Carbon::parse('Sep 1')->toPeriod('Sep 30')->start,
    Carbon::parse('Sep 1')->toPeriod('Sep 30')->end,
];
```

Carbon version: **3.1.1**

PHP version: **8.2.15**

Expected (and what Carbon 2 returns):

```php
[
    '2024-09-01 00:00:00', // Carbon\Carbon instance
    '2024-09-30 00:00:00', // Carbon\Carbon instance
];
```

Received:

```php
[
    '2000-01-01 00:00:00', // DateTime instance
    null,
];
```

**Comment by kylekatarnls** [comment]
It's because now `CarbonPeriod` extends `DatePeriod` but readonly cannot be controlled from sub-class.

I recommend you use the getters:
```php
[
    Carbon::parse('Sep 1')->toPeriod('Sep 30')->getStartDate(),
    Carbon::parse('Sep 1')->toPeriod('Sep 30')->getEndDate(),
];
```

**Comment by kylekatarnls** [comment]
We can make it correct at creation and then `CarbonPeriodImmutable` would be compatible including start and end properties, the issue will be that for `CarbonPeriod` start and end can be changed after creation but the properties would sill contain the old values.

**Comment by bakerkretzmar** [comment]
Thanks! 🙏🏻
