### ISSUE TITLE
Carbon v3 Documentaion for diffIn* methods

### ISSUE THREAD

**Issue by Nathanjms** [briannesbitt/Carbon#2986]
Hi,

In carbon v3, the `diffIn*` methods now return float instead of int, and this is nicely explained in the documentation:

![image](https://github.com/briannesbitt/Carbon/assets/64075030/8e6db278-26ae-4304-8d31-59b9642f17f5)

However, in the Reference, it still gives definitions such as "Get the difference in days rounded down." for `Carbon::diffInDays`. Could this make more sense to be changed to just "Get the difference in days.", because it no longer is rounding this down, and is instead a float?

See Reference:
![image](https://github.com/briannesbitt/Carbon/assets/64075030/6ac58ecc-43bb-42e3-9ceb-e0b6a9f464f0)

Thanks!

**Comment by kylekatarnls** [comment]
Definitely! Thank you for notifying me. 🙏

**Comment by Nathanjms** [comment]
> Definitely! Thank you for notifying me. 🙏

Great, I've just done a PR (#2988) that I think covers these changes, but please let me know if anything else needs doing!
