### ISSUE TITLE
[Translation tool] bs

### ISSUE THREAD

**Issue by sehic-ademir** [briannesbitt/Carbon#2990]
|English|bs|comments|
|--|--|--|
|2 weeks|2 sedmicu|This should rather be 2 sedmice because that is plural of sedmica|
|2w|2 sedmicu|This should rather be 2 sedmice because that is plural of sedmica|
|1 week|1 sedmice|This should rather be 1 sedmica because that is singular of sedmica|
|a week|1 sedmice|This should rather be 1 sedmica because that is singular of sedmica|

----
Above fix suggestions are for week singular and plural
It follows the same rules as Serbian, which is correct here
2 nedelje = 2 sedmice
1 nedelja = 1 sedmica

**Comment by kylekatarnls** [comment]
Hello, 👋 Thanks for your help.

So:
```
:count sedmice|:count sedmicu|:count sedmica
```
Would become:
```
:count sedmica|:count sedmice|:count sedmica
```

But is it like in Serbian that we should keep the first variants when "2 weeks" is in "2 weeks ago" or "2 weeks from now"?

BTW I see Bosnian also use `:count godina|:count godine|:count godina` like in Serbian.

Does it means that in conext of ago/from now, it should use the same as Serbian, i.e.:
```
:count godinu|:count godine|:count godina
```

**Comment by sehic-ademir** [comment]
Hello, it would be
prije 1 sedmicu|prije 2 sedmice|prije 10 sedmica

All rules from serbian should apply to bosnian
