### ISSUE TITLE
diffInDays returns a float

### ISSUE THREAD

**Issue by pimoudeveldhuis** [briannesbitt/Carbon#2998]
Hello,

I encountered an issue with the following code:

```php
echo Carbon::parse('2018-06-01')->diffInDays(Carbon::parse('2018-06-01'));
```

Carbon version: 3.2.2

PHP version: 8.2

I expected to get:

```
0 (integer)
```

But I actually get:

```
0.0 (double)
```

In the sandbox this code:
```
<?php
    var_dump(Carbon::parse('2018-06-01')->diffInDays(Carbon::parse('2018-06-01')) );

    var_dump(0);
    var_dump(0.0);
```

Gives:
```
phar:///var/psysh.phar/src/ExecutionClosure.php(16) : eval()'d code:4:
double(0)
phar:///var/psysh.phar/src/ExecutionClosure.php(16) : eval()'d code:5:
int(0)
phar:///var/psysh.phar/src/ExecutionClosure.php(16) : eval()'d code:6:
double(0)
```

The documentation shows it should be an integer, but the function itself returns a float:
```
public function diffInDays($date = null, bool $absolute = false, bool $utc = false): float
```

I did read the text above the documentation saying it diffIn returns a float, but the example below that text shows an int:
```
echo $dt->diffInDays($dt->copy()->addMonth());                         // 30
```

While the examples with the floatDiffInDays does show floats:
```
echo Carbon::parse('2000-01-01 12:00')->floatDiffInDays('2000-02-11 06:00');     // 40.75
```

I guess the example isn't updated in the documentation, but I also do not see the need to return a float if the return value is always rounded to a full day.

Please advise.

Thanks!

**Comment by kylekatarnls** [comment]
Hello,

From [Migrate to Carbon 3](https://carbon.nesbot.com/docs/#api-carbon-3) section of the documentation:

> **diffIn**
> They were returning positive integer by default, they will now return float

**Comment by kylekatarnls** [comment]
> that text shows an int

Actually no, that's how 30.0 displays when you use `echo`, it just outputs `30`

However we could remove `floatDiffInDays` from the docs and just mention once, that `float*` are just there for backward-compatibility in v3 but no longer make sense to be used.

**Comment by pimoudeveldhuis** [comment]
Thanks for your quick response. Although completely true that the echo shows 30 and not 30.0, when using an integer to represent a float because the echo shows it that way and having a float just below that is a bit confusing. Not saying you're wrong, but although echo removes the trailing .0 I think it would be better if the examples show the correct representation of the variable instead of the result of an echo.

We stumbled upon this because $diff === 0 is false when $diff is 0.0.

**Comment by kylekatarnls** [comment]
The results in comments shown in the documentation are auto-generated:

```
{{::exec(echo $dt->diffInDays($dt->copy()->addMonth());/*pad(70)*/)}} // {{eval}}
```
So `{{eval}}` contains the exact result of the code in the `exec()` this should automated as a matter of accuracy but we could use `var_dump` instead.

> We stumbled upon this because $diff === 0 is false when $diff is 0.0.

Yes, that's a breaking change, I would also highlight that previously a `diffInDays` of an interval of 23 hours and 59 minutes was giving you `int(0)`, it's now returning `double(0.9993)` which is the main reason for this breaking change. I encourage you to revisit all the calls to `->diffIn*` methods, as the v2 behavior might have lead to unnoticeable bugs/inaccuracy. And so you'll probably get your thing working as before by just wrapping diffs in `(int) abs()` but it's a good opportunity to check if this is actually what makes the more sense in your context, or if floating numbers (such as a diff >0 && <1), or negative value should be handled.

**Comment by pimoudeveldhuis** [comment]
We are using this function to calculate the amount of overnights, so we are looking for something that gives us the amount of nights and not so much the amount of time in a day, but we now solve this by first using the startOfDay on all objects and then calculate (and now cast to integer) the diffInDays.

Thank you for the explanation and keep up the good work :)

**Comment by kylekatarnls** [comment]
> we are looking for something that gives us the amount of nights and not so much the amount of time in a day

Indeed `diffInDays` does not provide that as it (but it was not providing it neither in v2). And indeed assuming both objects are in the same timezone, you get a calendar diff with:

```php
(int) $start->startOfDay()->diffInDays($end);
```
If `$start <= $end` then it's not needed to call `->startOfDay()` on `$end` as the  cast ti `int` will floor the result.

**Comment by pimoudeveldhuis** [comment]
Yep that is exactly what we are doing at the moment :)

Thank you and keep up the good work :)
