### ISSUE TITLE
Not working after download zip file

### ISSUE THREAD

**Issue by Alex-Basto** [briannesbitt/Carbon#3000]
Problema ao descompactar arquivo ZIP da versão 3.2.4 e anteriores, arquivo apos descompactado ficam com esses ponto (imagem) e o PHP não localiza os arquivos

ENGLISH: Problem when decompressing ZIP files from version 3.2.4 and earlier, after decompressing the file they have these dots (image) and PHP does not locate the files

![image](https://github.com/briannesbitt/Carbon/assets/52386938/263ed7d4-9de6-4b67-9c5e-762e0741324a)

**Comment by kylekatarnls** [comment]
Sounds like an issue with the program you use to extract it. Can you try this one with normalized paths?
[Carbon-3.2.4.zip](https://github.com/briannesbitt/Carbon/files/15027061/Carbon-3.2.4.zip)
