### ISSUE TITLE
Invalid CarbonInterval->format() results for Carbon 3 (unknown).

### ISSUE THREAD

**Issue by jifer** [briannesbitt/Carbon#3003]
Hello,

I encountered an issue with the following code:

```php
$past = new \DateTime('-3 Days');
$today = new \DateTime('today');
$interval = $today->diff($past);

var_dump($interval->format('%a')); // string(1) "2"

$past = new CarbonImmutable('-3 Days');
$today = new CarbonImmutable('today');
$interval = $today->diff($past);

var_dump($interval->format('%a')); // string(9) "(unknown)"
```

Carbon version: 3.0.0 to 3.3.0 (Carbon v2 returned correct values)

PHP version: 8.2

I expected to get:

```
Valid number of days: 2 in previous example.
```

But I actually get: 

```
(unknown)
```

Thanks!

**Comment by kylekatarnls** [comment]
Hello,

I will investigate if we can put back this support and keep the other benefits of `CarbonInterval`, for the record, in Carbon v2 `diff` was giving a `DateInterval`n in v3, it's now equivalent to the v2 `diffAsCarbonInterval` method, and this object is not directly created from the `diff` so miss the total number of days at the moment.

However you can work around this for now using:
```php
$past = new CarbonImmutable('-3 Days');
$today = new CarbonImmutable('today');
$interval = $today->diffAsDateInterval($past);
```

**Comment by jifer** [comment]
First of all, please take my apologies. I didn't ment to disrespect anyone. I do have full respect for anyone working for community purpose and open source liblaries.

I do know reasons why diff changes was introduced. But also It is noticable that this changes are discussed by many and considered as drastic.
We, as users, put our trust in project like this and we choose such free solution to help us in our day to day task. After years of using Carbon in specific project it is really hard to change such library. Thus it is hard to get over that we was forced to take this approches:
- do not update framework and stay on C2
- upgrade framework and Carbon with all the consequences 

Am I not legitimate to criticize decisions made just because it is open source? Maybe not. But i did.

----

About the issue. I did some research before posting.

`%a` is based on `$days` which is set while using `diff` method on `\DateTime` instance. `diffAsCarbonInterval` is not using core `diff` method (and that understandable).
`\DateInterval` instance created by constructor has `$days = false`.
But you already know all of this considering this comment from `CarbonInterval::instance`
```
     * Create a CarbonInterval instance from a DateInterval one.  Can not instance
     * DateInterval objects created from DateTime::diff() as you can't externally
     * set the $days field.
 ```
Maybe someone knowing this library better than me (or smarter than me) will find better solution than overriding `format` method to use other parameter than `days` to display `%a` result.

With best regards.

**Comment by jifer** [comment]
Thank you for your time to respond.
Hope someone will find way to fix above. I do prefer to be on time with libraries thus we will take time to upgrade all places with workarounds or other methods.

With regards.

**Comment by kylekatarnls** [comment]
So I took the path to override `format`, `->days` will still not be usable, but `->format('%a')` will returns (once #3031 is merged) what `DateInterval::format` would have returned as soon as the interval was created from a `diff()`.

**Comment by jifer** [comment]
Seeing PR im glad I didn't do it by myself. Without knowing library and its nuances my resolution wouldn't be fully correct. Thank you for fix & your support.
