### ISSUE TITLE
It is not possibble to upgrade Symfony 6.4 to 7.0 without upgrading Carbon from 2 to 3

### ISSUE THREAD

**Issue by jifer** [briannesbitt/Carbon#3004]
Hello,

It is not possibble to upgrade Symfony 6.4 to 7.0 without upgrading Carbon from 2 to 3.

Composer result:
```
  Problem 1
    - Root composer.json requires nesbot/carbon ^2.72.3 -> satisfiable by nesbot/carbon[2.72.3].
    - nesbot/carbon 2.72.3 requires symfony/translation ^3.4 || ^4.0 || ^5.0 || ^6.0 -> found symfony/translation[v3.4.0, ..., v3.4.47, v4.0.0, ..., v4.4.47, v5.0.0, ..., v5.4.35, v6.0.0, ..., v6.4.4] but it conflicts with your root composer.json require (^7.0).
```

Requirements for latest Carbon **2.72.3**
```
 "require": {
        "php": "^7.1.8 || ^8.0",
        "ext-json": "*",
        "carbonphp/carbon-doctrine-types": "*",
        "psr/clock": "^1.0",
        "symfony/polyfill-mbstring": "^1.0",
        "symfony/polyfill-php80": "^1.16",
        "symfony/translation": "^3.4 || ^4.0 || ^5.0 || ^6.0"
    },
```

Changes done to Carbon 3.0 (mostly in `diff*` methods that we heavily relay on) makes it really hard to move to 3.0.
We even tried but Carbon 3 is still bugged.
Carbon 2 should be able to run on Symfony 7.

Thanks!

**Comment by kylekatarnls** [comment]
Hello, support for Symfony 7 on Carbon 2.x will not happen. There are incompatible changes in the translator that force Symfony 7 support to be a breaking change.

> Carbon 3 is still bugged

They have to be listed, please open an issue for each and they will be addressed one by one, some might be actual bugs and pull-requests to fix them are welcome, some might be intended changes and in this case I would try to provide reference to the documentation for the alternatives to use.

Thanks.
