### ISSUE TITLE
Please don't modify existing instances with date arithmetic methods

### ISSUE THREAD

**Issue by kpconnell** [briannesbitt/Carbon#3008]
Hello,

I encountered an issue with the following code:

  
                $startDate = Carbon::today()->subDays(10);
                $endDate = $startDate->addDays(5);

Carbon version: 2.72.3

 
I expected to get:

a different end date than start date

But I actually get:

end and start date are the same. 

I am not interested in hearing why modifying the existing instance with a method like this makes sense because it does not and is really really bad practice.    As you can see we didn't pass it by reference or do something stupid like modify the value of today()  lol

**Comment by kylekatarnls** [comment]
Use `CarbonImmutable::today()` instead, it's like `DateTime` vs. `DateTimeImmutable`.
