### ISSUE TITLE
Carbon::createFromFormat Incorrect Month Output for February

### ISSUE THREAD

**Issue by mahmoudshabat** [briannesbitt/Carbon#3011]
Hello,

I encountered an issue with the following code:
```php
$monthDate =  Carbon::createFromFormat('Y-m', '2024-02');
echo $monthDate->year;
echo $monthDate->month;
```

Carbon version: 2.72.3

PHP version: 8.1.8

I expected to get:

```
2024
2
```

But I actually get:

```
2024
3
```

Thanks!

**Comment by kylekatarnls** [comment]
Hello, use `Carbon::createFromFormat('!Y-m', '2024-02');`, see https://www.php.net/manual/en/datetime.createfromformat.php
