### ISSUE TITLE
Date difference problem

### ISSUE THREAD

**Issue by isisureste** [briannesbitt/Carbon#3020]
I encountered an issue with the following code:

```php
$createTime =  Carbon::parse('2024-05-14T20:49:47.591Z', 'UTC')->tz('America/Merida');
$startedAt  = Carbon::parse('2024-04-14 14:49:15');
$finishAt   = Carbon::parse('2024-05-14 14:49:15');
$createdTimeClosesToStarterAt = $createTime->diffInDays($startedAt) < $createTime->diffInDays($finishAt);
```

Carbon version: 3.1.1

PHP version: 8.2.12

I expected to get:

```
false
```

But I actually get:

```
true
```

Thanks!

**Comment by kylekatarnls** [comment]
```php
$createdTimeClosesToStarterAt = $startedAt->diffInDays($createTime) < $finishAt->diffInDays($createTime);
```
Is also a way if you know that `$createTime` is always after both start and finish. But anyway here I think it's mainly a business decision depending what this variables does mean in the application.

**Comment by isisureste** [comment]
> Hola,
> 
> ¿Por qué sería falso?
> 
> Ambas diferencias son negativas, por lo que es posible que me pierda algo, pero a primera vista el resultado me parece correcto.
> 
> ¿Realmente quieres decir:
> 
> ```
> $createdTimeClosesToStarterAt = abs($createTime->diffInDays($startedAt)) < abs($createTime->diffInDays($finishAt));
> ```
> 
> En tal caso, es lo esperado, y no es una cuestión de carbono: `-30.25 < -0.25`ser `true`es el resultado esperado en PHP.

From Carbon version 2.72.1 to 3.3.1 the result varies and I am not looking for an explanation.

Carbon version 2.72.1
![image_2024_05_16T16_21_32_082Z (1)](https://github.com/briannesbitt/Carbon/assets/77758428/d9139b19-bfe1-4770-a88c-56237e2ca6ed)

Carbon version 3.3.1
![image_2024_05_16T16_23_47_415Z](https://github.com/briannesbitt/Carbon/assets/77758428/c557002b-b1c7-426c-bef7-6b47c68b6997)

**Comment by rhyudek1** [comment]
Diffs on update  
Upgrading nesbot/carbon (2.72.3 => 3.3.1)  


![image](https://github.com/briannesbitt/Carbon/assets/647189/80d4c9d7-166c-44f8-84db-bc5018fe7752)

**Comment by kylekatarnls** [comment]
This breaking changes from 2 to 3 is expected and explained in the doc, also the different ways to upgrade are given there:
https://carbon.nesbot.com/docs/#api-carbon-3
