### ISSUE TITLE
Inconsistent Date Calculation When Adding Months Across February

### ISSUE THREAD

**Issue by MrPunyapal** [briannesbitt/Carbon#3027]
#### Summary

When adding months to certain dates, particularly when February is involved, the resulting dates seem inconsistent. I am unsure if this is a bug or expected behavior.

#### Steps to Reproduce

Consider the following code snippets:

```php
use Carbon\Carbon;

// Example 1
$result1 = Carbon::parse('2024-01-31')->addMonths(2)->format('Y-m-d');
echo $result1; // Expected: "2024-03-31", Actual: "2024-03-31"

// Example 2
$result2 = Carbon::parse('2024-01-31')->addMonth()->addMonth()->format('Y-m-d');
echo $result2; // Expected: "2024-03-31", Actual: "2024-04-02"

// Example 3
$result3 = Carbon::parse('2024-03-31')->addMonths(2)->format('Y-m-d');
echo $result3; // Expected: "2024-05-31", Actual: "2024-06-01"

// Example 4
$result4 = Carbon::parse('2024-03-31')->addMonth()->addMonth()->format('Y-m-d');
echo $result4; // Expected: "2024-05-31", Actual: "2024-06-01"
```

#### Expected Behavior

When adding months to a date, the resulting date should account for month lengths, including leap years. For example:
- Adding two months to '2024-01-31' should result in '2024-03-31'.
- Adding one month to '2024-01-31' and then another month should also result in '2024-03-31'.

#### Actual Behavior

The results vary when adding months separately versus adding them together:
- Adding two months to '2024-01-31' directly results in '2024-03-31', which is correct.
- Adding one month to '2024-01-31' and then another month results in '2024-04-02', which seems inconsistent.

Similarly:
- Adding two months to '2024-03-31' results in '2024-06-01' instead of '2024-05-31'.
- Adding one month to '2024-03-31' and then another month also results in '2024-06-01'.

#### Environment

- Carbon Version: "^2.71.0 || ^3.0.0"
- PHP Version: 8.2 || 8.3

#### Additional Information

This behavior appears when February is in between the months being added. I would like to understand if this is the intended behavior or a potential bug.

**Comment by kylekatarnls** [comment]
Yes it's expected, the same happens with pure PHP `DateTime` doing `->modify('+2 months')` for instance and it's documented.

Use `addMonthNoOverflow()` instead.

**Comment by MrPunyapal** [comment]
> Yes it's expected, the same happens with pure PHP `DateTime` doing `->modify('+2 months')` for instance and it's documented.
> 
> Use `addMonthNoOverflow()` instead.

Same issue if we use feb but little different 

```php
Carbon::parse('2024-01-31')->addMonthsWithNoOverflow(2)->format('Y-m-d'),
// "2024-03-31"
Carbon::parse('2024-01-31')->addMonthWithNoOverflow()->addMonthWithNoOverflow()->format('Y-m-d'),
// "2024-03-29"
Carbon::parse('2024-04-31')->addMonthsWithNoOverflow(2)->format('Y-m-d'),
// "2024-07-01"
Carbon::parse('2024-04-31')->addMonthWithNoOverflow()->addMonthWithNoOverflow()->format('Y-m-d'),
// "2024-07-01"
```
![carbon-1.png](https://github.com/briannesbitt/Carbon/assets/53343069/bb2097f4-c25b-4431-b27e-00105b4de4c1)

**Comment by kylekatarnls** [comment]
I don't see what's wrong with the screenshot above. A month is not a fixed amount of day, the method does not know what was the initial value it only knows about the previous, so the second call starts from 2024-02-29 and it's adding 1 month.

> The results vary when adding months separately versus adding them together
Yes it does, same with pure `DateTime` doing `->modify('+1 month')->modify('+1 month')` is not always giving the same result as `->modify('+2 month')`

I'm investigating the case for the examples returning `2024-07-01`

**Comment by kylekatarnls** [comment]
`2024-04-31` does not exist, that's the reason why the output is `2024-07-01`. It requires a valid date to work properly, the main reason is that it's not possible at all to create a `DateTime` object (and so also a `Carbon` one) that represents and invalid date, `2024-04-31` is immediately converted by `DateTime` into `2024-05-01` and so adding 2 months leads to `2024-07-01` with or without overflow.

This is also expected behavior.

**Comment by MrPunyapal** [comment]
Thanks for confirmation 🤌
