### ISSUE TITLE
Failed to parse time dd/mm/yyyy

### ISSUE THREAD

**Issue by FranciscoCaldeira** [briannesbitt/Carbon#3029]
Hello,

I encountered an issue with the following code:

```php
echo Carbon::parseFromLocale('31/05/2022', 'pt');
```

Carbon version: * 3.4.0

PHP version: 8.3.6 

I expected to get:
```
2022/05/31 00:00:00
```

But I actually get:

```
Carbon\Exceptions\InvalidFormatException with message 'Could not parse '31/05/2022': Failed to parse time string (31/05/2022) at position 0 (3): Unexpected character'
   null
```

Thanks!

**Comment by kylekatarnls** [comment]
Hello,

`parseFromLocale` is only able to translate day names or month names in the given string from the given locale to English, then it will try to use the result into `new Carbon($englishString)`.

You can either give your format explicitly:
```php
echo Carbon::createFromFormat('d/m/Y', '31/05/2022');
```

```php
echo Carbon::createFromFormat('d/m/Y', '31/05/2022');
```

Or use the `L` ISO-format which is for instance DD/MM/YYY in Portuguese but MM/DD/YYYY in US English:
```php
echo Carbon::createFromLocaleIsoFormat('L', 'pt', '31/05/2022');
```

Thanks,
