### ISSUE TITLE
Check month issue 

### ISSUE THREAD

**Issue by narek8888** [briannesbitt/Carbon#3032]
Hello,

I encountered an issue with the following code:

```php
        $reportDate = now()->subMonth()->lastOfMonth();
        dd($reportDate->is('May'), $reportDate->is('April'));
```

Carbon version: *** 2.67.0**

PHP version: **8.1.2**

I expected to get:

```
true, false
```

But I actually get:

```
true, true
```

Thanks!

**Comment by kylekatarnls** [comment]
Hello,

I confirm this is a bug.

I suggest this work-around in the meantime:
```php
dd(
    $reportDate->copy()->startOfMonth()->is('May'),
    $reportDate->copy()->startOfMonth()->is('April')
);
```

Important note: I have to evaluate if it can go either to `2.72.4` patch or `3.5.0`, but the version `2.67.x` will no longer receive fixes.

Thanks for the report. 🙏
