### ISSUE TITLE
PHP Version < 7.4 broken

### ISSUE THREAD

**Issue by DisabledMonkey** [briannesbitt/Carbon#3034]
Hello,

Trying to update to the latest version of Carbon 2 results in error during install results in parse error.
![image](https://github.com/briannesbitt/Carbon/assets/52090243/d90f3902-aaaa-469f-b581-8db049b95fcc)

Carbon version: **2.72.4**
PHP version: **7.2**

The library says Carbon version 2 supports php versions >= 7.1.8
But this piece of code uses [php arrow functions](https://www.php.net/manual/en/functions.arrow.phphttps://www.php.net/manual/en/functions.arrow.php) which were introduced in php 7.4

Was broken in this commit https://github.com/briannesbitt/Carbon/commit/117671bd1a44c819b941dcd152bd0268466464e0

**Comment by kylekatarnls** [comment]
Thank you for the report 🙏  2.72.5 patch released with the fix.

**Comment by DisabledMonkey** [comment]
thanks for the quick patch
