### ISSUE TITLE
Psalm reports MissingDependency on CarbonPeriod

### ISSUE THREAD

**Issue by juliangums** [briannesbitt/Carbon#3037]
Hello,

I encountered an issue with the following code:

```php
$days = Carbon::parse($start)->toPeriod(Carbon::today(), '1 day');
```
or
```php
$days = CarbonPeriod::create($startDate, '1 day', $endDate);
```
Carbon version: latest

PHP version: latest

The code works as expected but running static analysis with Psalm, it tells me:
```
psalm: MissingDependency: Carbon\CarbonPeriod depends on class or interface carbon\dateperiodbase that does not exist
```

Any idea why this happens? I would submit a PR if anyone can point me in the right direction, but don't actually know where to start. 

Thanks!

**Comment by kylekatarnls** [comment]
Hello,

You can add files to your projects if Psalm is unable to detect them. It sounds it's not able to see what's in `lazy` folder:
```xml
<file name="vendor/nesbot/carbon/lazy/Carbon/UnprotectedDatePeriod.php" />
<file name="vendor/nesbot/carbon/lazy/Carbon/TranslatorStrongType.php" />
<file name="vendor/nesbot/carbon/lazy/Carbon/MessageFormatter/MessageFormatterMapperStrongType.php" />
```

If you can find a way so that we expose it at library level so that we can make a change and have projects using Psalm to inherit it, I would gladly merge.

Thanks.

**Comment by mcsky** [comment]
Hello,

I'm upgrading to carbon V3, psalm is having trouble with `CarbonPeriodImmutable` too.

- MixedInferredReturnType : Could not verify return type 'Carbon\CarbonPeriodImmutable'
- MissingDependency : Carbon\CarbonPeriodImmutable depends on class or interface carbon\dateperiodbase that does not exist
