### ISSUE TITLE
Undocumented breaking change: isSameMonth()

### ISSUE THREAD

**Issue by MattApril** [briannesbitt/Carbon#3039]
Hello,

I encountered an issue with the following code:
```php 
$date->isSameMonth();
```

Carbon version: 3.5.0

PHP version: 8.3

I expected to get:
```BOOL```

But I actually get:
```
ArgumentCountError: Too few arguments to function Carbon\Carbon::isSameMonth()
```

This breaking change was not documented in the upgrade guide. 

Thanks!

**Comment by kylekatarnls** [comment]
Hello,

In Carbon 3, it's expected that you should either use the method `->isCurrentMonth()` to check if the month of the date is the same as now. Or you must explicitly pass an argument to the method `->isSameMonth($otherDate)` as suggested by the error message you receive.

This changes enforce explicitness as it's error-prone to let ambiguity such as "is same as what?", it's way less risky for the next developer reading your code (including future yourself) if you say what is the other date.

Thanks.

**Comment by MattApril** [comment]
To be clear, I fully agree with the change. My only point was that it is not documented as a breaking change in your upgrade guide: https://carbon.nesbot.com/docs/#api-carbon-3

**Comment by kylekatarnls** [comment]
Thanks. 🙏  Documented.
