### ISSUE TITLE
2.7.4 is not support php7.3

### ISSUE THREAD

**Issue by zhongjq** [briannesbitt/Carbon#3048]
Hello,

I encountered an issue with the following code:

```php
composer require nesbot/carbon
```

Carbon version: 2.7.4

PHP version: 7.3.33

I expected to get:

```
Package manifest generated successfully.
```

But I actually get:

```
In Comparison.php line 999:
                                                                                   
  syntax error, unexpected 'fn' (T_STRING), expecting :: (T_PAAMAYIM_NEKUDOTAYIM) 
```

Thanks!

**Comment by kylekatarnls** [comment]
Hello, it's fixed in [2.72.5](https://github.com/briannesbitt/Carbon/releases/tag/2.72.5)

Thanks.
