### ISSUE TITLE
`age` function does not calculate the age correctly for Carbon >= 3

### ISSUE THREAD

**Issue by ferdinandfrank** [briannesbitt/Carbon#3050]
Hello,

I encountered an issue with the following code:

```php
echo Carbon::parse('2020-07-16')->age;
```

Carbon version: **3.6.0**

PHP version: **8.2**

I expected to get when running the code at day `2024-07-15`:

```
3
```

But I actually get:

```
4
```

The code works fine for Carbon version < 3.0.

Thanks!

**Comment by kylekatarnls** [comment]
Fixed in 3.7.0
