### ISSUE TITLE
DateInterval    CarbonInterval  Carbon - Laravel 11

### ISSUE THREAD

**Issue by phpbaba22** [briannesbitt/Carbon#3057]
I facing issues to 
how to initialize DateInterval in Laravel 10 **blade file** 

$loanStartDate = new DateTime("2020-01-01");
$loanPeriod = new DateInterval("P2Y5M");
$nextPaymentDate = clone $loanStartDate;
$nextPaymentDate->add($loanPeriod);
$nextPaymentDate->format("Y-m-d");

<td>{{$nextPaymentDate }}</td>

**Comment by kylekatarnls** [comment]
Hello,

Please report here issue specifically when using Carbon package/classes, and do so following the template that is provided to you when clicking "New issue".

You can do the above in one go like this using Carbon:
```blade
{{ \Carbon\Carbon::parse("2020-01-01")->add("P2Y5M")->format("Y-m-d") }}
```

However, it will be easier to maintain on the long run if you do not to calculate `$nextPaymentDate` in your controller, then pass it as a variable to your view as an object (Carbon or DateTime instance), then you only format it in the template `{{ $nextPaymentDate->format("Y-m-d") }}`

**Comment by phpbaba22** [comment]
It very useful and thanks one thing more, could it be possible to pass dynamical variable in 

add(P$yY$mM)   

or

 add($YM) 

{{ \Carbon\Carbon::parse("2020-01-01")->add("P2Y5M")->format("Y-m-d") }}

and is there any way to use for  adding loan period to date of start load date
