### ISSUE TITLE
Remove copy() & Make all arithmetic immutable.

### ISSUE THREAD

**Issue by kpconnell** [briannesbitt/Carbon#3058]
Having the arithmetic operations modify the underlying object rather than *just* return the result is completely non intuitive and different than 99% of the libraries in PHP.

Please remove copy() and change all date arithmetic methods to simply return the result without modifying the class instance.

**Comment by kylekatarnls** [comment]
Use CarbonImmutable instead, please read the first chapter of the doc carbon.nesbot.com/docs/ it's inherited directly from PHP having DateTime and DateTimeImmutable, and also please next time open issue following the given template.

Thanks,

**Comment by kpconnell** [comment]
You're still doing it wrong.  Change CarbonImmutable to Carbon and Carbon to CarbonMutable
