### ISSUE TITLE
Cant create negative interval between 00:00 and -01:00

### ISSUE THREAD

**Issue by alves-raphael** [briannesbitt/Carbon#3059]
Hello,

I encountered an issue with the following code:

```php
CarbonInterval::createFromFormat('H:i', '-00:59');
```

Carbon version: **3.4.0**

PHP version: 8.3.7

I expected to get:

```
Carbon\CarbonInterval {
    interval: - 00:59:00.0,
  }
```

But I actually get:

```
Carbon\CarbonInterval {
    interval: + 00:59:00.0,
  }
```

As stated in the print below, it seems like it's impossible to create a negative interval between 00:00 and -01:00, using the "H:i" format.
![image](https://github.com/user-attachments/assets/91be8c04-449a-49e9-8259-5a321f1ad5f9)
Let me now if I can do anything to contribute to solve this or any other issue!
Thanks!

**Comment by kylekatarnls** [comment]
Hello, the negative sign is per unit:

```php
var_dump(CarbonInterval::createFromFormat('H:i', '-00:59')); // -0 hours +59 minutes
var_dump(CarbonInterval::createFromFormat('H:i', '00:-59')); // +0 hours -59 minutes
var_dump(CarbonInterval::createFromFormat('H:i', '-01:59')); // -1 hour +59 minutes
var_dump(CarbonInterval::createFromFormat('H:i', '01:-59')); // +1 hour -59 minutes
```

Note that the interval is positive in any case above even with `'01:-59'` (only the units are negative).

If your string can start with a `-` but not contain it anywhere else, then you can do this to have an interval with all units positive but the whole interval negative (inverted):
```php
$duration = '-00:59';
$negative = str_starts_with($duration, '-');

if ($negative) {
  $duration = substr($duration, 1);
}

$interval = CarbonInterval::createFromFormat($duration);

if ($negative) {
  $interval = $interval->invert();
}
```

How does this solution sound to to you?

**Comment by alves-raphael** [comment]
That looks like it could handle the job. Thank you!
