### ISSUE TITLE
Translated months names off

### ISSUE THREAD

**Issue by PascaleBeier** [briannesbitt/Carbon#3097]
Hello,

I encountered an issue with the following code:

```php
foreach (range(1,12) as $month) {
    echo \Carbon\Carbon::now()->setMonth($month)->getTranslatedMonthName() . '<br>';
}
```

Carbon version: **3.8.0**

PHP version: **8.3.12**

I expected to get:

```
January
February
March
April
May
June
July
August
September
October
November
Dezember
```

But I actually get:

```
January
March
March
May
May
July
July
August
October
October
December
December
```

Examples:

https://phpsandbox.io/e/x/6n2z7?layout=EditorPreview&defaultPath=%2F&theme=dark&showExplorer=no&openedFiles=

This works:

```php
foreach (range(1,12) as $month) {
    echo \Carbon\Carbon::now()->setDay(1)->setMonth($month)->getTranslatedMonthName() . '<br>';
}
```

**Comment by PascaleBeier** [comment]
Seems to be a duplicate of https://github.com/briannesbitt/Carbon/issues/2317

**Comment by kylekatarnls** [comment]
Hello, if you want to get translated month name from month number, `now` is irrelevant, you'd better directly create a date from this number rather than creating an object then modifying it:

```php
foreach (range(1, 12) as $month) {
    echo \Carbon\Carbon::create(2000, $month, 1)->getTranslatedMonthName() . '<br>';
}
```

`2000` is a completely arbitrary year, anyone would work the same.
