### ISSUE TITLE
How i can get the current week, current month and current year

### ISSUE THREAD

**Issue by giwrgos88** [briannesbitt/Carbon#317]
Hello i'm looking a way using Carbon to select all the rows from the database for the current week, current month and current year using Carbon. How i can do it? I have checked the Doc but I didn't find anything. thank you

for example for current month i want something like this 2015-03-01 00:00:00 - 2015-03-31 23:59:59

**Comment by briannesbitt** [comment]
That would be documented here: http://carbon.nesbot.com/docs/#api-getters

```php
$now = Carbon::now();
echo $now->year;
echo $now->month;
echo $now->weekOfYear;
```

**Comment by tomhorvat** [comment]
For month you would do:

```
$now = Carbon::now();
$monthStart = $now->startOfMonth();
$monthEnd = $now->endOfMonth();
```

http://carbon.nesbot.com/docs/#api-modifiers

**Comment by giwrgos88** [comment]
i made it like this  
 $start = $this->now->year.'-'.(strlen($this->now->month) == 1 ? '0'.$this->now->month : $this->now->month) .'-01 00:00:00';
$end = $this->now->year.'-'.(strlen($this->now->month) == 1 ? '0'.$this->now->month : $this->now->month) .'-'.(strlen($this->now->daysInMonth) == 1 ? '0'.$this->now->daysInMonth : $this->now->daysInMonth).' 23:59:59'; 

where $this->now is equal to Carbon::now()->timezone('Europe/Athens');
thank you
