### ISSUE TITLE
diffForHumans for differend locales

### ISSUE THREAD

**Issue by dirkluijk** [briannesbitt/Carbon#32]
Hi,

Wouldn't it be nice to have different translations for the ``Carbon::diffForHumans()`` method?

```php
setlocale(LC_TIME, 'nl_NL');                     
echo Carbon::now()->subDays(5)->diffForHumans();  // 5 dagen geleden
echo Carbon::now()->addDays(5)->diffForHumans();  // over 5 dagen
setlocale(LC_TIME, '');                           
echo Carbon::now()->subDays(5)->diffForHumans();  // 5 days ago
echo Carbon::now()->addDays(5)->diffForHumans();  // 5 days from now
```

I don't know how this should be implemented, but I think (for flexibility) you should be able to:

- define the format (sequence/position of each part)
- define the units and other texts

Example configuration:

en.unit.day = "day"
en.unit.days = "days"
en.unit.week = "week"
en.unit.weeks = "weeks"
en.pastNow = "ago"
en.futureNow = "from now"
en.pastValue = "before"
en.futureValue = "after"
en.format = "{value} {unit} {pastNow}{futureNow}{pastValue}{futureValue}"

nl.unit.day = "dag"
nl.unit.days = "dagen"
nl.unit.week = "week"
nl.unit.weeks = "weken"
nl.pastNow = "geleden"
nl.futureNow = "over"
nl.pastValue = "ervoor"
nl.futureValue = "erna"
nl.format = "{futureNow} {value} {unit} {pastNow}{pastValue}{futureValue}"

I think this is a good idea, but I have no idea how this should be implemented. Also the variables names as proposed could be better.

**Comment by erayaydin** [comment]
+1 , I can help for Turkish :+1

**Comment by tplessis** [comment]
+1 !

**Comment by dschu-lab** [comment]
+1

Hope Brian will give us some good news in the next month.

**Comment by capir** [comment]
+1

**Comment by hohl** [comment]
+1 :+1:

**Comment by fedeisas** [comment]
:+1:

**Comment by flinux** [comment]
I could translate it in italian.

**Comment by HarmvZ** [comment]
+1

**Comment by ncodeIO** [comment]
dirkluijk opened this issue on 28 Aug 2013   still no support? wow

**Comment by GrahamCampbell** [comment]
@ncodeIO If you want support, do it yourself. That is how oss works.

**Comment by fedeisas** [comment]
@GrahamCampbell do you know why #84 didn't got merged? I was about to implement my own solution until I saw that one.

**Comment by kylekatarnls** [comment]
Yes, agree with you @fedeisas, the owner do not tell us why he do not merge and do not propose any other solution. I don't understand why Laravel keep include Carbon and no laravel-date or some other forks.

@GrahamCampbell, yes that is the way and @briannesbitt should add some contributors with administrator rights to allow Carbon to evolve faster, don't you think so?

**Comment by briannesbitt** [comment]
It looks like Carbon should also rely on symfony/Translation as laravel does anyway.  This will simplify supporting more complicated pluralization languages like Russian and the like.

I am no longer a fan of the implementation I initially proposed here as there is too much code duplication in each formatter when so many languages could rely on the same basic format.

I am going to implement something similar but have a single translator implementation (that will be overwrite-able) that will rely on symfony/Translation so it should really handle 99.9% of the cases anyway.

After the initial implementation we can also, while still being bc, update the implementation for `toFormattedDateString()` etc to rely on `strftime` and make the formats available to be translated.  At the moment though, I don't see a way for this to be easily done to `__toString()` without being a bc change since this already exposes a method to updates its format.

**Comment by briannesbitt** [comment]
Just pushed a simple localization of diffForHumans().  Its based on syfony Translation so we can easily handle all languages.

If this is good then I merge to master and then we can work on augmenting the localization to other parts.

**Comment by kylekatarnls** [comment]
Excellent!

**Comment by martinlindhe** [comment]
@briannesbitt awesome! here is a se.php translation (Swedish) that could fit in your branch
```

return [
    'year'      => '1 år|:count år',
    'month'     => '1 månad|:count månader',
    'week'      => '1 vecka|:count veckor',
    'day'       => '1 dag|:count dagar',
    'hour'      => '1 timme|:count timmar',
    'minute'    => '1 minut|:count minuter',
    'second'    => '1 sekund|:count sekunder',
    'ago'       => ':time sedan',
    'from_now'  => ':time från nu',
    'after'     => ':time efter',
    'before'    => ':time innan'
];
```

**Comment by kylekatarnls** [comment]
You can add it with a pull request (and so, you will appear in contributors when it will be merged). Maybe you should use array() instead of [] as Carbon must keep being compatible with PHP 5.3.

**Comment by martinlindhe** [comment]
I'll gladly do a pull request but can wait until this lands on master :)

also, thanks for the short array php 5.3 comment. i didn't realise that

**Comment by sebathi** [comment]
Added spanish translations with pull request.

**Comment by kylekatarnls** [comment]
@martinlindhe, if you add it in a pull request it will create a branch and you can use this branch instead of the official repository (edit package.json) to immediatly use it in you app.

**Comment by Cederman** [comment]
Added French localization

**Comment by kylekatarnls** [comment]
French is already added: https://github.com/briannesbitt/Carbon/blob/localized/src/Carbon/Lang/fr.php
Use the localized branch.

**Comment by Cederman** [comment]
Oh, my bad! Missed that :)

**Comment by flinux** [comment]
Added italian translations with pull request.

**Comment by kylekatarnls** [comment]
Hey guys, don't you think we could get the translations from laravel-date project instead of retranslate all the texts:
https://github.com/jenssegers/laravel-date
#271

**Comment by trololosha4real** [comment]
Mmm, how things are going? Will it be merged in to the master?

**Comment by briannesbitt** [comment]
I jumped the gun and bit off a little more (ie. too much) with this feature branch.  I have added a CarbonInterval class as well `CarbonInterval::year(5)`.  The pluralization for German has been fixed and the extra code is now documented and tested.  Should be in master in the next few days.

**Comment by nonamez** [comment]
Nice. In a few days I will provide LT and RU versions of translations.

**Comment by kylekatarnls** [comment]
Hi italian people, could you please check this:
laravel-date use `tra :time` instead of `:time da adesso`. What is the most appropriate?

**Comment by kylekatarnls** [comment]
And the same for netherlands:
`over :time` or `:time vanaf nu`?
If it's like `dans :time` vs. `:time à partir de maintenant`, so the long way is more literal, but the short is better and more comon and I think we should choose a rule and apply it on all languages.

**Comment by kylekatarnls** [comment]
Hi @nonamez please check this russian translation: #306

**Comment by Jeroen-G** [comment]
Well, every language has it's own practices and I think we should twist and turn these to make it the same in every translation. Does it really matter after all? It is just what people are used to in their language. In the case of Dutch (I made the translation, to be clear) no one says something is `:time vanaf nu`.

**Comment by kylekatarnls** [comment]
Import finished, please check: #284 #285 #286 #287 #298 #299 #300 #301 #302 #303 #304 #305 #306 #307 #309 #310 #311 #312 #313 #314 #315 #316

**Comment by briannesbitt** [comment]
Yikes !  Ok thanks @kylekatarnls !

**Comment by trololosha4real** [comment]
@kylekatarnls Nice one. At first it looks good. I will double-check it in production at my blog when it will be released.

**Comment by fedeisas** [comment]
:+1:

**Comment by briannesbitt** [comment]
In master.

**Comment by nonamez** [comment]
Added some fixes to lt lang https://github.com/briannesbitt/Carbon/pull/340
