### ISSUE TITLE
Setting locale for diffForHumans

### ISSUE THREAD

**Issue by Cederman** [briannesbitt/Carbon#324]
Hi!
I just saw that the locale branch has been merged to master, awesome news! But I can't figure out how to use my locale in my Laravel 4 app. I've set the locale in app/config/app.php but it doesn't affect the diffForHumans() output. What am I missing?

**Comment by Anahkiasen** [comment]
Carbon is not a Laravel package, it's an agnostic one. It's most likely Laravel that needs to be updated to take into account Carbon's locale feature

**Comment by rodrigopedra** [comment]
As @Anahkiasen stated, it is a Laravel issue to update its Carbon version requirements.

Meanwhile you could o this:

1) Update your composer.json with this entry

    "nesbot/carbon": "dev-master#a9525ab0cccd559006991902e0013b7e62640c5a as 1.0.99"

This will make composer replace your current installation of Carbon with the specific one which started supporting localization (it is not tagged yet). the `as 1.0.99` is a workaround to avoid any conflicts with a library that require Carbon to be on version `~1.0`. **Important**: using a different version may break something on your app libraries.

2) Run `composer update` on your shell/terminal

3) Call `\Carbon\Carbon::setLocale('pt_BR');` somewhere in your app before booting. I call it on the `boot(...)` method on my `AppServiceProvider`. (*no need to say to replace the 'pt_BR' with the desired language code*).

Hope it helps!

**Comment by briannesbitt** [comment]
Pretty much sums it up.  Call `\Carbon\Carbon::setLocale('pt_BR');` somewhere early on.

I'll tag a 1.18.0 release soon.
