### ISSUE TITLE
Weird subMonths problem

### ISSUE THREAD

**Issue by RobinMalfait** [briannesbitt/Carbon#329]
Okay so when I do 

```php
$date = Carbon\Carbon::now();

// Result
Carbon {#161 ▼
  +"date": "2015-03-30 12:57:18"
  +"timezone_type": 3
  +"timezone": "Europe/Brussels"
}
```

And I want to subtract 1 Month I do this:

```php
$prev = $date->copy()->subMonth();

// And I expect:
Carbon {#161 ▼
  +"date": "2015-02-30 12:57:18"
  +"timezone_type": 3
  +"timezone": "Europe/Brussels"
}

// But I get
Carbon {#162 ▼
  +"date": "2015-03-02 12:57:18"
  +"timezone_type": 3
  +"timezone": "Europe/Brussels"
}
```

So instead of a month, there are only 28 days subtracted?

**Comment by kylekatarnls** [comment]
A 30 february can not exist so the date is the equivalent in next month. You can also use subMonthNoOverflow() to get 2015-02-28. But 2015-02-30: No way. A datetime is always a valid date.

**Comment by RobinMalfait** [comment]
Yeah Okay I see that, I only needed the month and year; but let me try the subMonthNoOverflow method; thanks!

**Comment by RobinMalfait** [comment]
Thanks @kylekatarnls that worked!
