### ISSUE TITLE
MsSQL DateTime with Microseconds stopped working

### ISSUE THREAD

**Issue by CedNet** [briannesbitt/Carbon#331]
Hi! I don't know how long this issue have really been there, but the Carbon::createFromFormat() returned that my SQL DateTime-timestamps is of format Y-m-d H:i:s.000, correctly so. 
But upon converting a typical value of say (in my case): 
    2011-05-04 00:00:00.100 
it throws an exception: 
    The format separator does not match

Since the final class that returns the formatted value is PHP's DateTime() I don't know if this issue is submitted to the right place. 

Is this something for Carbon to fix or handle?

**Comment by briannesbitt** [comment]
Try a `u` for microseconds in the format according to http://php.net/manual/en/function.date.php

```php
$dt = Carbon::createFromFormat('Y-m-d H:i:s.u', '2011-05-04 00:00:00.134');
var_dump($dt); 
```

```
object(Carbon\Carbon)#3 (3) {
  ["date"]=>
  string(26) "2011-05-04 00:00:00.134000"
  ["timezone_type"]=>
  int(3)
  ["timezone"]=>
  string(15) "America/Toronto"
}
```
