### ISSUE TITLE
CakePHP 3.0.1

### ISSUE THREAD

**Issue by coolex** [briannesbitt/Carbon#332]
\# composer require nesbot/carbon

Using version dev-master for nesbot/carbon
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - cakephp/cakephp 3.0.0 requires nesbot/carbon 1.13.* -> no matching package found.
    - cakephp/cakephp 3.0.0 requires nesbot/carbon 1.13.* -> no matching package found.
    - Installation request for cakephp/cakephp == 3.0.0.0 -> satisfiable by cakephp/cakephp[3.0.0].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

Read <http://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

Installation failed, reverting ./composer.json to its original content.

**Comment by GrahamCampbell** [comment]
> Using version dev-master for nesbot/carbon

Yes, you CAN NOT use dev-master. That;s why it's not working...

**Comment by dereuromark** [comment]
@coolex Drop your `nesbot/carbon` dependency alltogether in your app json file. CakePHP itself requires it already, so it will be included either way. No need for you to also do that then.

**Comment by coolex** [comment]
OK, sorry, my mistake...
