### ISSUE TITLE
Carbon cannot find Symphony components

### ISSUE THREAD

**Issue by mbckrtn** [briannesbitt/Carbon#342]
Hello,
I'm certain this isn't really a Carbon issue, but i'm looking for help. Upon installing Carbon into my project with composer, everything seems to work fine (including Carbon::Now()) until I try to use diffForHumans(), at which point I receive the following error:

Fatal error: Class 'Symfony\Component\Translation\Translator' not found in /var/www/html/vendor/nesbot/carbon/src/Carbon/Carbon.php on line 800

Any idea what could be wrong? All of the Symphony components are there as far as I can tell. Composer seemed to work just fine. What am I missing?

**Comment by MelonSmasher** [comment]
Same problem here.

**Comment by Giioo** [comment]
I have same problem too, can help someone?

Class 'Symfony\Component\Translation\Translator' not found in /usr/share/nginx/html/carbon/carbon.php

**Comment by briannesbitt** [comment]
Did you run a `composer update` ?  Are the symfony components installed in the vendor directory?
