### ISSUE TITLE
Dependency-free version?

### ISSUE THREAD

**Issue by philer** [briannesbitt/Carbon#345]
Hi,
I came here remembering Carbon as an awesome, simple, and most of all dependency-free extension of PHP's clunky DateTime. That is what I need for a small project.

My question: Is there still a version of Carbon around that doesn't need Symfony components or anything else to run? I don't really care about localization.

edit: I found the 1.17 tag still works like that. Do you maybe have any plans on maintaining a no-dependencies branch? That'd be pretty cool.

Either way, awesome work. Keep it up.
philer

**Comment by kylekatarnls** [comment]
Use the version 1.17. You can also see my fork with a dependancy-free version of Carbon that includes the internationalization: https://github.com/kylekatarnls/Carbon

I don't think Carbon should maintain different versions, it will be tricky as the internationalization has not been taged as a major version (2).

If many users need it, I could merge new Carbon's features on my fork and maintain it.

**Comment by briannesbitt** [comment]
No plans to keep the 1.17 branch updated with current features.  If you are using composer to manage your dependencies then you don't really have to worry about it.

I'll also mention that if you just grab the `Carbon.php` src file and require it from another php file and do a simple `echo \Carbon\Carbon::now();` that works.  As long as you stay away from the functions that need the dependencies.

**Comment by kylekatarnls** [comment]
Note that you can also clone Carbon, then install the vendors with composer, and copy-paste all the directories including vendor to you application. In that case you can use all the new features, internationalization and you not forced to use composer for your project.

**Comment by philer** [comment]
Thanks guys.
I use composer for bigger projects. For a very small project I'm doing right now I'm trying to keep it as dependency free as possible, which includes avoiding third-party dependencies. The whole thing is supposed to be a minimalistic, copy-and-run kind of deal and the single-file version of Carbon is just what I need for that.

**Comment by GrahamCampbell** [comment]
> The whole thing is supposed to be a minimalistic

You probably don't need carbon then?

**Comment by briannesbitt** [comment]
@GrahamCampbell  Haha.

Thought of bundling it as a phar that way nicely including all of your dependencies?
