### ISSUE TITLE
Add endOfHour() and startOfHour() methods

### ISSUE THREAD

**Issue by bmitch** [briannesbitt/Carbon#347]
Great library, has helped quite a bit. One thing I noticed is there are methods for endOf/StartOf day, week, month, year, decade, century but not for hour (as far as I can see).

These would be nice to have as well.

**Comment by kylekatarnls** [comment]
Hello,

startOfDay is nothing more than: `$date->hour(0)->minute(0)->second(0)` and endOfDate: `$date->hour(23)->minute(59)->second(59)`
So just do that for start/endOfHour: `$date->minute(0)->second(0)` and  `$date->minute(59)->second(59)`

Or extend Carbon like this:
<pre>CarbonPlus extends Carbon {
  public function startOfHour() {
    return $this->minute(0)->second(0);
  }
  public function endOfHour() {
    return $this->minute(59)->second(59);
  }
}</pre>

**Comment by bmitch** [comment]
Thanks @kylekatarnls makes sense!
