### ISSUE TITLE
Class 'Symfony\Component\Translation\Translator' not found

### ISSUE THREAD

**Issue by Giioo** [briannesbitt/Carbon#348]
Class 'Symfony\Component\Translation\Translator' not found in /usr/share/nginx/html/carbon/carbon.php on line 709

I'm getting this fatal error when i am trying to use diffForHumans format, everything else works greatly, someone can help?

**Comment by Giioo** [comment]
hi

**Comment by briannesbitt** [comment]
Are you using composer?

**Comment by Giioo** [comment]
Oh i had some stupid mistake, i fixed it ty for your feedback

**Comment by ayhanvalencia** [comment]
I have the same issue, i'am not using composer, 
cant find class name : Symfony\Component\Translation\Translator in models Fatal error: Class 'Symfony\Component\Translation\Translator' not found in /customers/b/c/7/gurweb.se/httpd.www/portfolioShowCase/hero-slider/libs/carbon.php on line 799

I need help with that, thanks.

**Comment by GrahamCampbell** [comment]
> I have the same issue, i'am not using composer,
cant find class name : Symfony\Component\Translation\Translator in models Fatal error: Class 'Symfony\Component\Translation\Translator' not found in /customers/b/c/7/gurweb.se/httpd.www/portfolioShowCase/hero-slider/libs/carbon.php on line 799

I need help with that, thanks.

You need to download symfony's translator then...
