### ISSUE TITLE
datetime-local HTML5

### ISSUE THREAD

**Issue by alexbowers-tecmark** [briannesbitt/Carbon#356]
HTML5 datetime-local input field requires the format to be:
- A date.
- The literal string "T".
- A time.

This can be done with formatting, but having a ->toDatetimelocal() would be useful.

I couldnt find anything that already does this in the documentation.

http://www.w3.org/TR/html-markup/input.datetime-local.html

**Comment by briannesbitt** [comment]
See : http://carbon.nesbot.com/docs/#api-commonformats

```echo $dt->toW3cString();       // 1975-12-25T14:15:16-05:00```

**Comment by alexbowers-tecmark** [comment]
Thanks

**Comment by tevfik6** [comment]
Hi @briannesbitt,

It seems like this is not working anymore. I'm getting warning from Chrome Version 51.0.2704.103 (64-bit) and input[type="datetime-local"] doesn't show anything. It looks like it can't even parse this. 

> The specified value "2016-07-28T01:02:00+00:00" does not conform to the required format.  The format is "yyyy-MM-ddThh:mm" followed by optional ":ss" or ":ss.SSS".

Tev.

**Comment by bjuppa** [comment]
Hi!
It could make sense to reopen this request! The HTML5 `datetime` input is happy with the `toW3cString()` format, but `datetime-local` requires another similar format, up to but completely without the timezone info.

Current workaround is to use `$dt->format('Y-m-d\TH:i:s')`
Could `toDatetimelocalString()` be a suitable name to match the others in [http://carbon.nesbot.com/docs/#api-commonformats]()?

**Comment by papalardo** [comment]
**toDateTimeLocalString()** works to me

**Comment by bjuppa** [comment]
Until just now I wasn't even aware there had been a PR for this suggestion merged over a year ago! I'm so glad to see it in there, thanks to @yamenarahman!

**Comment by yamenarahman** [comment]
You’re welcome.

**Comment by weshooper** [comment]
A specific format for this would still be useful.

While `toDatetimelocalString()` does _work_, Chrome/Brave pickup the seconds and confusingly render them:

<img width="234" alt="Screenshot 2019-10-15 at 15 54 19" src="https://user-images.githubusercontent.com/2248206/66843550-d58bfc80-ef64-11e9-939d-ad5a57a4cec2.png">

A format without the seconds (i.e. a shortcut for `->format('Y-m-d\TH:i')` would be handy, since it'd render as:

<img width="233" alt="Screenshot 2019-10-15 at 15 52 59" src="https://user-images.githubusercontent.com/2248206/66843586-dcb30a80-ef64-11e9-93d9-24ba3f0f6fa3.png">

**Comment by kylekatarnls** [comment]
Macro?

```php
Carbon::macro('pickerFormat', static function () {
  return self::this()->format('Y-m-d\TH:i');
});

echo Carbon::now()->pickerFormat();
// or statically: echo Carbon::pickerFormat();
```

**Comment by bjuppa** [comment]
That's interesting @weshooper!

I also see now that all the examples on [the MDN input docs](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/datetime-local) are *without* the seconds part, and it actually says "Seconds are not supported". But [the MDN date and time formats docs](https://developer.mozilla.org/en-US/docs/Web/HTML/Date_and_time_formats#Local_date_and_time_strings) says seconds are valid, and so does [Whatwg](https://html.spec.whatwg.org/multipage/common-microsyntaxes.html#valid-local-date-and-time-string).

If real-world datetime-local inputs works better without the seconds part, I think `toDateTimeLocalString()` should drop seconds and format using `Y-m-d\TH:i`!

I guess it's a breaking change though 😄

**Comment by kylekatarnls** [comment]
After a check I disagree this statement:
> Chrome/Brave pickup the seconds and confusingly render

It's confusing only if you do not expect seconds as user input. But users may require their user to input seconds and even milliseconds. This works fine with Chrome:

```html
100m run start:
<input type="datetime-local" id="meeting-time"
       name="meeting-time" value="2018-06-12T19:30:04.123"
       min="2018-06-07T00:00" max="2018-06-14T11:25:12.324">
<br>
end:
<input type="datetime-local" id="meeting-time"
       name="meeting-time" value="2018-06-12T19:30:04.123"
       min="2018-06-07T00:00" max="2018-06-14T11:25:21.904">
```

Seconds matter (and even milliseconds could). So the user should be able to use them. And it should be explicitly removed if you don't want them.

For now it requires `->startOfMinute()` call (the more explicit way).

But the improvement can be:
```php
$date->toDatetimelocalString('minute');
$date->toDatetimelocalString('second');
$date->toDatetimelocalString('millisecond');
$date->toDatetimelocalString('microsecond');
```

But the default behavior would still be "second". I see no good reason to change it.

**Comment by bjuppa** [comment]
@kylekatarnls I like that improvement suggestion, letting the consumer decide what level of detail is desired! Also, not a breaking change anymore! 😎

**Comment by weshooper** [comment]
I should probably add that, by 'confusing', I mean that while Chrome/Brave renders the seconds, they're displayed in a faded/disabled colour and aren't selectable or editable by the user.

**Comment by kylekatarnls** [comment]
It can if you change the option `step="1"` (with a value lower than 60).

**Comment by weshooper** [comment]
@kylekatarnls Aha, did not realise that - thanks! :-)

**Comment by bveasey** [comment]
while this works for chrome using datetime-local on ios safari the seconds cause an error. Just noting this.

**Comment by Reza1290** [comment]
This how u use it in Laravel Blade Template

$var_date = "2024-01-25 11:04:00";

in blade
{{\Carbon\Carbon::parse($var_date)->toDateTimeLocalString()}}
