### ISSUE TITLE
diffForHumans shows me 45 years ago on 1900-04-16

### ISSUE THREAD

**Issue by PatrickJoannisse** [briannesbitt/Carbon#359]
I have the following timestamp (used for testing) 1900-04-16 00:00:00 and when I pass it through Carbon this way:

     Carbon::createFromTimestamp(strtotime($log->game_at))->diffForHumans();

It shows me: 45 years ago.

1902-01-01 works fine though. 

Is it by design? 

Edit: to be clear, I understand that PHP "starts" on 1901-12-13. I was expecting an error but it truncated the hundreds instead.

**Comment by briannesbitt** [comment]
According to the PHP docs:

`The valid range of a timestamp is typically from Fri, 13 Dec 1901 20:45:54 UTC to Tue, 19 Jan 2038 03:14:07 UTC. (These are the dates that correspond to the minimum and maximum values for a 32-bit signed integer.)`

Use this instead:
`echo Carbon::parse('1900-04-16 00:00:00')->diffForHumans();`

**Comment by DeeJaVu** [comment]
Hello i have the same problem but for unixtimestam, i tried parse() but it says

    DateTime::__construct(): Failed to parse time string (1442664851) at position 8 (5)

this is how my code looks like when it displays '45 years ago'

   {{ Carbon::createFromTimeStamp(strtotime($r['created_time']))->diffForHumans()  }}
