### ISSUE TITLE
age only displaying 0?

### ISSUE THREAD

**Issue by IntellectProductions** [briannesbitt/Carbon#362]
I'm using Laravel which comes with Carbon (the created_at and updated_at columns are instances of Carbon).

I'm doing this:
```php
var_dump($this->created_at->age);
$date = Carbon::createFromDate(2015,5,12);
var_dump($date);
```

The first one is coming out at 0. The second one is coming out as:
```
object(Carbon\Carbon)[896]
  public 'date' => string '2015-05-12 13:55:32' (length=19)
  public 'timezone_type' => int 3
  public 'timezone' => string 'UTC' (length=3)
```

Which is the SAME thing as created_at. But whenever I do ->age on them, it just spits out 0. Although it should be 3 days..

Thanks for any help! I believe I'm using it correctly since I typed exactly what the README has.

**Comment by dereuromark** [comment]
I dont know the functionality. But wouldn't age if you think about it by definition output the years?
Like "age" of a person. In that case 0 would be correct until one full year is reached where it changes to 1. What you are looking for is difference in time in general, where you can output the diff in a more fine-granular way (and that is given with the diff functionality provided by Carbon and DateTime as per their doc).

**Comment by briannesbitt** [comment]
Correct.  `age` is the age in years.  You might be looking for http://carbon.nesbot.com/docs/#api-humandiff

**Comment by IntellectProductions** [comment]
Ah thanks! That helped out a lot :P I never thought about it for just years.. I guess that makes more sense!
