### ISSUE TITLE
Business Time

### ISSUE THREAD

**Issue by caycek** [briannesbitt/Carbon#364]
Do you have any desire or plan to add a business difference? 

The best way I can explain this is more along the lines of a 8-5 for the most basic idea. Where a full day is equivalent to 9 hours and only the times between x and y are considered to be a part of the "work day". It would exclude weekends. Since holidays are harder to do internationally I would say this would be an optional array of dates containing month and day. 

This is just a general idea to see where you are on the thought of this. If you have and thought it was an awful idea I would like to hear about it. If you don't want to put the time would it be worth it for me to try and put something together for you on my free time?

**Comment by brunowego** [comment]
+1

**Comment by Sverri** [comment]
What exactly are you thinking of? Is it not possible to solve something like this using existing methods/properties, like:

    $c = Carbon::now();
    if ( ! $c->isWeekend() && ($c->hour >= 8 && $c->hour < 17)) {
        echo "Work day";
    }

Or are you thinking about something more elaborate? If so, would it be possible to think about this in more generic terms, so that it does not just apply to businesses, but also other institutions (e.g. schools,, gyms, etc.)?

**Comment by dereuromark** [comment]
Not sure those times work for everyone.
This might be too specific to each country/region and might be best implemented in an extending class, e.g. `class BusinessCarbon extends Carbon {}`.

**Comment by caycek** [comment]
@Sverri You are right in the aspect of we could all rewrite this idea over and over again for each case we do and potentially get to a point where someone writes one any way (Which I'm surprised hasn't occurred yet **that i know of**). But for each country / case this might not be true and in reality I'm hoping we / I can come up with something strong enough to be implemented so all people will have to do is maybe some basic `CarbonBusiness` setup and then do `$something->businessDiff()` and bam calculates business time between two dates.
@dereuromark This is basically what I'm thinking needs to occur. Essentially you would extend carbon and include necessary business calculations that are involved with everyday needs. I haven't tried to implement it yet because I wanted to see if there is a following for this or if there was major resistance. I have done something with this that worked fairly well for my need, but it would be a pain to implement that into a global pattern because I hard coded so much.

Any ideas are welcome!

**Comment by caycek** [comment]
It might also be worth noting having weekends excluded by default would be ideal, but allowing an option to be set to include weekends depending on the need. Not all businesses work during just the week obviously.

**Comment by caycek** [comment]
@Sverri @dereuromark @briannesbitt I don't want to waste any time for anyone. I do see 1 positive remark, but if you guys don't think this is worth the time I can close this as to not clog the issue reports.

**Comment by rmblstrp** [comment]
I created a PR which adds Carbon extensions that check to see if a given date is a business day. Custom holiday and business schedules can be provided which allow you to properly determine what the date is for next or previous number of business days.

https://github.com/briannesbitt/Carbon/pull/706

**Comment by lucasmichot** [comment]
Good idea, this might got to `2.x` version though
