### ISSUE TITLE
Missing months and days of the week

### ISSUE THREAD

**Issue by iivanov2** [briannesbitt/Carbon#365]
In Carbon library is missing i18n of months and days of the week.
You could get them from http://jenssegers.be/projects/laravel-date project and include.

Now Carbon::setLocale i18n only string as:

```
'year'      => '1 year|:count years',
'month'     => '1 month|:count months',
'week'      => '1 week|:count weeks',
'day'       => '1 day|:count days'
```

but not months and days of the week.

Another big problem for using Carbon and Laravel 4.2 is that last version of Carbon 1.18 not work with Laravel 4.2, because Carbon 1.18 require 
sympfony/translation 2.6+ but Laravel 4.2 can update only to sympfony/translation 2.5.11
Can you change this?

Now I have to use laravel-date library to workaround these problems, but I have to install it additionally, it would be great if Carbon did the same things as laravel-date, because it is included in Laravel 4.2

**Comment by maarten00** [comment]
It would be great if you could create 1.17.1 with language support, I'm also running into this problem with Laravel 4.2

**Comment by GrahamCampbell** [comment]
Laravel 4.2 is not supported anyway.
