### ISSUE TITLE
Carbon add month fail

### ISSUE THREAD

**Issue by ryanhs** [briannesbitt/Carbon#389]
require 'vendor/autoload.php';

use Carbon\Carbon;

$a = Carbon::parse('2015-08-31');
$a->addMonth(); //<< this should be 2015-09-30 right?, 

var_dump($a); // this return 2015-10-01

**Comment by TheSerenin** [comment]
It seems this is a bug (or feature, since the 31st of September doesn't exist and would be October 1st) in PHP itself, not in Carbon.

Using the following code, I was able to reproduce it without Carbon (just DateTime, which Carbon extends from).

```php
$dateTime = new DateTime('2015-08-31');

$dateTime->add(DateInterval::createFromDateString('1 month'));

echo $dateTime->format('Y-m-d'); // 2015-10-01
```

**Comment by ryanhs** [comment]
ok, then.. if that the case we have to check first before use addMonth.
i see similiar issue in january, 

i assume this one not categorized as bug..

**Comment by briannesbitt** [comment]
You might want to check out `subMonthNoOverflow()`

**Comment by ryanhs** [comment]
Thank you :D

2015-06-18 22:29 GMT+07:00 Brian Nesbitt <notifications@github.com>:

**Comment by briannesbitt** [comment]
Np...  well actually in your case `addMonthNoOverflow()`  ;)
