### ISSUE TITLE
formatLocalized() returns a binary string

### ISSUE THREAD

**Issue by asivaneswaran** [briannesbitt/Carbon#392]
Hi,

I have this issue with formatLocalized().
        setlocale(LC_TIME, 'frc');
        dd($this->date->formatLocalized('%A \l\e %d %B %Y'));

This returns: b"samedi \l\e 13 décembre 2014" instead of just a normal string. Why is that?

Thanks,
Ara

**Comment by briannesbitt** [comment]
I just get `string(30) "mercredi \l\e 11 novembre 2015"`... looks fine?

What is your `dd()` doing?

**Comment by swey** [comment]
That's Laravel's "dump and die". Same problem here.

**Comment by seanirwin** [comment]
Use utf8_encode() on the return value of the formatLocalized() method to convert the binary string to a utf8 string.

**Comment by ricardobucho** [comment]
Is there a fix for this yet or nah?

**Comment by ricardobucho** [comment]
Fixed by using:
Carbon::setUtf8(true);
