### ISSUE TITLE
Documentation fixes

### ISSUE THREAD

**Issue by bburr** [briannesbitt/Carbon#396]
Hi, thanks for Carbon so much!

I wanted to contribute some updates to the documentation that I noticed but didn't see a way to do so directly.

In the CarbonInterval section, I think it should read 

```
The CarbonInterval class is inherited from the PHP DateInterval class.
```

with appropriate link to http://php.net/manual/en/class.dateinterval.php

Additionally, the word `documentation` is misspelled in the first sentence on the contribute page.

Thanks again!

**Comment by lucasmichot** [comment]
PR docs are welcome
