### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by udemethegrtman** [briannesbitt/Carbon#399]
I am running on laravel version 4.2.17 and i want to install carbon and i got this, please help

Basic usage: composer <command>
For more information just type "composer".

C:\Users\udeme samuel\Documents\jobinpal\pb updated\popibay>composer require nes
bot/carbon
Using version ^1.20 for nesbot/carbon
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for nesbot/carbon ^1.20 -> satisfiable by nesbot/carb
on[1.20.0].
    - Conclusion: remove symfony/translation v2.5.12
    - Conclusion: don't install symfony/translation v2.5.12
    - nesbot/carbon 1.20.0 requires symfony/translation ~2.6|~3.0 -> satisfiable
 by symfony/translation[v2.6.0, v2.6.1, v2.6.2, v2.6.3, v2.6.4, v2.6.5, v2.6.6,
v2.6.7, v2.6.8, v2.6.9, v2.7.0, v2.7.1].
    - Can only install one of: symfony/translation[v2.6.0, v2.5.12].
    - Can only install one of: symfony/translation[v2.6.1, v2.5.12].
    - Can only install one of: symfony/translation[v2.6.2, v2.5.12].
    - Can only install one of: symfony/translation[v2.6.3, v2.5.12].
    - Can only install one of: symfony/translation[v2.6.4, v2.5.12].
    - Can only install one of: symfony/translation[v2.6.5, v2.5.12].
    - Can only install one of: symfony/translation[v2.6.6, v2.5.12].
    - Can only install one of: symfony/translation[v2.6.7, v2.5.12].
    - Can only install one of: symfony/translation[v2.6.8, v2.5.12].
    - Can only install one of: symfony/translation[v2.6.9, v2.5.12].
    - Can only install one of: symfony/translation[v2.7.0, v2.5.12].
    - Can only install one of: symfony/translation[v2.7.1, v2.5.12].
    - Installation request for symfony/translation == 2.5.12.0 -> satisfiable by
 symfony/translation[v2.5.12].

Installation failed, reverting ./composer.json to its original content.

C:\Users\udeme samuel\Documents\jobinpal\pb updated\popibay>

**Comment by GrahamCampbell** [comment]
Yeh, you can only use an older version of carbon if you want to use such an old version of laravel.

**Comment by GrahamCampbell** [comment]
You shouldn't even try to install carbon anyway. Laravel already requires it.

**Comment by ubilli** [comment]
@GrahamCampbell  so how do i plug it in to my app.

**Comment by rbruhn** [comment]
I'm running into this same issue. Trying to reinstall a laravel site on a server that took a nose dive. Even though Laravel 4.2 has "nesbot/carbon": "~1.0", in the composer.json, it doesn't load anything. It creates the nesbot folder in the vendor directory but it's empty.

**Comment by Zae** [comment]
I'm getting almost the same problem, carbon won't update because laravel/laravel:4.2 requires symfony/translation:2.5.

Is symfony/translation:2.6 really required, or would 2.5 also work?

**Comment by mozaamisi** [comment]
12

**Comment by briannesbitt** [comment]
Sorry for the late reply, but I hope you got it working !
