### ISSUE TITLE
Class "Carbon" not found.

### ISSUE THREAD

**Issue by ubilli** [briannesbitt/Carbon#403]
I have just installed a carbon package, it installed fine but i want to ask where it the data i will add to the app.php > providers array becuase is keep given me this "Class Carbon not found" when i do this 
`{{  Carbon::now()->subModel(20)->diffForHumans(); }}`

**Comment by briannesbitt** [comment]
Looks like you are trying to access Carbon from a twig view?  Either pass the calculated value in from the controller to the view or do something like http://stackoverflow.com/questions/6844266/twig-template-engine-using-a-static-function-or-variable

As a side note, I don't think Carbon has a `subModel()` method.
