### ISSUE TITLE
Is there a way to get dayOfWeekName( i.e Monday or Tuesday)?

### ISSUE THREAD

**Issue by Amar-Myana** [briannesbitt/Carbon#411]
Problem: I want to display the date in this format "Tuesday, 28 July, 2015".

This can be achieved by below way:
```php
$today = Carbon::today();
$days[$today->dayOfWeek] . ', ' .  $today->toFormattedDateString();
```
But I need to duplicate the days array from carbon code. Is it possible to directly get the day of week name?

**Comment by briannesbitt** [comment]
Your code snippet doesn't give you your desired format.  Following the formats from http://php.net/manual/en/function.date.php you can just use `echo Carbon::now()->format('l, d F, Y');`.

**Comment by Amar-Myana** [comment]
Thank you! I get desired date format now.

**Comment by Lukmauu** [comment]
Carbon::now()->dayName

**Comment by laratutodotcom** [comment]
**How To Get Full Day Name From Date In Laravel Php?** https://laratuto.com/how-to-get-full-day-name-from-date-in-laravel-php/
