### ISSUE TITLE
Why is the locale for pt-BR specified in pt_BR.php instead of pt-BR.php?

### ISSUE THREAD

**Issue by vsch** [briannesbitt/Carbon#413]
Is this an error? The zh-TW.php is correct. 

The reason I ask is that I am using standard locale id's application wide and having a locale with an _ makes it a special case from all the other localized packages and not in agreement with ISO 639 (http://www.localeplanet.com/icu/iso639.html).

**Comment by briannesbitt** [comment]
It seems its used as a - or _ depending on the language.  Since this is PHP I guess it should be a "-" as http://php.net/manual/en/class.locale.php describes.

**Comment by glaubersp** [comment]
Hi,
I'd like to know why this commit was not merged into master.
As I could see doing a research on RFCs, programming languages should use pt-BR and UNIX uses pt_BR.
zh-TW was changed to zh_TW, also.
The point it laravel language should be set to pt-BR but carbon at the moment uses pt_BR.
If there is no consensus, keeping both pt-BR and pt_BR should be an option.
