### ISSUE TITLE
timestamp ignores timezone

### ISSUE THREAD

**Issue by TheShiftExchange** [briannesbitt/Carbon#417]
I have a Carbon object:

```
Carbon {#224 ▼
  +"date": "2015-08-05 00:21:01.000000"
  +"timezone_type": 3
  +"timezone": "Australia/Sydney"
}
```

If I do

```
$time->timestamp
```

I get

```
1438698061
```

But that is the equilivant timestamp for UTC of 2015-08-04 14:21

Why is the set timezone ignored for timestamps?

**Comment by caycek** [comment]
Did you resolve this or was the decimal after seconds what caused it?

**Comment by TheShiftExchange** [comment]
Sorry - I should have written;

A "timestamp" is by definition a UTC time since 1970. It is not supposed to have a timezone from what I can see - so therefore this makes sense....?
