### ISSUE TITLE
addWeekday(s) clears time

### ISSUE THREAD

**Issue by zlorkovic** [briannesbitt/Carbon#419]
Hi,

I'm using Carbon in latest Laravel version (5.1.8) and it seems that methods addWeekday and addWeekdays resets time from added date.

Other methods are working fine but this one resets time to 00:00:00.

**Comment by zlorkovic** [comment]
Hm...it seems like this is PHP bug from long time ago.

https://bugs.php.net/bug.php?id=54909

**Comment by arkeidolon** [comment]
addDay() seem to work just fine, just have to count how many weekends it would go through and add additional days to it.

**Comment by zlorkovic** [comment]
Yeah. Just need to take care of Saturdays and Sundays.

**Comment by arkeidolon** [comment]
#424 is the first step in solving this problem. I wrote some tests.

**Comment by dereuromark** [comment]
This is actually not fixed (or fixed incomplete).
See https://github.com/cakephp/chronos/pull/58
sub methods need fixing, and without ago the sub methods also dont work correctly

    return $this->modify("$value weekdays ago, ...)
