### ISSUE TITLE
Carbon::instance is broken

### ISSUE THREAD

**Issue by mnpenner** [briannesbitt/Carbon#423]
`Carbon::instance` does not create a perfect copy. 

If the datetime is during a leap hour, that information is lost. Was it the first 1am or the 2nd 1am?

This cost me several hours of frustration 

It's better to create the new object from a unix timestamp, à la

``` php
public static function instance(DateTime $dt) {
    $tz = $dt->getTimeZone();
    return (new static($dt->format('@U'), $tz))->setTimezone($tz); // must set timezone again; http://php.net/manual/en/datetime.construct.php#104111
}
```

But I can't figure out how to retain the microseconds.

**Comment by mnpenner** [comment]
Any update on this?

**Comment by kylekatarnls** [comment]
Hi, I'm working on the microseconds loss. The timezone part is now fixed.
