### ISSUE TITLE
formatLocalized('%d %B %Y') month not localized

### ISSUE THREAD

**Issue by azulkipli** [briannesbitt/Carbon#430]
Ive tried to localized date to Indonesian format, but month not localized.

```
        Carbon::setLocale('id');
        $date = Carbon::createFromTimeStamp(strtotime($comment->created_at));
        $date_only = $date->formatLocalized('%d %B %Y');
        echo $date->diffForHumans(); // 3 hari yang lalu 
        echo $date_only; // 31 August 2015


```

Anyone know how to corectly localized formatted month? or this is bug?

**Comment by briannesbitt** [comment]
For formatLocalized you still need to use the php call setlocale().  Its based on strftime();

http://carbon.nesbot.com/docs/#api-localization

**Comment by azulkipli** [comment]
Ive tried to use the function from that sample too but still the Month name not localized
```
setlocale(LC_TIME, 'Indonesia');
Carbon::setLocale('id');

        $date = Carbon::createFromTimeStamp(strtotime($comment->created_at));
        $date_only = $date->formatLocalized('%d %B %Y');
        echo $date->diffForHumans(); // 3 hari yang lalu 
        echo $date_only; // 31 August 2015
```

it still gave me same result

**Comment by dlepaux** [comment]
Helo !

I had the same issue.

The probleme come from your system.
If you work on Linux do `locale -a` to list enabled locales (same in prod).

Next do `sudo locale-gen id_ID.UTF-8` to install your locale and do `sudo dpkg-reconfigure locales` to publish it.

Reboot your system (`vagrant reload`) and enjoy

David

**Comment by azulkipli** [comment]
@dlepaux Thanks for your tips

**Comment by mauricehofman** [comment]
@dlepaux Your solution almost worked. I had to do it like this:

> setlocale(LC_TIME, 'nl_NL.utf8');

**Comment by irvv17** [comment]
nice

**Comment by mtx-z** [comment]
Thanks @dlepaux :)

**Comment by ukasyahrz** [comment]
It has bug when converting number to month while setlocale is Indonesian, number "2" will become Maret (March), Februari(February) is gone.

**Comment by kovinet** [comment]
@dlepaux system reboot is required for this? Is there another way?

**Comment by dlepaux** [comment]
@kovinet It seem to be not possible (no hot-plug)

**Comment by kylekatarnls** [comment]
Hi, formatLocalized use locales installed on your operating system, so if the locale is not supported by your OS, you need to install it. In this case `setlocale` will return `false`.

That's why this method you really should use the new method `isoFormat` instead with Carbon 2 as documented:
https://carbon.nesbot.com/docs/#api-localization

You'll get directly 823 locales embedded and many more translation features than with formatLocalized in a really more reliable way.

**Comment by kovinet** [comment]
@kylekatarnls thanks, this is much better solution, I don't like to depend on system locales.

**Comment by arhakim** [comment]
Alternatively, you can use this:
```
setlocale(LC_ALL, 'IND');
$formattedDate = strftime('%d %B %Y, %H:%M', strtotime($item->created_at));
```

**Comment by mtx-z** [comment]
What I had to do on Debian 10:

1. run `dpkg-reconfigure locales`
2. select and install locales package (in my case, I choosed `fr_FR.utf8`)
3. At start of script 
```
setlocale(LC_TIME, 'fr_FR.utf8');
\Carbon\Carbon::setLocale('fr');
\Carbon\CarbonInterval::setLocale('fr');
```

**Comment by aristrisnawan** [comment]
> Alternatively, you can use this:
> 
> ```
> setlocale(LC_ALL, 'IND');
> $formattedDate = strftime('%d %B %Y, %H:%M', strtotime($item->created_at));
> ```

Thank you, this worked
