### ISSUE TITLE
Why not handle intervals created with diff?

### ISSUE THREAD

**Issue by sandermarechal** [briannesbitt/Carbon#434]
Why are intervals created with DateTime::diff() not supported? Why not override the diff() method to fix this and return a CarbonInterval instead of a DateInterval?

I have read the source and read the git history but I cannot figure out why support for this was removed.

**Comment by briannesbitt** [comment]
You can't set `days` internally so if you do create from a diff() result and then try and do `echo $ci->days` you get false in later version of PHP but you will get -99999 in earlier versions and I can't change it.  Mind you it works if you access dayz.

**Comment by sandermarechal** [comment]
Thanks for the explanation
