### ISSUE TITLE
Carbon diffForHumans incorrect diff

### ISSUE THREAD

**Issue by wanchopeblanco** [briannesbitt/Carbon#436]
Im having an issue with the diffForHumans function, the diff is assuming that the date is in the past when it really is in the future for example.

2015-10-14 10:54:20 : hace 4 semanas (4 weeks ago)
It should be showing en 4 semanas (in 4 weeks) 

I always have found that when using it without HHVM it works ok, it only shows it incorrectly when using HHVM.

**Comment by briannesbitt** [comment]
Yes, seems like there are some diff issues with hhvm.

https://travis-ci.org/briannesbitt/Carbon/jobs/90568615
