### ISSUE TITLE
diffForHumans shows 45 years ago

### ISSUE THREAD

**Issue by DeeJaVu** [briannesbitt/Carbon#440]
Hello i have the same problem but for unixtimestam, i tried parse() but it says

    DateTime::__construct(): Failed to parse time string (1442664851) at position 8 (5)

this is how my code looks like when it displays '45 years ago'

    {{ Carbon::createFromTimeStamp(strtotime($r['created_time']))->diffForHumans()  }}

**Comment by briannesbitt** [comment]
It looks like you have a timestamp there.  Either use `Carbon::createFromTimestamp(1442664851)` or to ignore timezone use `Carbon::createFromTimeStampUTC('1442664851')` which is equivalent to `Carbon::parse('@1442664851')`.

**Comment by DeeJaVu** [comment]
aha this works perfect. Thank you so much
    
    {{ Carbon::createFromTimeStampUTC($r['created_time'])->diffForHumans()  }}

**Comment by saji89** [comment]
@briannesbitt Looks like this bug can be closed. :smiley:
