### ISSUE TITLE
Set default Locale for translation

### ISSUE THREAD

**Issue by fobus42** [briannesbitt/Carbon#442]
Hello,

I couldn't find any good way to set the default lacalization. Change config/app.php doesn't effect. Then I have found and changed translator function like this on Carbon/Carbon.php file

```
protected static function translator()
    {
        if (static::$translator == null) {
            static::$translator = new Translator((config('app.locale')!='')?config('app.locale'):'en');
            static::$translator->addLoader('array', new ArrayLoader());
            static::setLocale((config('app.locale')!='')?config('app.locale'):'en');
        }

        return static::$translator;
    }
```
And now localization works good :)

**Comment by briannesbitt** [comment]
Looks like you are using Carbon in a framework.

Just call the setLocale() with the config setting you have somewhere in your framework bootstrap.  no need to modify Carbon itself.
