### ISSUE TITLE
Birthdays that fall on leap days only return true once a year

### ISSUE THREAD

**Issue by dhensby** [briannesbitt/Carbon#445]
Leaplings, as they are known, are born on 29th Febuary.

When using the `isBirthday` function their birthday would only be recognised once every 4 years, which is a bit of a bummer.

`isBirthday` should return true for 29th Feb on the 28th Feb IF it's not a leap year.

**Comment by dereuromark** [comment]
That is not that trivial.
According to wikipedia, it can then be "on either February 28 or March 1" depending on the country you are in (legally). And personally you can chose usually anyway.
But I agree, it is better to at least display it then e.g. 28th then not at all.

**Comment by dhensby** [comment]
True, but better to have a result for it than not at all. 

Perhaps a new method is needed `isAnniversary` for when you just want to know if this is the same day / month? Though you could argue aniversaries suffer the same problem...

**Comment by dereuromark** [comment]
I tested it and it does return true for March, 1st for me.
So it seems to work as "in general" people would expect.
28th would be something you would have to "configure" on a project level maybe, if you wanted it to be true earlier then it actually is.

**Comment by briannesbitt** [comment]
A true for march 1 makes sense to me as a good default.... Mimics PHP behaviour with carry over.

An anniversary is a birthday is an anniversary ;)

**Comment by dhensby** [comment]
> An anniversary is a birthday is an anniversary ;)

well, that's true from a language point of view, but I'm considering from a technical "we want to know if this is the exact same day" vs "we want to know if it's this user's 'birthday'"
