### ISSUE TITLE
Automatic localization fallback

### ISSUE THREAD

**Issue by jBOKA** [briannesbitt/Carbon#447]
Hi everyone,
I am using Carbon in the context of OctoberCMS/Laravel.
Since the system provides a `locale` and a `fallback_locale` I'd like to pass them through.
Unfortunately there is no error handling in the `setlocale` function, so a `FatalErrorException` from the static::translator()->addResource() is thrown and not handled, when passing a language Carbon doesn't support.
I understand the Symfony Translator has fallback functionality implemented, but I don't know how to access it through Carbon. Is there a way to handle this problem?

**Comment by briannesbitt** [comment]
If the current implementation doesn't work for you (although i think you could catch the exception and handle it) You can do whatever you want to create a translator object (own lang files etc) and use the setTranslator() to set it in Carbon.

**Comment by jBOKA** [comment]
Thanks for your answer.
I misunderstood the problem. The problem actually is, that when adding a resource to the translator in `Carbon::setLocale()`
https://github.com/briannesbitt/Carbon/blob/master/src/Carbon/Carbon.php#L961
you are using a `require` which is not catchable (or am I wrong?). Maybe a `file_exists` and throw an error,or switch to include to have a catchable error would solve the issue.

**Comment by briannesbitt** [comment]
Added a file exists check and a bool return.

**Comment by jBOKA** [comment]
Thanks a lot.
