### ISSUE TITLE
Allow isBirthday() to work with current day by default

### ISSUE THREAD

**Issue by dereuromark** [briannesbitt/Carbon#448]
We added this recently to Chronos.
It should be a valuable addition to Carbon, as well.

```php
$birthday = new Chronos($birthdayString);
$isBirthday = $birthday->isBirthday(); // Today by default (as in 99% of all use cases)
```

See https://github.com/cakephp/chronos/pull/24/files

**Comment by briannesbitt** [comment]
Makes sense... adding.  Thanks !
