### ISSUE TITLE
Copy created by copy() is wrong when using HHVM.

### ISSUE THREAD

**Issue by Johannestegner** [briannesbitt/Carbon#449]
One of the APIs I'm using gives me a (unix/epoch)timestamp which I convert to a Carbon object, I do this by using the `createFromTimestampUTC` method, a copy of the object is later made (by using `$orig->copy();`).
In my tests the default timezone is set to a none-UTC timezone. Comparing the copied object with the original - or another carbon object created with the same timestamp - results in a error when using HHVM instead of plain PHP.  

Test case:
```php
<?php

use Carbon\Carbon;

class CarbonCopyTest extends PHPUnit_Framework_TestCase {

    protected function setUp() {
        date_default_timezone_set('Pacific/Pohnpei');
        Carbon::setTestNow(null);
        Carbon::setTestNow(Carbon::now());
    }


    public function testCarbonCopy() {
        $dateTime = Carbon::createFromTimestampUTC(1434832348);
        $dateTimeCopy = $dateTime->copy();
        $this->assertEquals($dateTime, $dateTimeCopy);
    }
}
```

PHP passes fine, HHVM produces the following error:

```
There was 1 failure:

1) CarbonCopyTest::testCarbonCopy
Failed asserting that two DateTime objects are equal.
--- Expected
+++ Actual
@@ @@
-2015-06-20T20:32:28+0000
+2015-06-20T20:32:28+1100
```

objects `toAtomString` output:
```
PHP:
array:2 [
  "orig" => "2015-06-20T20:32:28+00:00"
  "copy" => "2015-06-20T20:32:28+00:00"
]

HHVM:
array:2 [
  "orig" => "2015-06-20T20:32:28+00:00"
  "copy" => "2015-06-20T20:32:28+11:00"
]
```

Versions:
HipHop VM 3.9.1
PHP 5.6.4

**Comment by Johannestegner** [comment]
Used this as temporary walk-around:  
  
```    
$dateTime = Carbon::now('UTC');
$dateTime->setTimestamp(1434832348);
```

Using above code produces same result for both php and hhvm, same result as php did in earlier code.

**Comment by briannesbitt** [comment]
I think you could also use `createFromTimestamp(1434832348, 'UTC');` to do it in 1 step ... the src is exactly what you are doing.
