### ISSUE TITLE
Suggestion: Comparsion isDayofWeek(0-6) or isMonday()

### ISSUE THREAD

**Issue by websygen** [briannesbitt/Carbon#455]
It will be nice if there is shorthand comparison to test is some date Monday, Tuesday...
this cal look as
`$dt->isDayofWeek(0)` or `$dt->isMonday()` return boolean
`$dt->isDayofWeek(1)` or  `$dt->isTuesday()` return boolean
and so on...
I know that I can check this with current functionality, but if there is short way it will be great.

**Comment by mtdavidson** [comment]
I think this has already been done https://github.com/briannesbitt/Carbon/blob/74711084ac7fdcc9ec13b802d7af030617f3b168/src/Carbon/Carbon.php#L1385 is that not what your looking for?

**Comment by websygen** [comment]
yes you are correct - just missing in the docs, I guess
