### ISSUE TITLE
Documentation page should point out namespace of Carbon\Carbon

### ISSUE THREAD

**Issue by dlancea** [briannesbitt/Carbon#458]
Neither the top of the front page nor the documentation page of http://carbon.nesbot.com/ point out the Carbon class' namespace. If you skip the Getting Started section of the front page and jump straight to the docs you might miss that you need to use Carbon\Carbon.

I had to look at the code to figure out the correct namespace.

It would be good to add the use statement to the sample code at the top of the front page and to somewhere in the docs page. Also, maybe the sample code in the GitHub readme.

**Comment by briannesbitt** [comment]
Ok, done.
