### ISSUE TITLE
dst always returning false?

### ISSUE THREAD

**Issue by mikeRead** [briannesbitt/Carbon#509]
When I try the example in the docs it always get false back
```php
// Indicates if day light savings time is on
var_dump(Carbon::createFromDate(2012, 1, 1)->dst);           // bool(false)
var_dump(Carbon::createFromDate(2012, 9, 1)->dst);           // bool(true)
```
returns
```
bool false
bool false
```

**Comment by briannesbitt** [comment]
Where (tz) is the server you are running this on?

echo Carbon::now()->tzName;

**Comment by mikeRead** [comment]
it returns 'UTC'

**Comment by briannesbitt** [comment]
That makes sense.... UTC doesn't experience DST.

There is a call out at the top of the docs:
Note: I live in Ottawa, Ontario, Canada and if the timezone is not specified in the examples then the default of 'America/Toronto' is to be assumed. Typically Ottawa is -0500 but when daylight savings time is on we are -0400.

**Comment by mikeRead** [comment]
I was just googleing UTC timezones and it does make a lot of sense.
I guess I need to figure out a workaround for what im trying to do. Thank you so much for your help and so fast too!

**Comment by briannesbitt** [comment]
Np
