### ISSUE TITLE
Add formatting constant / helper functions for databases

### ISSUE THREAD

**Issue by SamMousa** [briannesbitt/Carbon#523]
In our own custom DateTime class we have added some constants like:
`MYSQL_DATE`, `MYSQL_DATETIME`

These formats allow us to easily format a string before sending it to the database.

Would it be possible to add a `DB_DATE` format, for the most common databases (I'm sure we can think of a format that is parsed by most if not all databases)?

This would alllow us to switch to your library instead

-- I'm willing to make the code and PR, just checking if you think this could be good for Carbon.

**Comment by Glavic** [comment]
Method `toDateString()` returns `Y-m-d` and `toDateTimeString` returns `Y-m-d H:i:s`  which is probably understood by most databases out-there. 
What do your constants `MYSQL_DATE`and `MYSQL_DATETIME` contain?

**Comment by SamMousa** [comment]
Yes; I guess things were different in 2015 :p

**Comment by Glavic** [comment]
@SamMousa: sorry mate, just cleaning old PR's, don't even look at the created dates :) Good to see you still around :) BR
