### ISSUE TITLE
Norwegian has two different locales

### ISSUE THREAD

**Issue by anlutro** [briannesbitt/Carbon#527]
Norwegian has two forms of its written language - Norwegian Bokmål and Norwegian Nynorsk. In linux, these locales are expressed as `nb_NO` and `nn_NO` respectively.

I can submit a pull request for these locales, but would like to know what to do with the existing file `Lang/no.php`. I assume it has to stay for backwards compatibility reasons? Ideally it should be a symlink to `nb.php`.

**Comment by martinlindhe** [comment]
Personally, I'd love to see the existing locales be changed to have the nb_NO.php names. It would solve this, and all other such cases

**Comment by lucasmichot** [comment]
@anlutro , if these Norwegian languages are different, you could definitely do so.
I think we are using a different classification: mainlanguage_SUBLANGUAGE/COUNTRYCODE
Like
fr_FR
fr_BE
fr_CH
Feel free to provide new and updated translations with tests. Also I don't know if Norwegian use cases? If so, you can get get #584 `HuTest.php` as a starting point.

Also I think you could let the `no` file as a fallback. Is one of these two norwegian locale more widely used (media, TV...) ? If so this could be the main fallback locale...


Thanks !

**Comment by nickyoung87** [comment]
We are using Carbon in a WordPress plugin and have gotten a few errors where after much troubleshooting it came down to this issue. Do you guys think there will be a fix for this soon or is there something we can do as a workaround for now?

**Comment by lucasmichot** [comment]
Ping @briannesbitt

**Comment by briannesbitt** [comment]
Is there a PR for this ?

**Comment by lucasmichot** [comment]
I think @anlutro was waiting for your feedback before making one ;-)

**Comment by shooka** [comment]
> Ideally it should be a symlink to `nb.php`.

Unix symlinks are not supported in Windows. If this should be backward compatible, you'd have to create some kind of map between the language identifiers `'nn_NO' => 'no'` that can be removed in a future V2

**Comment by anlutro** [comment]
Someone else should feel free to pick up the PR, I probably won't get around to it at this point.

**Comment by kylekatarnls** [comment]
Hi, we'll keep the no.php until someone propose us a PR for nb locale.
