### ISSUE TITLE
Add ordinal suffix for formatLocalized()?

### ISSUE THREAD

**Issue by igorsantos07** [briannesbitt/Carbon#535]
As seen in [this comment](http://br2.php.net/manual/en/function.strftime.php#104894), `strftime()` misses the ordinal suffix for days (such as "Jan 1**st**"), but it's pretty easy to include this and provide an even better support for localized strings.

Do you think it's possible? I would step in to do it if agreed.

**Comment by fenoria** [comment]
I also need this !

**Comment by codep0et** [comment]
+1 for this.

**Comment by plauclair** [comment]
@briannesbitt would you accept a PR on this if I submit one?

**Comment by manticorp** [comment]
+1 for this!

**Comment by wlarch** [comment]
+1 for this !
@plauclair You never got an anwser for this. Found a solution ?
@briannesbitt This would be a very good feature to add to the formatLocalized() method.

**Comment by plauclair** [comment]
I implemented my own wrapper based on the locale to handle this. We ended up just sending the timestamp to the frontend and dealt with it using MomentJS..

**Comment by wlarch** [comment]
Thanks for the reply. I finally implemented a DateHelper myself using the `$date->format('l, F jS Y')` method for English dates and `$date->formatLocalized('%A, %e %B %Y')` for French. Bonne soirée!

**Comment by kylekatarnls** [comment]
`formatLocalized` is made for that, please use the @wlarch solution.
