### ISSUE TITLE
Wrong locale used with php setlocale() and diffForHumans()

### ISSUE THREAD

**Issue by federico77** [briannesbitt/Carbon#538]
Hello, I am using version 1.21 and I noticed that using the following:

`setLocale(LC_TIME, 'it_IT.utf8');`
`return Carbon::now()->diffForHumans();`

... returns the string in english even if `setLocale()` is properly set to  `it_IT`.

Setting the Carbon locale with `Carbon::setLocale('it')` returns properly localized strings with diffForHumans(). 

While using this works nicely:
`return Carbon::now()->formatLocalized('%A %d %B %Y');`

Thanks and keep up the good working!

**Comment by nicholas-eden** [comment]
https://github.com/briannesbitt/Carbon/pull/540

Look this over, I think it should solve your issue.

**Comment by federico77** [comment]
Cool! :+1:

**Comment by federico77** [comment]
Is this going to be merged anytime soon?
