### ISSUE TITLE
Caron::now() returns date offset to 1970

### ISSUE THREAD

**Issue by jerryhanks** [briannesbitt/Carbon#550]
Tymon JWt-Auth uses Cabon and i discovered that the expiry date is alway wrongly coded to 1970, i think the issue is from Carbon::now(), this make the json web token always expired as it is coded in the past.

**Comment by briannesbitt** [comment]
You are going to have to provide more info.  Obviously if you take Carbon out of the context of jwt-auth and just do `echo $first = Carbon::now();` you get the correct date/time.  It that is happening it must be something specific about the context.

**Comment by jerryhanks** [comment]
i found the problem, android System.getCurrentTimeMillis() returns time in milliseconds and it does not match the 10 digit returned from the server and when i try to parse the 13 digits from android and compare it against 10 digits from server, it does not match, though they are created at the same time .

**Comment by briannesbitt** [comment]
Divide by 1000.  Never used jwt-auth but if you using a token to keep a user alive you probably should set it into the future by X minutes anyway so a slight difference in system clocks is not relevant (Or 0 if it's a session token).

**Comment by jerryhanks** [comment]
Even when i divide it by 1000, the date does not tally still.

**Comment by briannesbitt** [comment]
What do you get from the java `System.getCurrentTimeMillis()` call ?

When I run the call here in Java I get "1450064567335".

When I then move that value over to PHP Carbon and do:

```
echo Carbon::createFromTimestamp(1450064567335);
echo PHP_EOL;
echo Carbon::createFromTimestamp(1450064567.335);
```

I get:

```
1918-03-18 08:54:47
2015-12-13 22:42:47
```

... which seems right to me (I am currently -5 UTC).

**Comment by jerryhanks** [comment]
Thanks for that, but how do you handle the 10 digits sent from the server, how do u insert the lass three millis so that it will be up to 13, if you pass 10 digits to the android DATE TIME it returns past years?
