### ISSUE TITLE
Problem with accented letters on Windows/IIS

### ISSUE THREAD

**Issue by ivanhalen** [briannesbitt/Carbon#558]
Hello,
I'm using Carbon 1.21.0 on Windows 10 with IIS 10.0.10586.0 and PHP 5.6
When using italian language I have issues with accented letters
I.e. this page:
```
<?php
require_once('Carbon/Carbon.php');
use Carbon\Carbon;
setlocale(LC_TIME, 'it');
?>
<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>Carbon Test</title>
</head>

<body>
<?php
$date = '2015-12-14';
$dt = Carbon::parse($date);
echo $dt->formatLocalized('%A %d %B %Y');
?>
</body>
</html>
```
Turns into `luned� 14 dicembre 2015`
I have to use `utf8_encode($dt->formatLocalized('%A %d %B %Y'))` to get the right output: `lunedì 14 dicembre 2015`

More, on Laravel 5.1 I have no output: i.e. `{{ $record->created_at->formatLocalized('%A %d %B %Y') }}` outputs nothing and I still have to use `utf8_encode()` to get the output:
```
{{ utf8_encode($record->created_at->formatLocalized('%A %d %B %Y')) }}
```
I can use `setlocale(LC_TIME, 'it');` or `setlocale(LC_TIME, 'Italian');` but I can't use `setlocale(LC_TIME, 'IT_it.utf8');` or similar notation since it doesn't work

I googled around but seems that no one has my problem (maybe because they all use Apache): is this a Carbon issue, specific with IIS?
Thanks

**Comment by nicholas-eden** [comment]
I'm suspecting that the problem is a mismatch between the character set from the time and the character set in html:
```
<meta charset="utf-8">
````

There is some documentation on what I think is C, which PHP might be wrapping: https://msdn.microsoft.com/en-us/library/x99tb11d(v=vs.90).aspx

ANSI seems to be the default character set for windows, maybe change your charset tag to ANSI.

**Comment by ivanhalen** [comment]
Hi Nicholas, and thanks for the answer
I looked at the page and tried several things (I used the provided French example since I still don't know the code for Italian language) like:
```
setlocale(LC_TIME, 'French_Canada.1252');
setlocale(LC_TIME, 'French_Canada.ACP');
setlocale(LC_TIME, 'French_Canada.OCP');
```
and of course removing the `utf8_encode()` function
Well, they still all lead to problems with accented letters, like `lundi 14 d�cembre 2015 `
Is there anything else I can try, as far as you know?

Thanks

**Comment by briannesbitt** [comment]
I just ran your php file like this `php try.php > try.html` and then dragged that file into Chrome and I get the � as you mentioned above.

I then took the file and changed the encoding to utf-8 (it was ANSI encoded) and hit reload in Chrome and then it was fine.

P.S. Close your meta html tag.  `<meta charset="utf-8" />`

**Comment by ivanhalen** [comment]
Hi briannesbitt,
Just tried what you did and it works: but does this mean that I have to change my php files into html?!? :-/ It would be crazy...
I also tried to save the php file with UTF-8 encoding with Sublime Text (File > Save with encoding > UTF-8) but no luck...

**Comment by briannesbitt** [comment]
This worked with the php dev server when it didn't with just plain output.

```
<?php
require 'vendor/autoload.php';

use Carbon\Carbon;

setlocale(LC_TIME, 'it');

class CarbonUtf8 extends Carbon
{
    public function formatLocalized($format)
    {
        return utf8_encode(parent::formatLocalized($format));
    }
}

?>
<!doctype html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Carbon Test</title>
</head>

<body>
<?php
$date = '2015-12-14';
$dt = CarbonUtf8::parse($date);
echo $dt->formatLocalized('%A %d %B %Y');
?>
</body>
</html>
```

**Comment by ivanhalen** [comment]
Thanks for the answer, briannesbitt, but this moves the problem elsewhere, doesn't solve the original one (I still have to use utf8_encode())... I think I have to go with Apache...

**Comment by rypsx** [comment]
Same issue for me, still in French translation. Thank you for your help ivanhalen

**Comment by thekoko** [comment]
Same problem with french special characters. Thanks for utf8_encode()!

**Comment by didinyah** [comment]
Same issue... thank you for utf8_encode() you saved me !

**Comment by briannesbitt** [comment]
The utf8 encode has been added to Carbon directly.
