### ISSUE TITLE
startOfDay and endOf* are mutable, could it be immutable?

### ISSUE THREAD

**Issue by HonzaMac** [briannesbitt/Carbon#560]
Is it possible to make methods `startOfDay()` and `endOfDay()` make immutable, so I dont need to do manual `->copy()` and use that instance as is?

```
$date = new Carbon($dateString);
$fromDate = $date->copy()->startOfDay();
$toDate = $date->copy()->endOfDay();

...->whereBetween('DepartureAt', [$fromDate, $toDate]));
```

For me is much more better to use it like this: 

```
$date = new Carbon($dateString);
...->whereBetween('DepartureAt', [$date->startOfDay(), $date->endOfDay()]));
```

What do you think?

**Comment by digilist** [comment]
As all methods of Carbon are mutable, this change would be very inconsistent. Furthermore, it would introduce a major BC break. I am :-1: on this

**Comment by dereuromark** [comment]
If you need immutable, you should look into the [Chronos](https://github.com/cakephp/chronos) successor, which runs on PHP 5.5.9+ and thus is supposed to support Immutable for DateTime and Date.

**Comment by timacdonald** [comment]
I've just made a little package wrapper around Carbon to make it immutable.

https://github.com/timacdonald/immutable-carbon
