### ISSUE TITLE
last month return  current month

### ISSUE THREAD

**Issue by rudemex** [briannesbitt/Carbon#562]
Hi, the function last month return current month. example

$now = Carbon::now('America/Argentina/Buenos_Aires');
$currenDate = Carbon::now('America/Argentina/Buenos_Aires');
$prevDate = new Carbon('last month','America/Argentina/Buenos_Aires');
$nextDate = new Carbon('next month','America/Argentina/Buenos_Aires');

RETURNS
$currenDate => 2015/12/31
$prevDate => 2015/12/31
$nextDate => 2016/01/01

**Comment by lucasmichot** [comment]
@rudemex this is the way `\Datetime` handles it.
Feel free to use `subMonthNoOverflow()` and `addMonthNoOverflow()`
