### ISSUE TITLE
How to find the beginning of the last x quarters - Carbon::now()->subQuarters(3) needed?

### ISSUE THREAD

**Issue by andreasba** [briannesbitt/Carbon#573]
Hello,

first of all thanks for this great library! I am new to Laravel and use Carbon extensively.

Now I am running into a problem where I am not sure whether I can easily solve this with the current feature set. What I want to do is
```PHP
Carbon::now()->subQuarters(3)
```
That means I want to find the beginning of -3 quarters. So if you take today, I want to be able to get the first day of the 3rd quarter of 2015, for example.

I thought about using firstDayOfMonth()->subMonths(3) but this is not clean, obviously. Then I thought about getting the current month, manually checking in which quarter it is and returning the difference in months to the beginning of this quarter. But it all is a mess.

Is there any way to achieve what I am trying to do?

Thanks
Andreas

**Comment by lucasmichot** [comment]
See https://github.com/briannesbitt/Carbon/pull/578

**Comment by lucasmichot** [comment]
Since #578 has been merged, can you close this issue @andreasba ?

**Comment by andreasba** [comment]
Thank you @lucasmichot , closed
