### ISSUE TITLE
startOfWeek the same as endOfWeek

### ISSUE THREAD

**Issue by redjanym** [briannesbitt/Carbon#574]
Hi, i just found that startOfWeek returns the same value as endOfWeek. I had this case:

$carbon = new Carbon();
$first_date_of_week = $carbon->startOfWeek();
$last_date_of_week = $carbon->endOfWeek();

dump($first_date_of_week);
dump($last_date_of_week);
----- Result 
![screenshot](https://cloud.githubusercontent.com/assets/15679866/12237978/c66c8d32-b881-11e5-9287-9f1be87c1569.png)

**Comment by nicholas-eden** [comment]
The problem is both variables refer to the same object. The methods modify the object and return it rather than creating a new object. 

Instead use the copy method to have an object for each date.

**Comment by redjanym** [comment]
I noticed it. I cloned the Object as a new Object. 
Thanks for the replay.
