### ISSUE TITLE
suggestion, count month less than full-month

### ISSUE THREAD

**Issue by alfaex** [briannesbitt/Carbon#576]
it would be nice if had a option to count mount like this.

start = 2015-05-30
end = 2015-06-01

start->diff(end, 'some parameter') = 1
because i don't need the difference by days, what i care is for the change of month, not the quantity of days.

**Comment by mikevrind** [comment]
What about the diffInMonths method? https://github.com/briannesbitt/Carbon/blob/master/src/Carbon/Carbon.php#L2142
