### ISSUE TITLE
Check for invalid date

### ISSUE THREAD

**Issue by 73sl4** [briannesbitt/Carbon#583]
Can we have a isValid(), currently there is no way to check if a date is valid or not.
Also, if I use Carbon as:
```php
$dt = Carbon::createFromDate(2016, 01, 32);
echo $dt->toDateString(); // 2016-02-01
```
Returned instance is for incorrect date, it should either return a null object or throw InvalidDateException

**Comment by lucasmichot** [comment]
@73sl4 this is the normal behaviour of `\DateTime` which is extended.
Nevertheless, you can maybe try something like this...

```php
public static function createSafe($year = null, $month = null, $day = null, $hour = null, $minute = null, $second = null, $tz = null)
{
    $year = $year === null ? date('Y') : $year;
    $month = $month === null ? date('n') : $month;
    $day = $day === null ? date('j') : $day;

    if ($hour === null) {
        $hour = date('G');
        $minute = $minute === null ? date('i') : $minute;
        $second = $second === null ? date('s') : $second;
    } else {
        $minute = $minute === null ? 0 : $minute;
        $second = $second === null ? 0 : $second;
    }

    $attributes = array_filter(compact($year, $month, $day, $hour, $minute, $second));

    $unsafeInstance = static::create($year, $month, $day, $hour, $minute, $second, $tz);

    foreach ($attributes as $key => $value) {
        if ($unsafeInstance->$key != $value) {
            throw new \InvalidArgumentException(sprintf("Attribute %s : %s is not a valid value", $key, $value));
        }
    }

    return $unsafeInstance;
}
```

But this is quite hacky

**Comment by 73sl4** [comment]
@lucasmichot I think this will work. Are you going to add it to Carbon repo?

**Comment by lucasmichot** [comment]
We're open to PRs submission

**Comment by RRStoyanov** [comment]
There is a PHP function [checkdate](http://php.net/manual/en/function.checkdate.php) which validates  give Gregorian date. So I think it can be added to Carbon as isValidGregorian() method. I might think of adding is to my current project and maybe create a PR?

**Comment by lucasmichot** [comment]
Indeed, this function is useful. Nevertheless, I think that it would be more useful to provide the key (year, month, day, hour, minute or second) and the "unsafe" value 

If not PR comes the next days, I’ll take care of it.

On 26 January 2016 at 20:19:12, Rostislav Stoyanov (notifications@github.com) wrote:

There is a PHP function checkdate which validates give Gregorian date. So I think it can be added to Carbon as isValidGregorian() method. I might think of adding is to my current project and maybe create a PR?

**Comment by lucasmichot** [comment]
Since #588 has been closed, can this be closed @73sl4 ?

**Comment by 73sl4** [comment]
Sure.
