### ISSUE TITLE
Update docs with link to or to embed datetime formats

### ISSUE THREAD

**Issue by InstanceOfMichael** [briannesbitt/Carbon#598]
You should update the docs to include a link to or to copy the datetime format documentation from this page:

http://php.net/manual/en/datetime.createfromformat.php

Every time I need to look for this page it is never intuitive to find this page. I usually bookmark it, but I think it would be appropriate for this library to at least add a link to it.

**Comment by lucasmichot** [comment]
Feel free to open a PR @InstanceOfMichael
