### ISSUE TITLE
Serializing a Carbon\Carbon date doesn't work in HHVM

### ISSUE THREAD

**Issue by JoelESvensson** [briannesbitt/Carbon#599]
It's easily reproducible in 3.11.1 (lastest HHVM as of now) with this one-liner:

`serialize(Carbon\Carbon::now());`

**Comment by GrahamCampbell** [comment]
Surely you should report this to the HHVM team? It's not the job of PHP libraries to change to work on HHVM, it's the job of HHVM to be properly PHP compliant.

**Comment by JoelESvensson** [comment]
Don't worry, i've also reported it on their issue tracker as well.

**Comment by farizluqman** [comment]
Any updates?

**Comment by kylekatarnls** [comment]
I agree with @GrahamCampbell and I would not spent efforts for HHVM (already spent too much in too many libraries), now with PHP 7, HHVM is no longer enough compatible and no longer provide performance advantage.

If you know how to fix and want to propose a PR for this, it is welcome, we will merge it if it does not break anything.

But our very small core team (compared to HHVM one) will focus on features and bugs with official PHP releases.

Thanks,
