### ISSUE TITLE
Locking instance for changing date

### ISSUE THREAD

**Issue by Quanthir** [briannesbitt/Carbon#603]
Hello,

If there is a posibility to lock the carbon instance for updating date?

For example I have a Task class when getCreationDate() called, it gives the creation date as Carbon instance. But I want to lock this instance so that It can never be updated. Because creation date must not changed.

For now, I am cloning the instance in the getter method every time.

If this is a good feature I might fork and patch it.

**Comment by lucasmichot** [comment]
@Quanthir, I think this is exactly the purpose of `\Carbon\Carbon::setTestNow()`

**Comment by Quanthir** [comment]
@lucasmichot, Yes it is something like that but everytime I update the database or do something internal in the Task class I need to call `\Carbon\Carbon::getTestNow()` I want to give the coder an instance of Carbon class who uses the Task class. But I don't want creation date to be changed.

I think this option does not nessesary. I am simply cloning the object and returning it in function.
