### ISSUE TITLE
[Idea] Concept of custom formatters / alias.

### ISSUE THREAD

**Issue by garygreen** [briannesbitt/Carbon#606]
It would be good if you could specify custom-named formats straight within Carbon. This would be immensely useful for normalizing various systems that have many different 'named' date formats, without having to write a wrapper on top of Carbon every time.

```
Carbon::addAlias('cms_date_time', 'd/m/Y H:i');
Carbon::createFromAlias('cms_date_time', '12/05/2015 05:36');
Carbon::now()->toAliasFormat('cms_date_time');
```

**Comment by lucasmichot** [comment]
See #608

**Comment by briannesbitt** [comment]
For formatting specifically we have enough ways to store and read strings that can just as easily be passed to the format() function.  For real functionality I don't see this as a better solution to a subclass.
