### ISSUE TITLE
Danish (DK)

### ISSUE THREAD

**Issue by Sennik** [briannesbitt/Carbon#609]
Can some Danish user create a Danish translation file?

**Comment by lucasmichot** [comment]
We're open to PR @Sennik

**Comment by Sverri** [comment]
@Sennik There already is one: https://github.com/briannesbitt/Carbon/blob/master/src/Carbon/Lang/da.php

Or am I misunderstanding something?

**Comment by lucasmichot** [comment]
Can this be close @Sennik ?

**Comment by shooka** [comment]
@lucasmichot That is indeed Danish. I think it's ok to close this issue 👍
