### ISSUE TITLE
Format datetime from '0000-00-00 00:00:00' problem

### ISSUE THREAD

**Issue by wzhwkent** [briannesbitt/Carbon#610]
**Use carbon like this:**
\Carbon\Carbon::createFromFormat('Y-m-d H:i:s', '0000-00-00 00:00:00', 'UTC')

**The result:**
Carbon {
  "date": "-0001-11-30 00:00:00"
  "timezone_type": 3
  "timezone": "UTC"
}

**Comment by lucasmichot** [comment]
This is the same behavior as for `Datetime` (see http://php.net/manual/fr/datetime.construct.php#95611)
```sh
>>> Datetime::createFromFormat('Y-m-d H:i:s', '0000-00-00 00:00:00');
=> DateTime {#176
     +"date": "-0001-11-30 00:00:00.000000",
     +"timezone_type": 3,
     +"timezone": "UTC",
   }
>>>
```
At minima the day and month should be set:
```sh
>>> \Carbon\Carbon::createFromFormat('Y-m-d H:i:s', '0000-01-01 00:00:00', 'UTC')
=> Carbon\Carbon {#175
     +"date": "0000-01-01 00:00:00.000000",
     +"timezone_type": 3,
     +"timezone": "UTC",
   }
>>>
```

**Comment by wzhwkent** [comment]
@lucasmichot Thank you for your prompt reply

**Comment by lucasmichot** [comment]
Can this issue be closed not @wzhwkent ?

**Comment by dereuromark** [comment]
This is often the result of not using "default null" for your DB columns. You should do that and not use "default not null", as `0000-00-00 00:00:00` is not a valid string. If you have `NULL` as result, you can skip trying to format.

**Comment by datashaman** [comment]
You can also check for `$carbon->year === -1`.
