### ISSUE TITLE
InvalidArgumentException for PHPUnit

### ISSUE THREAD

**Issue by msdm** [briannesbitt/Carbon#619]
Carbon generates InvalidArgumentException when an instance of it is a cloned dependency of a PHPUnit test (using `@depends clone` annotation). The reason is that PHPUnit uses ReflectionObject to deep copy the objects (in the `copyObject()` method of `DeepCopy` class) but deep copying a Carbon instance fails for `date` and `timezone_type` properties.

**Comment by villfa** [comment]
I made some tests and I managed to reproduce this problem by using DeepCopy 1.5.1.
It is solved from the 1.5.2 version.
