### ISSUE TITLE
Carbon::addMonths() vs Carbon::addMonthsNoOverflow() and mutability 

### ISSUE THREAD

**Issue by travisamiller** [briannesbitt/Carbon#621]
I was bit by (a bug in?) `addMonthsNoOverflow()` today as it returns a `copy()` while other mutators  seem to return `$this`. This issue was mentioned  [here](https://github.com/briannesbitt/Carbon/pull/239#issuecomment-132394813) in PR #239 but there doesn't seem to have been further comment.

Does `addMonthsNoOverflow()` differ on purpose? Would a PR bringing it in line with the other mutators be considered?

Example:

```php
$start = new Carbon('2016-01-01 00:00:00');
$start->addMonths(1);
var_dump($start->toDateTimeString() === '2016-02-01 00:00:00'); // true

$start = new Carbon('2016-01-01 00:00:00');
$start->addMonthsNoOverflow(1);
var_dump($start->toDateTimeString() === '2016-02-01 00:00:00'); // false (?!)
```

**Comment by lucasmichot** [comment]
@travisamiller , see #622

**Comment by travisamiller** [comment]
:+1:

**Comment by judgej** [comment]
For now, I'm using `copy()` explicitly with this method, just to make sure the behaviour does not change and catch me out later.

    $myNewDate = $date->copy()->addMonthsNoOverflow($number);
