### ISSUE TITLE
Time zone issue 

### ISSUE THREAD

**Issue by lukepolo** [briannesbitt/Carbon#635]
Also my server time is :  date Thu Mar 17 17:52:25 UTC 2016
-----

Converting EDT to UTC should be 17:30:00 not 18:30:00 

Am I doing something wrong? 

$easternTime = Carbon::parse(\Request::get('send_time'), 'EDT')

Carbon {#374 ▼
  +"date": "2016-03-17 13:30:00.000000"
  +"timezone_type": 2
  +"timezone": "EDT"
}

$easternTime->timezone('UTC')

Carbon {#374 ▼
  +"date": "2016-03-17 18:30:00.000000"
  +"timezone_type": 3
  +"timezone": "UTC"
}

**Comment by lucasmichot** [comment]
@lukepolo see the timezone type. 
As a reminder
1. offset (+02:00)
2. location (Europe/Berlin)
3. Special (UTC)

The first instance has 2 as type: this means that EDT has been considered as a "location". If it was considered as a special TZ identifier, it would be with type 3 (see your 2nd instance).

EDT as a special TZ identifier does not exist.
See http://php.net/manual/en/timezones.others.php for the list of all supported special IDs.

**Comment by lucasmichot** [comment]
Pretty sure the timezone you need is `EST5EDT`.

```php
<?php

require __DIR__.'/vendor/autoload.php';

use Carbon\Carbon;

Carbon::setTestNow(Carbon::create(2016, 3, 17, 13, 30, 1, 'EST5EDT'));

$edt = Carbon::now();
$utc = $edt->copy()->setTimezone('UTC');

print_r(array(
    'now' => $edt,
    'utc' => $utc,
));

// Array
// (
//     [now] => Carbon\Carbon Object
//         (
//             [date] => 2016-03-17 09:30:01.000000
//             [timezone_type] => 3
//             [timezone] => EST5EDT
//         )
//     [utc] => Carbon\Carbon Object
//         (
//             [date] => 2016-03-17 13:30:01.000000
//             [timezone_type] => 3
//             [timezone] => UTC
//         )
// )
```

**Comment by lukepolo** [comment]
Thank you

**Comment by lucasmichot** [comment]
ur welcome
