### ISSUE TITLE
Bug in subMonth

### ISSUE THREAD

**Issue by cmachu** [briannesbitt/Carbon#639]
Code:

> $date = [
>    'now' => Carbon::parse('2016-03-30'),
>    'prev_month' => Carbon::parse('2016-03-30')->subMonth()
> ];

return:

    [now] => Carbon\Carbon Object
        (
            [date] => 2016-03-30 00:00:00.000000
            [timezone_type] => 3
            [timezone] => Europe/Warsaw
        )

    [prev_month] => Carbon\Carbon Object
        (
            [date] => 2016-03-01 00:00:00.000000
            [timezone_type] => 3
            [timezone] => Europe/Warsaw
        )

for other months work correctly.

**Comment by EselDompteur** [comment]
same issue here

Carbon::now('Europe/Berlin')-toDateTimeString() => 2016-03-30 20:11:31
Carbon::now('Europe/Berlin')->subMonth()->toDateTimeString() => 2016-03-01 20:11:31

regards

**Comment by lybc** [comment]
I met the same question

today is 2016/3/31
```php
$startTime = new Carbon('this month first day') // echo 2016-04-01
```

```php
$last3Month = Carbon::now()->subMonth(3); // echo 2015-12-31 16:04:14
$last2Month = Carbon::now()->subMonth(2); // echo 2016-01-31 16:03:29
$lastMonth = Carbon::now()->addMonth(1); // echo 2016-05-01 16:03:29
```

**Comment by dbonner1987** [comment]
Experiencing the same issue here. It happens with `addMonth` as well.

It appears the bug lies with DateTime and not Carbon. The `Carbon::addMonth`and `Carbon::subMonth` method directly use `DateTime::modify`.

**Comment by dannyweeks** [comment]
I think the problem is deeper than this as I am having issues with even creating the correct object. 

```php
Carbon::createFromFormat('Y-m', '2016-02');
// or
Carbon::create(2016, 2, null, null, null, null, 'Europe/London');
``` 
The above returns an object of 2016-03-02;

Adding the first day of the month fixes the issue.

```php
Carbon::create(2016, 2, 1, null, null, null, 'Europe/London');
```

**Comment by lucasmichot** [comment]
Everyone,
this is related to the fact that there was a change of time (winter time to summer time) on this period. This is the way `\DateTime` works too.
It's a bit tricky sometimes so I always take the `dst` flag into consideration and use the `...Month(s)Overflow` functions as a workaround.

**Comment by lucasmichot** [comment]
Can it be closed @cmachu ?

**Comment by cmachu** [comment]
Yeap, thanks !

**Comment by gerfin** [comment]
what i fixed it by add "->subDay(3)",becaue february is 2-3 days less than other months.
for example:
  what i want:
     Carbon::now()->subMonth()->endOfMonth()
  fixed it by:
    Carbon::now()->subMonth()->subDay(3)->endOfMonth()

**Comment by kylekatarnls** [comment]
Don't do that, if you're january the 1st, then you will get the end of november.

Simply do: `Carbon::now()->startOfMonth()->subMonth()->endOfMonth()`
