### ISSUE TITLE
parse() provides unexpected/inconsistent results

### ISSUE THREAD

**Issue by bhosie** [briannesbitt/Carbon#641]
When using Carbon::parse() with the following strings, some results are correct, and others are incorrect. The call to `->hour` seems to always be right, but the call to `->dayOfWeek` is wrong in some instances. It seems like it's related to using the word `next` in the string. I understand from the docs that using `next` might reset the time to `00:00:00`, but the time seems fine and and the day is pushed out. 

I was expecting that in each of these instances, `->dayOfWeek` would return `0`.
If you need more information, please let me know.

```php
$sun = Carbon::parse('First Sunday next month 10am');
echo $sun->dayOfWeek . "," . $sun->hour;
//outputs 2,10

$sun = Carbon::parse('First Sunday next month 6pm');
echo $sun->dayOfWeek . "," . $sun->hour;
//outputs 2,18

$sun = Carbon::parse('First Sunday next year 10am');
echo $sun->dayOfWeek . "," . $sun->hour;
//outputs 1,10

$sun = Carbon::parse('Third Sunday this month 6pm');
echo $sun->dayOfWeek . "," . $sun->hour;
//outputs 0,18
```

for reference, my timezone is `America/Denver`:
```php
$now = Carbon::now();
echo $now->toDateTimeString();
//outputs: 2016-03-31 09:51:21
```

**Comment by lucasmichot** [comment]
@bhosie , it depends what you mean by correct or incorrect.
All parsed string produce the same result as if they were constructed with `\DateTime::__construct`:

```php
<?php

require __DIR__.'/vendor/autoload.php';

use Carbon\Carbon;

$strings = array(
    'First Sunday next month 10am',
    'First Sunday next month 6pm',
    'First Sunday next year 10am',
    'Third Sunday this month 6pm',
);

$assertions = array();

foreach ($strings as $string) {
    $assertions[] = (new DateTime($string))->getTimestamp() === Carbon::parse($string)->getTimestamp();
}

print_r($assertions);
Array
// (
//     [0] => 1
//     [1] => 1
//     [2] => 1
//     [3] => 1
// )
```

**Comment by lucasmichot** [comment]
Can it be closed @bhosie ?

**Comment by bhosie** [comment]
@lucasmichot yes, thanks. I should have checked more thoroughly before submitting. thanks.
