### ISSUE TITLE
Carbon Instance from Mime Date

### ISSUE THREAD

**Issue by mstaack** [briannesbitt/Carbon#649]
Hey there,

thanks for rhe nice library. I have an Issue getting Mime Dates into a Carbon Instance.

For example:
```
Sun, 18 Apr 2016 15:38:21 0000
or
Mon, 18 Apr 2016 11:04:22 +0200 (CEST) 
or
Mon, 18 Apr 2016 06:37:04 GMT 
or
Mon, 18 Apr 2016 10:23:16 +0200
```

Using
```
Carbon::createFromFormat('U', strtotime($dateString)
```
only works sometimes...  i get:

```
  [InvalidArgumentException]  
  Unexpected data found.
```

How to convert these string correctly?

Thanks Max

**Comment by lucasmichot** [comment]
You should use `\Carbon\Carbon::parse` instead ;-)

**Comment by mstaack** [comment]
as simple as that! man! was a monday ;)

thanks
