### ISSUE TITLE
[Question] diffInDays same result for different days

### ISSUE THREAD

**Issue by mahony0** [briannesbitt/Carbon#651]
Here is a sample:

```php
// 2016-04-18 22:33:29.000000
$today = \Carbon\Carbon::now();

// Actual time: 2016-04-12 22:22:07.000000
// Calculated: 2016-04-19 22:22:07.000000
$userRegistered = Auth::getUser()->activated_at->addWeek();

// Returns "0"
$dayLeft = $today->diffInDays($userRegistered, false);
```

also if "$userRegistered" is "2016-04-18" (one day before), returns 0 too. Maybe i'm wrong or this is possible a bug..

**Comment by lucasmichot** [comment]
This is normal @mahony0 
You would have `$dayLeft == 1`, only if `$userRegistered >= 2016-04-19 22:33:29`.

You may have `1` by doing:
```php
$dayLeft = $today->startOfDay()->diffInDays($calculated->endOfDay(), false);
```

**Comment by mahony0** [comment]
Yes, exactly. Works like a charm, thanks..
