### ISSUE TITLE
Carbon Timezone Handling Method

### ISSUE THREAD

**Issue by rsands2801** [briannesbitt/Carbon#659]
I am not sure that Carbon is handling timezone in a logical method.

When we call the following we get two different methods

The UTC time for example is 2016-05-01 11pm

Carbon::today('Australia/Sydney');
Carbon::today()->timezone('Australia/Sydney');

The first function returns it correctly, the second function doesn't as it just tries to add 10 hours on from UTC but it is basing time for today() as 00:00:00 as it using startofday()

a timezone format should fix the date from the previous function to the timezone required.  It doesn't make sense to set a timezone() and yet it returns incorrect because when it created today() it used startofday()

**Comment by rsands2801** [comment]
As a side note both of these work correctly so it relates to things like today(), etc

Carbon::now('Australia/Sydney');
Carbon::now()->timezone('Australia/Sydney');

**Comment by lucasmichot** [comment]
@rsands2801 , this is normal.
```php
Carbon::today()->timezone('Australia/Sydney'); 
// stands for:
Carbon::today('UTC')->timezone('Australia/Sydney');
```

So there is indeed a transition that you will not find in your first case, as the date is from the very beginning with `Australia/Sydney` timezone.

**Comment by rsands2801** [comment]
@lucasmichot I am not sure that it is correct in its current form.  If i request today()->timezone() a user would expect today in the timezone given by the timezone function.  It is just a matter of removing startofday from the today function so it returns correctly.  Whats your thoughts?

**Comment by rsands2801** [comment]
Also in your example if you do both the today(UTC)....it is not correct.  If it is 7am Sydney time on 2nd May, and I run that function it returns the wrong time.  If i remove startofday it is correct, you cannot get the correct date back if you are making the time 00:00:00 before applying the timezone function

**Comment by lucasmichot** [comment]
This is juste the way `\DateTime` handles that:

```php
<?php

$format = 'Y-m-d H:i:s';
$value = '2016-05-01 12:13:14';
$berlin = DateTime::createFromFormat($format, $value, $eb = new DateTimeZone('Europe/Berlin'));
$sydney = DateTime::createFromFormat($format, $value, $as = new DateTimeZone('Australia/Sydney'));
$offset = DateTime::createFromFormat($format, $value, $eb)->setTimezone($as);

print_r([
  $berlin,
  $sydney,
  $offset,
]);

/*
Array (
  [0] => DateTime Object (
  [date] => 2016-05-01 12:13:14.000000
      [timezone_type] => 3
      [timezone] => Europe/Berlin
    )
  [1] => DateTime Object (
  [date] => 2016-05-01 12:13:14.000000
      [timezone_type] => 3
      [timezone] => Australia/Sydney
    )
  [2] => DateTime Object (
  [date] => 2016-05-01 20:13:14.000000
      [timezone_type] => 3
      [timezone] => Australia/Sydney
    )
)
*/
```

**Comment by rsands2801** [comment]
@lucasmichot That isn't correct in example though, UTC time of 12.12pm would be 2016-05-01 in Sydney time...

This is correct in PHP

````
$format = 'Y-m-d H:i:s';
        $value = '2016-05-01 22:13:14';
        $as = new \DateTimeZone('Australia/Sydney');
        $eb = new \DateTimeZone('UTC');
        $berlin = \DateTime::createFromFormat($format, $value, $eb);
        $sydney = \DateTime::createFromFormat($format, $value, $as);
        $offset = \DateTime::createFromFormat($format, $value, $eb)->setTimezone($as);
````

**Comment by lucasmichot** [comment]
Anyway, this is not a Carbon issue

**Comment by rsands2801** [comment]
@lucasmichot it is a carbon issue, Carbon is doing startofday which is putting the time as 00.00.00  - If carbon did not do that and created a datetime correctly with the time and then applied the timezone function it would work, the issue is carbon on the helper function of today() etc is zeroing the time before it passes it through the chain.

If it was not a Carbon issue then now() would also not work but the thing is now() works as expected, so why doesnt today() ?

**Comment by rsands2801** [comment]
on line 273 of carbon removing the startofday() function fixes the issue, no where in PHP DateTime does it reset time in this manner when setting the required timezone, in fact it does the opposite, if the user didnt pass a time it actually sets the time so it can correctly handle the setTimezone

**Comment by lucasmichot** [comment]
@rsands2801 I think there is a misunderstanding about wh

**Comment by lucasmichot** [comment]
Can your reformulate more precisely?

**Comment by lucasmichot** [comment]
or even better, open a PR with a failing test

**Comment by rsands2801** [comment]
@lucasmichot When you pass time as midnight (i.e. 00:00:00) into the php date Time function it is impossible for it to work out the timezone as it needs the time.  Carbon now() works fine as it doesnt zero the time.

today() and all other sub functions that use today() fail because the time is set to midnight, datetime thinks it is midnight UTC every time, when it is not.

I will try open PR with test but by doing startofday your making it pass in midnight so timezone function fails

**Comment by liangliang** [comment]
Hi Lucas, 

If you change your example code to 

<?php
$format = 'Y-m-d';
$value = '2016-05-01';
$berlin = DateTime::createFromFormat($format, $value, $eb = new DateTimeZone('Europe/Berlin'));
$sydney = DateTime::createFromFormat($format, $value, $as = new DateTimeZone('Australia/Sydney'));
$offset = DateTime::createFromFormat($format, $value, $eb)->setTimezone($as);

print_r([
  $berlin,
  $sydney,
  $offset,
]);

?>

You will get:

Array
(
    [0] => DateTime Object
        (
            [date] => 2016-05-01 02:09:47
            [timezone_type] => 3
            [timezone] => Europe/Berlin
        )

    [1] => DateTime Object
        (
            [date] => 2016-05-01 10:09:47
            [timezone_type] => 3
            [timezone] => Australia/Sydney
        )

    [2] => DateTime Object
        (
            [date] => 2016-05-01 10:09:47
            [timezone_type] => 3
            [timezone] => Australia/Sydney
        )

)

You see the PHP DateTime passes the current time rather than the time "00:00:00" while Carbon::today() will return a date with "00:00:00" time.

**Comment by rsands2801** [comment]
Tests are hard to prove in this case as it depends on the time you decided to run the tests at.  Run them just before midnight UTC time and it will be the wrong value for Sydney, run them after midnight UTC and it will be same day as Sydney.

**Comment by lucasmichot** [comment]
@rsands2801
I could finally understand what your problem is
I will work on it

**Comment by kylekatarnls** [comment]
It works as expected, the both code you gave are **NOT** equivalent:
```php
Carbon::today('Australia/Sydney'); // is Today at midnight in Sydney
Carbon::today()->timezone('Australia/Sydney'); // is Today at midnight UTC matching date in Sidney
```
