### ISSUE TITLE
Calculations between timezone differences - Historical

### ISSUE THREAD

**Issue by lferro9000** [briannesbitt/Carbon#670]
Hi Brian,

Great library, just a question if you know of:

Is anyone working on a timezone difference?

http://www.timeanddate.com/news/time/

For instance, when making time calculations between Europe/Londaon and America/Caracas

http://www.timeanddate.com/news/time/venezuela-change-timezone.html

If we calculate a diff between before and after the timezone effects, will those timezone / DLS differences be accounted for?

Cheers,

**Comment by kylekatarnls** [comment]
Differences given are between "real" moments (no matter where it happen on the planet), not between clock needle positions.

See the example with Toronto and Vancouver: http://carbon.nesbot.com/docs/#api-introduction

It means difference between Vancouver 4pm and Toronto 7pm the same day is 0 seconds.
