### ISSUE TITLE
Incorrectly calculating previous month on May 31st

### ISSUE THREAD

**Issue by joshwhatk** [briannesbitt/Carbon#672]
In my application, I'm simply parsing `last month` to get the previous month. However, today on the 31st of May it doesn't seem to work correctly. Also parsing `April` doesn't work as expected either.

![Example](https://d.pr/17SOG+)

**Comment by briannesbitt** [comment]
That is how the underlying PHP datetime works.

'last month' is using 2016-04-31 which doesn't exist so it rolls over to May 1.  Same with 'April'.

You can try something like `Carbon::now()->subMonthNoOverflow()`

**Comment by joshwhatk** [comment]
Thanks, that works well enough, I was concerned it might be an underlaying problem with PHP.

**Comment by voveson** [comment]
@briannesbitt Thanks for that -- I ran into the exact same issue yesterday.
