### ISSUE TITLE
CarbonInterval documentation—copy paste bug

### ISSUE THREAD

**Issue by mblarsen** [briannesbitt/Carbon#679]
It seems you have a copy'n'paste bug in your documentation for `CarbonInternval` http://carbon.nesbot.com/docs/#api-interval
Looks like it was copied from the section describing that Carbon extends DateTime. The code block is fine. Just the text above it.

<img width="480" alt="screenshot 2016-06-22 11 28 30" src="https://cloud.githubusercontent.com/assets/247048/16253869/e0e4b2b4-386c-11e6-8874-a94162257d8b.png">

**Comment by briannesbitt** [comment]
Thanks.
