### ISSUE TITLE
Set Time/Day exibition code

### ISSUE THREAD

**Issue by lucianozanita** [briannesbitt/Carbon#682]
Hello, I'm using the script in a whmcs, which is this:

`<?php
use Carbon\Carbon;
use WHMCS\View\Menu\Item as MenuItem;
if (App::getCurrentFilename() == 'submitticket') {
    add_hook('ClientAreaPrimarySidebar', 1, function (MenuItem $primarySidebar) 
    {
        $supportHours = $primarySidebar->addChild('Horário de Atendimento');
        $supportHours->moveToFront();
        $supportHours->addChild(
            '<strong>Disponível</strong> 08:00h-17:00h',
            array(
                'icon'  => 'fa-smile-o',
                'order' => 1,
            )
        );
        $supportHours->addChild(
            '<strong>Indisponível</strong> Finais de Semana',
            array(
                'icon'  => 'fa-frown-o',
                'order' => 2,
            )
        );
         $client = Menu::context('client');
        $greeting = is_null($client)
            ? ''
            : ", <strong>{$client->firstName}</strong>";

```
    $now = Carbon::now();
    $supportIsOpen = $now->isWeekday()
        && $now->hour >= 8
        && $now->hour <= 17; 

    $supportHours->setBodyHtml(
        $supportIsOpen
            ? "Olá{$greeting}! Estamos diponíveis para responder seu ticket!"
            : "Não se preocupe{$greeting}! Vamos responder seu ticket no próximo dia útil!"
    );
});
```

}?>`

I would like to add a rule to the line "$ now-> isWeekday ()"
in order to set the days and hours set to be shown the message that appears at the end, how can I do this procedure? Would you help me?

**Comment by briannesbitt** [comment]
Maybe subclass Carbon and add an isSupportOpen() method and encapsulate that logic there?

**Comment by lucianozanita** [comment]
So I'm using this whmcs code to implement the hook, most like to put a specific day at a specific time in which it will show that this Unavailable.
http://docs.whmcs.com/Editing_Client_Area_Menus (End of page)

**Comment by briannesbitt** [comment]
Not sure what you need?  If you what to use the current structure then subclass Carbon and check it.  If you want to show the open hours in the string then just use string concatenation or sprintf() where needed ?!?

**Comment by lucianozanita** [comment]
So what I would like is that on Friday from 17:00 until 20:00 hours Saturday display only the message:

"Hi{$greeting}! We're open and will respond to your ticket soon!"

how can I do this?

**Comment by briannesbitt** [comment]
```
function isSupportOpen()
{
    $now = Carbon::now();

    return ($now->isFriday() && 8 <= $now->hour) || ($now->isSaturday() && $now->hour <= 17);
}

Carbon::setTestNow(Carbon::create(2018, 2, 16, 7, 0, 0));
var_dump(isSupportOpen());  // false
Carbon::setTestNow(Carbon::create(2018, 2, 16, 9, 0, 0));
var_dump(isSupportOpen());  // true
Carbon::setTestNow(Carbon::create(2018, 2, 17, 15, 0, 0));
var_dump(isSupportOpen());  // true
Carbon::setTestNow(Carbon::create(2018, 2, 17, 18, 0, 0));
var_dump(isSupportOpen());  // false
Carbon::setTestNow(Carbon::create(2018, 2, 18, 7, 0, 0));
var_dump(isSupportOpen());  // false
```
