### ISSUE TITLE
Failed to parse time string (double timezone specification)

### ISSUE THREAD

**Issue by arjenduinhouwer** [briannesbitt/Carbon#685]
In our RESTful api we use Carbon (which is great b.t.w.) to parse dates. In some cases we get this error:

`exception 'Exception' with message 'DateTime::__construct(): Failed to parse time string (Mon Jun 27 2016 00:00:00 GMT+0200 (Mitteleuropäische Sommerzeit)) at position 41 (e): Double timezone specification' in...`

This is from one of our German clients and we've solved it by converting the date object in frontend code to a valid string, but it seems unnecessary to me. 
Since i couldn't find anything online i hoped you could help me out.

**Comment by lucasmichot** [comment]
...
```sh
lucas@air:~/Gits/briannesbitt/carbon | master :                                                                                                                                                                                                                                   [ea4b1c5]  11:40
> psysh
Psy Shell v0.7.2 (PHP 7.0.8 — cli) by Justin Hileman
>>> $date = new \Datetime('Mon Jun 27 2016 00:00:00 GMT+0200 (Mitteleuropäische Sommerzeit)');
Exception with message 'DateTime::__construct(): Failed to parse time string (Mon Jun 27 2016 00:00:00 GMT+0200 (Mitteleuropäische Sommerzeit)) at position 41 (e): Double timezone specification'
>>> $date = new \Datetime('Mon Jun 27 2016 00:00:00 GMT+0200');
=> DateTime {#179
     +"date": "2016-06-27 00:00:00.000000",
     +"timezone_type": 1,
     +"timezone": "+02:00",
   }
>>>
```

Then just parse `Mon Jun 27 2016 00:00:00 GMT+0200` without `(Mitteleuropäische Sommerzeit)`

**Comment by arjenduinhouwer** [comment]
Sure that's an option. Reason why I posted the issue is that one might ( I did) expect Carbon to handle these dateobjects since that is the reason to use Carbon in the first place, not to have to check each datestring and then handing it over to Carbon. The particular issue is solved for our app, but I thought it would be nice to share the issue as a point of improvement.

**Comment by lucasmichot** [comment]
Can this be closed @arjenduinhouwer ?

**Comment by agmckee** [comment]
Just ran into this issue myself with a date coming in from an Angular app. Would be good if Carbon could handle this gracefully.

**Comment by lucasmichot** [comment]
Feel free to use any TZ listed on PHP.net website

**Comment by lesliek07** [comment]
@arjenduinhouwer hi I am newie on this and I have the same issue as you I don't know how to fix it. it only happens on windows, what you migth suggest for me how I might handle this issue?

**Comment by saulojg** [comment]
Have you guys commited any changes related to this issue?

**Comment by saulojg** [comment]
@lesliek07 same here, the issue happens only on windows machines

**Comment by aurukas** [comment]
same here

**Comment by nezaboravi** [comment]
DateTime::__construct(): Failed to parse time string (Fri Sep 20 2019 00:00:00 GMT+0700 (Indochina Time)) at position 41 (i): Double timezone specification

**Comment by Shobson-three29** [comment]
im experiencing this as well. am i wrong for assuming that carbon should be able to handle a "new Date()" passed in from javascript?

**Comment by kylekatarnls** [comment]
`new Date()` is an object from JS land, there is absolutely no way to pass it as an instance to any kind of PHP script. It's not a Carbon issue. It's about communication between PHP and JS. To exchange data across different languages, you need to convert it in a flat (scalar) representation (or V8Js extension but the principle is the same under the hood). The standard is to use JSON. So:

JS Date to JSON
```js
(new Date()).toJSON()
```
Carbon (and even pure DateTime) in PHP will perfectly understand this representation.

PHP Carbon instance to JSON
```js
(new Carbon())->toJSON()
```
It gives the exact same format and JS will perfectly understand this representation.

What you see when you cast a `new Date()` as a string from the JS side is NOT and normalized string aimed to be passed to an other system/language. It's a human-friendly output aimed to be displayed on screen to your users.
