### ISSUE TITLE
subWeekdays resets time to 00:00:00

### ISSUE THREAD

**Issue by Vherus** [briannesbitt/Carbon#692]
When comparing removing weekends from a carbon datetime and comparing it with another datetime, I encountered the issue that the time was being reset to 00:00:00 - this caused my comparison to be inaccurate.

Example:

``` php
$dt = new Carbon('2016-06-28 12:32:10');
echo $dt->subWeekdays(1); // outputs 2016-06-27 00:00:00
```

**Comment by dhirtzbruch** [comment]
It`s the same issue when using \DateTime:

```php
$dt = \DateTime::createFromFormat('Y-m-d H:i:s', '2016-07-07 06:13:51');
echo $dt->format('H:i:s'); // outputs 06:13:51

$dt->modify('-1 weekday');
echo $dt->format('H:i:s'); // outputs 00:00:00
```

**Comment by lucasmichot** [comment]
I believe that this is not a bug as long as we stick to the original DateTime behaviour
