### ISSUE TITLE
Potential issue with ISO 8601 timestamp format

### ISSUE THREAD

**Issue by bkuhl** [briannesbitt/Carbon#709]
I'm [experiencing an issue](http://stackoverflow.com/questions/38292501/unable-to-programmatically-create-tags-in-github-iso8601-timestamp-is-invalid) creating a github tag via the github api where the output generated by `Carbon::now()->toIso8601String()` is being rejected as an invalid timestamp.  

When reporting the link to StackOverflow to they showed some things on the page to direct me here.  This makes me question whether there are known issues using Carbon's ISO 8601 formatting.  It appears to be generating a correct timestamp, but with GitHub showing what it's showing I thought I'd post here and check.

<img width="1018" alt="screen shot 2016-07-10 at 6 45 46 am" src="https://cloud.githubusercontent.com/assets/524933/16713911/ffa3a5a6-4669-11e6-9970-cd256721b304.png">
<img width="472" alt="screen shot 2016-07-10 at 6 45 51 am" src="https://cloud.githubusercontent.com/assets/524933/16713912/00f8c2a6-466a-11e6-8e00-e53fbf1da828.png">

**Comment by lucasmichot** [comment]
Carbon is just a wrapper to Datetime. Depending on you version of PHP the output mith be different.

Please use the one which is appropriate for you:
```php
// PHP 7.0.9
class DateTime implements DateTimeInterface {
    const ATOM = 'Y-m-d\TH:i:sP';
    const COOKIE = 'l, d-M-y H:i:s T';
    const ISO8601 = 'Y-m-d\TH:i:sO';
    const RFC822 = 'D, d M y H:i:s O';
    const RFC850 = 'l, d-M-y H:i:s T';
    const RFC1036 = 'D, d M y H:i:s O';
    const RFC1123 = 'D, d M Y H:i:s O';
    const RFC2822 = 'D, d M Y H:i:s O';
    const RFC3339 = 'Y-m-d\TH:i:sP';
    const RSS = 'D, d M Y H:i:s O';
    const W3C = 'Y-m-d\TH:i:sP';
    ...
```

**Comment by bkuhl** [comment]
It's an underlying issue with PHP - see http://stackoverflow.com/a/38296139/197606

**Comment by briannesbitt** [comment]
But is fixed in master...  https://github.com/briannesbitt/Carbon/commit/643decdc19dda5218e320ae9431dbc47aad097b9
