### ISSUE TITLE
the return messup after august 2016

### ISSUE THREAD

**Issue by aashishx** [briannesbitt/Carbon#715]
I'm expecting "2016-08-01 21:00" from below code; But i'm getting "2015-12-01 21:00:00". Where did it go wrong?
```
<?php 
echo date('Y-m-d H:i:s', \Carbon\Carbon::create(2016, 08, 01, 21, 0, 0, "America/Los_Angeles")->timestamp); 
?>
```

**Comment by PrismPrince** [comment]
`<?php 
echo date('Y-m-d H:i**:s**', \Carbon\Carbon::create(2016, 08, 01, 21, 0, 0, "America/Los_Angeles")->timestamp); 
?>`
remove the `:s`

**Comment by aashishx** [comment]
year and month are the bigger problem here

**Comment by lucasmichot** [comment]
```php
<?php

require __DIR__.'/vendor/autoload.php';
use Carbon\Carbon;

echo Carbon::create(2016, 8, 01, 21, 0, 0, "America/Los_Angeles")->format('Y-m-d H:i');
// 2016-08-01 21:00
```

It's not a Carbon problem @aashishx , can this be closed?

**Comment by lucasmichot** [comment]
Ping @aashishx ?

**Comment by aashishx** [comment]
sorry for late response. Yes, this can close. Its not the Carbon issue.

**Comment by lucasmichot** [comment]
Then feel free to close this issue @aashishx ;-)
