### ISSUE TITLE
Carbon making wrong date from unix time stamp.

### ISSUE THREAD

**Issue by maantje** [briannesbitt/Carbon#732]
I am working with unix timestamps and the time is always 2 hours short. As a test a made this small snippet

`var_dump(Carbon::createFromFormat("U", Carbon::now()->format("U"))->format("Y-m-d H:i:s") == Carbon::now()->format("Y-m-d H:i:s"));`

I would asume these days would be equal to each other but they are not. What is going on here?

**Comment by lucasmichot** [comment]
Timestamp is always UTC, but your Carbon instance is not necessary using this timezone.

Have a try with:
```php
var_dump(Carbon::createFromFormat("U", Carbon::now('UTC')->format("U"))->format("Y-m-d H:i:s") == Carbon::now('UTC')->format("Y-m-d H:i:s"));

```

**Comment by maantje** [comment]
@lucasmichot That does indeed work. Is there a way to set the time zone with createFromFormat when using a unix time stamp?

**Comment by lucasmichot** [comment]
Have you played around with `\Carbon\Carbon::createFromTimestamp` ?
You can also pass at timezone as an argument @maantje
