### ISSUE TITLE
Lang\ca.php

### ISSUE THREAD

**Issue by LimitTech** [briannesbitt/Carbon#737]
Hello,

line 21:    'day'       => '1 dia|:count díes', 
should be
line 21:    'day'       => '1 dia|:count dies',

Thank you.

**Comment by lucasmichot** [comment]
Can you review #739 @LimitTech ?

**Comment by LimitTech** [comment]
It's OK

**Comment by LimitTech** [comment]
Hello, I think _d'aquí x dies_ would be better than _dins de x dies_.

_dins de x dies_ isn't incorrect but it seems a literal translation from Spanish and people usually uses _d'aquí x dies_. 

In addition, using this it also fixes days starting with vowel like _dins de 1 dia_, which is incorrect.

**Comment by lucasmichot** [comment]
Feel free to provide a PR if necessary @LimitTech
