### ISSUE TITLE
/vendor/nesbot/carbon/src/Carbon/Carbon.php on line 172

### ISSUE THREAD

**Issue by konskript** [briannesbitt/Carbon#742]
I don`t know why, there is no problem in my create method. 
But in my update method appear an error like this.. please refer to first image. And the second image is my small code of item update.

![time1](https://cloud.githubusercontent.com/assets/20536714/17326530/86607646-58e4-11e6-8787-38fa9cbb6c6f.PNG)

![time2](https://cloud.githubusercontent.com/assets/20536714/17326531/868f6096-58e4-11e6-9320-37cbc4a6c24a.PNG)

**Comment by lucasmichot** [comment]
This is not a Carbon issue, please set your default timezone: http://php.net/manual/en/function.date-default-timezone-set.php

**Comment by lucasmichot** [comment]
Can this be closed @konskript ?
