### ISSUE TITLE
from Carbon instance to back to  \DateTime instance

### ISSUE THREAD

**Issue by morloderex** [briannesbitt/Carbon#744]
So i found [this issue](https://github.com/briannesbitt/Carbon/issues/231) and it is documented that we can go from an instance of \DateTime to Carbon instance. 

but is it possible to go from instance of Carbon back to an instace of \DateTime?

if so how could i to this?

**Comment by briannesbitt** [comment]
A Carbon instance is an instance of DateTime.

**Comment by morloderex** [comment]
@briannesbitt I know it inheirts from datetime class correct yes. 
my problem is that while using [this package](https://github.com/yohang/CalendR) the methods in here is typehinded for DateTime and whenever i try to pass in my carbon object it throws an exception saying the object identity isn't correct.

**Comment by briannesbitt** [comment]
Here is an example of a type hinted function and the same instanceof that library is using.  Both seem fine to me.

```php
function isDateTime(DateTime $yearOrStart)
{
  return $yearOrStart instanceof DateTime;
}

$now = Carbon::now();

var_dump(isDateTime(Carbon::now()));
var_dump(Carbon::now() instanceof DateTime);
```

This prints: 
```
bool(true)
bool(true)
```

How are you using it?

**Comment by morloderex** [comment]
@briannesbitt I'll take a look at it once more and will come back to you :) 
Thank you for the help so far :)

**Comment by lucasmichot** [comment]
@morloderex can this be closed ?

**Comment by morloderex** [comment]
Yes it can..

**Comment by prashant-pokhriyal** [comment]
@briannesbitt I'm facing the same issue while passing **carbon object** to `new \MongoDB\BSON\UTCDateTime($post->created_at);`

Ideally it should store the date in **BSON date object** (mongodb date object), but date is getting stored as string.

If I change it to `new \MongoDB\BSON\UTCDateTime(new \DateTime($post->created_at));` , then it's working properly and storing the date in **BSON date object**
