### ISSUE TITLE
Incorrect date when formatting to weeks

### ISSUE THREAD

**Issue by kife-design** [briannesbitt/Carbon#754]
Hello,

I think i found a bug when formatting dates.

`$date = Carbon\Carbon::createFromDate(2013, 12, 30);
var_dump($date->format('W-Y'));`

So i created a Carbon object from the date 2013-12-30, but when i format it to show the week and year, it shows "01-2013".

Can someone confirm this is a bug?

**Comment by lucasmichot** [comment]
This is not a bug; this is the way Datetime works:

```php
print_r((new DateTime('2013-12-30'))->format('W-Y'));
// 01-2013
```

**Comment by briannesbitt** [comment]
If you mean because its showing week 1 and year 2013... that is actually correct.  The week is the ISO-8601 week which is actually 1 with that date.  If you want the matching ISO-8601 week-numbering year, and not the current calendar year, then use an 'o' in the format.

```php
print_r((new DateTime('2013-12-30'))->format('W-Y'));   // 01-2013
print_r((new DateTime('2013-12-30'))->format('W-o'));   // 01-2014
```

**Comment by systemovich** [comment]
How does one get the regular week number?

**Comment by Glavic** [comment]
@systemovich: what is regular week number? Standard ISO8601 explains weeks very well. Do you have any other standard in mind?

**Comment by systemovich** [comment]
@Glavic, sorry, it has been a while. I do not remember anymore.

**Comment by Glavic** [comment]
@systemovich: np mate, we are just cleaning up issues :)
