### ISSUE TITLE
Calculation between two times

### ISSUE THREAD

**Issue by tperrelli** [briannesbitt/Carbon#757]
Hi Brian, i wandered around the carbon framework and i didn't find anything to compair the interval between two times.

I have those functions: diffInHours, diffInMinutes, diffInSeconds, diffInYears. But i still couldn't find some function that return me similar to the example below:

Initial time
17:10:00

Final time
19:02:05

Result
02:12:05

What do you think of the possibility of having an implementation to bring this solution?

**Comment by briannesbitt** [comment]
So are you looking for a buggy implementation? ;-)   19:02:05 - 17:10:00 = 01:52:05

Already done... see http://carbon.nesbot.com/docs/#api-interval

```php
$start = Carbon::createFromTime(17, 10, 0);
$end = Carbon::createFromTime(19, 2, 5);

echo $end->diff($start)->format("%H:%I:%S");   // 01:52:05
```

**Comment by tperrelli** [comment]
Lol! And i din't know about this method "diff". Thanks.
