### ISSUE TITLE
Comparing two months

### ISSUE THREAD

**Issue by SergioAraya** [briannesbitt/Carbon#759]
I think there is a bug in the code when the actual month has 31 days, it goes 30 days back and it`s stil the same month.

If I`ve a mistake in my code please tell me

-----Code:------

<?php
use Illuminate\Foundation\Auth\User as Authenticatable;
use Carbon\Carbon;

class User extends Authenticatable
{

public function lastmonthSales(){

    $date = Carbon::now()->subMonth();
    $lastMonth = $date->month;

    $lastMonthInvoices = $this->hasMany('App\Invoice')->whereMonth('date','=',$lastMonth )->get();
    $lastMonthInvoices =0;
        for ($i=0; $i < count($lastMonthInvoices ) ; $i++) {
            $lastMonthInvoices += $lastMonthInvoices [$i]->total_invoice;
        }

        return number_format($lastMonthInvoices,2);

}
}

?>

**Comment by lucasmichot** [comment]
This is a Laravel related, not Carbon.
This is also the behaviour of `\Datetime`

You should use `add/subMonthsNoOverflow`

**Comment by SergioAraya** [comment]
Thanks

**Comment by lucasmichot** [comment]
Can this issue be closed @SergioAraya ?
