### ISSUE TITLE
Incorrect sub months

### ISSUE THREAD

**Issue by Smile42RU** [briannesbitt/Carbon#761]
What i did wrong? 31.08.2016

$currentMonth     = Carbon::now()->startOfMonth();
$prevMonth          = Carbon::now()->subMonth(1)->startOfMonth();
$prevPrevMonth   = Carbon::now()->subMonth(2)->startOfMonth();

var_dump($currentMonth, $prevMonth, $prevPrevMonth);

object(Carbon\Carbon)#450 (3) { ["date"]=> string(19) "2016-08-01 00:00:00" ["timezone_type"]=> int(3) ["timezone"]=> string(3) "UTC" } 

object(Carbon\Carbon)#449 (3) { ["date"]=> string(19) "2016-07-01 00:00:00" ["timezone_type"]=> int(3) ["timezone"]=> string(3) "UTC" } 

object(Carbon\Carbon)#453 (3) { ["date"]=> string(19) "2016-07-01 00:00:00" ["timezone_type"]=> int(3) ["timezone"]=> string(3) "UTC" }

**Comment by lucasmichot** [comment]
See subMonthNoOverflow

**Comment by kdabek** [comment]
Same for addMonth, used addMonthNoOverflow works properly

**Comment by Smile42RU** [comment]
subMonthNoOverflow works fine, thanks.
