### ISSUE TITLE
Wrong locale used on formatLocalized

### ISSUE THREAD

**Issue by boyd91** [briannesbitt/Carbon#763]
When you set the locale by `Carbon::setLocale` the locale won't be used for `->formatLocalized` but it does on `->diffForHumans`. It does work when I set the locale by PHP's `setlocale(LC_TIME, nl_NL.utf8)` though but it's still a bug.

I'm on version 1.21.0

``` php
Carbon::setLocale('nl');

$array                    = [];
$array['locale']          = Carbon::getLocale();
$array['formatLocalized'] = Carbon::now()->formatLocalized('%A %d %B %Y');
$array['diffForHumans']   = Carbon::now()->subDays(24)->diffForHumans();

var_dump($array); exit;
```

Outputs:

``` php
array(3) { 
    ["locale"]=> string(2) "nl"
    ["formatLocalized"]=> string(26) "Saturday 03 September 2016" // Not localized
    ["diffForHumans"]=> string(15) "3 weken geleden" // Localized
}
```

**Comment by tschallacka** [comment]
Use Carbon::setUtf8(true); at the beginning of your script. this only needs to be called once.
