### ISSUE TITLE
how to get the date from day of week using carbon

### ISSUE THREAD

**Issue by munachiani** [briannesbitt/Carbon#765]
i was able to get the way of the week from a calendarusing carbon, i now want to get the corresponding date
for example i have the date of week as 5, will that 5 correspond to 23 or 1 or 5 on the calendar

**Comment by lucasmichot** [comment]
Can you reformulate @munachiani ?

**Comment by munachiani** [comment]
No i can't

**Comment by lucasmichot** [comment]
> No i can't

That's quite unfortunate

**Comment by briannesbitt** [comment]
```
$c = new Carbon('2018-02-16');
echo $c->dayOfWeek; // 5, ie. Friday
echo $c->day;       // 16
```
Closing, re-open if there is something else.
