### ISSUE TITLE
Get how old is post information

### ISSUE THREAD

**Issue by landed1** [briannesbitt/Carbon#767]
Hi 
Sorry to ask here but I know not how to otherwise. Can this be used to work out how old a post is so that I can display :
2d or 34 min as an example for blog post with a date in a good php format.
I started to try and do this myself but it's getting very complicated quickly. I see the only way for me to do it is to make minutes since the start of the year from both dates and then simply subtract then take the difference back as a date/time.
Thanks

**Comment by lucasmichot** [comment]
I think `\Carbon\Carbon::diffForHumans` is there exactly for this purpose @landed1 ?

**Comment by lucasmichot** [comment]
Can this be closed @landed1 ?
