### ISSUE TITLE
Day week

### ISSUE THREAD

**Issue by hugofabricio** [briannesbitt/Carbon#768]
How to set day 0-6 match to SUN-SAT.

0 = SundaY
1 = Monday
2..
6 = Sartuday

Thanks

**Comment by lucasmichot** [comment]
Isn't it already the case https://github.com/briannesbitt/Carbon/blob/master/src/Carbon/Carbon.php#L58-L64 @hugofabricio ?

**Comment by lucasmichot** [comment]
Can this be closed @hugofabricio ?

**Comment by hugofabricio** [comment]
No, would otherwise 0 = SUNDAY, 1 = MONDAY... and so on its possible?

**Comment by lucasmichot** [comment]
I suppose `D` and `l` aret the formatters that you need...
http://php.net/manual/function.date.php
```php
echo strtoupper(\Carbon\Carbon::now()->format('l')).PHP_EOL; // THURSDAY
echo strtoupper(\Carbon\Carbon::now()->format('D')).PHP_EOL; // THU
```

**Comment by hugofabricio** [comment]
I want to spend numbers 0-6 and return the day of the week.

**Comment by Glavic** [comment]
@hugofabricio: I know it was a long time since you posted this, but is this still active issue?

**Comment by kylekatarnls** [comment]
Not tested but this should give it to you: `Carbo::createFromFormat('w', $number)->format('l')`

**Comment by kylekatarnls** [comment]
You can do this:
```php
function weekNumberToWeekName($number, $format = 'l')
{
    $number = abs($number) % 7;
    $date = new \Carbon\Carbon('sunday');
    while ($date->format('w') != $number) {
        $date->addDay();
    }
    
    return $date->format($format);
}
```

Or even without Carbon: https://3v4l.org/ibeST
