### ISSUE TITLE
Localize Week Days

### ISSUE THREAD

**Issue by 3nvy** [briannesbitt/Carbon#775]
Is it possible to localize weekdays from Carbon::now()->format('l') ?

**Comment by 3nvy** [comment]
Ok, I found a way to do it by manually create a method for it. Dunno if there's an implemented method yet, if not you guys can close this thread ;)

**Comment by briannesbitt** [comment]
http://carbon.nesbot.com/docs/#api-localization

```php

$n = Carbon::now();

setlocale(LC_TIME, 'German');
echo $n->formatLocalized('%A');  // "Montag"

setlocale(LC_TIME, '');
echo $n->formatLocalized('%A');  // "Monday"
```

**Comment by lucasmichot** [comment]
I believed that this issue can be closed
