### ISSUE TITLE
Incorrect date when formatting d/m/Y or d-m-Y

### ISSUE THREAD

**Issue by biscolab** [briannesbitt/Carbon#778]
`return Carbon::createFromFormat('Y-m-d', '1933-02-15')->format($output_format);`
if
`$output_format = 'd.m.Y';`
return correct value : 15.02.1933

else
`$output_format = 'd/m/Y';`
or
`$output_format = 'd-m-Y';`
return wrong value : 01/01/1970 | 01-01-1970

**Comment by briannesbitt** [comment]
```php
echo Carbon::createFromFormat('Y-m-d', '1933-02-15')->format('d.m.Y') . PHP_EOL;
echo Carbon::createFromFormat('Y-m-d', '1933-02-15')->format('d/m/Y') . PHP_EOL;
echo Carbon::createFromFormat('Y-m-d', '1933-02-15')->format('d-m-Y') . PHP_EOL;
```

Gives me
```
15.02.1933
15/02/1933
15-02-1933
```

... as expected.  I think you are not always passing in '1933-02-15' as your date to the createFromFormat call?

**Comment by biscolab** [comment]
There was my error! Now fixed. In a Model that extends the parent class, a forgotten mutator executed twice generated conflict
