### ISSUE TITLE
Is this project still alive?

### ISSUE THREAD

**Issue by martinssipenko** [briannesbitt/Carbon#781]
I'm asking because there have not been any releases recently.

**Comment by briannesbitt** [comment]
Yes, still alive.

**Comment by kargnas** [comment]
So why don't you any release?

**Comment by erdemkeren** [comment]
Same here. I wan't to use some features I can find on master.

```
>>> (new Carbon\Carbon('4 Nov 2015'))->diffForHumans(Carbon\Carbon::now()) // Date of 1.21.0
=> "11 months before"
```

**Comment by BlueTeck** [comment]
I've also added missing translations a long time ago, that were not merged:

https://github.com/briannesbitt/Carbon/pull/746

**Comment by manh91** [comment]
I made an online site for testing your API. But it still has ton of bugs.
Longing for next release :(
[http://phpio.net/tools/carbon](http://phpio.net/tools/carbon)

**Comment by timmetj** [comment]
Please make a new release? It's been over a year now. I know you must be working on 2.0, but please make a new branch and give a few fixes in the 1.0. Languages aren't correct in 1.0.

**Comment by dereuromark** [comment]
@manh91 Can you please also make a testing online site for the successor project [Chronos](https://github.com/cakephp/chronos)?

**Comment by briannesbitt** [comment]
Release on the way.

**Comment by tm1000** [comment]
Still no release in Composer....
