### ISSUE TITLE
Carbon Parse Last Day of Month

### ISSUE THREAD

**Issue by rohstar** [briannesbitt/Carbon#782]
On parsing the last second of the month, you get back the next day. 

Carbon::parse('2016-09-31 23:59:59')->toDateTimeString() => "2016-10-01 23:59:59"

**Comment by lucasmichot** [comment]
Unfortunately there are only 30 days in September ;-)

**Comment by rohstar** [comment]
@lucasmichot oops! My bad. still would be nice to return ->lastDayOfMonth(). 

Thanks!

**Comment by lucasmichot** [comment]
I think this is already the purpose of `->daysInMonth` and `endOfMonth()` ?

**Comment by lucasmichot** [comment]
Can this be closed @rohstar ?
