### ISSUE TITLE
setLocale only works in method diffForHumans

### ISSUE THREAD

**Issue by brunoramonalmeida** [briannesbitt/Carbon#784]
Carbon::setLocale('pt_BR');                
return Carbon::now()->format('l j F Y H:i:s');
It returns 'Monday 17 October 2016 21:53:33'
if I try with diffForHumans it works. What's wrong?
Is it a limitation or a bug?

Translate does not work for format

**Comment by briannesbitt** [comment]
http://carbon.nesbot.com/docs/#api-localization

**Comment by brunoramonalmeida** [comment]
I've tried it, it does not work for "format".

**Comment by briannesbitt** [comment]
Look at the first example.... `formatLocalized()`

**Comment by brunoramonalmeida** [comment]
$dt = Carbon::now();
setlocale(LC_TIME, 'German');
$dt->formatLocalized('%A %d %B %Y');

resulting in: Monday 17 October 2016

I don't know what to try anymore

**Comment by brunoramonalmeida** [comment]
`Carbon::setLocale('pt_BR');
return Carbon::now('America/Fortaleza')->format('l j F Y H:i:s');`// Monday 17 October 2016 22:12:38 (WRONG)

when:
`Carbon::setLocale('pt_BR');
return Carbon::now()->diffForHumans(); // há 1 segundo (RIGHT)

Get it?

**Comment by briannesbitt** [comment]
Try this 

```
setlocale(LC_TIME, "fr");
echo strftime("Weekday: %A");   // lundi
```

Doesn't rely on Carbon... but basically what Carbon is doing with the `formatLocalized()` call.

**Comment by brunoramonalmeida** [comment]
It did not work. 
It did: 'Weekday: Monday'.
What is that about? Do you know? 
So, it means that is not a Carbon problem, right?

**Comment by briannesbitt** [comment]
Correct.  Are you on linux?

on Linux
If you have trouble with translations, check locales installed in your system (local and production).
locale -a to list locales enabled.
sudo locale-gen fr_FR.UTF-8 to install a new locale.
sudo dpkg-reconfigure locales to publish all locale enabled.
And reboot your system.

This will depend on which flavour you are using, but you need to install the locale you want to use.

**Comment by brunoramonalmeida** [comment]
Dude, you saved my life!

I did this, the problem was in my linux was installed "pt_BR.utf8", no "pt_BR". Now, everything is working. 

You were right, it's not a Carbon issue!

Thanks in advice, many thanks man!

**Comment by briannesbitt** [comment]
👍

**Comment by luiz-andrade** [comment]
> Cara, você salvou minha vida!
> 
> Eu fiz isso, o problema estava no meu linux foi instalado "pt_BR.utf8", não "pt_BR". Agora tudo está funcionando.
> 
> Você estava certo, não é uma questão de carbono!
> 
> Obrigado em conselho, muito obrigado cara!

Bom Dia. O post é antigo mas estou com o mesmo problema, como voce resolveu ?
Obs.: Já instalei o pt_BR.

**Comment by kylekatarnls** [comment]
With last version:

```php
Carbon::setLocale('pt_BR');

echo Carbon::now()->translatedFormat('l j F Y H:i:s');
```

**Comment by opanegro** [comment]
@kylekatarnls thanks, it works.
