### ISSUE TITLE
Microseconds PHP 7.1

### ISSUE THREAD

**Issue by strebl** [briannesbitt/Carbon#785]
Hi

I'm currently testing my application with PHP 7.1 RC5 on my local dev machine (MacOS Sierra) and Travis CI.
My tests are failing because I'm comparing dates.

After debugging I see following:
Creating a new Carbon instance with Carbon::now() on PHP < 7.1 sets the microseconds to 000000. On PHP 7.1 it sets the real microseconds. Therefore all `->eq()` are failing.

Is that a change Carbon should handle?

Regards

**Comment by strebl** [comment]
To fix my PHP 7.1 issues, I reset the microseconds:
```php
$created_at = \Carbon\Carbon::now()->subHour();
$created_at->second($created_at->second);
```

Do I miss something?

**Comment by dereuromark** [comment]
Yeah, PHP 7.1 is indeed breaking the code due to the microseconds not being resetted.
We fixed it recently in [Chronos patch 1.0.1](https://github.com/cakephp/chronos/releases/tag/1.0.1), as well. Check the commit history on how it was resolved. Same would apply here.

**Comment by etcinit** [comment]
Just encountered this issue as well while upgrading a project to 7.1. Tests checking for equality started failing.

**Comment by mnabialek** [comment]
I've noticed the same problem. I've decided to use in my tests instead of

```php
$this->assertTrue($date1->eq($date2));
```

to

```php
$this->assertSame($date1->toDateTimeString(), $date2->toDateTimeString());
```

Otherwise they were failing in PHP 7.1

**Comment by bicatu** [comment]
any idea when this is going to be solved? do you need any help on testing?

**Comment by cfoellmann** [comment]
A fixed release would be great!!
SEE: https://github.com/cakephp/chronos/pull/112

**Comment by Glavic** [comment]
Why remove microseconds from >=7,1 ? Why not add them to <7.1 :)

https://github.com/briannesbitt/Carbon/pull/1140
