### ISSUE TITLE
Absolute values in diff methods

### ISSUE THREAD

**Issue by laurentvd** [briannesbitt/Carbon#8]
Hi, I think I found a bug in the latest version. The diff methods seem to always return a positive value. The 2nd argument doesn't have any effect. Check out this code to reproduce the error:

http://paste.laravel.com/koA

**Comment by Jeff-P** [comment]
thanks for the question, the answer helped me out as well

**Comment by mikelito859** [comment]
Thanks

**Comment by kylekatarnls** [comment]
For the record, this parameter will become `false` by default in Carbon 3 so to align with https://www.php.net/manual/en/datetime.diff.php
