### ISSUE TITLE
Carbon::parse('13 November, 2015') wrong

### ISSUE THREAD

**Issue by andrey-helldar** [briannesbitt/Carbon#820]
In the field "input" is entered the text: "13 November, 2015".

When transmitting method "Carbon :: parse ()" I get the following:

```
Carbon {# 447 ▼
     + "Date": "2016-11-13 20: 16: 00.000000"
     + "Timezone_type": 3
     + "Timezone": "Asia / Ulan_Bator"
   }
```

That is, "13 November 2016". Not 2015 year,

**Comment by briannesbitt** [comment]
`echo Carbon::parse('13 November, 2015'); // 2016-11-13 20:15:00`
but
`echo Carbon::parse('13 November 2015'); // 2015-11-13 00:00:00`

The comma makes it an unknown format.

If the format is consistent you can always do 
`echo Carbon::createFromFormat('d F, Y', '13 November, 2015');`

**Comment by andrey-helldar** [comment]
The guide does not describe this method, so I did not know. Thank you!

**Comment by briannesbitt** [comment]
Its documented on http://carbon.nesbot.com/docs/#api-instantiation

`createFromFormat() is mostly a wrapper for the base php function DateTime::createFromFormat. The difference being again the $tz argument can be a DateTimeZone instance or a string timezone value.`

http://php.net/manual/en/datetime.createfromformat.php

**Comment by andrey-helldar** [comment]
Wow)) And I read the readme here on Github)
Thanks!

**Comment by briannesbitt** [comment]
Thats just crazy :-)  Added a full docs link at the bottom now.... can't miss it 👍

**Comment by andrey-helldar** [comment]
I guess I could :-)
