### ISSUE TITLE
formatLocalized  %p (for AM/PM) not displaying anything

### ISSUE THREAD

**Issue by googled** [briannesbitt/Carbon#821]
using ->formatLocalized('%e %B %Y, %I:%M:%S %p')

the %p part is empty.

**Comment by briannesbitt** [comment]
`echo Carbon::now()->formatLocalized('%e %B %Y, %I:%M:%S %p');` gives me `2 December 2016, 10:09:06 AM`

**Comment by googled** [comment]
Using php 7 ?

**Comment by briannesbitt** [comment]
It was on 5.6 ... but here it is again on 7.1

```
z:\dev\CarbonPlay>php -v
PHP 7.1.0 (cli) (built: Dec  2 2016 05:24:39) ( NTS MSVC14 (Visual C++ 2015) x64 )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.1.0-dev, Copyright (c) 1998-2016 Zend Technologies

z:\dev\CarbonPlay>php try.php
2 December 2016, 11:42:09 AM
```

**Comment by googled** [comment]
it appears to have to do with:

setlocale(LC_TIME, "fr_CA.utf8");

in my code...

**Comment by briannesbitt** [comment]
> For the french locale (and others) %p in strftime is empty or a single space. The absence of AM/PM for some locales is correct as 24 hour time is usually the norm and sometimes there is no one-to-one equivalent for "am" or "pm".

**Comment by googled** [comment]
my bad!

we do use am/pm though in french.

**Comment by googled** [comment]
Terrifiv library mate, congratz on it's success :)
