### ISSUE TITLE
extend diffInDays

### ISSUE THREAD

**Issue by timzaak** [briannesbitt/Carbon#830]
```php
$a = new Carbon("2016-01-02 01:10:00")
$b = new Carbon("2016-01-01 01:29:00")
$a->diffInDays($b) //0
```
In my use case , I want there has some api to get `$a->someApi($b) == 1` .
the  following implement is ok, and is easy to expand to `diffInHours`, `diffInMonths` ... but don't know how to give the api name. is there any other idea? 
```php
(($a->timestamp - $a->timestamp%(60*60*24)) -($b->timestamp - $b->timestamp%(60*60*24)))/(60*60*24)     //1
```

**Comment by lucasmichot** [comment]
Sorry @timzaak but your issue is not really clear

**Comment by Glavic** [comment]
Maybe set time to `00:00:00` on first object?

```php
$a->startOfDay()->diffInDays($b); // 1
```
