### ISSUE TITLE
Symfony uses

### ISSUE THREAD

**Issue by webprogramozo** [briannesbitt/Carbon#831]
Hi,

I'm using Carbon in multiple projects but I don't use Symfony/Composer. I understand that there is some functionality what currently requires symfony codebase but without Composer those functions are useless and if I call them 'accidentally', my code breaks. 

Is it possible that split the symfony-specific code to an extended class?

**Comment by lorenzo** [comment]
@webprogramozo  Maybe try [Chronos](https://github.com/cakephp/chronos) ? It was built mainly because of this use case, as the extra dependencies where often conflicting for me. It is api compatible with Carbon

**Comment by Glavic** [comment]
Same as https://github.com/briannesbitt/Carbon/issues/1062
