### ISSUE TITLE
diffForHumans is misleading when looking at 1 - 2 weeks

### ISSUE THREAD

**Issue by dfoxx** [briannesbitt/Carbon#833]
Not terribly important, but for **humans** this is misleading...

![screen shot 2016-12-22 at 1 21 26 pm](https://cloud.githubusercontent.com/assets/4933482/21435893/08793d00-c84a-11e6-8086-d520489ae6a0.png)

4 January 2017 is 13 days from today (22 December 2016) it shows "1 week from now", because it's less than two weeks. I would argue less than 2 weeks should include days (like "1 week 6 days from now"), or for ease only days (like "13 days from now").

**Comment by Glavic** [comment]
Method `diffForHumans()` now accepts argument `$parts` (last one), which does exactly that.
