### ISSUE TITLE
Range of dates for humans

### ISSUE THREAD

**Issue by maidmaid** [briannesbitt/Carbon#838]
It would be useful to write a range of dates for humans, like this:

```php
echo Carbon::parse('2016-10-15 12:00')->rangeForHumans('2016-10-17 13:00');
// from Saturday, October 15, 2016 to Monday, October 17, 2016 from 12:00 PM to 1:00 PM
```

I have created a [lib](https://github.com/maidmaid/phperiod) that writes ranged translated dates in many formats. If you are interested, I can suggest a PR that adds this feature in Carbon.

**Comment by maidmaid** [comment]
WDYT @lucasmichot?

**Comment by maidmaid** [comment]
ping @lucasmichot

**Comment by kylekatarnls** [comment]
Nice, and good idea for the i18n fallback. If you're still motivated, I would be interested in your PR.

**Comment by kylekatarnls** [comment]
I close this for now, but if you send a PR, it will be welcome.
