### ISSUE TITLE
Carbon needs to be more ACTIVE.

### ISSUE THREAD

**Issue by tm1000** [briannesbitt/Carbon#839]
Can we can get update on https://packagist.org/packages/nesbot/carbon

Right now I'm having to use dev-master to get some nice changes from the community. (Like setLocale not crashing the entire framework when the locale doesn't exist)

Furthermore I know a few other people have proposed or questioned if @briannesbitt was alive or active. He came back and said he was (#781), committed some PRs. Said he was going to release but then didn't. There are over 71 issues and 21 pull requests. The last thing Brian did was on Decemebr 2nd. I guess what I'm asking here is what is the status of this project.

It's a great project but it can't survive based on one owner who shows up every 6 months and then disappears again. There are plenty of community members who I assume would help out if given permissions. (@lucasmichot comes to mind).

Don't let this project rot. You've got a whole community on your side trying to help @briannesbitt!

**Comment by lucasmichot** [comment]
@tm1000 , I've already proposed this to @briannesbitt - I will be glad to help

**Comment by dakota** [comment]
@tm1000 Lack of active development (and the addition of `symfony/translation` as a dependency) is the primary reason behind the CakePHP team deciding to fork Carbon. We created the [Chronos](https://github.com/cakephp/chronos) library to allow for the continued development of the great work that @briannesbitt (and others) had done with Carbon.

Chronos is more-or-less compatible with Carbon (You should be able to simply replace Carbon), with the addition of functionality like immutable datetime and date classes. It also has some great [documentation](https://book.cakephp.org/3.0/en/chronos.html), and is fully supported by the entire CakePHP team.

**Comment by dereuromark** [comment]
@dakota @tm1000  It is probably worth mentioning that Chronos supports the new interfaces of recent PHP versions as well as Mutable vs Immutable (the latter should be used if possible).
Carbon never implemented any of that. Refs https://github.com/briannesbitt/Carbon/issues/406

**Comment by tm1000** [comment]
Wow that's awesome guys! I love CakePHP and it's nice to know that the development team of CakePHP supports "Chronos". Will look into changing out Carbon for Chronos in the next couple of weeks.

**Comment by lucasmichot** [comment]
I am very happy to announce you that I am now collaborating on `briannesbitt/carbon`

Release will now happen much more often.
And lots of other great features for `2.0` on their way 💯  !

**Comment by tm1000** [comment]
@lucasmichot can you push a tag out for the most recent changes so I no longer have to tell composer to use dev-master??

**Comment by lucasmichot** [comment]
Sure @tm1000 , there are some PR to apply and some docs to write. A release could be done next weekend

**Comment by lucasmichot** [comment]
Version `1.22.0` has just been released.
On my way for updating the docs.

**Comment by tm1000** [comment]
@lucasmichot do you need help maintaining this? 57 PRs. Last commit was Feb.

**Comment by dereuromark** [comment]
@tm1000 Whats the big deal? You can see above there is Chronos available, which basically supports up to PHP7.2 by now :)

**Comment by tm1000** [comment]
@dereuromark that requires me to do work! I don't want to do work!!!!....

.....ok fine....... I guess it's time I looked into https://github.com/cakephp/chronos/issues/84 👍
