### ISSUE TITLE
Translation for th is wrong

### ISSUE THREAD

**Issue by nicolas-grekas** [briannesbitt/Carbon#840]
in `src/Carbon/Lang/th.php`

there are no plural in th, which means e.g.
`    'year' => '1 ปี|:count ปี',`
should be 
`    'year' => ':count ปี',`

ping @@ROKAISAKKON, follow up of https://github.com/symfony/symfony/pull/20299

**Comment by ROKAISAKKON** [comment]
@nicolas-grekas Thank a lot, confirm translation for th is wrong.

**Comment by lucasmichot** [comment]
Can anyone make a PR?
With tests would be even better !

**Comment by lucasmichot** [comment]
@nicolas-grekas - feel free to open a PR to fix this

**Comment by nicolas-grekas** [comment]
ping @ROKAISAKKON I'll let you do the PR please :)
