### ISSUE TITLE
PHP 7.1 apparently added microseconds in setTime method

### ISSUE THREAD

**Issue by elibyy** [briannesbitt/Carbon#844]
I've just installed carbon on PHP 7.1 and got the following warning

> Warning: Declaration of Carbon\Carbon::setTime($hour, $minute, $second = 0) should be compatible with DateTime::setTime($hour, $minute, $second = NULL, $microseconds = NULL) in vendor/nesbot/carbon/src/Carbon/Carbon.php on line 2127

So I've checked with the php manual and 7.1 release notes and it seems that they have missed it but as you can see [here](https://github.com/php/php-src/blob/php-7.1.0/ext/date/php_date.c#L263) it's in the core.

I can create pull request if needed :)

**Comment by sihades** [comment]
We have some implementations that depends on Carbon and actually we will migrate our servers to PHP 7.1, so it's important if you help us to fix it in order we want to continue using Carbon :).

**Comment by elibyy** [comment]
i ended up using [Chronos](https://github.com/cakephp/chronos) which is an active fork

**Comment by jbrooksuk** [comment]
There was a commit to Carbon 5 hours ago, how is it not active? 🤔

**Comment by elibyy** [comment]
it's much less active. also. see the commit log

**Comment by briannesbitt** [comment]
Just an fyi, @lucasmichot was added as a project committer so things should pickup

**Comment by lucasmichot** [comment]
@elibyy , Carbon does not override `setTime()`, at least in the current stable version.

**Comment by elibyy** [comment]
hey @lucasmichot thanks for letting me know, as specified, i already moved to chronos but good to know, will close this issue :)

**Comment by DeeJaVu** [comment]
Goodby Carbon - Welcome [Chronos](https://github.com/cakephp/chronos)
