### ISSUE TITLE
Carbon object changes on different variables

### ISSUE THREAD

**Issue by tdolph** [briannesbitt/Carbon#845]
Is it supposed to act like this? Using Laravel 5.3.

`
$date = Carbon::now();
$starting_at = $date->startOfWeek();
$ending_at = $date->endOfWeek();`

After this. $starting_at is the same as $ending_at and showing date for end of the week. Why is it happening?

**Comment by briannesbitt** [comment]
Carbon is not immutable.  You can use the `copy()` method if you want to create a second instance.  This will be changing in a v2 release.

**Comment by timacdonald** [comment]
I've just created a little wrapper package around Carbon to make it immutable.

https://github.com/timacdonald/immutable-carbon
