### ISSUE TITLE
Update History

### ISSUE THREAD

**Issue by mfn** [briannesbitt/Carbon#853]
I can't find any documentation about the new release, is there a changelog somewhere?

http://carbon.nesbot.com/history/ does not cover 1.22.0

**Comment by pascalbaljet** [comment]
That would be great, many of my tests are failing because of the new 1.22.0 release, a changelog would definitely help to debug :)

**Comment by mfn** [comment]
I was about to suggest to look at the diff since the last release, but it's not for the faint of the heart: https://github.com/briannesbitt/Carbon/compare/1.21.0...1.22.0

**Comment by lucasmichot** [comment]
I am still writing the documentation, it should be available tonight
@pascalbaljet - this is strange as this new release only bring new features, nothing was changed.

**Comment by lucasmichot** [comment]
@ascalbaljet can you maybe send me an example of a failing test?
this might be related to : https://github.com/briannesbitt/Carbon/issues/852

**Comment by lucasmichot** [comment]
Ping @pascalbaljet

**Comment by lucasmichot** [comment]
See #890
