### ISSUE TITLE
Why toIso8601String() change from +0000 to +00:00 ?

### ISSUE THREAD

**Issue by thanh-taro** [briannesbitt/Carbon#861]
I just run the composer update today and all my unit tests are failed. Because of this change.

**Comment by dereuromark** [comment]
Refs https://github.com/briannesbitt/Carbon/issues/451
In Chronos we were able to implement it correctly, the PHP implementation is wrong and not the actual ISO value. For BC reasons you cannot change this in in minors of course for Carbon usually.

**Comment by ameliaikeda** [comment]
This is indeed a breaking change – it just KOed several test suites of ours, and our database :cry:

**Comment by kylekatarnls** [comment]
Now explained in the documentation.
