### ISSUE TITLE
Error in PHP 5.5.9. PHP DateTime::setTimezone(): Can only do this for zones with ID for now 

### ISSUE THREAD

**Issue by dixalex** [briannesbitt/Carbon#865]
Getting error in my Laravel project here: 
`vendor/nesbot/carbon/src/Carbon/Carbon.php(946): DateTime->setTimezone(Object(DateTimeZone))`

Error log: `PHP DateTime::setTimezone(): Can only do this for zones with ID for now `
PHP version: 5.5.9
Carbon version: 1.22.1 (works on 1.21.0 though)

**Comment by lucasmichot** [comment]
Can you show me the code causing this error?

**Comment by dixalex** [comment]
It's not related specifically to my code:
```
           $user_token = JWTAuth::getToken();
            $user = JWTAuth::toUser($user_token);
            $token = JWTAuth::parseToken()->refresh();
```

The error is raised by `refresh()` function of [JWTAuth](https://github.com/tymondesigns/jwt-auth/). I'm using version 0.5.9.

**Comment by lucasmichot** [comment]
I believe this is more in your implementation of https://github.com/tymondesigns/jwt-auth/
