### ISSUE TITLE
between equal to not working?

### ISSUE THREAD

**Issue by octoxan** [briannesbitt/Carbon#868]
If I have two dates, 1/20/2017 and 1/23/2017, and today is 1/23/2017 then shouldn't the following be equal to true.

```php
$validity = Carbon::now()->between($start, $final, true);
```

I've tried changing the third argument there to both true and false, but this always returns false unless I set the second date to one past what I want it to be?

**Comment by willrowe** [comment]
`between` takes into account the entire `DateTime`, which includes the time. Double-check what time of day is set on `$final`.

**Comment by lucasmichot** [comment]
Indeed @willrowe ! Thanks for issue solving
