### ISSUE TITLE
create date with no overflow

### ISSUE THREAD

**Issue by davidkoberan** [briannesbitt/Carbon#870]
i would like to ask for guidance with one problem. i'm creating date from string and in some cases it can be non-existing (e.g. 2017-02-30).

in this case created date will be 2017-03-02, is it somehow possible to create date without overflow to next month so end will be 2017-02-28. something like function addMonthNoOverflow().

thanks.

**Comment by lucasmichot** [comment]
Try the `\Carbon\Carbon::createSafe()` function maybe?

**Comment by davidkoberan** [comment]
thanks.
