### ISSUE TITLE
Wrong arabic format

### ISSUE THREAD

**Issue by TamkeenLMS** [briannesbitt/Carbon#873]
First, THANKS, Carbon is a godsend for me.

In the language files, namely the Arabic one. The "from_now" key isn't formatted correctly in Arabic, currently it print: " from now xxx ", it should be " xxx from now ", as it's in English. So, instead of 
```
    'from_now' => 'من الآن :time',
```
It should be 
```
    'from_now' => ':time من الآن',
``` 

Thanks.

**Comment by lucasmichot** [comment]
Thanks @TamkeenLMS , can you maybe submit a PR?

**Comment by TamkeenLMS** [comment]
Done. Thanks again :)

**Comment by lucasmichot** [comment]
See https://github.com/briannesbitt/Carbon/pull/875
