### ISSUE TITLE
Setting month to a month with 30 days when at the 31 gives wrong month

### ISSUE THREAD

**Issue by EmilMoe** [briannesbitt/Carbon#879]
I just experienced this issue today where it's 31th of January, that I want to set this:

~~~~php
Carbon::now()->month(11)->year(2016);
~~~~

The result is 1st of December 2016 since November only has 30 days. Solution was to add `startOfMonth()` before I set the month.

Shouldn't the behaviour here be to set the month to November and just `lastOfMonth` in cases like this?

**Comment by willrowe** [comment]
The `subMonths` and `addMonths` methods will do this if the `$monthsOverflow` property is set to false using the `useMonthsOverflow` method.
It might make sense to expand use of the overflow property to cover cases like your example.

**Comment by tommica** [comment]
I also experienced yesterday (31-01-2017) that something like Carbon::createFromFormat('m-Y', '11-2016')->format('m-Y') results in '12-2016'

**Comment by EmilMoe** [comment]
@willrowe I think so, because its not what is the expected behaviour.

**Comment by briannesbitt** [comment]
This is based on the underlying PHP functionality.  I am not sure if you say create a date with a year of 2016-11-XX what you would expected? What should it use for the day?  It picks the day today which is in theory invalid and jumps it forward to a valid date.

The use case is easy to resolve as you just be more specific and use a day of 1 and then move to endOfMonth() if that is what you want.

**Comment by EmilMoe** [comment]
I understand if it's how PHP it's an argument not to change that. I also agree it's something that should be discussed by more than just 3-4 people.

But my opinion is still the same, I set month and year and don't expect it to be a different month. Maybe the better result would be a warning.

**Comment by arjasco** [comment]
@briannesbitt @EmilMoe Had a similar discussion on the Laravel framework issues page the other day. Doing validation against just the year and month fails if you're in a month with 30-31 days and you're current on one of them days. A really quick fix is to put a '!' at the start of the format before creating the instance.

Roll your clock back to January 30th or 31st and run the following

```php
echo DateTime::createFromFormat('Y-m', '2016-02')->format('Y-m') . "\n";
echo DateTime::createFromFormat('!Y-m', '2016-02')->format('Y-m') . "\n";
```

You will see the second one creates the correct date time. Not sure if this affects creating instances with a timestamp etc?

**Comment by lucasmichot** [comment]
Yeah, it seems the usage of `\Carbon\Carbon::shouldOverflowMonths` could be applied in many other cases

**Comment by EmilMoe** [comment]
I just had the same error as you @arjasco a production environment went off because I had this

~~~~php
Carbon::createFromFormat('Y\Mm', $date)->startOfDay()->startOfMonth();
~~~~

Now and yesterday February resulted in March.

**Comment by arjasco** [comment]
@EmilMoe Yep! It has affected me today in production... I should of known better seeing as i raised the point.

<img src="https://s14.postimg.org/ljtrev081/Screen_Shot_2017-05-31_at_19.38.13.png" width="200">

If you only care about the month then resetting the day back to the 1st helps too eg.
```php
Carbon::now()->day(1)->month(7)->format('F');
```

I'm pretty sure i didn't find anything about it in the PHP internals issues site either when i first looked..

**Comment by EmilMoe** [comment]
@arjasco Can you do this

~~~~php
Carbon::now()->firstOrMonth()->format('Y\Mm');
~~~~

I haven't tested it, but it might be a solution.

**Comment by EmilMoe** [comment]
@briannesbitt Will this prevent my issue with `createFromFormat`?

~~~~php
Carbon::useMonthsOverflow(false);
~~~~

**Comment by Glavic** [comment]
@EmilMoe: both of your last examples will solve this issue.
