### ISSUE TITLE
Incorrect result with the function subMonths()

### ISSUE THREAD

**Issue by sairam2188** [briannesbitt/Carbon#881]
Hi. For this date: 2017-01-31, the function subMonths(2) does not return the correct result.

Example:
`$month = Carbon::now()->subMonths(2)->format('n');`

return 12
should return 11

thanks for any help.

**Comment by willrowe** [comment]
Try turning off month overflow:
```php
Carbon::useMonthsOverflow(false);
$month = Carbon::now()->subMonths(2)->format('n');
```

or if you simply need to know which month was two months before the current month then:
```php
$month = Carbon::now()->startOfMonth()->subMonths(2)->format('n');
```

Things can get a little weird at the end of months since months don't all have the same number of days.

**Comment by underdpt** [comment]
I think this should be stated on the docs, maybe as a warning.

I didn't find the docs on github, to send a PR.

**Comment by mcoenca** [comment]
Same here, really surprised that on the `31/10/17` `Carbon::now()->subMonths(1)->format('m/y')` gives me back `10/17`

**Comment by Glavic** [comment]
@mcoenca: 31/10/2017 - 1 month = 31/09/2017. September doesn't have 31 days, so overflow happens to 01/10/2017. That is why you get back 10/2017.

@willrowe already showed solution. _Closing this issue. Reopen if needed._

**Comment by kylekatarnls** [comment]
Documentation needed. I will document that.

**Comment by kylekatarnls** [comment]
Overflow now documented.
