### ISSUE TITLE
setDate issue with 1.22.1

### ISSUE THREAD

**Issue by th3fallen** [briannesbitt/Carbon#882]
After an update to 1.22.1 the setDate method in carbon is reporting, that param 1 must be an integer, the issue stems from this commit https://github.com/briannesbitt/Carbon/commit/4d57f3197510067a9ee29b81e2fe4c097a8444d8

Since the second is the case being triggered but when the stack goes to here with only a second
http://th3fallen.d.pr/161dr.jpg

you see in http://th3fallen.d.pr/XCwY.jpg that setDate is missing a year which is causing http://th3fallen.d.pr/rAjJ.jpg to fail due to missing a year.

**Comment by th3fallen** [comment]
in digging deeper seems to occur when passing a date of `0000-00-00 00:00:00` which returns

```
{
  ["date"]=>
  string(27) "-0001-11-29 17:00:00.000000"
  ["timezone_type"]=>
  int(3)
  ["timezone"]=>
  string(14) "America/Denver"
}
```

**Comment by Glavic** [comment]
Images do not exists anymore. Could you check if this issue still exists in v1.23? If it does, please let me know, so I can reopen this case.
