### ISSUE TITLE
php-cs-fixer and .gitattributes EOL inconsistent on Windows

### ISSUE THREAD

**Issue by Ovsyanka** [briannesbitt/Carbon#885]
I have a Windows 7. When i run php-cs-fixer all files marked "changed" because theirs EOL was changed from CRLF to LF.

But why they have CRLF initially?
It is because `* text=auto` in `.gitattributes`. It means that all files that considered as text will have system-related EOL in working directory. On windows it is CRLF.

But php-cs-fixer dont bother what is the current system - it always make EOL = LF.

**Comment by GawainLynch** [comment]
​Owing to the apparently "unmaintained" status of this project (last official update was Februrary 2017), a small group have forked this project, and merged this pull request.
​​
You can safely update to the new project by changing `nesbot/carbon` to `carbondate/carbon` in your project's `composer.json` file.

The new home for the project is https://github.com/CarbonDate/Carbon and we welcome continuing engagement from the open source community.

Please also note that Carbon owes its very existence to Brian Nesbitt's work, and for that, we are eternally grateful.

**Comment by dereuromark** [comment]
@GawainLynch 
Why not contributing to https://github.com/cakephp/chronos as de facto successor?
Having a strong community behind a project is always a big plus here.

**Comment by GawainLynch** [comment]
Compatibility would be the first. We have years of support to provide yet on components using `Carbon\Carbon`, so Chronos is just not an option.

**Comment by kylekatarnls** [comment]
Now fixed.
