### ISSUE TITLE
Carbon does not handle DST correct when calculating in users default timezone.

### ISSUE THREAD

**Issue by kaufholdr** [briannesbitt/Carbon#887]
If a user does a calculation with Carbon instances in his current timezone then all the addXXX and subXXX methods do not handle DST correctly.
This behaviour is inconsistent when it comes to calculations in other timezones because then the DST will be handled properly.
The core of this problem is that calculation methods are based on modify which ignores DST and that the overloaded version of modify in Carbon does directly use this method when calculating in the users default timezone.

```
    /**
     * Consider the timezone when modifying the instance.
     *
     * @param string $modify
     *
     * @return static
     */
    public function modify($modify)
    {
        if ($this->local) {
            return parent::modify($modify);
        }

        $timezone = $this->getTimezone();
        $this->setTimezone('UTC');
        $instance = parent::modify($modify);
        $this->setTimezone($timezone);

        return $instance;
    }
```

Failing Test: Add 61 Minutes on the border of DST in America/Toronto

```
    public function testTimezoneAddMinutesInLocalTimezone()
    {
        $a = new Carbon('2016-11-06 01:59:00'); // This only works in timezone America/Toronto
        $b = $a->copy();
        $b->addMinutes(61);
        $this->assertSame(61, $a->diffInMinutes($b));
        date_default_timezone_set($default_timezone);
    }
```

Workaround: Do not use addXXX subXXX methods and use add(CarbonInterval interval) instead.

```
    public function testTimezoneAddMinutesInLocalTimezoneWorkaround()
    {
        $a = new Carbon('2016-11-06 01:59:00'); // This only works in timezone America/Toronto
        $b = $a->copy();
        $b->add(\Carbon\CarbonInterval::minute(61));
        $this->assertSame(61, $a->diffInMinutes($b));
    }
```

Possible Solutions:

1. Change all addXXX or  methods to use add(CarbonInterval interval) instead.
2. Change Carbon::modify to never directly call modify. (tried it. fixes my unit test but breaks at least 50 other.) ;-)

I have prepared a fork with the unit test (https://github.com/yathos/Carbon) and am willing to create a fix if you guide me which of the proposed solutions is the right one.

This issue is a followup of: [Pull 548](https://github.com/briannesbitt/Carbon/pull/548)

**Comment by Ovsyanka** [comment]
I want to point here to this issue: #883. There i described my opinion about this situation.

**Comment by kaufholdr** [comment]
You are right the issues are closely related.

**Comment by lucasmichot** [comment]
See #884

**Comment by kaufholdr** [comment]
Thanks. Problem Solved.
