### ISSUE TITLE
closest() and farthest() not documented

### ISSUE THREAD

**Issue by samiles** [briannesbitt/Carbon#888]
[closest()](https://github.com/briannesbitt/Carbon/blob/master/src/Carbon/Carbon.php#L1587) is very very helpful, but does not seem to be documented? It is included in the [History](http://carbon.nesbot.com/history/) page for release 1.21.0, but it isn't in the [documentation](http://carbon.nesbot.com/docs/). Should it be added?

**Comment by lucasmichot** [comment]
See #890
