### ISSUE TITLE
Provide an up-to-date date documentation for > 1.22

### ISSUE THREAD

**Issue by lucasmichot** [briannesbitt/Carbon#890]
Provide an up-to-date date documentation for releases `> 1.22`

---

An feedback on auto-generated documentation is welcome.

Any PR on documenting new `> 1.22` functions is greatly appreciated too ! 
(please just reference this issue)

---

TODO:

- [x] `CreateSafe`
- [x] `closest` & `farthest`
- ...

**Comment by kylekatarnls** [comment]
All documented for next release.
