### ISSUE TITLE
Date difference for multiple units

### ISSUE THREAD

**Issue by christophrumpel** [briannesbitt/Carbon#903]
Hey, 

I was just trying to create a dateTime difference string like `10 days 5 hours 23 minutes 12 seconds`. I tried the `differenceForHumans` methods but they just work for one of the units. Is it possible to get the above output with Carbon?

Thx and greets

**Comment by Glavic** [comment]
This is now possible with v1.23, where new argument `$parts = 1` to method `differenceForHumans()` was introduced. 

http://carbon.nesbot.com/docs/#api-humandiff
