### ISSUE TITLE
Next seems to return incorrect values when not using UTC

### ISSUE THREAD

**Issue by jshayes** [briannesbitt/Carbon#909]
Assuming that `var_dump(Carbon::now());` results in
```
object(Carbon\Carbon)#933 (3) {
  ["date"]=>
  string(26) "2017-03-07 18:20:06.751397"
  ["timezone_type"]=>
  int(3)
  ["timezone"]=>
  string(15) "America/Toronto"
}
```

Doing `var_dump(Carbon::now('America/Toronto')->next(Carbon::WEDNESDAY));` gives me the following result.

```
object(Carbon\Carbon)#918 (3) {
  ["date"]=>
  string(26) "2017-03-07 19:00:00.000000"
  ["timezone_type"]=>
  int(3)
  ["timezone"]=>
  string(15) "America/Toronto"
}
```

Since I am dealing with a time in `America/Toronto` I expected that saying `next(Carbon::WEDNESDAY)` would give me the start of the day Wednesday in the `America/Toronto` timezone, rather than Tuesday. 

This was tested on 1.20 and 1.22.1.

**Comment by Ovsyanka** [comment]
As i can see, #884 fixes that.
