### ISSUE TITLE
setLocale on CarbonInterval raise a FatalErrorException if the locale does not exists.

### ISSUE THREAD

**Issue by cyqui** [briannesbitt/Carbon#913]
As of today, there is a workaround :  

`
if (Carbon::setLocale('xx')) {
//Then we can safely do setLocale on CarbonInterval
}
`

But i believe CarbonInterval should behave the same as "Carbon"

**Comment by kylekatarnls** [comment]
Now (in dev-master and in the next version) setLocale of both call a third common Translator.
