### ISSUE TITLE
Confusing addMonth(s) method

### ISSUE THREAD

**Issue by pzaj2** [briannesbitt/Carbon#915]
Hi there!

I read few open issues about that so I wouldn't call it a bug. Although you should really consider solving it somehow, because it does cause confusion and needs workarounds.

I would expect addMonth / addMonths to add a month to my current Carbon instance (meaning that if I am on 01/03/2017 it gives me 01/04/2017). And it probably does in UTC, but consider my example and outcome of addMonths operation:

```php
$months = 2; // I'm here trying to generate 2-months calendar to loop over and render actual calendar
$dt = Carbon\Carbon::parse('2017-03-01 00:00:00', 'Europe/Paris');
$dt2 = $dt->copy()->addMonths($months - 1) // I make the copy just to be sure, because there was a situation where my original object has been modified few times
// $dt2 is now 2017-03-29!
```
While this behaviour is confusing, there's an explanation to it. Considering all operations are done on UTC dates, we end up with $dt back to February with UTC, thus only adding 28 days, converted back gives us March 29th.

I have workarounds for this of course, the easiest one is to first bring the source date to end of the month by calling endOfMonth() and setting Carbon::$monthsOverflow to false or by changing source date to beginning of the month with startOfMonth() and adding daysInMonth (only if adding one month).

While I believe it's intended and correct behaviour, I think it would be nice to have an alternative method, let's call it "nextMonth($keepDay = false)" as an example, which would do change the date to first day of next month (if $keepDay is false) or respective day of next month otherwise (with no overflow).

Would you accept pull request with methods "nextMonth()" and "previousMonth()"?

**Comment by Ovsyanka** [comment]
I wrote this test and #884 passes it.

```
public function testAddMonth() {
        $dt = Carbon::parse('2017-03-01 00:00:00', 'Europe/Paris');
        $dt->addMonths(1);
        $this->assertSame('2017-04-01 00:00:00', $dt->format('Y-m-d H:i:s'));
}
```

**Comment by pzaj2** [comment]
Thank you, I used my workarounds to deal with it until now, but I will revert my code back to work with this PR. Great!
