### ISSUE TITLE
Carbon::createFromFormat() unexpected behaviour

### ISSUE THREAD

**Issue by tschallacka** [briannesbitt/Carbon#917]
When I do `Carbon::createFromFormat('Y-m-d', '2017-03-25')` I end up with a carbon object with the curren time.
```
   [0] => Carbon\Carbon Object
       (
       [date] => 2017-03-25 08:31:43.000000
       [timezone_type] => 3
       [timezone] => UTC
        )
```
I would expect Carbon object with [date] => 2017-03-25 00:00:00.000000 instead.

**Comment by pavlovskyarto** [comment]
Same issue with days.
Lets imagine that today is 2017-07-31.
When we run `Carbon::createFromFormat('Y-m', '2017-06')`
We obtain 2017-07-01

This is critical error.

**Comment by tschallacka** [comment]
@pavlovskyarto so what happens to you is
2017-6 
Missing day. 
Get current day, append to date
Eval date
Date invalid by one day, shift to valid date by difference in day.

If thats the case its probaly the samed root cause

**Comment by pavlovskyarto** [comment]
@tschallacka yes. 
But how to fix it? When we parse date without a day - it should take the 1st day of month, but not current. Isnt it?

**Comment by tschallacka** [comment]
only solution at the moment is to keep an eye out for the edge cases and correct it manually.

**Comment by Glavic** [comment]
In v1.23 new method was added: `createFromDate()`, where time parts will be set to zero.
