### ISSUE TITLE
Allows createFromTime('00:00:00')

### ISSUE THREAD

**Issue by rentalhost** [briannesbitt/Carbon#919]
Currently the `createFromTime()` method expects four arguments: `hour?`, `minute?`, `second?` and` tz?`. Should be great if it could support a string that defines hours and minutes (and optionally seconds). It will help if you are loading data from SQL, for instance:

```php
$time = Carbon::createFromTime('02:40');    // 02 hours and 40 minutes
$time = Carbon::createFromTime('02:40:35'); // 02 hours, 40 minutes and 35 seconds
```

I could make a PR if you think that it's valid.

**Comment by Glavic** [comment]
Sorry for late reply.

Yes, PR would be welcomed. Maybe name of method should be `createFromTimeString` ?

**Comment by Glavic** [comment]
> $time = Carbon::createFromTime('02:40');    // 02 hours and 40 minutes

To me this would mean `2 min 40 sec` not hours and minutes..

**Comment by kylekatarnls** [comment]
Hi, I would prefer one method for each data input type. And as we have `setTime` and `setTimeFromTimeString` (see: http://carbon.nesbot.com/docs/#api-settersfluent), it would be consistent to have `createFromTimeString` and keep `setTimeFromTimeString` and  `createFromTimeString` synchronized on possible input and interpretation of it.

@Glavic currently `setTimeFromTimeString('02:40')` will set 2 hours 40 minutes 0 seconds so I agree for the same behavior for `createFromTimeString`.

**Comment by kylekatarnls** [comment]
I close this, we can continue to discuss about this on the implementation PR #1192
