### ISSUE TITLE
BUG on addMonth 

### ISSUE THREAD

**Issue by minkbear** [briannesbitt/Carbon#923]
if Today = 2017-03-29
and Today - 1 month = should be 2017-02-28 (expected end of last month)

Here is code

```PHP
dd(Carbon::now())

Carbon\Carbon {#1352
  +"date": "2017-03-29 13:22:21.000000"
  +"timezone_type": 3
  +"timezone": "Asia/Bangkok"
}

dd(Carbon::now()->addMonth(-1))

Carbon\Carbon {#1352
  +"date": "2017-03-01 13:23:31.000000"
  +"timezone_type": 3
  +"timezone": "Asia/Bangkok"
}
```

**Comment by bramslob** [comment]
Same here, but with Carbon::now()->subMonth(1)->startOfMonth() returning : 
Carbon\Carbon {#1341
     +"date": "2017-03-01 00:00:00.000000",
     +"timezone_type": 3,
     +"timezone": "Europe/Amsterdam",
}

**Comment by VladErc** [comment]
If you can disregard the day and need to check only months and years you can do: Carbon::now()->startOfMonth()->subMonth(1) which will return the first day of last month.

**Comment by bramslob** [comment]
@VladErc sadly I do need to work with the day. But as you can see in my comment, I did do the `startOfMonth()` but that still returned march

**Comment by VladErc** [comment]
@bramslob You did it the other way (first sub then first), which, due to the bug, would've returned 1st of March and then take first of that month. My way gets you to first of March and then subtracting a month which will return 1st of February.

**Comment by bramslob** [comment]
@VladErc I see yes, that does work. But I do believe this is unintended behavior. The order in this should not matter. But thanks for showing a way in which it works for now

**Comment by leepownall** [comment]
#639
#761 

`Carbon::now()->subMonth()` -> `Carbon::now()->subMonthNoOverflow()`
`Carbon::now()->addMonth()` -> `Carbon::now()->addMonthNoOverflow()`

Had same issue, not sure what the underlying reason is, but here is the fix.

**Comment by bramslob** [comment]
@leepownall found that option in the source as well, but did not see the explanation of 'overflow'. Now that you pointed to those issues I get it a lot more. Thanks, I guess we'll change our code accordingly

**Comment by VladErc** [comment]
@leepownall I would've expected default behaviour to be with no overflow, thanks for the fix however!

**Comment by DanielDarrenJones** [comment]
I also feel like the default behaviour should be changed to include the overflow, I was not aware of this until I saw a tweet about it just now and this would have certainly caught me out.

**Comment by dereuromark** [comment]
@DanielDarrenJones https://github.com/cakephp/chronos has the default behavior built in as expected.
For Carbon it would require a major bump in version.

**Comment by DanielDarrenJones** [comment]
@dereuromark ooo thanks for sharing that, it seems to cover some of the shortfalls I didn't like with carbon such as immutability, will defo give that a go 😄

**Comment by lucasmichot** [comment]
@minkbear then use `addMonthsNoOverflow`

**Comment by lucasmichot** [comment]
And have a look at `\Carbon\Carbon::useMonthsOverflow`
