### ISSUE TITLE
createFromFormat()->startOfMonth() is returning wrong output for February

### ISSUE THREAD

**Issue by debashis07** [briannesbitt/Carbon#925]
Tried to get the first date and last date for the month of February. But it's returning the wrong start date and end date for February.

```
date_default_timezone_set('UTC');

$date = 'Feb 2017';
echo 'First Day: ' . Carbon::createFromFormat('M Y', $date)->startOfMonth(); echo '<br/>';
echo 'Last Day: ' . Carbon::createFromFormat('M Y', $date)->endOfMonth(); 
```

It's showing the below output:

> First Day: 2017-03-01 00:00:00
> Last Day: 2017-03-31 23:59:59

This is happening for February of every year only.

**Comment by robertpcontreras** [comment]
Looks like this is a problem in PHP's date time as well... https://3v4l.org/TRpX4

**Comment by robertpcontreras** [comment]
Actually this is due to the fact that today is the 30th... February doesn't have a 30th so it overflows the format overflows it to next month... stick a `!` or specify a day in the string to fix your issue...
```
 Carbon::createFromFormat('!M Y', $date)->startOfMonth()
```

**Comment by debashis07** [comment]
I have tested it today (on 31st) again and found the same issue. I will re-test tomorrow to see whether it resolves or not.

`Carbon::createFromFormat('!M Y', $date)->startOfMonth()`

However, the above solution of yours is working.

**Comment by mcoenca** [comment]
Normal that `Carbon::useMonthsOverflow(false);` from pull request https://github.com/briannesbitt/Carbon/pull/710 does not affect that behaviour too ?

**Comment by kylekatarnls** [comment]
@mcoenca createFromFormat will not take useMonthsOverflow into account. So yes, the good solution is the `!` (`Carbon::createFromFormat('!M Y', $date)->startOfMonth()`) or set manually the day to `1`.
