### ISSUE TITLE
Incorrect $week_no = Carbon\Carbon::createFromDate($y, $m, $d)->weekOfMonth;

### ISSUE THREAD

**Issue by shawindershingora** [briannesbitt/Carbon#929]
i m using Carbon to get week no but i got incorrect information in case if date is = 2017-02-12
$y = 2017;
$m = 02;
$d= 12;
$week_no = Carbon\Carbon::createFromDate($y, $m, $d)->weekOfMonth;

$week_no should be 3 but it returns 2.
pls look into this issue
Thanks

**Comment by smokehill** [comment]
It seems to me that **Carbon** counts **weekOfMonth** independently of calendar order of day.
My problem is similar:
```php
$date = Carbon::createFromFormat('Y-m-d H', '2017-02-13 00', 'Europe/Moscow');
$date->weekOfMonth;
```
I expect that week number will be **3**, but the result is **2**.
Can sombody explane these issue?

**Comment by sisve** [comment]
2017-02-12 is a Sunday. It is week 2 when you assume a week starts on Mondays, and week 3 when you assume they start on Sundays. So it seems Carbon follows the ISO-standard here.

> According to international standard ISO 8601, Monday is the first day of the week. It is followed by Tuesday, Wednesday, Thursday, Friday, and Saturday. Sunday is the 7th and final day.
> Although this is the international standard, several countries, including the United States, Canada, and Australia consider Sunday as the start of the week.

Source: https://www.timeanddate.com/calendar/days/

**Comment by Glavic** [comment]
```php
case $name === 'weekOfMonth':
	return (int) ceil($this->day / static::DAYS_PER_WEEK);

case $name === 'weekNumberInMonth':
	return (int) ceil(($this->day + $this->copy()->startOfMonth()->dayOfWeek - 1) / static::DAYS_PER_WEEK);
```

As you can see `weekOfMonth` returns number `ceil(current month day \ 7)`. In your example `ceil(12\7) = 2`.

`weekNumberInMonth` was added in v1.23, baybe that should work for you?

Neither has nothing to do with ISO8601 standard.
