### ISSUE TITLE
modify() method resets timezones to UTC, causes issues

### ISSUE THREAD

**Issue by bensinclair** [briannesbitt/Carbon#930]
I opened a [Stackoverflow issue](https://stackoverflow.com/questions/43223825/carbon-timezone-issues) yesterday due to a strange timezone issue I was experiencing with Carbon.

Basically, if the timezone set by `date_default_timezone_set()` differs from the timezone I pass through to Carbon, it to modify the date correctly.

```php
date_default_timezone_set('UTC'); <---- This timezone differs from the one set by $tz

$tz = new DateTimeZone('Australia/Brisbane');

$start_date = \Carbon\Carbon::instance(new DateTime('2019-03-01 00:00:00', $tz));
$end_date = \Carbon\Carbon::instance(new DateTime('2021-03-21 23:59:00', $tz));

$current_date = $start_date->copy();

$x = 0;
while ($end_date->gte($current_date)) {
   echo $current_date->toDateTimeString() . "\n";
   $current_date->addMonth()->startOfMonth(); <--- This is the part that fails
   $x++;
   if ($x === 10)
       break;
}
```

Expected Output

> 2019-03-01 00:00:00
> 2019-04-01 00:00:00
> 2019-05-01 00:00:00
> 2019-06-01 00:00:00
> 2019-07-01 00:00:00
> 2019-08-01 00:00:00
> 2019-09-01 00:00:00
> 2019-10-01 00:00:00
> 2019-11-01 00:00:00
> 2019-12-01 00:00:00

Actual Output

> 2019-03-01 00:00:00
> 2019-03-01 00:00:00
> 2019-03-01 00:00:00
> 2019-03-01 00:00:00
> 2019-03-01 00:00:00
> 2019-03-01 00:00:00
> 2019-03-01 00:00:00
> 2019-03-01 00:00:00
> 2019-03-01 00:00:00
> 2019-03-01 00:00:00

As pointed out by the kind person who found a workaround...

> The following is the method that `addMonth()` uses to increments the current date by one month
> 
> ```php
> /**
>  * Consider the timezone when modifying the instance.
>  *
>  * @param string $modify
>  *
>  * @return static
>  */
> public function modify($modify)
> {
>     if ($this->local) {
>         return parent::modify($modify);
>     }
> 
>     $timezone = $this->getTimezone();
>     $this->setTimezone('UTC');
>     $instance = parent::modify($modify);
>     $this->setTimezone($timezone);
> 
>     return $instance;
> }
> ```
>
> As you can see, this function resets the timezone to `UTC` before modifying your date, then modifys the date, and finally convert it into the given timezone - in this context it is a `Australia/Brisbane`.
> 
> Actually It's not clear enough why Carbon authors resets the timezone to UTC in that function but this is the cause of your issue.

Why does Carbon change the timezone to `UTC` to modify? Shouldn't it remain in the current timezone set by the developer?

**Comment by Ovsyanka** [comment]
Pay your attention on #884

**Comment by bensinclair** [comment]
Ah yes thank you! Hopefully they merge it in soon :)

**Comment by Ovsyanka** [comment]
Actially i lost my hope few weeks ago =/ So, maybe, you shouldnt count on this.

**Comment by bensinclair** [comment]
Our workaround is fine for now but would like to see it merged. I've commented on your PR so that might remind them to relook :/

`$current_date->add(new \DateTimeinterval('P1M'))->startOfMonth();`

**Comment by agemmell** [comment]
+1 to this.  Just updated from 1.21.0 to 1.22.1 (via the Laravel dependency) and my tests failed immediately.

When I use xdebug to step through I can clearly see that in 1.22.1, the new Carbon->modify() function is messing up the time when it converts to UTC and then back to my timezone ("-07:00" or "America/Los_Angeles").  Oddly the initial timezone change to UTC did NOT change the time, however the change back to the original timezone ("-07:00") DOES change the time!  

I don't understand why it would only change time in one direction but that's why it's messing up my datetimes.

**Comment by Glavic** [comment]
This issue will be resolved in PR https://github.com/briannesbitt/Carbon/pull/1070
