### ISSUE TITLE
diffForHumans - Abbreviated dates?

### ISSUE THREAD

**Issue by zaritzki** [briannesbitt/Carbon#937]
Hi Brian, 

On this example..
Carbon::parse($date)->diffForHumans();

I'm looking for '2 hrs' instead of ' 2 hours ago'

having diffForHumans(null, true) will removed ago.. 
how about, I want to Abbreviate the dates?

ex:
minute to min
minutes to mins

hour to hr
hours to hrs

on so..

Thank you!

**Comment by ArmenGabrielyan16** [comment]
You could get '2h' with `Carbon::parse($date)->diffForHumans(null, true, true)`. However, 'hr' or 'hrs' versions are not currently supported (file: Carbon/src/Carbon/Lang/en.php)

**Comment by kylekatarnls** [comment]
Indeed you can use the short flag. I close this.
