### ISSUE TITLE
Format when the _toString method is called

### ISSUE THREAD

**Issue by mstephens** [briannesbitt/Carbon#938]
Hi guys

More of a question rather than a issue here, but thought I'd ask anyhow (after spending a fair bit of time debugging a problem). Great project by the way!

What was the reasoning for excluding the timezone from the `toString` method out of the box? _I know a workaround to this would be to override the `Carbon` class and modify `$toStringFormat`._

    const DEFAULT_TO_STRING_FORMAT = 'Y-m-d H:i:s';

For instance:

    $orig = Carbon::now('Antarctica/Davis');
    var_dump($orig);
    $dateStringOrig = (string)$orig;
    var_dump($dateStringOrig);
    
    $new = Carbon($dateStringOrig);
    var_dump($new);
    $dateStringNew = (string)$new;
    var_dump($datdateStringNew);

Produces:

    object(Carbon\Carbon)#680 (3) {
      ["date"]=>
      string(26) "2017-04-27 22:39:49.000000"
      ["timezone_type"]=>
      int(3)
      ["timezone"]=>
      string(16) "Antarctica/Davis"
    }
    string(19) "2017-04-27 22:39:49"
    object(Carbon\Carbon)#631 (3) {
      ["date"]=>
      string(26) "2017-04-27 22:39:49.000000"
      ["timezone_type"]=>
      int(3)
      ["timezone"]=>
      string(3) "UTC"
    }
    string(19) "2017-04-27 22:39:49"

If the `toString` were to be changed to use a format with the timezone, for instance RFC-3339 (`Y-m-d\TH:i:sP`):

    $orig = Carbon::now('Antarctica/Davis');
    var_dump($orig);
    var_dump($orig->toRfc3339String());
    
    $new = new Carbon($orig->toRfc3339String());
    var_dump($new);
    var_dump($new->toRfc3339String());

Produces:

    object(Carbon\Carbon)#680 (3) {
      ["date"]=>
      string(26) "2017-04-27 22:41:10.000000"
      ["timezone_type"]=>
      int(3)
      ["timezone"]=>
      string(16) "Antarctica/Davis"
    }
    string(25) "2017-04-27T22:41:10+07:00"
    object(Carbon\Carbon)#631 (3) {
      ["date"]=>
      string(26) "2017-04-27 22:41:10.000000"
      ["timezone_type"]=>
      int(1)
      ["timezone"]=>
      string(6) "+07:00"
    }
    string(25) "2017-04-27T22:41:10+07:00"

Cheers
Matt

**Comment by briannesbitt** [comment]
Typical usage I think doesn't require tz information so it was left out by default.  You can use the `Carbon::setToStringFormat()` method though to control your own default string format.  http://carbon.nesbot.com/docs/#api-formatting
