### ISSUE TITLE
Carbon::setTestNow() has no effect on weekday relative time creation

### ISSUE THREAD

**Issue by DfKimera** [briannesbitt/Carbon#940]
After setting the current date value with `setTestNow()`, dates created with weekday relative strings yield values based on actual current date instead of test value.

**Example:**
```
<?php
require("vendor/autoload.php");
use Carbon\Carbon;

Carbon::setTestNow("2017-01-01 12:00:00");

$correct = new Carbon("next sunday"); // yields 2017-01-08
$incorrect = new Carbon("sunday"); // yields 2017-04-30, should yield 2017-01-01
```

Tested with version 1.22.

Evidence below:
![image](https://cloud.githubusercontent.com/assets/581765/25562021/42e6e436-2d50-11e7-9769-83f13bd2151b.png)

**Comment by kylekatarnls** [comment]
Indeed, we should need exceptions for parse relative to now arguments. It would be relevant for the setTestNow purpose (testing).

It would be a big RegExp based on https://secure.php.net/manual/fr/datetime.formats.relative.php but it could be done.

**Comment by DfKimera** [comment]
@kylekatarnls Considering `strtotime()` takes a second `$now` argument, wouldn't it be possible to conditionally inject the value in `setTestNow` on the native relative time parser? Or does Carbon handle this differently?

I haven't yet poked under the hood to see how relative time is being handled in Carbon, so I might be overlooking something.

**Comment by DfKimera** [comment]
Okay, so digging deeper into the code, I see what you mean regarding the RegExp. Carbon identifies a relative string by a preset of keywords, and weekdays without any words such as "next" or "previous" fail to match the list.

I made a quick patch by extending `Carbon::$relativeKeywords` to include all weekdays, and the test passed. I'll prepare a pull request in a bit with this fix.
