### ISSUE TITLE
WeekOfYear method call on "2017-01-01" is 52!!!

### ISSUE THREAD

**Issue by c00p3r** [briannesbitt/Carbon#942]
WTF guys?
Maybe I'm not getting something here?... Please, explain
![1_009](https://cloud.githubusercontent.com/assets/5259532/25663800/4e0a23c2-3021-11e7-8cf8-05ad565c45b5.png)

**Comment by dereuromark** [comment]
That's absolutely correct. It is called week of year.

**Comment by c00p3r** [comment]
@dereuromark Could you explain why 1st of January is 52nd week of the year and not 1st week of the year?

**Comment by dereuromark** [comment]
I believe it can all easily be retrieved via google, e.g. https://en.wikipedia.org/wiki/ISO_week_date

**Comment by c00p3r** [comment]
Jeez, it's so complicated...
Sorry, thought it's a bug

**Comment by c00p3r** [comment]
The behavior of CArbon is a bit misleading here..
'Cause what I see in wiki is: 2010-01-01	translates into 2009-W53-5
But in my case for 2017-01-01 I get year: 2017, week: 52 instead of year: 2016, week: 52
In the end I got that I should never mix Year, Month, Day with Week of the Year....

**Comment by briannesbitt** [comment]
There are 2 getters to help you out `$carbon->year` and `$carbon->yearIso`.

The `year` is what you would expect.  The `yearIso` is `ISO-8601 week-numbering year. This has the same value as Y, except that if the ISO week number (W) belongs to the previous or next year, that year is used instead. (added in PHP 5.1.0)` and you can use that to work out any `weekOfYear` issues.

**Comment by c00p3r** [comment]
@briannesbitt MANY HUGE THANKS! You saved my day!
btw `yearIso` method not mentioned in docs at http://carbon.nesbot.com/

**Comment by briannesbitt** [comment]
Np. True ! I always just check the code myself ;)
