### ISSUE TITLE
formatLocalized - bad output for diacrytic characters

### ISSUE THREAD

**Issue by apsg** [briannesbitt/Carbon#943]
I'm using Carbon in Laravel to generate localized date labels in my project.

In my controller I use following code to generate the labels:

$today = Carbon::now();

    $labels[] = [
        'date' => $today->format('Y-m-d'),
        'label' => ('Dziś ('.$today->formatLocalized('%a, %e %b').')')
    ];
    $labels[] = [
        'date' => (clone $today )->addDays(1)->format('Y-m-d'),
        'label' => 'Jutro ('.(clone $today)->addDays(1)->formatLocalized('%a, %e %b').')'
    ];
    $labels[] = [
        'date' => (clone $today )->addDays(2)->format('Y-m-d'),
        'label' => (clone $today)->addDays(2)->formatLocalized('%a, %e %b')
    ];
    $labels[] = [
        'date' => (clone $today )->addDays(3)->format('Y-m-d'),
        'label' => (clone $today)->addDays(3)->formatLocalized('%a, %e %b')
    ];
    $labels[] = [
        'date' => (clone $today )->addDays(4)->format('Y-m-d'),
        'label' => (clone $today)->addDays(4)->formatLocalized('%a, %e %b')
    ];
And it works OK until there is any language-specific diacrytic sign. If I output the $labels with dd(...) this is what I get:

```
array:5 [▼
  0 => array:2 [▼
    "date" => "2017-04-27"
    "label" => "Dziś (czw, 27 kwi)"
  ]
  1 => array:2 [▼
    "date" => "2017-04-28"
    "label" => b"Jutro (pi±, 28 kwi)"
  ]
  2 => array:2 [▼
    "date" => "2017-04-29"
    "label" => "sob, 29 kwi"
  ]
  3 => array:2 [▼
    "date" => "2017-04-30"
    "label" => "nie, 30 kwi"
  ]
  4 => array:2 [▼
    "date" => "2017-05-01"
    "label" => "pon,  1 maj"
  ]
]
```
Notice strange label for second item:

`"label" => b"Jutro (pi±, 28 kwi)"`
correct label should be: `"Jutro (pią, 29 kwi)".`

Of course labels like that do not output correctly in Blade.

What is wrong? Is it something with coding or maybe I'm using the formatLocalized method wrong?

FYI: I have set locales in boot() method of my AppServiceProvider:

    setlocale(LC_TIME, 'pl_PL');
    \Carbon\Carbon::setLocale('pl');

**Comment by ricardobucho** [comment]
I was looking at Carbon's class file and found the fix.
Just do this below your setLocale carbon method.

\Carbon\Carbon::setUtf8(true);

**Comment by kylekatarnls** [comment]
Yep, it's explained in the doc: http://carbon.nesbot.com/docs/#api-localization, it's not Carbon specific, locales can be UTF-8 or not.

**Comment by hoRacy** [comment]
@apsg  - Hi, do you found a workaround? I have the same problem [polski język, trudny język ;)]

**Comment by kylekatarnls** [comment]
Hi @hoRacy, this internationalization mode has been dropped in Carbon 2, translations are now internal and so all UTF-8. Please upgrade to Carbon 2 (See install: https://carbon.nesbot.com/#gettingstarted and migration guide: https://carbon.nesbot.com/docs/#api-carbon-2) and use the new `isoFormat` as in the documentation rather than `formatLocalized` that relies on language packages installed and so can produce inconsistent results depending on the machine/hosting settings and packages.
