### ISSUE TITLE
Incorrect weekOfMonth

### ISSUE THREAD

**Issue by smokehill** [briannesbitt/Carbon#949]
I want to get properly number of week according to current day, but It seems to me that **Carbon** counts **weekOfMonth** independently of calendar order of day.

My code example:
```php
$date = Carbon::createFromFormat('Y-m-d', '2017-02-13', 'Europe/Moscow');
return $date->weekOfMonth;
```
I expect that week number will be **3**, but the result is **2**.
Can sombody explane these issue?

**Comment by Vendin** [comment]
@smokehill, such correct behavior in your opinion ?
#969

**Comment by smokehill** [comment]
@Vendin, yes. Now behavior as i expect.

**Comment by kylekatarnls** [comment]
Now available as ->weekNumberInMonth.
