### ISSUE TITLE
->addMonth() fails on 2017-05-01 when using Australia/Sydney timezone

### ISSUE THREAD

**Issue by SonarSoftware** [briannesbitt/Carbon#958]
=> Carbon\Carbon {#3260
+"date": "2017-05-01 00:00:00.000000",
+"timezone_type": 3,
+"timezone": "Australia/Sydney",
}
>>> $carbon->addMonth();
=> Carbon\Carbon {#3260
+"date": "2017-05-31 00:00:00.000000",
+"timezone_type": 3,
+"timezone": "Australia/Sydney",
}

=> Carbon\Carbon {#3247
+"date": "2017-05-01 00:00:00.000000",
+"timezone_type": 3,
+"timezone": "America/Chicago",
}
>>> $carbon->addMonth();
=> Carbon\Carbon {#3247
+"date": "2017-06-01 00:00:00.000000",
+"timezone_type": 3,
+"timezone": "America/Chicago",
}

Steps to recreate:

Instantiate Carbon with `new Carbon\Carbon("2017-05-01","Australia/Sydney");`
Add a month with `->addMonth()`
I would expect to get 2017-06-01, but I get 2017-05-31.

Now do the same with America/Chicago, and you will get the expected behavior.

**Comment by SonarSoftware** [comment]
As a note, I did see some other issues state to use 'addMonthNoOverflow()' but this just returns the same date.

=> Carbon\Carbon {#3284
+"date": "2017-07-01 00:00:00.000000",
+"timezone_type": 3,
+"timezone": "Australia/Sydney",
}
>>> $carbon->addMonthNoOverflow();
=> Carbon\Carbon {#3284
+"date": "2017-07-01 00:00:00.000000",
+"timezone_type": 3,
+"timezone": "Australia/Sydney",
}

**Comment by lucasmichot** [comment]
See `\Carbon\Carbon::addMonthNoOverflow` and `\Carbon\Carbon::useMonthsOverflow`

**Comment by SonarSoftware** [comment]
Neither of these seem to help, can you explain how this solves it?

>>> $carbon = new Carbon\Carbon("2017-05-01","Australia/Sydney");
=> Carbon\Carbon {#3297
     +"date": "2017-05-01 00:00:00.000000",
     +"timezone_type": 3,
     +"timezone": "Australia/Sydney",
   }
>>> $carbon->AddMonthsNoOverflow();
PHP warning:  Missing argument 1 for Carbon\Carbon::addMonthsNoOverflow(), called in /mnt/hgfs/Sonar/sonar/vendor/psy/psysh/src/Psy/ExecutionLoop/Loop.php(79) : eval()'d code on line 1 and defined in /mnt/hgfs/Sonar/sonar/vendor/nesbot/carbon/src/Carbon/Carbon.php on line 2203
>>> $carbon->AddMonthNoOverflow();
=> Carbon\Carbon {#3297
     +"date": "2017-05-01 00:00:00.000000",
     +"timezone_type": 3,
     +"timezone": "Australia/Sydney",
   }
>>>



>>> $carbon = new Carbon\Carbon("2017-05-01","Australia/Sydney");
=> Carbon\Carbon {#3301
     +"date": "2017-05-01 00:00:00.000000",
     +"timezone_type": 3,
     +"timezone": "Australia/Sydney",
   }
>>> $carbon->useMonthsOverflow(false);
=> null
>>> $carbon->addMonth();
=> Carbon\Carbon {#3301
     +"date": "2017-05-01 00:00:00.000000",
     +"timezone_type": 3,
     +"timezone": "Australia/Sydney",
   }
>>>

>>> $carbon = new Carbon\Carbon("2017-05-01","Australia/Sydney");
=> Carbon\Carbon {#3302
     +"date": "2017-05-01 00:00:00.000000",
     +"timezone_type": 3,
     +"timezone": "Australia/Sydney",
   }
>>> $carbon->useMonthsOverflow(true);
=> null
>>> $carbon->addMonth();
=> Carbon\Carbon {#3302
     +"date": "2017-05-31 00:00:00.000000",
     +"timezone_type": 3,
     +"timezone": "Australia/Sydney",
   }
>>>


What combination of these settings should I use to give me 2017-06-01?

**Comment by lucasmichot** [comment]
Do you switch to DST ?

**Comment by SonarSoftware** [comment]
The only commands I'm running are the ones above - do I need to calculate when DST applies externally and set that each time?
