### ISSUE TITLE
Error when try format() on var is null

### ISSUE THREAD

**Issue by DarkCobalt** [briannesbitt/Carbon#962]
Often i have variable date when can be null and when i use on that variable format then have error is variable can't be null. Not better add condition in format() function 
if(!is_null($variable)){
  return $format_date.
}else{
  return null;
}
My all system crash bc try format date =.=

**Comment by Glavic** [comment]
Sorry for late reply.

I must say I don't understand what exactly what you are saying.
You can specify `null` parameter to `format()` method, that will return empty string, not an error. See here: https://eval.in/957684

If I misunderstood, please be more specific.

**Comment by kylekatarnls** [comment]
If you do `null->format()` any code of Carbon isn't even triggered, so you must go on you own with a custom function:

```php
function format_carbon_date($date, $format)
{
  return $date ? $date->format($format) : null;
}
```
