### ISSUE TITLE
Year starts on Sunday to Saturday, 2017-12-31 weekOfYear does not return 53

### ISSUE THREAD

**Issue by cuautorres** [briannesbitt/Carbon#966]
If I set Carbon::setWeekStartsAt(Carbon :: SUNDAY) and Carbon::setWeekEndsAt(Carbon :: SATURDAY), when Carbon::parse('2017-12-31')->weekOfYear should return 53, but return 52

**Comment by Glavic** [comment]
Hi, sorry for late reply.
Those 2 methods have nothing to do with `weekOfYear`, since latest only returns `->format('W')`, where `W` is `ISO-8601 week number of year, weeks starting on Monday`.
If you have any more questions, comment bellow.
