### ISSUE TITLE
Standard and Daylight time showing same offset for Mountain

### ISSUE THREAD

**Issue by mMerlin** [briannesbitt/Carbon#968]
For an example I have, Carbon::parse()->format() is correctly converting to -0600 MDT (Mountain Daylight Time) when using -6 for the timezone parameter.  However, using 'MDT' for the timezone parameter gives -0700 MDT.  Using 'MST' gives -0700 MST.  Daylight and Standard times can not both be -0700.
https://www.timeanddate.com/time/zones/mdt
https://www.timeanddate.com/time/zones/mst
The 'MDT' case should be -0600 MDT.  Or at least -0600.

From Carbon-1.22.1-0-g7cdf42c.zip.  At least composer.lock (in Laravel) says
"url": "https://api.github.com/repos/briannesbitt/Carbon/zipball/7cdf42c0b1cc763ab7e4c33c47a24e27c66bfccc"

```php
$datestr = "2016-06-15";
dd([$datestr,
  Carbon::parse($datestr, -6)->format('D, Y-m-d H:i:s O (T)'),
  Carbon::parse($datestr, 'MDT')->format('D, Y-m-d H:i:s O (T)'),
  Carbon::parse($datestr, 'MST')->format('D, Y-m-d H:i:s O (T)'),
]);
```
```
array:4 [▼
  0 => "2016-06-15"
  1 => "Wed, 2016-06-15 00:00:00 -0600 (MDT)"
  2 => "Wed, 2016-06-15 00:00:00 -0700 (MDT)"
  3 => "Wed, 2016-06-15 00:00:00 -0700 (MST)"
]
```

**Comment by kylekatarnls** [comment]
Hi, this is not a Carbon bug, pure PHP gives the same result: https://3v4l.org/QJWT3, you should open a ticket in the PHP tracker.
