### ISSUE TITLE
Include ISO Duration

### ISSUE THREAD

**Issue by bretterer** [briannesbitt/Carbon#971]
Hi @briannesbitt ,

I have created a package for working with ISO Durations.
https://github.com/bretterer/iso_duration_converter

I would love to have this kind of thing included in Carbon, as it is a pretty common time format.  Would you entertain a PR that basically takes my library and puts it into the Carbon library?

-Brian

**Comment by Glavic** [comment]
Hi!
Your project seem to be unmaintained? Tests are not working :(

**Comment by bretterer** [comment]
@Glavic I will check... there is not much there to maintain.   I will update travis to test weekly with nightly and newer versions of PHP later today!

**Comment by kylekatarnls** [comment]
Hi, I'm interested, could you do a PR that would enable it this way on CarbonInterval (using the actual spec method)?

```php
CarbonInterval::parse('PT8S')->asSeconds(); // Returns 8
CarbonInterval::parse('PT5M')->asSeconds() // Returns 300
CarbonInterval::parse('PT20H')->asSeconds(); // Returns 72000
CarbonInterval::parse('PT6M4S')->asSeconds(); // Returns 364

CarbonInterval::compose(8)->spec(); // Returns PT8S
CarbonInterval::compose(300)->spec(); // Returns PT5M
CarbonInterval::compose(7200)->spec(); // Returns PT20H
CarbonInterval::compose(364)->spec(); //Returns PT6M4S

CarbonInterval::parse('P5W')->asSeconds(); // Returns 3024000
// To Returns Weeks, The second argument should be true
CarbonInterval::compose(3024000)->weekSpec(); // Returns P5W
CarbonInterval::compose(3024000)->spec(); // Returns P35D
```

**Comment by bretterer** [comment]
I got pulled away from working on this, but I will work on it soon

**Comment by kylekatarnls** [comment]
Note: our current way to construct CarbonInterval would be better if consistent with DateInterval, it would be nice if first CarbonInterval get a non-numeric string as first argument to call the parent::__construct with it, so CarbonInterval::parse could simply call `new static()`.

**Comment by kylekatarnls** [comment]
I close this for the moment, but you can propose a PR for this. I would be glad to continue the discussion on it.

**Comment by bretterer** [comment]
Thanks @kylekatarnls ... when I get a bit of my time back in April, I will open up a PR for this
