### ISSUE TITLE
isSame* methods should take DateTime instead of Carbon as argument

### ISSUE THREAD

**Issue by pzaj2** [briannesbitt/Carbon#974]
I believe that
`isSame*` functions should accept `DateTime` instead of `Carbon`. There is no reason not to support this functionality, since it all goes down to `isSameAs` method which uses `format` method of `DateTime` class.

What do you think?

**Comment by Glavic** [comment]
Sorry for late reply.
Problem I see is only `isSameDay()` method, because it calls `->toDateString()` on given object, and `DateTime` doesn't have that method, so fatal error will aprear.
Could you do a PR for a fix?

**Comment by Glavic** [comment]
@pzaj2: did you mean something like this? => https://github.com/Glavic/Carbon/commit/cc7c98ed4306a256a0ce3ccb2ff749f3af30a0f9

Sorry for late reply :(

**Comment by pzaj2** [comment]
Haha, I have completely forgotten about this issue, but yes, that seems about right.

**Comment by Glavic** [comment]
I have opened a PR. We will see how people react to that. TY for the issue. Will close this now, since we have a PR.
