### ISSUE TITLE
ISO8601 Date retusn Atom Date format

### ISSUE THREAD

**Issue by autumndev** [briannesbitt/Carbon#976]
Hey,

I have upgraded our carbob instance and found some of our tests failing. They are failing as we are expecting a carbon ISO8601 string as per [docs](http://carbon.nesbot.com/docs/#api-commonformats):
```php
$dt->toIso8601String();   // 1975-12-25T14:15:16-0500
```

 but we are getting an ATOM string:
```php
$dt->toAtomString();      // 1975-12-25T14:15:16-05:00
```

looking through the code I can see the following:
```php
       /**
     * Format the instance as ATOM
     *
     * @return string
     */
    public function toAtomString()
    {
        return $this->format(static::ATOM);
    }
...
    /**
     * Format the instance as ISO8601
     *
     * @return string
     */
    public function toIso8601String()
    {
        return $this->toAtomString();
    }
```
My Question is why is the ISO8601 string just calling the Atom function? the extra ':' (colon) is breaking my tests and whilst a quick fix (use base format() function) I wish to understand why this has changed

**Comment by autumndev** [comment]
I just saw https://github.com/cakephp/chronos/pull/45 and https://github.com/briannesbitt/Carbon/issues/861

which explains the php constant is wrong. 

I would suggest docs update with explanation as docs show ISO8601 with php constant formatting, which is not true.

I had put a pull request in for the fix: https://github.com/briannesbitt/Carbon/pull/977

this can be excluded if required.

**Comment by autumndev** [comment]
also from what i can see [wiki](https://en.wikipedia.org/wiki/ISO_8601)

the iso format can be +1100 or +11:00

**Comment by autumndev** [comment]
ignore previous comment, w3 states it should be +1100:
https://www.w3.org/TR/NOTE-datetime

**Comment by acorncom** [comment]
@autumndev I must be reading something different here ...

>    Complete date plus hours and minutes:
          YYYY-MM-DDThh:mmTZD (eg 1997-07-16T19:20+01:00)

>   Complete date plus hours, minutes and seconds:
      YYYY-MM-DDThh:mm:ssTZD (eg 1997-07-16T19:20:30+01:00)

> Complete date plus hours, minutes, seconds and a decimal fraction of a
second
      YYYY-MM-DDThh:mm:ss.sTZD (eg 1997-07-16T19:20:30.45+01:00)

Looks like it should be `+01:00`?

**Comment by autumndev** [comment]
@acorncom you are correct, believe i got mixed up there, the correct format is the format returned by the toAtomString function. 

but still the documentation states: 

> echo $dt->toAtomString();      // 1975-12-25T14:15:16-05:00
> echo $dt->toIso8601String();   // 1975-12-25T14:15:16-0500


which is wrong as the toIso8601String returns the atom formatted string as per my previous comment - believe the docs need updating to reflect this.

**Comment by aalaap** [comment]
I've worked around this by using the built-in PHP DateTime format

>echo $dt->format(\DateTime::ISO8601); // 1975-12-25T14:15:16-0500

**Comment by kylekatarnls** [comment]
Hi, I close this to continue the discussion on #1042
