### ISSUE TITLE
Travis CI - Bug on PHP:hhvm

### ISSUE THREAD

**Issue by MarekAdamicky** [briannesbitt/Carbon#982]
Hi, I have extended and corrected the Slovak language file **sk.php**. But my pull request has 1 failing and 3 successful checks. Codecov/project is 98.65%, because the request throws a bug on PHP:hhvm.
[github.com/briannesbitt/Carbon/pull/975](https://github.com/briannesbitt/Carbon/pull/975)

Does anyone know how to fix it?

I also created **SkTest.php**. The check failed.
[SkTest.php for new sk.php](https://github.com/MarekAdamicky/Carbon/blob/9145a20d6c82d4e3dc00d3fb2799b8635adebc13/tests/Localization/SkTest.php)

It works only for the old sk.php file, but PHP:hhvm failed again.
[SkTest.php for old sk.php](https://github.com/MarekAdamicky/Carbon/blob/208bb9a6a09623e3cce3637e32348cbb67f0233c/tests/Localization/SkTest.php)

**Comment by kylekatarnls** [comment]
I close since now it pass.
