### ISSUE TITLE
last day, month set

### ISSUE THREAD

**Issue by spacerangerniko** [briannesbitt/Carbon#986]
create object with **last day** of the month. sor, bad english. bug in screenshot.
![image](https://user-images.githubusercontent.com/16322716/28869490-88adb31c-7785-11e7-9f80-d1d406b08e02.png)

**Comment by briannesbitt** [comment]
When you set the month to a 6 the internal date would have been 2017-06-31 which doesn't exist so it rolls over to 2017-07-01.  Then you set the date to 29 so 2017-07-29 it is.

Set the date to 29 then the month to 6 and you'll be fine.

**Comment by spacerangerniko** [comment]
ok, thx
