### ISSUE TITLE
String Formatting not based on Locale

### ISSUE THREAD

**Issue by biwerr** [briannesbitt/Carbon#987]
For e. g. Carbon::toDateString() is not based on Locale.

It doesn't matter which language is set, Carbon use the same Format for every language. 

The same applies to toFormattedDateString(), toTimeString(), toDateTimeString() toDayDateTimeString()

**Comment by briannesbitt** [comment]
Use formatLocalized() for localization. http://carbon.nesbot.com/docs/#api-localization
