### ISSUE TITLE
Diff in calendar days

### ISSUE THREAD

**Issue by xaviqv** [briannesbitt/Carbon#990]
I want to get difference in calendar days. I want to spot dates that correspond to today, yesterday and tomorrow with relative numbers (0, -1, 1).

Here are some basic tests:

`\Carbon\Carbon::now() // Out: 2017-08-08 09:16 ...`

// diffInDays()
```
\Carbon\Carbon::now()->diffInDays(\Carbon\Carbon::now()->addHour(1)) // output: 0
\Carbon\Carbon::now()->diffInDays(\Carbon\Carbon::now()->tomorrow()) // output: 0
\Carbon\Carbon::now()->diffInDays(\Carbon\Carbon::now()->addHour(23)) // output: 0
\Carbon\Carbon::now()->diffInDays(\Carbon\Carbon::now()->addHour(25)) // output: 1
```

// diffInWeekDays()
```
\Carbon\Carbon::now()->diffInWeekDays(\Carbon\Carbon::now()->addHour(1)) // output: 1
\Carbon\Carbon::now()->diffInWeekDays(\Carbon\Carbon::now()->tomorrow()) // output: 1
\Carbon\Carbon::now()->diffInWeekDays(\Carbon\Carbon::now()->addHour(23)) // output: 1
\Carbon\Carbon::now()->diffInWeekDays(\Carbon\Carbon::now()->addHour(25)) // output: 2
```

Both methods seem to count days by periods of 24 hrs. What I would like to get with "someMethod":
```
\Carbon\Carbon::now()->someMethod(\Carbon\Carbon::now()->addHour(1)) // output: 0
\Carbon\Carbon::now()->someMethod(\Carbon\Carbon::now()->tomorrow()) // output: 1
\Carbon\Carbon::now()->someMethod(\Carbon\Carbon::now()->addHour(23)) // output: 1
\Carbon\Carbon::now()->someMethod(\Carbon\Carbon::now()->addHour(25)) // output: 1
```

The most similar question I've located here is https://github.com/briannesbitt/Carbon/issues/830 , but there points directly to create new methods that suit this approach. Is there any way to get my needed output within Carbon?

**Comment by xaviqv** [comment]
I've found by myself the trick using Carbon methods. It seems to be all covered applying startOfDay() method on both dates, like the following:

`Carbon::now()->startOfDay()->diffInWeekDays(Carbon::parse($ticket->start_date)->startOfDay(), false)`

For anyone interested also in a pure PHP solution that outputs same results, check this:

`intval(floor((strtotime($ticket->start_date)-time()) / (60*60*24)))`

Anyway, is there any shortener method to get this with Carbon?

**Comment by kylekatarnls** [comment]
Hi, first, `now()->startOfDay()` is `today()` and if you pass a date to `Carbon::parse()` it should set to midnight automatically, so this should works just well:

```php
Carbon::today()->diffInWeekDays(Carbon::parse($ticket->start_date), false);
```

**Comment by xaviqv** [comment]
Thanks @kylekatarnls ! I'll keep that in mind!
