### ISSUE TITLE
[FEATURE] CarbonInterval from string

### ISSUE THREAD

**Issue by tflori** [briannesbitt/Carbon#997]
I like the format of Jira to define time worked. It's very easy and intuitive.

`1w 3d 4h 32m 23s` will become 1 week, 3 days, 4 hours, 32 minutes and 23 seconds. I know you can use php's `new DateInterval('P10DT4H32M23S')`. One thing: it's not readable and the other you have to device time and date with `T`.

Of course it's not very complicated but a lot of text to have it in every project:
```php
<?php
function interval($interval)
{
  $years = 0;
  $months = 0;
  $days = 0;
  $hours = 0;
  $minutes = 0;
  $seconds = 0;

  foreach (explode(' ', $interval) as $v) {
    switch (substr($v, -1)) {
      case 'y':
        $years += intval($v);
        break;
      case 'M':
        $months += intval($v);
        break;
      case 'w':
        $days += intval($v) * 7;
        break;
      case 'd':
        $days += intval($v);
        break;
      case 'h':
        $hours += intval($v);
        break;
      case 'm':
        $minutes += intval($v);
        break;
      case 's':
        $seconds += intval($v);
        break;
    }
  }

  return CarbonInterval::instance(new DateInterval(
    'P' . // Period
    $years . 'Y' .
    $months . 'M' .
    $days . 'D' . 
    'T' . // Time
    $hours . 'H' .
    $minutes . 'M' .
    $seconds . 'S'
  ));
}

**Comment by kylekatarnls** [comment]
I like it :)

**Comment by imbrish** [comment]
Some time ago I wrote an extension of `Carbon\CarbonInterval` with similar functionality. It comes with a few more methods like cascading the interval (45 days becomes 1 month 15 days), converting it to period or to human readable string in current locale. 

You can take a look at it here https://gist.github.com/imbrish/fb09b3328c498873818b9ff0b56ea423.

If you think it will be an useful addition to the core Carbon i can draft a pull request with the whole ting of some parts of it.

**Comment by kylekatarnls** [comment]
Cascading to months is a rounding maybe not expected. I personally would prefer to get 6 weeks and 3 days for 45 days.

**Comment by imbrish** [comment]
Cascading is optional and can be done just when desired. You're right that what units we cascade to depends on use case/preferences. Adding some flexibility shouldn't be difficult though, it's just matter of an extra argument with some kind of unit whitelist.

I decided to solve the month/minute issue by making units case sensitive, uppercase for "date" and lowercase for "time" part: Y(ear), M(onth), D(ay) and h(our), m(inute), s(econd).

**Comment by kylekatarnls** [comment]
@tflori @imbrish Is one of you interested in proposing a PR for this? I have many things assigned and I would be glad to share.

**Comment by tflori** [comment]
I can prepare a PR. I will have to read the guidelines for contributing to this repo and therefore I'm not sure how long it might take.. but if @imbrish want I'm fine too

**Comment by kylekatarnls** [comment]
Thanks!

**Comment by imbrish** [comment]
@tflori we can collaborate on that one, especially that I like the way you tackled it, switch statement looks just way cleaner. I'll have some time in the afternoon so I can start a pull request and draft some preliminary code.

**Comment by imbrish** [comment]
Or should we split it into multiple PRs, which way do you like it @kylekatarnls?

**Comment by kylekatarnls** [comment]
@imbrish if you want you can fork Carbon then add the https://github.com/tflori/Carbon.git to your remotes. `git remote add tflori https://github.com/tflori/Carbon.git` then copy the branch:
`git checkout -b tflori-feature-interval-from-string tflori/feature-interval-from-string`
Then push it in your own origin:
`git push -u tflori-feature-interval-from-string origin/tflori-feature-interval-from-string`
Then you can code, add commits, push them and send a pull-request that will contain both @tflori commits and yours.

I close this for now, let's continue the discussion on #1199
