### ISSUE TITLE
Is this package abandoned? 

### ISSUE THREAD

**Issue by jycr753** [briannesbitt/Carbon#998]
We still waiting for the https://github.com/briannesbitt/Carbon/pull/673 to be merge, or make a new release... if this package has been abandoned please mark it as so. to @taylorotwell can add another dependency to laravel that is actually being maintained and updated more regular

https://en.wikipedia.org/wiki/Abandonware

**Comment by lucasmichot** [comment]
@jycr753, it is not abandoned.

https://github.com/briannesbitt/Carbon/pull/673 would imply that we get rid of PHP 5.3, which we don't want.

Carbon is not solely developed for laravel users.

If you feel like some like using functions which are not available yet, please use `\Illuminate\Support\Carbon` which also support Macros and Mixins in Laravel 5.5.

If you feel like using ImmutableDateTime, https://github.com/cakephp/chronos is also a good alternative.

**Comment by jycr753** [comment]
okay, so how would you @lucasmichot implemented that from the PR in laravel with the current Carbon version?

**Comment by kylekatarnls** [comment]
JSON serializable yet available in Laravel `\Illuminate\Support\Carbon` and will be available in Carbon 1.26.
